import {describe,expect,test} from 'bun:test'
import fixtures from '../../../../docs/research/m74-accounting-fixtures.json'
import {M74_METHOD,type M74AuthorityInput} from '../../../../packages/neuvetra-database/src/m74-contract'
import {createM74Authority} from './m74-authority'

const id='11111111-1111-4111-8111-111111111111',hash='1'.repeat(64)
const base:Omit<M74AuthorityInput,'quantityGallons'|'distanceMiles'>={binding:{coverageVersionId:id,coverageVersionSha256:hash,entityId:id,facilityId:id,sourceId:id,boundaryDecisionId:id},period:{start:'2025-01-01',endExclusive:'2026-01-01'},vehicle:{assetId:'TRUCK-001',vehicleClass:'Medium- and Heavy-Duty Vehicles',classificationBasis:'Synthetic registration identifies the bounded heavy-duty class.',modelYear:2015,fuel:'Fossil Diesel',controlBasis:'owned_operational_control_full_year'},quantityUnit:'US_gallon',distanceUnit:'vehicle_mile',fuelStatementSha256:'2'.repeat(64),mileageStatementSha256:'3'.repeat(64)}
const authority=createM74Authority()

describe('M74 Decimal authority',()=>{
 test('matches independently derived positive, boundary, maximum and half-even fixtures',async()=>{for(const item of fixtures.cases){const result=await authority.calculate({...base,quantityGallons:item.quantityGallons,distanceMiles:item.distanceMiles});expect(result.method).toEqual(M74_METHOD);expect(result.gasResults.co2.mass).toBe(item.co2Kg);expect(result.gasResults.ch4.mass).toBe(item.ch4Kg);expect(result.gasResults.n2o.mass).toBe(item.n2oKg);expect(result.gasResults.ch4.co2e).toBe(item.ch4KgCo2e);expect(result.gasResults.n2o.co2e).toBe(item.n2oKgCo2e);expect(result.total.unrounded).toBe(item.totalKgCo2eExact);expect(result.total.display).toBe(item.totalKgCo2eDisplay)}})
 test('keeps fuel CO2 and mileage gases independent',async()=>{const positive=fixtures.cases.find(item=>item.id==='positive')!,gallons=fixtures.cases.find(item=>item.id==='gallons_only_correction')!,miles=fixtures.cases.find(item=>item.id==='miles_only_correction')!;const a=await authority.calculate({...base,quantityGallons:positive.quantityGallons,distanceMiles:positive.distanceMiles}),b=await authority.calculate({...base,quantityGallons:gallons.quantityGallons,distanceMiles:gallons.distanceMiles}),c=await authority.calculate({...base,quantityGallons:miles.quantityGallons,distanceMiles:miles.distanceMiles});expect(b.gasResults.co2.mass).not.toBe(a.gasResults.co2.mass);expect(b.gasResults.ch4).toEqual(a.gasResults.ch4);expect(b.gasResults.n2o).toEqual(a.gasResults.n2o);expect(c.gasResults.co2).toEqual(a.gasResults.co2);expect(c.gasResults.ch4.mass).not.toBe(a.gasResults.ch4.mass);expect(c.gasResults.n2o.mass).not.toBe(a.gasResults.n2o.mass);await authority.replayBatch([a,b,c])})
 test('refuses unsupported units, raw factor tails and replay tampering',async()=>{await expect(authority.calculate({...base,quantityGallons:'1.000',distanceMiles:'1.000',quantityUnit:'litre' as 'US_gallon'})).rejects.toThrow('unavailable');const record=await authority.calculate({...base,quantityGallons:'1.000',distanceMiles:'1.000'});await expect(authority.replayBatch([{...record,total:{...record.total,unrounded:'10.210000000000001'}}])).rejects.toThrow('unavailable')})
})
