export const env = {
  DATABASE_URL: Bun.env.DATABASE_URL!,
  SUPABASE_URL: Bun.env.SUPABASE_URL!,
  SUPABASE_SERVICE_ROLE_KEY: Bun.env.SUPABASE_SERVICE_ROLE_KEY!,
  ANTHROPIC_API_KEY: Bun.env.ANTHROPIC_API_KEY!,
  PORT: Number(Bun.env.PORT ?? 3000),
}
