create table neuvetra.inventory_draft_reports (
 id uuid primary key, company_id uuid not null, annual_inventory_version_id uuid not null, evidence_pack_id uuid not null,
 profile text not null check(profile='neuvetra.synthetic.inventory-draft-report.v1'), inventory_snapshot_sha256 text not null check(inventory_snapshot_sha256~'^[0-9a-f]{64}$'),
 source_archive_sha256 text not null check(source_archive_sha256~'^[0-9a-f]{64}$'), source_manifest_sha256 text not null check(source_manifest_sha256~'^[0-9a-f]{64}$'), source_lineage_root_sha256 text not null check(source_lineage_root_sha256~'^[0-9a-f]{64}$'),
 report_bytes bytea not null, report_sha256 text not null check(report_sha256~'^[0-9a-f]{64}$'), report_byte_length integer not null check(report_byte_length between 1 and 65536),
 idempotency_key uuid not null, operation_fingerprint text not null check(operation_fingerprint~'^[0-9a-f]{64}$'), created_by uuid not null references auth.users(id), created_at timestamptz not null default now(),
 unique(id,company_id),unique(company_id,annual_inventory_version_id,profile),unique(company_id,idempotency_key),foreign key(annual_inventory_version_id,company_id) references neuvetra.annual_inventory_versions(id,company_id),foreign key(evidence_pack_id,company_id) references neuvetra.inventory_evidence_packs(id,company_id)
);
create table neuvetra.inventory_draft_report_audit_log(id uuid primary key,company_id uuid not null references neuvetra.companies(id) on delete cascade,report_id uuid not null,actor_user_id uuid not null references auth.users(id),event_type text not null check(event_type='inventory_draft_report.created'),event_meta jsonb not null,created_at timestamptz not null default now(),unique(company_id,report_id),foreign key(report_id,company_id) references neuvetra.inventory_draft_reports(id,company_id));
alter table neuvetra.inventory_draft_reports enable row level security;alter table neuvetra.inventory_draft_reports force row level security;alter table neuvetra.inventory_draft_report_audit_log enable row level security;alter table neuvetra.inventory_draft_report_audit_log force row level security;
create policy inventory_report_member_select on neuvetra.inventory_draft_reports for select to authenticated using(neuvetra.is_company_member(company_id));create policy inventory_report_audit_member_select on neuvetra.inventory_draft_report_audit_log for select to authenticated using(neuvetra.is_company_member(company_id));
create trigger inventory_report_immutable before update or delete on neuvetra.inventory_draft_reports for each row execute function neuvetra.reject_inventory_history_mutation();create trigger inventory_report_audit_immutable before update or delete on neuvetra.inventory_draft_report_audit_log for each row execute function neuvetra.reject_inventory_history_mutation();
create function neuvetra.create_inventory_draft_report(target_company_id uuid,target_inventory_id uuid,target_pack_id uuid,requested_report_id uuid,requested_audit_id uuid,expected_inventory_snapshot_sha256 text,expected_archive_sha256 text,request_report_bytes bytea,request_report_sha256 text,request_report_byte_length integer,request_manifest_sha256 text,request_lineage_sha256 text,request_idempotency_key uuid,request_operation_fingerprint text) returns uuid language plpgsql security definer set search_path=neuvetra,pg_temp as $$
declare actor_id uuid:=neuvetra.current_user_id();stored_id uuid;anchored record;
begin
 if actor_id is null or not neuvetra.can_manage_company(target_company_id) then raise exception 'workspace not found' using errcode='42501';end if;
 select i.snapshot_sha256,p.archive_sha256,p.manifest_sha256,p.lineage_root_sha256 into anchored from neuvetra.annual_inventory_versions i join neuvetra.inventory_evidence_packs p on p.company_id=i.company_id and p.annual_inventory_version_id=i.id where i.company_id=target_company_id and i.id=target_inventory_id and p.id=target_pack_id for update of i;
 if anchored.snapshot_sha256 is distinct from expected_inventory_snapshot_sha256 or anchored.archive_sha256 is distinct from expected_archive_sha256 or anchored.manifest_sha256 is distinct from request_manifest_sha256 or anchored.lineage_root_sha256 is distinct from request_lineage_sha256 or octet_length(request_report_bytes) is distinct from request_report_byte_length or encode(sha256(request_report_bytes),'hex') is distinct from request_report_sha256 then raise exception 'verified evidence pack required' using errcode='22023';end if;
 select id into stored_id from neuvetra.inventory_draft_reports where company_id=target_company_id and idempotency_key=request_idempotency_key;if stored_id is not null then if not exists(select 1 from neuvetra.inventory_draft_reports where id=stored_id and operation_fingerprint=request_operation_fingerprint)then raise exception 'draft report request conflicts' using errcode='23505';end if;return stored_id;end if;
 insert into neuvetra.inventory_draft_reports values(requested_report_id,target_company_id,target_inventory_id,target_pack_id,'neuvetra.synthetic.inventory-draft-report.v1',expected_inventory_snapshot_sha256,expected_archive_sha256,request_manifest_sha256,request_lineage_sha256,request_report_bytes,request_report_sha256,request_report_byte_length,request_idempotency_key,request_operation_fingerprint,actor_id,now()) on conflict(company_id,annual_inventory_version_id,profile) do nothing returning id into stored_id;
 if stored_id is null then select id into stored_id from neuvetra.inventory_draft_reports where company_id=target_company_id and annual_inventory_version_id=target_inventory_id and source_archive_sha256=expected_archive_sha256 and report_sha256=request_report_sha256;end if;if stored_id is null then raise exception 'draft report request conflicts' using errcode='23505';end if;
 insert into neuvetra.inventory_draft_report_audit_log values(requested_audit_id,target_company_id,stored_id,actor_id,'inventory_draft_report.created',jsonb_build_object('evidence_pack_id',target_pack_id,'source_archive_sha256',expected_archive_sha256,'report_sha256',request_report_sha256),now()) on conflict(company_id,report_id)do nothing;return stored_id;
end$$;
revoke all on table neuvetra.inventory_draft_reports,neuvetra.inventory_draft_report_audit_log from public;revoke all on function neuvetra.create_inventory_draft_report(uuid,uuid,uuid,uuid,uuid,text,text,bytea,text,integer,text,text,uuid,text) from public,authenticated;grant select on neuvetra.inventory_draft_reports,neuvetra.inventory_draft_report_audit_log to authenticated;
