-- M73 additive source-scoped synthetic natural-gas workpapers. M42/M71 remain intact.
create table neuvetra.stationary_gas_heads(id uuid primary key,company_id uuid not null references neuvetra.companies(id),source_id uuid not null,version_id uuid,revision integer not null default 0,meter_key text,reference_key text,unique(id,company_id),unique(company_id,source_id),unique(company_id,meter_key),unique(company_id,reference_key));
create table neuvetra.stationary_gas_statements(id uuid primary key,company_id uuid not null references neuvetra.companies(id),payload jsonb not null,statement_sha256 text not null,statement_text text not null,unique(id,company_id));
create table neuvetra.stationary_gas_versions(id uuid primary key,company_id uuid not null,worksheet_id uuid not null,version integer not null,previous_version_id uuid,coverage_version_id uuid not null,statement_id uuid,quantity_mmbtu numeric(15,3),payload jsonb not null,input_sha256 text not null,content_sha256 text not null,version_sha256 text not null,created_by uuid not null references auth.users(id),created_at timestamptz not null,export_text text not null,unique(id,company_id),unique(company_id,worksheet_id,version),foreign key(worksheet_id,company_id) references neuvetra.stationary_gas_heads(id,company_id),foreign key(previous_version_id,company_id) references neuvetra.stationary_gas_versions(id,company_id),foreign key(coverage_version_id,company_id) references neuvetra.corporate_inventory_versions(id,company_id),foreign key(statement_id,company_id) references neuvetra.stationary_gas_statements(id,company_id));
alter table neuvetra.stationary_gas_heads add foreign key(version_id,company_id) references neuvetra.stationary_gas_versions(id,company_id);
create table neuvetra.stationary_gas_reviews(id uuid primary key,company_id uuid not null,version_id uuid not null,payload jsonb not null,decision_sha256 text not null,reviewed_by uuid not null references auth.users(id),reviewed_at timestamptz not null,unique(id,company_id),unique(company_id,version_id),foreign key(version_id,company_id) references neuvetra.stationary_gas_versions(id,company_id));
create table neuvetra.stationary_gas_reports(id uuid primary key,company_id uuid not null,worksheet_id uuid not null,version_id uuid not null,decision_id uuid,payload jsonb not null,report_sha256 text not null,created_by uuid not null references auth.users(id),created_at timestamptz not null,unique(id,company_id),foreign key(worksheet_id,company_id) references neuvetra.stationary_gas_heads(id,company_id),foreign key(version_id,company_id) references neuvetra.stationary_gas_versions(id,company_id),foreign key(decision_id,company_id) references neuvetra.stationary_gas_reviews(id,company_id));
create unique index m73_report_state on neuvetra.stationary_gas_reports(company_id,version_id,coalesce(decision_id,'00000000-0000-0000-0000-000000000000'::uuid));
create table neuvetra.stationary_gas_requests(company_id uuid not null references neuvetra.companies(id),idempotency_key uuid not null,actor_id uuid not null references auth.users(id),kind text not null check(kind in('save','review','report')),fingerprint text not null,record_id uuid not null,primary key(company_id,idempotency_key));
create table neuvetra.stationary_gas_audit(id uuid primary key,company_id uuid not null references neuvetra.companies(id),record_id uuid not null,kind text not null check(kind in('save','review','report')),record_sha256 text not null,actor_id uuid not null references auth.users(id),created_at timestamptz not null,unique(company_id,kind,record_id));
do $$declare t text;begin foreach t in array array['stationary_gas_heads','stationary_gas_statements','stationary_gas_versions','stationary_gas_reviews','stationary_gas_reports','stationary_gas_requests','stationary_gas_audit'] loop
execute format('alter table neuvetra.%I enable row level security',t);execute format('alter table neuvetra.%I force row level security',t);execute format('revoke all on neuvetra.%I from public,authenticated,neuvetra_runtime',t);execute format('create policy m73_read on neuvetra.%I for select to neuvetra_runtime using(neuvetra.has_staging_access() and neuvetra.is_company_member(company_id))',t);execute format('grant select on neuvetra.%I to neuvetra_runtime',t);
if t<>'stationary_gas_heads' then execute format('create trigger m73_immutable before update or delete on neuvetra.%I for each row execute function neuvetra.reject_inventory_history_mutation()',t);end if;end loop;end $$;
create function neuvetra.m73_text(v jsonb,maximum integer) returns text language plpgsql immutable set search_path=pg_catalog,neuvetra,pg_temp as $$declare s text:=v#>>'{}';begin if jsonb_typeof(v) is distinct from 'string' or length(s) not between 1 and maximum or s<>btrim(s) or s~U&'^[\00A0\1680\2000-\200A\2028\2029\202F\205F\3000\FEFF]|[\00A0\1680\2000-\200A\2028\2029\202F\205F\3000\FEFF]$' or s<>normalize(s,NFC) or s~'[[:cntrl:]]' then raise exception 'invalid text' using errcode='22023';end if;return s;end $$;
create function neuvetra.m73_quantity(v jsonb) returns text language plpgsql immutable set search_path=pg_catalog,neuvetra,pg_temp as $$declare s text:=v#>>'{}';begin if jsonb_typeof(v) is distinct from 'string' or s!~'^(0|[1-9][0-9]{0,11})\.[0-9]{3}$' then raise exception 'invalid quantity' using errcode='22023';end if;return s;end $$;
create function neuvetra.m73_exact(v numeric) returns text language sql immutable set search_path=pg_catalog,neuvetra,pg_temp as $$select case when position('.' in v::text)>0 then rtrim(rtrim(v::text,'0'),'.') else v::text end$$;
create function neuvetra.m73_display(v numeric) returns text language sql immutable set search_path=pg_catalog,neuvetra,pg_temp as $$with x as(select v*10000 n),r as(select trunc(n) q,n-trunc(n) f from x) select to_char((q+case when f>0.5 or(f=0.5 and mod(q,2)=1)then 1 else 0 end)/10000,'FM999999999999999999999990.0000') from r$$;
create function neuvetra.m73_findings(a jsonb) returns jsonb language plpgsql immutable set search_path=pg_catalog,neuvetra,pg_temp as $$declare out jsonb:='[{"code":"scope1_incomplete","message":"This source subtotal does not cover all stationary, mobile, fugitive or process emissions."},{"code":"method_not_released","message":"Factors and method are development candidates; no reporting or assurance determination."}]';begin
if a->'quantityMmbtu'='null' then out:=out||'[{"code":"activity_missing","message":"Activity is missing; no emissions were calculated."}]';end if;if a->'statement'='null' then out:=out||'[{"code":"statement_missing","message":"No synthetic activity statement is retained."}]';end if;if a->'quantityMmbtu'<>'null' and a->'statement'<>'null' and a->>'quantityMmbtu'<>a#>>'{statement,statedQuantityMmbtu}' then out:=out||'[{"code":"activity_statement_discrepancy","message":"Entered and stated quantities differ; the discrepancy remains unresolved."}]';end if;return out;end $$;
create function neuvetra.m73_coverage(target_company uuid,b jsonb,current_required boolean default true) returns jsonb language plpgsql security definer set search_path=pg_catalog,neuvetra,pg_temp as $$declare cv record;s jsonb;e jsonb;f jsonb;src jsonb;bd jsonb;rel jsonb;node text;seen text[]:='{}';pair record;begin
perform neuvetra.m71_keys(b,'coverageVersionId,coverageVersionSha256,entityId,facilityId,sourceId,boundaryDecisionId');for pair in select key,value from jsonb_each(b) loop if jsonb_typeof(pair.value)<>'string' or (pair.value#>>'{}') !~ (case when pair.key='coverageVersionSha256' then '^[0-9a-f]{64}$' else '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' end) then raise exception 'invalid binding' using errcode='22023';end if;end loop;
select * into cv from neuvetra.corporate_inventory_versions where company_id=target_company and id=(b->>'coverageVersionId')::uuid;if not found or cv.version_sha256<>b->>'coverageVersionSha256' then raise exception 'coverage binding conflict' using errcode='23505';end if;
if current_required and not exists(select 1 from neuvetra.corporate_inventory_heads where company_id=target_company and version_id=cv.id) then raise exception 'coverage changed' using errcode='23505';end if;
s:=cv.payload->'snapshot';perform neuvetra.m71_snapshot(s,null);if neuvetra.m67_hash(s)<>cv.content_sha256 or neuvetra.m67_hash((cv.payload-'snapshot'-'versionSha256')||jsonb_build_object('profile','synthetic-corporate-coverage-v1'))<>cv.version_sha256 or cv.export_text<>neuvetra.m67_canonical(cv.payload||jsonb_build_object('findings',neuvetra.m71_findings(s),'synthetic',true,'corporateCompleteness','incomplete','releaseEligible',false,'assurance','none','emissionsTotals',null,'review',null)) then raise exception 'coverage integrity failure' using errcode='22023';end if;
select x into e from jsonb_array_elements(s->'entities')x where x->>'id'=b->>'entityId';select x into f from jsonb_array_elements(s->'facilities')x where x->>'id'=b->>'facilityId';select x into src from jsonb_array_elements(s->'sources')x where x->>'id'=b->>'sourceId';select x into bd from jsonb_array_elements(s->'boundaryDecisions')x where x->>'id'=b->>'boundaryDecisionId';
if s->>'consolidationApproach'<>'operational_control' or e is null or f is null or src is null or bd is null or src->>'domain'<>'stationary_combustion' or src->>'entityId'<>e->>'id' or src->>'facilityId'<>f->>'id' or f->>'entityId'<>e->>'id' or bd->>'entityId'<>e->>'id' or e->>'countryCode'<>'US' or e->>'regionCode' is distinct from 'CA' or f->>'countryCode'<>'US' or f->>'regionCode' is distinct from 'CA' or bd->>'disposition'<>'included_activity' or bd->'reason'='null' or jsonb_array_length(bd->'evidenceRefs')=0 then raise exception 'source ineligible' using errcode='22023';end if;
for pair in select value from jsonb_array_elements(jsonb_build_array(e,f,src,bd))loop if pair.value->>'start'<>'2025-01-01' or pair.value->>'endExclusive'<>'2026-01-01' then raise exception 'unsupported period' using errcode='22023';end if;end loop;
node:=e->>'id';loop if node=any(seen) then raise exception 'relationship cycle' using errcode='22023';end if;seen:=array_append(seen,node);select x into rel from jsonb_array_elements(s->'relationships')x where x->>'childEntityId'=node;exit when rel is null;if rel->>'start'<>'2025-01-01' or rel->>'endExclusive'<>'2026-01-01' or rel->>'ownershipPercent' is distinct from '100' or rel->'controlFacts'='null' or jsonb_array_length(rel->'evidenceRefs')=0 then raise exception 'control basis incomplete' using errcode='22023';end if;node:=rel->>'parentEntityId';end loop;
return cv.export_text::jsonb;end $$;
create function neuvetra.m73_validate_request(r jsonb) returns void language plpgsql immutable set search_path=pg_catalog,neuvetra,pg_temp as $$declare a jsonb;rkey text;begin
perform neuvetra.m71_keys(r,'profile,binding,period,fuel,heatBasis,unit,quantityMmbtu,statement,manualConfirmation,discrepancyReason,zeroReason,expectedVersionId,expectedVersionSha256,correctionReason,idempotencyKey');
if r->>'profile' is distinct from 'synthetic-stationary-natural-gas-v1' or r->'period' is distinct from '{"start":"2025-01-01","endExclusive":"2026-01-01"}'::jsonb or r->>'fuel' is distinct from 'Natural Gas' or r->>'heatBasis' is distinct from 'HHV' or r->>'unit' is distinct from 'MMBtu' or jsonb_typeof(r->'manualConfirmation') is distinct from 'boolean' or jsonb_typeof(r->'idempotencyKey') is distinct from 'string' or r->>'idempotencyKey'!~'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then raise exception 'invalid profile' using errcode='22023';end if;
foreach rkey in array array['discrepancyReason','zeroReason','correctionReason']loop if r->rkey<>'null' then perform neuvetra.m73_text(r->rkey,500);end if;end loop;
if r->'expectedVersionId'='null' then if r->'expectedVersionSha256'<>'null' or r->'correctionReason'<>'null' then raise exception 'initial binding invalid' using errcode='22023';end if;else if jsonb_typeof(r->'expectedVersionId')<>'string' or r->>'expectedVersionId'!~'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' or jsonb_typeof(r->'expectedVersionSha256')<>'string' or r->>'expectedVersionSha256'!~'^[0-9a-f]{64}$' or r->'correctionReason'='null' then raise exception 'correction binding invalid' using errcode='22023';end if;end if;
if r->'statement'<>'null' then a:=r->'statement';perform neuvetra.m71_keys(a,'issuer,reference,meterLabel,statedQuantityMmbtu,description,consumptionBasis');perform neuvetra.m73_text(a->'issuer',120);perform neuvetra.m73_text(a->'reference',120);perform neuvetra.m73_text(a->'meterLabel',120);perform neuvetra.m73_text(a->'description',2000);perform neuvetra.m73_quantity(a->'statedQuantityMmbtu');if a->>'consumptionBasis' is distinct from 'dedicated_meter_consumed_no_adjustments' then raise exception 'consumption basis invalid' using errcode='22023';end if;end if;
if r->'quantityMmbtu'<>'null' then perform neuvetra.m73_quantity(r->'quantityMmbtu');if r->'statement'='null' or r->'manualConfirmation'<>'true' then raise exception 'evidence missing' using errcode='22023';end if;if r->>'quantityMmbtu'='0.000' then if r#>>'{statement,statedQuantityMmbtu}'<>'0.000' or r->'zeroReason'='null' then raise exception 'zero unsupported' using errcode='22023';end if;elsif r->>'quantityMmbtu'<>r#>>'{statement,statedQuantityMmbtu}' and r->'discrepancyReason'='null' then raise exception 'discrepancy reason missing' using errcode='22023';end if;end if;end $$;
create function neuvetra.m73_statement(a jsonb,coverage jsonb) returns text language plpgsql immutable set search_path=pg_catalog,neuvetra,pg_temp as $$declare s jsonb:=coverage->'snapshot';e jsonb;f jsonb;src jsonb;begin select x into e from jsonb_array_elements(s->'entities')x where x->>'id'=a#>>'{binding,entityId}';select x into f from jsonb_array_elements(s->'facilities')x where x->>'id'=a#>>'{binding,facilityId}';select x into src from jsonb_array_elements(s->'sources')x where x->>'id'=a#>>'{binding,sourceId}';return 'SYNTHETIC — NOT A UTILITY BILL'||chr(10)||neuvetra.m67_canonical(jsonb_build_object('profile','m73-synthetic-gas-statement-v1','companyLabel',s->'companyLabel','entityLabel',e->'legalName','facilityLabel',f->'name','sourceLabel',src->'name','binding',a->'binding','period',a->'period','fuel',a->'fuel','heatBasis',a->'heatBasis','unit',a->'unit','statement',a->'statement'))||chr(10);end $$;

create function neuvetra.m73_method() returns jsonb language sql immutable set search_path=pg_catalog,neuvetra,pg_temp as $$select '{"id":"stationary-natural-gas-combustion","version":"m73-development-v1","engineSha256":"e1b91d4fa6afa1126eeb642769c458d0b0b747c12ad5ee172543afb9246eaa14","dependencySha256":"eebade88f291cec281f38efe09597a107ce24904f28782d51405e739c4d37603","sourceSha256":"43afb91d79b2ae765b3a447549d9e1021a144a407cec5eb804be9fcf69a668a7","factorSha256":"80da7b01f57c852a1bca9a6f80a23636baef02091cd26880a7395c8331f5a20f","gwpSha256":"d87fb6c54a170e1dff70327bf475774febb3681a754cb8abec9c4c31efa3b908","sourceTitle":"EPA GHG Emission Factors Hub 2025","sourceSheet":"Emission Factors Hub","factorCells":["C38","E38","F38","G38"],"gwpCells":["E524","E525","E526"],"noteCells":["C94","C95","C99","E523","C10","C556"],"co2KgPerMmbtu":"53.06","ch4GramsPerMmbtu":"1.0","n2oGramsPerMmbtu":"0.10","ch4Gwp":"28","n2oGwp":"265","gwpAssessment":"IPCC AR5 100-year","status":"development_candidate_not_released","releaseEligible":false,"rights":"unresolved_for_factor_release"}'::jsonb$$;
create function neuvetra.m73_calculation(a jsonb,statement_hash text) returns jsonb language plpgsql immutable set search_path=pg_catalog,neuvetra,pg_temp as $$declare q numeric;co2 numeric;ch4 numeric;n2o numeric;total numeric;i jsonb;body jsonb;begin
if a->'quantityMmbtu'='null' then return 'null'::jsonb;end if;q:=(a->>'quantityMmbtu')::numeric;co2:=q*53.06;ch4:=q/1000;n2o:=q/10000;total:=co2+ch4*28+n2o*265;
i:=jsonb_build_object('binding',a->'binding','period',a->'period','fuel',a->'fuel','heatBasis',a->'heatBasis','unit',a->'unit','quantityMmbtu',a->'quantityMmbtu','statementSha256',statement_hash);
body:=jsonb_build_object('profile','m73-decimal-result-v1','input',i,'inputSha256',neuvetra.m67_hash(i),'method',neuvetra.m73_method(),'gasResults',jsonb_build_object('co2',jsonb_build_object('mass',neuvetra.m73_exact(co2),'massUnit','kg CO2','co2e',neuvetra.m73_exact(co2),'co2eUnit','kg CO2e'),'ch4',jsonb_build_object('mass',neuvetra.m73_exact(ch4),'massUnit','kg CH4','co2e',neuvetra.m73_exact(ch4*28),'co2eUnit','kg CO2e'),'n2o',jsonb_build_object('mass',neuvetra.m73_exact(n2o),'massUnit','kg N2O','co2e',neuvetra.m73_exact(n2o*265),'co2eUnit','kg CO2e')),'total',jsonb_build_object('unrounded',neuvetra.m73_exact(total),'display',neuvetra.m73_display(total),'unit','kg CO2e','rounding','half_even_4dp'));
return body||jsonb_build_object('resultSha256',neuvetra.m67_hash(body));end $$;
create function neuvetra.m73_capacity(target_company uuid,new_bytes integer) returns void language plpgsql security definer set search_path=pg_catalog,neuvetra,pg_temp as $$declare used_bytes bigint;begin
select coalesce((select sum(octet_length(convert_to(export_text,'utf8'))+4096) from neuvetra.stationary_gas_versions where company_id=target_company),0)+coalesce((select sum(octet_length(convert_to(payload::text,'utf8'))) from neuvetra.stationary_gas_reports where company_id=target_company),0) into used_bytes;
if used_bytes+new_bytes>3800000 then raise exception 'history bytes limit' using errcode='54001';end if;end $$;
create function neuvetra.save_stationary_gas(target_company uuid,target_worksheet uuid,request jsonb,calculation jsonb) returns uuid language plpgsql security definer set search_path=pg_catalog,neuvetra,pg_temp as $$declare actor uuid:=auth.uid();head record;prior record;old record;coverage jsonb;a jsonb;statement jsonb:='null';statement_id uuid;statement_text text;statement_hash text;expected_calc jsonb;body jsonb;v jsonb;contributors jsonb;fingerprint text;input_hash text;content_hash text;version_hash text;frozen text;new_id uuid:=gen_random_uuid();captured timestamptz;meter text;ref text;begin
if not neuvetra.m71_lock(target_company,true) then raise exception 'forbidden' using errcode='42501';end if;perform id from neuvetra.companies where id=target_company for update;perform id from neuvetra.corporate_inventory_heads where company_id=target_company for update;
perform neuvetra.m73_validate_request(request);fingerprint:=neuvetra.m67_hash(jsonb_build_object('operation','save','actor',actor,'companyId',target_company,'worksheetId',target_worksheet,'request',request-'idempotencyKey'));
select * into old from neuvetra.stationary_gas_requests where company_id=target_company and idempotency_key=(request->>'idempotencyKey')::uuid;if found then if old.fingerprint<>fingerprint or old.kind<>'save' or old.actor_id<>actor then raise exception 'idempotency conflict' using errcode='23505';end if;return old.record_id;end if;
coverage:=neuvetra.m73_coverage(target_company,request->'binding',true);a:=request-'expectedVersionId'-'expectedVersionSha256'-'correctionReason'-'idempotencyKey';
select * into head from neuvetra.stationary_gas_heads where company_id=target_company and id=target_worksheet for update;
select * into prior from neuvetra.stationary_gas_versions where company_id=target_company and id=head.version_id;
if target_worksheet is null then
if request->'expectedVersionId'<>'null' or exists(select 1 from neuvetra.stationary_gas_heads where company_id=target_company and source_id=(a#>>'{binding,sourceId}')::uuid)then raise exception 'source stream exists' using errcode='23505';end if;
if(select count(*) from neuvetra.stationary_gas_heads where company_id=target_company)>=3 then raise exception 'stream limit' using errcode='54000';end if;
insert into neuvetra.stationary_gas_heads(id,company_id,source_id) values(gen_random_uuid(),target_company,(a#>>'{binding,sourceId}')::uuid) returning * into head;
else
if head.id is null or head.source_id::text<>a#>>'{binding,sourceId}' then raise exception 'source identity conflict' using errcode='23505';end if;
select * into prior from neuvetra.stationary_gas_versions where company_id=target_company and id=head.version_id;
if prior.id::text is distinct from request->>'expectedVersionId' or prior.version_sha256 is distinct from request->>'expectedVersionSha256' then raise exception 'stale source version' using errcode='23505';end if;
if prior.payload->'activity'=a and prior.payload->'correctionReason'=request->'correctionReason' then raise exception 'no-op correction' using errcode='23505';end if;end if;
if(select count(*) from neuvetra.stationary_gas_versions where company_id=target_company)>=40 then raise exception 'version limit' using errcode='54000';end if;
if a->'statement'<>'null' then
statement_id:=gen_random_uuid();statement_text:=neuvetra.m73_statement(a,coverage);statement_hash:=encode(sha256(convert_to(statement_text,'utf8')),'hex');statement:=jsonb_build_object('id',statement_id,'profile','m73-synthetic-gas-statement-v1','input',a->'statement','locator','m73-statement:'||statement_id::text||':annual-activity','text',statement_text,'sha256',statement_hash,'byteLength',octet_length(convert_to(statement_text,'utf8')));
meter:=neuvetra.m67_hash(jsonb_build_array(lower(a#>>'{statement,issuer}'),lower(a#>>'{statement,meterLabel}'),'2025'));ref:=neuvetra.m67_hash(jsonb_build_array(lower(a#>>'{statement,issuer}'),lower(a#>>'{statement,reference}'),'2025'));
end if;
expected_calc:=neuvetra.m73_calculation(a,statement_hash);if calculation is distinct from expected_calc then raise exception 'calculation binding invalid' using errcode='22023';end if;
-- This update also enforces same company/meter/year and issuer/reference/year uniqueness.
update neuvetra.stationary_gas_heads set meter_key=meter,reference_key=ref where id=head.id;
captured:=date_trunc('milliseconds',clock_timestamp());
select jsonb_agg(x order by x collate "C") into contributors from(select distinct x from(select jsonb_array_elements_text(coalesce(prior.payload->'contributorIds','[]'))x union all select jsonb_array_elements_text(coverage->'contributorIds') union all select actor::text)a)a;
input_hash:=neuvetra.m67_hash(a);body:=jsonb_build_object('activity',a,'coverageVersion',coverage,'statement',statement,'calculation',calculation,'findings',neuvetra.m73_findings(a));content_hash:=neuvetra.m67_hash(body);
v:=jsonb_build_object('profile','synthetic-stationary-natural-gas-v1','id',new_id,'companyId',target_company,'worksheetId',head.id,'version',head.revision+1,'previousVersionId',prior.id,'previousVersionSha256',prior.version_sha256,'createdBy',actor,'createdAt',to_char(captured at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'contributorIds',contributors,'correctionReason',request->'correctionReason','inputSha256',input_hash,'contentSha256',content_hash);version_hash:=neuvetra.m67_hash(v);
v:=(v-'profile')||body||jsonb_build_object('versionSha256',version_hash,'synthetic',true,'scope1Completeness','incomplete','corporateCompleteness','incomplete','releaseEligible',false,'assurance','none','review',null);frozen:=neuvetra.m67_canonical(v);
if octet_length(convert_to(frozen,'utf8'))>102400 then raise exception 'version bytes limit' using errcode='54001';end if;perform neuvetra.m73_capacity(target_company,octet_length(convert_to(frozen,'utf8'))+4096);
if statement_id is not null then insert into neuvetra.stationary_gas_statements values(statement_id,target_company,statement,statement_hash,statement_text);end if;
insert into neuvetra.stationary_gas_versions values(new_id,target_company,head.id,head.revision+1,prior.id,(a#>>'{binding,coverageVersionId}')::uuid,statement_id,(a->>'quantityMmbtu')::numeric,v,input_hash,content_hash,version_hash,actor,captured,frozen);
insert into neuvetra.stationary_gas_requests values(target_company,(request->>'idempotencyKey')::uuid,actor,'save',fingerprint,new_id);insert into neuvetra.stationary_gas_audit values(gen_random_uuid(),target_company,new_id,'save',version_hash,actor,captured);
update neuvetra.stationary_gas_heads set version_id=new_id,revision=revision+1 where id=head.id;return new_id;end $$;
create function neuvetra.review_stationary_gas(target_company uuid,target_worksheet uuid,request jsonb) returns uuid language plpgsql security definer set search_path=pg_catalog,neuvetra,pg_temp as $$declare actor uuid:=auth.uid();v record;old record;body jsonb;fingerprint text;digest text;new_id uuid:=gen_random_uuid();captured timestamptz;pair record;begin
if not neuvetra.m71_lock(target_company,true) then raise exception 'forbidden' using errcode='42501';end if;perform id from neuvetra.companies where id=target_company for update;perform id from neuvetra.corporate_inventory_heads where company_id=target_company for update;perform id from neuvetra.stationary_gas_heads where company_id=target_company and id=target_worksheet for update;
perform neuvetra.m71_keys(request,'versionId,expectedVersionSha256,decision,note,acknowledgedLimitations,idempotencyKey');for pair in select key,value from jsonb_each(request) where key<>'acknowledgedLimitations'loop if jsonb_typeof(pair.value)<>'string' then raise exception 'invalid review type' using errcode='22023';end if;end loop;
if request->>'versionId'!~'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' or request->>'idempotencyKey'!~'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' or request->>'expectedVersionSha256'!~'^[0-9a-f]{64}$' or request->>'decision' not in('accepted_bounded_internal','changes_requested') or request->'acknowledgedLimitations'<>'["synthetic_only","scope1_incomplete","corporate_inventory_incomplete","factor_and_method_not_released","combustion_only_upstream_excluded","requirements_not_determined","no_external_assurance"]'::jsonb then raise exception 'invalid review' using errcode='22023';end if;perform neuvetra.m73_text(request->'note',500);
fingerprint:=neuvetra.m67_hash(jsonb_build_object('operation','review','actor',actor,'companyId',target_company,'worksheetId',target_worksheet,'request',request-'idempotencyKey'));select * into old from neuvetra.stationary_gas_requests where company_id=target_company and idempotency_key=(request->>'idempotencyKey')::uuid;if found then if old.fingerprint<>fingerprint or old.kind<>'review' or old.actor_id<>actor then raise exception 'idempotency conflict' using errcode='23505';end if;return old.record_id;end if;
select * into v from neuvetra.stationary_gas_versions where company_id=target_company and worksheet_id=target_worksheet and id=(request->>'versionId')::uuid;if not found or v.version_sha256<>request->>'expectedVersionSha256' or not exists(select 1 from neuvetra.stationary_gas_heads where id=target_worksheet and version_id=v.id) then raise exception 'stale review version' using errcode='23505';end if;
if v.payload->'contributorIds'?actor::text then raise exception 'contributor cannot review' using errcode='42501';end if;perform neuvetra.m73_coverage(target_company,v.payload#>'{activity,binding}',true);if request->>'decision'='accepted_bounded_internal' and v.payload->'calculation'='null' then raise exception 'missing calculation' using errcode='22023';end if;
captured:=date_trunc('milliseconds',clock_timestamp());body:=jsonb_build_object('id',new_id,'versionId',v.id,'versionSha256',v.version_sha256,'decision',request->'decision','note',request->'note','acknowledgedLimitations',request->'acknowledgedLimitations','reviewerId',actor,'reviewedAt',to_char(captured at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'));digest:=neuvetra.m67_hash(body||jsonb_build_object('profile','synthetic-stationary-natural-gas-v1','companyId',target_company));body:=body||jsonb_build_object('decisionSha256',digest);
insert into neuvetra.stationary_gas_reviews values(new_id,target_company,v.id,body,digest,actor,captured);insert into neuvetra.stationary_gas_requests values(target_company,(request->>'idempotencyKey')::uuid,actor,'review',fingerprint,new_id);insert into neuvetra.stationary_gas_audit values(gen_random_uuid(),target_company,new_id,'review',digest,actor,captured);return new_id;end $$;

create function neuvetra.m73_escape(v text) returns text language sql immutable set search_path=pg_catalog,neuvetra,pg_temp as $$select replace(replace(replace(replace(replace(coalesce(v,'Missing'),'&','&amp;'),'<','&lt;'),'>','&gt;'),'"','&quot;'),chr(39),'&#39;')$$;
create function neuvetra.m73_pair(label text,v text) returns text language sql immutable set search_path=pg_catalog,neuvetra,pg_temp as $$select '<dt>'||label||'</dt><dd>'||neuvetra.m73_escape(v)||'</dd>'$$;
create function neuvetra.m73_render_report(snapshot jsonb) returns text language plpgsql immutable set search_path=pg_catalog,neuvetra,pg_temp as $$declare v jsonb:=snapshot->'version';c jsonb:=v->'calculation';src jsonb;f jsonb;entity jsonb;boundary jsonb;fields jsonb;facts text;findings text;begin
select x into src from jsonb_array_elements(v#>'{coverageVersion,snapshot,sources}')x where x->>'id'=v#>>'{activity,binding,sourceId}';select x into f from jsonb_array_elements(v#>'{coverageVersion,snapshot,facilities}')x where x->>'id'=v#>>'{activity,binding,facilityId}';
select x into entity from jsonb_array_elements(v#>'{coverageVersion,snapshot,entities}')x where x->>'id'=v#>>'{activity,binding,entityId}';select x into boundary from jsonb_array_elements(v#>'{coverageVersion,snapshot,boundaryDecisions}')x where x->>'id'=v#>>'{activity,binding,boundaryDecisionId}';
facts:=neuvetra.m73_pair('Company',v#>>'{coverageVersion,snapshot,companyLabel}')||neuvetra.m73_pair('Entity',entity->>'legalName')||neuvetra.m73_pair('Boundary basis',boundary->>'reason')||neuvetra.m73_pair('Facility',f->>'name')||neuvetra.m73_pair('Source',src->>'name')||neuvetra.m73_pair('Reporting period','2025-01-01 through 2026-01-01 (exclusive)')||neuvetra.m73_pair('Coverage version',v#>>'{activity,binding,coverageVersionId}')||neuvetra.m73_pair('Source version',v->>'version')||neuvetra.m73_pair('Entered natural gas (MMBtu HHV)',v#>>'{activity,quantityMmbtu}')||neuvetra.m73_pair('Statement amount (MMBtu HHV)',v#>>'{activity,statement,statedQuantityMmbtu}')||neuvetra.m73_pair('Discrepancy explanation',coalesce(v#>>'{activity,discrepancyReason}','Not applicable'))||neuvetra.m73_pair('No-consumption explanation',coalesce(v#>>'{activity,zeroReason}','Not applicable'))||neuvetra.m73_pair('Exact source subtotal (kg CO2e)',c#>>'{total,unrounded}')||neuvetra.m73_pair('Displayed source subtotal (kg CO2e)',c#>>'{total,display}')||neuvetra.m73_pair('Review as captured',coalesce(snapshot#>>'{review,decision}','Unreviewed'))||neuvetra.m73_pair('Reviewer note',coalesce(snapshot#>>'{review,note}','Not yet reviewed'))||neuvetra.m73_pair('Review time',coalesce(snapshot#>>'{review,reviewedAt}','Not yet reviewed'))||neuvetra.m73_pair('Correction reason',coalesce(v->>'correctionReason','Not applicable'));
select coalesce(string_agg('<li>'||neuvetra.m73_escape(message)||'</li>','' order by ord),'') into findings from(select x->>'message' message,min(ord) ord from jsonb_array_elements((v->'findings')||(v#>'{coverageVersion,findings}')) with ordinality a(x,ord) group by x->>'message') deduplicated;
fields:=jsonb_build_object('facts',facts,'calculation',case when c='null' then '<p>Activity is missing; no emissions total was calculated.</p>' else '<table><thead><tr><th>Gas</th><th>Mass (kg)</th><th>kg CO2e</th></tr></thead><tbody>'||(select string_agg('<tr><th>'||label||'</th><td>'||neuvetra.m73_escape(c#>>array['gasResults',key,'mass'])||'</td><td>'||neuvetra.m73_escape(c#>>array['gasResults',key,'co2e'])||'</td></tr>','' order by ord) from(values('co2','CO2',1),('ch4','CH4',2),('n2o','N2O',3)) gases(key,label,ord))||'</tbody></table><p>Only the displayed total is rounded to four decimal places, using half-even rounding. Gas values and the exact total retain full precision.</p>' end,'statement',case when v->'statement'='null' then neuvetra.m73_pair('Evidence','No supporting statement entered') else neuvetra.m73_pair('Statement type','Synthetic — not a utility bill')||neuvetra.m73_pair('Issuer',v#>>'{activity,statement,issuer}')||neuvetra.m73_pair('Reference',v#>>'{activity,statement,reference}')||neuvetra.m73_pair('Dedicated meter',v#>>'{activity,statement,meterLabel}')||neuvetra.m73_pair('Annual period','2025-01-01 through 2026-01-01 (exclusive)')||neuvetra.m73_pair('Stated energy (MMBtu HHV)',v#>>'{activity,statement,statedQuantityMmbtu}')||neuvetra.m73_pair('Description',v#>>'{activity,statement,description}')||neuvetra.m73_pair('Retained statement locator',v#>>'{statement,locator}')||neuvetra.m73_pair('Statement SHA-256',v#>>'{statement,sha256}') end,'findings',findings,'snapshot',neuvetra.m73_escape(neuvetra.m67_canonical(snapshot)));
return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src ''none''; style-src ''unsafe-inline''; base-uri ''none''; form-action ''none''"><title>Synthetic stationary natural-gas source report</title><style>body{font:16px/1.5 system-ui;margin:2rem auto;padding:0 1rem;max-width:900px;color:#172f2c;overflow-wrap:anywhere}h1,h2{line-height:1.2}dt{font-weight:700}dd{margin:0 0 .6rem}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.5 monospace;background:#f3f6f3;padding:1rem}li{margin:.3rem 0}table{border-collapse:collapse;width:100%}th,td{padding:.45rem;text-align:left;border-bottom:1px solid #ccd8d0}@media print{body{font-size:11pt;margin:0;max-width:none}h2{break-after:avoid}pre{font-size:9pt}.technical-appendix:not([open]){display:none}}</style></head><body><h1>Stationary natural-gas source report — synthetic internal draft</h1><p>Development candidate · Not released. Corporate inventory incomplete. No filing determination or external assurance.</p><h2>Source and activity</h2><dl>'||(fields->>'facts')||'</dl><h2>Gas results and calculation trace</h2>'||(fields->>'calculation')||'<h2>Supporting synthetic statement</h2><dl>'||(fields->>'statement')||'</dl><h2>Corporate coverage remains incomplete</h2><p>Stationary combustion is partial. Mobile combustion, fugitive emissions including refrigerants, process emissions, other sources/facilities/periods, Scope 2 and all 15 Scope 3 categories remain unresolved or separately assessed. Combustion only; upstream fuel emissions excluded.</p><ul>'||(fields->>'findings')||'</ul><details class="technical-appendix"><summary>Exact version and provenance record</summary><pre>'||(fields->>'snapshot')||'</pre></details></body></html>';end $$;
create function neuvetra.create_stationary_gas_report(target_company uuid,target_worksheet uuid,request jsonb) returns uuid language plpgsql security definer set search_path=pg_catalog,neuvetra,pg_temp as $$declare actor uuid:=auth.uid();v record;decision record;old record;new_id uuid:=gen_random_uuid();captured timestamptz;fingerprint text;snapshot jsonb;snapshot_text text;html text;body jsonb;digest text;begin
if not neuvetra.m71_lock(target_company,true) then raise exception 'forbidden' using errcode='42501';end if;perform id from neuvetra.companies where id=target_company for update;perform id from neuvetra.corporate_inventory_heads where company_id=target_company for update;perform id from neuvetra.stationary_gas_heads where company_id=target_company and id=target_worksheet for update;
perform neuvetra.m71_keys(request,'versionId,expectedVersionSha256,expectedDecisionId,expectedDecisionSha256,idempotencyKey');
if jsonb_typeof(request->'versionId')<>'string' or request->>'versionId'!~'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' or jsonb_typeof(request->'idempotencyKey')<>'string' or request->>'idempotencyKey'!~'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' or jsonb_typeof(request->'expectedVersionSha256')<>'string' or request->>'expectedVersionSha256'!~'^[0-9a-f]{64}$' then raise exception 'invalid report request' using errcode='22023';end if;
if request->'expectedDecisionId'='null' then if request->'expectedDecisionSha256'<>'null' then raise exception 'invalid decision pair' using errcode='23505';end if;else if jsonb_typeof(request->'expectedDecisionId')<>'string' or request->>'expectedDecisionId'!~'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' or jsonb_typeof(request->'expectedDecisionSha256')<>'string' or request->>'expectedDecisionSha256'!~'^[0-9a-f]{64}$' then raise exception 'invalid decision pair' using errcode='23505';end if;end if;
fingerprint:=neuvetra.m67_hash(jsonb_build_object('operation','report','actor',actor,'companyId',target_company,'worksheetId',target_worksheet,'request',request-'idempotencyKey'));select * into old from neuvetra.stationary_gas_requests where company_id=target_company and idempotency_key=(request->>'idempotencyKey')::uuid;if found then if old.fingerprint<>fingerprint or old.kind<>'report' or old.actor_id<>actor then raise exception 'idempotency conflict' using errcode='23505';end if;return old.record_id;end if;
select * into v from neuvetra.stationary_gas_versions where company_id=target_company and worksheet_id=target_worksheet and id=(request->>'versionId')::uuid;if not found or v.version_sha256<>request->>'expectedVersionSha256' then raise exception 'report version conflict' using errcode='23505';end if;perform neuvetra.m73_coverage(target_company,v.payload#>'{activity,binding}',true);
select * into decision from neuvetra.stationary_gas_reviews where company_id=target_company and version_id=v.id;
if decision.id::text is distinct from request->>'expectedDecisionId' or decision.decision_sha256 is distinct from request->>'expectedDecisionSha256' then raise exception 'actual decision does not match report pin' using errcode='23505';end if;
snapshot:=jsonb_build_object('profile','m73-source-report-v1','version',v.payload,'review',decision.payload);snapshot_text:=neuvetra.m67_canonical(snapshot);html:=neuvetra.m73_render_report(snapshot);if octet_length(convert_to(html,'utf8'))>131072 then raise exception 'report bytes limit' using errcode='54001';end if;
captured:=date_trunc('milliseconds',clock_timestamp());body:=jsonb_build_object('id',new_id,'companyId',target_company,'worksheetId',target_worksheet,'versionId',v.id,'versionSha256',v.version_sha256,'decisionId',decision.id,'decisionSha256',decision.decision_sha256,'createdBy',actor,'createdAt',to_char(captured at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'rendererVersion','m73-source-report-v1','htmlSha256',encode(sha256(convert_to(html,'utf8')),'hex'),'htmlByteLength',octet_length(convert_to(html,'utf8')),'snapshotSha256',encode(sha256(convert_to(snapshot_text,'utf8')),'hex'));
digest:=neuvetra.m67_hash(body||jsonb_build_object('profile','synthetic-stationary-natural-gas-v1'));body:=body||jsonb_build_object('html',html,'snapshotJson',snapshot_text,'reportSha256',digest);perform neuvetra.m73_capacity(target_company,octet_length(convert_to(body::text,'utf8')));
insert into neuvetra.stationary_gas_reports values(new_id,target_company,target_worksheet,v.id,decision.id,body,digest,actor,captured);insert into neuvetra.stationary_gas_requests values(target_company,(request->>'idempotencyKey')::uuid,actor,'report',fingerprint,new_id);insert into neuvetra.stationary_gas_audit values(gen_random_uuid(),target_company,new_id,'report',digest,actor,captured);return new_id;end $$;
do $$declare f record;begin for f in select p.oid::regprocedure::text signature,p.proname from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='neuvetra' and(p.proname like 'm73_%' or p.proname in('save_stationary_gas','review_stationary_gas','create_stationary_gas_report'))loop execute 'revoke all on function '||f.signature||' from public,authenticated,neuvetra_runtime';if f.proname in('save_stationary_gas','review_stationary_gas','create_stationary_gas_report')then execute 'grant execute on function '||f.signature||' to neuvetra_runtime';end if;end loop;end $$;
create function neuvetra.m73_lock(target_company uuid,writing boolean) returns boolean language plpgsql security definer set search_path=pg_catalog,neuvetra,pg_temp as $$begin if not neuvetra.m71_lock(target_company,writing) then return false;end if;if writing then perform id from neuvetra.companies where id=target_company for update;perform id from neuvetra.corporate_inventory_heads where company_id=target_company for update;else perform id from neuvetra.companies where id=target_company for share;end if;return true;end $$;
revoke all on function neuvetra.m73_lock(uuid,boolean) from public,authenticated;grant execute on function neuvetra.m73_lock(uuid,boolean) to neuvetra_runtime;
