import { useEffect, useRef, useState, type FormEvent, type RefObject } from "react"
import type { HostedWorkspaceActor } from "@/lib/workspace-api"
import { annualWorksheetRequest, MONTH_LABELS, type AnnualElectricityWorksheet } from "@/lib/m67-api"
import { listElectricitySources, readElectricitySource, uploadElectricitySource, type ElectricitySource } from "@/lib/m66-api"
import { annualEvidenceRequest, EVIDENCE_LIMITATIONS, EVIDENCE_LIMITATION_LABELS, type AnnualElectricityEvidence as Evidence, type AnnualEvidenceVersion } from "@/lib/m68-api"
import { AnnualEvidenceReports } from "./AnnualEvidenceReports"

export function AnnualElectricityEvidence({actor,workspaceId,headingRef,onEntries}:{actor:HostedWorkspaceActor;workspaceId:string|null;headingRef:RefObject<HTMLHeadingElement|null>;onEntries:()=>void}) {
  const [annual,setAnnual]=useState<AnnualElectricityWorksheet|null>(null),[saved,setSaved]=useState<Evidence|null>(null),[sources,setSources]=useState<ElectricitySource[]>([])
  const [annualId,setAnnualId]=useState(""),[selected,setSelected]=useState<string[]>([]),[reasons,setReasons]=useState<Record<string,string>>({}),[reason,setReason]=useState("")
  const [editing,setEditing]=useState(false),[busy,setBusy]=useState(true),[message,setMessage]=useState("Loading annual entries and supporting bills…"),[error,setError]=useState(false)
  const [choice,setChoice]=useState<"accept_bounded_internal_draft"|"changes_requested">("accept_bounded_internal_draft"),[note,setNote]=useState(""),[acks,setAcks]=useState<string[]>([])
  const [file,setFile]=useState<File|null>(null)
  const lock=useRef(false),pending=useRef<{signature:string;key:string}|null>(null),uploadKey=useRef(crypto.randomUUID()),lifecycle=useRef({active:true}),status=useRef<HTMLParagraphElement>(null),initialActor=useRef(actor)
  const current=saved?.versions[saved.versions.length-1],chosen=annual?.versions.find(v=>v.id===annualId),manager=actor.role!=="member"
  const active=()=>lifecycle.current.active&&!actor.signal?.aborted
  function accept(data:Evidence,history:AnnualElectricityWorksheet){setSaved(data);setAnnual(history);const v=data.versions[data.versions.length-1];setAnnualId(v?.annual.id??history.versions[history.versions.length-1]?.id??"");setSelected(v?.links.map(l=>l.source.id)??[]);setReasons(Object.fromEntries(v?.links.map(l=>[l.source.id,l.quantityDifferenceReason??""])??[]));setReason("");setEditing(false);setAcks([]);setNote("")}
  useEffect(()=>{const state={active:true};lifecycle.current=state;const a=initialActor.current;void(async()=>{try{if(!workspaceId){setMessage("No company workspace is assigned.");return}const history=await annualWorksheetRequest(a,workspaceId);const [evidence,bills]=await Promise.all([annualEvidenceRequest(a,workspaceId,history),listElectricitySources(a,workspaceId)]);if(state.active&&!a.signal?.aborted){accept(evidence,history);setSources(bills);setMessage("Select saved annual entries and link the supplied January bills. Other months remain evidence gaps.")}}catch(e){if(state.active&&!a.signal?.aborted){setError(true);setMessage(e instanceof Error?e.message:"Could not load evidence.")}}finally{if(state.active&&!a.signal?.aborted)setBusy(false)}})();return()=>{state.active=false}},[workspaceId])
  async function run(action:"read"|"create"|"corrections"|"reviews",payload?:Record<string,unknown>){if(!workspaceId||!annual||lock.current||!active())return;lock.current=true;setBusy(true);setError(false);const signature=JSON.stringify({action,payload});if(action!=="read"&&pending.current?.signature!==signature)pending.current={signature,key:crypto.randomUUID()};try{const history=await annualWorksheetRequest(actor,workspaceId);const evidence=await annualEvidenceRequest(actor,workspaceId,history,action,payload?{...payload,idempotencyKey:pending.current!.key} as Parameters<typeof annualEvidenceRequest>[4]:undefined);const bills=await listElectricitySources(actor,workspaceId);if(!active())return;accept(evidence,history);setSources(bills);pending.current=null;setMessage(action==="read"?"Annual entries and evidence refreshed.":action==="reviews"?"Decision saved for this evidence version. It remains an incomplete, unreleased draft.":"Evidence version saved. Earlier versions and reports remain unchanged; a different manager can review this version.")}catch(e){if(active()){setError(true);setMessage(e instanceof Error?e.message:"Could not save evidence.")}}finally{lock.current=false;if(active()){setBusy(false);status.current?.focus()}}}
  function submit(e:FormEvent){e.preventDefault();if(!chosen)return;const payload={annualVersionId:chosen.id,expectedAnnualInputSha256:chosen.inputSha256,expectedAnnualResultSha256:chosen.resultSha256,links:selected.map(id=>{const s=sources.find(s=>s.id===id)!;return {month:"2023-01",sourceId:id,expectedSourceSha256:s.sha256,sourcePage:1,manualConfirmation:true,quantityDifferenceReason:s.printedQuantityKwh===chosen.months[0].quantityKwh?null:reasons[id]??""}})};void run(current?"corrections":"create",current?{...payload,expectedVersionId:current.id,expectedResultSha256:current.resultSha256,correctionReason:reason}:payload)}
  async function billAction(source?:ElectricitySource){if(!workspaceId||lock.current||!active())return;lock.current=true;setBusy(true);setError(false);try{if(source){const bytes=await readElectricitySource(actor,source);if(!active())return;const url=URL.createObjectURL(new Blob([bytes],{type:"application/pdf"}));const link=document.createElement("a");link.href=url;link.download=source.originalName;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage("The original bill bytes were verified and downloaded.")}else if(file){await uploadElectricitySource(actor,workspaceId,file,uploadKey.current);const bills=await listElectricitySources(actor,workspaceId);if(!active())return;setSources(bills);setFile(null);uploadKey.current=crypto.randomUUID();setMessage("Fictional bill retained. Select it below to link it to this evidence version.")}}catch(e){if(active()){setError(true);setMessage(e instanceof Error?e.message:"Could not read or upload the bill.")}}finally{lock.current=false;if(active())setBusy(false)}}
  return <section className="worksheet">
    <p className="worksheet-eyebrow">Private · synthetic · supporting evidence</p><h1 ref={headingRef} tabIndex={-1}>Annual electricity and bills</h1>
    <p>Connect saved monthly electricity entries to their supporting documents, inspect gaps and conflicts, and produce a traceable draft.</p>
    <div className="worksheet-context"><span>2023 · one fictional CAMX facility</span><span>Location-based Scope 2</span><span>Supported bills: January only</span></div>
    <p>Entered months and document coverage are separate. An attachment, matching quantity or explanation does not establish verification.</p>
    <div className="worksheet-report-actions"><button type="button" disabled={busy} onClick={onEntries}>Enter or correct monthly electricity</button><button type="button" disabled={busy||!annual} onClick={()=>void run("read")}>Refresh annual entries and bills</button></div>
    <p ref={status} tabIndex={-1} role={error?"alert":"status"} className={error?"worksheet-error":"worksheet-status"}>{message}</p>
    {annual&&!annual.versions.length&&<p>First save at least one monthly entry in Full-year electricity, then return here to link bills.</p>}
    {manager&&annual&&annual.versions.length>0&&(!current||editing)&&<>
      <form className="worksheet-card worksheet-form" onSubmit={e=>{e.preventDefault();void billAction()}}><h2>Retain a supplied fictional bill</h2><p>Only the two supplied January PDFs are supported. Use fictional files only.</p><fieldset disabled={busy}><label>Supplied PDF<input type="file" accept="application/pdf" onChange={e=>{setFile(e.target.files?.[0]??null);uploadKey.current=crypto.randomUUID()}}/></label><button disabled={!file}>Upload fictional bill</button></fieldset></form>
      <form className="worksheet-card worksheet-form" onSubmit={submit}><h2>{current?`Correct evidence version ${current.version}`:"Create an annual evidence draft"}</h2><fieldset disabled={busy}>
        <label>Saved annual entries<select value={annualId} onChange={e=>{setAnnualId(e.target.value);setSelected([]);setReasons({})}}>{annual.versions.map(v=><option key={v.id} value={v.id}>Annual version {v.version} · {v.coverage.knownMonths}/12 entered · {v.quantityKwh} kWh</option>)}</select></label>
        {chosen&&<><p>Selected January entry: {chosen.months[0].quantityKwh===null?"Not entered":`${chosen.months[0].quantityKwh} kWh`}. The saved subtotal is {chosen.total.display} kg CO2e.</p><p>Select bills only after checking the original. These bills cover January 1–31, 2023. They cannot support other months.</p>
          {sources.map(s=><div className="worksheet-card" key={s.id}><label className="worksheet-check"><input type="checkbox" disabled={chosen.months[0].quantityKwh===null} checked={selected.includes(s.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,s.id]:v.filter(id=>id!==s.id))}/>I manually confirm linking {s.originalName} to January</label><p>Printed: {s.printedQuantityKwh} kWh · page 1 · January 1–31</p><button type="button" onClick={()=>void billAction(s)}>Download original bill</button>{selected.includes(s.id)&&s.printedQuantityKwh!==chosen.months[0].quantityKwh&&<label>Explain the printed/entered quantity difference<textarea required maxLength={500} value={reasons[s.id]??""} onChange={e=>setReasons(v=>({...v,[s.id]:e.target.value}))}/><span>The explanation is retained; the discrepancy remains flagged.</span></label>}</div>)}
          {chosen.months[0].quantityKwh===null&&<p>Enter January consumption before linking a January bill. Missing consumption is not zero.</p>}
          <p role="status">{chosen.coverage.knownMonths}/12 months entered · {selected.length?1:0}/12 months with a document · {selected.length===1?1:0}/12 months with exactly one document.</p>
          {selected.length>1&&<p className="worksheet-error">Overlapping January periods: both documents are retained, their quantities are never added, and January has no unambiguous document coverage.</p>}
          {!selected.length&&<p>No bills selected. All twelve months will be shown as missing documents.</p>}
        </>}
        {current&&<label>Reason for evidence correction<textarea required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>}
        <button type="submit" disabled={!chosen}>Save {current?"corrected evidence version":"evidence draft"}</button>{current&&<button type="button" onClick={()=>{if(saved)accept(saved,annual)}}>Cancel correction</button>}
      </fieldset></form>
    </>}
    {current&&annual&&saved&&<>
      <EvidenceCard version={current} onDownload={s=>void billAction(s)} busy={busy}/>
      {!editing&&<AnnualEvidenceReports key={current.id+(current.review?.id??"none")} actor={actor} worksheet={saved} annual={annual} version={current}/>}
      {manager&&!editing&&<button type="button" disabled={busy} onClick={()=>setEditing(true)}>Correct linked bills or annual version</button>}
      {manager&&current.createdBy===actor.userId&&!current.review&&<p>A different authorized manager must review this evidence version. Earlier annual or bill reviews are not inherited.</p>}
      {manager&&current.createdBy!==actor.userId&&!current.review&&!editing&&<form className="worksheet-card worksheet-form" onSubmit={e=>{e.preventDefault();void run("reviews",{versionId:current.id,expectedResultSha256:current.resultSha256,decision:choice,note:choice==="changes_requested"?note:null,acknowledgedLimitations:choice==="accept_bounded_internal_draft"?EVIDENCE_LIMITATIONS.filter(k=>acks.includes(k)):[]})}}><h2>Review evidence version {current.version}</h2><fieldset disabled={busy}><label>Decision<select value={choice} onChange={e=>setChoice(e.target.value as typeof choice)}><option value="accept_bounded_internal_draft">Accept for bounded internal use</option><option value="changes_requested">Request a correction</option></select></label>{choice==="changes_requested"?<label>What needs correction?<textarea required maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/></label>:EVIDENCE_LIMITATIONS.map(k=><label key={k} className="worksheet-check"><input type="checkbox" required checked={acks.includes(k)} onChange={e=>setAcks(v=>e.target.checked?[...v,k]:v.filter(x=>x!==k))}/>{EVIDENCE_LIMITATION_LABELS[k]}</label>)}<button>Save evidence review decision</button></fieldset></form>}
      {saved.versions.length>1&&<details className="worksheet-history"><summary>Previous evidence versions ({saved.versions.length-1})</summary>{saved.versions.slice(0,-1).reverse().map(v=><div key={v.id}><EvidenceCard version={v} onDownload={s=>void billAction(s)} busy={busy}/><AnnualEvidenceReports actor={actor} worksheet={saved} annual={annual} version={v}/></div>)}</details>}
    </>}
    {!manager&&<p>Your access is read-only. A manager can save or review evidence versions.</p>}
    <p className="worksheet-footnote">Synthetic, manually confirmed evidence. Overall inventory incomplete; factors and methods unreleased. No assurance or filing approval.</p>
  </section>
}
function EvidenceCard({version:v,onDownload,busy}:{version:AnnualEvidenceVersion;onDownload:(s:ElectricitySource)=>void;busy:boolean}){return <article className="worksheet-card"><p className="worksheet-eyebrow">Evidence version {v.version} · Annual version {v.annual.version}</p><h2>{v.annual.companyLabel}</h2><p>{v.annual.facilityLabel}</p><dl className="worksheet-result"><div><dt>Electricity in entered months</dt><dd>{v.annual.quantityKwh} kWh</dd></div><div><dt>{v.annual.coverage.electricityComplete?"Full-year electricity subtotal":"Entered-month subtotal"}</dt><dd>{v.annual.total.display} <small>kg CO2e</small></dd></div></dl><p><strong>{v.coverage.enteredMonths}/12 months entered · {v.coverage.linkedDocumentMonths}/12 with documents · {v.coverage.unambiguousDocumentMonths}/12 with exactly one document.</strong></p><p>Exactly one document describes attachment coverage only; it does not mean verified consumption.</p><div className="annual-table-wrap"><table className="annual-month-table"><thead><tr><th>2023 month</th><th>Entered kWh</th><th>Bill evidence</th></tr></thead><tbody>{v.annual.months.map((m,i)=><tr key={m.month}><th scope="row">{MONTH_LABELS[i]}</th><td>{m.quantityKwh??"Not entered"}</td><td>{v.coverage.overlappingDocumentMonths.includes(m.month)?"Overlapping documents — unresolved":v.coverage.missingDocumentMonths.includes(m.month)?"Missing document":"One document attached"}{v.coverage.quantityDifferenceMonths.includes(m.month)?" · Quantity discrepancy":""}</td></tr>)}</tbody></table></div>{v.links.map(l=><div className="worksheet-card" key={l.source.id}><h3>{l.source.originalName}</h3><p>{l.periodStart} to {l.periodEnd} · page {l.page} · printed {l.source.printedQuantityKwh} kWh</p><button disabled={busy} onClick={()=>onDownload(l.source)}>Download original bill</button>{l.quantityDifferenceReason&&<p><strong>Quantity discrepancy:</strong> {l.quantityDifferenceReason}. This explanation does not verify the entered quantity.</p>}<details><summary>Source fingerprint</summary><p className="worksheet-fingerprint">{l.source.sha256}</p></details></div>)}{v.correctionReason&&<p>Correction: {v.correctionReason}</p>}<p>Evidence review: {v.review?.decision==="accept_bounded_internal_draft"?"Accepted for bounded internal use":v.review?.decision==="changes_requested"?"Correction requested":"Unreviewed"}. {v.review?.note}</p><details><summary>Exact result and version fingerprint</summary><p>{v.annual.total.unrounded} kg CO2e before display rounding</p><p className="worksheet-fingerprint">{v.resultSha256}</p></details></article>}
