import { useEffect, useLayoutEffect, useRef, useState, type RefObject } from 'react'
import type { HostedWorkspaceActor } from '@/lib/workspace-api'
import { FleetRosterEditor } from './FleetRosterEditor'
import { newFleetStatement } from '@/lib/m75-form'
import { M75_PROFILE, M75_PERIOD, M75_LIMITATIONS, type M75Register, type M75StatementInput, type M75Link, type M75ReviewInput, type M75ReportMetadata } from '../../../../packages/neuvetra-database/src/m75-contract'
import { m75CanonicalJson, validateM75Save } from '../../../../packages/neuvetra-database/src/m75-validation'
import { m75ReportSnapshot } from '../../../../packages/neuvetra-database/src/m75-report'
import { coverageSha256 } from '@/lib/m71-api'
import { fleetRegisterRequest, fleetSaveRequest, fleetReviewRequest, fleetReportRequest, fleetReportDownload, fleetReportSnapshotDownload, fleetStatementDownload, fleetVersionDownload } from '@/lib/m75-api'

const words = (value: string) => value.replace(/_/g, ' ')
function download(text: string, name: string, type: string) { const url = URL.createObjectURL(new Blob([text], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }

export function ControlledFleet({ actor, workspaceId, headingRef, onNavigate }: { actor: HostedWorkspaceActor; workspaceId: string | null; headingRef: RefObject<HTMLHeadingElement | null>; onNavigate: (panel: 'corporate' | 'mobile') => void }) {
  const [scope, setScope] = useState({ actor, workspaceId }), [register, setRegister] = useState<M75Register | null>(null), [selectedId, setSelectedId] = useState('')
  const [statement, setStatement] = useState<M75StatementInput>(newFleetStatement), [links, setLinks] = useState<M75Link[]>([]), [editing, setEditing] = useState(false), [confirmed, setConfirmed] = useState(false), [reason, setReason] = useState('')
  const [busy, setBusy] = useState(true), [error, setError] = useState(false), [message, setMessage] = useState('Loading fleet records…')
  const [decision, setDecision] = useState<M75ReviewInput['decision']>('changes_requested'), [reviewNote, setReviewNote] = useState(''), [ack, setAck] = useState(false), [currentReportHash, setCurrentReportHash] = useState('')
  const life = useRef({ scope, active: true }), lock = useRef(false), retry = useRef<{ signature: string; key: string } | null>(null), closeReport = useRef<(() => void) | null>(null)
  const scopeMatches = scope.actor === actor && scope.workspaceId === workspaceId
  const active = () => scopeMatches && life.current.active && life.current.scope === scope && !actor.signal?.aborted
  const manager = actor.role !== 'member', head = register?.versions.find(v => v.id === register.headVersionId), selected = register?.versions.find(v => v.id === selectedId), review = register?.reviews.find(r => r.versionId === selected?.id)
  const current = !selected || selected.id === head?.id, reconciliation = register?.reconciliation
  const canReview = manager && head && current && !editing && !review && !head.contributorIds.includes(actor.userId)
  const acceptanceBlocked = reconciliation?.findings.some(f => f.blocking && f.code !== 'roster_review_required') ?? true

  function accept(value: M75Register, preferred = '') { setRegister(value); setSelectedId(value.versions.some(v => v.id === preferred) ? preferred : value.headVersionId ?? ''); setEditing(false); setConfirmed(false); setReviewNote(''); setAck(false); setCurrentReportHash('') }
  useLayoutEffect(() => {
    const state = { scope, active: true }; life.current = state; lock.current = false; retry.current = null
    void (async () => { try { if (!scope.workspaceId) { setMessage('No company workspace is assigned.'); return } const value = await fleetRegisterRequest(scope.actor,scope.workspaceId); if (state.active && !scope.actor.signal?.aborted) { accept(value); setMessage('Declare the fleet, then inspect every missing or conflicting match.') } } catch (e) { if (state.active && !scope.actor.signal?.aborted) { setError(true); setMessage(e instanceof Error ? e.message : 'Fleet records unavailable.') } } finally { if (state.active && !scope.actor.signal?.aborted) setBusy(false) } })()
    return () => { state.active = false; closeReport.current?.(); closeReport.current = null }
  }, [scope])
  useEffect(() => {
    let live = true
    if (register && head) { const r = register.reviews.find(x => x.versionId === head.id) ?? null; void coverageSha256(m75CanonicalJson(m75ReportSnapshot(head,r,register.reconciliation))).then(value => { if (live) setCurrentReportHash(value) }).catch(() => { if (live) setCurrentReportHash('') }) }
    return () => { live = false }
  }, [register,head])
  if (!scopeMatches) { setScope({ actor,workspaceId }); setRegister(null); setSelectedId(''); setStatement(newFleetStatement()); setLinks([]); setEditing(false); setConfirmed(false); setReason(''); setBusy(true); setError(false); setMessage('Loading fleet records…'); setReviewNote(''); setAck(false); setDecision('changes_requested'); setCurrentReportHash('') }

  async function action(kind: string, payload: unknown, work: (key: string) => Promise<void>) {
    if (!active() || lock.current || !workspaceId) return
    lock.current = true; setBusy(true); setError(false)
    const signature = m75CanonicalJson({ kind, payload }); if (retry.current?.signature !== signature) retry.current = { signature,key:crypto.randomUUID() }
    try { await work(retry.current.key); if (active()) retry.current = null }
    catch (e) { if (active()) { setError(true); setMessage(e instanceof Error ? e.message : 'The action could not be verified. Retry the same action or refresh.') } }
    finally { if (active()) { lock.current = false; setBusy(false) } }
  }
  const refresh = () => action('refresh',null,async () => { const value = await fleetRegisterRequest(actor,workspaceId!); if (active()) { accept(value); setMessage('Fleet status refreshed against the current records.') } })
  function start() { if (!manager || busy || !active()) return; setStatement(structuredClone(head?.activity.rosterStatement ?? newFleetStatement())); setLinks(structuredClone(head?.activity.links ?? [])); setSelectedId(head?.id ?? ''); setConfirmed(false); setReason(''); setEditing(true); setError(false); setMessage('Unsaved roster. Enter its own evidence before matching corporate sources.') }
  async function save() {
    if (!manager || !register?.proof.coverageVersion || !reconciliation || !active()) return
    const coverage = register.proof.coverageVersion, input = { profile:M75_PROFILE, coverageVersionId:coverage.id, coverageVersionSha256:coverage.versionSha256, expectedDependencySha256:reconciliation.dependencySha256, period:{...M75_PERIOD}, rosterStatement:statement, manualConfirmation:confirmed, links, expectedVersionId:head?.id ?? null, expectedVersionSha256:head?.versionSha256 ?? null, correctionReason:head ? reason : null }
    try { validateM75Save({...input,idempotencyKey:crypto.randomUUID()}) } catch { setError(true); setMessage('Check the roster reference, evidence description, vehicle facts and correction reason. Unknown facts can remain blank; invalid dates or identifiers must be corrected. Nothing was saved.'); return }
    await action('save',input,async key => { await fleetSaveRequest(actor,workspaceId!,register.rosterId,{...input,idempotencyKey:key}); const fresh = await fleetRegisterRequest(actor,workspaceId!); if (active()) { accept(fresh); setMessage('Roster version saved. Inspect the findings and obtain a separate fleet review.') } })
  }
  async function saveReview() {
    if (!canReview || !head || !register?.rosterId || !reconciliation || !active()) return
    const input = { versionId:head.id, expectedVersionSha256:head.versionSha256, expectedDependencySha256:reconciliation.dependencySha256, decision, note:reviewNote, acknowledgedLimitations:ack ? [...M75_LIMITATIONS] : [] }
    await action('review',input,async key => { await fleetReviewRequest(actor,workspaceId!,register.rosterId!,{...input,idempotencyKey:key}); const fresh = await fleetRegisterRequest(actor,workspaceId!); if (active()) { accept(fresh); setMessage('Fleet review saved for the exact roster, boundary and workpaper versions.') } })
  }
  async function createReport() { if (!manager || !current || !register?.rosterId || !head || !reconciliation || editing) return; const input = { expectedReconciliationSha256:reconciliation.contentSha256 }; await action('report',input,async key => { await fleetReportRequest(actor,workspaceId!,register.rosterId!,{...input,idempotencyKey:key}); const fresh = await fleetRegisterRequest(actor,workspaceId!); if (active()) { accept(fresh); setMessage('Exact fleet report retained, including every open finding.') } }) }
  async function reportFile(report: M75ReportMetadata, mode: 'open' | 'download' | 'print' | 'snapshot') {
    await action('report-'+mode,report.id,async () => {
      if (mode === 'snapshot') { const text = await fleetReportSnapshotDownload(actor,workspaceId!,report); if (active()) { download(text,`fleet-report-${report.id}.json`,'application/json'); setMessage('Exact report snapshot downloaded.') } return }
      const html = await fleetReportDownload(actor,workspaceId!,report); if (!active()) return
      if (mode === 'download') { download(html,`fleet-report-${report.id}.html`,'text/html;charset=utf-8'); setMessage('Exact fleet report downloaded.'); return }
      closeReport.current?.(); const before = document.activeElement instanceof HTMLElement ? document.activeElement : null, dialog = document.createElement('dialog'), frame = document.createElement('iframe'), close = document.createElement('button')
      dialog.setAttribute('aria-label','Fleet reconciliation report'); dialog.style.cssText='width:90vw;max-width:1050px;height:90vh;padding:12px;background:white;color:#172f2c;border:2px solid #667085'
      frame.title='Fleet reconciliation report'; frame.setAttribute('sandbox','allow-same-origin allow-modals'); frame.style.cssText='display:block;width:100%;height:90%;border:0;background:white'; close.textContent='Close fleet report'; close.style.cssText='padding:10px 16px;margin-bottom:10px;font:inherit'
      const cleanup = () => { dialog.remove(); if (active()) before?.focus() }; closeReport.current=cleanup; close.onclick=() => { cleanup(); closeReport.current=null }; dialog.addEventListener('cancel',() => { cleanup(); closeReport.current=null })
      frame.onload=() => { if (mode === 'print' && active()) { try { frame.contentWindow?.print(); setMessage('Print preview requested for the exact fleet report.') } catch { setError(true); setMessage('Print preview could not open. Download the HTML report to print from your browser.') } } }; frame.srcdoc=html; dialog.append(close,frame); document.body.append(dialog); dialog.showModal(); close.focus()
    })
  }
  if (!scopeMatches) return <section className="worksheet"><h1 ref={headingRef} tabIndex={-1}>Fleet reconciliation</h1><p role="status">Loading fleet records…</p></section>
  return <section className="worksheet controlled-fleet">
    <p className="worksheet-eyebrow">California reporting · Private synthetic workspace</p><h1 ref={headingRef} tabIndex={-1}>Fleet reconciliation</h1>
    <p>Declare the whole fleet, then match every vehicle to its source and reviewed workpaper. Include all controlled trips, wherever they occur.</p>
    <div className="worksheet-context"><span>2025 calendar year</span><span>Declared fleet only</span><span>Scope 1 incomplete</span></div>
    <p role={error ? 'alert' : 'status'} className={error ? 'worksheet-error' : 'worksheet-status'}>{message}</p>
    <div className="fleet-actions"><button type="button" disabled={busy} onClick={() => void refresh()}>Refresh fleet status</button><button type="button" disabled={busy} onClick={() => onNavigate('corporate')}>Open corporate register</button><button type="button" disabled={busy} onClick={() => onNavigate('mobile')}>Open vehicle workpapers</button>{manager && <button type="button" disabled={busy || !register?.proof.coverageVersion || editing} onClick={start}>{head ? 'Correct roster or refresh its links' : 'Declare fleet roster'}</button>}</div>
    {!register?.proof.coverageVersion && !busy && <p>Save the corporate boundary and source register before declaring the fleet.</p>}
    {register && <>
      {!!register.versions.length && <label>Roster history<select disabled={busy || editing} value={selectedId} onChange={e => { setSelectedId(e.target.value); setAck(false); setReviewNote('') }}>{register.versions.map(v => <option key={v.id} value={v.id}>Version {v.version}{v.id === register.headVersionId ? ' · current roster' : ' · historical'}</option>)}</select></label>}
      {!current && <p className="worksheet-error">Historical roster version. Its review and reports apply only to the records they captured. Select the current roster to inspect today’s reconciliation.</p>}
      {editing && <div className="fleet-draft"><h2>Unsaved roster {head ? 'correction' : 'declaration'}</h2><FleetRosterEditor statement={statement} links={links} coverage={register.proof.coverageVersion?.snapshot ?? null} disabled={busy} onStatement={setStatement} onLinks={setLinks} /><label className="fleet-check"><input type="checkbox" disabled={busy} checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />I checked this synthetic declaration against its stated records and retained every disclosed vehicle.</label>{head && <label>Reason for this correction or refreshed linkage<textarea disabled={busy} value={reason} maxLength={500} onChange={e => setReason(e.target.value)} /></label>}<div className="fleet-actions"><button type="button" disabled={busy} onClick={() => void save()}>Save roster version</button><button type="button" disabled={busy} onClick={() => { setEditing(false); setConfirmed(false); setMessage('Unsaved roster changes discarded.') }}>Discard draft</button></div></div>}
      {current && reconciliation && <div className="fleet-reconciliation"><h2>Current fleet check</h2><p><strong>{reconciliation.status === 'reconciled_bounded_synthetic' ? 'Declared synthetic roster reconciled' : 'Blocked · findings need attention'}</strong></p><div className="worksheet-context"><span>{reconciliation.counts.evidenceRows} declared rows</span><span>{reconciliation.counts.currentMobileSources} registered mobile sources</span><span>{reconciliation.counts.currentWorkpaperStreams} of 3 workpaper slots used</span><span>{reconciliation.counts.reconciledRows} matched and reviewed rows</span></div><p>Counts describe the retained records. They are not an emissions total or proof that all real vehicles were discovered.</p><div className="fleet-table-wrap"><table><caption>Every declared, registered or calculated mobile source</caption><thead><tr><th>Vehicle / source</th><th>Entity and facility</th><th>Status</th><th>Findings</th></tr></thead><tbody>{reconciliation.rows.map(row => <tr key={row.rowKey}><td><strong>{row.assetId ?? 'Identity unknown'}</strong><br/>{row.sourceLabel ?? 'No source match'}<details><summary>Record references</summary><code>{row.sourceId ?? 'No source'}</code>{row.worksheetIds.map(id => <code key={id}>{id}</code>)}</details></td><td>{row.entityLabel ?? 'Entity unknown'}<br/>{row.facilityLabel ?? 'Facility unknown'}</td><td>{words(row.status)}</td><td>{row.findings.length ? <ul>{row.findings.map((f,i) => <li key={`${f.code}:${i}`}>{f.message}</li>)}</ul> : 'No row findings'}</td></tr>)}</tbody></table></div>{!reconciliation.rows.length && <p>No fleet records are present. An empty register does not mean there are no vehicles.</p>}<h3>All reconciliation findings</h3><ul>{reconciliation.findings.map((f,i) => <li key={`${f.rowKey}:${f.code}:${i}`}>{f.message}</li>)}</ul></div>}
      {selected && <div className="fleet-evidence"><h2>Roster version {selected.version} evidence and review</h2><p>{selected.activity.rosterStatement?.issuer ?? 'No statement'} · {selected.activity.rosterStatement?.reference ?? 'No reference'}</p><p>{selected.activity.rosterStatement?.description}</p><p>Fleet review: {review ? words(review.decision) : 'Not reviewed'}{selected.dependencies.dependencySha256 !== reconciliation?.dependencySha256 ? ' · captured dependencies are historical' : ''}</p><p>{review?.note}</p>{selected.statement && <><code>{selected.statement.locator}</code><div className="fleet-actions"><button type="button" disabled={busy} onClick={() => void action('statement',selected.id,async () => { const text=await fleetStatementDownload(actor,workspaceId!,selected); if(active())download(text,`fleet-roster-${selected.id}.txt`,'text/plain;charset=utf-8') })}>Download roster evidence</button><button type="button" disabled={busy} onClick={() => void action('version',selected.id,async () => { const text=await fleetVersionDownload(actor,workspaceId!,selected); if(active())download(text,`fleet-roster-${selected.id}.json`,'application/json') })}>Download exact roster version</button></div></>}<details><summary>Declared vehicle facts for this version</summary><pre>{JSON.stringify(selected.activity.rosterStatement?.assets ?? [],null,2)}</pre></details></div>}
      {canReview && <fieldset disabled={busy}><legend>Separate fleet reconciliation review</legend><p>Acceptance requires an exact current boundary, complete reviewed workpapers and no blocking findings. A contributor cannot review this version.</p><label>Decision<select value={decision} onChange={e => setDecision(e.target.value as M75ReviewInput['decision'])}><option value="changes_requested">Changes requested</option><option value="accepted_bounded_reconciliation" disabled={acceptanceBlocked}>Accept bounded synthetic reconciliation</option></select></label><label>Review note<textarea value={reviewNote} maxLength={500} onChange={e => setReviewNote(e.target.value)} /></label><label className="fleet-check"><input type="checkbox" checked={ack} onChange={e => setAck(e.target.checked)} />I acknowledge all limitations listed below.</label><button type="button" disabled={!ack || !reviewNote.trim() || decision === 'accepted_bounded_reconciliation' && acceptanceBlocked} onClick={() => void saveReview()}>Save fleet review</button></fieldset>}
      <div className="fleet-reports"><h2>Retained fleet reports</h2>{manager && <button type="button" disabled={busy || !head || !current || editing} onClick={() => void createReport()}>Retain current fleet report</button>}<p>A report may document a blocked fleet. Earlier reports remain unchanged when source records change.</p>{register.reports.filter(r => !selected || r.rosterVersionId === selected.id).map(report => <article key={report.id}><p>{new Date(report.createdAt).toLocaleString()} · {currentReportHash ? report.snapshotSha256 === currentReportHash ? 'Matches the current snapshot' : 'Historical snapshot' : 'Checking current snapshot'}</p><div className="fleet-actions">{(['open','download','print','snapshot'] as const).map(mode => <button key={mode} type="button" disabled={busy} onClick={() => void reportFile(report,mode)}>{mode === 'snapshot' ? 'Download report data' : mode[0]!.toUpperCase()+mode.slice(1)+' report'}</button>)}</div></article>)}</div>
    </>}
    <aside className="worksheet-report-notice"><h2>Limits of this demonstration</h2><ul>{M75_LIMITATIONS.map(item => <li key={item}>{words(item)}</li>)}</ul></aside>
  </section>
}
