import { useCallback, useEffect, useRef, useState, type FormEvent, type RefObject } from "react"
import type { HostedWorkspaceActor } from "@/lib/workspace-api"
import { corporateRegisterRequest, corporateSaveRequest, corporateReviewRequest, corporateExportRequest, syntheticCoverageReference } from "@/lib/m71-api"
import { createM71Seed, M71_MAX_VERSIONS, M71_ARTIFACT, M71_CATEGORIES, M71_LIMITATIONS, type M71Snapshot, type M71Register, type M71CoverageItem, type M71Disposition, type M71Version } from "../../../../packages/neuvetra-database/src/m71-contract"

const clone = <T,>(value:T):T => structuredClone(value)
const words = (value:string) => value.replace(/_/g, " ")
const dispositions:Record<M71Disposition,string> = {unassessed:"Not assessed",missing:"Missing",included_activity:"Proposed inclusion",included_estimate:"Estimate proposed",excluded:"Proposed exclusion",not_applicable:"Proposed not applicable"}
const domainName = (domain:string) => domain.startsWith("scope3_") ? `${domain.slice(7)}. ${M71_CATEGORIES[Number(domain.slice(7))-1]}` : ({stationary_combustion:"Stationary combustion",mobile_combustion:"Mobile combustion",process:"Process emissions",fugitive:"Fugitive emissions",electricity:"Purchased electricity",steam:"Purchased steam",heat:"Purchased heat",cooling:"Purchased cooling",location_based:"Location-based Scope 2 view",market_based:"Market-based Scope 2 view"}[domain]??words(domain))
const limits = ["Fictional data only", "Corporate inventory remains incomplete", "Methods are not released", "Reporting requirements are not determined", "No emissions totals are calculated", "No external assurance"]

function findingLabel(snapshot:M71Snapshot,id:string|null):string {
 if(!id)return "Company register"
 const entity=snapshot.entities.find(e=>e.id===id);if(entity)return entity.legalName
 const facility=snapshot.facilities.find(f=>f.id===id);if(facility)return facility.name
 const source=snapshot.sources.find(r=>r.id===id);if(source)return `${source.name} · ${snapshot.facilities.find(f=>f.id===source.facilityId)?.name??snapshot.entities.find(e=>e.id===source.entityId)?.legalName??"Operation"}`
 const decision=snapshot.boundaryDecisions.find(r=>r.id===id);if(decision)return `${snapshot.entities.find(e=>e.id===decision.entityId)?.legalName??"Entity"} boundary`
 const relationship=snapshot.relationships.find(r=>r.id===id);if(relationship)return `${snapshot.entities.find(e=>e.id===relationship.childEntityId)?.legalName??"Entity"} ownership and control`
 const row=snapshot.coverageItems.find(r=>r.id===id);if(row)return `${domainName(row.domain)}${row.sourceId?` · ${findingLabel(snapshot,row.sourceId)}`:" · Company-wide screening"}`
 return "Reporting requirement"
}

export function CorporateCoverageRegister({actor,workspaceId,headingRef}:{actor:HostedWorkspaceActor;workspaceId:string|null;headingRef:RefObject<HTMLHeadingElement|null>}) {
 const [saved,setSaved]=useState<M71Register|null>(null),[draft,setDraft]=useState<M71Snapshot>(()=>createM71Seed())
 const [panel,setPanel]=useState<"boundary"|"coverage"|"history">("boundary"),[selected,setSelected]=useState<string|null>(null)
 const [editing,setEditing]=useState(false),[reason,setReason]=useState(""),[busy,setBusy]=useState(true),[error,setError]=useState(false),[message,setMessage]=useState("Loading the saved company coverage…")
 const [historyId,setHistoryId]=useState(""),[reviewNote,setReviewNote]=useState(""),[reviewDecision,setReviewDecision]=useState<"accepted_bounded_internal"|"changes_requested">("accepted_bounded_internal"),[acknowledged,setAcknowledged]=useState(false)
 const [operation,setOperation]=useState({name:"",facility:"",country:"US",region:"CA"})
 const [gasSource,setGasSource]=useState({facilityId:"",name:""})
 const [mobileSource,setMobileSource]=useState({facilityId:"",name:""})
 const lifecycle=useRef({active:true}),lock=useRef(false),pending=useRef<{signature:string;key:string}|null>(null),initialActor=useRef(actor)
 const latest=saved?.versions[saved.versions.length-1],historical=saved?.versions.find(v=>v.id===historyId)??latest
 const manager=actor.role!=="member",canEdit=manager&&editing&&!busy
 const active=()=>lifecycle.current.active&&!actor.signal?.aborted
 const displayed=editing?draft:latest?.snapshot??draft
 const selectedItem=displayed.coverageItems.find(row=>row.id===selected)
 const accept=useCallback((register:M71Register)=>{setSaved(register);const last=register.versions[register.versions.length-1];setDraft(clone(last?.snapshot??createM71Seed()));setEditing(!last&&manager);setReason("");setHistoryId(last?.id??"");setReviewNote("");setAcknowledged(false)},[manager])
 useEffect(()=>{const state={active:true};lifecycle.current=state;const currentActor=initialActor.current;void(async()=>{try{if(!workspaceId){setMessage("No company workspace is assigned.");return}const register=await corporateRegisterRequest(currentActor,workspaceId);if(state.active&&!currentActor.signal?.aborted){accept(register);setMessage(register.versions.length?"Saved coverage loaded. Review unresolved findings before making a correction.":"Start with the fictional California company, then save its coverage register.")}}catch(e){if(state.active&&!currentActor.signal?.aborted){setError(true);setMessage(e instanceof Error?e.message:"Coverage is unavailable.")}}finally{if(state.active&&!currentActor.signal?.aborted)setBusy(false)}})();return()=>{state.active=false}},[workspaceId,accept])
 async function run(action:"refresh"|"save"|"review"){if(!workspaceId||lock.current||!active())return;lock.current=true;setBusy(true);setError(false);try{
  if(action==="save"){
   const effective={snapshot:draft,expectedVersionId:latest?.id??null,expectedVersionSha256:latest?.versionSha256??null,correctionReason:latest?reason:null};const signature=JSON.stringify({action,...effective});if(pending.current?.signature!==signature)pending.current={signature,key:crypto.randomUUID()}
   await corporateSaveRequest(actor,workspaceId,saved?.inventoryId??null,{...effective,idempotencyKey:pending.current.key})
  }else if(action==="review"&&latest&&saved?.inventoryId){
   const effective={versionId:latest.id,expectedVersionSha256:latest.versionSha256,decision:reviewDecision,note:reviewNote,acknowledgedLimitations:acknowledged?[...M71_LIMITATIONS]:[]};const signature=JSON.stringify({action,...effective});if(pending.current?.signature!==signature)pending.current={signature,key:crypto.randomUUID()}
   await corporateReviewRequest(actor,workspaceId,saved.inventoryId,{...effective,idempotencyKey:pending.current.key})
  }
  const register=await corporateRegisterRequest(actor,workspaceId);if(!active())return;accept(register);pending.current=null;setMessage(action==="save"?"Coverage version saved. Earlier versions and exports stay unchanged; review is still separate.":action==="review"?"Internal decision saved for this exact version. Coverage remains incomplete.":"Saved coverage refreshed.")
 }catch(e){if(active()){setError(true);setMessage(e instanceof Error?e.message:"Could not save coverage. Retry the same action or refresh.")}}finally{lock.current=false;if(active())setBusy(false)}}
 async function exportVersion(version:M71Version){if(!workspaceId||lock.current||!active())return;lock.current=true;setBusy(true);setError(false);try{const text=await corporateExportRequest(actor,workspaceId,version);if(!active())return;const url=URL.createObjectURL(new Blob([text],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download=`california-coverage-version-${version.version}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage(`Version ${version.version} coverage downloaded. The frozen save snapshot does not include later review decisions.`)}catch(e){if(active()){setError(true);setMessage(e instanceof Error?e.message:"Export unavailable.")}}finally{lock.current=false;if(active())setBusy(false)}}
 function edit(mutator:(next:M71Snapshot)=>void){setDraft(old=>{const next=clone(old);mutator(next);return next})}
 async function attach(kind:"boundary"|"coverage"|"estimate",id:string,checked:boolean){if(!canEdit||lock.current||!active())return;lock.current=true;setBusy(true);try{const ref=checked?await syntheticCoverageReference():null;if(!active())return;edit(next=>{if(kind==="estimate"){const row=next.coverageItems.find(r=>r.id===id);if(row?.estimateBasis)row.estimateBasis.inputEvidenceRefs=ref?[ref]:[]}else{const row=kind==="boundary"?next.boundaryDecisions.find(r=>r.id===id):next.coverageItems.find(r=>r.id===id);if(row)row.evidenceRefs=ref?[ref]:[]}})}catch(e){if(active()){setError(true);setMessage(e instanceof Error?e.message:"Synthetic reference unavailable.")}}finally{lock.current=false;if(active())setBusy(false)}}
 function updateItem(patch:Partial<M71CoverageItem>){if(selected)edit(next=>{const row=next.coverageItems.find(r=>r.id===selected);if(row)Object.assign(row,patch)})}
 function addOperation(event:FormEvent){event.preventDefault();if(!canEdit)return;if(!operation.name.trim()||!operation.facility.trim()){setError(true);setMessage("Enter the operation and facility names.");return}edit(next=>{const entityId=crypto.randomUUID(),facilityId=crypto.randomUUID(),sourceId=crypto.randomUUID(),interval={...next.period};next.entities.push({id:entityId,legalName:operation.name,countryCode:operation.country,regionCode:operation.region||null,...interval,evidenceRefs:[]});next.facilities.push({id:facilityId,entityId,name:operation.facility,countryCode:operation.country,regionCode:operation.region||null,...interval,evidenceRefs:[]});next.sources.push({id:sourceId,entityId,facilityId,name:"Purchased electricity — assess activity",domain:"electricity",...interval,evidenceRefs:[]});next.boundaryDecisions.push({id:crypto.randomUUID(),entityId,disposition:"unassessed",reason:null,...interval,evidenceRefs:[]});next.relationships.push({id:crypto.randomUUID(),parentEntityId:next.entities[0]!.id,childEntityId:entityId,ownershipPercent:null,controlFacts:null,...interval,evidenceRefs:[]});next.coverageItems.push({id:crypto.randomUUID(),domain:"electricity",entityId,sourceId,...interval,disposition:"unassessed",activityDataState:"not_assessed",evidenceState:"missing",methodReadiness:"unsupported",reason:null,evidenceRefs:[],estimateBasis:null,quantity:null,unit:null})});setOperation({name:"",facility:"",country:"US",region:"CA"});setMessage("Operation added to this unsaved draft. Boundary, control and activity assessment remain open.")}
 function addGasSource(event:FormEvent){
  event.preventDefault();if(!canEdit||lock.current||!active())return
  const facility=draft.facilities.find(f=>f.id===gasSource.facilityId&&f.countryCode==="US"&&f.regionCode==="CA"&&f.start===draft.period.start&&f.endExclusive===draft.period.endExclusive)
  const name=gasSource.name.trim()
  if(!facility||!name){setError(true);setMessage("Select a full-year California facility and enter a fictional stationary source name.");return}
  const sourceId=crypto.randomUUID(),coverageId=crypto.randomUUID()
  edit(next=>{const interval={...next.period};next.sources.push({id:sourceId,entityId:facility.entityId,facilityId:facility.id,name,domain:"stationary_combustion",...interval,evidenceRefs:[]});next.coverageItems.push({id:coverageId,domain:"stationary_combustion",entityId:facility.entityId,sourceId,...interval,disposition:"missing",activityDataState:"missing",evidenceState:"missing",methodReadiness:"candidate",reason:null,evidenceRefs:[],estimateBasis:null,quantity:null,unit:null})})
  setGasSource({facilityId:"",name:""});setError(false);setMessage("Stationary source added to this unsaved draft. Record the entity's boundary rationale and fictional reference, then save the coverage version. Gas activity and evidence remain missing.")
 }
 function addMobileSource(event:FormEvent){
  event.preventDefault();if(!canEdit||lock.current||!active())return
  const facility=draft.facilities.find(f=>f.id===mobileSource.facilityId&&f.countryCode==="US"&&f.regionCode==="CA"&&f.start===draft.period.start&&f.endExclusive===draft.period.endExclusive)
  const name=mobileSource.name.trim()
  if(!facility||!name){setError(true);setMessage("Select a full-year California base facility and enter a fictional vehicle name.");return}
  const sourceId=crypto.randomUUID()
  edit(next=>{const interval={...next.period};next.sources.push({id:sourceId,entityId:facility.entityId,facilityId:facility.id,name,domain:"mobile_combustion",...interval,evidenceRefs:[]});next.coverageItems.push({id:crypto.randomUUID(),domain:"mobile_combustion",entityId:facility.entityId,sourceId,...interval,disposition:"missing",activityDataState:"missing",evidenceState:"missing",methodReadiness:"candidate",reason:null,evidenceRefs:[],estimateBasis:null,quantity:null,unit:null})})
  setMobileSource({facilityId:"",name:""});setError(false);setMessage("Vehicle added to this unsaved draft. Record the entity's boundary rationale and fictional reference, then save coverage. Vehicle classification, fuel, mileage and evidence remain unverified.")
 }
 const reviewAllowed=manager&&latest&&!latest.contributorIds.includes(actor.userId)&&!latest.review&&!editing
 return <section className="worksheet corporate-register">
  <p className="worksheet-eyebrow">California reporting · Private synthetic workspace</p><h1 ref={headingRef} tabIndex={-1}>Corporate coverage register</h1>
  <p>Record the company, its operations and the emissions categories to investigate. Save corrections and review each version while keeping unresolved gaps visible.</p>
  <div className="worksheet-context"><span>2025 calendar year</span><span>California example</span><span>Inventory incomplete · No assurance</span></div>
  <p role={error?"alert":"status"} className={error?"worksheet-error":"worksheet-status"}>{message}</p>
  <div className="worksheet-report-actions"><button type="button" disabled={busy||editing} onClick={()=>void run("refresh")}>Refresh saved register</button>{manager&&latest&&!editing&&<button type="button" disabled={busy||saved.versions.length>=M71_MAX_VERSIONS} onClick={()=>{setDraft(clone(latest.snapshot));setEditing(true);setReason("");setMessage("Editing a new version. Saved history stays unchanged.")}}>Make a correction</button>}{editing&&latest&&<button type="button" disabled={busy} onClick={()=>{setDraft(clone(latest.snapshot));setEditing(false);setReason("");setError(false);setMessage("Unsaved changes discarded.")}}>Cancel correction</button>}</div>
  {saved&&saved.versions.length>=M71_MAX_VERSIONS&&<p>This fictional demonstration has reached its {M71_MAX_VERSIONS}-version limit. Saved versions remain available for review and download.</p>}
  {!manager&&<p>Read-only member access. A manager can save or review coverage.</p>}
  <nav className="worksheet-nav" aria-label="Corporate register sections">{([['boundary','Company and operations'],['coverage','Scope 1, 2 and 3'],['history','History and review']] as const).map(([id,label])=><button key={id} type="button" aria-pressed={panel===id} onClick={()=>setPanel(id)}>{label}</button>)}</nav>
  {panel==="boundary"&&<>
  <div className="worksheet-form"><label>Company group<input disabled={!canEdit} value={displayed.companyLabel} onChange={e=>edit(n=>{n.companyLabel=e.target.value})}/></label><p>Reporting period: {displayed.period.start} through December 31, 2025. Consolidation: {words(displayed.consolidationApproach)}. Supporting control facts remain subject to review.</p></div>
   {canEdit&&<form className="worksheet-card worksheet-form" onSubmit={addGasSource}><h2>Add synthetic natural-gas source</h2><p>Choose an existing full-year California facility. This adds a source to assess; its activity and supporting statement are recorded separately.</p><fieldset disabled={busy}><label>Source facility<select required value={gasSource.facilityId} onChange={e=>setGasSource({...gasSource,facilityId:e.target.value})}><option value="">Select a facility</option>{displayed.facilities.filter(f=>f.countryCode==="US"&&f.regionCode==="CA"&&f.start===displayed.period.start&&f.endExclusive===displayed.period.endExclusive).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Stationary source name<input required maxLength={120} value={gasSource.name} onChange={e=>setGasSource({...gasSource,name:e.target.value})}/></label><button type="submit">Add gas source to draft</button></fieldset></form>}
   {canEdit&&<form className="worksheet-card worksheet-form" onSubmit={addMobileSource}>
    <h2>Add synthetic diesel vehicle</h2>
    <p>Choose the vehicle's California base facility. Include all of its travel, including trips outside California. Fuel consumed and distance travelled are recorded separately in its workpaper.</p>
    <fieldset disabled={busy}>
     <label>Vehicle base facility<select required value={mobileSource.facilityId} onChange={e=>setMobileSource({...mobileSource,facilityId:e.target.value})}><option value="">Select a facility</option>{displayed.facilities.filter(f=>f.countryCode==="US"&&f.regionCode==="CA"&&f.start===displayed.period.start&&f.endExclusive===displayed.period.endExclusive).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>
     <label>Vehicle source name<input required maxLength={120} value={mobileSource.name} onChange={e=>setMobileSource({...mobileSource,name:e.target.value})}/></label>
     <button type="submit">Add vehicle to draft</button>
    </fieldset>
   </form>}
   {displayed.entities.map(entity=>{const decision=displayed.boundaryDecisions.find(d=>d.entityId===entity.id);return <article className="worksheet-card worksheet-form" key={entity.id}><h2>{entity.legalName}</h2><p>{entity.regionCode} / {entity.countryCode}</p><fieldset disabled={!canEdit}><label>Entity name<input value={entity.legalName} onChange={e=>edit(n=>{n.entities.find(x=>x.id===entity.id)!.legalName=e.target.value})}/></label>{decision&&<><label>Boundary decision<select value={decision.disposition} onChange={e=>edit(n=>{n.boundaryDecisions.find(x=>x.id===decision.id)!.disposition=e.target.value as M71Disposition})}>{Object.entries(dispositions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Boundary rationale<textarea value={decision.reason??""} onChange={e=>edit(n=>{n.boundaryDecisions.find(x=>x.id===decision.id)!.reason=e.target.value||null})}/></label><label className="worksheet-check"><input type="checkbox" checked={decision.evidenceRefs.length>0} onChange={e=>void attach("boundary",decision.id,e.target.checked)}/>Link the supplied fictional screening reference</label></>}</fieldset><h3>Facilities and sources</h3>{displayed.facilities.filter(f=>f.entityId===entity.id).map(f=><div key={f.id}><p>{f.name} · {f.regionCode} / {f.countryCode}</p><ul>{displayed.sources.filter(s=>s.facilityId===f.id).map(s=><li key={s.id}>{s.name} · {domainName(s.domain)}</li>)}</ul></div>)}</article>})}
   {canEdit&&<form className="worksheet-card worksheet-form" onSubmit={addOperation}><h2>Add an operation to assess</h2><p>Use fictional records only. Include operations needed for the company boundary, wherever located. Unsupported activity remains a gap.</p><fieldset disabled={busy}><label>Operation name<input value={operation.name} onChange={e=>setOperation({...operation,name:e.target.value})}/></label><label>Facility name<input value={operation.facility} onChange={e=>setOperation({...operation,facility:e.target.value})}/></label><div className="coverage-grid"><label>Country code<input maxLength={2} value={operation.country} onChange={e=>setOperation({...operation,country:e.target.value.toUpperCase()})}/></label><label>State or region code<input value={operation.region} onChange={e=>setOperation({...operation,region:e.target.value.toUpperCase()})}/></label></div><button type="submit">Add to draft</button></fieldset></form>}
  </>}
  {panel==="coverage"&&<><h2>Scope 1 and 2 source screening</h2><div className="coverage-grid">{displayed.coverageItems.filter(r=>!r.domain.startsWith("scope3_")).map(row=><button type="button" key={row.id} aria-pressed={selected===row.id} onClick={()=>setSelected(row.id)}>{domainName(row.domain)}{row.sourceId?` · ${displayed.facilities.find(f=>f.id===displayed.sources.find(s=>s.id===row.sourceId)?.facilityId)?.name??"Source detail"}`:""}<br/>{dispositions[row.disposition]}</button>)}</div><h2>All 15 Scope 3 categories</h2><div className="coverage-grid">{displayed.coverageItems.filter(r=>r.domain.startsWith("scope3_")).sort((a,b)=>Number(a.domain.slice(7))-Number(b.domain.slice(7))).map(row=><button type="button" key={row.id} aria-pressed={selected===row.id} onClick={()=>setSelected(row.id)}>{domainName(row.domain)}<br/>{dispositions[row.disposition]}</button>)}</div>
   {selectedItem&&<article className="worksheet-card worksheet-form"><h2>{domainName(selectedItem.domain)}</h2><p>Method: {words(selectedItem.methodReadiness)} · Emissions unavailable. Linking a reference does not establish sufficient evidence.</p><fieldset disabled={!canEdit}><label>Proposed category decision<select value={selectedItem.disposition} onChange={e=>{const value=e.target.value as M71Disposition;updateItem({disposition:value,estimateBasis:value==="included_estimate"?{methodVersionId:"synthetic-estimate-proposal-v1",assumptions:"",inputEvidenceRefs:[],uncertainty:""}:null})}}>{Object.entries(dispositions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Screening rationale<textarea value={selectedItem.reason??""} onChange={e=>updateItem({reason:e.target.value||null})}/></label><div className="coverage-grid"><label>Activity data<select value={selectedItem.activityDataState} onChange={e=>updateItem({activityDataState:e.target.value as M71CoverageItem['activityDataState'],quantity:null,unit:null})}>{['not_assessed','missing','partial','entered','estimate_proposed','explicit_zero'].map(v=><option key={v} value={v}>{words(v)}</option>)}</select></label><label>Evidence status<select value={selectedItem.evidenceState} onChange={e=>updateItem({evidenceState:e.target.value as M71CoverageItem['evidenceState']})}>{['not_assessed','missing','partial','linked','conflicting'].map(v=><option key={v} value={v}>{words(v)}</option>)}</select></label></div><label className="worksheet-check"><input type="checkbox" checked={selectedItem.evidenceRefs.length>0} onChange={e=>void attach("coverage",selectedItem.id,e.target.checked)}/>Link supplied fictional screening reference</label>
   {selectedItem.activityDataState==="explicit_zero"&&<div className="coverage-grid"><label>Explicit quantity<input value={selectedItem.quantity??""} onChange={e=>updateItem({quantity:e.target.value||null})}/></label><label>Unit<input value={selectedItem.unit??""} onChange={e=>updateItem({unit:e.target.value||null})}/></label></div>}
   {selectedItem.estimateBasis&&<><label>Proposed estimate method<input value={selectedItem.estimateBasis.methodVersionId} onChange={e=>updateItem({estimateBasis:{...selectedItem.estimateBasis!,methodVersionId:e.target.value}})}/></label><label>Estimate assumptions<textarea value={selectedItem.estimateBasis.assumptions} onChange={e=>updateItem({estimateBasis:{...selectedItem.estimateBasis!,assumptions:e.target.value}})}/></label><label>Estimate uncertainty<textarea value={selectedItem.estimateBasis.uncertainty} onChange={e=>updateItem({estimateBasis:{...selectedItem.estimateBasis!,uncertainty:e.target.value}})}/></label><label className="worksheet-check"><input type="checkbox" checked={selectedItem.estimateBasis.inputEvidenceRefs.length>0} onChange={e=>void attach("estimate",selectedItem.id,e.target.checked)}/>Link fictional estimate input reference</label></>}
   </fieldset></article>}
  </>}
  {editing&&<form className="worksheet-card worksheet-form" onSubmit={e=>{e.preventDefault();void run("save")}}><h2>{latest?`Save correction to version ${latest.version}`:"Save the first coverage version"}</h2><p>Saving records these assertions and their gaps. It does not approve the inventory or evidence.</p><fieldset disabled={busy}>{latest&&<label>Reason for correction<textarea required value={reason} onChange={e=>setReason(e.target.value)}/></label>}<button type="submit">Save coverage version</button></fieldset></form>}
  {latest&&<details><summary>{latest.findings.length} recorded findings in saved version {latest.version}</summary><ul>{latest.findings.map((finding,i)=><li key={`${finding.code}:${finding.recordId}:${i}`}>{findingLabel(latest.snapshot,finding.recordId)}: {finding.message}</li>)}</ul></details>}
  {panel==="history"&&<><h2>Saved versions</h2>{saved?.versions.length?<><label className="coverage-version">View version<select value={historical?.id??""} onChange={e=>setHistoryId(e.target.value)}>{saved.versions.map(v=><option key={v.id} value={v.id}>Version {v.version} · {v.createdAt.slice(0,10)}</option>)}</select></label>{historical&&<article className="worksheet-card"><h2>Version {historical.version} · {historical.snapshot.companyLabel}</h2><p>{historical.snapshot.entities.length} entities · {historical.snapshot.facilities.length} facilities · {historical.snapshot.coverageItems.filter(c=>c.domain.startsWith('scope3_')).length} Scope 3 categories</p><p>Review: {historical.review?words(historical.review.decision):"Unreviewed"}. {historical.review?.note}</p>{historical.correctionReason&&<p>Correction: {historical.correctionReason}</p>}<button type="button" disabled={busy} onClick={()=>void exportVersion(historical)}>Download version {historical.version} coverage</button><p>The export is frozen at save and excludes subsequent review decisions. Current review is shown separately above.</p><details><summary>Saved boundary and screenings</summary><ul>{historical.snapshot.entities.map(e=><li key={e.id}>{e.legalName} · {e.regionCode} / {e.countryCode}</li>)}</ul><ul>{historical.snapshot.coverageItems.map(c=><li key={c.id}>{domainName(c.domain)}: {dispositions[c.disposition]} · {words(c.evidenceState)}</li>)}</ul></details><details><summary>Version fingerprint</summary><p className="worksheet-fingerprint">{historical.versionSha256}</p></details></article>}</>:<p>No versions saved yet.</p>}
   {reviewAllowed&&<form className="worksheet-card worksheet-form" onSubmit={e=>{e.preventDefault();void run("review")}}><h2>Review current version {latest.version}</h2><fieldset disabled={busy}><label>Internal decision<select value={reviewDecision} onChange={e=>setReviewDecision(e.target.value as typeof reviewDecision)}><option value="accepted_bounded_internal">Accept bounded internal register</option><option value="changes_requested">Request changes</option></select></label><label>Review note<textarea required value={reviewNote} onChange={e=>setReviewNote(e.target.value)}/></label>{<><ul>{limits.map(l=><li key={l}>{l}</li>)}</ul><label className="worksheet-check"><input type="checkbox" required checked={acknowledged} onChange={e=>setAcknowledged(e.target.checked)}/>I acknowledge these limits and have reviewed the unresolved findings.</label></>}<button type="submit">Save internal review</button></fieldset></form>}
   {latest&&latest.contributorIds.includes(actor.userId)&&<p>A manager who has not contributed to this version or its predecessors must perform the internal review.</p>}
  </>}
  <details><summary>Supplied fictional reference</summary><p>{M71_ARTIFACT.text}</p><p>Locator: {M71_ARTIFACT.locator}. This does not establish activity quantities or legal applicability.</p></details>
  <p className="worksheet-footnote">California reporting is the first product focus. Company operations elsewhere remain part of boundary assessment when relevant. This synthetic register has no released calculation methods, filing determination or external assurance.</p>
 </section>
}
