import { useCallback, useEffect, useRef, useState, type RefObject } from "react"
import type { HostedWorkspaceActor } from "@/lib/workspace-api"
import { M74_LIMITATIONS, M74_PERIOD, M74_PROFILE, type M74Register, type M74SaveInput, type M74Version, type M74Report } from "../../../../packages/neuvetra-database/src/m74-contract"
import { validateM74Save } from "../../../../packages/neuvetra-database/src/m74-validation"
import { mobileRegisterRequest, mobileSaveRequest, mobileReviewRequest, mobileReportRequest, mobileReportDownload, mobileStatementDownload, mobileExportRequest } from "@/lib/m74-api"

const emptyForm = () => ({ assetId: "", modelYear: "2018", classification: "", quantity: "", distance: "", fuelStatement: true, mileageStatement: true, fuelIssuer: "Synthetic fleet operator", mileageIssuer: "Synthetic fleet operator", fuelReference: "SYN-FUEL-2025-001", mileageReference: "SYN-MILES-2025-001", statedFuel: "", statedMileage: "", fuelDescription: "Fictional annual fossil diesel consumed by this vehicle alone, without stock or shared-fuel adjustments.", mileageDescription: "Fictional actual annual vehicle distance, including every trip location and interstate travel.", fuelConfirmed: false, mileageConfirmed: false, fuelDiscrepancy: "", mileageDiscrepancy: "", zero: "", reason: "" })
const words = (value: string) => value.replace(/_/g, " ")
function download(text: string, name: string, type: string) { const url = URL.createObjectURL(new Blob([text], { type })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }

export function MobileDiesel({ actor, workspaceId, headingRef }: { actor: HostedWorkspaceActor; workspaceId: string | null; headingRef: RefObject<HTMLHeadingElement | null> }) {
  const [register, setRegister] = useState<M74Register | null>(null), [streamId, setStreamId] = useState(""), [sourceId, setSourceId] = useState(""), [versionId, setVersionId] = useState("")
  const [form, setForm] = useState(emptyForm), [editing, setEditing] = useState(false), [busy, setBusy] = useState(true), [error, setError] = useState(false), [message, setMessage] = useState("Loading mobile sources…")
  const [reviewNote, setReviewNote] = useState(""), [decision, setDecision] = useState<"accepted_bounded_internal" | "changes_requested">("accepted_bounded_internal"), [ack, setAck] = useState(false)
  const [scope, setScope] = useState({ actor, workspaceId })
  const lifetime = useRef({ active: true, scope }), lock = useRef(false), retry = useRef<{ signature: string; key: string } | null>(null), reportCleanup = useRef<(() => void) | null>(null)
  const manager = actor.role !== "member", stream = register?.worksheets.find(w => w.worksheetId === streamId), latest = stream?.versions[stream.versions.length - 1], selected = stream?.versions.find(v => v.id === versionId) ?? latest
  const choice = register?.sources.find(s => s.binding.sourceId === sourceId)
  const scopeMatches = scope.actor === actor && scope.workspaceId === workspaceId
  const active = () => lifetime.current.active && lifetime.current.scope === scope && scopeMatches && !actor.signal?.aborted
  const accept = useCallback((value: M74Register, preferred = "") => { setRegister(value); const next = value.worksheets.find(w => w.worksheetId === preferred) ?? value.worksheets[0]; setStreamId(next?.worksheetId ?? ""); setVersionId(next?.headVersionId ?? ""); setSourceId(next?.sourceId ?? value.sources.find(s => s.eligible)?.binding.sourceId ?? ""); setEditing(false); setAck(false); setReviewNote("") }, [])
  useEffect(() => { const state = { active: true, scope }; lifetime.current = state; lock.current = false; retry.current = null;  void (async () => { try { if (!workspaceId) { setMessage("No company workspace is assigned."); return } const value = await mobileRegisterRequest(actor, workspaceId); if (state.active && !actor.signal?.aborted) { accept(value); setMessage("Select a saved vehicle or create a mobile source draft.") } } catch (e) { if (state.active && !actor.signal?.aborted) { setError(true); setMessage(e instanceof Error ? e.message : "Mobile sources unavailable.") } } finally { if (state.active && !actor.signal?.aborted) setBusy(false) } })(); return () => { state.active = false; reportCleanup.current?.(); reportCleanup.current = null } }, [actor, workspaceId, accept, scope])
  if (!scopeMatches) { setScope({ actor, workspaceId }); setRegister(null); setStreamId(""); setSourceId(""); setVersionId(""); setForm(emptyForm()); setEditing(false); setBusy(true); setError(false); setAck(false); setReviewNote(""); setDecision("accepted_bounded_internal"); setMessage("Loading mobile sources…"); }
  function patch(change: Partial<ReturnType<typeof emptyForm>>) { setForm(old => ({ ...old, ...change })); setError(false) }
  function start(version?: M74Version) {
    if (busy || !manager || !active()) return
    setEditing(true); setError(false); setAck(false); setReviewNote("")
    if (version) { const a = version.activity; setSourceId(a.binding.sourceId); setForm({ assetId: a.vehicle.assetId, modelYear: String(a.vehicle.modelYear), classification: a.vehicle.classificationBasis, quantity: a.quantityGallons ?? "", distance: a.distanceMiles ?? "", fuelStatement: a.fuelStatement !== null, mileageStatement: a.mileageStatement !== null, fuelIssuer: a.fuelStatement?.issuer ?? "", mileageIssuer: a.mileageStatement?.issuer ?? "", fuelReference: a.fuelStatement?.reference ?? "", mileageReference: a.mileageStatement?.reference ?? "", statedFuel: a.fuelStatement?.statedQuantityGallons ?? "", statedMileage: a.mileageStatement?.statedDistanceMiles ?? "", fuelDescription: a.fuelStatement?.description ?? "", mileageDescription: a.mileageStatement?.description ?? "", fuelConfirmed: false, mileageConfirmed: false, fuelDiscrepancy: a.fuelDiscrepancyReason ?? "", mileageDiscrepancy: a.mileageDiscrepancyReason ?? "", zero: a.zeroReason ?? "", reason: "" }) }
    else { setStreamId(""); setVersionId(""); setForm(emptyForm()); setSourceId(register?.sources.find(s => s.eligible && !register.worksheets.some(w => w.sourceId === s.binding.sourceId))?.binding.sourceId ?? "") }
    setMessage("Unsaved draft. Missing evidence or activity will remain incomplete, with no calculated subtotal.")
  }
  async function action(kind: string, work: (key: string) => Promise<void>, payload: unknown) {
    if (!workspaceId || lock.current || !active()) return
    lock.current = true; setBusy(true); setError(false)
    try { const signature = JSON.stringify({ kind, payload }); if (retry.current?.signature !== signature) retry.current = { signature, key: crypto.randomUUID() }; await work(retry.current.key); if (active()) retry.current = null }
    catch (e) { if (active()) { setError(true); setMessage(e instanceof Error ? e.message : "This action could not be completed.") } }
    finally { if (active()) { lock.current = false; setBusy(false) } }
  }
  async function save() {
    if (!manager || !active()) return
    if (!workspaceId || !choice?.eligible) { setError(true); setMessage("Save a supported mobile source and its boundary rationale in Corporate coverage first."); return }
    const input: Omit<M74SaveInput, "idempotencyKey"> = { profile: M74_PROFILE, binding: choice.binding, period: M74_PERIOD, vehicle: { assetId: form.assetId, vehicleClass: "Medium- and Heavy-Duty Vehicles", classificationBasis: form.classification, modelYear: Number(form.modelYear), fuel: "Fossil Diesel", controlBasis: "owned_operational_control_full_year" }, quantityGallons: form.quantity || null, distanceMiles: form.distance || null, fuelStatement: form.fuelStatement ? { issuer: form.fuelIssuer, reference: form.fuelReference, statedQuantityGallons: form.statedFuel, description: form.fuelDescription, consumptionBasis: "dedicated_vehicle_consumed_no_adjustments" } : null, mileageStatement: form.mileageStatement ? { issuer: form.mileageIssuer, reference: form.mileageReference, statedDistanceMiles: form.statedMileage, description: form.mileageDescription, distanceBasis: "dedicated_vehicle_annual_distance" } : null, fuelManualConfirmation: form.fuelStatement && form.fuelConfirmed, mileageManualConfirmation: form.mileageStatement && form.mileageConfirmed, fuelDiscrepancyReason: form.fuelDiscrepancy || null, mileageDiscrepancyReason: form.mileageDiscrepancy || null, zeroReason: form.zero || null, expectedVersionId: latest?.id ?? null, expectedVersionSha256: latest?.versionSha256 ?? null, correctionReason: latest ? form.reason : null }
    try { validateM74Save({ ...input, idempotencyKey: crypto.randomUUID() }) } catch { setError(true); setMessage("Check vehicle identity and classification, model year 2007–2022, and both statements. Quantities must be non-negative decimals with up to 12 whole digits and 3 decimal places. Nothing was saved."); return }
    await action("save", async key => { const v = await mobileSaveRequest(actor, workspaceId, stream?.worksheetId ?? null, { ...input, idempotencyKey: key }); const fresh = await mobileRegisterRequest(actor, workspaceId); if (active()) { accept(fresh, v.worksheetId); setMessage(v.calculation ? "Vehicle version saved with a source subtotal. Separate review and corporate reconciliation remain." : "Vehicle version saved as incomplete. No subtotal was calculated.") } }, input)
  }
  async function review() { if (!manager || !active() || !workspaceId || !stream || !latest || selected?.id !== latest.id) return; const input = { versionId: latest.id, expectedVersionSha256: latest.versionSha256, decision, note: reviewNote, acknowledgedLimitations: ack ? [...M74_LIMITATIONS] : [] }; await action("review", async key => { await mobileReviewRequest(actor, workspaceId, stream.worksheetId, { ...input, idempotencyKey: key }); const fresh = await mobileRegisterRequest(actor, workspaceId); if (active()) { accept(fresh, streamId); setMessage("Internal decision saved for the exact vehicle version. Open findings remain.") } }, input) }
  async function createReport() { if (!manager || !active() || !workspaceId || !stream || !selected) return; const input = { versionId: selected.id, expectedVersionSha256: selected.versionSha256, expectedDecisionId: selected.review?.id ?? null, expectedDecisionSha256: selected.review?.decisionSha256 ?? null }; await action("report", async key => { await mobileReportRequest(actor, workspaceId, stream.worksheetId, { ...input, idempotencyKey: key }); const fresh = await mobileRegisterRequest(actor, workspaceId); if (active()) { accept(fresh, streamId); setVersionId(selected.id); setMessage("Exact-version vehicle report retained.") } }, input) }
  async function reportFile(report: M74Report, mode: "download" | "open" | "print") {
    if (!workspaceId || !stream) return
    await action("report-file", async () => {
      const html = await mobileReportDownload(actor, workspaceId, stream.worksheetId, report); if (!active()) return
      if (mode === "download") { download(html, `mobile-diesel-report-${report.id}.html`, "text/html;charset=utf-8"); setMessage("Exact retained HTML downloaded."); return }
      reportCleanup.current?.(); const before = document.activeElement instanceof HTMLElement ? document.activeElement : null
      const dialog = document.createElement("dialog"); dialog.setAttribute("aria-label", "Mobile diesel source report"); dialog.style.cssText = "width:90vw;max-width:1050px;height:90vh;padding:12px;background:white;color:#172f2c;border:2px solid #667085"
      const frame = document.createElement("iframe"); frame.title = "Mobile diesel source report"; frame.setAttribute("sandbox", "allow-same-origin allow-modals"); frame.style.cssText = "display:block;width:100%;height:90%;border:0;background:white"
      const close = document.createElement("button"); close.textContent = "Close source report"; close.style.cssText = "padding:10px 16px;margin-bottom:10px;font:inherit"
      const cleanup = () => { dialog.remove(); if (active()) before?.focus() }; reportCleanup.current = cleanup
      dialog.addEventListener("cancel", () => { cleanup(); reportCleanup.current = null }); close.onclick = () => { cleanup(); reportCleanup.current = null }
      frame.onload = () => { if (mode === "print" && active()) { try { frame.contentWindow?.print(); setMessage("Print preview requested for the exact retained vehicle report.") } catch { setError(true); setMessage("Print preview could not open. Download the retained HTML report to print from a browser tab.") } } }
      frame.srcdoc = html; dialog.append(close, frame); document.body.append(dialog); dialog.showModal(); close.focus()
      if (mode === "open") setMessage("Exact retained report opened. Close source report returns to the worksheet.")
    }, report.id)
  }
  const canReview = manager && latest && selected?.id === latest.id && !editing && !latest.review && !latest.contributorIds.includes(actor.userId)
  if (!scopeMatches) return <section className="worksheet"><h1 ref={headingRef} tabIndex={-1}>Mobile diesel vehicles</h1><p role="status">Loading mobile sources…</p></section>
  return <section className="worksheet mobile-diesel">
    <p className="worksheet-eyebrow">California reporting · Private synthetic workspace</p><h1 ref={headingRef} tabIndex={-1}>Mobile diesel vehicles</h1>
    <p>Retain separate annual fuel and mileage evidence for one owned, controlled vehicle. All travel locations are included.</p>
    <div className="worksheet-context"><span>2025 calendar year</span><span>California base · Operational control</span><span>Vehicle subtotal · Inventory incomplete</span></div>
    <p role={error ? "alert" : "status"} className={error ? "worksheet-error" : "worksheet-status"}>{message}</p>
    <div className="worksheet-report-actions"><button disabled={busy || editing} onClick={() => void action("refresh", async () => { if (workspaceId) { const value = await mobileRegisterRequest(actor, workspaceId); if (active()) { accept(value, streamId); setMessage("Saved mobile sources refreshed.") } } }, null)}>Refresh mobile sources</button>{manager && <button disabled={busy || editing} onClick={() => start()}>Create vehicle draft</button>}{manager && latest && !editing && <button disabled={busy} onClick={() => start(latest)}>Make a correction</button>}{editing && <button disabled={busy} onClick={() => { setEditing(false); setError(false); setMessage("Unsaved draft discarded.") }}>Cancel draft</button>}</div>
    {!manager && <p>Read-only member access. A manager can save or review vehicle activity.</p>}
    {!editing && register && <label className="coverage-version" htmlFor="mobile-saved">Saved vehicle<select id="mobile-saved" disabled={busy} value={streamId} onChange={e => { setStreamId(e.target.value); const w = register.worksheets.find(w => w.worksheetId === e.target.value); setVersionId(w?.headVersionId ?? ""); setSourceId(w?.sourceId ?? ""); setAck(false); setReviewNote("") }}><option value="">Select a saved vehicle</option>{register.worksheets.map(w => <option key={w.worksheetId} value={w.worksheetId}>{w.vehicleAssetId} · {register.sources.find(s => s.binding.sourceId === w.sourceId)?.sourceLabel ?? "Historical source"}</option>)}</select></label>}
    {editing && <form className="worksheet-card worksheet-form" onSubmit={e => { e.preventDefault(); void save() }}><h2>{latest ? "Correct vehicle activity" : "Create vehicle draft"}</h2><fieldset disabled={busy}>
      <label htmlFor="mobile-source">Source and reporting boundary<select id="mobile-source" required disabled={!!latest} value={sourceId} onChange={e => setSourceId(e.target.value)}><option value="">Select a saved mobile source</option>{register?.sources.filter(s => !latest || s.binding.sourceId === latest.activity.binding.sourceId).map(s => <option key={s.binding.sourceId} value={s.binding.sourceId} disabled={!s.eligible || !latest && register.worksheets.some(w => w.sourceId === s.binding.sourceId)}>{s.facilityLabel} · {s.sourceLabel}{s.eligible ? "" : " · Boundary needs attention"}</option>)}</select></label>
      {choice && <p>{choice.companyLabel} · {choice.entityLabel} · {choice.facilityLabel}</p>}{choice?.findings.map(f => <p key={f.code}>{f.message}</p>)}
      <p>Supported: owned medium/heavy on-road vehicle under operational control throughout 2025, model year 2007–2022, fossil diesel only. No blends, renewable diesel, pooled fleet quantities, off-road or auxiliary-engine activity.</p>
      <label htmlFor="mobile-asset">Vehicle asset ID<input id="mobile-asset" required maxLength={64} disabled={!!latest} value={form.assetId} onChange={e => patch({ assetId: e.target.value })}/></label><p>Use the same stable ID across names and records. It cannot be changed after the first save.</p>
      <label htmlFor="mobile-year">Vehicle model year<input id="mobile-year" required type="number" min={2007} max={2022} step={1} value={form.modelYear} onChange={e => patch({ modelYear: e.target.value, fuelConfirmed: false, mileageConfirmed: false })}/></label>
      <label htmlFor="mobile-classification">Vehicle classification and control facts<textarea id="mobile-classification" required maxLength={500} value={form.classification} onChange={e => patch({ classification: e.target.value, fuelConfirmed: false, mileageConfirmed: false })}/></label>
      <p>Record why this vehicle belongs to the supported class and was owned and operationally controlled for the full year. Unknown facts must be resolved before using this method.</p>
      <label htmlFor="mobile-gallons">Consumed fossil diesel (U.S. gallons)<input id="mobile-gallons" inputMode="decimal" value={form.quantity} onChange={e => patch({ quantity: e.target.value, fuelConfirmed: false })}/></label>
      <label htmlFor="mobile-miles">Actual distance (vehicle-miles)<input id="mobile-miles" inputMode="decimal" value={form.distance} onChange={e => patch({ distance: e.target.value, mileageConfirmed: false })}/></label>
      <p>Blank means missing, never zero. Up to 12 whole digits and 3 decimal places. Both dimensions and their confirmed statements are required for a subtotal. Include interstate travel.</p>
      {(["fuel", "mileage"] as const).map(kind => { const fuel = kind === "fuel"; return <div key={kind}>
        <h3>{fuel ? "Fuel evidence" : "Mileage evidence"}</h3>
        <label className="worksheet-check" htmlFor={`mobile-${kind}-retain`}><input id={`mobile-${kind}-retain`} type="checkbox" checked={fuel ? form.fuelStatement : form.mileageStatement} onChange={e => patch(fuel ? { fuelStatement: e.target.checked, fuelConfirmed: false } : { mileageStatement: e.target.checked, mileageConfirmed: false })}/>Retain a fictional {kind} statement</label>
        {(fuel ? form.fuelStatement : form.mileageStatement) && <><p>Manually entered synthetic text; not an uploaded or authenticated record.</p>
          <label htmlFor={`mobile-${kind}-issuer`}>{fuel ? "Fuel" : "Mileage"} statement issuer<input id={`mobile-${kind}-issuer`} required maxLength={120} value={fuel ? form.fuelIssuer : form.mileageIssuer} onChange={e => patch(fuel ? { fuelIssuer: e.target.value, fuelConfirmed: false } : { mileageIssuer: e.target.value, mileageConfirmed: false })}/></label>
          <label htmlFor={`mobile-${kind}-reference`}>{fuel ? "Fuel" : "Mileage"} statement reference<input id={`mobile-${kind}-reference`} required maxLength={120} value={fuel ? form.fuelReference : form.mileageReference} onChange={e => patch(fuel ? { fuelReference: e.target.value, fuelConfirmed: false } : { mileageReference: e.target.value, mileageConfirmed: false })}/></label>
          <label htmlFor={`mobile-${kind}-stated`}>{fuel ? "Statement consumed U.S. gallons" : "Statement actual vehicle-miles"}<input id={`mobile-${kind}-stated`} required inputMode="decimal" value={fuel ? form.statedFuel : form.statedMileage} onChange={e => patch(fuel ? { statedFuel: e.target.value, fuelConfirmed: false } : { statedMileage: e.target.value, mileageConfirmed: false })}/></label>
          <label htmlFor={`mobile-${kind}-description`}>{fuel ? "Fuel" : "Mileage"} statement description<textarea id={`mobile-${kind}-description`} required maxLength={2000} value={fuel ? form.fuelDescription : form.mileageDescription} onChange={e => patch(fuel ? { fuelDescription: e.target.value, fuelConfirmed: false } : { mileageDescription: e.target.value, mileageConfirmed: false })}/></label>
          <label className="worksheet-check" htmlFor={`mobile-${kind}-confirm`}><input id={`mobile-${kind}-confirm`} type="checkbox" checked={fuel ? form.fuelConfirmed : form.mileageConfirmed} onChange={e => patch(fuel ? { fuelConfirmed: e.target.checked } : { mileageConfirmed: e.target.checked })}/>{fuel ? "I confirmed this vehicle, year and fossil-only diesel consumed, without shared-fuel or stock adjustments." : "I confirmed actual annual miles for this vehicle, including all trip locations, with no estimation or extrapolation."}</label>
        </>}
        <label htmlFor={`mobile-${kind}-discrepancy`}>{fuel ? "Fuel" : "Mileage"} discrepancy explanation<textarea id={`mobile-${kind}-discrepancy`} maxLength={500} value={fuel ? form.fuelDiscrepancy : form.mileageDiscrepancy} onChange={e => patch(fuel ? { fuelDiscrepancy: e.target.value } : { mileageDiscrepancy: e.target.value })}/></label>
      </div> })}
      <p>Each discrepancy requires its own explanation and remains unresolved. Zero in only one dimension is outside this method and produces no subtotal.</p>
      <label htmlFor="mobile-zero">No-operation and no-consumption reason (for both zero)<textarea id="mobile-zero" maxLength={500} value={form.zero} onChange={e => patch({ zero: e.target.value })}/></label>
      {latest && <label htmlFor="mobile-correction">Correction reason<textarea id="mobile-correction" required maxLength={500} value={form.reason} onChange={e => patch({ reason: e.target.value })}/></label>}
      <button type="submit">Save vehicle version</button>
    </fieldset></form>}
    {!editing && selected && stream && <><label className="coverage-version" htmlFor="mobile-version">View vehicle version<select id="mobile-version" disabled={busy} value={selected.id} onChange={e => { setVersionId(e.target.value); setAck(false); setReviewNote("") }}>{stream.versions.map(v => <option key={v.id} value={v.id}>Version {v.version} · {v.createdAt.slice(0, 10)}</option>)}</select></label>
      <article className="worksheet-card"><h2>Vehicle {selected.activity.vehicle.assetId} · Version {selected.version}</h2><p>{selected.activity.vehicle.vehicleClass} · Model year {selected.activity.vehicle.modelYear}</p><p>{selected.activity.vehicle.classificationBasis}</p><p>Consumed diesel: {selected.activity.quantityGallons ?? "Missing"} U.S. gallons · {words(selected.activityStatus.fuel)}</p><p>Actual distance: {selected.activity.distanceMiles ?? "Missing"} vehicle-miles · {words(selected.activityStatus.mileage)}</p>
        {selected.calculation ? <><p>Exact vehicle subtotal: <strong>{selected.calculation.total.unrounded} kg CO2e</strong></p><p>Displayed vehicle subtotal: {selected.calculation.total.display} kg CO2e</p><details><summary>Gas results and calculation trace</summary><table><thead><tr><th>Gas</th><th>Mass</th><th>CO2e</th></tr></thead><tbody>{Object.entries(selected.calculation.gasResults).map(([gas, r]) => <tr key={gas}><th>{gas.toUpperCase()}</th><td>{r.mass} {r.massUnit}</td><td>{r.co2e} {r.co2eUnit}</td></tr>)}</tbody></table><p>CO2 uses consumed gallons; CH4 and N2O use actual miles. Final display uses four decimals, half-even rounding; intermediate values are unrounded.</p><pre>{JSON.stringify(selected.calculation.method, null, 2)}</pre></details></> : <p>Activity incomplete · No calculated subtotal.</p>}
        <p>Development candidate · Not released. Vehicle combustion only; upstream fuel and auxiliary/fugitive emissions are excluded.</p>
        {selected.findings.map(f => <p key={f.code}>{f.message}</p>)}{selected.activity.fuelDiscrepancyReason && <p>Fuel discrepancy — unresolved: {selected.activity.fuelDiscrepancyReason}</p>}{selected.activity.mileageDiscrepancyReason && <p>Mileage discrepancy — unresolved: {selected.activity.mileageDiscrepancyReason}</p>}{selected.activity.zeroReason && <p>No-operation basis: {selected.activity.zeroReason}</p>}{selected.correctionReason && <p>Correction: {selected.correctionReason}</p>}<p>Review: {selected.review ? words(selected.review.decision) : "Unreviewed"}. {selected.review?.note}</p>
        {(["fuel", "mileage"] as const).map(kind => { const statement = kind === "fuel" ? selected.fuelStatement : selected.mileageStatement; if (!statement) return null; return <details key={kind}><summary>{kind === "fuel" ? "Fuel" : "Mileage"} supporting evidence</summary><p>Fictional annual statement · {statement.input.issuer} · {statement.input.reference}</p><p>{statement.input.description}</p><p>Manual confirmation: {(kind === "fuel" ? selected.activity.fuelManualConfirmation : selected.activity.mileageManualConfirmation) ? "Confirmed" : "Not confirmed"}</p><pre>{statement.text}</pre><p className="worksheet-fingerprint">{statement.sha256}</p><button disabled={busy} onClick={() => void action(`statement-${kind}`, async () => { if (workspaceId) { const text = await mobileStatementDownload(actor, workspaceId, stream.worksheetId, selected, kind); if (active()) download(text, `mobile-${kind}-${statement.id}.txt`, "text/plain;charset=utf-8") } }, selected.id)}>Download {kind} statement</button></details> })}
        <details><summary>Version fingerprint</summary><p className="worksheet-fingerprint">{selected.versionSha256}</p><p>Coverage version: {selected.activity.binding.coverageVersionId}</p></details>
        <button disabled={busy} onClick={() => void action("export", async () => { if (workspaceId) { const text = await mobileExportRequest(actor, workspaceId, selected); if (active()) download(text, `mobile-diesel-version-${selected.version}.json`, "application/json") } }, selected.id)}>Download calculation record</button>{manager && <button disabled={busy} onClick={() => void createReport()}>Create vehicle report</button>}
      </article></>}
    {canReview && <form className="worksheet-card worksheet-form" onSubmit={e => { e.preventDefault(); void review() }}><h2>Review vehicle version {latest.version}</h2><fieldset disabled={busy}><label htmlFor="mobile-decision">Internal decision<select id="mobile-decision" value={decision} onChange={e => setDecision(e.target.value as typeof decision)}><option value="accepted_bounded_internal" disabled={!latest.calculation}>Accept for bounded internal use</option><option value="changes_requested">Request changes</option></select></label><label htmlFor="mobile-review-note">Review note<textarea id="mobile-review-note" required maxLength={500} value={reviewNote} onChange={e => setReviewNote(e.target.value)}/></label><ul>{M74_LIMITATIONS.map(l => <li key={l}>{words(l)}</li>)}</ul><label className="worksheet-check" htmlFor="mobile-review-ack"><input id="mobile-review-ack" type="checkbox" required checked={ack} onChange={e => setAck(e.target.checked)}/>I reviewed this exact vehicle version and acknowledge all listed limitations.</label><button type="submit" disabled={decision === "accepted_bounded_internal" && !latest.calculation}>Save internal vehicle review</button></fieldset></form>}
    {latest?.contributorIds.includes(actor.userId) && <p>A manager who has not contributed to this vehicle history or linked boundary must perform the internal review.</p>}
    {!editing && stream?.reports.filter(r => r.versionId === selected?.id).map(r => <article className="worksheet-card" key={r.id}><h2>Retained vehicle report</h2><p>{r.decisionId ? "Reviewed snapshot" : "Unreviewed snapshot"} · {r.createdAt}</p><div className="worksheet-report-actions"><button disabled={busy} onClick={() => void reportFile(r, "open")}>Open report</button><button disabled={busy} onClick={() => void reportFile(r, "print")}>Print report</button><button disabled={busy} onClick={() => void reportFile(r, "download")}>Download HTML</button></div><p className="worksheet-fingerprint">{r.htmlSha256}</p></article>)}
    <article className="worksheet-card"><h2>Corporate coverage remains incomplete</h2><p>This vehicle workpaper does not reconcile the fleet or complete stationary combustion, refrigerants, process emissions or corporate Scope 1. Scope 2, all 15 Scope 3 categories and applicable reporting requirements remain separate assessments.</p>{stream?.findings.map(f => <p key={f.code}>{f.message}</p>)}<details><summary>{register?.coverageFindings.length ?? 0} recorded open findings in current corporate coverage</summary><ul>{register?.coverageFindings.map((f, i) => <li key={`${f.code}:${i}`}>{f.message}</li>)}</ul></details></article>
    <p className="worksheet-footnote">Synthetic workpaper only. No released method, filing determination or external assurance.</p>
  </section>
}
