import {M78_CATEGORIES,type M78GasCoverage,type M78ProcessActivity,type M78ProcessLocation,type M78ProcessAssessment,type M78EvidenceInput,type M78Register} from '../../../../packages/neuvetra-database/src/m78-contract'
import {processCategoryLabels,toggleId} from '@/lib/m78-form'

type Props={value:M78ProcessActivity;register:M78Register;onChange:(value:M78ProcessActivity)=>void;disabled:boolean}
export function ProcessScreenEditor({value,register,onChange,disabled}:Props){
  const coverage=register.coverageVersion.snapshot
  const patch=(next:Partial<M78ProcessActivity>)=>onChange({...value,...next})
  const declaration=value.declaration??{completeness:'unknown' as const,coveredEntityIds:[],coveredFacilityIds:[],allControlledOperationsIncluded:false,discoveryBasis:''}
  const location=(index:number,next:Partial<M78ProcessLocation>)=>patch({locations:value.locations.map((row,i)=>i===index?{...row,...next}:row)})
  const assessment=(index:number,next:Partial<M78ProcessAssessment>)=>patch({assessments:value.assessments.map((row,i)=>i===index?{...row,...next}:row)})
  const evidence=(index:number,next:Partial<M78EvidenceInput>)=>patch({evidenceStatements:value.evidenceStatements.map((row,i)=>i===index?{...row,...next}:row)})
  const earlier=register.process.versions.flatMap(version=>version.activity.profile==='synthetic-process-screen-v1'?version.activity.assessments:[])
  const retainedIndicatedIds=new Set(earlier.filter(row=>row.disposition==='indicated').map(row=>row.rowId))
  const retainedLocations=new Set(register.process.versions.flatMap(version=>version.activity.profile==='synthetic-process-screen-v1'?version.activity.locations.map(row=>row.rowId):[]))
  const gas=(index:number,next:Partial<M78GasCoverage>)=>patch({gasCoverage:value.gasCoverage.map((row,i)=>i===index?{...row,...next}:row)})
  const locationLabel=(row:M78ProcessLocation)=>`${coverage.entities.find(entity=>entity.id===row.entityId)?.legalName??'Entity not selected'} · ${coverage.facilities.find(facility=>facility.id===row.facilityId)?.name??row.operationId??'Location not selected'}`
  const references=(values:string[],change:(next:string[])=>void)=>value.evidenceStatements.map((statement,index)=><label className="stationary-check" key={index}><input type="checkbox" disabled={!statement.reference} checked={values.includes(statement.reference)} onChange={event=>change(toggleId(values,statement.reference,event.target.checked))}/>{statement.reference||'Enter an evidence reference'} · {statement.description||'Description missing'}</label>)
  return <fieldset disabled={disabled} className="stationary-editor scope1-process-editor"><legend>Process discovery and evidence</legend>
    <p>Inspect every controlled location and off-site operation. A blank list does not establish that process emissions are absent. New statements in this demonstration are fictional evidence and remain labeled as such.</p>
    <div className="stationary-fields">
      <label>Discovery completeness<select value={declaration.completeness} onChange={event=>patch({declaration:{...declaration,completeness:event.target.value as typeof declaration.completeness}})}><option value="unknown">Unknown</option><option value="partial">Partial discovery</option><option value="declared_complete">All controlled operations inspected</option></select></label>
      <label>How operations were identified<textarea value={declaration.discoveryBasis} onChange={event=>patch({declaration:{...declaration,discoveryBasis:event.target.value}})}/></label>
    </div>
    <fieldset><legend>Entities inspected</legend>{coverage.entities.map(entity=><label className="stationary-check" key={entity.id}><input type="checkbox" checked={declaration.coveredEntityIds.includes(entity.id)} onChange={event=>patch({declaration:{...declaration,coveredEntityIds:toggleId(declaration.coveredEntityIds,entity.id,event.target.checked)}})}/>{entity.legalName}</label>)}</fieldset>
    <fieldset><legend>Facilities inspected</legend>{coverage.facilities.map(facility=><label className="stationary-check" key={facility.id}><input type="checkbox" checked={declaration.coveredFacilityIds.includes(facility.id)} onChange={event=>patch({declaration:{...declaration,coveredFacilityIds:toggleId(declaration.coveredFacilityIds,facility.id,event.target.checked)}})}/>{facility.name} · {coverage.entities.find(entity=>entity.id===facility.entityId)?.legalName??'Entity unavailable'}</label>)}</fieldset>
    <label className="stationary-check"><input type="checkbox" checked={declaration.allControlledOperationsIncluded} onChange={event=>patch({declaration:{...declaration,allControlledOperationsIncluded:event.target.checked}})}/>All controlled operations were considered, including activities away from fixed facilities.</label>

    <h3>Locations and activities</h3>
    {value.locations.map((row,index)=><details className="stationary-asset" key={row.rowId} open><summary>Location {index+1}: {locationLabel(row)}</summary><div className="stationary-fields">
      <label>Owning entity<select disabled={retainedLocations.has(row.rowId)} value={row.entityId} onChange={event=>location(index,{entityId:event.target.value,facilityId:null})}><option value="">Select entity</option>{coverage.entities.map(entity=><option key={entity.id} value={entity.id}>{entity.legalName}</option>)}</select></label>
      <label>Facility<select disabled={retainedLocations.has(row.rowId)} value={row.facilityId??''} onChange={event=>location(index,{facilityId:event.target.value||null,operationId:event.target.value?null:row.operationId})}><option value="">Off-site or non-facility operation</option>{coverage.facilities.filter(facility=>facility.entityId===row.entityId).map(facility=><option key={facility.id} value={facility.id}>{facility.name}</option>)}</select></label>
      {!row.facilityId&&<label>Off-site operation identifier<input disabled={retainedLocations.has(row.rowId)} value={row.operationId??''} onChange={event=>location(index,{operationId:event.target.value||null})}/></label>}
      <label>Business activities<textarea value={row.businessActivities} onChange={event=>location(index,{businessActivities:event.target.value})}/></label>
      <label>Equipment and materials inspected<textarea value={row.equipmentAndMaterials} onChange={event=>location(index,{equipmentAndMaterials:event.target.value})}/></label>
      <label>Control and operating-period explanation<textarea value={row.controlExplanation} onChange={event=>location(index,{controlExplanation:event.target.value})}/></label>
    </div><fieldset><legend>Supporting evidence for location {index+1}</legend>{references(row.evidenceReferences,next=>location(index,{evidenceReferences:next}))}</fieldset></details>)}
    <button type="button" disabled={value.locations.length>=25} onClick={()=>patch({locations:[...value.locations,{rowId:crypto.randomUUID(),entityId:'',facilityId:null,operationId:null,businessActivities:'',equipmentAndMaterials:'',controlExplanation:'',evidenceReferences:[]}]})}>Add inspected location or operation</button>

    <h3>Evidence statements</h3>
    {value.evidenceStatements.map((statement,index)=><details className="stationary-asset" key={index} open><summary>Evidence {index+1}: {statement.reference||'Reference needed'}</summary><div className="stationary-fields">
      <label>Reference<input value={statement.reference} onChange={event=>evidence(index,{reference:event.target.value})}/></label>
      <label>Issuer<input value={statement.issuer} onChange={event=>evidence(index,{issuer:event.target.value})}/></label>
      <label>Issue date<input type="date" value={statement.issuedOn} onChange={event=>evidence(index,{issuedOn:event.target.value})}/></label>
      <label>Purpose<select value={statement.purpose} onChange={event=>evidence(index,{purpose:event.target.value as M78EvidenceInput['purpose']})}><option value="business_activity">Business activity</option><option value="process_inspection">Process inspection</option><option value="offsite_discovery">Off-site discovery</option></select></label>
      <label>Entity<select value={statement.entityId} onChange={event=>evidence(index,{entityId:event.target.value,facilityId:null})}><option value="">Select entity</option>{coverage.entities.map(entity=><option key={entity.id} value={entity.id}>{entity.legalName}</option>)}</select></label>
      <label>Facility<select value={statement.facilityId??''} onChange={event=>evidence(index,{facilityId:event.target.value||null})}><option value="">Off-site or entity-wide evidence</option>{coverage.facilities.filter(facility=>facility.entityId===statement.entityId).map(facility=><option key={facility.id} value={facility.id}>{facility.name}</option>)}</select></label>
      <label>What the evidence establishes<textarea value={statement.description} onChange={event=>evidence(index,{description:event.target.value})}/></label>
    </div></details>)}
    <button type="button" disabled={value.evidenceStatements.length>=100} onClick={()=>patch({evidenceStatements:[...value.evidenceStatements,{reference:'',issuer:'',description:'',issuedOn:'',purpose:'process_inspection',entityId:'',facilityId:null}]})}>Add evidence statement</button>

    <h3>Process assessments</h3>
    <p>Proposed non-applicability requires supporting inspection evidence and separate review. Previously indicated sources remain part of the record.</p>
    {value.assessments.map((row,index)=><details className="stationary-asset" key={row.rowId} open><summary>{processCategoryLabels[row.category]} · assessment {index+1}</summary><div className="stationary-fields">
      <label>Category<select value={row.category} disabled={retainedIndicatedIds.has(row.rowId)} onChange={event=>assessment(index,{category:event.target.value as M78ProcessAssessment['category']})}>{M78_CATEGORIES.map(category=><option key={category} value={category}>{processCategoryLabels[category]}</option>)}</select></label>
      <label>Assessment<select disabled={retainedIndicatedIds.has(row.rowId)} value={row.disposition} onChange={event=>assessment(index,{disposition:event.target.value as M78ProcessAssessment['disposition']})}><option value="unknown">Unknown</option><option value="indicated">Potential process source identified</option><option value="not_applicable_proposed">Evidence supports proposed non-applicability</option></select></label>
      <label>Discovered source identifier<input disabled={retainedIndicatedIds.has(row.rowId)} value={row.discoveredSourceId??''} onChange={event=>assessment(index,{discoveredSourceId:event.target.value||null})}/></label>
      <label>Basis and unresolved conflicts<textarea value={row.reason??''} onChange={event=>assessment(index,{reason:event.target.value||null})}/></label>
    </div><fieldset><legend>Locations covered by assessment {index+1}</legend>{value.locations.map(locationRow=><label className="stationary-check" key={locationRow.rowId}><input type="checkbox" checked={row.locationRowIds.includes(locationRow.rowId)} onChange={event=>assessment(index,{locationRowIds:toggleId(row.locationRowIds,locationRow.rowId,event.target.checked)})}/>{locationLabel(locationRow)}</label>)}</fieldset><fieldset><legend>Assessment evidence</legend>{references(row.evidenceReferences,next=>assessment(index,{evidenceReferences:next}))}</fieldset>{retainedIndicatedIds.has(row.rowId)&&<p>This previously identified source cannot be removed or cleared through a renamed assessment.</p>}</details>)}
    <button type="button" disabled={value.assessments.length>=100} onClick={()=>patch({assessments:[...value.assessments,{rowId:crypto.randomUUID(),category:'other_direct_process',discoveredSourceId:null,locationRowIds:[],disposition:'unknown',reason:null,evidenceReferences:[]}]})}>Add another discovered process assessment</button>
    <h3>Seven-gas applicability</h3>
    <p>Check each gas group across every location and off-site operation. Include direct gas use and electrical equipment as well as manufacturing. Existing combustion and refrigerant sources must be linked explicitly.</p>
    {value.gasCoverage.map((row,index)=><details className="stationary-asset" key={row.gasGroup} open><summary>{row.gasGroup}</summary><div className="stationary-fields">
      <label>Applicability<select value={row.state} onChange={event=>gas(index,{state:event.target.value as M78GasCoverage['state']})}><option value="unknown">Unknown</option><option value="covered_by_sources">Covered by listed sources</option><option value="indicated">Additional source identified</option><option value="not_applicable_proposed">Evidence supports proposed non-applicability</option></select></label>
      <label>Additional discovered identifiers (comma separated)<input value={row.discoveredSourceIds.join(',')} onChange={event=>gas(index,{discoveredSourceIds:event.target.value.split(',')})}/></label>
      <label>Evidence basis<textarea value={row.reason??''} onChange={event=>gas(index,{reason:event.target.value||null})}/></label>
    </div><fieldset><legend>Sources covering {row.gasGroup}</legend>{coverage.sources.filter(source=>['stationary_combustion','mobile_combustion','fugitive','process'].includes(source.domain)).map(source=><label className="stationary-check" key={source.id}><input type="checkbox" checked={row.sourceIds.includes(source.id)} onChange={event=>gas(index,{sourceIds:toggleId(row.sourceIds,source.id,event.target.checked)})}/>{source.name} · {coverage.entities.find(entity=>entity.id===source.entityId)?.legalName} · {coverage.facilities.find(facility=>facility.id===source.facilityId)?.name??'Off-site'} · {register.proof.stationary.reconciliation.rows.find(item=>item.sourceId===source.id)?.equipmentId??register.proof.fleet.reconciliation.rows.find(item=>item.sourceId===source.id)?.assetId??register.proof.fugitive.reconciliation.assets.find(item=>item.sourceId===source.id)?.assetId??'Physical identity unresolved'}</label>)}</fieldset><fieldset><legend>Locations assessed for {row.gasGroup}</legend>{value.locations.map(locationRow=><label className="stationary-check" key={locationRow.rowId}><input type="checkbox" checked={row.locationRowIds.includes(locationRow.rowId)} onChange={event=>gas(index,{locationRowIds:toggleId(row.locationRowIds,locationRow.rowId,event.target.checked)})}/>{locationLabel(locationRow)}</label>)}</fieldset><fieldset><legend>Evidence for {row.gasGroup}</legend>{references(row.evidenceReferences,next=>gas(index,{evidenceReferences:next}))}</fieldset></details>)}
    <details><summary>Remove an unsaved draft row</summary><p>Previously retained locations and identified sources stay in the record.</p>{value.locations.filter(row=>!retainedLocations.has(row.rowId)).map(row=><button type="button" key={row.rowId} onClick={()=>patch({locations:value.locations.filter(x=>x.rowId!==row.rowId),assessments:value.assessments.map(x=>({...x,locationRowIds:x.locationRowIds.filter(id=>id!==row.rowId)})),gasCoverage:value.gasCoverage.map(x=>({...x,locationRowIds:x.locationRowIds.filter(id=>id!==row.rowId)}))})}>Remove draft location: {locationLabel(row)}</button>)}{value.assessments.filter(row=>!earlier.some(old=>old.rowId===row.rowId)).map(row=><button type="button" key={row.rowId} onClick={()=>patch({assessments:value.assessments.filter(x=>x.rowId!==row.rowId)})}>Remove draft assessment: {processCategoryLabels[row.category]}</button>)}</details>
    <label className="stationary-check"><input type="checkbox" checked={value.manualConfirmation} onChange={event=>patch({manualConfirmation:event.target.checked})}/>I reviewed the recorded facts and evidence references. This declaration does not grant acceptance.</label>
  </fieldset>
}
