import {useEffect,useRef,useState,type RefObject} from 'react'
import type {HostedWorkspaceActor} from '@/lib/workspace-api'
import {blankProcessScreen} from '@/lib/m78-form'
import {deriveScope1,scope1Equal,scope1RegisterRequest,scope1VersionRequest,scope1SaveRequest,scope1ReviewRequest,scope1ReportCreate,scope1ReportRead,scope1Download,scope1StatementDownload} from '@/lib/m78-api'
import {M78_INVENTORY_PROFILE,M78_LIMITATIONS,M78_PERIOD,type M78Family,type M78Register,type M78ProcessActivity,type M78VersionEnvelope,type M78Report,type M78CoverageBinding} from '../../../../packages/neuvetra-database/src/m78-contract'
import {buildM78Dependencies} from '../../../../packages/neuvetra-database/src/m78-reconciliation'
import {m78CanonicalJson,validateM78ProcessSave,validateM78InventorySave} from '../../../../packages/neuvetra-database/src/m78-validation'
import {ProcessScreenEditor} from './ProcessScreenEditor'
import {Scope1Totals} from './Scope1Totals'

type Props={actor:HostedWorkspaceActor;workspaceId:string|null;headingRef:RefObject<HTMLHeadingElement|null>}
export function Scope1Inventory(props:Props){const [identity,setIdentity]=useState({actor:props.actor,workspace:props.workspaceId,generation:0});if(identity.actor!==props.actor||identity.workspace!==props.workspaceId){setIdentity({actor:props.actor,workspace:props.workspaceId,generation:identity.generation+1});return null}return <Scope1InventorySession key={identity.generation} {...props}/>}
function Scope1InventorySession({actor,workspaceId,headingRef}:Props){
 const [register,setRegister]=useState<M78Register|null>(null),[family,setFamily]=useState<M78Family>('process_screen'),[draft,setDraft]=useState<M78ProcessActivity|null>(null),[note,setNote]=useState(''),[reason,setReason]=useState(''),[reviewNote,setReviewNote]=useState(''),[ack,setAck]=useState(false),[selected,setSelected]=useState<M78VersionEnvelope|null>(null),[report,setReport]=useState<M78Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const active=useRef(true),lock=useRef(false),pending=useRef<{fingerprint:string;key:string}|null>(null)
 useEffect(()=>{active.current=true;return()=>{active.current=false}},[])
 const alive=()=>active.current&&!actor.signal?.aborted
 const binding=(r:M78Register):M78CoverageBinding=>{const process=r.coverageVersion.snapshot.coverageItems.find(item=>item.domain==='process'&&item.entityId===null&&item.sourceId===null);if(!process)throw new Error('Corporate process coverage must be established first.');return {coverageVersionId:r.coverageVersion.id,coverageVersionSha256:r.coverageVersion.versionSha256,processCoverageItemId:process.id,period:M78_PERIOD}}
 const load=async()=>{if(!workspaceId)return;const r=await scope1RegisterRequest(actor,workspaceId);if(!alive())return;setRegister(r);const head=r.process.versions[r.process.versions.length-1];setDraft(head&&head.activity.profile==='synthetic-process-screen-v1'?{...structuredClone(head.activity),binding:binding(r),manualConfirmation:false}:blankProcessScreen(binding(r)));setSelected(null);setReport(null);setReason('');setReviewNote('');setAck(false)}
 const action=async(fn:()=>Promise<void>)=>{if(lock.current||!alive())return;lock.current=true;setBusy(true);setError('');setMessage('');try{await fn()}catch(e){if(alive())setError(e instanceof Error?e.message:'The action could not be completed. Refresh current records before continuing.')}finally{lock.current=false;if(alive())setBusy(false)}}
 const initialLoad=useRef(()=>action(load))
 useEffect(()=>{const timer=setTimeout(()=>{void initialLoad.current()},0);return()=>clearTimeout(timer)},[]) // Session remounts on actor or workspace changes.
 const key=(payload:unknown)=>{const fingerprint=m78CanonicalJson(payload);if(pending.current?.fingerprint!==fingerprint)pending.current={fingerprint,key:crypto.randomUUID()};return pending.current.key}
 const manage=actor.role==='owner'||actor.role==='admin'
 const stream=register?(family==='process_screen'?register.process:register.inventory):null
 const head=stream?.versions[stream.versions.length-1]??null
 const selectedVersion=selected?.version??null
 const chosenIsHead=selectedVersion?.id===head?.id
 const currentDependencies=register?buildM78Dependencies:null
 async function save(){if(!register||!workspaceId||!stream)return;const dependencies=await deriveScope1(h=>buildM78Dependencies(register.proof,family,h));const activity=family==='process_screen'?(draft?{...draft,gasCoverage:draft.gasCoverage.map(g=>({...g,discoveredSourceIds:g.discoveredSourceIds.map(id=>id.trim()).filter(Boolean)}))}:null):{profile:M78_INVENTORY_PROFILE,binding:binding(register),note};if(!activity)throw new Error('Enter discovery information first.');const input={...activity,expectedVersionId:head?.id??null,expectedVersionSha256:head?.versionSha256??null,expectedDependencySha256:dependencies.dependencySha256,correctionReason:head?reason:null};const value=family==='process_screen'?validateM78ProcessSave({...input,idempotencyKey:key(input)}):validateM78InventorySave({...input,idempotencyKey:key(input)});const saved=await scope1SaveRequest(actor,workspaceId,family,stream.streamId,value);await load();if(alive()){setSelected(saved);setMessage('Version retained. Separate review is still required.');pending.current=null}}
 async function review(changes:boolean){if(!register||!workspaceId||!selectedVersion)return;const dependencies=await deriveScope1(h=>buildM78Dependencies(register.proof,family,h));if(!scope1Equal(dependencies,selectedVersion.dependencies))throw new Error('The supporting records changed. Save a current successor before review.');const input={versionId:selectedVersion.id,expectedVersionSha256:selectedVersion.versionSha256,expectedDependencySha256:dependencies.dependencySha256,decision:changes?'changes_requested' as const:family==='process_screen'?'accepted_bounded_process_screen' as const:'accepted_bounded_inventory' as const,note:reviewNote,acknowledgedLimitations:[...M78_LIMITATIONS]};await scope1ReviewRequest(actor,workspaceId,family,selectedVersion.streamId,{...input,idempotencyKey:key(input)});const exact=await scope1VersionRequest(actor,workspaceId,family,selectedVersion.streamId,selectedVersion.id);await load();if(alive()){setSelected(exact);setMessage('Separate review decision retained.');pending.current=null}}
 async function createReport(){if(!workspaceId||!selectedVersion)return;const input={versionId:selectedVersion.id,expectedVersionSha256:selectedVersion.versionSha256,expectedDecisionId:selectedVersion.review?.id??null,expectedDecisionSha256:selectedVersion.review?.decisionSha256??null,expectedReconciliationSha256:selectedVersion.reconciliation?.contentSha256??null};const created=await scope1ReportCreate(actor,workspaceId,family,selectedVersion.streamId,{...input,idempotencyKey:key(input)});const retainedSelected=selected;await load();if(alive()){setSelected(retainedSelected);setReport(created);setMessage('Historical report retained with the exact evidence and review state.');pending.current=null}}
 const download=(text:string,type:string,name:string)=>{if(!alive())return;const url=URL.createObjectURL(new Blob([text],{type})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="worksheet stationary-workspace controlled-stationary scope1-workspace" aria-busy={busy}>
  <h2 ref={headingRef} tabIndex={-1}>Scope 1 inventory</h2>
  <p className="stationary-warning">Synthetic calendar 2025 demonstration. Scope 1 release readiness remains incomplete. Candidate methods, fictional evidence and internal review do not establish regulatory compliance or external assurance.</p>
  <p>First confirm corporate control and boundaries, then update and review every source and equipment register. Complete process and seven-gas discovery before retaining the combined inventory.</p>
  {error&&<p role="alert" className="stationary-warning">{error}</p>}{message&&<p role="status">{message}</p>}{busy&&<p role="status">Verifying and retaining records…</p>}
  {!workspaceId?<p>Select an authorized company workspace to continue.</p>:<button type="button" disabled={busy} onClick={()=>void action(load)}>Refresh current Scope 1 records</button>}
  {register&&<>
   <p>Corporate coverage version {register.coverageVersion.version} · {register.coverageVersion.snapshot.entities.length} entities · {register.coverageVersion.snapshot.facilities.length} facilities</p>
   <Scope1Totals reconciliation={register.reconciliation} register={register}/>
   <nav className="worksheet-nav" aria-label="Scope 1 steps"><button type="button" aria-pressed={family==='process_screen'} disabled={busy} onClick={()=>{setFamily('process_screen');setSelected(null);setReport(null);setReason('');setAck(false);setReviewNote('')}}>1. Process and seven-gas discovery</button><button type="button" aria-pressed={family==='inventory'} disabled={busy} onClick={()=>{setFamily('inventory');setSelected(null);setReport(null);setReason('');setAck(false);setReviewNote('')}}>2. Combined inventory and review</button></nav>
   <h3>{family==='process_screen'?'Editable current discovery draft':'Retain the combined inventory'}</h3>
   <p>{head?`Current saved version ${head.version}. Corrections create a retained successor.`:'No version has been saved yet.'}</p>
   {manage?<form onSubmit={event=>{event.preventDefault();void action(save)}}>
    {family==='process_screen'&&draft?<ProcessScreenEditor value={draft} register={register} onChange={setDraft} disabled={busy}/>:<label>Inventory preparation note<textarea disabled={busy} value={note} onChange={event=>setNote(event.target.value)} required maxLength={2000}/></label>}
    {head&&<label>Reason for this correction<textarea disabled={busy} required value={reason} onChange={event=>setReason(event.target.value)} maxLength={2000}/></label>}
    <button type="submit" disabled={busy||!currentDependencies}>{head?'Save current successor':'Save first version'}</button>
   </form>:<p>Your role can read retained records. An owner or administrator prepares versions and reviews.</p>}
   <h3>Retained versions</h3>
   <div className="scope1-history">{stream?.versions.map(v=><button type="button" key={v.id} disabled={busy} aria-pressed={selectedVersion?.id===v.id} onClick={()=>void action(async()=>{const e=await scope1VersionRequest(actor,workspaceId!,family,v.streamId,v.id);if(alive()){setSelected(e);setReport(null);setReviewNote('');setAck(false)}})}>Version {v.version} · {v.review?v.review.decision==='changes_requested'?'Changes requested':'Reviewed':'Awaiting review'}</button>)}</div>
   {selectedVersion&&<section className="scope1-retained"><h4>Retained {family==='process_screen'?'discovery':'inventory'} version {selectedVersion.version}</h4><p>{chosenIsHead?'Latest saved version':'Historical version'} · created {new Date(selectedVersion.createdAt).toLocaleString()}</p><p>Review: {selectedVersion.review?selectedVersion.review.decision.replace(/_/g,' '):'None captured for this version'}</p>
    {selectedVersion.findings.length>0&&<details open><summary>Recorded findings ({selectedVersion.findings.length})</summary><ul>{selectedVersion.findings.map((finding,i)=><li key={i}>{finding.message} · {finding.classification.replace(/_/g,' ')}</li>)}</ul></details>}
    {selectedVersion.activity.profile==='synthetic-process-screen-v1'&&selected&&<section><h4>Exact retained discovery facts — read only</h4><p>These are the saved locations, category assessments, seven-gas coverage and evidence links for the selected version. The editable current draft above is separate.</p><ProcessScreenEditor key={selectedVersion.id} value={selectedVersion.activity} register={{...register,coverageVersion:selected.proof.coverageVersion,proof:selected.proof,reconciliation:register.reconciliation}} onChange={()=>{}} disabled={true}/></section>}
    {selectedVersion.reconciliation&&selected&&<Scope1Totals reconciliation={selectedVersion.reconciliation} register={{...register,coverageVersion:selected.proof.coverageVersion,proof:selected.proof}}/>}
    {selectedVersion.statements.length>0&&<details><summary>Retained fictional evidence statements</summary>{selectedVersion.statements.map(s=><p key={s.id}>{s.reference} · {s.description} <button type="button" disabled={busy} onClick={()=>void action(async()=>{const text=await scope1StatementDownload(actor,workspaceId!,selectedVersion,s.id);download(text,'text/plain',`${s.reference}.txt`)})}>Download evidence {s.reference}</button></p>)}</details>}
    {manage&&chosenIsHead&&!selectedVersion.review&&(selectedVersion.contributorIds.includes(actor.userId)?<p>A separate reviewer is required. Anyone who contributed to this version or its supporting records cannot accept it.</p>:<fieldset disabled={busy}><legend>Separate internal review</legend><label>Review explanation<textarea value={reviewNote} onChange={event=>setReviewNote(event.target.value)} maxLength={2000}/></label><label className="stationary-check"><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/>I acknowledge synthetic evidence, incomplete Scope 1 and corporate release readiness, unreleased factors and methods, undetermined requirements and no external assurance.</label><button type="button" disabled={!ack||!reviewNote.trim()||selectedVersion.findings.some(f=>f.classification==='functional_blocker')} onClick={()=>void action(()=>review(false))}>Accept bounded internal {family==='process_screen'?'discovery':'inventory'}</button><button type="button" disabled={!ack||!reviewNote.trim()} onClick={()=>void action(()=>review(true))}>Request changes</button></fieldset>)}
    {manage&&<button type="button" disabled={busy} onClick={()=>void action(createReport)}>Retain report for this exact version</button>}
   </section>}
   <h3>Saved reports</h3><div className="scope1-history">{stream?.reports.map(meta=><button type="button" key={meta.id} disabled={busy} onClick={()=>void action(async()=>{const r=await scope1ReportRead(actor,workspaceId!,family,meta.streamId,meta.id);if(alive())setReport(r)})}>Open report · {new Date(meta.createdAt).toLocaleString()}</button>)}</div>
   {report&&<section><h4>Retained report</h4><p>Historical report · created {new Date(report.createdAt).toLocaleString()}. Later corrections and reviews do not rewrite this snapshot.</p><button type="button" disabled={busy} onClick={()=>void action(async()=>download(await scope1Download(actor,workspaceId!,report,'download'),'text/html','synthetic-scope1-report.html'))}>Download printable report</button><button type="button" disabled={busy} onClick={()=>void action(async()=>download(await scope1Download(actor,workspaceId!,report,'snapshot'),'application/json','synthetic-scope1-evidence-package.json'))}>Download evidence package</button><iframe title="Retained Scope 1 report preview" className="scope1-report-preview" sandbox="" srcDoc={report.html}/></section>}
  </>}
 </section>
}
