import { afterEach, beforeEach, describe, expect, setSystemTime, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { hash, parsePassageRelease } from '../research-passages/release';
import { SOURCE_SHA } from './catalog';
import { createComposedAnswerService } from './answer';
import { composedRequestBody, createComposedProvider, type ComposedStage } from './provider';
const now = Date.parse('2026-09-12T12:00:00Z');
// These retained parser and service fixtures describe the approved historical
// release at `now`; aligning the test clock is not current-release approval.
beforeEach(()=>setSystemTime(new Date(now)));
afterEach(()=>setSystemTime());
const read=(path:string)=>readFileSync(new URL(`../../../../data/research/${path}`,import.meta.url));
const catalogBytes=read('answer-units/scope2-website.epa-inquiry.v1.json'), capabilityBytes=read('capabilities/scope2-website.epa-inquiry.v1.json');
const release=parsePassageRelease(JSON.parse(read('releases/scope2-website.v1.json').toString()),now),verified={release,passages:release.passages,sha256:SOURCE_SHA};
const binding={scopeId:'offline',buildId:'offline',namespace:'offline',releaseId:release.release_id,releaseVersion:release.version,releaseSha256:SOURCE_SHA,profileSha256:'offline',sourceSha256:release.sources.map(s=>s.sha256)};
const question='When an agreement is absent, does a reporting instruction still apply?';
const analysis=(kind='conditional_rule',subject='reporting_methods')=>({operation:'explain',parts:[{id:'q1',start_token:0,kind:'request',requirements:[{kind,subject}],ambiguity_context_ids:[]}]});
const boundary=()=>({facets:[],question_contract:{parts:[{id:'q1',resolution:'coverage_missing',facet_ids:[],context_ids:[]}]}});
const fidelity=()=>({operation_faithful:true,decomposition_complete:true,boundary_mapping_faithful:true,question_parts:[{id:'q1',faithful:true}],issues:[] as {code:string;target:string}[],decision:'pass'});
const ordinary=()=>({decision:'pass',decomposition_complete:true,relevant:true,scope_appropriate:true,context_appropriate:true,premise_handled:true,task_fit:true,proportionate:true,facets:[],question_parts:[{id:'q1',faithful:true,appropriately_resolved:true,requirements:[{id:'q1-r1',capability_ids:[],blocking_limit_ids:[]}],additional_requirements:[]}],issues:[]});
function harness(outputs:unknown[]){const calls:{stage:ComposedStage;input:any}[]=[];let rechecks=0;const service=createComposedAnswerService({catalogBytes,catalogSha256:hash(catalogBytes),capabilityBytes,capabilitySha256:hash(capabilityBytes),now:()=>now,repository:{loadForQuestion:async()=>({verified,binding,candidateIds:['S01']}),recheck:async()=>{rechecks++;}},provider:{model:'offline',remaining:()=>20-calls.length,invoke:async(stage,input)=>{calls.push({stage,input});return outputs.shift();}}});return {service,calls,rechecks:()=>rechecks};}
describe('Certified boundary service flow',()=>{
 test('pure catalog gap needs a fresh source-independent fidelity pass and renders no claim',async()=>{const h=harness([analysis(),boundary(),fidelity()]),a=await h.service.answer(question);expect(a.reason_code).toBe('coverage_missing');expect(a.status).toBe('unsupported');expect(a.claims).toEqual([]);expect(a.scope_gaps).toEqual([{question_fragment:question,reason:'coverage_missing',context_ids:[]}]);expect(h.calls.map(c=>c.stage)).toEqual(['analyze','plan','verify']);expect(h.rechecks()).toBe(1);const packet=h.calls[2]!.input;expect(Object.keys(packet)).toEqual(['review_mode','fidelity']);expect(packet.fidelity.original_question).toBe(question);const text=JSON.stringify(packet);for(const forbidden of ['unit_catalog','ranked_candidate','previous_selection','U01','S01','capability_ids'])expect(text).not.toContain(forbidden);expect(JSON.parse(composedRequestBody('verify',JSON.parse(text))).output_config.format.schema.properties.operation_faithful).toBeDefined();});
 test('a faithful:false verdict is terminal and never converted to the ordinary boundary pass',async()=>{const fail=fidelity();fail.question_parts[0]!.faithful=false;fail.decision='fail';fail.issues=[{code:'question_part',target:'q1'}];const h=harness([analysis(),boundary(),fail,boundary(),fidelity()]);expect((await h.service.answer(question)).reason_code).toBe('question_analysis_not_verified');expect(h.calls).toHaveLength(3);expect(h.rechecks()).toBe(0);});
 test('omitted or newly added needs on the specialized schema fail rather than creating a repair',async()=>{for(const output of [{...fidelity(),question_parts:[]},{...fidelity(),additional_requirements:[]},{...fidelity(),decision:'fail'}]){const h=harness([analysis(),boundary(),output]);expect((await h.service.answer(question)).reason_code).toBe('selection_review_invalid');expect(h.calls).toHaveLength(3);}});
 test('a qualifying strict timing capability retains ordinary substantive review',async()=>{const h=harness([analysis('conditional_rule','agreement_period_alignment'),boundary(),ordinary()]);expect((await h.service.answer(question)).reason_code).toBe('coverage_missing');expect(h.calls[2]!.input.review_mode).toBeUndefined();expect(h.calls[2]!.input.unit_catalog).toHaveLength(23);});
 test('the sole semantic correction can reach a new certified boundary without converting the first negative review',async()=>{const plan={facets:[{id:'f1',unit_ids:['U02']}],question_contract:{parts:[{id:'q1',resolution:'source_available',facet_ids:['f1'],context_ids:[]}]}};const r=ordinary();r.decision='revise';r.question_parts[0]!.appropriately_resolved=false;(r as any).facets=[{id:'f1',covered:true,unit_ids:['U02']}];(r as any).issues=[{code:'question_part',target_id:'q1',explanation:'The selected general recommendation does not resolve the declared conditional effect.'}];const h=harness([analysis(),plan,r,boundary(),fidelity()]),a=await h.service.answer(question);expect(a.reason_code).toBe('coverage_missing');expect(a.correction_kind).toBe('source_review');expect(h.calls).toHaveLength(5);expect(h.calls[3]!.input.correction_packet.review.decision).toBe('revise');expect(h.calls[4]!.input.review_mode).toBe('catalog_absence_fidelity_v1');});
 test('provider rejects source contamination and a tampered serialized certificate before reserve or I/O',async()=>{const h=harness([analysis(),boundary(),fidelity()]);await h.service.answer(question);let reserves=0,network=0;const provider=createComposedProvider({apiKey:'offline-test',budget:{maxCalls:10,remaining:()=>10,reserve:()=>{reserves++;return reserves;}},fetch:async()=>{network++;throw Error('forbidden');}});for(const mutate of [(p:any)=>{p.fidelity.unit_catalog=[]},(p:any)=>{p.fidelity.certificate.catalog_sha256='0'.repeat(64)},(p:any)=>{p.extra=[]},(p:any)=>{p.review_mode='unknown'}]){const packet=structuredClone(h.calls[2]!.input);mutate(packet);await expect(provider.invoke('verify',packet,new AbortController().signal)).rejects.toThrow('selection_review_invalid');}expect(reserves).toBe(0);expect(network).toBe(0);});
 test('the default production clock allows work before expiry and refuses at or after expiry before provider reserve or I/O',async()=>{const expiry=Date.parse(JSON.parse(catalogBytes.toString()).review.expires_at);for(const [offset,reason,expectedCalls] of [[-1,'provider_failure',1],[0,'unit_catalog_stale',0],[1,'unit_catalog_stale',0]] as const){setSystemTime(new Date(expiry+offset));let invocations=0,reserves=0,network=0;const delegate=createComposedProvider({apiKey:'offline-test',budget:{maxCalls:10,remaining:()=>10,reserve:()=>{reserves++;return reserves;}},fetch:async()=>{network++;throw Error('offline-test');}}),provider={...delegate,invoke:async(...args:Parameters<typeof delegate.invoke>)=>{invocations++;return delegate.invoke(...args)}};const service=createComposedAnswerService({catalogBytes,catalogSha256:hash(catalogBytes),capabilityBytes,capabilitySha256:hash(capabilityBytes),repository:{loadForQuestion:async()=>({verified,binding,candidateIds:['S01']}),recheck:async()=>{}},provider});const answer=await service.answer(question);expect(answer.reason_code).toBe(reason);expect(invocations).toBe(expectedCalls);expect(reserves).toBe(expectedCalls);expect(network).toBe(expectedCalls);expect(answer.claims).toEqual([]);}});
});
