import assert from 'node:assert/strict'
import {readFileSync,writeFileSync} from 'node:fs'
import {buildAnnualWorksheetReport,annualWorksheetReportIdentity} from '../../packages/neuvetra-database/src/m67-report'
import {M67_TEMPLATE,M67_TEMPLATE_SHA256} from '../../packages/neuvetra-database/src/m67-template'
import {M67_METHOD,M67_LIMITATIONS,annualWorksheetInputHash,annualWorksheetResultHash,annualWorksheetReviewHash} from '../../packages/neuvetra-database/src/m67'
import type {AnnualWorksheetVersion} from '../../packages/neuvetra-database/src/m67-contract'
const cases=JSON.parse(readFileSync('evaluations/research-qa/m67-accounting-cases.json','utf8'))
const hash=(value:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(value).digest('hex')
const fileHash=(path:string)=>hash(readFileSync(path))
const company='11111111-1111-4111-8111-111111111111',author='22222222-2222-4222-8222-222222222222',manager='33333333-3333-4333-8333-333333333333',id='44444444-4444-4444-8444-444444444444'
function version(c:any):AnnualWorksheetVersion{const e=c.expected;const v:AnnualWorksheetVersion={id,version:1,previousVersionId:null,companyLabel:'Synthetic company',facilityLabel:'Synthetic CAMX facility',year:2023,geography:'CAMX',unit:'kWh',evidenceBasis:'synthetic_manual_without_linked_bills',months:e.months.map((m:any)=>({month:m.month,quantityKwh:m.quantity_kwh,quantityMwh:m.quantity_mwh,total:m.unrounded_kg_co2e===null?null:{unrounded:m.unrounded_kg_co2e,display:m.display_kg_co2e,unit:'kg CO2e',rounding:'half_even_4dp'}})),quantityKwh:e.quantity_kwh,quantityMwh:e.quantity_mwh,total:{unrounded:e.total_unrounded_kg_co2e,display:e.total_display_kg_co2e,unit:'kg CO2e',rounding:'half_even_4dp'},coverage:e.coverage,createdBy:author,createdAt:'2026-09-15T01:00:00.000Z',correctionReason:null,inputSha256:'',resultSha256:'',method:M67_METHOD,review:null};v.inputSha256=annualWorksheetInputHash(company,v);v.resultSha256=annualWorksheetResultHash(v.inputSha256,v);return v}
const phrases=['Annual entries are manual and have no linked bill evidence. The separate January bill-linked worksheet does not provide evidence or approval for this annual worksheet.','The subtotal is rounded after summing exact monthly values. Displayed monthly amounts may not sum to the displayed subtotal.','This is a snapshot of a worksheet decision, not approval of the report presentation, verification of manual inputs or assurance.','The same annual 2023 CAMX regional average factor is applied to each entered month. It is not a month-specific factor.','Draft \u00b7 Synthetic \u00b7 Incomplete company inventory \u00b7 Unreleased \u00b7 No assurance','SRL23!AI6','A6=2023, B6=CAMX, C6=WECC California','AR5 \u00b7 100 years \u00b7 without climate-carbon feedbacks; CO2 1, CH4 28, N2O 265','No factor or method is released by this report.','Browser print/PDF layout and bytes may vary and are not covered by the HTML hash.']
const checks=[]
for(const c of cases.accepted_cases){for(const state of ['unreviewed','accepted','changes_requested']){const v=version(c)
 if(state!=='unreviewed'){v.review={id:'55555555-5555-4555-8555-555555555555',versionId:v.id,resultSha256:v.resultSha256,decision:state==='accepted'?'accept_bounded_internal_draft':'changes_requested',note:state==='accepted'?null:'Correct month <January> & review {values}.',acknowledgedLimitations:state==='accepted'?[...M67_LIMITATIONS]:[],reviewerId:manager,reviewedAt:'2026-09-15T02:00:00.000Z',decisionSha256:''};v.review.decisionSha256=annualWorksheetReviewHash(company,v.review)}
 const context={id:'66666666-6666-4666-8666-666666666666',companyId:company,createdBy:author,createdAt:'2026-09-15T03:00:00.000Z',source:v};const built=buildAnnualWorksheetReport(context),html=new TextDecoder('utf-8',{fatal:true}).decode(built.bytes)
 assert.equal(built.reportSha256,hash(built.bytes));assert.equal(built.identitySha256,annualWorksheetReportIdentity(company,v));assert.equal(hash(M67_TEMPLATE),M67_TEMPLATE_SHA256);assert(!/\{\{[a-zA-Z0-9]+\}\}/.test(html));assert(!/[\u00c2\u00e2\u00c3]/.test(html),'No mojibake sentinel')
 for(const text of phrases)assert(html.includes(text),`${c.id}/${state} phrase: ${text}`)
 for(const pin of [cases.authority.source_sha256,cases.authority.candidate_sha256,cases.authority.gwp_sha256,'4ad28f3877d13f238bbbf7e8bfb1fc6241922b9def73712ec1b02fd80b51b82c'])assert(html.includes(pin))
 assert(html.includes(`<h2>${c.expected.subtotal_label}</h2>`));assert(html.includes(`${c.expected.coverage.knownMonths} of 12 months entered`));assert(html.includes(`<p class="subtotal">${c.expected.total_display_kg_co2e} kg CO2e</p>`));assert(html.includes(`<strong>${c.expected.total_unrounded_kg_co2e} kg CO2e</strong>`))
 if(c.expected.coverage.electricityComplete)assert(html.includes('Full electricity period coverage for this fictional facility; the overall company inventory remains incomplete.'));else assert(html.includes('This subtotal excludes months not entered.'))
 const rows=[...html.matchAll(/<tr><th scope="row">([^<]+)<\/th>((?:<td>[^<]*<\/td>){5})<\/tr>/g)];assert.equal(rows.length,12)
 rows.forEach((row,i)=>{const e=c.expected.months[i],cells=[...row[2]!.matchAll(/<td>([^<]*)<\/td>/g)].map(m=>m[1]);assert.deepEqual(cells,[e.quantity_kwh===null?'Not entered':e.quantity_kwh==='0.000'?'Entered zero':'Entered',e.quantity_kwh??'Not entered',e.quantity_mwh??'Not entered',e.unrounded_kg_co2e??'Not entered',e.display_kg_co2e??'Not entered'])})
 assert(html.includes(state==='unreviewed'?'No worksheet review was recorded when this report was created.':state==='accepted'?'The worksheet version was accepted for bounded internal use.':'A manager requested changes to this worksheet version.'))
 if(state==='changes_requested')assert(html.includes('Correct month &lt;January&gt; &amp; review &#123;values&#125;.'))
 const second=buildAnnualWorksheetReport(context);assert.deepEqual(second.bytes,built.bytes)
 if(state==='unreviewed'&&['january_25000_partial','twelve_minimum','twelve_below_maximum'].includes(c.id))writeFileSync(`evaluations/research-qa/m67-accounting-report-${c.id}.html`,built.bytes)
 checks.push({case:c.id,state,knownMonths:c.expected.coverage.knownMonths,subtotal:c.expected.total_display_kg_co2e,sha256:built.reportSha256,bytes:built.bytes.length})
}}
const paths=['docs/research/m67-accounting-contract.md','evaluations/research-qa/m67-accounting-cases.json','packages/neuvetra-database/src/m67-contract.ts','packages/neuvetra-database/src/m67.ts','packages/neuvetra-database/src/m67-report.ts','packages/neuvetra-database/src/m67-template.ts','apps/site-web/src/components/AnnualElectricityWorksheet.tsx','apps/site-web/src/components/AnnualWorksheetReports.tsx','apps/site-web/src/lib/m67-api.ts','apps/site-web/src/lib/m67-report-api.ts','evaluations/research-qa/m67-accounting-report-check.ts']
writeFileSync(process.argv[2]??'evaluations/research-qa/m67-accounting-report-receipt.json',JSON.stringify({observedAt:new Date().toISOString(),scope:'Executed pure report renderer against independently derived case inputs in three captured review states. No database, native browser or print-layout execution.',templateSha256:M67_TEMPLATE_SHA256,checks,sha256:Object.fromEntries(paths.map(p=>[p,fileHash(p)]))},null,2)+'\n')
console.log(JSON.stringify({rendered:checks.length,monthlyRows:checks.length*12,templateSha256:M67_TEMPLATE_SHA256}))
