import {beforeAll,afterAll,expect,test} from 'bun:test'
import {createPostgresConnection,HostedWorkspaceDatabase} from '../../packages/neuvetra-database/src/hosted'
import {migratePrivateStaging,readMigrationManifest,provisionStagingRoster} from '../../packages/neuvetra-database/src/staging-migrations'
import {createStagingServer} from '../../apps/site-api/src/staging/server'
import {decodeAnnualElectricityWorksheet} from '../../apps/site-web/src/lib/m67-api'
import {decodeAnnualElectricityEvidence} from '../../apps/site-web/src/lib/m68-api'
import {decodeAnnualEvidenceReport} from '../../apps/site-web/src/lib/m68-report-api'
import {readAnnualElectricityEvidence,annualEvidenceResultHash} from '../../packages/neuvetra-database/src/m68'
import {readAnnualEvidenceReports} from '../../packages/neuvetra-database/src/m68-report'
import {M68_LIMITATIONS} from '../../packages/neuvetra-database/src/m68-contract'
import {M67_LIMITATIONS} from '../../packages/neuvetra-database/src/m67-contract'
import {hashManifestValue} from '../../tools/staging/create-source-manifest'
import type {WorkspaceConnection,WorkspaceSql} from '../../packages/neuvetra-database/src/workspace'
const url=process.env.M68_QA_DATABASE_URL
if(url!=='postgres://m63_test_admin@127.0.0.1:55463/m68_qa')throw Error('Dedicated m68_qa only; explicit URL required')
const REF='abcdefghijklmnopqrst',ORIGIN='http://127.0.0.1:36668',company=crypto.randomUUID(),otherCompany=crypto.randomUUID()
const ids={owner:crypto.randomUUID(),admin:crypto.randomUUID(),member:crypto.randomUUID(),other:crypto.randomUUID(),outsider:crypto.randomUUID(),uninvited:crypto.randomUUID()}
const hash=(v:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(v).digest('hex')
const baseline=await Bun.file(new URL('./m68-independent-baseline.json',import.meta.url)).json()
let operator:WorkspaceConnection,runtime:WorkspaceConnection,db:HostedWorkspaceDatabase,app:Awaited<ReturnType<typeof createStagingServer>>,annual:any,evidence:any,current:any,report:any,reportBytes:Uint8Array,sources:any[]=[]
const construct=(c:WorkspaceConnection)=>new(HostedWorkspaceDatabase as unknown as new(c:WorkspaceConnection,r:string)=>HostedWorkspaceDatabase)(c,REF)
const request=(actor:keyof typeof ids|null,kind='annual-electricity-evidence',suffix='',payload?:unknown,c=company)=>app.fetch(new Request(`${ORIGIN}/workspace-api/workspace/${c}/${kind}${suffix}`,{method:payload===undefined?'GET':'POST',headers:{origin:ORIGIN,...(actor?{authorization:'Bearer '+actor}:{}),...(payload===undefined||payload instanceof FormData?{}:{'content-type':'application/json'})},body:payload===undefined?undefined:payload instanceof FormData?payload:JSON.stringify(payload)}))
const json=async(actor:keyof typeof ids,kind:string,suffix='',payload?:unknown,status=payload===undefined?200:201,c=company)=>{const r=await request(actor,kind,suffix,payload,c);expect(r.status,await r.clone().text()).toBe(status);return r.json() as Promise<any>}
const months=(j:string|null='0',rest:string|null=null)=>Array.from({length:12},(_,i)=>({month:`2023-${String(i+1).padStart(2,'0')}`,quantityKwh:i?rest:j}))
async function annualSave(rows=months(),label='Independent fictional facility'){const prior=annual?.versions.at(-1);annual=decodeAnnualElectricityWorksheet(await json('owner','annual-electricity-worksheet',prior?'/corrections':'',{companyLabel:'Synthetic QA <draft>',facilityLabel:label,year:2023,geography:'CAMX',unit:'kWh',months:rows,idempotencyKey:crypto.randomUUID(),...(prior?{expectedVersionId:prior.id,expectedResultSha256:prior.resultSha256,correctionReason:'Independent annual input correction'}:{})}),company);return annual.versions.at(-1)}
const link=(i=0,reason:string|null=null)=>({month:'2023-01',sourceId:sources[i].id,expectedSourceSha256:sources[i].sha256,sourcePage:1,manualConfirmation:true,quantityDifferenceReason:reason})
const input=(links:any[]=[],a=annual.versions.at(-1))=>({annualVersionId:a.id,expectedAnnualInputSha256:a.inputSha256,expectedAnnualResultSha256:a.resultSha256,links,idempotencyKey:crypto.randomUUID(),...(current?{expectedVersionId:current.id,expectedResultSha256:current.resultSha256,correctionReason:'Independent evidence correction'}:{})})
async function save(links:any[]=[],a=annual.versions.at(-1)){evidence=decodeAnnualElectricityEvidence(await json('owner','annual-electricity-evidence',current?'/corrections':'',input(links,a)),company,annual);current=evidence.versions.at(-1);return current}
const rp=(v=current)=>({sourceVersionId:v.id,expectedInputSha256:v.inputSha256,expectedResultSha256:v.resultSha256,expectedReviewId:v.review?.id??null,expectedReviewSha256:v.review?.decisionSha256??null,idempotencyKey:crypto.randomUUID()})
const review=(v=current)=>({versionId:v.id,expectedResultSha256:v.resultSha256,decision:'accept_bounded_internal_draft',note:null,acknowledgedLimitations:[...M68_LIMITATIONS],idempotencyKey:crypto.randomUUID()})
async function rejects(fn:()=>Promise<unknown>){let rejected=false;try{await fn()}catch{rejected=true}expect(rejected).toBe(true)}
async function preserved(){for(const t of baseline.rowHashes){const now=new Set((await operator.query<{value:any}>(`select to_jsonb(t) value from neuvetra.${t.table} t`)).rows.map(r=>hashManifestValue(r.value)));expect(t.hashes.every((h:string)=>now.has(h)),t.table).toBe(true)}}
const scoped=<T>(id:string|null,fn:(tx:WorkspaceSql)=>Promise<T>)=>runtime.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[id??'']);return fn(tx)})
beforeAll(async()=>{
 operator=createPostgresConnection(url!,{tls:false});const manifest=await readMigrationManifest();expect(manifest).toHaveLength(14);expect(manifest[13]!.sha256).toBe('81686f3c62f8130a60dbbc096ae758eb6d56ecd80df3d533621a1990ae33d425')
 await migratePrivateStaging(operator,{expectedProjectRef:REF,syntheticTargetConfirmed:true})
 for(const id of Object.values(ids))await operator.query('insert into auth.users(id) values($1)',[id])
 await provisionStagingRoster(operator,{expectedProjectRef:REF,workspaceId:company,ownerUserId:ids.owner,members:[{userId:ids.admin,role:'admin'},{userId:ids.member,role:'member'}]})
 await provisionStagingRoster(operator,{expectedProjectRef:REF,workspaceId:otherCompany,ownerUserId:ids.other,members:[]})
 await operator.query("insert into neuvetra.company_members(company_id,user_id,role) values($1,$2,'admin')",[company,ids.uninvited])
 runtime=createPostgresConnection('postgres://neuvetra_runtime@127.0.0.1:55463/m68_qa',{tls:false,maxConnections:4});db=construct(runtime)
 app=await createStagingServer({profile:'neuvetra.private-synthetic-staging.v1',projectRef:REF,reuseExistingProject:false,origin:ORIGIN,supabaseUrl:`https://${REF}.supabase.co`,supabaseAnonKey:'synthetic-fixture',databaseUrl:url!,webRoot:'.',port:36668},{database:db,validateUser:async token=>token in ids?{id:ids[token as keyof typeof ids],email:null,phone:null,fullName:null}:null,verifyAssets:async()=>{},serveAsset:async()=>null,log:()=>{}})
},30000)
afterAll(async()=>{await app?.close();await operator?.close()})
test('migration14 retains all1894 independently frozen predecessor rows; sources are pinned originals',async()=>{
 expect((await db.checkReadiness()).schemaVersion).toBe(14);await preserved()
 for(const [name,pinned] of [['neuvetra-m55-synthetic-electricity-bill.pdf','0a97cd0976c03af0776214fc19bdc3d4f0c00e9c835f3e116574a6f375c8e135'],['neuvetra-m66-synthetic-electricity-bill-b.pdf','83e000a95f9e2f95473dc2cba18be0fc36810b24b9288f59b5aceb3a5ec0430f']]){const bytes=await Bun.file(new URL('../../output/pdf/'+name,import.meta.url)).bytes();expect(hash(bytes)).toBe(pinned!);const form=new FormData();form.set('file',new File([bytes],name!,{type:'application/pdf'}));form.set('idempotencyKey',crypto.randomUUID());sources.push(await json('owner','source-electricity-worksheet','/sources',form));const r=await request('member','source-electricity-worksheet','/sources/'+sources.at(-1).id+'/download');expect(r.status).toBe(200);expect(new Uint8Array(await r.arrayBuffer())).toEqual(bytes)}
})
test('explicit zero and unknown inputs retain separate evidence gaps and selected annual review is not inherited',async()=>{
 const a=await annualSave();annual=decodeAnnualElectricityWorksheet(await json('admin','annual-electricity-worksheet','/reviews',{...review(a),acknowledgedLimitations:[...M67_LIMITATIONS]}),company)
 await save();expect(current.coverage).toEqual({enteredMonths:1,missingInputMonths:months().slice(1).map(m=>m.month),linkedDocumentMonths:0,unambiguousDocumentMonths:0,missingDocumentMonths:months().map(m=>m.month),overlappingDocumentMonths:[],quantityDifferenceMonths:[]});expect(current.annual.months[0].quantityKwh).toBe('0.000');expect(current.annual.months[1].quantityKwh).toBeNull();expect(current.annual.review).toBeNull();expect(current.review).toBeNull()
 await save([link(0,'Zero differs from printed usage')]);expect(current.coverage.quantityDifferenceMonths).toEqual(['2023-01']);expect(current.coverage.unambiguousDocumentMonths).toBe(1);expect(current.annual.total.display).toBe('0.0000')
 report=decodeAnnualEvidenceReport(await json('owner','annual-electricity-evidence','/reports',rp()),evidence,annual);reportBytes=new Uint8Array(await(await request('member','annual-electricity-evidence',`/reports/${report.id}/download`)).arrayBuffer());expect(hash(reportBytes)).toBe(report.reportSha256)
})
test('source-only, explanation-only, annual-only successors pass actual decoder and preserve earlier report',async()=>{
 const before=current;await save([link(1,'Zero differs from printed usage')]);expect(current.annual).toEqual(before.annual);expect(current.links[0].source.id).toBe(sources[1].id)
 const replacement=current;await save([link(1,'Revised explanation; discrepancy remains')]);expect(current.annual).toEqual(replacement.annual);expect(current.coverage).toEqual(replacement.coverage)
 const explanation=current;await annualSave(months(),'Only changed the fictional facility label');await save([link(1,'Revised explanation; discrepancy remains')]);expect(current.annual.id).not.toBe(explanation.annual.id);expect(current.annual.total).toEqual(explanation.annual.total);expect(current.review).toBeNull()
 expect((await request('owner','annual-electricity-evidence','/corrections',input([link(1,'Revised explanation; discrepancy remains')]))).status).toBe(409)
 await save([link(0,'Unresolved A'),link(1,'Unresolved B')]);expect(current.coverage.linkedDocumentMonths).toBe(1);expect(current.coverage.unambiguousDocumentMonths).toBe(0);expect(current.coverage.overlappingDocumentMonths).toEqual(['2023-01']);expect(current.coverage.quantityDifferenceMonths).toEqual(['2023-01']);expect(current.annual.total.display).toBe('0.0000')
 expect((await request('owner','annual-electricity-evidence','/corrections',input([link(1,'Unresolved B'),link(0,'Unresolved A')]))).status).toBe(409)
 await save();expect(current.coverage.missingDocumentMonths).toHaveLength(12)
 expect(new Uint8Array(await(await request('member','annual-electricity-evidence',`/reports/${report.id}/download`)).arrayBuffer())).toEqual(reportBytes)
})
test('missing January cannot link; equal quantity requires no explanation; duplicate IDs and bytes and false periods refuse in HTTP and native SQL',async()=>{
 await annualSave(months(null,'1'));await save();const badMissing=input([link(0,'Missing January must not be inferred')]);expect((await request('owner','annual-electricity-evidence','/corrections',badMissing)).status).toBe(422)
 await annualSave(months('12345','0'));await save([link()]);expect(current.coverage.enteredMonths).toBe(12);expect(current.coverage.quantityDifferenceMonths).toEqual([]);expect(current.coverage.missingDocumentMonths).toHaveLength(11)
 const invalid=[[link(0,'Equal must be null')],[link(),link()],[link(),{...link(),sourceId:crypto.randomUUID()}],[{...link(),month:'2023-02'}],[{...link(),sourcePage:2}],[{...link(),manualConfirmation:false}],[{...link(),confirmedBy:ids.other}],[{...link(),quantityDifferenceReason:undefined}]]
 for(const links of invalid){const p=input(links);expect((await request('owner','annual-electricity-evidence','/corrections',p)).status).toBe(422);await rejects(()=>scoped(ids.owner,tx=>tx.query('select neuvetra.save_annual_electricity_evidence($1,$2::text::jsonb,true)',[company,JSON.stringify(p)])))}
})
test('native driver independently recomputed small, tie and maximal totals are reused through M68 API and decoder',async()=>{
 // integer millikWh times 1950402888 / 10^13 kg; display rounds quotient/remainder half-even at 4dp.
 for(const milli of [1n,62500000n,187500000n,1000000000n]){const q=`${milli/1000n}.${String(milli%1000n).padStart(3,'0')}`;await annualSave(months(q,'0'));await save();const numerator=milli*1950402888n,den=10000000000000n,whole=numerator/den,frac=String(numerator%den).padStart(13,'0').replace(/0+$/,'');const exact=String(whole)+(frac?'.'+frac:'');let d=numerator/1000000000n;const rem=numerator%1000000000n;if(rem>500000000n||(rem===500000000n&&d%2n===1n))d++;const display=`${d/10000n}.${String(d%10000n).padStart(4,'0')}`;expect(current.annual.total.unrounded).toBe(exact);expect(current.annual.total.display).toBe(display);expect(current.annual).toEqual({...annual.versions.at(-1),review:null})}
})
test('cross-tenant, uninvited, member, signed-out, self-review and competing saves reject at real boundaries',async()=>{
 for(const [actor,status] of [['member',200],['other',404],['outsider',403],['uninvited',403],[null,401]] as const){for(const suffix of ['', '/reports',`/reports/${report.id}`,`/reports/${report.id}/download`])expect((await request(actor,'annual-electricity-evidence',suffix)).status).toBe(status)}
 for(const id of [ids.member,ids.other,ids.outsider,ids.uninvited,null])await rejects(()=>scoped(id,tx=>tx.query('select neuvetra.save_annual_electricity_evidence($1,$2::text::jsonb,true)',[company,JSON.stringify(input())])))
 for(const id of [ids.other,ids.outsider,ids.uninvited,null])expect((await scoped(id,tx=>tx.query('select * from neuvetra.annual_electricity_evidence_versions where company_id=$1',[company]))).rows).toHaveLength(0)
 expect((await request('owner','annual-electricity-evidence','/reviews',review())).status).toBe(409)
 const left=input([link(0,'Concurrent A')]),right=input([link(1,'Concurrent B')]);const responses=await Promise.all([request('owner','annual-electricity-evidence','/corrections',left),request('admin','annual-electricity-evidence','/corrections',right)]);expect(responses.map(r=>r.status).sort()).toEqual([201,409]);evidence=decodeAnnualElectricityEvidence(await json('owner','annual-electricity-evidence'),company,annual);current=evidence.versions.at(-1)
 const reviewer=current.createdBy===ids.owner?'admin':'owner';const before=decodeAnnualEvidenceReport(await json('owner','annual-electricity-evidence','/reports',rp()),evidence,annual);const bytes=new Uint8Array(await(await request('member','annual-electricity-evidence',`/reports/${before.id}/download`)).arrayBuffer());evidence=decodeAnnualElectricityEvidence(await json(reviewer,'annual-electricity-evidence','/reviews',review()),company,annual);current=evidence.versions.at(-1);expect(current.review.reviewerId).toBe(ids[reviewer]);expect(decodeAnnualEvidenceReport(before,evidence,annual).reviewState).toBe('unreviewed');expect(new Uint8Array(await(await request('member','annual-electricity-evidence',`/reports/${before.id}/download`)).arrayBuffer())).toEqual(bytes)
})
test('coordinated stored coverage, annual snapshot and report bytes/hash/length corruption refuse with rollback',async()=>{
 for(const kind of ['coverage','annual','report','source']){let observed=false;try{await operator.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[ids.owner]);if(kind==='report'){await tx.query('alter table neuvetra.annual_evidence_reports disable trigger user');await tx.query("update neuvetra.annual_evidence_reports set report_bytes=convert_to('<html>Forged verified total</html>','utf8'),report_sha256=encode(sha256(convert_to('<html>Forged verified total</html>','utf8')),'hex'),report_byte_length=octet_length(convert_to('<html>Forged verified total</html>','utf8')) where id=$1",[report.id])}else if(kind==='source'){await tx.query('alter table neuvetra.electricity_sources disable trigger user');await tx.query("update neuvetra.electricity_sources set original_bytes=convert_to('forged-pdf','utf8'),sha256=encode(sha256(convert_to('forged-pdf','utf8')),'hex'),byte_length=10 where id=$1",[sources[0].id])}else{const v=structuredClone(current);if(kind==='coverage')v.coverage.linkedDocumentMonths=12;else v.annual.facilityLabel='Coordinated annual substitution';v.resultSha256=annualEvidenceResultHash(v.inputSha256,v);const {review:_,...payload}=v;await tx.query('alter table neuvetra.annual_electricity_evidence_versions disable trigger user');await tx.query('alter table neuvetra.annual_electricity_evidence_audit disable trigger user');await tx.query('update neuvetra.annual_electricity_evidence_versions set payload=$2::text::jsonb,result_sha256=$3 where id=$1',[v.id,JSON.stringify(payload),v.resultSha256]);await tx.query('update neuvetra.annual_electricity_evidence_audit set record_sha256=$2 where record_id=$1',[v.id,v.resultSha256])}await rejects(()=>kind==='report'?readAnnualEvidenceReports(tx,company):readAnnualElectricityEvidence(tx,company));observed=true;throw Error('QA_ROLLBACK')})}catch(e){if(!(e instanceof Error&&e.message==='QA_ROLLBACK'))throw e}expect(observed,kind).toBe(true)}
 expect((await json('owner','annual-electricity-evidence')).versions.at(-1).id).toBe(current.id)
})
test('queued authorized save is refused after access revocation at lock release and fresh connection retains closure',async()=>{
 await save();const p=input([link(0,'Post-lock revocation challenge')]);let pending:Promise<Response>|undefined
 await operator.transaction(async tx=>{await tx.query('select id from neuvetra.companies where id=$1 for update',[company]);pending=request('admin','annual-electricity-evidence','/corrections',p);let waiting=false;for(let i=0;i<100;i++){await tx.query('select pg_stat_clear_snapshot()');const r=await tx.query<{n:number}>("select count(*)::int n from pg_stat_activity where datname=current_database() and usename='neuvetra_runtime' and wait_event_type='Lock'");if(r.rows[0]!.n){waiting=true;break}await new Promise(r=>setTimeout(r,10))}expect(waiting).toBe(true);await tx.query('update neuvetra.staging_access set active=false where user_id=$1',[ids.admin])});expect((await pending!).status).toBe(404);expect((await json('owner','annual-electricity-evidence')).versions.at(-1).id).toBe(current.id)
 const fresh=construct(createPostgresConnection('postgres://neuvetra_runtime@127.0.0.1:55463/m68_qa',{tls:false}));try{expect((await fresh.downloadAnnualEvidenceReport(ids.member,company,report.id))!.bytes).toEqual(reportBytes)}finally{await fresh.close()}await preserved()
 await Bun.write(new URL('./m68-independent-native-fixture.json',import.meta.url),JSON.stringify({company,annual,evidence:await json('owner','annual-electricity-evidence'),report,reportHtml:new TextDecoder().decode(reportBytes)},null,2)+'\n')
})
