import {afterEach,expect,test} from 'bun:test'
import {annualEvidenceRequest,decodeAnnualElectricityEvidence} from '../../apps/site-web/src/lib/m68-api'
import {decodeAnnualEvidenceReport,readAnnualEvidenceReportHtml,listAnnualEvidenceReports,createAnnualEvidenceReport} from '../../apps/site-web/src/lib/m68-report-api'
const fixture=await Bun.file(new URL('./m68-independent-native-fixture.json',import.meta.url)).json()
const {company,annual,evidence,report,reportHtml}=fixture
const original=globalThis.fetch
const actor={accessToken:'synthetic-qa-token',userId:evidence.versions[0].createdBy,role:'owner' as const}
afterEach(()=>{globalThis.fetch=original})
async function refuses(fn:()=>Promise<unknown>){let denied=false;try{await fn()}catch{denied=true}expect(denied).toBe(true)}
test('actual native success history decodes including the full independent lifecycle',()=>{expect(decodeAnnualElectricityEvidence(evidence,company,annual).versions.length).toBeGreaterThan(10);expect(decodeAnnualEvidenceReport(report,evidence,annual).source.review).toBeNull()})
test('independent malformed values, false coverage, inherited review and duplicate-byte changes refuse',()=>{
 const index=evidence.versions.findIndex((v:any)=>v.links.length===2)
 for(const mutate of [(w:any)=>w.companyId=crypto.randomUUID(),(w:any)=>w.complete=true,(w:any)=>w.assurance='verified',(w:any)=>w.limitations.pop(),(w:any)=>w.versions[index].coverage.linkedDocumentMonths=2,(w:any)=>w.versions[index].coverage.unambiguousDocumentMonths=1,(w:any)=>w.versions[index].coverage.quantityDifferenceMonths=[],(w:any)=>w.versions[index].links[1]=structuredClone(w.versions[index].links[0]),(w:any)=>w.versions[index].links[1].source.sha256=w.versions[index].links[0].source.sha256,(w:any)=>w.versions[index].links[0].month='2023-02',(w:any)=>w.versions[index].links[0].quantityDifferenceReason=null,(w:any)=>delete w.versions[index].links[0].quantityDifferenceReason,(w:any)=>w.versions[index].links[0].confirmedBy=crypto.randomUUID(),(w:any)=>w.versions[index].annual.review=annual.versions[0].review,(w:any)=>w.versions[index].annual.months[0].quantityKwh='12345.000',(w:any)=>w.versions[index].annual.id=annual.versions.at(-1).id,(w:any)=>w.versions[index].previousVersionId=null]){const value=structuredClone(evidence);mutate(value);expect(()=>decodeAnnualElectricityEvidence(value,company,annual)).toThrow()}
 const reordered=JSON.parse(JSON.stringify(evidence,(_k,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).reverse()):v));expect(decodeAnnualElectricityEvidence(reordered,company,annual).versions.length).toBe(evidence.versions.length)
})
test('actual evidence transport refuses late header/body success and revoked actor callbacks',async()=>{
 for(const timing of ['headers','body']){const c=new AbortController();globalThis.fetch=(async()=>{if(timing==='headers'){c.abort();return Response.json(evidence)}return {ok:true,status:200,json:async()=>{c.abort();return evidence}} as Response}) as typeof fetch;await refuses(()=>annualEvidenceRequest({...actor,signal:c.signal},company,annual))}
 let unauthorized=0;globalThis.fetch=(async()=>new Response('',{status:403})) as typeof fetch;await refuses(()=>annualEvidenceRequest({...actor,onUnauthorized:()=>unauthorized++},company,annual));expect(unauthorized).toBe(1)
 let sent:any;globalThis.fetch=(async(_url,init)=>{sent=JSON.parse(String(init?.body));return Response.json(evidence)}) as typeof fetch;const a=annual.versions[0];const payload={annualVersionId:a.id,expectedAnnualInputSha256:a.inputSha256,expectedAnnualResultSha256:a.resultSha256,links:[],idempotencyKey:crypto.randomUUID()};await annualEvidenceRequest(actor,company,annual,'create',payload);expect(sent).toEqual(payload)
})
test('real report transport verifies metadata then exact bytes; rejects body abort, corruption and denied access',async()=>{
 let calls=0;globalThis.fetch=(async()=>++calls===1?Response.json(report):new Response(reportHtml,{headers:{'content-type':'text/html'}})) as typeof fetch;expect(await readAnnualEvidenceReportHtml(actor,evidence,annual,report)).toBe(reportHtml);expect(calls).toBe(2)
 for(const mode of ['denied','bytes','late']){calls=0;const c=new AbortController();globalThis.fetch=(async()=>{if(++calls===1)return Response.json(report);if(mode==='denied')return new Response('',{status:403});if(mode==='late'){c.abort();return new Response(reportHtml,{headers:{'content-type':'text/html'}})}return new Response(reportHtml+'forged',{headers:{'content-type':'text/html'}})}) as typeof fetch;await refuses(()=>readAnnualEvidenceReportHtml({...actor,signal:c.signal},evidence,annual,report))}
 globalThis.fetch=(async()=>Response.json({profile:report.profile,companyId:company,reports:[report,report]})) as typeof fetch;await refuses(()=>listAnnualEvidenceReports(actor,evidence,annual))
 for(const mode of ['list','create']){const c=new AbortController();globalThis.fetch=(async()=>({ok:true,status:200,json:async()=>{c.abort();return mode==='list'?{profile:report.profile,companyId:company,reports:[report]}:report}} as Response)) as typeof fetch;await refuses(()=>mode==='list'?listAnnualEvidenceReports({...actor,signal:c.signal},evidence,annual):createAnnualEvidenceReport({...actor,signal:c.signal},evidence,annual,{} as any))}
})
test('report frozen source, lineage, review and template substitutions refuse',()=>{for(const mutate of [(r:any)=>r.source.coverage.linkedDocumentMonths=12,(r:any)=>r.source.annual.months[0].quantityKwh='99.000',(r:any)=>r.sourceVersionId=evidence.versions.at(-1).id,(r:any)=>r.reviewState='accepted_bounded_internal_draft',(r:any)=>r.templateSha256='1'.repeat(64),(r:any)=>r.source.links[0].quantityDifferenceReason='Changed later']){const r=structuredClone(report);mutate(r);expect(()=>decodeAnnualEvidenceReport(r,evidence,annual)).toThrow()}})
test('Docker web/runtime stages and deny-by-default context include every new imported M68 module',async()=>{
 const docker=await Bun.file(new URL('../../Dockerfile.staging',import.meta.url)).text(),ignore=await Bun.file(new URL('../../Dockerfile.staging.dockerignore',import.meta.url)).text(),web=docker.split('FROM workspace AS web-build')[1]!.split('FROM workspace AS production-dependencies')[0]!,runtime=docker.split('FROM python:')[1]!
 for(const name of ['m68-contract.ts','m68-template.ts'])expect(web).toContain('packages/neuvetra-database/src/'+name)
 for(const file of ['packages/neuvetra-database/src/m68.ts','packages/neuvetra-database/src/m68-contract.ts','packages/neuvetra-database/src/m68-template.ts','packages/neuvetra-database/src/m68-report.ts','packages/neuvetra-database/src/migrations/0014_annual_electricity_evidence.sql','apps/site-api/src/workspace/m68-routes.ts','apps/site-api/src/workspace/m68-report-routes.ts']){expect(runtime).toContain(file);expect(ignore.split(/\r?\n/)).toContain('!'+file)}
})
