import {expect,test} from 'bun:test'
import {createM71Seed,M71_ARTIFACT} from '../../packages/neuvetra-database/src/m71-contract'
import {M71_EVIDENCE_SHA256,validateM71Snapshot,deriveM71Findings,m71VersionHashPayload} from '../../packages/neuvetra-database/src/m71-validation'
import {M74_PROFILE,M74_PERIOD,M74_LIMITATIONS} from '../../packages/neuvetra-database/src/m74-contract'
import {m74CanonicalJson,m74SourceChoices,validateM74Save,m74Activity,deriveM74ActivityStatus,deriveM74Findings,m74CanCalculate,m74FuelStatementText,m74MileageStatementText,m74InputHashPayload,m74ContentPayload,m74VersionHashPayload,m74CalculationHashPayload,m74ReviewHashPayload,m74ReportHashPayload} from '../../packages/neuvetra-database/src/m74-validation'
import {m74ReportSnapshot,m74RenderReport} from '../../packages/neuvetra-database/src/m74-report'
import {createM74Authority} from '../../apps/site-api/src/calculation/m74-authority'
import {decodeMobileVersion,decodeMobileRegister,decodeMobileReport} from '../../apps/site-web/src/lib/m74-api'

// Valid canonical synthetic objects plus the real Python authority. This is NOT native persistence evidence.
const id=(n:number)=>`74000000-0000-4000-8000-${String(n).padStart(12,'0')}`
const hash=(v:unknown)=>new Bun.CryptoHasher('sha256').update(m74CanonicalJson(v)).digest('hex')
const bytesHash=(v:string)=>new Bun.CryptoHasher('sha256').update(v).digest('hex')
function rehash(v:any){if(v.calculation){v.calculation.inputSha256=hash(v.calculation.input);v.calculation.resultSha256=hash(m74CalculationHashPayload(v.calculation))}v.inputSha256=hash(m74InputHashPayload(v));v.contentSha256=hash(m74ContentPayload(v));v.versionSha256=hash(m74VersionHashPayload(v));return v}
function coverage(){const snapshot=createM71Seed(),source={id:id(40),entityId:snapshot.entities[0]!.id,facilityId:snapshot.facilities[0]!.id,name:'Synthetic interstate truck',domain:'mobile_combustion',...M74_PERIOD,evidenceRefs:[]};snapshot.sources.push(source);snapshot.coverageItems.push({id:id(41),domain:'mobile_combustion',entityId:source.entityId,sourceId:source.id,disposition:'missing',activityDataState:'missing',evidenceState:'missing',methodReadiness:'candidate',reason:null,evidenceRefs:[],estimateBasis:null,quantity:null,unit:null,...M74_PERIOD});snapshot.boundaryDecisions[0]!.reason='Synthetic wholly controlled operation for full calendar year.';snapshot.boundaryDecisions[0]!.evidenceRefs=[{artifactId:M71_ARTIFACT.id,expectedSha256:M71_EVIDENCE_SHA256,locator:M71_ARTIFACT.locator,purpose:'Synthetic full-year boundary assertion'}];const normalized=validateM71Snapshot(snapshot);const v:any={id:id(2),inventoryId:id(3),companyId:id(1),version:1,previousVersionId:null,previousVersionSha256:null,createdBy:id(4),createdAt:'2026-09-15T00:00:00.000Z',contributorIds:[id(4)],correctionReason:null,snapshot:normalized,contentSha256:hash(normalized),versionSha256:'',findings:deriveM71Findings(normalized),synthetic:true,corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none',emissionsTotals:null,review:null};v.versionSha256=hash(m71VersionHashPayload(v));return v}
async function makeVersion(patch:any={}){const cv=coverage(),binding=m74SourceChoices(cv)[0]!.binding;const input=validateM74Save({profile:M74_PROFILE,binding,period:M74_PERIOD,vehicle:{assetId:'QA-TRUCK-001',vehicleClass:'Medium- and Heavy-Duty Vehicles',classificationBasis:'Synthetic owned medium/heavy truck, full-year operational control.',modelYear:2018,fuel:'Fossil Diesel',controlBasis:'owned_operational_control_full_year'},quantityGallons:'1000.125',distanceMiles:'12000.500',fuelStatement:{issuer:'Synthetic fleet',reference:'QA-FUEL-001',statedQuantityGallons:'1000.125',description:'Dedicated consumed fossil fuel, no stock adjustment or auxiliary engine.',consumptionBasis:'dedicated_vehicle_consumed_no_adjustments'},mileageStatement:{issuer:'Synthetic fleet',reference:'QA-MILES-001',statedDistanceMiles:'12000.500',description:'All actual trip locations including interstate travel.',distanceBasis:'dedicated_vehicle_annual_distance'},fuelManualConfirmation:true,mileageManualConfirmation:true,fuelDiscrepancyReason:null,mileageDiscrepancyReason:null,zeroReason:null,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:id(5),...patch});const activity=m74Activity(input)
 const retain=(kind:'fuel'|'mileage')=>{const text=kind==='fuel'?m74FuelStatementText(activity,cv):m74MileageStatementText(activity,cv),statementId=kind==='fuel'?id(8):id(9);return {id:statementId,profile:`m74-synthetic-${kind}-statement-v1`,input:kind==='fuel'?activity.fuelStatement:activity.mileageStatement,locator:`m74-${kind}-statement:${statementId}:annual-activity`,text,sha256:bytesHash(text),byteLength:new TextEncoder().encode(text).length}}
 const fuelStatement=activity.fuelStatement===null?null:retain('fuel'),mileageStatement=activity.mileageStatement===null?null:retain('mileage'),calculation=m74CanCalculate(activity)?await createM74Authority().calculate({binding,period:M74_PERIOD,vehicle:activity.vehicle,quantityGallons:activity.quantityGallons!,quantityUnit:'US_gallon',distanceMiles:activity.distanceMiles!,distanceUnit:'vehicle_mile',fuelStatementSha256:fuelStatement!.sha256,mileageStatementSha256:mileageStatement!.sha256}):null
 return rehash({id:id(10),companyId:id(1),worksheetId:id(7),version:1,previousVersionId:null,previousVersionSha256:null,createdBy:id(4),createdAt:'2026-09-15T01:00:00.000Z',contributorIds:[id(4)],correctionReason:null,activity,activityStatus:deriveM74ActivityStatus(activity),coverageVersion:cv,fuelStatement,mileageStatement,calculation,findings:deriveM74Findings(activity),inputSha256:'',contentSha256:'',versionSha256:'',synthetic:true,scope1Completeness:'incomplete',corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none',review:null})
}
const positive=await makeVersion()
function makeReview(version:any){const r:any={id:id(20),versionId:version.id,versionSha256:version.versionSha256,decision:'accepted_bounded_internal',note:'Bounded internal review only; inventory remains incomplete.',acknowledgedLimitations:[...M74_LIMITATIONS],reviewerId:id(21),reviewedAt:'2026-09-15T02:00:00.000Z',decisionSha256:''};r.decisionSha256=hash(m74ReviewHashPayload(id(1),r));return r}
function makeReport(version:any,review:any=null){const snapshot=m74ReportSnapshot(version,review),snapshotJson=m74CanonicalJson(snapshot),html=m74RenderReport(snapshot),r:any={id:id(22),companyId:id(1),worksheetId:version.worksheetId,versionId:version.id,versionSha256:version.versionSha256,decisionId:review?.id??null,decisionSha256:review?.decisionSha256??null,createdBy:id(21),createdAt:'2026-09-15T03:00:00.000Z',rendererVersion:'m74-mobile-source-report-v1',html,htmlSha256:bytesHash(html),htmlByteLength:new TextEncoder().encode(html).length,snapshotJson,snapshotSha256:bytesHash(snapshotJson),reportSha256:''};r.reportSha256=hash(m74ReportHashPayload(r));return r}
function register(v:any,reports:any[]=[]){return {profile:M74_PROFILE,companyId:id(1),coverageHeadVersionId:v.coverageVersion.id,worksheets:[{profile:M74_PROFILE,companyId:id(1),worksheetId:v.worksheetId,sourceId:v.activity.binding.sourceId,vehicleAssetId:v.activity.vehicle.assetId,headVersionId:v.id,versions:[v],reports,findings:[],limitations:[...M74_LIMITATIONS],synthetic:true,scope1Completeness:'incomplete',corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none'}],sources:m74SourceChoices(v.coverageVersion),coverageFindings:v.coverageVersion.findings,limitations:[...M74_LIMITATIONS],synthetic:true,scope1Completeness:'incomplete',corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none'}}

test('real authority result and both separate statement identities survive complete decoder',async()=>{expect(positive.calculation.total.unrounded).toBe('10351.53209375');expect(positive.calculation.total.display).toBe('10351.5321');expect(await decodeMobileVersion(positive,id(1))).toEqual(positive);expect(await decodeMobileRegister(register(positive),id(1))).toEqual(register(positive));expect(positive.fuelStatement.sha256).not.toBe(positive.mileageStatement.sha256)})
for(const [name,mutate] of [
 ['fuel unit',(v:any)=>{v.calculation.input.quantityUnit='litre'}],['distance unit',(v:any)=>{v.calculation.input.distanceUnit='kilometre'}],['result profile',(v:any)=>{v.calculation.profile='m73-decimal-result-v1'}],['method release',(v:any)=>{v.calculation.method.releaseEligible=true}],['method factor',(v:any)=>{v.calculation.method.ch4GramsPerMile='1.0'}],['gas mass unit',(v:any)=>{v.calculation.gasResults.ch4.massUnit='g CH4'}],['activity hash',(v:any)=>{v.activity.distanceMiles='13000.000'}],['fuel statement profile',(v:any)=>{v.fuelStatement.profile='m74-synthetic-mileage-statement-v1'}],['mileage statement profile',(v:any)=>{v.mileageStatement.profile='m74-synthetic-fuel-statement-v1'}],['duplicate statement id',(v:any)=>{v.mileageStatement.id=v.fuelStatement.id}],['statement locator',(v:any)=>{v.fuelStatement.locator='unknown:statement'}],['future vehicle year',(v:any)=>{v.activity.vehicle.modelYear=2023}],['wrong binding',(v:any)=>{v.activity.binding.facilityId=id(99)}],['gas result extra field',(v:any)=>{v.calculation.gasResults.co2.extra=true}],['dimension status',(v:any)=>{v.activityStatus.mileage='missing'}],['coverage source',(v:any)=>{v.coverageVersion.snapshot.sources.at(-1).name='Substituted source'}],['coordinated statement bytes',(v:any)=>{v.mileageStatement.text+='forged';v.mileageStatement.sha256=bytesHash(v.mileageStatement.text);v.mileageStatement.byteLength=new TextEncoder().encode(v.mileageStatement.text).length;v.calculation.input.mileageStatementSha256=v.mileageStatement.sha256}],
] as const)test(`complete decoder rejects ${name} even with rewritten outer hashes`,async()=>{const v=structuredClone(positive);mutate(v);rehash(v);await expect(decodeMobileVersion(v,id(1))).rejects.toThrow()})

for(const patch of [{distanceMiles:null},{quantityGallons:null},{quantityGallons:'0.000'}])test(`missing/contradictory input retains no subtotal: ${JSON.stringify(patch)}`,async()=>{const v=await makeVersion(patch);expect(v.calculation).toBeNull();expect(await decodeMobileVersion(v,id(1))).toEqual(v);const forged=structuredClone(v);forged.calculation=structuredClone(positive.calculation);rehash(forged);await expect(decodeMobileVersion(forged,id(1))).rejects.toThrow()})

test('reviewed and unreviewed exact report snapshots decode; rewritten malicious HTML is refused',async()=>{for(const review of [null,makeReview(positive)]){const version={...positive,review},report=makeReport(version,review);expect(await decodeMobileReport(report,id(1),version)).toEqual(report);const forged=structuredClone(report);forged.html+='<script>alert(1)</script>';forged.htmlSha256=bytesHash(forged.html);forged.htmlByteLength=new TextEncoder().encode(forged.html).length;forged.reportSha256=hash(m74ReportHashPayload(forged));await expect(decodeMobileReport(forged,id(1),version)).rejects.toThrow()}})

test('report must not predate the review it claims to capture, including standalone decode',async()=>{const review=makeReview(positive),version={...positive,review},report=makeReport(version,review);report.createdAt='2026-09-15T01:30:00.000Z';report.reportSha256=hash(m74ReportHashPayload(report));await expect(decodeMobileReport(report,id(1),version)).rejects.toThrow();await expect(decodeMobileReport(report,id(1))).rejects.toThrow();const beforeVersion=makeReport(positive);beforeVersion.createdAt='2026-09-15T00:30:00.000Z';beforeVersion.reportSha256=hash(m74ReportHashPayload(beforeVersion));await expect(decodeMobileReport(beforeVersion,id(1))).rejects.toThrow()})
test('duplicate report identities and different identities for the same state are rejected',async()=>{for(const differentIdentity of [false,true]){const report=makeReport(positive),duplicate=structuredClone(report);if(differentIdentity){duplicate.id=id(23);duplicate.reportSha256=hash(m74ReportHashPayload(duplicate))}await expect(decodeMobileRegister(register(positive,[report,duplicate]),id(1))).rejects.toThrow()}})
test('equivalent reordered JSON object keys preserve canonical version acceptance',async()=>{const reorder=(v:any):any=>Array.isArray(v)?v.map(reorder):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).reverse().map(([k,x])=>[k,reorder(x)])):v;expect(await decodeMobileVersion(reorder(positive),id(1))).toEqual(positive)})
