import {expect,test} from 'bun:test'
import {M74_LIMITATIONS,M74_PERIOD,M74_PROFILE} from '../../packages/neuvetra-database/src/m74-contract'
import {validateM74Save} from '../../packages/neuvetra-database/src/m74-validation'

// Actual component handlers with injected hooks and transport; not React DOM/browser evidence.
const source=await Bun.file(new URL('../../apps/site-web/src/components/MobileDiesel.tsx',import.meta.url)).text()
const script=new Bun.Transpiler({loader:'tsx',tsconfig:{compilerOptions:{jsx:'react',jsxFactory:'h',jsxFragmentFactory:'Fragment'}}}).transformSync(source.replace(/^import[^\r\n]*(?:\r?\n|$)/gm,'').replace('export function MobileDiesel','function MobileDiesel'))+'\nreturn MobileDiesel'
const id=(n:number)=>`74000000-0000-4000-8000-${String(n).padStart(12,'0')}`
const binding={coverageVersionId:id(1),coverageVersionSha256:'a'.repeat(64),entityId:id(2),facilityId:id(3),sourceId:id(4),boundaryDecisionId:id(5)}
const activity={profile:M74_PROFILE,binding,period:M74_PERIOD,vehicle:{assetId:'TRUCK-001',vehicleClass:'Medium- and Heavy-Duty Vehicles',classificationBasis:'Synthetic owned heavy-duty distribution truck controlled for all of 2025.',modelYear:2018,fuel:'Fossil Diesel',controlBasis:'owned_operational_control_full_year'},quantityGallons:'1000.125',distanceMiles:'12000.500',fuelStatement:{issuer:'Synthetic fleet',reference:'FUEL-001',statedQuantityGallons:'1000.125',description:'Dedicated fossil fuel consumed, no stock adjustment.',consumptionBasis:'dedicated_vehicle_consumed_no_adjustments'},mileageStatement:{issuer:'Synthetic fleet',reference:'MILES-001',statedDistanceMiles:'12000.500',description:'All vehicle travel, including interstate.',distanceBasis:'dedicated_vehicle_annual_distance'},fuelManualConfirmation:true,mileageManualConfirmation:true,fuelDiscrepancyReason:null,mileageDiscrepancyReason:null,zeroReason:null}
function fixture(){const versions=[1,2].map(n=>({id:id(10+n),worksheetId:id(8),version:n,versionSha256:String(n).repeat(64),createdAt:'2026-09-15T00:00:00.000Z',activity:structuredClone(activity),activityStatus:{fuel:'entered',mileage:'entered'},calculation:{total:{unrounded:n===1?'10351.53209375':'10357.37584375',display:n===1?'10351.5321':'10357.3758'},gasResults:{},method:{}},fuelStatement:null,mileageStatement:null,findings:[],review:null,contributorIds:[id(30)],correctionReason:n===1?null:'Correct annual mileage'}));return {profile:M74_PROFILE,companyId:id(6),coverageHeadVersionId:id(1),worksheets:[{worksheetId:id(8),sourceId:id(4),vehicleAssetId:'TRUCK-001',headVersionId:id(12),versions,reports:[],findings:[]}],sources:[{binding,companyLabel:'Synthetic group',entityLabel:'Synthetic entity',facilityLabel:'Synthetic depot',sourceLabel:'Distribution truck',eligible:true,findings:[]}],coverageFindings:[]}}
function deferred<T>(){let resolve!:(v:T)=>void;const promise=new Promise<T>(r=>{resolve=r});return {promise,resolve}}
function harness(register:any=fixture(),role='owner',initialRequest?:()=>Promise<any>){
 const slots:any[]=[],effects:Record<number,{deps:any[];cleanup?:()=>void}>={};let cursor=0,tree:any,updates=0,savePayload:any,reportPayload:any,reviewPayload:any,request=initialRequest??(async()=>register),saveTransport=async()=>({...register.worksheets[0].versions[1],calculation:null})
 let controller=new AbortController(),actor:any={userId:id(31),role,accessToken:'synthetic-test-token',signal:controller.signal};const pending:Array<()=>void>=[]
 const h=(type:any,props:any,...children:any[])=>({type,props:props??{},children})
 const component=new Function('useCallback','useEffect','useRef','useState','mobileRegisterRequest','mobileSaveRequest','mobileReviewRequest','mobileReportRequest','mobileReportDownload','mobileStatementDownload','mobileExportRequest','M74_LIMITATIONS','M74_PERIOD','M74_PROFILE','validateM74Save','h','Fragment',script)(
  (fn:any)=>{cursor++;return fn},(fn:any,deps:any[])=>{const n=cursor++;const prior=effects[n];if(!prior||deps.some((v,i)=>i===2?false:v!==prior.deps[i]))pending.push(()=>{prior?.cleanup?.();effects[n]={deps,cleanup:fn()}})},(v:any)=>{const n=cursor++;return slots[n]??(slots[n]={current:v})},(v:any)=>{const n=cursor++;if(!(n in slots))slots[n]=typeof v==='function'?v():v;return[slots[n],(next:any)=>{updates++;slots[n]=typeof next==='function'?next(slots[n]):next}]},
  ()=>request(),async(_a:any,_c:any,_w:any,p:any)=>{savePayload=structuredClone(p);return saveTransport()},async(_a:any,_c:any,_w:any,p:any)=>{reviewPayload=p},async(_a:any,_c:any,_w:any,p:any)=>{reportPayload=p},async()=>'',async()=>'',async()=>'',M74_LIMITATIONS,M74_PERIOD,M74_PROFILE,validateM74Save,h,'fragment')
 function render(){cursor=0;tree=component({actor,workspaceId:id(6),headingRef:{current:null}});while(pending.length)pending.shift()!()}
 const flatten=(n:any):any[]=>n&&typeof n==='object'&&'type'in n?[n,...n.children.flat(Infinity).flatMap(flatten)]:[]
 const text=(n:any):string=>n&&typeof n==='object'&&'children'in n?n.children.flat(Infinity).map(text).join(' ').replace(/\s+/g,' ').trim():typeof n==='string'||typeof n==='number'?String(n):''
 const nodes=()=>flatten(tree),field=(name:string)=>nodes().find(n=>n.props.id===name),button=(name:string)=>nodes().find(n=>n.type==='button'&&text(n)===name)
 function change(name:string,value:any){const node=field(name);expect(Boolean(node)).toBe(true);node.props.onChange({target:typeof value==='boolean'?{checked:value}:{value}});render()}
 async function flush(){for(let n=0;n<30;n++)await Promise.resolve();render()}
 function submit(heading:string){const form=nodes().find(n=>n.type==='form'&&text(n).includes(heading));expect(Boolean(form)).toBe(true);form.props.onSubmit({preventDefault(){}})}
 render();return {render,flush,nodes,field,button,change,submit,text:()=>text(tree),updates:()=>updates,savePayload:()=>savePayload,reportPayload:()=>reportPayload,reviewPayload:()=>reviewPayload,setSaveTransport(fn:()=>Promise<any>){saveTransport=fn},replaceActor(nextRole:string,nextRequest:()=>Promise<any>){controller.abort();controller=new AbortController();actor={...actor,role:nextRole,signal:controller.signal};request=nextRequest;render()},cleanup(){controller.abort();for(const e of Object.values(effects))e.cleanup?.()}}
}

test('editing the saved vehicle hides old numerical totals and locks vehicle identity',async()=>{const h=harness();await h.flush();expect(h.text()).toContain('10357.37584375');h.button('Make a correction').props.onClick();h.render();expect(h.text()).not.toContain('10357.37584375');expect(h.field('mobile-asset').props.disabled).toBe(true);expect(h.field('mobile-source').props.disabled).toBe(true);expect(h.field('mobile-fuel-confirm').props.checked).toBe(false);expect(h.field('mobile-mileage-confirm').props.checked).toBe(false);h.cleanup()})

test('actual correction handler preserves missing mileage as null and separate confirmations',async()=>{const h=harness();await h.flush();h.button('Make a correction').props.onClick();h.render();h.change('mobile-miles','');h.change('mobile-correction','Retain missing mileage for follow-up.');h.change('mobile-fuel-confirm',true);h.submit('Correct vehicle activity');await h.flush();expect(h.savePayload().distanceMiles).toBeNull();expect(h.savePayload().quantityGallons).toBe('1000.125');expect(h.savePayload().fuelManualConfirmation).toBe(true);expect(h.savePayload().mileageManualConfirmation).toBe(false);expect(h.savePayload().vehicle.assetId).toBe('TRUCK-001');h.cleanup()})

test('actual save handler preserves explicit zero and dimension-specific discrepancy reasons',async()=>{const h=harness();await h.flush();h.button('Make a correction').props.onClick();h.render();h.change('mobile-gallons','0');h.change('mobile-miles','0');h.change('mobile-fuel-stated','0');h.change('mobile-mileage-stated','0');h.change('mobile-zero','Vehicle did not operate or consume fuel.');h.change('mobile-correction','Confirm no annual operation.');h.change('mobile-fuel-discrepancy','Fuel statement correction recorded.');h.change('mobile-mileage-discrepancy','Mileage statement correction recorded.');h.change('mobile-fuel-confirm',true);h.change('mobile-mileage-confirm',true);h.submit('Correct vehicle activity');await h.flush();const p=h.savePayload();expect(p.quantityGallons).toBe('0');expect(p.distanceMiles).toBe('0');expect(p.fuelDiscrepancyReason).toContain('Fuel');expect(p.mileageDiscrepancyReason).toContain('Mileage');expect(p.zeroReason).toContain('did not');h.cleanup()})

test('unsupported model year stays unsaved and does not expose a stale subtotal',async()=>{const h=harness();await h.flush();h.button('Make a correction').props.onClick();h.render();h.change('mobile-year','2024');h.change('mobile-correction','Unsupported test.');h.submit('Correct vehicle activity');await h.flush();expect(h.savePayload()).toBeUndefined();expect(h.text()).toContain('Nothing was saved');expect(h.text()).not.toContain('10357.37584375');h.cleanup()})

test('historical selection can create its exact report but cannot present review of a different latest version',async()=>{const h=harness();await h.flush();h.change('mobile-version',id(11));expect(h.text()).toContain('10351.53209375');expect(h.field('mobile-review-note')).toBeUndefined();h.button('Create vehicle report').props.onClick();await h.flush();expect(h.reportPayload().versionId).toBe(id(11));h.cleanup()})

test('same-user demotion clears the owner draft immediately while the replacement register is pending',async()=>{const h=harness();await h.flush();h.button('Make a correction').props.onClick();h.render();h.change('mobile-classification','Private unsaved owner classification');const pending=deferred<any>();h.replaceActor('member',()=>pending.promise);h.render();expect(h.button('Save vehicle version')).toBeUndefined();expect(h.field('mobile-classification')).toBeUndefined();h.cleanup()})

test('late initial responses after unmount cannot update component state',async()=>{const pending=deferred<any>(),h=harness(fixture(),'owner',()=>pending.promise);h.cleanup();const count=h.updates();pending.resolve(fixture());await h.flush();expect(h.updates()).toBe(count)})

test('late save completion or failure cannot update or unlock a replacement actor lifetime',async()=>{
 for(const fail of [false,true]){const pending=deferred<any>(),replacement=deferred<any>(),h=harness();await h.flush();h.setSaveTransport(()=>fail?pending.promise.then(()=>{throw Error('Old actor save failed')}):pending.promise);h.button('Make a correction').props.onClick();h.render();h.change('mobile-correction','Old actor pending correction.');h.submit('Correct vehicle activity');h.render();expect(h.savePayload()).toBeDefined();h.replaceActor('member',()=>replacement.promise);h.render();const before=h.updates();pending.resolve({...fixture().worksheets[0]!.versions[1],calculation:null});await h.flush();expect(h.updates()).toBe(before);expect(h.button('Refresh mobile sources').props.disabled).toBe(true);expect(h.button('Save vehicle version')).toBeUndefined();replacement.resolve(fixture());await h.flush();expect(h.text()).toContain('Read-only member access');expect(h.text()).not.toContain('Old actor save failed');h.cleanup()}
})

test('switching away from the review target clears acknowledgment and note before returning',async()=>{const h=harness();await h.flush();h.change('mobile-review-note','Reviewing the latest exact vehicle version.');h.change('mobile-review-ack',true);h.change('mobile-version',id(11));expect(h.field('mobile-review-note')).toBeUndefined();h.change('mobile-version',id(12));expect(h.field('mobile-review-note').props.value).toBe('');expect(h.field('mobile-review-ack').props.checked).toBe(false);h.cleanup()})

test('all actual draft inputs have meaningful labels and member has no writing controls',async()=>{const h=harness();await h.flush();h.button('Make a correction').props.onClick();h.render();const labels=h.nodes().filter(n=>n.type==='label');for(const input of h.nodes().filter(n=>['input','select','textarea'].includes(n.type))){expect(typeof input.props.id).toBe('string');expect(labels.some(l=>l.props.htmlFor===input.props.id)).toBe(true)}expect(h.text()).toContain('all trip locations');expect(h.nodes().some(n=>n.props.role==='status')).toBe(true);h.cleanup();const member=harness(fixture(),'member');await member.flush();expect(member.button('Make a correction')).toBeUndefined();expect(member.button('Create vehicle draft')).toBeUndefined();expect(member.button('Create vehicle report')).toBeUndefined();member.cleanup()})
