import {expect,test} from 'bun:test'
import {parseM74JourneyInput,readM74Journal,runM74Journey,validateM74JourneyRoute} from '../../tools/staging/check-m74-hosted'
import {createM71Seed,M71_ARTIFACT,M71_EVIDENCE_SHA256,validateM71Snapshot,deriveM71Findings,m71VersionHashPayload,M71_PROFILE,M71_LIMITATIONS,M73_PROFILE,M73_PERIOD,M73_LIMITATIONS,m73SourceChoices,m73Activity,validateM73Save,m73StatementText,m73InputHashPayload,m73ContentPayload,m73VersionHashPayload,deriveM73Findings,m73ReviewHashPayload,m73ReportSnapshot,m73RenderReport,m73ReportHashPayload,m73Export,M74_PROFILE,M74_LIMITATIONS,m74SourceChoices,m74Activity,validateM74Save,m74FuelStatementText,m74MileageStatementText,m74InputHashPayload,m74ContentPayload,m74VersionHashPayload,deriveM74Findings,deriveM74ActivityStatus,m74ReviewHashPayload,m74ReportSnapshot,m74RenderReport,m74ReportHashPayload,m74Export,m74CanonicalJson} from '../../packages/neuvetra-database/src/index'
import {createM73Authority} from '../../apps/site-api/src/calculation/m73-authority'
import {createM74Authority} from '../../apps/site-api/src/calculation/m74-authority'
const HOST='https://www.neuvetra.ai',AUTH='https://icockcoguyadhryzydvl.supabase.co',id=(n:number)=>`74000000-0000-4000-8000-${String(n).padStart(12,'0')}`,company=id(1),root=HOST+`/workspace-api/workspace/${company}`
const input=(mode='baseline')=>parseM74JourneyInput({mode,env:{SUPABASE_URL:AUTH,SUPABASE_ANON_KEY:'sb_publishable_'+'x'.repeat(30)},roster:{workspaceId:company},accounts:['manager1','manager2','member','outsider'].map((role,i)=>({role,id:id(i+10),email:role+'@synthetic.invalid',password:'synthetic-offline-password'}))})
const bytesHash=(value:string)=>new Bun.CryptoHasher('sha256').update(value).digest('hex'),hash=(value:unknown)=>bytesHash(m74CanonicalJson(value)),flags={synthetic:true,scope1Completeness:'incomplete',corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none'},observe=(text:string)=>({sha256:bytesHash(text),byteLength:new TextEncoder().encode(text).length})
const json=(value:any,status=200)=>Response.json(value,{status,headers:{'cache-control':'no-store'}}),text=(value:string)=>new Response(value,{headers:{'cache-control':'no-store'}})
function chain(rows:any[]){let previousSha256:string|null=null;return rows.map((r,i)=>{const body={sequence:i+1,previousSha256,workspaceId:company,mode:'baseline',createdAt:'2026-09-15T00:00:00.000Z',...r},sha256=hash(body);previousSha256=sha256;return JSON.stringify({...body,sha256})}).join('\n')+'\n'}
function finishVersion(v:any,mobile=false){v.inputSha256=hash(mobile?m74InputHashPayload(v):m73InputHashPayload(v));v.contentSha256=hash(mobile?m74ContentPayload(v):m73ContentPayload(v));v.versionSha256=hash(mobile?m74VersionHashPayload(v):m73VersionHashPayload(v));return v}
function makeReport(v:any,mobile=false){const snapshot=mobile?m74ReportSnapshot(v,v.review):m73ReportSnapshot(v,v.review),snapshotJson=m74CanonicalJson(snapshot),html=mobile?m74RenderReport(snapshot):m73RenderReport(snapshot);const r:any={id:crypto.randomUUID(),companyId:company,worksheetId:v.worksheetId,versionId:v.id,versionSha256:v.versionSha256,decisionId:v.review?.id??null,decisionSha256:v.review?.decisionSha256??null,createdBy:id(10),createdAt:new Date().toISOString(),rendererVersion:mobile?'m74-mobile-source-report-v1':'m73-source-report-v1',html,htmlSha256:bytesHash(html),htmlByteLength:new TextEncoder().encode(html).length,snapshotJson,snapshotSha256:bytesHash(snapshotJson),reportSha256:''};r.reportSha256=hash(mobile?m74ReportHashPayload(r):m73ReportHashPayload(r));return r}
async function baseFixture(){
 const snapshot=createM71Seed(),source={id:id(30),entityId:snapshot.entities[0]!.id,facilityId:snapshot.facilities[0]!.id,name:'Preserved synthetic gas boiler',domain:'stationary_combustion',...M73_PERIOD,evidenceRefs:[]};snapshot.sources.push(source);snapshot.coverageItems.push({id:id(31),domain:'stationary_combustion',entityId:source.entityId,sourceId:source.id,...M73_PERIOD,disposition:'missing',activityDataState:'missing',evidenceState:'missing',methodReadiness:'candidate',reason:null,evidenceRefs:[],estimateBasis:null,quantity:null,unit:null});snapshot.boundaryDecisions[0]!.reason='Preserved synthetic full-year operational control';snapshot.boundaryDecisions[0]!.evidenceRefs=[{artifactId:M71_ARTIFACT.id,expectedSha256:M71_EVIDENCE_SHA256,locator:M71_ARTIFACT.locator,purpose:'Original synthetic boundary reference'}];const normalized=validateM71Snapshot(snapshot),cv:any={id:id(32),inventoryId:id(33),companyId:company,version:1,previousVersionId:null,previousVersionSha256:null,createdBy:id(10),createdAt:'2026-09-15T00:00:00.000Z',contributorIds:[id(10)],correctionReason:null,snapshot:normalized,contentSha256:hash(normalized),versionSha256:'',findings:deriveM71Findings(normalized),synthetic:true,corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none',emissionsTotals:null,review:null};cv.versionSha256=hash(m71VersionHashPayload(cv));const corporate={profile:M71_PROFILE,companyId:company,inventoryId:cv.inventoryId,headVersionId:cv.id,versions:[cv],limitations:[...M71_LIMITATIONS]}
 const a=m73Activity(validateM73Save({profile:M73_PROFILE,binding:m73SourceChoices(cv)[0]!.binding,period:M73_PERIOD,fuel:'Natural Gas',heatBasis:'HHV',unit:'MMBtu',quantityMmbtu:'1000.000',statement:{issuer:'Synthetic gas operator',reference:'PRESERVED-GAS',meterLabel:'PRESERVED-METER',statedQuantityMmbtu:'1000.000',description:'Preserved original synthetic statement',consumptionBasis:'dedicated_meter_consumed_no_adjustments'},manualConfirmation:true,discrepancyReason:null,zeroReason:null,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:id(34)})),statementText=m73StatementText(a,cv),statement={id:id(35),profile:'m73-synthetic-gas-statement-v1',input:a.statement,locator:`m73-statement:${id(35)}:annual-activity`,text:statementText,...observe(statementText)},calculation=await createM73Authority().calculate({binding:a.binding,period:a.period,fuel:a.fuel,heatBasis:a.heatBasis,unit:a.unit,quantityMmbtu:a.quantityMmbtu!,statementSha256:statement.sha256})
 const v=finishVersion({id:id(36),companyId:company,worksheetId:id(37),version:1,previousVersionId:null,previousVersionSha256:null,createdBy:id(10),createdAt:'2026-09-15T01:00:00.000Z',contributorIds:[id(10)],correctionReason:null,activity:a,coverageVersion:cv,statement,calculation,findings:deriveM73Findings(a),inputSha256:'',contentSha256:'',versionSha256:'',...flags,review:null}),unreviewed=makeReport(v),review:any={id:id(38),versionId:v.id,versionSha256:v.versionSha256,decision:'accepted_bounded_internal',note:'Preserved synthetic review',acknowledgedLimitations:[...M73_LIMITATIONS],reviewerId:id(11),reviewedAt:'2026-09-15T02:00:00.000Z',decisionSha256:''};review.decisionSha256=hash(m73ReviewHashPayload(company,review));v.review=review;const reports=[unreviewed,makeReport(v)],gas={profile:M73_PROFILE,companyId:company,coverageHeadVersionId:cv.id,worksheets:[{profile:M73_PROFILE,companyId:company,worksheetId:v.worksheetId,sourceId:a.binding.sourceId,headVersionId:v.id,versions:[v],reports,findings:[],limitations:[...M73_LIMITATIONS],...flags}],sources:m73SourceChoices(cv),coverageFindings:cv.findings,limitations:[...M73_LIMITATIONS],...flags},downloads:any={};downloads['version_'+v.id]=observe(m73Export(v));downloads['statement_'+statement.id]=observe(statement.text);for(const r of reports)downloads['report_'+r.id]=observe(r.html)
 const legacy={records:{electricity:'a'.repeat(64)},downloads:{electricity:{sha256:'b'.repeat(64),byteLength:42}}},exports={[cv.id]:observe(m74CanonicalJson({...cv,review:null}))},previous=chain([{kind:'baseline',data:{legacy}},{kind:'exercise_complete',data:{corporate,exports,register:gas,downloads}},{kind:'revisit_verified',data:{}}]);return {corporate,gas,legacy,previous,downloads}
}
const base=await baseFixture()
function harness(){const f=structuredClone(base);let corporate=structuredClone(f.corporate),journal:string|null=null,schema=16,versions:any[]=[],reports:any[]=[],appPosts=0,tokenCount=0,logoutCount=0,failFinalRead=false,postFault:'none'|'network'|'private'|'unexpected_status'='none',outcomeAppendFailure=false,authFault=false,legacyFault=false,tamperGas=false,tamperDownload=false;const calls:any[]=[];const now=()=>new Date().toISOString()
 const gas=()=>{const value=structuredClone(f.gas);value.coverageHeadVersionId=corporate.headVersionId;value.sources=m73SourceChoices(corporate.versions.at(-1)!);value.coverageFindings=corporate.versions.at(-1)!.findings;if(corporate.headVersionId!==f.corporate.headVersionId)value.worksheets[0]!.findings=[{code:'coverage_head_changed',message:'Corporate coverage changed; relink this source before a new review or report.'}];if(tamperGas)value.worksheets[0]!.versions[0].activity.statement.description='UNEXPECTED_GAS_MUTATION';return value}
 const mobile=()=>({profile:M74_PROFILE,companyId:company,coverageHeadVersionId:corporate.headVersionId,worksheets:versions.length?[{profile:M74_PROFILE,companyId:company,worksheetId:versions[0].worksheetId,sourceId:versions[0].activity.binding.sourceId,vehicleAssetId:versions[0].activity.vehicle.assetId,headVersionId:versions.at(-1).id,versions,reports,findings:[],limitations:[...M74_LIMITATIONS],...flags}]:[],sources:m74SourceChoices(corporate.versions.at(-1)!),coverageFindings:corporate.versions.at(-1)!.findings,limitations:[...M74_LIMITATIONS],...flags})
 const fetcher=async(url:any,init:any={})=>{const u=String(url),method=init.method??'GET';calls.push({url:u,method,redirect:init.redirect,signal:init.signal});expect(init.redirect).toBe('error');expect(init.signal).toBeInstanceOf(AbortSignal)
  if(u===HOST+'/ready'){if(failFinalRead&&versions.length===2){failFinalRead=false;return json({error:'temporary offline readiness failure'},503)}return json({status:'ready',profile:'neuvetra.private-synthetic-staging.v1',legacyContainmentVerified:true,schemaVersion:schema})}
  if(u===AUTH+'/auth/v1/token?grant_type=password'){if(authFault)throw Error('UNEXPECTED_PRIVATE_AUTH_DETAIL');const account=input().accounts.find(a=>a.email===JSON.parse(init.body).email)!;tokenCount++;return json({access_token:'offline-token-'+account.role,user:{id:account.id}})}
  if(u===AUTH+'/auth/v1/logout?scope=local'){logoutCount++;return new Response(null,{status:204})}
  if(method==='GET'){
   if(u===root+'/corporate-inventories')return json(corporate)
   if(u.endsWith('/coverage-export'))return text(m74CanonicalJson({...corporate.versions.find(v=>u.includes(v.id))!,review:null}))
   if(u===root+'/stationary-natural-gas')return json(gas())
   if(u.startsWith(root+'/stationary-natural-gas/')){const w=f.gas.worksheets[0]!,v=w.versions[0];if(u.endsWith('/calculation-export'))return text(m73Export(v)+(tamperDownload?'x':''));if(u.includes('/statements/'))return text(v.statement.text);const r=w.reports.find(r=>u.includes(r.id));if(r)return text(r.html)}
   if(u===root+'/mobile-diesel')return json(mobile())
   if(u.endsWith('/calculation-export'))return text(m74Export(versions.find(v=>u.includes(v.id))))
   if(u.includes('/statements/')){const s=versions.flatMap(v=>[v.fuelStatement,v.mileageStatement]).find(s=>u.includes(s.id));return text(s.text)}
   if(u.includes('/reports/'))return text(reports.find(r=>u.includes(r.id)).html)
   throw Error('Unexpected offline GET')
  }
  appPosts++;if(postFault==='network')throw Error('UNEXPECTED_PRIVATE_NETWORK_DETAIL');if(postFault==='private')return json({...corporate.versions.at(-1),access_token:'UNEXPECTED_PRIVATE_SUCCESS_FIELD'},201);if(postFault==='unexpected_status')return json({privateDetail:'UNEXPECTED_PRIVATE_403_FIELD'},403)
  const body=JSON.parse(init.body),role=String(init.headers.authorization??'').replace('Bearer offline-token-','');if(!role)return json({privateDetail:'UNEXPECTED_PRIVATE_SIGNED_OUT'},401);if(['member','outsider'].includes(role))return json({privateDetail:'UNEXPECTED_PRIVATE_REFUSAL'},403)
  if(u.includes('/corporate-inventories/')){const prior=corporate.versions.at(-1)!,snapshot=validateM71Snapshot(body.snapshot,prior.snapshot),v={...prior,id:crypto.randomUUID(),version:prior.version+1,previousVersionId:prior.id,previousVersionSha256:prior.versionSha256,createdAt:now(),correctionReason:body.correctionReason,snapshot,findings:deriveM71Findings(snapshot),contentSha256:hash(snapshot),versionSha256:''};v.versionSha256=hash(m71VersionHashPayload(v));corporate.versions.push(v);corporate.headVersionId=v.id;return json(v,201)}
  if(u.endsWith('/reviews')){if(role==='manager1')return json({privateDetail:'UNEXPECTED_PRIVATE_CONTRIBUTOR'},403);const v=versions.find(v=>v.id===body.versionId),r:any={id:crypto.randomUUID(),versionId:v.id,versionSha256:v.versionSha256,decision:body.decision,note:body.note,acknowledgedLimitations:body.acknowledgedLimitations,reviewerId:id(11),reviewedAt:now(),decisionSha256:''};r.decisionSha256=hash(m74ReviewHashPayload(company,r));v.review=r;return json(r,201)}
  if(u.endsWith('/reports')){const v=versions.find(v=>v.id===body.versionId),r=makeReport(v,true);reports.push(r);return json(r,201)}
  const activity=m74Activity(validateM74Save(body)),cv=corporate.versions.at(-1)!,statement=(kind:'fuel'|'mileage')=>{const statementId=crypto.randomUUID(),t=kind==='fuel'?m74FuelStatementText(activity,cv):m74MileageStatementText(activity,cv);return {id:statementId,profile:`m74-synthetic-${kind}-statement-v1`,input:kind==='fuel'?activity.fuelStatement:activity.mileageStatement,locator:`m74-${kind}-statement:${statementId}:annual-activity`,text:t,...observe(t)}},fuelStatement=statement('fuel'),mileageStatement=statement('mileage'),prior=versions.at(-1),calculation=await createM74Authority().calculate({binding:activity.binding,period:activity.period,vehicle:activity.vehicle,quantityGallons:activity.quantityGallons!,quantityUnit:'US_gallon',distanceMiles:activity.distanceMiles!,distanceUnit:'vehicle_mile',fuelStatementSha256:fuelStatement.sha256,mileageStatementSha256:mileageStatement.sha256}),v=finishVersion({id:crypto.randomUUID(),companyId:company,worksheetId:prior?.worksheetId??crypto.randomUUID(),version:versions.length+1,previousVersionId:prior?.id??null,previousVersionSha256:prior?.versionSha256??null,createdBy:id(10),createdAt:now(),contributorIds:[id(10)],correctionReason:body.correctionReason,activity,activityStatus:deriveM74ActivityStatus(activity),coverageVersion:cv,fuelStatement,mileageStatement,calculation,findings:deriveM74Findings(activity),inputSha256:'',contentSha256:'',versionSha256:'',...flags,review:null},true);versions.push(v);return json(v,201)
 }
 const deps:any={load:async()=>journal,append:async(line:string,exclusive:boolean)=>{expect(exclusive).toBe(journal===null);if(outcomeAppendFailure&&JSON.parse(line).kind==='post_outcome')throw Error('OFFLINE_JOURNAL_WRITE_FAILURE');journal=(journal??'')+line},loadPrevious:async()=>f.previous,legacy:async(_input:any,d:any)=>{const r=await d.fetch(HOST+'/ready',{method:'GET'});expect((await r.json()).schemaVersion).toBe(14);if(legacyFault)await d.fetch(root+'/members',{method:'POST'});await d.save({baseline:f.legacy});return {status:'passed',allCreatedAuthSessionsClosed:true,applicationPostRequests:0}},fetch:fetcher}
 return {deps,calls,get journal(){return journal},set journal(v:string|null){journal=v},set schema(v:number){schema=v},set failFinalRead(v:boolean){failFinalRead=v},set postFault(v:typeof postFault){postFault=v},set outcomeAppendFailure(v:boolean){outcomeAppendFailure=v},set authFault(v:boolean){authFault=v},set legacyFault(v:boolean){legacyFault=v},set tamperGas(v:boolean){tamperGas=v},set tamperDownload(v:boolean){tamperDownload=v},get appPosts(){return appPosts},get tokenCount(){return tokenCount},get logoutCount(){return logoutCount},get versions(){return versions},get reports(){return reports},get gas(){return gas()},get corporate(){return corporate}}
}

test('full offline16→17 exercise and zero-write revisit preserve nonempty M73 versions/reports despite legitimate head-drift findings',async()=>{const h=harness();const baseline=await runM74Journey(input(),h.deps);expect(baseline.status,baseline.stage).toBe('passed');expect(h.appPosts).toBe(0);const before=structuredClone(h.gas.worksheets[0]);h.schema=17;const run=await runM74Journey(input('exercise'),h.deps);expect(run.status,run.stage).toBe('passed');expect(run.applicationPostRequests).toBe(11);expect(h.appPosts).toBe(11);expect(h.versions).toHaveLength(2);expect(h.reports).toHaveLength(2);expect(h.gas.worksheets[0]!.versions).toEqual(before.versions);expect(h.gas.worksheets[0]!.reports).toEqual(before.reports);expect(h.gas.worksheets[0]!.findings).not.toEqual(before.findings);const revisit=await runM74Journey(input('revisit'),h.deps);expect(revisit.status,revisit.stage).toBe('passed');expect(revisit.applicationPostRequests).toBe(0);expect(h.appPosts).toBe(11);expect(h.logoutCount).toBe(h.tokenCount);expect(h.journal).not.toContain('offline-token-');expect(h.journal).not.toContain('synthetic-offline-password');expect(h.journal).not.toContain('UNEXPECTED_PRIVATE');const completed=readM74Journal(h.journal,company).find(e=>e.kind==='exercise_complete')!;expect(Object.keys(completed.data.downloads)).toHaveLength(8);expect(Object.keys(readM74Journal(h.journal,company).find(e=>e.kind==='baseline')!.data.priorGas.downloads)).toHaveLength(4)},20000)

test('known completed writes resume after transient final read failure without repeating any POST',async()=>{const h=harness();await runM74Journey(input(),h.deps);h.schema=17;h.failFinalRead=true;const first=await runM74Journey(input('exercise'),h.deps);expect(first.status).toBe('failed');expect(first.applicationPostRequests).toBe(11);expect(first.allCreatedAuthSessionsClosed).toBe(true);const posts=h.appPosts,resumed=await runM74Journey(input('exercise'),h.deps);expect(resumed.status,resumed.stage).toBe('passed');expect(resumed.applicationPostRequests).toBe(0);expect(h.appPosts).toBe(posts);expect(h.logoutCount).toBe(h.tokenCount)},20000)

for(const fault of ['network','private','unexpected_status'] as const)test(`uncertain or malformed ${fault} POST outcome never leaks raw content and blocks retry before network`,async()=>{const h=harness();await runM74Journey(input(),h.deps);h.schema=17;h.postFault=fault;const run=await runM74Journey(input('exercise'),h.deps);expect(run.status).toBe('failed');expect(run.applicationPostRequests).toBe(1);expect(run.allCreatedAuthSessionsClosed).toBe(true);expect(h.journal).not.toContain('UNEXPECTED_PRIVATE');const n=h.calls.length,retry=await runM74Journey(input('exercise'),h.deps);expect(retry.stage).toBe('resume_preconditions');expect(h.calls).toHaveLength(n);expect(retry.applicationPostRequests).toBe(0)})

test('successful application write followed by failed durable outcome append is uncertain and not retryable',async()=>{const h=harness();await runM74Journey(input(),h.deps);h.schema=17;h.outcomeAppendFailure=true;const run=await runM74Journey(input('exercise'),h.deps);expect(run.status).toBe('failed');expect(h.corporate.versions).toHaveLength(2);expect(h.appPosts).toBe(1);expect(readM74Journal(h.journal,company).some(e=>e.kind==='post_intent')).toBe(true);const calls=h.calls.length;expect((await runM74Journey(input('exercise'),h.deps)).stage).toBe('resume_preconditions');expect(h.calls).toHaveLength(calls)})

test('prior gas version or exact-download mutation refuses baseline with zero application writes',async()=>{for(const kind of ['version','download']){const h=harness();if(kind==='version')h.tamperGas=true;else h.tamperDownload=true;const result=await runM74Journey(input(),h.deps);expect(result.status).toBe('failed');expect(h.appPosts).toBe(0);expect(result.allCreatedAuthSessionsClosed).toBe(true);expect(h.logoutCount).toBe(h.tokenCount)}})

test('unknown sign-in and interrupted-attempt journals fail closed without exposing error content',async()=>{const h=harness();h.authFault=true;const unknown=await runM74Journey(input(),h.deps);expect(unknown.status).toBe('failed');expect(unknown.allCreatedAuthSessionsClosed).toBe(false);expect(h.journal).not.toContain('UNEXPECTED_PRIVATE');const n=h.calls.length;await runM74Journey(input('exercise'),h.deps);expect(h.calls).toHaveLength(n);const interrupted=harness();await runM74Journey(input(),interrupted.deps);interrupted.journal=interrupted.journal!.trimEnd().split('\n').slice(0,-1).join('\n')+'\n';const count=interrupted.calls.length;expect((await runM74Journey(input('exercise'),interrupted.deps)).stage).toBe('resume_preconditions');expect(interrupted.calls).toHaveLength(count)})

test('legacy adapter cannot introduce application writes and route guard rejects unrelated tenants/actions',async()=>{const h=harness();h.legacyFault=true;expect((await runM74Journey(input(),h.deps)).status).toBe('failed');expect(h.appPosts).toBe(0);for(const [u,m] of [[HOST+'/workspace-api/workspace/'+id(99)+'/mobile-diesel','GET'],[root+'/mobile-diesel','DELETE'],[root+'/stationary-natural-gas','POST'],[AUTH+'/auth/v1/token?grant_type=refresh_token','POST'],[HOST+'/ready?profile=other','GET'],[HOST+'/ready#override','GET']])expect(()=>validateM74JourneyRoute(u!,m!,company)).toThrow()})
