import {expect,test} from 'bun:test'
import {decodeMobileRegister,mobileRegisterRequest} from '../../apps/site-web/src/lib/m74-api'
import {M74_PROFILE,M74_LIMITATIONS} from '../../packages/neuvetra-database/src/m74-contract'
const id=(n:number)=>`74000000-0000-4000-8000-${String(n).padStart(12,'0')}`
function empty(){return {profile:M74_PROFILE,companyId:id(1),coverageHeadVersionId:id(2),worksheets:[],sources:[{binding:{coverageVersionId:id(2),coverageVersionSha256:'a'.repeat(64),entityId:id(3),facilityId:id(4),sourceId:id(5),boundaryDecisionId:id(6)},companyLabel:'Synthetic company',entityLabel:'Synthetic entity',facilityLabel:'Synthetic base',sourceLabel:'Synthetic vehicle',eligible:true,findings:[]}],coverageFindings:[],limitations:[...M74_LIMITATIONS],synthetic:true,scope1Completeness:'incomplete',corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none'}}
test('valid empty source register decodes and strict top-level extra fields are refused',async()=>{const good=empty();expect(await decodeMobileRegister(good,id(1))).toEqual(good);await expect(decodeMobileRegister({...good,complete:true},id(1))).rejects.toThrow()})
for(const key of ['entityId','facilityId','boundaryDecisionId'] as const)test(`eligible source binding rejects malformed ${key}`,async()=>{const value=empty();value.sources[0]!.binding[key]='malformed';await expect(decodeMobileRegister(value,id(1))).rejects.toThrow()})
test('duplicate source choices must not enter the UI',async()=>{const duplicate=empty();duplicate.sources.push(structuredClone(duplicate.sources[0]!));await expect(decodeMobileRegister(duplicate,id(1))).rejects.toThrow()})
for(const key of ['coverageFindings','sourceFindings'])test(`malformed ${key} must not enter the UI`,async()=>{const value:any=empty();if(key==='coverageFindings')value.coverageFindings=[{code:'missing',recordId:null,message:{untrusted:'object'}}];else value.sources[0].findings=[{code:[],message:'malformed'}];await expect(decodeMobileRegister(value,id(1))).rejects.toThrow()})
test('transport abort discards late headers/body without revoking a replacement actor',async()=>{const original=globalThis.fetch;try{for(const stage of ['headers','body']){let resolve!:(v:any)=>void;const pending=new Promise<any>(r=>{resolve=r}),control=new AbortController();let unauthorized=0;globalThis.fetch=(async()=>stage==='headers'?pending:{ok:true,status:200,text:()=>pending}) as typeof fetch;const result=mobileRegisterRequest({userId:id(7),role:'owner',accessToken:'synthetic',signal:control.signal,onUnauthorized:()=>{unauthorized++}},id(1)).then(()=>false,()=>true);await Promise.resolve();control.abort();resolve(stage==='headers'?new Response('',{status:403}):JSON.stringify(empty()));expect(await result).toBe(true);expect(unauthorized).toBe(0)}}finally{globalThis.fetch=original}})
test('actual adapter refuses duplicate JSON keys and wrong-tenant responses',async()=>{const original=globalThis.fetch;try{for(const text of [JSON.stringify({...empty(),companyId:id(8)}),JSON.stringify(empty()).replace('"profile":','"companyId":"'+id(8)+'","profile":')]){globalThis.fetch=(async()=>new Response(text)) as typeof fetch;await expect(mobileRegisterRequest({userId:id(7),role:'owner',accessToken:'synthetic'},id(1))).rejects.toThrow()}}finally{globalThis.fetch=original}})
