import {expect,test} from 'bun:test'
import {createPostgresConnection,HostedWorkspaceDatabase,provisionStagingRoster,createM71Seed,M71_ARTIFACT,M71_EVIDENCE_SHA256,M74_PROFILE,M74_PERIOD,M74_LIMITATIONS,m74SourceChoices,m74CanonicalJson,m74Export,m74Hash,m74CalculationHashPayload,m74ContentPayload,m74VersionHashPayload,readMobileDiesel,type WorkspaceConnection,type M74SaveInput,type M74Version} from '../../packages/neuvetra-database/src/index'
import {createM74Authority} from '../../apps/site-api/src/calculation/m74-authority'
import {createM74Routes} from '../../apps/site-api/src/workspace/m74-routes'
import {decodeMobileVersion,decodeMobileRegister,decodeMobileReport} from '../../apps/site-web/src/lib/m74-api'
import expectations from './m74-independent-accounting-expectations.json'
const templateDatabase=process.env.M74_ACCOUNTING_TEMPLATE_DATABASE??'m74_author_backend_20260915c'
if(templateDatabase!==templateDatabase.trim()||!/^m74_author_[a-z0-9_]{1,52}$/.test(templateDatabase))throw new Error('M74_ACCOUNTING_TEMPLATE_DATABASE must be a lowercase m74_author_ database identifier of at most 63 characters')
const pins={'packages/neuvetra-database/src/migrations/0017_mobile_diesel.sql':'4486f83e2f2f6e5cb8db5991575a74f540b891eefd1ff65317801545c5b6c071','apps/site-api/src/calculation/m74_mobile_diesel.py':'1dc0bb7249d91e854004a8cadd34068be3fc03ecdd6e10b4cf297d375d7f52a6','packages/neuvetra-database/src/m74.ts':'494eb69227a8d18ac5068fcc5225daab1edbc88979fa3694f3f89981898bced9','packages/neuvetra-database/src/m74-contract.ts':'96d2469c1b79d0f26e1908e5971fdf602c3b9881828d53e2752d7220a3d19207'}
const digest=(text:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(text).digest('hex')
const components=(c:any)=>({co2MassKg:c.gasResults.co2.mass,ch4MassKg:c.gasResults.ch4.mass,n2oMassKg:c.gasResults.n2o.mass,ch4Co2eKg:c.gasResults.ch4.co2e,n2oCo2eKg:c.gasResults.n2o.co2e,totalExactKgCo2e:c.total.unrounded,totalDisplayKgCo2e:c.total.display})
test('M74 independent frozen oracle through Python, native SQL, API and frontend lifecycle',async()=>{
 for(const [file,pin]of Object.entries(pins))expect(digest(await Bun.file(file).bytes())).toBe(pin)
 expect(digest(await Bun.file('evaluations/research-qa/m74-independent-accounting-expectations.json').bytes())).toBe('1068fba315aa68d517bb29532a23d9c9e3ab1ddd47f8ee075aa609a23d42724b')
 const dbName='m74_qa_accounting_'+crypto.randomUUID().replaceAll('-',''),admin=createPostgresConnection('postgres://m63_test_admin@127.0.0.1:55463/postgres',{tls:false,maxConnections:1});expect((await admin.query('select 1 from pg_database where datname=$1',[dbName])).rows).toHaveLength(0);await admin.exec(`create database ${dbName} template ${templateDatabase}`);await admin.close()
 const operator=createPostgresConnection(`postgres://m63_test_admin@127.0.0.1:55463/${dbName}`,{tls:false,maxConnections:1}),runtime=createPostgresConnection(`postgres://neuvetra_runtime@127.0.0.1:55463/${dbName}`,{tls:false,maxConnections:4}),db=new(HostedWorkspaceDatabase as unknown as new(c:WorkspaceConnection,r:string)=>HostedWorkspaceDatabase)(runtime,'abcdefghijklmnopqrst'),authority=createM74Authority(),company=crypto.randomUUID(),users={owner:crypto.randomUUID(),reviewer:crypto.randomUUID(),member:crypto.randomUUID()},origin='http://127.0.0.1:37475',evidence:any={database:dbName,sourceDatabase:templateDatabase,candidatePins:pins,vectors:[],nullCases:[],negativeCases:[],singleFieldSuccessors:[],reports:[]}
 const routes=createM74Routes({database:db,authority,origin,validateUser:async token=>users[token as keyof typeof users]?{id:users[token as keyof typeof users],email:null,phone:null,fullName:null}:null}),send=async(path='',body?:unknown,actor='owner')=>routes(new Request(origin+`/workspace/${company}/mobile-diesel`+path,{method:body===undefined?'GET':'POST',headers:{origin,authorization:'Bearer '+actor,...(body===undefined?{}:{'content-type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)})),post=async(path:string,body:unknown,actor='owner')=>{const r=await send(path,body,actor),text=await r.text();expect(r.status,text).toBe(201);return JSON.parse(text)}
 try{
  expect((await operator.query<{sha256:string}>("select sha256 from neuvetra.schema_migrations where name='0017_mobile_diesel.sql'")).rows[0]!.sha256).toBe(pins['packages/neuvetra-database/src/migrations/0017_mobile_diesel.sql'])
  for(const id of Object.values(users))await operator.query('insert into auth.users(id) values($1)',[id]);await provisionStagingRoster(operator,{expectedProjectRef:'abcdefghijklmnopqrst',workspaceId:company,ownerUserId:users.owner,members:[{userId:users.reviewer,role:'admin'},{userId:users.member,role:'member'}]})
  const snapshot=createM71Seed(),sourceIds=[crypto.randomUUID(),crypto.randomUUID()];snapshot.companyLabel='Independent synthetic accounting vehicle fixture';snapshot.boundaryDecisions[0]!.reason='Fictional full-year operational control';snapshot.boundaryDecisions[0]!.evidenceRefs=[{artifactId:M71_ARTIFACT.id,expectedSha256:M71_EVIDENCE_SHA256,locator:M71_ARTIFACT.locator,purpose:'Fictional accounting review control basis'}]
  for(const sourceId of sourceIds){snapshot.sources.push({id:sourceId,entityId:snapshot.entities[0]!.id,facilityId:snapshot.facilities[0]!.id,name:'Independent mobile vehicle source '+sourceId,domain:'mobile_combustion',...M74_PERIOD,evidenceRefs:[]});snapshot.coverageItems.push({id:crypto.randomUUID(),sourceId,entityId:snapshot.entities[0]!.id,domain:'mobile_combustion',...M74_PERIOD,disposition:'missing',activityDataState:'missing',evidenceState:'missing',methodReadiness:'candidate',reason:null,evidenceRefs:[],estimateBasis:null,quantity:null,unit:null})}
  const coverage=await db.saveCorporateInventory(users.owner,company,null,{snapshot,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()}),binding=m74SourceChoices(coverage).find(c=>c.binding.sourceId===sourceIds[0])!.binding
  const base:M74SaveInput={profile:M74_PROFILE,binding,period:M74_PERIOD,vehicle:{assetId:'QA-INDEPENDENT-001',vehicleClass:'Medium- and Heavy-Duty Vehicles',classificationBasis:'Fictional manufacturer registration documents this exact medium/heavy-duty diesel class.',modelYear:2011,fuel:'Fossil Diesel',controlBasis:'owned_operational_control_full_year'},quantityGallons:'17.333',distanceMiles:'881.777',fuelStatement:{issuer:'Independent fictional fuel keeper',reference:'QA-FUEL-ORIGINAL',statedQuantityGallons:'17.333',description:'Fictional consumed fossil diesel assigned only to this vehicle, no stock changes, transfers or auxiliary engines.',consumptionBasis:'dedicated_vehicle_consumed_no_adjustments'},mileageStatement:{issuer:'Independent fictional odometer keeper',reference:'QA-MILES-ORIGINAL',statedDistanceMiles:'881.777',description:'Fictional actual vehicle-miles including California, Nevada and all other in-boundary trips.',distanceBasis:'dedicated_vehicle_annual_distance'},fuelManualConfirmation:true,mileageManualConfirmation:true,fuelDiscrepancyReason:null,mileageDiscrepancyReason:null,zeroReason:null,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()}
  let current=await decodeMobileVersion(await post('',base),company),first=current;const worksheet=current.worksheetId,versionPath=`/${worksheet}/versions`,firstExport=await(await send(`${versionPath}/${first.id}/calculation-export`)).text();expect(components(first.calculation)).toEqual(expectations.numericFixtures.find(f=>f.id==='independent_irregular')!.expected)
  const report=async(v:M74Version)=>decodeMobileReport(await post(`/${worksheet}/reports`,{versionId:v.id,expectedVersionSha256:v.versionSha256,expectedDecisionId:v.review?.id??null,expectedDecisionSha256:v.review?.decisionSha256??null,idempotencyKey:crypto.randomUUID()}),company,v)
  const originalReport=await report(first);for(const needle of ['10.21 kg CO2 per U.S. gallon','0.0095 g CH4 per vehicle-mile','0.0431 g N2O per vehicle-mile','IPCC AR5 100-year; CH4 28, N2O 265','Published displayed decimals','C107:E107','C255:G256','E523:E526','half-even','including interstate','unresolved_for_factor_release','development_candidate_not_released'])expect(originalReport.html).toContain(needle)
  expect(originalReport.html).not.toContain('10.210000000000001');expect(first.mileageStatement!.text).toContain('all_trip_locations_including_interstate');expect(first.fuelStatement!.id).not.toBe(first.mileageStatement!.id)
  const decision=await post(`/${worksheet}/reviews`,{versionId:first.id,expectedVersionSha256:first.versionSha256,decision:'accepted_bounded_internal',note:'Independent bounded accounting test, not external assurance.',acknowledgedLimitations:[...M74_LIMITATIONS],idempotencyKey:crypto.randomUUID()},'reviewer');first={...first,review:decision};current=first;await report(first)
  const successor=(patch:Partial<M74SaveInput>,reason:string)=>({...base,...patch,expectedVersionId:current.id,expectedVersionSha256:current.versionSha256,correctionReason:reason,idempotencyKey:crypto.randomUUID()})
  for(const fixture of expectations.numericFixtures){const body=successor({quantityGallons:fixture.quantityGallons,distanceMiles:fixture.distanceMiles,fuelStatement:{...base.fuelStatement!,statedQuantityGallons:fixture.quantityGallons},mileageStatement:{...base.mileageStatement!,statedDistanceMiles:fixture.distanceMiles},zeroReason:fixture.id==='both_zero'?'Fictional vehicle not operated; both records support zero.':null},'Independent vector '+fixture.id);current=await decodeMobileVersion(await post(versionPath,body),company,current);expect(current.review).toBeNull();expect(components(current.calculation)).toEqual(fixture.expected)
   const direct=await authority.calculate(current.calculation!.input);expect(components(direct)).toEqual(fixture.expected);const sql=(await operator.query<{result:any}>('select neuvetra.m74_calculation($1::text::jsonb,$2,$3) result',[JSON.stringify(current.activity),current.fuelStatement!.sha256,current.mileageStatement!.sha256])).rows[0]!.result;expect(components(sql)).toEqual(fixture.expected);expect(sql).toEqual(direct);const native=(await operator.query<any>('select quantity_gallons::text gallons,distance_miles::text miles from neuvetra.mobile_diesel_versions where id=$1',[current.id])).rows[0]!;expect(native).toEqual({gallons:fixture.quantityGallons,miles:fixture.distanceMiles});evidence.vectors.push({id:fixture.id,versionId:current.id,calculationSha256:current.calculation!.resultSha256})
  }
  const nullCases:[string,Partial<M74SaveInput>][]=[['fuel_missing',{quantityGallons:null}],['distance_missing',{distanceMiles:null}],['both_missing',{quantityGallons:null,distanceMiles:null}],['fuel_zero_distance_positive',{quantityGallons:'0.000',fuelStatement:{...base.fuelStatement!,statedQuantityGallons:'0.000'}}],['distance_zero_fuel_positive',{distanceMiles:'0.000',mileageStatement:{...base.mileageStatement!,statedDistanceMiles:'0.000'}}],['zero_contradicted_by_positive_statements',{quantityGallons:'0.000',distanceMiles:'0.000',zeroReason:'Reason cannot override positive evidence.',fuelDiscrepancyReason:'Contradiction',mileageDiscrepancyReason:'Contradiction'}],['fuel_statement_missing',{fuelStatement:null}],['mileage_confirmation_absent',{mileageManualConfirmation:false}],['fuel_difference_reason_absent',{quantityGallons:'17.334'}],['mileage_difference_reason_absent',{distanceMiles:'881.778'}]]
  for(const [id,patch]of nullCases){current=await decodeMobileVersion(await post(versionPath,successor(patch,'Independent incomplete '+id)),company,current);expect(current.calculation).toBeNull();const sql=(await operator.query<{result:any}>('select neuvetra.m74_calculation($1::text::jsonb,$2,$3) result',[JSON.stringify(current.activity),current.fuelStatement?.sha256??null,current.mileageStatement?.sha256??null])).rows[0]!.result;expect(sql).toBeNull();const r=await report(current);expect(r.html).toContain('no emissions total was calculated');expect(r.html).not.toContain('<table>');expect(JSON.parse(r.snapshotJson).version.calculation).toBeNull();expect((await send(`/${worksheet}/reviews`,{versionId:current.id,expectedVersionSha256:current.versionSha256,decision:'accepted_bounded_internal',note:'Incomplete cannot be accepted',acknowledgedLimitations:[...M74_LIMITATIONS],idempotencyKey:crypto.randomUUID()},'reviewer')).status).toBe(422);evidence.nullCases.push({id,versionId:current.id,reportSha256:r.htmlSha256})}
  for(const patch of [{vehicle:{...base.vehicle,modelYear:2006}},{vehicle:{...base.vehicle,modelYear:2023}},{vehicle:{...base.vehicle,vehicleClass:'Passenger Cars'}},{vehicle:{...base.vehicle,fuel:'B20'}},{vehicle:{...base.vehicle,fuel:'Renewable Diesel'}},{vehicle:{...base.vehicle,classificationBasis:''}},{quantityUnit:'imperial_gallon'},{distanceUnit:'kilometre'},{quantityGallons:17.333},{quantityGallons:'1e3'},{distanceMiles:'1.0001'},{period:{start:'2025-02-01',endExclusive:'2026-01-01'}}]){const r=await send(versionPath,successor(patch as any,'Unsupported input challenge'));expect(r.status).toBe(422);evidence.negativeCases.push({patch,status:r.status})}
  current=await decodeMobileVersion(await post(versionPath,successor({quantityGallons:'17.334',distanceMiles:'881.778',fuelDiscrepancyReason:'Fuel discrepancy remains.',mileageDiscrepancyReason:'Mileage discrepancy remains.'},'Restore positive with both discrepancies')),company,current);expect(current.findings.filter(f=>f.code.includes('discrepancy'))).toHaveLength(2);const discrepancyDecision=await post(`/${worksheet}/reviews`,{versionId:current.id,expectedVersionSha256:current.versionSha256,decision:'accepted_bounded_internal',note:'Bounded acceptance retains both discrepancies.',acknowledgedLimitations:[...M74_LIMITATIONS],idempotencyKey:crypto.randomUUID()},'reviewer');current={...current,review:discrepancyDecision};const discrepancyReport=await report(current);expect(discrepancyReport.html).toContain('Fuel discrepancy remains.');expect(discrepancyReport.html).toContain('Mileage discrepancy remains.');expect(JSON.parse(discrepancyReport.snapshotJson).version.findings.filter((f:any)=>f.code.includes('discrepancy'))).toHaveLength(2)
  for(const [id,patch]of [['fuel_note_only',{fuelDiscrepancyReason:'Amended independent fuel explanation.'}],['mileage_note_only',{mileageDiscrepancyReason:'Amended independent mileage explanation.'}],['classification_basis_only',{vehicle:{...current.activity.vehicle,classificationBasis:'A corrected fictional manufacturer class basis.'}}],['fuel_description_only',{fuelStatement:{...current.activity.fuelStatement!,description:'Corrected retained synthetic fuel description.'}}],['mileage_reference_only',{mileageStatement:{...current.activity.mileageStatement!,reference:'QA-MILES-NEW-REF'}}]] as [string,Partial<M74SaveInput>][]){const before=current,body={...current.activity,...patch,expectedVersionId:current.id,expectedVersionSha256:current.versionSha256,correctionReason:id,idempotencyKey:crypto.randomUUID()};current=await decodeMobileVersion(await post(versionPath,body),company,before);expect(current.calculation!.total).toEqual(before.calculation!.total);expect(current.review).toBeNull();expect(current.version).toBe(before.version+1);evidence.singleFieldSuccessors.push(id)}
  const secondBinding=m74SourceChoices(coverage).find(c=>c.binding.sourceId===sourceIds[1])!.binding;expect((await send('',{...base,binding:secondBinding,idempotencyKey:crypto.randomUUID()})).status).toBe(409);expect((await send('',{...base,binding:secondBinding,vehicle:{...base.vehicle,assetId:'QA-OTHER-VEHICLE'},fuelStatement:{...base.fuelStatement!,reference:'QA-DIFFERENT-FUEL'},idempotencyKey:crypto.randomUUID()})).status).toBe(409)
  // Coordinated arithmetic forgery rewrites outer hashes and audit, but trusted replay must refuse it.
  const forged=structuredClone(current);forged.calculation!.gasResults.ch4.mass='1';forged.calculation!.resultSha256=m74Hash(m74CalculationHashPayload(forged.calculation!));forged.contentSha256=m74Hash(m74ContentPayload(forged));forged.versionSha256=m74Hash(m74VersionHashPayload(forged));let refused=false
  try{await operator.transaction(async tx=>{await tx.exec("set local session_replication_role='replica'");await tx.query('update neuvetra.mobile_diesel_versions set payload=$2::text::jsonb,content_sha256=$3,version_sha256=$4,export_text=$5 where id=$1',[forged.id,JSON.stringify(forged),forged.contentSha256,forged.versionSha256,m74Export(forged)]);await tx.query("update neuvetra.mobile_diesel_audit set record_sha256=$2 where kind='save' and record_id=$1",[forged.id,forged.versionSha256]);await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[users.owner]);try{await readMobileDiesel(tx,company,authority)}catch{refused=true}throw Error('independent-forgery-rollback')})}catch(error){expect((error as Error).message).toBe('independent-forgery-rollback')}expect(refused).toBe(true);evidence.coordinatedArithmeticForgeryRefused=true
  const register=await decodeMobileRegister(await(await send()).json(),company);expect(register.worksheets).toHaveLength(1);expect(await(await send(`${versionPath}/${first.id}/calculation-export`)).text()).toBe(firstExport);expect(await(await send(`/${worksheet}/reports/${originalReport.id}/download`)).text()).toBe(originalReport.html);for(const s of [first.fuelStatement!,first.mileageStatement!])expect(await(await send(`/${worksheet}/statements/${s.id}/download`)).text()).toBe(s.text)
  evidence.status='passed';evidence.companyId=company;evidence.versionCount=current.version;evidence.originalExportSha256=digest(firstExport);evidence.originalReportSha256=originalReport.htmlSha256;evidence.finalRegisterSha256=digest(m74CanonicalJson(register));evidence.expectationSha256='1068fba315aa68d517bb29532a23d9c9e3ab1ddd47f8ee075aa609a23d42724b';evidence.reports=[originalReport];await Bun.write(`evaluations/research-qa/m74-independent-accounting-native-${dbName}.json`,JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({status:evidence.status,database:dbName,vectors:evidence.vectors.length,nullCases:evidence.nullCases.length,negativeCases:evidence.negativeCases.length,singleFieldSuccessors:evidence.singleFieldSuccessors.length,versions:evidence.versionCount}))
 }catch(error){evidence.status='failed';evidence.error={name:(error as Error).name,message:(error as Error).message};await Bun.write(`evaluations/research-qa/m74-independent-accounting-native-${dbName}.json`,JSON.stringify(evidence,null,2)+'\n');throw error}finally{await runtime.close();await operator.close()}
},120000)

test('M74 independent authority enforces supported inputs and rejects recomputed method forgeries',async()=>{
 const authority=createM74Authority({python:'python'}),input:any={binding:{coverageVersionId:'74000000-0000-4000-8000-000000000001',coverageVersionSha256:'a'.repeat(64),entityId:'74000000-0000-4000-8000-000000000002',facilityId:'74000000-0000-4000-8000-000000000003',sourceId:'74000000-0000-4000-8000-000000000004',boundaryDecisionId:'74000000-0000-4000-8000-000000000005'},period:{start:'2025-01-01',endExclusive:'2026-01-01'},vehicle:{assetId:'QA-DIRECT',vehicleClass:'Medium- and Heavy-Duty Vehicles',classificationBasis:'Independent fictional classification basis',modelYear:2007,fuel:'Fossil Diesel',controlBasis:'owned_operational_control_full_year'},quantityGallons:'2.125',quantityUnit:'US_gallon',distanceMiles:'12.800',distanceUnit:'vehicle_mile',fuelStatementSha256:'b'.repeat(64),mileageStatementSha256:'c'.repeat(64)}
 const record=await authority.calculate(input);expect(components(record)).toEqual(expectations.numericFixtures.find(f=>f.id==='new_tie_even_down')!.expected);expect(record.method.sourceSha256).toBe(expectations.source.sha256);expect(record.method.engineSha256).toBe(pins['apps/site-api/src/calculation/m74_mobile_diesel.py']);expect(record.method.factorSha256).toBe(digest(m74CanonicalJson({co2KgPerGallon:'10.21',ch4GramsPerMile:'0.0095',n2oGramsPerMile:'0.0431'})));expect(record.method.gwpSha256).toBe(digest(m74CanonicalJson({assessment:'IPCC AR5',horizonYears:'100',co2:'1',ch4:'28',n2o:'265'})));expect(record.method.releaseEligible).toBe(false)
 for(const patch of [{quantityUnit:'imperial_gallon'},{distanceUnit:'kilometre'},{quantityGallons:null},{distanceMiles:null},{quantityGallons:'1000000000000.000'},{distanceMiles:'-1.000'},{quantityGallons:2.125},{distanceMiles:'1.0000'},{vehicle:{...input.vehicle,modelYear:2006}},{vehicle:{...input.vehicle,modelYear:2023}},{vehicle:{...input.vehicle,vehicleClass:'Light-Duty Trucks'}},{vehicle:{...input.vehicle,fuel:'B20'}}])await expect(authority.calculate({...input,...patch})).rejects.toThrow('unavailable')
 for(const method of [{...record.method,co2KgPerGallon:'10.210000000000001'},{...record.method,ch4Gwp:'29.8'},{...record.method,releaseEligible:true}]){const forged={...record,method};forged.resultSha256=m74Hash(m74CalculationHashPayload(forged as any));await expect(authority.replayBatch([forged as any])).rejects.toThrow('unavailable')}
 await expect(authority.calculate({...input,vehicle:{...input.vehicle,modelYear:2022}})).resolves.toMatchObject({total:{display:'21.8458'}})
},20000)
