/** Native SQL adversarial probes; every function attempt is rolled back.
 * Uses author fixture only for setup, independent mutations/expectations. */
import {createPostgresConnection,HostedWorkspaceDatabase} from '../../packages/neuvetra-database/src/hosted'
import {populateM75RecoveryFixture} from '../../tools/staging/m75-backend-fixture'
import {createM74Authority} from '../../apps/site-api/src/calculation/m74-authority'
import {m75CanonicalJson,m75ContentPayload,m75InputPayload,m75VersionHashPayload,m75StatementText,m75ReportHashPayload,m75ReviewHashPayload,deriveM75RosterFindings} from '../../packages/neuvetra-database/src/m75-validation'
import {qaHash} from './m75-independent-scenarios'
import {m75RenderReport} from '../../packages/neuvetra-database/src/m75-report'
import {readMigrationManifest} from '../../packages/neuvetra-database/src/staging-migrations'
import {M75_LIMITATIONS} from '../../packages/neuvetra-database/src/m75-contract'
import type {WorkspaceSql} from '../../packages/neuvetra-database/src/workspace'
const template=process.env.M75_QA_TEMPLATE??'m74_ops_restore17_1789509920941'
if(template!=='m63_integration'&&!/^m7[45]_(ops|qa|author)_[a-z0-9_]+$/.test(template))throw Error('Only isolated synthetic template names are permitted')
const name='m75_qa_sql_'+Date.now(),connect=(db:string,user='m63_test_admin')=>createPostgresConnection(`postgres://${user}@127.0.0.1:55463/${db}`,{tls:false,maxConnections:1}),hash=(v:unknown)=>qaHash(m75CanonicalJson(v)),admin=connect('postgres'),sqlPath='packages/neuvetra-database/src/migrations/0018_controlled_fleet.sql',rawSql=await Bun.file(sqlPath).text(),sql=rawSql.replace(/\r\n/g,'\n'),sqlSha256=qaHash(sql)
const outcomes:{id:string;expectedAccepted:boolean;accepted:boolean;error:string|null;pass:boolean}[]=[];let op:ReturnType<typeof connect>|undefined
try{
 await admin.exec(`create database ${name} template ${template}`);op=connect(name)
 const manifest=await readMigrationManifest(),receipts=(await op.query<{name:string;sha256:string}>('select name,sha256 from neuvetra.schema_migrations order by name')).rows
 if(!receipts.every((r,i)=>r.name===manifest[i]?.name&&r.sha256===manifest[i]?.sha256)||manifest.at(-1)?.sha256!==sqlSha256)throw Error('Exact migration receipt/candidate mismatch')
 await op.transaction(async tx=>{for(const m of manifest.slice(receipts.length)){await tx.exec(m.sql);await tx.query('insert into neuvetra.schema_migrations(name,sha256) values($1,$2)',[m.name,m.sha256])}})
 const seed=await populateM75RecoveryFixture(op,name,55463),read=connect(name,'neuvetra_runtime'),ref=(await op.query<{project_ref:string}>('select project_ref from neuvetra.staging_target')).rows[0]!.project_ref,db=new(HostedWorkspaceDatabase as any)(read,ref) as HostedWorkspaceDatabase,authority=createM74Authority()
 const register=(await db.findControlledFleet(seed.users.owner,seed.companyId,authority))!,report=(await db.findControlledFleetReport(seed.users.owner,seed.companyId,seed.rosterId,seed.reportId,authority))!;await read.close()
 const before=(await op.query<{n:number}>('select count(*)::integer n from neuvetra.controlled_fleet_versions')).rows[0]!.n
 async function probe(id:string,expectedAccepted:boolean,query:string,params:unknown[],setup?:(tx:WorkspaceSql)=>Promise<void>,actor=seed.users.owner){const connection=connect(name,'neuvetra_runtime'),rollback=Symbol('independent rollback');let accepted=false,error:string|null=null;try{await connection.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[seed.users.owner]);if(setup)await setup(tx);await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[actor]);await tx.query(query,params);accepted=true;throw rollback})}catch(e){if(e!==rollback)error=(e as Error).message}finally{await connection.close()}outcomes.push({id,expectedAccepted,accepted,error,pass:accepted===expectedAccepted});console.log(JSON.stringify(outcomes.at(-1)))}
 function save(mutate:(activity:any,version:any)=>void=()=>{}){const prior=register.versions.at(-1)!,v=structuredClone(prior);v.id=crypto.randomUUID();v.version++;v.previousVersionId=prior.id;v.previousVersionSha256=prior.versionSha256;v.createdAt=new Date().toISOString();v.correctionReason='Independent SQL correction';v.activity.rosterStatement!.reference+='-SQL';mutate(v.activity,v);const statementId=crypto.randomUUID(),text=m75StatementText(v.activity,register.proof.coverageVersion!);v.statement={id:statementId,profile:'m75-synthetic-roster-statement-v1',input:v.activity.rosterStatement!,locator:`m75-roster-statement:${statementId}:declared-fleet`,text,sha256:qaHash(text),byteLength:Buffer.byteLength(text)};if(!Object.hasOwn(v,'qaKeepFindings'))v.findings=deriveM75RosterFindings(v.activity,register.proof.coverageVersion!);delete (v as any).qaKeepFindings;v.inputSha256=hash(m75InputPayload(v));v.contentSha256=hash(m75ContentPayload(v));v.versionSha256=hash(m75VersionHashPayload(v));const request={...v.activity,expectedDependencySha256:v.dependencies.dependencySha256,expectedVersionId:prior.id,expectedVersionSha256:prior.versionSha256,correctionReason:v.correctionReason,idempotencyKey:crypto.randomUUID()};return [seed.companyId,seed.rosterId,JSON.stringify(request),JSON.stringify(v),JSON.stringify(v.statement)]}
 const saveSql='select neuvetra.save_controlled_fleet($1,$2,$3::text::jsonb,$4::text::jsonb,$5::text::jsonb)'
 await probe('save_valid_control',true,saveSql,save())
 for(const id of ['unsupported_hidden','wrong_blocker','roster_null_confirmation','flags_null','missing_prior_row','duplicate_alias_hidden','capacity_26','string_model_year','lowercase_asset','numeric_asset','unknown_mode_enum','empty_discovery','extra_roster_key','string_all_trips','string_synthetic_flag','null_created_by','null_payload_company','null_payload_roster','null_payload_version'] as const){await probe(id,false,saveSql,save((a:any,v:any)=>{
  if(id==='unsupported_hidden'){a.rosterStatement.assets[0].modelYear=2024;v.findings=[];v.qaKeepFindings=true}
  if(id==='wrong_blocker'){a.rosterStatement.assets[0].modelYear=2024;v.findings=[{code:'roster_unconfirmed',rowKey:null,message:'Invented different finding',blocking:true}];v.qaKeepFindings=true}
  if(id==='roster_null_confirmation')a.manualConfirmation=null
  if(id==='flags_null')v.synthetic=null
  if(id==='string_synthetic_flag')v.synthetic='true'
  if(id==='null_created_by')v.createdBy=null
  if(id==='null_payload_company')v.companyId=null
  if(id==='null_payload_roster')v.rosterId=null
  if(id==='null_payload_version')v.version=null
  if(id==='string_model_year')a.rosterStatement.assets[0].modelYear='2018'
  if(id==='lowercase_asset')a.rosterStatement.assets[0].assetId='recovery-truck-a'
  if(id==='numeric_asset')a.rosterStatement.assets[0].assetId=123
  if(id==='unknown_mode_enum')a.rosterStatement.assets[0].mode='arbitrary_mode'
  if(id==='empty_discovery')a.rosterStatement.discoveryBasis=''
  if(id==='extra_roster_key')a.rosterStatement.hidden=true
  if(id==='string_all_trips')a.rosterStatement.allTripLocationsIncluded='true'
  if(id==='missing_prior_row'){a.rosterStatement.assets=[];a.links=[]}
  if(id==='duplicate_alias_hidden'){const a2=structuredClone(a.rosterStatement.assets[0]);a2.rowId=crypto.randomUUID();a2.assetId='SQL-SECOND';a2.aliases=[a.rosterStatement.assets[0].assetId];a.rosterStatement.assets.push(a2);a.links.push({rowId:a2.rowId,sourceId:a.links[0].sourceId});v.findings=[];v.qaKeepFindings=true}
  if(id==='capacity_26'){const first=a.rosterStatement.assets[0];a.rosterStatement.assets=Array.from({length:26},(_,i)=>({...structuredClone(first),rowId:i===0?first.rowId:crypto.randomUUID(),assetId:'CAP-'+i}));a.links=a.rosterStatement.assets.map((x:any)=>({rowId:x.rowId,sourceId:a.links[0].sourceId}))}
 }))}
 for(const id of ['review_valid_control','review_empty_ack','review_null_note','review_null_decision','review_wrong_dependency','review_contributor'] as const){const saveParams=save(),v=JSON.parse(saveParams[3] as string),actor=id==='review_contributor'?seed.users.owner:seed.users.fleetReviewer,r:any={id:crypto.randomUUID(),versionId:v.id,versionSha256:v.versionSha256,dependencies:v.dependencies,decision:'accepted_bounded_reconciliation',note:'Independent direct review',acknowledgedLimitations:[...M75_LIMITATIONS],reviewerId:actor,reviewedAt:new Date().toISOString(),decisionSha256:''};if(id==='review_empty_ack')r.acknowledgedLimitations=[];if(id==='review_null_note')r.note=null;if(id==='review_null_decision')r.decision=null;if(id==='review_wrong_dependency')r.dependencies={...r.dependencies,dependencySha256:'0'.repeat(64)};r.decisionSha256=hash(m75ReviewHashPayload(seed.companyId,r));const request={versionId:r.versionId,expectedVersionSha256:r.versionSha256,expectedDependencySha256:r.dependencies.dependencySha256,decision:r.decision,note:r.note,acknowledgedLimitations:r.acknowledgedLimitations,idempotencyKey:crypto.randomUUID()};await probe(id,id==='review_valid_control','select neuvetra.review_controlled_fleet($1,$2,$3::text::jsonb,$4::text::jsonb)',[seed.companyId,seed.rosterId,JSON.stringify(request),JSON.stringify(r)],async tx=>{await tx.query(saveSql,saveParams)},actor)}
 const reportSql='select neuvetra.create_controlled_fleet_report($1,$2,$3::text::jsonb,$4::text::jsonb)'
 for(const id of ['report_valid_control','report_arbitrary_html','report_wrong_rows','report_null_status','report_wrong_asset_same_key','report_wrong_findings','report_string_boolean','report_wrong_entity_label','report_null_rows'] as const){const r=structuredClone(report);r.id=crypto.randomUUID();r.createdAt=new Date().toISOString();const snapshot=JSON.parse(r.snapshotJson);if(id==='report_wrong_rows'){snapshot.reconciliation.rows=[];snapshot.reconciliation.counts.reconciledRows=99}if(id==='report_null_status')snapshot.reconciliation.status=null;if(id==='report_wrong_asset_same_key')snapshot.reconciliation.rows[0].assetId='UNRELATED-VEHICLE';if(id==='report_wrong_findings'){snapshot.reconciliation.findings.push({code:'invented',rowKey:null,message:'Invented evidence narrative',blocking:false})}if(id==='report_string_boolean')snapshot.reconciliation.synthetic='true';if(id==='report_wrong_entity_label')snapshot.reconciliation.rows[0].entityLabel='Unrelated entity';if(id==='report_null_rows')snapshot.reconciliation.rows=null;const {contentSha256:_,...body}=snapshot.reconciliation;snapshot.reconciliation.contentSha256=hash(body);r.snapshotJson=m75CanonicalJson(snapshot);r.snapshotSha256=qaHash(r.snapshotJson);if(id==='report_arbitrary_html')r.html='<html><body>All vehicles supported; no findings.</body></html>';else if(id!=='report_null_rows')r.html=m75RenderReport(snapshot);r.htmlSha256=qaHash(r.html);r.htmlByteLength=Buffer.byteLength(r.html);r.reportSha256=hash(m75ReportHashPayload(r));await probe(id,id==='report_valid_control',reportSql,[seed.companyId,seed.rosterId,JSON.stringify({expectedReconciliationSha256:snapshot.reconciliation.contentSha256,idempotencyKey:crypto.randomUUID()}),JSON.stringify(r)])}
 const after=(await op.query<{n:number}>('select count(*)::integer n from neuvetra.controlled_fleet_versions')).rows[0]!.n
 const result={status:outcomes.every(x=>x.pass)&&before===after?'pass':'fail',database:name,sqlSha256,rawSqlSha256:qaHash(rawSql),sqlUnchanged:sqlSha256===qaHash((await Bun.file(sqlPath).text()).replace(/\r\n/g,'\n')),beforeVersionCount:before,afterVersionCount:after,seed,outcomes,createdAt:new Date().toISOString(),scriptSha256:qaHash(await Bun.file(import.meta.path).text())};await Bun.write('evaluations/research-qa/m75-independent-direct-sql-result.json',JSON.stringify(result,null,2)+'\n');if(result.status!=='pass')process.exitCode=1
}finally{await op?.close();await admin.close()}
