/** Independent expectations prepared before M75 reconciliation implementation.
 * These are synthetic structural fixtures, not persisted/readback integrity evidence.
 * The adapter test must run these against delivered code; creating this file proves no case passed.
 */
import {createM71Seed,M71_ARTIFACT,M71_LIMITATIONS} from '../../packages/neuvetra-database/src/m71-contract'
import {M71_EVIDENCE_SHA256} from '../../packages/neuvetra-database/src/m71-validation'
import {M74_METHOD,M74_PROFILE,M74_PERIOD,M74_LIMITATIONS} from '../../packages/neuvetra-database/src/m74-contract'
import {M75_PROFILE,M75_LIMITATIONS} from '../../packages/neuvetra-database/src/m75-contract'

export const qaId=(n:number)=>`75000000-0000-4000-8000-${String(n).padStart(12,'0')}`
export const qaHash=(s:string)=>new Bun.CryptoHasher('sha256').update(s).digest('hex')
export const qaTime='2026-09-16T00:00:00.000Z'
export interface IndependentGraph {companyId:string;coverage:any;mobile:any;version:any;reviews:any[]}
export type Mutation=(graph:IndependentGraph)=>void
export interface IndependentCase {id:string;requirement:string;mutate:Mutation;expectedStatus:'blocked'|'reconciled_bounded_synthetic';row?:number;expectedRowStatus?:string;minimumRows?:number;refreshDependencies?:boolean}

export function independentGraph():IndependentGraph {
 const companyId=qaId(1),snapshot=createM71Seed(),author=qaId(2),reviewer=qaId(3)
 const evidence={artifactId:M71_ARTIFACT.id,expectedSha256:M71_EVIDENCE_SHA256,locator:M71_ARTIFACT.locator,purpose:'Independent fictional control evidence'}
 for(const b of snapshot.boundaryDecisions){b.disposition='included_activity';b.reason='Full-year fictional operational control';b.evidenceRefs=[evidence]}
 for(const r of snapshot.relationships){r.controlFacts='Full-year fictional operational control';r.evidenceRefs=[evidence]}
 snapshot.companyLabel='Independent synthetic fleet, not author happy-path fixture'
 for(let i=0;i<2;i++){
  snapshot.sources.push({id:qaId(100+i),entityId:snapshot.entities[0]!.id,facilityId:snapshot.facilities[0]!.id,name:'Independent source '+i,domain:'mobile_combustion',...M74_PERIOD,evidenceRefs:[]})
  snapshot.coverageItems.push({id:qaId(120+i),sourceId:qaId(100+i),entityId:snapshot.entities[0]!.id,domain:'mobile_combustion',...M74_PERIOD,disposition:'included_activity',activityDataState:'missing',evidenceState:'missing',methodReadiness:'candidate',reason:'Included declared source; exact activity and evidence are separately linked through M74.',evidenceRefs:[],estimateBasis:null,quantity:null,unit:null})
 }
 const cv:any={id:qaId(20),companyId,inventoryId:qaId(21),version:1,previousVersionId:null,previousVersionSha256:null,createdBy:author,createdAt:qaTime,contributorIds:[author],correctionReason:null,snapshot,contentSha256:qaHash('coverage-content'),versionSha256:qaHash('coverage-version'),findings:[],synthetic:true,corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none',emissionsTotals:null,review:null}
 cv.review={id:qaId(22),versionId:cv.id,versionSha256:cv.versionSha256,decision:'accepted_bounded_internal',note:'Bounded synthetic coverage review',acknowledgedLimitations:[...M71_LIMITATIONS],reviewerId:reviewer,reviewedAt:qaTime,decisionSha256:qaHash('coverage-review')}
 const coverage:any={profile:snapshot.profile,companyId,inventoryId:cv.inventoryId,headVersionId:cv.id,versions:[cv],limitations:[...M71_LIMITATIONS]}
 const assets=[0,1].map(i=>({rowId:qaId(200+i),assetId:`QA-FLEET-${i}`,aliases:[],entityId:snapshot.entities[0]!.id,facilityId:snapshot.facilities[0]!.id,period:{...M74_PERIOD},mode:'on_road',vehicleClass:'Medium- and Heavy-Duty Vehicles',modelYear:2010+i,fuel:'Fossil Diesel',controlBasis:'owned_operational_control_full_year',classificationBasis:'Independent fictional manufacturer class record',controlExplanation:'Independent fictional ownership and full-year control record'}))
 const rosterStatement={issuer:'Independent fictional fleet keeper',reference:'INDEPENDENT-FLEET-2025',description:'Separate roster established before selecting workpapers.',discoveryBasis:'Independent fictional asset and insurance records across both corporate entities; no vehicle omitted for lacking a worksheet.',coveredEntityIds:snapshot.entities.map(e=>e.id),completeness:'declared_complete',allTripLocationsIncluded:true,assets}
 const activity:any={profile:M75_PROFILE,coverageVersionId:cv.id,coverageVersionSha256:cv.versionSha256,period:{...M74_PERIOD},rosterStatement,manualConfirmation:true,links:assets.map((a,i)=>({rowId:a.rowId,sourceId:qaId(100+i)}))}
 const worksheets=assets.map((a,i)=>{
  const binding={coverageVersionId:cv.id,coverageVersionSha256:cv.versionSha256,entityId:a.entityId,facilityId:a.facilityId,sourceId:qaId(100+i),boundaryDecisionId:snapshot.boundaryDecisions[0]!.id}
  const input:any={profile:M74_PROFILE,binding,period:{...M74_PERIOD},vehicle:{assetId:a.assetId,vehicleClass:a.vehicleClass,classificationBasis:a.classificationBasis,modelYear:a.modelYear,fuel:a.fuel,controlBasis:a.controlBasis},quantityGallons:'1.000',distanceMiles:'1.000',fuelStatement:{issuer:'Independent fictional fuel record',reference:`F-${i}`,statedQuantityGallons:'1.000',description:'Consumed fossil diesel, no stock or auxiliary adjustments.',consumptionBasis:'dedicated_vehicle_consumed_no_adjustments'},mileageStatement:{issuer:'Independent fictional distance record',reference:`M-${i}`,statedDistanceMiles:'1.000',description:'All controlled trips including interstate movement.',distanceBasis:'dedicated_vehicle_annual_distance'},fuelManualConfirmation:true,mileageManualConfirmation:true,fuelDiscrepancyReason:null,mileageDiscrepancyReason:null,zeroReason:null}
  const v:any={id:qaId(300+i),companyId,worksheetId:qaId(320+i),version:1,previousVersionId:null,previousVersionSha256:null,createdBy:author,createdAt:qaTime,contributorIds:[author],correctionReason:null,activity:input,activityStatus:{fuel:'entered',mileage:'entered'},coverageVersion:cv,fuelStatement:{id:qaId(340+i),profile:'m74-synthetic-fuel-statement-v1',input:input.fuelStatement,locator:`independent-fuel-${i}`,text:'structural fixture',sha256:qaHash(`fuel-${i}`),byteLength:18},mileageStatement:{id:qaId(360+i),profile:'m74-synthetic-mileage-statement-v1',input:input.mileageStatement,locator:`independent-miles-${i}`,text:'structural fixture',sha256:qaHash(`miles-${i}`),byteLength:18},calculation:{method:M74_METHOD,total:{unrounded:'10.2216875',display:'10.2217',unit:'kg CO2e',rounding:'half_even_4dp'}},findings:[{code:'scope1_incomplete',message:'Scope1 incomplete.'},{code:'method_not_released',message:'Candidate only.'}],inputSha256:qaHash(`input-${i}`),contentSha256:qaHash(`content-${i}`),versionSha256:qaHash(`version-${i}`),synthetic:true,scope1Completeness:'incomplete',corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none',review:null}
  v.review={id:qaId(380+i),versionId:v.id,versionSha256:v.versionSha256,decision:'accepted_bounded_internal',note:'Separate bounded review',acknowledgedLimitations:[...M74_LIMITATIONS],reviewerId:reviewer,reviewedAt:qaTime,decisionSha256:qaHash(`review-${i}`)}
  return {profile:M74_PROFILE,companyId,worksheetId:v.worksheetId,sourceId:binding.sourceId,vehicleAssetId:a.assetId,headVersionId:v.id,versions:[v],reports:[],findings:[],limitations:[...M74_LIMITATIONS],synthetic:true,scope1Completeness:'incomplete',corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none'}
 })
 const mobile:any={profile:M74_PROFILE,companyId,coverageHeadVersionId:cv.id,worksheets,sources:[],coverageFindings:[],limitations:[...M74_LIMITATIONS],synthetic:true,scope1Completeness:'incomplete',corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none'}
 const version:any={id:qaId(400),companyId,rosterId:qaId(401),version:1,previousVersionId:null,previousVersionSha256:null,createdBy:author,createdAt:qaTime,contributorIds:[author],correctionReason:null,activity,dependencies:null,statement:{id:qaId(402),profile:'m75-synthetic-roster-statement-v1',input:rosterStatement,locator:`m75-roster-statement:${qaId(402)}:declared-fleet`,text:'structural fixture',sha256:qaHash('roster-statement'),byteLength:18},findings:[],inputSha256:qaHash('roster-input'),contentSha256:qaHash('roster-content'),versionSha256:qaHash('roster-version'),synthetic:true,scope1Completeness:'incomplete',corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none',emissionsTotals:null}
 const reviews:any[]=[{id:qaId(403),versionId:version.id,versionSha256:version.versionSha256,dependencies:null,decision:'accepted_bounded_reconciliation',note:'Independent bounded roster review',acknowledgedLimitations:[...M75_LIMITATIONS],reviewerId:reviewer,reviewedAt:qaTime,decisionSha256:qaHash('roster-review')}]
 return {companyId,coverage,mobile,version,reviews}
}

const asset=(g:IndependentGraph,i=0)=>g.version.activity.rosterStatement.assets[i]
const head=(g:IndependentGraph,i=0)=>g.mobile.worksheets[i].versions.find((v:any)=>v.id===g.mobile.worksheets[i].headVersionId)
export const classificationCases:IndependentCase[]=[
 {id:'positive',requirement:'A01',mutate:()=>{},expectedStatus:'reconciled_bounded_synthetic',minimumRows:2},
 ...(['assetId','entityId','facilityId','period','vehicleClass','modelYear','fuel','classificationBasis','controlExplanation'] as const).map(field=>({id:`unknown_${field}`,requirement:'A13/A15',mutate:(g:IndependentGraph)=>{asset(g)[field]=null},expectedStatus:'blocked' as const,row:0,expectedRowStatus:'unknown'})),
 ...Object.entries({mode:'unknown',controlBasis:'unknown'}).map(([field,value])=>({id:`unknown_${field}`,requirement:'A15',mutate:(g:IndependentGraph)=>{asset(g)[field]=value},expectedStatus:'blocked' as const,row:0,expectedRowStatus:'unknown'})),
 ...Object.entries({mode:'off_road',vehicleClass:'Light-Duty Trucks',modelYear:2024,fuel:'B20',controlBasis:'other_control_arrangement',period:{start:'2025-02-01',endExclusive:'2026-01-01'}}).map(([field,value])=>({id:`unsupported_${field}`,requirement:'A25/A26',mutate:(g:IndependentGraph)=>{asset(g)[field]=value},expectedStatus:'blocked' as const,row:0,expectedRowStatus:'unsupported'})),
 {id:'alias_primary_collision',requirement:'A09',mutate:g=>{asset(g,0).aliases=[asset(g,1).assetId]},expectedStatus:'blocked',row:0,expectedRowStatus:'duplicate'},
 {id:'alias_alias_collision',requirement:'A09',mutate:g=>{asset(g,0).aliases=['SHARED-ALIAS'];asset(g,1).aliases=['SHARED-ALIAS']},expectedStatus:'blocked',row:0,expectedRowStatus:'duplicate'},
 {id:'same_asset_different_rows',requirement:'A09',mutate:g=>{asset(g,1).assetId=asset(g,0).assetId},expectedStatus:'blocked',row:1,expectedRowStatus:'duplicate'},
 {id:'same_source_different_assets',requirement:'A10',mutate:g=>{g.version.activity.links[1].sourceId=g.version.activity.links[0].sourceId},expectedStatus:'blocked',row:1,expectedRowStatus:'duplicate'},
 {id:'same_labels_distinct_assets',requirement:'A12',mutate:g=>{g.coverage.versions[0].snapshot.sources.filter((s:any)=>s.domain==='mobile_combustion').forEach((s:any)=>{s.name='Same visible source label'})},expectedStatus:'reconciled_bounded_synthetic'},
 {id:'missing_second_workpaper',requirement:'A02',mutate:g=>{g.mobile.worksheets.pop()},expectedStatus:'blocked',row:1,expectedRowStatus:'missing_workpaper',refreshDependencies:true,minimumRows:2},
 {id:'unrostered_mobile_source',requirement:'A04',mutate:g=>{const s=structuredClone(g.coverage.versions[0].snapshot.sources.find((s:any)=>s.domain==='mobile_combustion'));s.id=qaId(999);s.name='Unrostered mobile source';g.coverage.versions[0].snapshot.sources.push(s)},expectedStatus:'blocked',minimumRows:3,refreshDependencies:true},
 {id:'roster_omits_workpaper_and_source',requirement:'A05',mutate:g=>{g.version.activity.rosterStatement.assets.pop();g.version.activity.links.pop()},expectedStatus:'blocked',minimumRows:2},
 {id:'no_roster_statement',requirement:'A07',mutate:g=>{g.version.activity.rosterStatement=null;g.version.activity.links=[];g.version.statement=null},expectedStatus:'blocked',minimumRows:2},
 {id:'empty_roster',requirement:'A08',mutate:g=>{g.version.activity.rosterStatement.assets=[];g.version.activity.links=[]},expectedStatus:'blocked',minimumRows:2},
 {id:'omitted_entity',requirement:'A07',mutate:g=>{g.version.activity.rosterStatement.coveredEntityIds.pop()},expectedStatus:'blocked'},
 {id:'unconfirmed_roster',requirement:'A07',mutate:g=>{g.version.activity.manualConfirmation=false},expectedStatus:'blocked'},
 {id:'partial_declaration',requirement:'A07',mutate:g=>{g.version.activity.rosterStatement.completeness='partial'},expectedStatus:'blocked'},
 {id:'interstate_activity_omitted',requirement:'A28',mutate:g=>{g.version.activity.rosterStatement.allTripLocationsIncluded=false},expectedStatus:'blocked'},
 {id:'accepted_discrepancy',requirement:'A18',mutate:g=>{const v=head(g);v.activity.quantityGallons='1.001';v.activity.fuelDiscrepancyReason='Explained but unresolved';v.activityStatus.fuel='discrepancy';v.findings.push({code:'fuel_activity_statement_discrepancy',message:'Unresolved fuel discrepancy'})},expectedStatus:'blocked',row:0,expectedRowStatus:'workpaper_incomplete'},
 {id:'current_head_unreviewed',requirement:'A21',mutate:g=>{head(g).review=null},expectedStatus:'blocked',row:0,expectedRowStatus:'workpaper_incomplete',refreshDependencies:true},
 {id:'current_head_changes_requested',requirement:'A21',mutate:g=>{head(g).review.decision='changes_requested'},expectedStatus:'blocked',row:0,expectedRowStatus:'workpaper_incomplete',refreshDependencies:true},
 {id:'roster_unreviewed',requirement:'A24',mutate:g=>{g.reviews=[]},expectedStatus:'blocked'},
 {id:'boundary_unreviewed',requirement:'A24',mutate:g=>{g.coverage.versions[0].review=null},expectedStatus:'blocked',refreshDependencies:true},
 {id:'stale_workpaper_coverage_hash',requirement:'A23',mutate:g=>{head(g).activity.binding.coverageVersionSha256=qaHash('old-coverage')},expectedStatus:'blocked',row:0,expectedRowStatus:'stale'},
 {id:'stale_workpaper_coverage_id',requirement:'A23',mutate:g=>{head(g).activity.binding.coverageVersionId=qaId(989)},expectedStatus:'blocked',row:0,expectedRowStatus:'stale'},
 {id:'stale_roster_coverage_hash',requirement:'A23',mutate:g=>{g.version.activity.coverageVersionSha256=qaHash('old-coverage')},expectedStatus:'blocked'},
 ...(['unassessed','missing','excluded','not_applicable','included_estimate'] as const).map(disposition=>({id:`source_screening_${disposition}`,requirement:'A27',mutate:(g:IndependentGraph)=>{const c=g.coverage.versions[0].snapshot.coverageItems.find((x:any)=>x.sourceId===qaId(100));c.disposition=disposition;c.reason='Fictional assertion awaiting applicable reconciliation decision';c.evidenceRefs=[{artifactId:M71_ARTIFACT.id,expectedSha256:M71_EVIDENCE_SHA256,locator:M71_ARTIFACT.locator,purpose:'Fictional screening assertion'}];if(disposition==='included_estimate')c.estimateBasis={methodVersionId:'fictional-unreleased-estimate',assumptions:'Fictional unapproved estimate',inputEvidenceRefs:c.evidenceRefs,uncertainty:'Unknown uncertainty'}},expectedStatus:'blocked' as const,row:0,expectedRowStatus:'workpaper_incomplete'})),
 {id:'new_review_invalidates_captured_dependencies',requirement:'A24',mutate:g=>{head(g).review.id=qaId(990);head(g).review.decisionSha256=qaHash('new-decision')},expectedStatus:'blocked'},
 {id:'fuel_missing',requirement:'A16',mutate:g=>{const v=head(g);v.activity.quantityGallons=null;v.activityStatus.fuel='missing';v.calculation=null},expectedStatus:'blocked',row:0,expectedRowStatus:'workpaper_incomplete'},
 {id:'mileage_evidence_missing',requirement:'A17',mutate:g=>{const v=head(g);v.activity.mileageStatement=null;v.mileageStatement=null;v.activityStatus.mileage='evidence_missing';v.calculation=null},expectedStatus:'blocked',row:0,expectedRowStatus:'workpaper_incomplete'},
 {id:'mixed_zero',requirement:'A20',mutate:g=>{const v=head(g);v.activity.quantityGallons='0.000';v.activityStatus.fuel='explicit_zero';v.calculation=null;v.findings.push({code:'mixed_zero_contradiction',message:'Mixed zero.'})},expectedStatus:'blocked',row:0,expectedRowStatus:'workpaper_incomplete'},
]
