import {test,expect} from 'bun:test'
import {createPostgresConnection,HostedWorkspaceDatabase} from '../../packages/neuvetra-database/src/hosted'
import {createM74Authority} from '../../apps/site-api/src/calculation/m74-authority'
import {decodeFleetRegister} from '../../apps/site-web/src/lib/m75-api'
import {M75_LIMITATIONS} from '../../packages/neuvetra-database/src/m75-contract'
import {M71_LIMITATIONS} from '../../packages/neuvetra-database/src/m71-contract'
import {qaId,qaHash} from './m75-independent-scenarios'
import {readMigrationManifest,provisionStagingRoster} from '../../packages/neuvetra-database/src/staging-migrations'
import {populateM75RecoveryFixture} from '../../tools/staging/m75-backend-fixture'
import {createM75Routes} from '../../apps/site-api/src/workspace/m75-routes'
const source=process.env.M75_QA_TEMPLATE??'m74_ops_restore17_1789509920941'
if(source!=='m63_integration'&&!/^m7[45]_(ops|qa|author)_[a-z0-9_]+$/.test(source))throw Error('Only an explicit isolated synthetic template is permitted')
const connect=(database:string,user='m63_test_admin')=>createPostgresConnection(`postgres://${user}@127.0.0.1:55463/${database}`,{tls:false,maxConnections:4})
async function mustReject(work:Promise<unknown>,message?:string){let error:unknown;try{await work}catch(e){error=e}expect(error instanceof Error).toBe(true);if(message)expect((error as Error).message).toContain(message)}
test.skipIf(process.env.M75_INDEPENDENT_NATIVE!=='enabled')('M75 independent native lifecycle, access and stale historical evidence',async()=>{
 const name=`m75_qa_review_${Date.now()}`,admin=connect('postgres'),authority=createM74Authority();let op:ReturnType<typeof connect>|undefined,runtime:ReturnType<typeof connect>|undefined
 const events:string[]=[]
 try{
  console.log('Native QA connecting for new isolated clone '+name)
  expect((await admin.query('select datname from pg_database where datname=$1',[name])).rows.length).toBe(0)
  console.log('Native QA creating clone');await admin.exec(`create database ${name} template ${source}`);op=connect(name)
  const manifest=await readMigrationManifest(),receipts=(await op.query<{name:string;sha256:string}>('select name,sha256 from neuvetra.schema_migrations order by name')).rows
  expect(receipts.every((r,i)=>r.name===manifest[i]?.name&&r.sha256===manifest[i]?.sha256)).toBe(true)
  await op.transaction(async tx=>{for(const m of manifest.slice(receipts.length)){await tx.exec(m.sql);await tx.query('insert into neuvetra.schema_migrations(name,sha256) values($1,$2)',[m.name,m.sha256])}})
  const seeded=await populateM75RecoveryFixture(op,name,55463),company=seeded.companyId,owner=seeded.users.owner,fleetReviewer=seeded.users.fleetReviewer
  runtime=connect(name,'neuvetra_runtime');console.log('Native QA clone ready')
  const ref=(await op.query<{project_ref:string}>('select project_ref from neuvetra.staging_target')).rows[0]!.project_ref
  const db=new(HostedWorkspaceDatabase as any)(runtime,ref) as HostedWorkspaceDatabase
  const original=(await db.findControlledFleet(owner,company,authority))!;expect(original.reconciliation.status).toBe('reconciled_bounded_synthetic');await decodeFleetRegister(original,company);events.push('native positive register and real browser decoder')
  const reportMeta=original.reports[0]!,report=(await db.findControlledFleetReport(owner,company,original.rosterId!,reportMeta.id,authority))!,proof=(await db.findControlledFleetReportProof(owner,company,original.rosterId!,reportMeta.id,authority))!
  expect(proof.reportId).toBe(report.id);expect(proof.proof.coverageVersion?.id).toBe(original.proof.coverageVersion?.id)
  await Bun.write('evaluations/research-qa/m75-independent-ui-fixture.json',JSON.stringify({register:original,report,proof,owner,fleetReviewer},null,2)+'\n')
  await mustReject(db.findControlledFleet(qaId(900),company,authority),'Private staging access required.');await mustReject(db.findControlledFleetReport(qaId(900),company,original.rosterId!,reportMeta.id,authority),'Private staging access required.');events.push('foreign unprovisioned actor denied register/report')
  await mustReject(runtime.query('update neuvetra.controlled_fleet_versions set content_sha256=$1 where company_id=$2',['0'.repeat(64),company]));events.push('runtime direct DML refused')
  const v=original.versions.at(-1)!,base={...structuredClone(v.activity),expectedDependencySha256:original.reconciliation.dependencySha256,expectedVersionId:v.id,expectedVersionSha256:v.versionSha256,correctionReason:'Independent correction',idempotencyKey:crypto.randomUUID()}
  const foreign=crypto.randomUUID();await op.query('insert into auth.users(id) values($1)',[foreign]);await provisionStagingRoster(op,{expectedProjectRef:ref,workspaceId:crypto.randomUUID(),ownerUserId:foreign,members:[]})
  expect(await db.findControlledFleet(foreign,company,authority)).toBeNull();expect(await db.findControlledFleetReport(foreign,company,original.rosterId!,report.id,authority)).toBeNull()
  const member=crypto.randomUUID();await op.query('insert into auth.users(id) values($1)',[member]);await op.query("insert into neuvetra.company_members(company_id,user_id,role) values($1,$2,'member')",[company,member]);await op.query('insert into neuvetra.staging_access(user_id,company_id,active) values($1,$2,true)',[member,company])
  expect((await db.findControlledFleet(member,company,authority))!.headVersionId).toBe(original.headVersionId)
  const memberSave=structuredClone(base);memberSave.rosterStatement!.reference+='-MEMBER';await mustReject(db.saveControlledFleet(member,company,original.rosterId,memberSave,authority));await mustReject(db.createControlledFleetReport(member,company,original.rosterId!,{expectedReconciliationSha256:original.reconciliation.contentSha256,idempotencyKey:crypto.randomUUID()},authority))
  const origin='http://127.0.0.1:37579',actors:Record<string,string>={owner,member,foreign},route=createM75Routes({database:db,authority,origin,validateUser:async token=>actors[token]?{id:actors[token]!,email:null,phone:null,fullName:null}:null})
  const http=(suffix='',token:string|null='owner',method='GET',body?:string,requestOrigin=origin)=>route(new Request(`${origin}/workspace/${company}/controlled-fleet${suffix}`,{method,headers:{origin:requestOrigin,...(token?{authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body})}))
  expect((await http('',null)).status).toBe(401);expect((await http('','unknown')).status).toBe(401);expect((await http('','owner','GET',undefined,'https://unrelated.invalid')).status).toBe(403);expect((await http('','foreign')).status).toBe(404)
  const publicRegister=await http();expect(publicRegister.status).toBe(200);await decodeFleetRegister(await publicRegister.json(),company)
  expect((await http(`/${original.rosterId}/versions`,'member','POST',JSON.stringify(memberSave))).status).toBe(403);expect((await http(`/${original.rosterId}/versions`,'owner','POST','{"invalid":1,"invalid":2}')).status).toBe(422);expect((await http('','owner','PUT','{}')).status).toBe(405)
  const htmlResponse=await http(`/${original.rosterId}/reports/${report.id}/download`);expect(htmlResponse.status).toBe(200);expect(htmlResponse.headers.get('cache-control')).toBe('no-store');expect(htmlResponse.headers.get('x-content-type-options')).toBe('nosniff');expect(htmlResponse.headers.get('content-security-policy')).toContain('sandbox allow-modals');expect(await htmlResponse.text()).toBe(report.html)
  const publicProof=await http(`/${original.rosterId}/reports/${report.id}/proof`);expect(publicProof.status).toBe(200);expect(await publicProof.json()).toEqual(proof);events.push('Real public route with native database: authentication/origin/tenant/member/JSON/method refusals, exact downloads and historical proof with restrictive headers')
  await op.query('update neuvetra.staging_access set active=false where user_id=$1',[member]);await mustReject(db.findControlledFleet(member,company,authority),'Private staging access required.');events.push('Active other-tenant reads hidden; same-tenant member can read but cannot write/report; revoked access immediately refused')
  await mustReject(db.saveControlledFleet(owner,company,original.rosterId,base,authority));events.push('no-op correction refused')
  const changed=structuredClone(base);changed.rosterStatement!.reference+='-QA';const saved=await db.saveControlledFleet(owner,company,original.rosterId,changed,authority)
  const retry=await db.saveControlledFleet(owner,company,original.rosterId,changed,authority);expect(retry.id).toBe(saved.id);expect(retry.versionSha256).toBe(saved.versionSha256)
  const conflicting=structuredClone(changed);conflicting.rosterStatement!.reference+='-DIFFERENT';await mustReject(db.saveControlledFleet(owner,company,original.rosterId,conflicting,authority));events.push('exact retry reused one record; conflicting retry refused')
  let current=(await db.findControlledFleet(owner,company,authority))!;expect(current.versions.length).toBe(original.versions.length+1);expect(current.reconciliation.status).toBe('blocked');expect(current.reconciliation.findings.some(x=>x.code==='roster_review_required')).toBe(true)
  const review={versionId:saved.id,expectedVersionSha256:saved.versionSha256,expectedDependencySha256:current.reconciliation.dependencySha256,decision:'accepted_bounded_reconciliation' as const,note:'Independent bounded synthetic QA review.',acknowledgedLimitations:[...M75_LIMITATIONS],idempotencyKey:crypto.randomUUID()}
  await mustReject(db.reviewControlledFleet(owner,company,original.rosterId!,review,authority));await db.reviewControlledFleet(fleetReviewer,company,original.rosterId!,{...review,idempotencyKey:crypto.randomUUID()},authority);current=(await db.findControlledFleet(owner,company,authority))!;expect(current.reconciliation.status).toBe('reconciled_bounded_synthetic');events.push('contributor review refused, separate reviewer accepted')
  const beforeMobile=current.proof.workpaperVersions[0]!,mobileInput={...structuredClone(beforeMobile.activity),distanceMiles:'1001.000',mileageStatement:{...beforeMobile.activity.mileageStatement!,statedDistanceMiles:'1001.000'},expectedVersionId:beforeMobile.id,expectedVersionSha256:beforeMobile.versionSha256,correctionReason:'Independent mileage correction',idempotencyKey:crypto.randomUUID()}
  await db.saveMobileDiesel(owner,company,beforeMobile.worksheetId,mobileInput,authority);current=(await db.findControlledFleet(owner,company,authority))!;expect(current.reconciliation.status).toBe('blocked');expect(current.reconciliation.findings.some(x=>x.code==='dependency_stale')).toBe(true)
  const historical=await db.findControlledFleetReport(owner,company,original.rosterId!,report.id,authority),historicalProof=await db.findControlledFleetReportProof(owner,company,original.rosterId!,report.id,authority)
  expect(historical).toEqual(report);expect(historicalProof).toEqual(proof);events.push('M74 successor blocks current reconciliation while report bytes and historical proof remain exact')
  const correction=()=>{const h=current.versions.at(-1)!;return {...structuredClone(h.activity),expectedDependencySha256:current.reconciliation.dependencySha256,expectedVersionId:h.id,expectedVersionSha256:h.versionSha256,correctionReason:'Independent concurrent correction',idempotencyKey:crypto.randomUUID()}}
  const raceA=correction(),raceB=correction();raceA.rosterStatement!.reference+='-RACE-A';raceB.rosterStatement!.reference+='-RACE-B'
  const race=await Promise.allSettled([db.saveControlledFleet(owner,company,current.rosterId,raceA,authority),db.saveControlledFleet(owner,company,current.rosterId,raceB,authority)])
  expect(race.filter(x=>x.status==='fulfilled').length).toBe(1);expect(race.filter(x=>x.status==='rejected').length).toBe(1)
  const count=current.versions.length;current=(await db.findControlledFleet(owner,company,authority))!;expect(current.versions.length).toBe(count+1);expect(current.reconciliation.status).toBe('blocked');events.push('Concurrent different corrections create exactly one successor and retain current blockers')
  const same=correction();same.rosterStatement!.reference+='-SAME';const concurrentRetry=await Promise.all([db.saveControlledFleet(owner,company,current.rosterId,same,authority),db.saveControlledFleet(owner,company,current.rosterId,same,authority)]);expect(concurrentRetry[0].id).toBe(concurrentRetry[1].id);const sameCount=current.versions.length;current=(await db.findControlledFleet(owner,company,authority))!;expect(current.versions.length).toBe(sameCount+1);events.push('Concurrent exact same-key retries yield one identical immutable successor')
  const priorCoverage=current.proof.coverageVersion!,snapshot=structuredClone(priorCoverage.snapshot);snapshot.companyLabel+=' QA successor'
  const newCoverage=await db.saveCorporateInventory(owner,company,priorCoverage.inventoryId,{snapshot,expectedVersionId:priorCoverage.id,expectedVersionSha256:priorCoverage.versionSha256,correctionReason:'Independent later corporate boundary',idempotencyKey:crypto.randomUUID()})
  current=(await db.findControlledFleet(owner,company,authority))!;const rebind=correction();rebind.coverageVersionId=newCoverage.id;rebind.coverageVersionSha256=newCoverage.versionSha256;rebind.rosterStatement!.reference+='-NEW-BOUNDARY'
  await db.saveControlledFleet(owner,company,current.rosterId,rebind,authority);current=(await db.findControlledFleet(owner,company,authority))!;const blockedReport=await db.createControlledFleetReport(owner,company,current.rosterId!,{expectedReconciliationSha256:current.reconciliation.contentSha256,idempotencyKey:crypto.randomUUID()},authority)
  const nullProof=(await db.findControlledFleetReportProof(owner,company,current.rosterId!,blockedReport.id,authority))!;expect(nullProof.proof.coverageVersion!.review).toBeNull();expect(nullProof.proof.boundCoverageVersion!.review).toBeNull()
  await db.reviewCorporateInventory(seeded.users.coverageReviewer,company,newCoverage.inventoryId,{versionId:newCoverage.id,expectedVersionSha256:newCoverage.versionSha256,decision:'accepted_bounded_internal',note:'Independent later bounded coverage review',acknowledgedLimitations:[...M71_LIMITATIONS],idempotencyKey:crypto.randomUUID()})
  expect(await db.findControlledFleetReport(owner,company,current.rosterId!,blockedReport.id,authority)).toEqual(blockedReport)
  expect(await db.findControlledFleetReportProof(owner,company,current.rosterId!,blockedReport.id,authority)).toEqual(nullProof);events.push('Later coverage review leaves captured null decision and exact historical proof unchanged')
  current=(await db.findControlledFleet(owner,company,authority))!
  while(current.versions.length<40){const input=correction();input.rosterStatement!.reference='QA-CAP-VERSION-'+current.versions.length;await db.saveControlledFleet(owner,company,current.rosterId,input,authority);current=(await db.findControlledFleet(owner,company,authority))!}
  const overflow=correction();overflow.rosterStatement!.reference='QA-CAP-OVERFLOW';await mustReject(db.saveControlledFleet(owner,company,current.rosterId,overflow,authority));expect((await db.findControlledFleet(owner,company,authority))!.versions.length).toBe(40);events.push('Forty retained versions accepted; forty-first refused without an extra record')
  while(current.reports.length<40){await db.createControlledFleetReport(owner,company,current.rosterId!,{expectedReconciliationSha256:current.reconciliation.contentSha256,idempotencyKey:crypto.randomUUID()},authority);current=(await db.findControlledFleet(owner,company,authority))!}
  await mustReject(db.createControlledFleetReport(owner,company,current.rosterId!,{expectedReconciliationSha256:current.reconciliation.contentSha256,idempotencyKey:crypto.randomUUID()},authority));expect((await db.findControlledFleet(owner,company,authority))!.reports.length).toBe(40);expect(await db.findControlledFleetReport(owner,company,current.rosterId!,report.id,authority)).toEqual(report);events.push('Forty retained reports accepted; forty-first refused and earliest bytes remain exact')
  for(const r of [original,current]){expect(r.reconciliation.emissionsTotals).toBeNull();expect(r.reconciliation.releaseEligible).toBe(false);expect(r.reconciliation.scope1Completeness).toBe('incomplete')}
  await Bun.write('evaluations/research-qa/m75-independent-native-result.json',JSON.stringify({status:'native_lifecycle_pass',database:name,source,pooledConnectionReuse:true,poolCapacity:4,migrationSha256:manifest.at(-1)?.sha256,events,reportSha256:report.reportSha256,scriptSha256:qaHash(await Bun.file(import.meta.path).text()),createdAt:new Date().toISOString(),limitations:['Direct-function forged payload and recovery18 have separate evidence.','Author fixture is setup only; mutations, expectations and assertions are independent.']},null,2)+'\n')
 }catch(e){console.error(JSON.stringify({database:name,events,error:(e as Error).message}));throw e}finally{await runtime?.close();await op?.close();await admin.close()}
},120000)
