/** Independent local restored schema19 replay. No host connection or database writes. */
import {inspectRecovered}from'../../tools/staging/m76-replay'
const dir='.tmp/m76-ops-1789569395595',output='.superpowers/m76-security-forward-recovery-candidate1.json',hash=(b:Uint8Array)=>new Bun.CryptoHasher('sha256').update(b).digest('hex'),pin=hash(await Bun.file('packages/neuvetra-database/src/migrations/0019_stationary_sources.sql').bytes())
if(await Bun.file(output).exists())throw Error('Existing independent receipt refused')
const author=await Bun.file(dir+'/author-result.json').json(),source=await Bun.file(dir+'/source19-content-manifest.json').json(),oldSource=await Bun.file(dir+'/source18-content-manifest.json').json(),restore=await Bun.file(dir+'/restore19.json').json()
if(author.migrationHash!==pin||author.forwardName!=='m76_ops_forward19_1789569395595'||restore.database!==author.forwardName||restore.schemaVersion!==19||source.sha256!==restore.recoveryManifest.sha256)throw Error('Exact final schema19 populated restore bindings required')
const replay=await inspectRecovered(author.forwardName,55463)
if(JSON.stringify(source)!==JSON.stringify(replay.recoveryManifest)||JSON.stringify(source)!==JSON.stringify(restore.recoveryManifest)||!replay.noMutationVerified||!replay.runtimeNoClaimDenied||replay.dieselVersions<2||replay.equipmentVersions<3||replay.equipmentProofReads<3||replay.stationaryFrontendDownloads<1||replay.gasVersions<1||replay.mobileVersions<1||replay.fleetVersions<1||replay.legacyDownloads<1)throw Error('Independent schema19 runtime replay failed')
const retained=new Set(source.entries.map((e:unknown)=>JSON.stringify(e)));if(!oldSource.entries.every((e:unknown)=>retained.has(JSON.stringify(e))))throw Error('Earlier source archive content missing from schema19')
await Bun.write(output,JSON.stringify({status:'m76_schema19_forward_recovery_review_passed',createdAt:new Date().toISOString(),reviewerId:'/root/m76_accounting',reviewedMigrationHash:pin,schemaVersion:19,database:author.forwardName,port:55463,populatedStationaryRecoveryVerified:true,m76CalculationReplayVerified:true,m76HistoricalProofVerified:true,m73M74M75AndLegacyPreserved:true,runtimeReplayAndDownloadsVerified:true,noMutationVerified:true,sourceContentManifest:source,restoredContentManifest:replay.recoveryManifest,restoreReceiptSha256:hash(await Bun.file(dir+'/restore19.json').bytes()),authorReceiptSha256:hash(await Bun.file(dir+'/author-result.json').bytes()),replay,reviewArrangement:'Separate reviewer execution of actual reconstructed source/workpaper/report proof using production/operator interfaces, with independent exact archived-content and earlier-entry preservation comparisons; reviewer authored no operators.',limitations:['Synthetic restored application database on local55463 only; no provider Auth/session/configuration/storage restoration.','Source19 historical-entry preservation independently compared; operator creation/archive/restore action separately authored and reviewed by root.']},null,2)+'\n')
console.log(JSON.stringify({status:'independent_schema19_forward_recovery_passed',schemaVersion:19,contentEntries:source.entries.length,dieselVersions:replay.dieselVersions,equipmentVersions:replay.equipmentVersions,proofReads:replay.equipmentProofReads,receiptSha256:hash(await Bun.file(output).bytes()),output}))
