import {test,expect} from 'bun:test'
import {createPostgresConnection,HostedWorkspaceDatabase,readMigrationManifest,provisionStagingRoster,M76_DIESEL_LIMITATIONS,M76_LIMITATIONS,m73SourceChoices} from '../../packages/neuvetra-database/src/index'
import {createM73Authority} from '../../apps/site-api/src/calculation/m73-authority'
import {createM76DieselAuthority} from '../../apps/site-api/src/calculation/m76-authority'
import {createM76Routes,createM76DieselRoutes} from '../../apps/site-api/src/workspace/m76-routes'
import {decodeStationaryRegister} from '../../apps/site-web/src/lib/m76-api'
import {decodeGeneratorRegister,decodeGeneratorReport} from '../../apps/site-web/src/lib/m76-diesel-api'
import {populateM76RecoveryFixture} from '../../tools/staging/m76-backend-fixture'
import oracle from './m76-independent-expectations.json'
const connect=(name:string,user='m63_test_admin')=>createPostgresConnection(`postgres://${user}@127.0.0.1:55463/${name}`,{tls:false,maxConnections:4})
async function refuses(work:Promise<unknown>){let e:unknown;try{await work}catch(x){e=x}expect(e instanceof Error).toBe(true);return e}
const components=(c:any)=>({heatMmbtu:c.derivedHhv.quantityMmbtu,co2MassKg:c.gasResults.co2.mass,ch4MassKg:c.gasResults.ch4.mass,n2oMassKg:c.gasResults.n2o.mass,ch4Co2eKg:c.gasResults.ch4.co2e,n2oCo2eKg:c.gasResults.n2o.co2e,totalExactKgCo2e:c.total.unrounded,totalDisplayKgCo2e:c.total.display})
test.skipIf(process.env.M76_INDEPENDENT_NATIVE!=='enabled')('M76 independent native arithmetic, lifecycle, HTTP and historical proof',async()=>{
 const source=process.env.M76_QA_TEMPLATE??'m76_author_candidate5';if(!/^m76_(qa|author|ops)_[a-z0-9_]+$/.test(source))throw Error('Explicit isolated synthetic template required')
 const name=`m76_qa_review_${Date.now()}`,admin=connect('postgres'),events:string[]=[],authority={gas:createM73Authority({python:'python'}),diesel:createM76DieselAuthority({python:'python'})};let op:ReturnType<typeof connect>|undefined,runtime:ReturnType<typeof connect>|undefined
 try{
  expect((await admin.query('select 1 from pg_database where datname=$1',[name])).rows.length).toBe(0);await admin.exec(`create database ${name} template ${source}`);op=connect(name)
  const manifest=await readMigrationManifest(),receipts=(await op.query<{name:string;sha256:string}>('select name,sha256 from neuvetra.schema_migrations order by name')).rows;expect(receipts).toEqual(manifest.map(m=>({name:m.name,sha256:m.sha256})))
  const seed=await populateM76RecoveryFixture(op,name,55463),{companyId:company,users}=seed,owner=users.owner
  runtime=connect(name,'neuvetra_runtime');const ref=(await op.query<{project_ref:string}>('select project_ref from neuvetra.staging_target')).rows[0]!.project_ref,db=new (HostedWorkspaceDatabase as any)(runtime,ref) as HostedWorkspaceDatabase
  let roster=(await db.findStationaryEquipment(owner,company,authority))!,generator=(await db.findStationaryDiesel(owner,company,authority.diesel))!,head=generator.worksheets[0]!.versions.at(-1)!
  await decodeStationaryRegister(roster,company);await decodeGeneratorRegister(generator,company);expect(roster.reconciliation.status).toBe('reconciled_bounded_synthetic');events.push('Native positive fixture read by actual stationary and generator decoders')
  const historic=await db.findStationaryEquipmentReport(owner,company,roster.rosterId!,roster.reports.at(-1)!.id,authority),proof=await db.findStationaryEquipmentReportProof(owner,company,roster.rosterId!,roster.reports.at(-1)!.id,authority)
  const origin='http://127.0.0.1:37579',foreign=crypto.randomUUID();await op.query('insert into auth.users(id)values($1)',[foreign]);await provisionStagingRoster(op,{expectedProjectRef:ref,workspaceId:crypto.randomUUID(),ownerUserId:foreign,members:[]})
  const actors:any={owner,member:users.member,foreign},deps={database:db,origin,validateUser:async(token:string)=>actors[token]?{id:actors[token],email:null,phone:null,fullName:null}:null},routes={roster:createM76Routes({...deps,authorities:authority}),diesel:createM76DieselRoutes({...deps,authority:authority.diesel})}
  const http=(family:'roster'|'diesel',suffix='',token:string|null='owner',method='GET',body?:string,requestOrigin=origin)=>routes[family](new Request(`${origin}/workspace/${company}/${family==='roster'?'stationary-equipment':'stationary-diesel'}${suffix}`,{method,headers:{origin:requestOrigin,...token?{authorization:'Bearer '+token}:{}},...body===undefined?{}:{body}}))
  for(const family of ['roster','diesel']as const){expect((await http(family,'',null)).status).toBe(401);expect((await http(family,'','foreign')).status).toBe(404);expect((await http(family,'','owner','GET',undefined,'https://wrong.invalid')).status).toBe(403);expect((await http(family,'','member')).status).toBe(200);expect((await http(family,'','member','POST','{}')).status).toBe(403);expect((await http(family,'','owner','POST','{"x":1,"x":2}')).status).toBe(422)}
  await refuses(runtime.query('update neuvetra.stationary_diesel_versions set version_sha256=$1 where company_id=$2',['0'.repeat(64),company]));events.push('Both real routes enforce authentication, tenant, origin, member read-only and duplicate JSON; runtime DML denied')
  const report=generator.worksheets[0]!.reports.at(-1)!;await decodeGeneratorReport(report,company,head)
  const html=await http('diesel',`/${head.worksheetId}/reports/${report.id}/download`);expect(html.status).toBe(200);expect(html.headers.get('content-security-policy')).toContain('sandbox');expect(html.headers.get('cache-control')).toBe('no-store');expect(await html.text()).toBe(report.html)
  await Bun.write('evaluations/research-qa/m76-independent-native-ui-fixture.json',JSON.stringify({register:roster,generatorRegister:generator,owner,equipmentReviewer:users.equipmentReviewer,generatorReviewer:users.workpaperReviewer,report:historic,proof},null,2)+'\n')
  for(const f of oracle.numericFixtures.filter(f=>f.family==='stationary_diesel')){
   const input={...structuredClone(head.activity),quantityGallons:f.quantity,statement:{...head.activity.statement!,statedQuantityGallons:f.quantity},zeroReason:f.quantity==='0.000'?'Independent documented no fuel consumption, including tests.':null,expectedVersionId:head.id,expectedVersionSha256:head.versionSha256,correctionReason:'Independent source-cell arithmetic vector '+f.quantity,idempotencyKey:crypto.randomUUID()}
   const sql=(await op.query<{c:any}>('select neuvetra.m76_diesel_calculation($1::text::jsonb,$2) c',[JSON.stringify(input),'a'.repeat(64)])).rows[0]!.c;expect(components(sql)).toEqual(f.expected)
   head=await db.saveStationaryDiesel(owner,company,head.worksheetId,input,authority.diesel);expect(components(head.calculation)).toEqual(f.expected);const reread=(await http('diesel')).clone();expect(reread.status).toBe(200);await decodeGeneratorRegister(await reread.json(),company)
  }events.push('All nine independent generator vectors matched direct native SQL and persisted Python/server/HTTP/actual decoder: zero, minimum, irregular, maximum and both new half-even ties')
  roster=(await db.findStationaryEquipment(owner,company,authority))!;expect(roster.reconciliation.status).toBe('blocked');expect(roster.reconciliation.findings.some(f=>f.code==='dependency_stale')).toBe(true);expect(await db.findStationaryEquipmentReport(owner,company,roster.rosterId!,historic!.id,authority)).toEqual(historic);expect(await db.findStationaryEquipmentReportProof(owner,company,roster.rosterId!,historic!.id,authority)).toEqual(proof)
  const correction=()=>({...structuredClone(head.activity),expectedVersionId:head.id,expectedVersionSha256:head.versionSha256,correctionReason:'Independent evidence-only correction',idempotencyKey:crypto.randomUUID()})
  await refuses(db.saveStationaryDiesel(owner,company,head.worksheetId,correction(),authority.diesel))
  for(const kind of ['statement','label']as const){const input=correction();if(kind==='statement')input.statement!.description+=' Independent retained clarification.';else input.equipment.assetId+='-CORRECTED';const prior=structuredClone(head);head=await db.saveStationaryDiesel(owner,company,head.worksheetId,input,authority.diesel);expect(head.calculation!.total).toEqual(prior.calculation!.total);const saved=(await db.findStationaryDiesel(owner,company,authority.diesel))!.worksheets[0]!.versions;expect(saved.find(v=>v.id===prior.id)).toEqual(prior)}
  const unreviewedReport=await db.createStationaryDieselReport(owner,company,head.worksheetId,{versionId:head.id,expectedVersionSha256:head.versionSha256,expectedDecisionId:null,expectedDecisionSha256:null,idempotencyKey:crypto.randomUUID()},authority.diesel)
  const review={versionId:head.id,expectedVersionSha256:head.versionSha256,decision:'accepted_bounded_internal' as const,note:'Independent supported native correction review.',acknowledgedLimitations:[...M76_DIESEL_LIMITATIONS],idempotencyKey:crypto.randomUUID()};await refuses(db.reviewStationaryDiesel(owner,company,head.worksheetId,review,authority.diesel));await db.reviewStationaryDiesel(users.workpaperReviewer,company,head.worksheetId,review,authority.diesel)
  generator=(await db.findStationaryDiesel(owner,company,authority.diesel))!;expect(generator.worksheets[0]!.reports.find(r=>r.id===unreviewedReport.id)).toEqual(unreviewedReport);await decodeGeneratorReport(unreviewedReport,company,generator.worksheets[0]!.versions.at(-1)!);events.push('No-op refused, statement-only and equipment label-only successors retained exact prior versions; null-review report stays exact after independent later review; self-review refused')
  const raceA=correction(),raceB=correction();raceA.statement!.description+=' Race A';raceB.statement!.description+=' Race B';const race=await Promise.allSettled([db.saveStationaryDiesel(owner,company,head.worksheetId,raceA,authority.diesel),db.saveStationaryDiesel(owner,company,head.worksheetId,raceB,authority.diesel)]);expect(race.filter(r=>r.status==='fulfilled').length).toBe(1);expect(race.filter(r=>r.status==='rejected').length).toBe(1);events.push('Concurrent corrections retain exactly one successor')
  await Bun.write('evaluations/research-qa/m76-independent-native-result.json',JSON.stringify({status:'passed',database:name,template:source,schema:receipts.at(-1),company,seed,events,limitations:['Synthetic isolated clone only; production author fixture used solely for setup. Native tests and assertions independently authored.','Cross-family evidence and coordinated stored-byte forgery run separately. No hosted or release acceptance.']},null,2)+'\n')
  console.log(JSON.stringify({database:name,status:'passed',events}))
 }finally{await runtime?.close();await op?.close();await admin.close()}
},180000)
