/** Independent reviewer action on an already restored local archive. Never connects to a host or mutates a database. */
import {inspectRecovered}from'../../tools/staging/m76-replay'
import {createPostgresConnection}from'../../packages/neuvetra-database/src/index'
const hash=(bytes:Uint8Array)=>new Bun.CryptoHasher('sha256').update(bytes).digest('hex')
const backupPath='.superpowers/m76-hosted-backup-candidate1.json',restorePath='.superpowers/m76-hosted-restore-candidate1.json',output='.superpowers/m76-security-hosted-recovery-candidate1.json'
const backup=await Bun.file(backupPath).json(),restore=await Bun.file(restorePath).json()
if(restore.status!=='m76_exact_application_archive_restored'||restore.database!=='m76_security_hosted_restore1'||restore.port!==55472||restore.schemaVersion!==18||backup.archiveSha256!==restore.archiveSha256||backup.dumpSha256!==restore.dumpSha256||backup.recoveryManifest.sha256!==restore.recoveryManifest.sha256)throw Error('Exact private restored archive bindings required')
if(await Bun.file(output).exists())throw Error('Existing reviewer receipt refused')
const db=createPostgresConnection(`postgres://supabase_admin@127.0.0.1:55472/${restore.database}`,{tls:false,maxConnections:1})
let counts:Record<string,number>
try{const row=(await db.query<{gas:number;mobile:number;fleet:number;legacy:number}>(`select (select count(*)::integer from neuvetra.stationary_gas_versions) gas,(select count(*)::integer from neuvetra.mobile_diesel_versions) mobile,(select count(*)::integer from neuvetra.controlled_fleet_versions) fleet,(select count(*)::integer from neuvetra.electricity_sources)+(select count(*)::integer from neuvetra.worksheet_reports)+(select count(*)::integer from neuvetra.source_worksheet_reports)+(select count(*)::integer from neuvetra.annual_electricity_reports)+(select count(*)::integer from neuvetra.annual_evidence_reports) legacy`)).rows[0]!;counts=row}finally{await db.close()}
const replay=await inspectRecovered(restore.database,55472)
if(replay.recoveryManifest.sha256!==backup.recoveryManifest.sha256||JSON.stringify(replay.recoveryManifest)!==JSON.stringify(restore.recoveryManifest)||replay.gasVersions!==counts.gas||replay.mobileVersions!==counts.mobile||replay.fleetVersions!==counts.fleet||replay.legacyDownloads!==counts.legacy||!replay.noMutationVerified||!replay.runtimeNoClaimDenied||replay.gasVersions<1||replay.mobileVersions<1||replay.fleetVersions<1||replay.legacyDownloads<1)throw Error('Independent restored content replay comparison failed')
await Bun.write(output,JSON.stringify({status:'m76_independent_recovery_passed',createdAt:new Date().toISOString(),project:restore.project,schemaVersion:18,port:55472,database:restore.database,archiveSha256:backup.archiveSha256,dumpSha256:backup.dumpSha256,restoreReceiptSha256:hash(await Bun.file(restorePath).bytes()),backupReceiptSha256:hash(await Bun.file(backupPath).bytes()),reviewerId:'/root/m76_accounting',applicationReadsAndDownloadsVerified:true,m73CalculationReplayVerified:true,m74CalculationReplayVerified:true,m75ReconciliationReplayVerified:true,legacyDownloadsVerified:true,noMutationVerified:true,independentCountComparison:counts,recoveryManifest:replay.recoveryManifest,replay,reviewArrangement:'Independent execution and receipt/content/count comparison by reviewer who authored no operators; existing production/operator replay helpers reused as exercised interfaces.',limitations:['Only restored local application archive. No hosted connection or writes.','Actual provider Auth accounts/sessions/configuration/storage and role passwords excluded.','Schema19 populated forward recovery is separate.']},null,2)+'\n')
console.log(JSON.stringify({status:'independent_local_restored18_replay_passed',schemaVersion:18,contentEntries:replay.recoveryManifest.entries.length,counts,output,receiptSha256:hash(await Bun.file(output).bytes())}))
