import {test,expect}from'bun:test'
import {createPostgresConnection,HostedWorkspaceDatabase,readMigrationManifest,m73SourceChoices,m74SourceChoices,M74_PROFILE,M74_PERIOD,M71_LIMITATIONS}from'../../packages/neuvetra-database/src/index'
import {createM73Authority}from'../../apps/site-api/src/calculation/m73-authority'
import {createM74Authority}from'../../apps/site-api/src/calculation/m74-authority'
import {createM76DieselAuthority}from'../../apps/site-api/src/calculation/m76-authority'
import {m76DieselHash,readStationaryDiesel}from'../../packages/neuvetra-database/src/m76-diesel'
import {m76DieselCalculationHashPayload,m76DieselContentPayload,m76DieselVersionHashPayload,m76DieselExport}from'../../packages/neuvetra-database/src/m76-diesel-validation'
import {decodeStationaryRegister}from'../../apps/site-web/src/lib/m76-api'
import {decodeGeneratorRegister}from'../../apps/site-web/src/lib/m76-diesel-api'
const connect=(n:string,u='m63_test_admin')=>createPostgresConnection(`postgres://${u}@127.0.0.1:55463/${n}`,{tls:false,maxConnections:4})
async function refuses(p:Promise<unknown>){let e:any;try{await p}catch(x){e=x}expect(e instanceof Error).toBe(true);return e}
test.skipIf(process.env.M76_INDEPENDENT_NATIVE!=='enabled')('M76 independent native source-only correction, cross-family fuel race and stored semantic replay',async()=>{
 const prior=await Bun.file('evaluations/research-qa/m76-independent-native-result.json').json();if(prior.status!=='passed'||!/^m76_qa_review_\d+$/.test(prior.database))throw Error('Successful independent native fixture required')
 const name=`m76_qa_security_${Date.now()}`,admin=connect('postgres'),events:string[]=[],authorities={gas:createM73Authority({python:'python'}),diesel:createM76DieselAuthority({python:'python'})},mobileAuthority=createM74Authority({python:'python'});let op:ReturnType<typeof connect>|undefined,runtime:ReturnType<typeof connect>|undefined
 try{
  expect((await admin.query('select 1 from pg_database where datname=$1',[name])).rows.length).toBe(0);await admin.exec(`create database ${name} template ${prior.database}`);op=connect(name);const manifest=await readMigrationManifest(),receipts=(await op.query<{name:string;sha256:string}>('select name,sha256 from neuvetra.schema_migrations order by name')).rows;expect(receipts).toEqual(manifest.map(m=>({name:m.name,sha256:m.sha256})))
  runtime=connect(name,'neuvetra_runtime');const ref=(await op.query<{project_ref:string}>('select project_ref from neuvetra.staging_target')).rows[0]!.project_ref,db=new(HostedWorkspaceDatabase as any)(runtime,ref)as HostedWorkspaceDatabase,{company,seed}=prior,{owner}=seed.users
  const generator=async()=>((await db.findStationaryDiesel(owner,company,authorities.diesel))!.worksheets[0]!.versions.at(-1)!)
  let head=await generator();const correction=()=>({...structuredClone(head.activity),expectedVersionId:head.id,expectedVersionSha256:head.versionSha256,correctionReason:'Independent native security correction',idempotencyKey:crypto.randomUUID()})
  const initial=structuredClone(head),coverage=(await db.findCorporateInventory(owner,company))!.versions.at(-1)!,sourceOnly=correction();sourceOnly.binding=m73SourceChoices(coverage).find(s=>s.binding.sourceId===seed.sourceIds[1])!.binding
  head=await db.saveStationaryDiesel(owner,company,head.worksheetId,sourceOnly,authorities.diesel);expect(head.calculation!.total).toEqual(initial.calculation!.total);const sameSource=(await db.findStationaryEquipment(owner,company,authorities))!;expect(sameSource.reconciliation.status).toBe('blocked');expect(sameSource.reconciliation.findings.some(f=>f.code==='duplicate_workpaper')).toBe(true);await decodeStationaryRegister(sameSource,company);await decodeGeneratorRegister(await db.findStationaryDiesel(owner,company,authorities.diesel),company)
  const restored=correction();restored.binding=initial.activity.binding;head=await db.saveStationaryDiesel(owner,company,head.worksheetId,restored,authorities.diesel);expect((await db.findStationaryDiesel(owner,company,authorities.diesel))!.worksheets[0]!.versions.find(v=>v.id===initial.id)).toEqual(initial);events.push('Source-only same-facility correction keeps exact arithmetic and old versions; gas/generator duplicate source remains readable through actual decoder and blocking')
  const snapshot=structuredClone(coverage.snapshot),mobileSource=crypto.randomUUID(),source=snapshot.sources.find(s=>s.id===seed.sourceIds[2])!,item=snapshot.coverageItems.find(i=>i.sourceId===source.id)!
  snapshot.sources.push({...source,id:mobileSource,name:'Independent synthetic road truck',domain:'mobile_combustion'});snapshot.coverageItems.push({...item,id:crypto.randomUUID(),sourceId:mobileSource,domain:'mobile_combustion'})
  const cv=await db.saveCorporateInventory(owner,company,coverage.inventoryId,{snapshot,expectedVersionId:coverage.id,expectedVersionSha256:coverage.versionSha256,correctionReason:'Independent cross-family evidence test adds one disclosed synthetic truck',idempotencyKey:crypto.randomUUID()});await db.reviewCorporateInventory(seed.users.coverageReviewer,company,cv.inventoryId,{versionId:cv.id,expectedVersionSha256:cv.versionSha256,decision:'accepted_bounded_internal',note:'Independent bounded synthetic coverage review',acknowledgedLimitations:[...M71_LIMITATIONS],idempotencyKey:crypto.randomUUID()})
  const currentCoverage=(await db.findCorporateInventory(owner,company))!.versions.at(-1)!,rebind=correction();rebind.binding=m73SourceChoices(currentCoverage).find(s=>s.binding.sourceId===seed.sourceIds[2])!.binding;head=await db.saveStationaryDiesel(owner,company,head.worksheetId,rebind,authorities.diesel)
  let mobileInput:any={profile:M74_PROFILE,binding:m74SourceChoices(currentCoverage).find(s=>s.binding.sourceId===mobileSource)!.binding,period:{...M74_PERIOD},vehicle:{assetId:'QA-TRUCK-72',vehicleClass:'Medium- and Heavy-Duty Vehicles',classificationBasis:'Independent synthetic full-year owned heavy-duty road truck record.',modelYear:2018,fuel:'Fossil Diesel',controlBasis:'owned_operational_control_full_year'},quantityGallons:'13.000',distanceMiles:'125.000',fuelStatement:{issuer:'Independent synthetic fuel meter provider',reference:'QA-MOBILE-2025-ONLY',statedQuantityGallons:'13.000',description:'Independent synthetic directly measured annual vehicle consumption.',consumptionBasis:'dedicated_vehicle_consumed_no_adjustments'},mileageStatement:{issuer:'Independent synthetic telematics',reference:'QA-TRUCK-2025-MILES',statedDistanceMiles:'125.000',description:'All synthetic travel included.',distanceBasis:'dedicated_vehicle_annual_distance'},fuelManualConfirmation:true,mileageManualConfirmation:true,fuelDiscrepancyReason:null,mileageDiscrepancyReason:null,zeroReason:null,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()}
  let mobile=await db.saveMobileDiesel(owner,company,null,mobileInput,mobileAuthority);expect(mobile.calculation).not.toBeNull();events.push('Unchanged legacy M74 valid non-collision writer still succeeds under schema19')
  const claimMobile=correction();claimMobile.statement!.issuer=mobile.activity.fuelStatement!.issuer;claimMobile.statement!.reference=mobile.activity.fuelStatement!.reference;expect((await refuses(db.saveStationaryDiesel(owner,company,head.worksheetId,claimMobile,authorities.diesel))).code).toBe('23505')
  const mobileCorrection=()=>({...structuredClone(mobile.activity),expectedVersionId:mobile.id,expectedVersionSha256:mobile.versionSha256,correctionReason:'Independent consumed evidence correction',idempotencyKey:crypto.randomUUID()})
  const claimGenerator=mobileCorrection();claimGenerator.fuelStatement!.issuer=head.activity.statement!.issuer;claimGenerator.fuelStatement!.reference=head.activity.statement!.reference;expect((await refuses(db.saveMobileDiesel(owner,company,mobile.worksheetId,claimGenerator,mobileAuthority))).code).toBe('23505');events.push('Actual generator writer rejects retained mobile fuel record, actual legacy mobile writer rejects retained generator fuel record')
  const raceMobile=mobileCorrection(),raceGenerator=correction(),issuer='Independent shared annual fuel statement',reference='QA-FUEL-RACE-2025';raceMobile.fuelStatement!.issuer=issuer;raceMobile.fuelStatement!.reference=reference;raceGenerator.statement!.issuer=issuer;raceGenerator.statement!.reference=reference
  const race=await Promise.allSettled([db.saveMobileDiesel(owner,company,mobile.worksheetId,raceMobile,mobileAuthority),db.saveStationaryDiesel(owner,company,head.worksheetId,raceGenerator,authorities.diesel)]);expect(race.filter(r=>r.status==='fulfilled').length).toBe(1);expect(race.filter(r=>r.status==='rejected').length).toBe(1);expect((race.find(r=>r.status==='rejected')as PromiseRejectedResult).reason.code).toBe('23505');events.push('Concurrent old mobile/new generator same annual fuel evidence creates exactly one successful successor')
  head=await generator();const sameKey=correction();sameKey.statement!.reference=sameKey.statement!.meterLabel;head=await db.saveStationaryDiesel(owner,company,head.worksheetId,sameKey,authorities.diesel);const evidenceKey=m76DieselHash([head.activity.statement!.issuer.toLowerCase(),head.activity.statement!.reference.toLowerCase(),'2025']);expect((await op.query<{kind:string}>('select kind from neuvetra.stationary_diesel_evidence_reservations where company_id=$1 and evidence_key=$2 order by kind',[company,evidenceKey])).rows).toEqual([{kind:'meter'},{kind:'reference'}]);events.push('Identical textual meter label/reference produces separate retained kind-qualified reservations and readable workpaper')
  const before=structuredClone(head);let reachedReplay=false,replayRejected=false
  try{await op.transaction(async tx=>{
   const forged=structuredClone(head);forged.calculation!.gasResults.co2.mass='1';forged.calculation!.gasResults.co2.co2e='1';forged.calculation!.total.unrounded='1';forged.calculation!.total.display='1.0000';forged.calculation!.resultSha256=m76DieselHash(m76DieselCalculationHashPayload(forged.calculation!));forged.contentSha256=m76DieselHash(m76DieselContentPayload(forged));forged.versionSha256=m76DieselHash(m76DieselVersionHashPayload(forged))
   await tx.exec("set local session_replication_role='replica'");await tx.query('update neuvetra.stationary_diesel_versions set payload=$1::text::jsonb,content_sha256=$2,version_sha256=$3,export_text=$4 where id=$5',[JSON.stringify(forged),forged.contentSha256,forged.versionSha256,m76DieselExport(forged),forged.id]);await tx.query('update neuvetra.stationary_diesel_audit set record_sha256=$1 where record_id=$2',[forged.versionSha256,forged.id]);await tx.exec("set local session_replication_role='origin'");await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[owner]);await tx.exec('set local role neuvetra_runtime')
   const challenge={...authorities.diesel,replayBatch:async(calcs:any)=>{reachedReplay=true;try{await authorities.diesel.replayBatch(calcs)}catch(e){replayRejected=true;throw e}}};await refuses(readStationaryDiesel(tx,company,challenge));throw Error('Independent mandatory rollback')
  })}catch(e){expect((e as Error).message).toBe('Independent mandatory rollback')}
  expect(reachedReplay).toBe(true);expect(replayRejected).toBe(true);expect(await generator()).toEqual(before);events.push('Coordinated stored arithmetic/content/version/export/audit rehash reaches actual Python semantic replay and is refused; isolated transaction rollback restores exact original version')
  await Bun.write('evaluations/research-qa/m76-independent-native-security-result.json',JSON.stringify({status:'passed',database:name,template:prior.database,schema:receipts.at(-1),events,limitations:['Synthetic isolated database; no hosted execution.','Trigger catalog-definition enforcement reviewed separately by root/CTO.','Operator privilege used only for rollback-contained hostile storage mutation; runtime DML remains forbidden.']},null,2)+'\n');console.log(JSON.stringify({status:'passed',database:name,events}))
 }finally{await runtime?.close();await op?.close();await admin.close()}
},180000)
