import {test,expect}from'bun:test'
import {createPostgresConnection,HostedWorkspaceDatabase,readMigrationManifest,M76_DIESEL_LIMITATIONS}from'../../packages/neuvetra-database/src/index'
import {createM76DieselAuthority}from'../../apps/site-api/src/calculation/m76-authority'
import {decodeGeneratorRegister}from'../../apps/site-web/src/lib/m76-diesel-api'
const connect=(n:string,u='m63_test_admin')=>createPostgresConnection(`postgres://${u}@127.0.0.1:55463/${n}`,{tls:false,maxConnections:4})
async function refuses(p:Promise<unknown>){let e:any;try{await p}catch(x){e=x}expect(e instanceof Error).toBe(true);return e}
test.skipIf(process.env.M76_INDEPENDENT_NATIVE!=='enabled')('M76 independent retained generator forty-version and aggregate report-byte capacity',async()=>{
 const prior=await Bun.file('evaluations/research-qa/m76-independent-native-result.json').json();if(prior.status!=='passed'||!/^m76_qa_review_\d+$/.test(prior.database))throw Error('Successful independent native fixture required')
 const name=`m76_qa_capacity_${Date.now()}`,admin=connect('postgres'),authority=createM76DieselAuthority({python:'python'});let op:ReturnType<typeof connect>|undefined,runtime:ReturnType<typeof connect>|undefined
 try{
  expect((await admin.query('select 1 from pg_database where datname=$1',[name])).rows.length).toBe(0);await admin.exec(`create database ${name} template ${prior.database}`);op=connect(name);const manifest=await readMigrationManifest(),receipts=(await op.query<{name:string;sha256:string}>('select name,sha256 from neuvetra.schema_migrations order by name')).rows;expect(receipts).toEqual(manifest.map(m=>({name:m.name,sha256:m.sha256})))
  runtime=connect(name,'neuvetra_runtime');const ref=(await op.query<{project_ref:string}>('select project_ref from neuvetra.staging_target')).rows[0]!.project_ref,db=new(HostedWorkspaceDatabase as any)(runtime,ref)as HostedWorkspaceDatabase,{company,seed}=prior,{owner,workpaperReviewer}=seed.users
  const current=async()=>(await db.findStationaryDiesel(owner,company,authority))!,original=await current();let head=original.worksheets[0]!.versions.at(-1)!
  const correction=()=>({...structuredClone(head.activity),expectedVersionId:head.id,expectedVersionSha256:head.versionSha256,correctionReason:'Independent retained capacity check',idempotencyKey:crypto.randomUUID()})
  while(head.version<40){const input=correction();input.statement!.description='Independent bounded statement correction '+(head.version+1);head=await db.saveStationaryDiesel(owner,company,head.worksheetId,input,authority)}
  expect(head.version).toBe(40);const extra=correction();extra.statement!.description='Independent forty-first correction must be refused';expect((await refuses(db.saveStationaryDiesel(owner,company,head.worksheetId,extra,authority))).code).toBe('54000');let register=await current();expect(register.worksheets[0]!.versions.length).toBe(40);for(const v of original.worksheets[0]!.versions)expect(register.worksheets[0]!.versions.find(x=>x.id===v.id)).toEqual(v)
  let count=register.worksheets[0]!.reports.length,capacityCode:string|null=null
  for(const version of register.worksheets[0]!.versions){if(count===40)break;if(!register.worksheets[0]!.reports.some(r=>r.versionId===version.id&&r.decisionId===(version.review?.id??null))){try{await db.createStationaryDieselReport(owner,company,head.worksheetId,{versionId:version.id,expectedVersionSha256:version.versionSha256,expectedDecisionId:version.review?.id??null,expectedDecisionSha256:version.review?.decisionSha256??null,idempotencyKey:crypto.randomUUID()},authority);count++}catch(e){capacityCode=(e as any).code;expect(capacityCode).toBe('54001');break}}}
  register=await current();expect(register.worksheets[0]!.reports.length).toBe(count);expect(register.worksheets[0]!.versions.length).toBe(40);expect(capacityCode==='54001'||count===40).toBe(true);for(const report of original.worksheets[0]!.reports)expect(register.worksheets[0]!.reports.find(r=>r.id===report.id)).toEqual(report);await decodeGeneratorRegister(register,company)
  await Bun.write('evaluations/research-qa/m76-independent-native-capacity-result.json',JSON.stringify({status:'passed',database:name,template:prior.database,schema:receipts.at(-1),versions:40,reports:count,capacityCode,events:['Forty actual source versions retained; forty-first refused54000 with oldversions exact','Further source reports reached count or documented aggregate bytebound with earlierreports exact','Actual browser generator decoder accepts all retained records at capacity'],limitations:['Report countcap40 requires a separate smaller-history test; this fixture can hit the intentional3.8MB aggregate bytecap first','Isolated synthetic source family only; declaration-family count/byte caps remain separate','No production tables injected to simulate count limits; all records created by authenticated production writer methods']},null,2)+'\n');console.log(JSON.stringify({status:'passed',database:name,versions:40,reports:count,capacityCode}))
 }finally{await runtime?.close();await op?.close();await admin.close()}
},240000)
