import {test,expect}from'bun:test'
import {createPostgresConnection,HostedWorkspaceDatabase,readMigrationManifest,M76_DIESEL_LIMITATIONS}from'../../packages/neuvetra-database/src/index'
import {populateM76RecoveryFixture}from'../../tools/staging/m76-backend-fixture'
import {createM76DieselAuthority}from'../../apps/site-api/src/calculation/m76-authority'
import {decodeGeneratorRegister}from'../../apps/site-web/src/lib/m76-diesel-api'
const connect=(n:string,u='m63_test_admin')=>createPostgresConnection(`postgres://${u}@127.0.0.1:55463/${n}`,{tls:false,maxConnections:4})
test.skipIf(process.env.M76_INDEPENDENT_NATIVE!=='enabled')('M76 independent smaller source history reaches bounded report capacity without losing retained records',async()=>{
 const prior=await Bun.file('evaluations/research-qa/m76-independent-native-result.json').json();if(prior.status!=='passed'||!/^m76_qa_review_\d+$/.test(prior.database))throw Error('Successful independent native fixture required')
 const name=`m76_qa_reportcap_${Date.now()}`,admin=connect('postgres'),authority=createM76DieselAuthority({python:'python'});let op:ReturnType<typeof connect>|undefined,runtime:ReturnType<typeof connect>|undefined
 try{
  expect((await admin.query('select 1 from pg_database where datname=$1',[name])).rows.length).toBe(0);await admin.exec(`create database ${name} template ${prior.database}`);op=connect(name);const manifest=await readMigrationManifest(),receipts=(await op.query<{name:string;sha256:string}>('select name,sha256 from neuvetra.schema_migrations order by name')).rows;expect(receipts).toEqual(manifest.map(m=>({name:m.name,sha256:m.sha256})))
  const seed=await populateM76RecoveryFixture(op,name,55463),company=seed.companyId,{owner,workpaperReviewer}=seed.users
  runtime=connect(name,'neuvetra_runtime');const ref=(await op.query<{project_ref:string}>('select project_ref from neuvetra.staging_target')).rows[0]!.project_ref,db=new(HostedWorkspaceDatabase as any)(runtime,ref)as HostedWorkspaceDatabase,current=async()=>(await db.findStationaryDiesel(owner,company,authority))!
  const original=await current();let head=original.worksheets[0]!.versions.at(-1)!,count=original.worksheets[0]!.reports.length,capacityCode:string|null=null;const retainedReports=[...original.worksheets[0]!.reports]
  const report=async(v:any,review:any)=>{const saved=await db.createStationaryDieselReport(owner,company,v.worksheetId,{versionId:v.id,expectedVersionSha256:v.versionSha256,expectedDecisionId:review?.id??null,expectedDecisionSha256:review?.decisionSha256??null,idempotencyKey:crypto.randomUUID()},authority);retainedReports.push(saved);count++}
  while(count<40){try{const input={...structuredClone(head.activity),statement:{...head.activity.statement!,description:'Independent report-capacity source statement '+(head.version+1)},expectedVersionId:head.id,expectedVersionSha256:head.versionSha256,correctionReason:'Independent report count ceiling setup',idempotencyKey:crypto.randomUUID()};head=await db.saveStationaryDiesel(owner,company,head.worksheetId,input,authority);await report(head,null);if(count===40)break;const review=await db.reviewStationaryDiesel(workpaperReviewer,company,head.worksheetId,{versionId:head.id,expectedVersionSha256:head.versionSha256,decision:'accepted_bounded_internal',note:'Independent separate reviewer capacity setup',acknowledgedLimitations:[...M76_DIESEL_LIMITATIONS],idempotencyKey:crypto.randomUUID()},authority);await report(head,review)}catch(e){capacityCode=(e as any).code;expect(capacityCode).toBe('54001');break}}
  const final=await current();expect(capacityCode==='54001'||count===40).toBe(true);expect(count).toBeGreaterThan(original.worksheets[0]!.reports.length);expect(final.worksheets[0]!.reports).toEqual(retainedReports);expect(final.worksheets[0]!.versions.at(-1)!.id).toBe(head.id);for(const v of original.worksheets[0]!.versions)expect(final.worksheets[0]!.versions.find(x=>x.id===v.id)).toEqual(v);await decodeGeneratorRegister(final,company)
  await Bun.write('evaluations/research-qa/m76-independent-native-report-capacity-result.json',JSON.stringify({status:'passed',database:name,schema:receipts.at(-1),company,versions:final.worksheets[0]!.versions.length,reports:count,capacityCode,events:['Successive actual reports stored with captured null and later separately reviewed states until count or aggregate byte boundary','Bounded refusal preserves every successful source/report and fails no hidden integrity check','Actual generator browser decoder accepts the complete retained report register'],limitations:['Exact forty-report count guard inspected in SQL, not necessarily dynamically reached because3.8MB bytebound can refuse earlier','New isolated synthetic company; author fixture used only for two-source-version setup; capacity assertions independently authored','Declaration-family history limit remains separately scoped']},null,2)+'\n');console.log(JSON.stringify({status:'passed',database:name,versions:final.worksheets[0]!.versions.length,reports:count,capacityCode}))
 }finally{await runtime?.close();await op?.close();await admin.close()}
},240000)
