/** Read-only completed actual maintenance/gate receipt verification. No host/network/Git. */
import {validateUpgradeGate} from '../../tools/staging/m77-upgrade'
import {exclusiveJson,sha} from '../../tools/staging/m77-common'
const check=(x:unknown)=>{if(!x)throw Error('Independent completed gate body refused.')}
if(import.meta.main){
 const file='.superpowers/m77-hosted-gate-candidate1.json',gateText=await Bun.file(file).text(),gate=JSON.parse(gateText),artifacts:any={};for(const key of ['backup','restore','recovery','forwardRecovery']){const expected='.superpowers/'+({backup:'m77-hosted-backup-candidate1',restore:'m77-hosted-restore-candidate1',recovery:'m77-independent-hosted-recovery-candidate1',forwardRecovery:'m77-independent-forward-recovery-candidate1'} as any)[key]+'.json';check(gate[key+'Receipt']===expected);const text=await Bun.file(expected).text();check(sha(text)===gate[key+'ReceiptSha256']);artifacts[key]=JSON.parse(text)}
 check(gate.reviewedCommit==='1e2c44feb31a689363dbcde1c51dc38363d23bc1'&&gate.independentReviewSnapshotSha256==='e92dc48700cee08682c67bc92ae754b8f567699b62cd71ba2ef0c69006df4808'&&gate.operatorId==='/root'&&gate.independentReviewerId==='/root/m76_cto');validateUpgradeGate(gate,artifacts.backup,artifacts.restore,artifacts.recovery,artifacts.forwardRecovery);const evidenceAge=Date.now()-Date.parse(artifacts.forwardRecovery.evidenceObservedAt);check(evidenceAge>=0&&evidenceAge<4*60*60*1000);
 const checksText=await Bun.file('.superpowers/m70-checks.json').text(),headText=await Bun.file('.superpowers/m77-head-observation.json').text(),maintenanceText=await Bun.file('.superpowers/m77-maintenance.json').text(),checks=JSON.parse(checksText),head=JSON.parse(headText),maintenance=JSON.parse(maintenanceText),required=['Dedicated staging image and offline runtime smoke','GHG calculation specifications and engine','Native PostgreSQL worksheet and tenant regression','Offline research catalog tests','Role routing and evidence records','Typecheck, lint, unit tests and web builds'];check(checks.sha===gate.reviewedCommit&&checks.checks.length===6&&required.every(name=>checks.checks.filter((x:any)=>x.name===name&&x.status==='completed'&&x.conclusion==='success').length===1));check(head.remoteHead===gate.reviewedCommit&&head.observedAt===gate.headObservedAt&&new Date(checks.observed_at).toISOString()===gate.checksObservedAt);check(maintenance.activeDeploymentRemoved===true&&maintenance.readinessStatus===404&&maintenance.automaticDeploymentPaused===true&&maintenance.observedAt===gate.maintenanceObservedAt);check(sha(await Bun.file('.superpowers/m77-hosted-journey.jsonl').text())==='396f086ee8702e7fbb48dbd0b303ab1a9a993fed62db5569ac1bf184b8fd5462');
 const output='.superpowers/m77-independent-hosted-gate-body-candidate1.json';await exclusiveJson(output,{status:'independent_actual_maintenance_and_upgrade_gate_body_passed',createdAt:new Date().toISOString(),gateSha256:sha(gateText),reviewedCommit:gate.reviewedCommit,acceptedSnapshotSha256:gate.independentReviewSnapshotSha256,backupReceiptSha256:gate.backupReceiptSha256,restoreReceiptSha256:gate.restoreReceiptSha256,recoveryReceiptSha256:gate.recoveryReceiptSha256,forwardReceiptSha256:gate.forwardRecoveryReceiptSha256,maintenanceArtifactSha256:sha(maintenanceText),checkArtifactSha256:sha(checksText),headArtifactSha256:sha(headText),actualRootMaintenanceObservationsReviewed:true,allReviewedGateValidatorsPassed:true,underlyingForwardEvidenceFresh:true,reviewerDistinctFromOperator:true,actualUpgradeNotYetAccepted:true});console.log(JSON.stringify({output,sha256:sha(await Bun.file(output).text()),gateSha256:sha(gateText)}));
}
