import {test,expect} from 'bun:test'
import {acceptedM76Continuation,cleanM77Journal,readM77Journal} from '../../tools/staging/check-m77-hosted'
import {m77CanonicalJson as canonical} from '../../packages/neuvetra-database/src/m77-validation'
const company='11111111-1111-4111-8111-111111111111',hash=(x:any)=>new Bun.CryptoHasher('sha256').update(canonical(x)).digest('hex')
function chain(events:any[],previous=false){return events.map((e,i)=>{const {sha256,...original}=e;const body={...original,sequence:i+1,previousSha256:i?events[i-1].sha256:null,profile:previous?'m76-hosted-recovery-v1':'m77-hosted-journey-v1',...(previous?{companyId:company}:{workspaceId:company}),createdAt:'2026-09-16T23:00:00.000Z'};const out={...body,sha256:hash(body)};events[i]=out;return out})}
const text=(es:any[])=>es.map(e=>JSON.stringify(e)).join('\n')+'\n'
function current(){return chain([{mode:'baseline',kind:'attempt_started',data:{mode:'baseline'}},{mode:'baseline',kind:'baseline',data:{}},{mode:'baseline',kind:'attempt_finished',data:{attemptSequence:1,status:'passed',applicationPostRequests:0,allCreatedAuthSessionsClosed:true}},{mode:'exercise',kind:'attempt_started',data:{mode:'exercise'}},{mode:'exercise',kind:'post_intent',data:{name:'synthetic',route:'/synthetic',role:'manager1',expected:201}},{mode:'exercise',kind:'post_outcome',data:{name:'synthetic',route:'/synthetic',role:'manager1',expected:201,status:201,response:{id:'fictional'}}},{mode:'exercise',kind:'exercise_complete',data:{}},{mode:'exercise',kind:'attempt_finished',data:{attemptSequence:4,status:'passed',applicationPostRequests:1,allCreatedAuthSessionsClosed:true}}])}
function previous(){const es=current();es[1].kind='failed_state_baseline';es[1].data={legacy:{safe:'synthetic'}};es[5].data={name:'synthetic',status:201,response:{id:'fictional'},responseObservation:{sha256:'a'.repeat(64),byteLength:1}};es.splice(6,0,{mode:'exercise',kind:'step_verified',data:{name:'synthetic',response:{id:'fictional'}}});es[7].kind='recovery_complete';es[7].data={registers:{fictional:true},downloads:{}};es[8].data.attemptSequence=5;es.unshift({mode:'baseline',kind:'continuation_provenance',data:{}});es[3].data.attemptSequence=2;es.push({mode:'revisit',kind:'attempt_started',data:{mode:'revisit'}},{mode:'revisit',kind:'recovery_revisit',data:{applicationPostRequests:0}},{mode:'revisit',kind:'attempt_finished',data:{attemptSequence:11,status:'passed',applicationPostRequests:0,allCreatedAuthSessionsClosed:true}});return chain(es,true)}
test('F05 exact legacy outcome shape and current ordered closure admitted',()=>{expect(()=>cleanM77Journal(readM77Journal(text(current()),company))).not.toThrow();expect(()=>acceptedM76Continuation(text(previous()),company)).not.toThrow()})
test('F05 current orphan, reversed, crossed and uncertain events refuse',()=>{const cases=[(e:any[])=>e.push({mode:'exercise',kind:'attempt_finished',data:{attemptSequence:999,status:'failed'}}),(e:any[])=>{[e[4],e[5]]=[e[5],e[4]]},(e:any[])=>e[7].data.attemptSequence=1,(e:any[])=>e[7].data.status='failed',(e:any[])=>e[7].data.allCreatedAuthSessionsClosed=false,(e:any[])=>e[7].data.applicationPostRequests=0,(e:any[])=>e[5].data.route='/other',(e:any[])=>e[5].data.role='manager2',(e:any[])=>e[5].data.expected=403,(e:any[])=>e[5].data.status=403,(e:any[])=>e.splice(5,1),(e:any[])=>e.splice(7,1),(e:any[])=>e[4].mode='baseline',(e:any[])=>e.splice(5,0,{...e[4]})];for(const mutate of cases){const es=current();mutate(es);expect(()=>cleanM77Journal(readM77Journal(text(chain(es)),company))).toThrow()}})
test('F05 legacy exact step/outcome and original intent expectation remain bound',()=>{const cases=[(e:any[])=>e[7].data.response.id='forged',(e:any[])=>e[6].data.status=403,(e:any[])=>e[5].data.expected=403,(e:any[])=>{[e[6],e[7]]=[e[7],e[6]]},(e:any[])=>e.splice(7,1),(e:any[])=>e.push({mode:'revisit',kind:'attempt_finished',data:{attemptSequence:999,status:'failed'}}),(e:any[])=>e[12].data.allCreatedAuthSessionsClosed=false,(e:any[])=>e[12].data.applicationPostRequests=1];for(const mutate of cases){const es=previous();mutate(es);expect(()=>acceptedM76Continuation(text(chain(es,true)),company)).toThrow()}})
test('F05 successful closure requires matching verification marker before finish',()=>{const es:any[]=[{mode:'baseline',kind:'attempt_started',data:{mode:'baseline'}},{mode:'baseline',kind:'attempt_finished',data:{attemptSequence:1,status:'passed',applicationPostRequests:0,allCreatedAuthSessionsClosed:true}}];expect(()=>cleanM77Journal(readM77Journal(text(chain(es)),company))).toThrow();const currentEarly=current();[currentEarly[5],currentEarly[6]]=[currentEarly[6],currentEarly[5]];expect(()=>cleanM77Journal(readM77Journal(text(chain(currentEarly)),company))).toThrow();const legacyLate=previous();[legacyLate[7],legacyLate[8]]=[legacyLate[8],legacyLate[7]];expect(()=>acceptedM76Continuation(text(chain(legacyLate,true)),company)).toThrow()})
test('unchanged runner503 and partial durability failures halt without retry or global transport mutation',async()=>{const {runM77Journey,parseM77JourneyInput}=await import('../../tools/staging/check-m77-hosted');const prior=previous(),priorText=text(prior),digest=(s:string)=>new Bun.CryptoHasher('sha256').update(s).digest('hex'),input=parseM77JourneyInput({mode:'baseline',acceptedM76:{journalSha256:digest(priorText),headSha256:prior.at(-1).sha256},env:{SUPABASE_URL:'https://icockcoguyadhryzydvl.supabase.co',SUPABASE_ANON_KEY:'sb_publishable_'+'a'.repeat(30)},roster:{workspaceId:company},accounts:['manager1','manager2','member','outsider'].map((role,i)=>({role,id:`77000000-0000-4000-8000-00000000001${i}`,email:role+'@synthetic.invalid',password:'fictional-local-only'}))});const original=globalThis.fetch;for(const partial of [false,true]){let journal:string|null=null,calls=0;const deps:any={load:async()=>journal,loadPrevious:async()=>priorText,append:async(line:string)=>{journal=(journal??'')+line;if(partial)throw Error('Fictional partial durability failure')},fetch:async(url:string,init:any)=>{calls++;expect(url).toBe('https://www.neuvetra.ai/ready');expect(init.redirect).toBe('error');return new Response(null,{status:503})}};const failed=await runM77Journey(input,deps);expect(failed.status).toBe('failed');expect(failed.applicationPostRequests).toBe(0);expect(failed.allCreatedAuthSessionsClosed).toBe(true);expect(journal).not.toBeNull();expect(calls).toBe(partial?0:1);expect(()=>cleanM77Journal(readM77Journal(journal,company))).toThrow();const before=calls;expect((await runM77Journey(input,deps)).status).toBe('failed');expect(calls).toBe(before);expect(globalThis.fetch).toBe(original)}})
