/** Independent corporate screening/source correction and additive catalog preservation. */
import {test,expect} from 'bun:test'
import {createM77AuthorDatabase,serveM77Fixture,m77FixtureReportInput,m77FixtureSourceInput} from '../../tools/staging/m77-backend-fixture'
import {decodeFugitiveRegister,decodeFugitiveVersion} from '../../apps/site-web/src/lib/m77-api'
import {createPostgresConnection,m77CanonicalJson,m77BytesHash,M71_LIMITATIONS,M77_LIMITATIONS,type M77SourceVersion,type M77PopulationVersion} from '../../packages/neuvetra-database/src/index'
test.skipIf(process.env.NEUVETRA_M77_QA_NATIVE!=='1')('independent schema19 preservation, corporate screening, source identity correction and population rebind',async()=>{
 let assertions=0,baselineSchema=0;const ci=process.env.NEUVETRA_M77_CI_BASELINE==='1',ct=(v:unknown)=>{assertions++;expect(Boolean(v)).toBe(true)},baseline=ci?'m63_integration':'m76_author_root_ui3',prior=createPostgresConnection(`postgres://m63_test_admin@127.0.0.1:55463/${baseline}`,{tls:false,maxConnections:1})
 const catalogSql="select p.oid::regprocedure::text identity,pg_get_functiondef(p.oid) definition,p.proacl::text acl,p.prosecdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='neuvetra'and p.prokind='f'order by identity"
 let old:any[];try{old=(await prior.query(catalogSql)).rows;baselineSchema=(await prior.query<{count:number}>('select count(*)::integer count from neuvetra.schema_migrations')).rows[0].count;ct(ci?baselineSchema>0&&baselineSchema<=20:baselineSchema===19)}finally{await prior.close()}
 const name='m77_author_qa_binding_'+Date.now(),f=await createM77AuthorDatabase(name,baseline),s=await serveM77Fixture(f,0),op=createPostgresConnection(`postgres://m63_test_admin@127.0.0.1:55463/${name}`,{tls:false,maxConnections:1}),company=f.companyId
 const pins=Object.fromEntries(await Promise.all(['packages/neuvetra-database/src/migrations/0020_fugitive_sources.sql','packages/neuvetra-database/src/m77.ts','packages/neuvetra-database/src/m77-validation.ts','packages/neuvetra-database/src/m77-report.ts','apps/site-web/src/lib/m77-api.ts'].map(async p=>[p,m77BytesHash(await Bun.file(p).text())])))
 const req=(route:string,body?:unknown,actor='owner')=>s.server.fetch(new Request(`http://127.0.0.1:${s.server.port}/workspace/${company}/${route}`,{method:body?'POST':'GET',headers:{origin:'http://localhost:4186',authorization:'Bearer synthetic-m77-'+actor,...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}))
 const read=async()=>{const r=await req('fugitive-sources');ct(r.status===200);return decodeFugitiveRegister(await r.json(),company)}
 const reviewSource=async(v:M77SourceVersion,actor='sourceReviewer',status=201)=>{ct((await req(`fugitive-sources/${v.streamId}/reviews`,{versionId:v.id,expectedVersionSha256:v.versionSha256,expectedDependencySha256:null,decision:'accepted_bounded_internal',note:'Independent synthetic review after corporate correction.',acknowledgedLimitations:[...M77_LIMITATIONS],idempotencyKey:crypto.randomUUID()},actor)).status===status)}
 const corpReview=async(v:any)=>{await s.database.reviewCorporateInventory(f.users.sourceReviewer,company,v.inventoryId,{versionId:v.id,expectedVersionSha256:v.versionSha256,decision:'accepted_bounded_internal',note:'Separate bounded synthetic control and source screening review.',acknowledgedLimitations:[...M71_LIMITATIONS],idempotencyKey:crypto.randomUUID()})}
 try{
  const after=(await op.query(catalogSql)).rows as any[];for(const before of old!){ct(m77CanonicalJson(after.find(x=>x.identity===before.identity))===m77CanonicalJson(before))}
  const classes=(await op.query<any>("select relname,relrowsecurity,relforcerowsecurity,has_table_privilege('neuvetra_runtime',oid,'INSERT,UPDATE,DELETE,TRUNCATE') write,has_table_privilege('authenticated',oid,'SELECT,INSERT,UPDATE,DELETE') authenticated from pg_class where relnamespace='neuvetra'::regnamespace and relname like 'fugitive_%'and relkind='r'")).rows;ct(classes.length===8);for(const c of classes)ct(c.relrowsecurity&&c.relforcerowsecurity&&!c.write&&!c.authenticated)
  const funcs=(await op.query<any>("select proname,proconfig,has_function_privilege('authenticated',oid,'execute') auth,has_function_privilege('neuvetra_runtime',oid,'execute') runtime from pg_proc where pronamespace='neuvetra'::regnamespace and(proname like 'm77_%'or proname in('save_fugitive_version','review_fugitive_version','create_fugitive_report'))")).rows;for(const p of funcs){ct(!p.auth);ct(p.runtime===['m77_lock','save_fugitive_version','review_fugitive_version','create_fugitive_report'].includes(p.proname));ct(p.proconfig?.includes('search_path=pg_catalog, neuvetra, pg_temp'))}
  await s.runtime.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[f.users.outsider]);ct((await tx.query('select id from neuvetra.fugitive_versions')).rows.length===0);ct((await tx.query<{allowed:boolean}>('select neuvetra.m77_lock($1,false) allowed',[company])).rows[0].allowed===false)})
  let r=await read();const historical=[...r.worksheets.flatMap(w=>w.reports),...r.population.reports].map(x=>structuredClone(x)),source=r.worksheets.find(w=>w.assetId==='OFFICE-HVAC-A')!.versions.at(-1)!,oldSourceId=source.activity.binding.sourceId,newSourceId=crypto.randomUUID();let corporate=(await s.database.findCorporateInventory(f.users.owner,company))!.versions.at(-1)!
  // A current ordinary screening successor can expose missing evidence; old source estimates cannot clear it.
  const unresolved=structuredClone(corporate.snapshot);const item=unresolved.coverageItems.find(x=>x.sourceId===oldSourceId)!;Object.assign(item,{disposition:'missing',activityDataState:'missing',evidenceState:'missing',methodReadiness:'unsupported',reason:null,evidenceRefs:[]})
  corporate=await s.database.saveCorporateInventory(f.users.coverageReviewer,company,corporate.inventoryId,{snapshot:unresolved,expectedVersionId:corporate.id,expectedVersionSha256:corporate.versionSha256,correctionReason:'Independent fictional screening correction exposes unresolved source evidence.',idempotencyKey:crypto.randomUUID()});await corpReview(corporate);r=await read();ct(r.reconciliation.status==='blocked');ct(r.reconciliation.findings.some(x=>x.code==='stale_workpaper'));ct(!r.sources.find(x=>x.binding.sourceId===oldSourceId)!.eligible)
  const invalid={...source.activity,binding:r.sources.find(x=>x.binding.sourceId===oldSourceId)!.binding,expectedVersionId:source.id,expectedVersionSha256:source.versionSha256,correctionReason:'Attempt numerical admission with unresolved current corporate screening.',idempotencyKey:crypto.randomUUID()};ct((await req(`fugitive-sources/${source.streamId}/versions`,invalid)).status===422)
  // Justified source identity correction retains device identity and repairs only ordinary source screening.
  const fixed=structuredClone(corporate.snapshot),src=fixed.sources.find(x=>x.id===oldSourceId)!;fixed.sources.push({...src,id:newSourceId,name:'Office HVAC corrected ordinary source identity'});const fixedItem=fixed.coverageItems.find(x=>x.sourceId===oldSourceId)!;const retained=r.worksheets.find(w=>w.assetId===source.activity.assetId)!.versions[0].coverageVersion.snapshot.coverageItems.find(x=>x.sourceId===oldSourceId)!;Object.assign(fixedItem,{...retained,id:fixedItem.id,reason:'Fictional complete evidence resolves the prior screening; old source identity remains retained.'});fixed.coverageItems.push({...fixedItem,id:crypto.randomUUID(),sourceId:newSourceId,reason:'Fictional additional ordinary source identity documents the corrected physical device relationship.'});ct(fixedItem.quantity===null&&fixedItem.unit===null)
  corporate=await s.database.saveCorporateInventory(f.users.coverageReviewer,company,corporate.inventoryId,{snapshot:fixed,expectedVersionId:corporate.id,expectedVersionSha256:corporate.versionSha256,correctionReason:'Correct ordinary source identity while retaining the physical controlled device.',idempotencyKey:crypto.randomUUID()});await corpReview(corporate);r=await read()
  for(const w of r.worksheets){const v=w.versions.at(-1)!,binding=r.sources.find(x=>x.binding.sourceId===(v.activity.binding.sourceId===oldSourceId?newSourceId:v.activity.binding.sourceId))!.binding,x=await req(`fugitive-sources/${v.streamId}/versions`,{...v.activity,binding,expectedVersionId:v.id,expectedVersionSha256:v.versionSha256,correctionReason:'Rebind unchanged physical source evidence to corrected separately reviewed corporate coverage.',idempotencyKey:crypto.randomUUID()});ct(x.status===201);const saved=await decodeFugitiveVersion(await x.json(),company) as M77SourceVersion;ct(saved.activity.assetId===v.activity.assetId);ct(saved.calculation!.kg_co2e_exact===v.calculation!.kg_co2e_exact);ct(saved.contributorIds.includes(f.users.coverageReviewer));await reviewSource(saved,'coverageReviewer',403);await reviewSource(saved)}
  r=await read();ct(r.reconciliation.status==='blocked');ct(r.reconciliation.findings.some(x=>x.code==='orphan_source'&&x.sourceId===newSourceId));ct(r.worksheets.find(w=>w.assetId===source.activity.assetId)!.sourceId===newSourceId)
  const additional=m77FixtureSourceInput(r.coverageVersion!,oldSourceId,'QA-SECOND-DOCUMENTED-OFFICE-HVAC','R-410A','fixed_hvac','0.5'),extraResponse=await req('fugitive-sources',additional);ct(extraResponse.status===201);const extra=await decodeFugitiveVersion(await extraResponse.json(),company) as M77SourceVersion;await reviewSource(extra);r=await read()
  let pop=r.population.versions.at(-1)!;const physical={...pop.activity.declaration!.assets.find(a=>a.sourceId===oldSourceId)!,assetId:additional.assetId,explanation:'Independent fictional discovery distinguishes a second controlled device and preserves the previously recorded source identity.'};const x=await req(`fugitive-population/${pop.streamId}/versions`,{...pop.activity,coverageVersionId:corporate.id,coverageVersionSha256:corporate.versionSha256,declaration:{...pop.activity.declaration!,assets:[...pop.activity.declaration!.assets.map(a=>a.sourceId===oldSourceId?{...a,sourceId:newSourceId}:a),physical]},expectedVersionId:pop.id,expectedVersionSha256:pop.versionSha256,expectedDependencySha256:r.reconciliation.dependencySha256,correctionReason:'Retain all discovered device identities and correct their ordinary source relationship with an independently documented additional device.',idempotencyKey:crypto.randomUUID()});ct(x.status===201);pop=await decodeFugitiveVersion(await x.json(),company) as M77PopulationVersion
  const review={versionId:pop.id,expectedVersionSha256:pop.versionSha256,expectedDependencySha256:pop.dependencies!.dependencySha256,decision:'accepted_bounded_reconciliation',note:'Separate exact synthetic population and corrected source union review.',acknowledgedLimitations:[...M77_LIMITATIONS],idempotencyKey:crypto.randomUUID()};ct((await req(`fugitive-population/${pop.streamId}/reviews`,review,'coverageReviewer')).status===403);ct((await req(`fugitive-population/${pop.streamId}/reviews`,{...review,idempotencyKey:crypto.randomUUID()},'populationReviewer')).status===201);r=await read();ct(r.reconciliation.status==='reconciled_bounded_synthetic')
  ct((await req(`fugitive-population/${pop.streamId}/reports`,m77FixtureReportInput(r.population.versions.at(-1)!,r))).status===201);r=await read();for(const old of historical){const now=[...r.worksheets.flatMap(w=>w.reports),...r.population.reports].find(x=>x.id===old.id)!;ct(m77CanonicalJson(now)===m77CanonicalJson(old))}
  for(const p of Object.keys(pins))ct(pins[p]===m77BytesHash(await Bun.file(p).text()))
  await Bun.write('evaluations/research-qa/m77-binding-native-result.json',JSON.stringify({status:'independent_local_binding_catalog_preservation_pass',database:name,baseline,baselineSchema,assertions,oldFunctionCount:old!.length,newTableCount:classes.length,pins,createdAt:new Date().toISOString(),hostedEvidence:false,auth:'fictional_local_adapter',rowPreservationReceipt:`.superpowers/${name}-preservation.json`,criteria:['exact_existing_functions_ACLs_security_flags_preserved','new_FORCED_RLS_and_no_runtime_DML','restricted_helper_execute_and_fixed_search_path','unresolved_current_corporate_screening_blocks_numerical_admission','distinct_corporate_contributor_excluded_from_source_and_population_reviews','source_identity_correction_retains_device_and_results','all_source_versions_and_reviews_rebind','independent_population_source_relationship_rebind','exact_old_captured_reports_preserved']},null,2)+'\n')
 }finally{await op.close();await s.close()}
},180000)
