/** Independent first-review probes; fictional isolated database only. */
import {createM77AuthorDatabase,serveM77Fixture,m77FixtureReportInput} from '../../tools/staging/m77-backend-fixture'
import {decodeFugitiveRegister,decodeFugitiveVersion,decodeFugitiveReport,fugitiveReportDownload} from '../../apps/site-web/src/lib/m77-api'
import {m77Hash,m77BytesHash,m77CanonicalJson,m77ContentPayload,m77VersionHashPayload,m77ReportHashPayload,m77RenderReport,M77_LIMITATIONS,type M77PopulationVersion,type M77Report} from '../../packages/neuvetra-database/src/index'
const check=(v:unknown)=>{if(!v)throw Error('Independent M77 probe failed.')}
export async function firstProbe(){
 const name='m77_author_qa_first_'+Date.now(),fixture=await createM77AuthorDatabase(name),service=await serveM77Fixture(fixture,0),company=fixture.companyId,origin='http://localhost:4186'
 const hashes:Record<string,string>={};for(const p of ['packages/neuvetra-database/src/migrations/0020_fugitive_sources.sql','packages/neuvetra-database/src/m77.ts','packages/neuvetra-database/src/m77-validation.ts','apps/site-web/src/lib/m77-api.ts'])hashes[p]=m77BytesHash(await Bun.file(p).text())
 const request=(p:string,body?:unknown,actor='owner')=>service.server.fetch(new Request(`http://127.0.0.1:${service.server.port}/workspace/${company}/${p}`,{method:body?'POST':'GET',headers:{origin,authorization:'Bearer synthetic-m77-'+actor,...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}))
 const read=async()=>{const r=await request('fugitive-sources');check(r.status===200);return decodeFugitiveRegister(await r.json(),company)}
 try{
  let r=await read();check(r.reconciliation.status==='reconciled_bounded_synthetic')
  const initial=r.population.versions.at(-1)!,mobile={assetId:'QA-CONTROLLED-MOBILE-HVAC',entityId:initial.activity.declaration!.assets[0].entityId,facilityId:null,equipment:'mobile_hvac' as const,gas:'HFC-134a',capacityKg:'2',controlBasis:'owned_operational_control_full_year' as const,explanation:'Independent fictional fleet discovery confirms this controlled vehicle air-conditioning asset throughout 2025; unsupported numerical method.',sourceId:null}
  const addedResponse=await request(`fugitive-population/${initial.streamId}/versions`,{...initial.activity,declaration:{...initial.activity.declaration!,assets:[...initial.activity.declaration!.assets,mobile]},expectedDependencySha256:r.reconciliation.dependencySha256,expectedVersionId:initial.id,expectedVersionSha256:initial.versionSha256,correctionReason:'Retain independently discovered unsupported controlled vehicle HVAC.',idempotencyKey:crypto.randomUUID()});check(addedResponse.status===201)
  let pop=await decodeFugitiveVersion(await addedResponse.json(),company) as M77PopulationVersion;r=await read();check(r.reconciliation.findings.some(f=>f.code==='unsupported_asset'&&f.assetId===mobile.assetId))
  const blockedReportResponse=await request(`fugitive-population/${pop.streamId}/reports`,m77FixtureReportInput(pop,r));check(blockedReportResponse.status===201);const blocked=await decodeFugitiveReport(await blockedReportResponse.json(),company)
  const dropResponse=await request(`fugitive-population/${pop.streamId}/versions`,{...pop.activity,declaration:{...pop.activity.declaration!,assets:pop.activity.declaration!.assets.filter(a=>a.assetId!==mobile.assetId)},expectedDependencySha256:r.reconciliation.dependencySha256,expectedVersionId:pop.id,expectedVersionSha256:pop.versionSha256,correctionReason:'Remove the unsupported vehicle discovery without admitting a retirement or removal method.',idempotencyKey:crypto.randomUUID()})
  let dropReviewStatus:number|null=null,afterDropStatus:string|null=null
  if(dropResponse.status===201){pop=await decodeFugitiveVersion(await dropResponse.json(),company) as M77PopulationVersion;const review=await request(`fugitive-population/${pop.streamId}/reviews`,{versionId:pop.id,expectedVersionSha256:pop.versionSha256,expectedDependencySha256:pop.dependencies!.dependencySha256,decision:'accepted_bounded_reconciliation',note:'Independent fictional reviewer attempts acceptance after unsupported asset deletion.',acknowledgedLimitations:[...M77_LIMITATIONS],idempotencyKey:crypto.randomUUID()},'populationReviewer');dropReviewStatus=review.status;r=await read();afterDropStatus=r.reconciliation.status}
  const retained=r.population.reports.find(x=>x.id===blocked.id)!;check(retained.html===blocked.html&&retained.snapshotJson===blocked.snapshotJson)
  const sourceReport=r.worksheets.find(w=>w.reports.length)!.reports.at(-1)!,captured=JSON.parse(sourceReport.snapshotJson),actualVersion=r.worksheets.flatMap(w=>w.versions).find(v=>v.id===sourceReport.versionId)!
  captured.version.activity.label='COORDINATED-FORGED-LABEL';captured.version.inputSha256=m77Hash(captured.version.activity);captured.version.contentSha256=m77Hash(m77ContentPayload(captured.version));captured.version.versionSha256=m77Hash(m77VersionHashPayload(captured.version));if(captured.review){captured.review.versionSha256=captured.version.versionSha256;const {decisionSha256,...review}=captured.review;captured.review.decisionSha256=m77Hash({companyId:company,...review})}
  const snapshotJson=m77CanonicalJson(captured),html=m77RenderReport(captured),forged:M77Report={...sourceReport,versionSha256:captured.version.versionSha256,snapshotJson,snapshotSha256:m77BytesHash(snapshotJson),html,htmlSha256:m77BytesHash(html),htmlByteLength:new TextEncoder().encode(html).length};forged.reportSha256=m77Hash(m77ReportHashPayload(forged))
  let forgedDecodeAccepted=false,forgedDownloadAccepted=false;try{await decodeFugitiveReport(forged,company);forgedDecodeAccepted=true}catch{}
  const savedFetch=globalThis.fetch,downloadRoutes:string[]=[];globalThis.fetch=(async(url)=>{downloadRoutes.push(String(url));return new Response(forged.html,{headers:{'cache-control':'no-store'}})}) as typeof fetch
  try{const text=await fugitiveReportDownload({accessToken:'synthetic-only',userId:fixture.users.member,role:'member'},company,forged);forgedDownloadAccepted=text===forged.html}catch{}finally{globalThis.fetch=savedFetch}
  check(captured.version.id===actualVersion.id&&captured.version.versionSha256!==actualVersion.versionSha256)
  const results={task:'M77-INDEPENDENT-QA',status:dropResponse.status===201&&dropReviewStatus===201&&afterDropStatus==='reconciled_bounded_synthetic'||forgedDownloadAccepted?'findings_reproduced':'probes_refused',database:name,createdAt:new Date().toISOString(),hashes,findings:{savedUnsupportedAssetRemoval:{addStatus:addedResponse.status,dropStatus:dropResponse.status,reviewStatus:dropReviewStatus,currentStatus:afterDropStatus,blockedHistoryPreserved:true},coordinatedReportVersionForgery:{sameRetainedVersionId:true,differentCapturedVersionSha256:true,decodeAccepted:forgedDecodeAccepted,downloadAccepted:forgedDownloadAccepted,downloadRequests:downloadRoutes.length,authorizedExactVersionFetched:downloadRoutes.some(p=>p.includes('/versions/'))}},transport:'actual_local_runtime_routes_and_authority; synthetic_local_auth_adapter; forged_download_transport_stub_only',hostedEvidence:false}
  await Bun.write('evaluations/research-qa/m77-first-probe-result.json',JSON.stringify(results,null,2)+'\n');return results
 }finally{await service.close()}
}
if(import.meta.main){try{console.log(JSON.stringify(await firstProbe()))}catch{console.error(JSON.stringify({status:'m77_independent_first_probe_refused'}));process.exitCode=1}}
