/** Independent integrated QA. New fictional databases only; no host or provider Auth. */
import {test,expect} from 'bun:test'
import {createM77AuthorDatabase,serveM77Fixture} from '../../tools/staging/m77-backend-fixture'
import {decodeFugitiveRegister,decodeFugitiveVersion,fugitiveReportDownload,fugitiveSnapshotDownload,fugitiveStatementDownload,fugitiveRegisterRequest} from '../../apps/site-web/src/lib/m77-api'
import {createPostgresConnection,m77Hash,m77BytesHash,m77CanonicalJson,m77ContentPayload,m77VersionHashPayload,m77ReportHashPayload,m77RenderReport,deriveM77Reconciliation,M77_LIMITATIONS,type M77SourceVersion,type M77PopulationVersion,type M77Report,type M77Register} from '../../packages/neuvetra-database/src/index'
test.skipIf(process.env.NEUVETRA_M77_QA_NATIVE!=='1')('independent M77 physical discovery, contributor/dependency closure, historical reports, security and exact arithmetic',async()=>{
 const name='m77_author_qa_final_'+Date.now(),f=await createM77AuthorDatabase(name,process.env.NEUVETRA_M77_CI_BASELINE==='1'?'m63_integration':'m68_qa'),s=await serveM77Fixture(f,0),op=createPostgresConnection(`postgres://m63_test_admin@127.0.0.1:55463/${name}`,{tls:false,maxConnections:1}),company=f.companyId,origin='http://localhost:4186';let assertions=0
 const ct=(v:unknown)=>{assertions++;expect(Boolean(v)).toBe(true)}
 const req=(route:string,body?:unknown,actor='owner',c=company,o=origin)=>s.server.fetch(new Request(`http://127.0.0.1:${s.server.port}/workspace/${c}/${route}`,{method:body?'POST':'GET',headers:{origin:o,authorization:'Bearer synthetic-m77-'+actor,...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}))
 const read=async()=>{const r=await req('fugitive-sources');ct(r.status===200);return decodeFugitiveRegister(await r.json(),company)}
 const save=async(v:M77SourceVersion,patch:Record<string,unknown>,status=201,actor='owner')=>{const r=await req(`fugitive-sources/${v.streamId}/versions`,{...v.activity,...patch,expectedVersionId:v.id,expectedVersionSha256:v.versionSha256,correctionReason:'Independent fictional correction with retained equipment identity.',idempotencyKey:crypto.randomUUID()},actor);ct(r.status===status);return status===201?await decodeFugitiveVersion(await r.json(),company) as M77SourceVersion:v}
 const savePop=async(r:M77Register,declaration:unknown,status=201)=>{const v=r.population.versions.at(-1)!,x=await req(`fugitive-population/${v.streamId}/versions`,{...v.activity,declaration,expectedVersionId:v.id,expectedVersionSha256:v.versionSha256,expectedDependencySha256:r.reconciliation.dependencySha256,correctionReason:'Independent physical discovery correction retains all known devices.',idempotencyKey:crypto.randomUUID()});ct(x.status===status);return status===201?await decodeFugitiveVersion(await x.json(),company) as M77PopulationVersion:v}
 const review=async(v:M77SourceVersion|M77PopulationVersion,actor:string,status=201)=>{const r=await req(`${v.family==='source'?'fugitive-sources':'fugitive-population'}/${v.streamId}/reviews`,{versionId:v.id,expectedVersionSha256:v.versionSha256,expectedDependencySha256:v.dependencies?.dependencySha256??null,decision:v.family==='source'?'accepted_bounded_internal':'accepted_bounded_reconciliation',note:'Independent fictional exact version and evidence review.',acknowledgedLimitations:[...M77_LIMITATIONS],idempotencyKey:crypto.randomUUID()},actor);ct(r.status===status)}
 const rehash=(v:any)=>{v.inputSha256=m77Hash(v.activity);v.contentSha256=m77Hash(m77ContentPayload(v));v.versionSha256=m77Hash(m77VersionHashPayload(v))}
 const rejected=async(action:()=>Promise<unknown>)=>{let refused=false;try{await action()}catch{refused=true}ct(refused)}
 const files=['packages/neuvetra-database/src/migrations/0020_fugitive_sources.sql','packages/neuvetra-database/src/m77.ts','packages/neuvetra-database/src/m77-validation.ts','packages/neuvetra-database/src/m77-report.ts','packages/neuvetra-database/src/m77-contract.ts','apps/site-api/src/calculation/m77-authority.ts','apps/site-api/src/calculation/m77_fugitive.py','apps/site-web/src/lib/m77-api.ts','apps/site-web/src/components/FugitiveWorkpapers.tsx','apps/site-web/src/components/FugitivePopulationEditor.tsx','apps/site-web/src/components/FugitiveSourceEditor.tsx','apps/site-api/src/workspace/m77-routes.ts'];const pins=Object.fromEntries(await Promise.all(files.map(async p=>[p,m77BytesHash(await Bun.file(p).text())])))
 const actualFetch=globalThis.fetch
 try{
  let r=await read();ct(r.reconciliation.status==='reconciled_bounded_synthetic');ct(r.worksheets.length===5)
  const historical=[...r.worksheets.flatMap(w=>w.reports),...r.population.reports].map(x=>structuredClone(x)),pending=r.population.reports[0],sourcePending=r.worksheets.flatMap(w=>w.reports).find(x=>JSON.parse(x.snapshotJson).review===null)!
  ct(JSON.parse(pending.snapshotJson).review===null);ct(JSON.parse(pending.snapshotJson).proof.workpaperVersions.every((v:any)=>v.review===null));ct(JSON.parse(sourcePending.snapshotJson).review===null)
  const formulas:Record<string,[string,string]>={'OFFICE-HVAC-A':['2405','2405.0000'],'OFFICE-FIRE-A':['0.00335','0.0034'],'DISTRIBUTION-HVAC-A':['1443','1443.0000'],'DISTRIBUTION-REFRIG-A':['162.5','162.5000'],'DISTRIBUTION-FIRE-A':['0.01005','0.0100']}
  for(const w of r.worksheets){const v=w.versions.at(-1)!;ct(v.calculation!.kg_co2e_exact===formulas[w.assetId][0]);ct(v.calculation!.kg_co2e_display===formulas[w.assetId][1]);ct(v.calculation!.evidence_verified===false)}
  for(const actor of ['member','outsider','invalid'])ct((await req('fugitive-sources',undefined,actor)).status===({member:200,outsider:403,invalid:401} as any)[actor])
  ct((await req('fugitive-sources',undefined,'owner',crypto.randomUUID())).status===404);ct((await req('fugitive-sources',undefined,'owner',company,'https://untrusted.invalid')).status===403);ct((await req('fugitive-sources',f.inputs[0],'member')).status===403)
  const a={accessToken:'synthetic-m77-member',userId:f.users.member,role:'member' as const};const calls:string[]=[]
  globalThis.fetch=(async(url,init)=>{calls.push(String(url));return s.server.fetch(new Request(String(url).replace('/workspace-api',`http://127.0.0.1:${s.server.port}`),{...init,headers:{...Object.fromEntries(new Headers(init?.headers)),origin}}))}) as typeof fetch
  for(const report of historical){ct(await fugitiveReportDownload(a,company,report)===report.html);ct(await fugitiveSnapshotDownload(a,company,report)===report.snapshotJson)}
  ct(calls.some(x=>x.includes('/versions/')));ct(calls.some(x=>/\/reports\/[a-f0-9-]+$/.test(x)))
  const first=r.worksheets[0].versions[0];ct(await fugitiveStatementDownload(a,company,first,first.statements[0].id)===first.statements[0].text)
  // Coordinated core forgery cannot be blessed by matching report metadata alone.
  const original=historical.find(x=>x.family==='source')!,snap=JSON.parse(original.snapshotJson);snap.version.activity.label='QA-FORGED-CORE';rehash(snap.version)
  if(snap.review){snap.review.versionSha256=snap.version.versionSha256;const {decisionSha256,...rest}=snap.review;snap.review.decisionSha256=m77Hash({companyId:company,...rest})}
  const forge=(base:M77Report,snapshot:any)=>{const snapshotJson=m77CanonicalJson(snapshot),html=m77RenderReport(snapshot),v={...base,versionSha256:snapshot.version.versionSha256,snapshotJson,snapshotSha256:m77BytesHash(snapshotJson),html,htmlSha256:m77BytesHash(html),htmlByteLength:new TextEncoder().encode(html).length};return {...v,reportSha256:m77Hash(m77ReportHashPayload(v))}}
  const forged=forge(original,snap),authoritativeVersion=r.worksheets.flatMap(w=>w.versions).find(v=>v.id===original.versionId)!
  const forgedMetadata=(report:M77Report)=>(async(url:RequestInfo|URL)=>String(url).includes('/versions/')?new Response(m77CanonicalJson(authoritativeVersion)):String(url).endsWith('/download')?new Response(report.html):new Response(m77CanonicalJson(report))) as typeof fetch
  globalThis.fetch=forgedMetadata(forged);await rejected(()=>fugitiveReportDownload(a,company,forged))
  // Outer captured review must match the independently saved decision, and cannot forge absence.
  const reviewedSource=historical.find(x=>x.family==='source'&&JSON.parse(x.snapshotJson).review!==null)!,changedReview=JSON.parse(reviewedSource.snapshotJson);changedReview.review.note='QA-UNSAVED-CAPTURED-REVIEW';const {decisionSha256:oldDecision,...decisionBody}=changedReview.review;changedReview.review.decisionSha256=m77Hash({companyId:company,...decisionBody});const wrongReview=forge(reviewedSource,changedReview)
  const replaceReport=(report:M77Report)=>{const copied=structuredClone(r);for(const w of copied.worksheets)w.reports=w.reports.map(x=>x.id===report.id?report:x);return copied}
  await rejected(()=>decodeFugitiveRegister(replaceReport(wrongReview),company));globalThis.fetch=forgedMetadata(wrongReview);await rejected(()=>fugitiveReportDownload(a,company,wrongReview))
  const removedReview=JSON.parse(reviewedSource.snapshotJson);removedReview.review=null;await rejected(()=>decodeFugitiveRegister(replaceReport(forge(reviewedSource,removedReview)),company))
  globalThis.fetch=actualFetch
  // Separate source creator expands the population contributor set.
  let v=r.worksheets.find(w=>w.assetId==='DISTRIBUTION-HVAC-A')!.versions.at(-1)!,oldEvent=v.activity.calculatorInput!.refills[0]
  v=await save(v,{label:'QA distinct source contributor'},201,'coverageReviewer');await review(v,'coverageReviewer',403);await review(v,'owner',403);await review(v,'sourceReviewer')
  r=await read();let pop=await savePop(r,r.population.versions.at(-1)!.activity.declaration);ct(pop.contributorIds.includes(f.users.coverageReviewer));await review(pop,'coverageReviewer',403)
  r=await read();const forgedRegister=structuredClone(r),fp=forgedRegister.population.versions.at(-1)!;fp.contributorIds=fp.contributorIds.filter(x=>x!==f.users.coverageReviewer);rehash(fp);forgedRegister.reconciliation=deriveM77Reconciliation(company,forgedRegister.coverageVersion,forgedRegister.worksheets.map(w=>w.versions.at(-1)!),fp,[],m77Hash);await rejected(()=>decodeFugitiveRegister(forgedRegister,company))
  const missing=structuredClone(r),mp=missing.population.versions.at(-1)!;mp.dependencies!.workpaperPins[0].version.id=crypto.randomUUID();const {dependencySha256,...body}=mp.dependencies!;mp.dependencies!.dependencySha256=m77Hash(body);rehash(mp);missing.reconciliation=deriveM77Reconciliation(company,missing.coverageVersion,missing.worksheets.map(w=>w.versions.at(-1)!),mp,[],m77Hash);await rejected(()=>decodeFugitiveRegister(missing,company))
  await review(pop,'populationReviewer');r=await read();ct(r.reconciliation.status==='reconciled_bounded_synthetic')
  // A null review in the old captured report stays null after later reviews.
  ct(r.population.reports.find(x=>x.id===pending.id)!.snapshotJson===pending.snapshotJson);ct(JSON.parse(r.population.reports.find(x=>x.id===pending.id)!.snapshotJson).review===null)
  // Permanent reservations survive removal from the effective annual activity.
  const zero='QA-EXPLICIT-ANNUAL-ZERO';v=await save(v,{calculatorInput:{...v.activity.calculatorInput!,refills:[],zero_activity_evidence:zero},evidenceStatements:[...v.activity.evidenceStatements,{reference:zero,issuer:'SYNTHETIC-CONTRACTOR',description:'Complete independent fictional all-provider record establishes no annual servicing or known releases.'}]});ct(v.calculation!.kg_co2e_exact==='0')
  let other=(await read()).worksheets.find(w=>w.assetId==='OFFICE-HVAC-A')!.versions.at(-1)!
  const reuse={calculatorInput:{...other.activity.calculatorInput!,refills:[oldEvent]},evidenceStatements:[...other.activity.evidenceStatements,{reference:oldEvent.reference,issuer:oldEvent.contractor,description:'Attempt superseded servicing identity reuse on a second physical device.'}]}
  await save(other,reuse,409);await save(other,{...reuse,calculatorInput:{...reuse.calculatorInput,refills:[{...oldEvent,id:'QA-NEW-ID-SAME-REFERENCE'}]}},409)
  // Exact maximum input and independently hand-derived output, then two linked losses counted once.
  const refill=other.activity.calculatorInput!.refills[0];other=await save(other,{calculatorInput:{...other.activity.calculatorInput!,refills:[{...refill,kg:'999999.999999'}]}});ct(other.calculation!.kg_co2e_exact==='1923999999.998076');ct(other.calculation!.kg_co2e_display==='1923999999.9981')
  const releaseRef='QA-TWO-KNOWN-LOSSES';other=await save(other,{calculatorInput:{...other.activity.calculatorInput!,refills:[{...refill,kg:'0.3'}],releases:[{id:'QA-LOSS-A',date:'2025-06-12',kg:'0.1',evidence:releaseRef,refill_id:refill.id,preceded_refill_verified:true},{id:'QA-LOSS-B',date:'2025-06-11',kg:'0.2',evidence:releaseRef+'-B',refill_id:refill.id,preceded_refill_verified:true}]},evidenceStatements:[...other.activity.evidenceStatements,...[releaseRef,releaseRef+'-B'].map(reference=>({reference,issuer:'SYNTHETIC-CONTRACTOR',description:'Independent fictional loss chronology ties this mass to the subsequent total consumed servicing refill.'}))]});ct(other.calculation!.kg_co2e_exact==='577.2');ct(other.calculation!.known_release_count===2)
  const c=other.activity.calculatorInput!;for(const patch of [{unit:'lb'},{opening_capacity:'10.0000001'},{declarations:{...c.declarations,complete_all_provider_service_records:false}},{releases:[{...c.releases[0],date:'2025-06-13'}]},{refills:[],releases:[],zero_activity_evidence:null},{refills:[{...c.refills[0],kg:0.3}]},{gas:'__proto__'}])await save(other,{calculatorInput:{...c,...patch}},422)
  // Independent discovery cannot omit, null or rename a retained unsupported device.
  r=await read();const dec=r.population.versions.at(-1)!.activity.declaration!,mobile={assetId:'QA-RETAINED-MOBILE',entityId:dec.assets[0].entityId,facilityId:null,equipment:'mobile_hvac',gas:'HFC-134a',capacityKg:'2',controlBasis:'owned_operational_control_full_year',explanation:'Fictional fleet inspection discovers a controlled unsupported mobile refrigerant device throughout the reporting year.',sourceId:null}
  pop=await savePop(r,{...dec,assets:[...dec.assets,mobile]});r=await read();ct(r.reconciliation.findings.some(x=>x.code==='unsupported_asset'&&x.assetId===mobile.assetId));await review(pop,'populationReviewer',422)
  await savePop(r,dec,422);await savePop(r,null,422);await savePop(r,{...pop.activity.declaration!,assets:pop.activity.declaration!.assets.map(x=>x.assetId===mobile.assetId?{...x,assetId:'QA-HIDE-BY-RENAME'}:x)},422)
  let sqlGuard=false;try{await s.runtime.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[f.users.owner]);await tx.query('select neuvetra.save_fugitive_version($1,$2,$3,$4::text::jsonb,$5::text::jsonb)',[company,pop.streamId,'population',m77CanonicalJson({...pop.activity,declaration:null,expectedVersionId:pop.id,expectedVersionSha256:pop.versionSha256,expectedDependencySha256:r.reconciliation.dependencySha256,correctionReason:'Attempt direct SQL disappearance of previously discovered devices.',idempotencyKey:crypto.randomUUID()}),m77CanonicalJson({...pop,review:null})])})}catch(e){sqlGuard=(e as any).code==='22023'&&(e as Error).message.includes('previously discovered')}ct(sqlGuard)
  // Missing physical facts remain retained and cannot produce a candidate result.
  const partial=await savePop(r,{...pop.activity.declaration!,assets:pop.activity.declaration!.assets.map(x=>x.assetId===mobile.assetId?{...x,gas:null,capacityKg:null,controlBasis:'unknown'}:x)});r=await read();ct(r.reconciliation.assets.some(x=>x.assetId===mobile.assetId&&x.gas===null));ct(r.reconciliation.status==='blocked');ct(partial.calculation===null)
  // Removing a captured review after it already existed cannot forge historical absence.
  const reviewed=historical.find(x=>x.family==='source'&&JSON.parse(x.snapshotJson).review!==null)!,absence=JSON.parse(reviewed.snapshotJson);absence.review=null;const altered=forge(reviewed,absence)
  await op.transaction(async tx=>{await tx.exec('alter table neuvetra.fugitive_reports disable trigger m77_immutable');await tx.exec('alter table neuvetra.fugitive_audit disable trigger m77_immutable');await tx.query('update neuvetra.fugitive_reports set payload=$1::text::jsonb,report_sha256=$2 where id=$3',[m77CanonicalJson(altered),altered.reportSha256,altered.id]);await tx.query('update neuvetra.fugitive_audit set record_sha256=$1 where record_id=$2',[altered.reportSha256,altered.id])})
  try{ct((await req('fugitive-sources')).status===503)}finally{await op.transaction(async tx=>{await tx.query('update neuvetra.fugitive_reports set payload=$1::text::jsonb,report_sha256=$2 where id=$3',[m77CanonicalJson(reviewed),reviewed.reportSha256,reviewed.id]);await tx.query('update neuvetra.fugitive_audit set record_sha256=$1 where record_id=$2',[reviewed.reportSha256,reviewed.id]);await tx.exec('alter table neuvetra.fugitive_reports enable trigger m77_immutable');await tx.exec('alter table neuvetra.fugitive_audit enable trigger m77_immutable')})}
  r=await read();for(const old of historical){const now=[...r.worksheets.flatMap(w=>w.reports),...r.population.reports].find(x=>x.id===old.id)!;ct(m77CanonicalJson(now)===m77CanonicalJson(old))}
  let denied=false;try{await s.runtime.exec('update neuvetra.fugitive_versions set version=version')}catch(e){denied=(e as any).code==='42501'}ct(denied)
  // Aborted actor requests fail before dispatch and after a late response.
  let net=0;const controller=new AbortController();controller.abort();globalThis.fetch=(async()=>{net++;return new Response('{}')}) as typeof fetch;await rejected(()=>fugitiveRegisterRequest({...a,signal:controller.signal},company));ct(net===0)
  const late=new AbortController();globalThis.fetch=(async()=>{net++;late.abort();return new Response(m77CanonicalJson(r))}) as typeof fetch;await rejected(()=>fugitiveRegisterRequest({...a,signal:late.signal},company))
  for(const p of files)ct(pins[p]===m77BytesHash(await Bun.file(p).text()))
  await Bun.write('evaluations/research-qa/m77-integrated-native-result.json',JSON.stringify({status:'independent_local_integrated_pass',database:name,createdAt:new Date().toISOString(),assertions,pins,hostedEvidence:false,auth:'fictional_local_adapter',coverage:'actual_routes_runtime_postgres_pinned_python_frontend_decoders_and_authorized_downloads',limitations:['physical_browser_preview_and_actual_actor_UI_transitions_owned_by_root','no_live_schema20_recovery_or_hosted_exercise','no_accounting_method_release_or_external_assurance']},null,2)+'\n')
 }finally{globalThis.fetch=actualFetch;await op.close();await s.close()}
},180000)
