import {test,expect} from 'bun:test'
import {readFile} from 'node:fs/promises'
import {createHash} from 'node:crypto'
import {hostedSourcePins,hostedDumpEnvironment,hostedOperatorUrl,parseOperatorJson,pinnedReceipt,REQUIRED_SOURCE_ROOTS} from '../../tools/staging/m78-hosted-database'
const project='icockcoguyadhryzydvl',url='postgres://postgres.'+project+':fictional%24%28only%29@aws-1-us-west-1.pooler.supabase.com:5432/postgres'
test('independent operator parser preserves exact UTF8 values and rejects semantic duplicate aliases',()=>{expect(parseOperatorJson('{"π":"雪","numbers":[1e2,-0,null,true]}',200)).toEqual({'π':'雪',numbers:[100,-0,null,true]});for(const bad of ['{"π":1,"\\u03c0":2}','{"outer":{"a":1,"\\u0061":2}}','{"a":"unterminated}','{"a":01}','{"a":NaN}','[true false]','{} trailing'])expect(()=>parseOperatorJson(bad,1000)).toThrow();expect(()=>parseOperatorJson('"雪"',4)).toThrow();expect(()=>parseOperatorJson('{}',256*1024*1024+1)).toThrow()})
test('independent dump transport uses explicit fictional credential and verify-full CA without PostgreSQL options inheritance',()=>{const env=hostedDumpEnvironment(url);expect(env.PGPASSWORD).toBe('fictional$(only)');expect(env.PGSSLMODE).toBe('verify-full');expect(env.PGUSER).toBe('postgres.'+project);expect(env.PGHOST).toBe('aws-1-us-west-1.pooler.supabase.com');expect(env.PGDATABASE).toBe('postgres');expect(Object.keys(env).sort()).toEqual(['PATH','SystemRoot','TEMP','TMP','PGHOST','PGPORT','PGDATABASE','PGUSER','PGPASSWORD','PGSSLMODE','PGSSLROOTCERT','PGCONNECT_TIMEOUT'].sort());for(const changed of [url.replace(project,'aaaaaaaaaaaaaaaaaaaa'),url.replace('postgres.'+project,'service_role'),url+'?options=-csearch_path%3Dpublic',url.replace('/postgres','/template0')])expect(()=>hostedOperatorUrl(changed)).toThrow()})
test('independent exact source map covers complete21migration corpus and credential transport dependencies',async()=>{const pins=await hostedSourcePins();expect(new Set(pins.map(x=>x.path)).size).toBe(pins.length);expect(pins.map(x=>x.path)).toEqual(pins.map(x=>x.path).sort());for(const path of [...REQUIRED_SOURCE_ROOTS,'packages/neuvetra-database/src/hosted.ts','packages/neuvetra-database/src/staging-tls.ts','tools/staging/m73-common.ts','tools/staging/m78-backup.ts'])expect(pins.some(x=>x.path===path)).toBe(true);const migrations=pins.filter(x=>x.path.includes('/migrations/'));expect(migrations).toHaveLength(21);expect(migrations.some(x=>x.path.endsWith('/0021_scope1_inventory.sql'))).toBe(true);for(const pin of pins){expect(pin.path.startsWith('../')||pin.path.startsWith('/')).toBe(false);expect(createHash('sha256').update(await readFile(pin.path)).digest('hex')).toBe(pin.sha256)}})
test('independent closed restore journal requires same archive, snapshot and absent-target identity',()=>{const at='2026-09-17T12:00:00.000Z',d='a'.repeat(64),start={status:'m78_hosted_restore_started',project,createdAt:at,archiveSha256:d,snapshotSha256:d,database:'m78_qa_review_fictional'},end={...start,status:'m78_hosted_snapshot_restored_locally'};const text=(a:unknown,b:unknown)=>JSON.stringify(a)+'\n'+JSON.stringify(b)+'\n';expect(pinnedReceipt(text(start,end),'restore')).toEqual(end);for(const change of [{archiveSha256:'b'.repeat(64)},{snapshotSha256:'b'.repeat(64)},{database:'m78_qa_different'},{project:'other'},{createdAt:'2026-09-17T11:59:59.999Z'}])expect(()=>pinnedReceipt(text(start,{...end,...change}),'restore')).toThrow();expect(()=>pinnedReceipt(JSON.stringify(end),'restore')).toThrow();expect(()=>pinnedReceipt(text(start,end)+JSON.stringify(end),'restore')).toThrow()})
