import {test,expect} from 'bun:test'
import {readFile} from 'node:fs/promises'
const source=await readFile('.superpowers/m78-interrupted-session-cleanup.ts','utf8'),sha=(s:string)=>new Bun.CryptoHasher('sha256').update(s).digest('hex');expect(sha(source)).toBe('4fa277e52e4c3a64016a4ea070a4b943eb1ecdb17e89a9d666fe70004006d78a');
const js=new Bun.Transpiler({loader:'ts'}).transformSync(source.split('\n').filter(l=>!l.startsWith('import ')).join('\n')),AsyncFunction=Object.getPrototypeOf(async()=>{}).constructor;
async function run(change:any={}){const observation=await readFile('.superpowers/m78-interrupted-sessions-observed.json','utf8'),selected=JSON.parse(observation).observations.map((o:any)=>o.sessions[0]);let rows=structuredClone(selected),deleted=0,committed=false,rolledBack=false,closed=false,connected=false,app=0;const files:any[]=[];const tx={exec:async(sql:string)=>{expect(sql).toBe('set transaction isolation level serializable')},query:async(sql:string,args:any[])=>{if(sql.includes('current_database'))return{rows:[{database:'postgres',actor:'postgres',isolation:'serializable'}]};if(sql.includes('pg_constraint'))return{rows:change.fks??['auth.refresh_tokens','auth.mfa_amr_claims'].map(child_table=>({child_table,parent_table:'auth.sessions',definition:'FOREIGN KEY (session_id) REFERENCES auth.sessions(id) ON DELETE CASCADE'}))};if(sql.includes('pg_trigger'))return{rows:change.triggers??[]};if(sql.startsWith('select id,user_id'))return{rows:rows.map(r=>({...r,...(change.metadata?{user_id:'other'}:{})}))};if(sql.startsWith('select session_id'))return{rows:sql.includes('refresh_tokens')?rows.map(r=>({session_id:r.id,count:'1'})):[]};if(sql.startsWith('delete ')){expect(sql).toBe('delete from auth.sessions where id=$1 and user_id=$2 and created_at=$3::timestamptz and updated_at=$4::timestamptz returning id');deleted++;if(change.microseconds||change.zeroAt===deleted)return{rows:[]};const row=rows.find(r=>r.id===args[0]&&r.user_id===args[1]&&r.created_at===args[2]&&r.updated_at===args[3]);rows=rows.filter(r=>r!==row);return{rows:row?[{id:row.id}]:[]}}throw Error('Unexpected SQL') }};const db={transaction:async(fn:any)=>{try{const v=await fn(tx);committed=true;return v}catch(e){rows=structuredClone(selected);rolledBack=true;throw e}},close:async()=>{closed=true}};let error:any=null;try{await new AsyncFunction('readFile','writeFile','connectOperator','hostedDumpEnvironment','inventory','Bun','console',js)(async()=>observation,async(path:string,text:string,opts:any)=>{expect(opts.flag).toBe('wx');if(change.intentExists&&path.includes('-intent'))throw Error('EEXIST');if(change.resultExists&&path.includes('-result'))throw Error('EEXIST');files.push({path,value:JSON.parse(text)})},async()=>{connected=true;return db},()=>{},async()=>({fixture:change.appChange?++app:1}),{CryptoHasher:Bun.CryptoHasher,stdin:{text:async()=>JSON.stringify({operatorId:'/root',operatorDatabaseUrl:'fixture'})}},{log:()=>{}})}catch(e){error=e}return{error,rows,deleted,committed,rolledBack,closed,connected,files}}
test('four exact millisecond fixtures commit once with explicit residual token limit',async()=>{const r=await run();expect(r.error).toBeNull();expect(r.deleted).toBe(4);expect(r.committed).toBe(true);expect(r.rows).toHaveLength(0);expect(r.files.at(-1).value.tokenUsability).toBe('not_verified');expect(r.files.at(-1).value.expiryVerified).toBe(false)})
test('guard or postcondition failure rolls back all deletions and emits no success',async()=>{for(const change of [{fks:[]},{triggers:[{tgname:'unexpected'}]},{metadata:true},{zeroAt:2},{appChange:true}]){const r=await run(change);expect(r.error).not.toBeNull();expect(r.rolledBack).toBe(true);expect(r.committed).toBe(false);expect(r.rows).toHaveLength(4);expect(r.files.some(f=>f.path.includes('-result'))).toBe(false);expect(r.closed).toBe(true)}})
test('exclusive intent prevents retry; failed postcommit receipt cannot falsely establish rollback',async()=>{const before=await run({intentExists:true});expect(before.connected).toBe(false);const after=await run({resultExists:true});expect(after.error).not.toBeNull();expect(after.committed).toBe(true);expect(after.rolledBack).toBe(false);expect(after.files.some(f=>f.path.includes('-result'))).toBe(false)})
test('submillisecond server timestamps cause candidate1 exact predicate refusal despite ISO guard match',async()=>{expect(new Date('2026-09-22T18:49:13.404321Z').toISOString()).toBe('2026-09-22T18:49:13.404Z');const r=await run({microseconds:true});expect(r.error).not.toBeNull();expect(r.rolledBack).toBe(true);expect(r.committed).toBe(false);expect(r.files.some(f=>f.path.includes('-intent'))).toBe(true)})
