import {readFile,writeFile} from 'node:fs/promises'
import {readM78ContinuationJournal,cleanM78ContinuationJournal} from '../../tools/staging/check-m78-continuation'
import {readM78Continuation2Diagnostics} from '../../tools/staging/check-m78-continuation2'
const sha=(v:Uint8Array|string)=>new Bun.CryptoHasher('sha256').update(v).digest('hex'),check=(v:unknown,m:string)=>{if(!v)throw Error(m)}
const observationPath='.superpowers/m78-platform-resume-observation.json',observationBytes=await readFile(observationPath),observation=JSON.parse(observationBytes.toString());check(observation.observedAt==='2026-09-22T19:57:27.603000+00:00','Exact resume observation')
const mainBytes=await readFile('.superpowers/m78-hosted-continuation2.jsonl'),diagnosticBytes=await readFile('.superpowers/m78-hosted-continuation2-diagnostics.jsonl');check(sha(mainBytes)==='3ce68c3fc87e37623326badb88d412f2db36daceacf43060c5849f287a358507'&&sha(diagnosticBytes)==='8ae88cd344ab1a6376b91a63581c57c9c61c381eb57141e1b6a11ca7647eae08','Exact interrupted bytes');const events=readM78ContinuationJournal(mainBytes.toString(),'8b90c706-1710-494d-b12d-02eef88eacb7'),diagnostics=readM78Continuation2Diagnostics(diagnosticBytes.toString());check(events.length===15&&events.at(-1)!.sha256==='9762c119f900df7be09426114f49e06c888af3ae3d3fba42dc81a7a00482c25e'&&diagnostics.length===30&&diagnostics.at(-1)!.sha256==='a7af0d5e04a71cc883b75aaf6921c6bb2de94049f00e3c21427a8736df2dd04e','Exact prefixes');check(events.every(e=>e.mode==='baseline'&&!e.kind.startsWith('post_'))&&events.every(e=>!['attempt_finished','baseline','logout_intent','logout_outcome','legacy_auth_intent'].includes(e.kind)),'Interrupted baseline no closure');let refused=false;try{cleanM78ContinuationJournal(events)}catch{refused=true}check(refused,'Interrupted journal refuses continuation');
const intents=diagnostics.filter(e=>e.kind==='request_intent'),headers=diagnostics.filter(e=>e.kind==='response_headers');check(intents.length===15&&headers.length===14&&intents.every((e,i)=>e.data.ordinal===i+1)&&headers.every((e,i)=>e.data.ordinal===i+1),'Exact interrupted request prefix');check(intents.filter(e=>e.data.method==='POST').length===4&&intents.filter(e=>e.data.method==='POST').every(e=>e.data.route==='auth:/auth/v1/token'),'Only auth POSTs observed');check(intents.at(-1)!.data.method==='GET'&&intents.at(-1)!.data.ordinal===15,'Unresolved read only');
const roles=['manager1','manager2','member','outsider'];const sessions=roles.map((role,i)=>{const intent=events.find(e=>e.kind==='auth_intent'&&e.data.role===role)!,outcome=events.find(e=>e.kind==='auth_outcome'&&e.data.role===role)!;check(outcome.data.status===200&&outcome.data.tokenObserved===true&&outcome.data.subjectMatched===true,'Known matching session');return {role,subjectMatchedExpectedRoster:true,subjectUuid:null,providerSessionId:null,subjectIdentitySource:'root must resolve admitted private roster; UUID not stored in these events',loginIntentAt:intent.createdAt,loginOutcomeAt:outcome.createdAt,diagnosticOrdinal:i+3,logoutConfirmed:false,currentProviderSessionState:'unobserved'}})
for(const[path,pin]of [['.superpowers/m78-hosted-journey.jsonl','d3301eb226c0cae4428c1e20cde4e2afdcf572b622e96d690cc8c262d6e44058'],['.superpowers/m78-hosted-continuation.jsonl','8525a8416b3e55f07d508c9a9ec17fc8ac0a4902e798534dc05e9f4df72d1a46']])check(sha(await readFile(path!))===pin,'Original journal preserved');
const result={status:'m78_platform_interruption_independently_reconciled_cleanup_unresolved',reviewerId:'/root/resume_release',createdAt:new Date().toISOString(),observationPath,observationSha256:sha(observationBytes),mainSha256:sha(mainBytes),diagnosticsSha256:sha(diagnosticBytes),mainEvents:15,diagnosticEvents:30,requestIntents:15,headerOutcomes:14,applicationPostIntents:0,knownAuthSessions:4,unresolvedKnownSessionClosures:4,unmatchedAuthIntents:0,legacySessionsObserved:0,sessions,lastReadIntent:intents.at(-1),cleanContinuationRefused:true,baselineCompleted:false,actualCleanupVerified:false,original72And24Preserved:true,causalClassification:'interrupted without terminal evidence; pause mechanism and platform interruption timing not independently resolved',rootReportedProcessAbsentAt:'2026-09-22T19:57:27Z',processAbsenceIndependentlyVerified:false,hostCalls:0,authCalls:0,databaseCalls:0};const out='evaluations/research-qa/m78-platform-interruption-result.json';await writeFile(out,JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({path:out,sha256:sha(await readFile(out)),status:result.status,sessions}))
