import {expect,test} from 'bun:test';
import {m78CanonicalJson as canonical} from '../../packages/neuvetra-database/src/m78-validation';
import {verifyExactAddedTypedRecords,verifyRecoveryObservationBinding,verifyRecoveryTransportEvidence} from './m78-continuation4-readonly-recovery-independent-review';
const sha=(value:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(value).digest('hex');
function serialize(profile:string,raw:{kind:string;data:any}[]){let previousSha256:string|null=null;const events=raw.map((entry,index)=>{const body={sequence:index+1,previousSha256,profile,kind:entry.kind,data:entry.data,createdAt:new Date(Date.UTC(2026,8,23)+index*1000).toISOString()},event={...body,sha256:sha(canonical(body))};previousSha256=event.sha256;return event});return{text:events.map(event=>JSON.stringify(event)).join('\n')+'\n',events}}
function fixture(){const roles=['manager1','manager2','member','outsider'],observationText='{"status":"synthetic-observation"}\n',currentSourceGateSha256='a'.repeat(64),mainRaw:{kind:string;data:any}[]=[{kind:'attempt_started',data:{applicationMethods:['GET'],currentSourceGateSha256}}];for(const role of roles)mainRaw.push({kind:'auth_intent',data:{role}},{kind:'auth_outcome',data:{role,status:200,subjectMatched:true,sessionCreationUncertain:false}});mainRaw.push({kind:'recovery_observed',data:{observationSha256:sha(observationText),applicationPostRequests:0,allMainSessionsClosed:true,allLegacySessionsClosed:true}});for(const role of roles)mainRaw.push({kind:'logout_intent',data:{role}},{kind:'logout_outcome',data:{role,status:204}});const diagnosticRaw:{kind:string;data:any}[]=[];let ordinal=0;const request=(method:string,route:string,status:number)=>{diagnosticRaw.push({kind:'request_intent',data:{ordinal:++ordinal,method,route,...(route==='auth:/auth/v1/logout'?{logoutScope:'local'}:{})}},{kind:'response_headers',data:{ordinal,status}})},scope='application:/workspace-api/workspace/:id/scope1-inventory';for(let index=0;index<4;index++)request('POST','auth:/auth/v1/token',200);request('GET',scope,403);request('GET',scope,401);request('GET',scope,200);request('GET',scope,200);for(const family of ['corporate-inventories','stationary-natural-gas','mobile-diesel','controlled-fleet','stationary-diesel','stationary-equipment','fugitive-sources'])request('GET',`application:/workspace-api/workspace/:id/${family}`,200);for(let index=0;index<5;index++)request('GET',`application:/workspace-api/workspace/:id/scope1-inventory/:id/reports/:id`,200);for(let index=0;index<4;index++)request('POST','auth:/auth/v1/token',200);for(let index=0;index<8;index++)request('POST','auth:/auth/v1/logout',204);mainRaw.push({kind:'attempt_finished',data:{status:'passed',requests:ordinal,applicationPostRequests:0,allCreatedAuthSessionsClosed:true,unknownAuthSessions:0,diagnosticsHealthy:true}});diagnosticRaw.push({kind:'phase_finished',data:{status:'passed',requests:ordinal,applicationPostRequests:0,allCreatedAuthSessionsClosed:true,unknownAuthSessions:0,diagnosticsHealthy:true}});const main=serialize('m78-continuation4-readonly-recovery-v1',mainRaw),diagnostics=serialize('m78-continuation4-readonly-recovery-diagnostic-v1',diagnosticRaw);return{main,diagnostics,observationText,currentSourceGateSha256,admission:{journalSha256:sha(main.text),journalHead:main.events.at(-1)!.sha256,diagnosticsSha256:sha(diagnostics.text),diagnosticsHead:diagnostics.events.at(-1)!.sha256}}}

test('transport evidence accepts one zero-write phase with paired GET/application and fixed auth POSTs',()=>{const value=fixture(),result=verifyRecoveryTransportEvidence(value.main.text,value.diagnostics.text,value.admission);expect(result.requests.size).toBe(32);expect(result.journal).toHaveLength(19);expect(result.diagnostics).toHaveLength(65)});

test('transport evidence rejects application POST, auth GET, request error, unknown session and success-only marker',()=>{const mutations=[
 (value:ReturnType<typeof fixture>)=>{const raw=value.diagnostics.events.map(({kind,data})=>({kind,data:structuredClone(data)}));raw.find(event=>event.kind==='request_intent'&&event.data.route.startsWith('application:'))!.data.method='POST';value.diagnostics=serialize('m78-continuation4-readonly-recovery-diagnostic-v1',raw);value.admission.diagnosticsSha256=sha(value.diagnostics.text);value.admission.diagnosticsHead=value.diagnostics.events.at(-1)!.sha256},
 (value:ReturnType<typeof fixture>)=>{const raw=value.diagnostics.events.map(({kind,data})=>({kind,data:structuredClone(data)}));raw.find(event=>event.kind==='request_intent'&&event.data.route.endsWith('/token'))!.data.method='GET';value.diagnostics=serialize('m78-continuation4-readonly-recovery-diagnostic-v1',raw);value.admission.diagnosticsSha256=sha(value.diagnostics.text);value.admission.diagnosticsHead=value.diagnostics.events.at(-1)!.sha256},
 (value:ReturnType<typeof fixture>)=>{const raw=value.diagnostics.events.map(({kind,data})=>({kind,data:structuredClone(data)}));const outcome=raw.find(event=>event.kind==='response_headers'&&event.data.ordinal===9)!;outcome.kind='request_error';value.diagnostics=serialize('m78-continuation4-readonly-recovery-diagnostic-v1',raw);value.admission.diagnosticsSha256=sha(value.diagnostics.text);value.admission.diagnosticsHead=value.diagnostics.events.at(-1)!.sha256},
 (value:ReturnType<typeof fixture>)=>{const raw=value.main.events.map(({kind,data})=>({kind,data:structuredClone(data)}));raw.at(-1)!.data.unknownAuthSessions=1;value.main=serialize('m78-continuation4-readonly-recovery-v1',raw);value.admission.journalSha256=sha(value.main.text);value.admission.journalHead=value.main.events.at(-1)!.sha256},
 (value:ReturnType<typeof fixture>)=>{const raw=value.main.events.map(({kind,data})=>({kind,data:structuredClone(data)}));raw.splice(2,0,{kind:'exercise_complete',data:{}});value.main=serialize('m78-continuation4-readonly-recovery-v1',raw);value.admission.journalSha256=sha(value.main.text);value.admission.journalHead=value.main.events.at(-1)!.sha256},
 (value:ReturnType<typeof fixture>)=>{const raw=value.diagnostics.events.map(({kind,data})=>({kind,data:structuredClone(data)}));raw.find(event=>event.kind==='response_headers'&&event.data.status===204)!.data.status=200;value.diagnostics=serialize('m78-continuation4-readonly-recovery-diagnostic-v1',raw);value.admission.diagnosticsSha256=sha(value.diagnostics.text);value.admission.diagnosticsHead=value.diagnostics.events.at(-1)!.sha256},
 (value:ReturnType<typeof fixture>)=>{const raw=value.main.events.map(({kind,data})=>({kind,data:structuredClone(data)}));raw.find(event=>event.kind==='auth_intent')!.data.role='member';value.main=serialize('m78-continuation4-readonly-recovery-v1',raw);value.admission.journalSha256=sha(value.main.text);value.admission.journalHead=value.main.events.at(-1)!.sha256},
 (value:ReturnType<typeof fixture>)=>{const raw=value.main.events.map(({kind,data})=>({kind,data:structuredClone(data)}));raw.at(-1)!.data.requests=31;value.main=serialize('m78-continuation4-readonly-recovery-v1',raw);value.admission.journalSha256=sha(value.main.text);value.admission.journalHead=value.main.events.at(-1)!.sha256},
 (value:ReturnType<typeof fixture>)=>{const raw=value.diagnostics.events.map(({kind,data})=>({kind,data:structuredClone(data)}));delete raw.find(event=>event.kind==='request_intent'&&event.data.route==='auth:/auth/v1/logout')!.data.logoutScope;value.diagnostics=serialize('m78-continuation4-readonly-recovery-diagnostic-v1',raw);value.admission.diagnosticsSha256=sha(value.diagnostics.text);value.admission.diagnosticsHead=value.diagnostics.events.at(-1)!.sha256},
 ];for(const mutate of mutations){const value=fixture();mutate(value);expect(()=>verifyRecoveryTransportEvidence(value.main.text,value.diagnostics.text,value.admission)).toThrow()}});

test('observation bytes and current source gate are bound into the recovery journal',()=>{const value=fixture(),transport=verifyRecoveryTransportEvidence(value.main.text,value.diagnostics.text,value.admission);expect(verifyRecoveryObservationBinding(transport.journal,value.observationText,value.currentSourceGateSha256).kind).toBe('recovery_observed');expect(()=>verifyRecoveryObservationBinding(transport.journal,value.observationText+' ',value.currentSourceGateSha256)).toThrow('journal observation/source binding');expect(()=>verifyRecoveryObservationBinding(transport.journal,value.observationText,'b'.repeat(64))).toThrow('journal observation/source binding')});

test('typed delta accepts exactly the 37 verified version/review/report identities and rejects missing, extra or changed identities',()=>{const identities=Array.from({length:37},(_,index)=>({id:`00000000-0000-4000-8000-${String(index+1).padStart(12,'0')}`,versionSha256:sha('version-'+index)})),before={records:[]},after={records:structuredClone(identities)};expect(verifyExactAddedTypedRecords(before,after,identities)).toHaveLength(37);expect(()=>verifyExactAddedTypedRecords(before,{records:after.records.slice(1)},identities)).toThrow('exactly37');expect(()=>verifyExactAddedTypedRecords(before,{records:[...after.records,{id:'00000000-0000-4000-8000-999999999999',versionSha256:sha('extra')}]},identities)).toThrow('exactly37');const changed=structuredClone(identities);changed[0]!.versionSha256=sha('changed');expect(()=>verifyExactAddedTypedRecords(before,after,changed)).toThrow('exactly37')});
