/** Static/offline review of the root-owned private recovery entry and PowerShell launcher. Never executes either helper. */
const digest=(value:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(value).digest('hex');
const check:(value:unknown,message:string)=>asserts value=(value,message)=>{if(!value)throw Error(message)};
const count=(text:string,needle:string)=>text.split(needle).length-1;
const ordered=(text:string,needles:string[])=>{let cursor=-1;for(const needle of needles){const next=text.indexOf(needle,cursor+1);check(next>cursor,'ordering '+needle);cursor=next}};
export type PrivateReviewPins={entrySha256:string;wrapperSha256:string;privateConfigSha256:string};

export function reviewM78ReadonlyPrivateSources(entry:string,wrapper:string,pins:PrivateReviewPins){
 check(digest(entry)===pins.entrySha256&&digest(wrapper)===pins.wrapperSha256,'exact helper pins');
 check(pins.privateConfigSha256==='39a9a9ce6820ad75956ffadb1f23f80359d41c72b18f52674271c44e542d0f8a','approved encrypted config pin');
 for(const forbidden of ['process.env','Bun.env','Deno.env','child_process','exec(','spawn(','console.error','access_token)',"console.log(body",'unlink(lockPath'])check(!entry.includes(forbidden),'entry secret/process boundary '+forbidden);
 check(count(entry,'console.log(')===2&&entry.includes("console.log(JSON.stringify({status:result.status,requests:result.requests,applicationPostRequests:result.applicationPostRequests,allCreatedAuthSessionsClosed:result.allCreatedAuthSessionsClosed,unknownAuthSessions:result.unknownAuthSessions}))")&&entry.includes("console.log(JSON.stringify({status:'failed',stage:'readonly_recovery_entry',successNotInferred:true}))"),'safe entry output only');
 check(entry.includes("gate.status==='m78_readonly_recovery_execution_admitted'")&&entry.includes("gate.applicationPostRequests===0")&&entry.includes("gate.workspaceId===input.roster.workspaceId"),'entry admission/workspace');
 check(entry.includes(`gate.privateConfigSha256==='${pins.privateConfigSha256}'`)&&entry.includes("sha(await readFile('C:/Users/nimab/Neuvetra/m63-runtime/recovery/m63-private-config.json.dpapi'))===gate.privateConfigSha256"),'entry encrypted config binding');
 ordered(entry,['const gateText=await readFile(gatePath','for(const p of gate.pins)','const runtime=JSON.parse','const sourceText=await readFile','await verifyM78ReadonlyRecoveryPreAuth(admission)','const expectedSubjects=Object.fromEntries(input.accounts.map(a=>[a.role,a.id]))','gate.privateConfigSha256','for(const p of Object.values(paths))','lock=await open(lockPath',"runM78Continuation4ReadonlyRecovery"]);
 check(entry.includes("runtime.status==='m78_get_route_deployed_runtime_verified'")&&entry.includes("runtime.ready.schemaVersion===21")&&entry.includes('age>=0&&age<15*60*1000')&&entry.includes('source.runtime.commit===runtime.commit&&source.runtime.deploymentId===runtime.deploymentId'),'entry runtime/source binding');
 check(entry.includes("open(lockPath,'wx',0o600)")&&entry.includes("lock.writeFile('{\"profile\":\"m78-readonly-recovery-exclusive-v1\"}\\n')")&&entry.includes('await lock.sync()')&&entry.includes('Keep the lock as a durable no-replay marker'),'durable exclusive lock');
 check(entry.includes('fetch:globalThis.fetch')&&!entry.includes('decoders:'),'production transport/decoders');
 check(entry.includes("AUTH+'/auth/v1/token?grant_type=password'")&&entry.includes("AUTH+'/auth/v1/logout?scope=local'")&&entry.includes("method:'POST'")&&entry.includes('authorization:session.authorization'),'fixed auth and local logout');
 check(entry.includes("runM72Journey({...input,mode:'baseline'}")&&entry.includes('load:async()=>null')&&entry.includes('save:async value=>{captured=value}')&&entry.includes("String(url)==='https://www.neuvetra.ai/ready'")&&entry.includes("body.status==='ready'&&body.schemaVersion===21&&body.legacyContainmentVerified===true")&&entry.includes('Response.json({...body,schemaVersion:14}')&&entry.includes("result.status==='passed'&&result.applicationPostRequests===0&&result.allCreatedAuthSessionsClosed===true")&&entry.includes('canonical(captured?.baseline)===canonical(expected)'),'read-only legacy preservation');
 check(entry.includes("check(Object.values(paths).includes(p as any))")&&entry.includes("exclusive?'wx':'a'")&&entry.includes('await f.sync()'),'exclusive bounded evidence IO');

 for(const forbidden of ['$env:','Write-Host','$errors.Result','Write-Output $errors','Remove-Item','Start-Process','Invoke-WebRequest','Invoke-RestMethod'])check(!wrapper.includes(forbidden),'wrapper secret/process boundary '+forbidden);
 check(wrapper.includes("[ValidatePattern('^[a-f0-9]{64}$')]")&&wrapper.includes("$gate=Read-Pinned @{path='.superpowers/m78-readonly-recovery-execution-admission.json';sha256=$AdmissionSha256}"),'safe admission input');
 check(wrapper.includes("$gate.workspaceId -cne '8b90c706-1710-494d-b12d-02eef88eacb7'")&&wrapper.includes("$runtime.autodeploy -ne $false")&&wrapper.includes("$runtime.ready.schemaVersion -ne 21")&&wrapper.includes("$age.TotalMinutes -ge 15")&&wrapper.includes("$source.status -cne 'm78_continuation4_readonly_recovery_source_admitted'"),'fixed workspace/runtime/source');
 check(wrapper.includes("StartsWith($workspace+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)")&&wrapper.includes("Get-FileHash -LiteralPath $resolved -Algorithm SHA256")&&wrapper.includes("Hash.ToLowerInvariant() -cne $pin.sha256"),'pinned contained paths');
 for(const required of ['.superpowers/m78-private-readonly-recovery.ps1','.superpowers/m78-readonly-recovery-entry.ts','tools/staging/check-m78-continuation4-readonly-recovery.ts'])check(wrapper.includes(required),'required source '+required);
 check(wrapper.includes(`$gate.privateConfigSha256 -cne '${pins.privateConfigSha256}'`)&&wrapper.includes("Get-FileHash -LiteralPath 'C:/Users/nimab/Neuvetra/m63-runtime/recovery/m63-private-config.json.dpapi'"),'wrapper encrypted config binding');
 ordered(wrapper,['$gate=Read-Pinned','foreach($pin in $gate.pins)','$runtime=Read-Pinned','$source=Read-Pinned','foreach($pin in $source.sourcePins)','execution exists','$gate.privateConfigSha256','Add-Type -AssemblyName System.Security','ProtectedData]::Unprotect','[Array]::Clear','$start=[Diagnostics.ProcessStartInfo]::new()','$process.StandardInput.Write','$data=$null','$process.WaitForExit()','Write-Output $output.Result']);
 check(wrapper.includes("$start.FileName='C:/Users/nimab/.bun/bin/bun.exe'")&&wrapper.includes("$start.ArgumentList.Add('run')")&&wrapper.includes(".superpowers/m78-readonly-recovery-entry.ts")&&wrapper.includes('$start.UseShellExecute=$false')&&wrapper.includes('$start.CreateNoWindow=$true'),'fixed hidden child entry');
 check(wrapper.includes('$start.RedirectStandardInput=$true')&&wrapper.includes('$start.RedirectStandardOutput=$true')&&wrapper.includes('$start.RedirectStandardError=$true')&&wrapper.includes('ConvertTo-Json -Depth 20 -Compress')&&wrapper.includes("Write-Output 'Read-only recovery failed; sensitive diagnostics withheld.'")&&wrapper.includes("Write-Output 'Read-only recovery unavailable; sensitive diagnostics withheld.'"),'private stdin and safe output');
 check(wrapper.includes("m78-continuation4-readonly-recovery.jsonl.lock")&&count(wrapper,'execution exists')===1,'exclusive evidence/lock preflight');
 return{status:'m78_readonly_private_helpers_source_review_passed',entrySha256:pins.entrySha256,wrapperSha256:pins.wrapperSha256,privateConfigSha256:pins.privateConfigSha256,actualExecution:false,dpapiUsed:false,networkUsed:false,databaseUsed:false,providerUsed:false};
}
