import {test,expect} from 'bun:test'
import {verifyDiagnostics,verifyBaseline} from './m78-continuation2-baseline-independent-review'
import {m78CanonicalJson as canonical} from '../../packages/neuvetra-database/src/m78-validation'
import {readFile} from 'node:fs/promises'
const sha=(v:string)=>new Bun.CryptoHasher('sha256').update(v).digest('hex')
const seed=()=>{const es:any[]=[{kind:'phase_started',data:{failedBaselineSha256:'8525a8416b3e55f07d508c9a9ec17fc8ac0a4902e798534dc05e9f4df72d1a46',failedBaselineHead:'e766f74b730bebf69849945407598c011f918b9a77b7ff9c3a5913cd6964f744',journal:'.superpowers/m78-hosted-continuation2.jsonl'}}];for(let i=1;i<=16;i++){es.push({kind:'request_intent',data:{ordinal:i,method:'POST',route:'auth:/auth/v1/'+(i<=8?'token':'logout')}});es.push({kind:'response_headers',data:{ordinal:i,status:i<=8?200:204,elapsedMs:1}})}es.push({kind:'phase_finished',data:{status:'passed',diagnosticsHealthy:true,applicationPostRequests:0,allCreatedAuthSessionsClosed:true}});return es}
const freeze=(es:any[])=>{let previous:string|null=null;const lines=es.map((e,i)=>{const body={sequence:i+1,previousSha256:previous,profile:'m78-continuation2-diagnostic-v1',mode:'baseline',...e,createdAt:new Date(100000+i).toISOString()},hash=sha(canonical(body));previous=hash;return JSON.stringify({...body,sha256:hash})});const text=lines.join('\n')+'\n';return {text,sha:sha(text),head:previous!}}
test('diagnostic success pairs every header with intent and exact parent/phase/auth closure',()=>{const f=freeze(seed());expect(verifyDiagnostics(f.text,f.sha,f.head,16).requests).toBe(16);expect(()=>verifyDiagnostics(f.text,'0'.repeat(64),f.head,16)).toThrow();expect(()=>verifyDiagnostics(f.text,f.sha,f.head,17)).toThrow()})
test('rehashing cannot admit missing headers, application write, wrong status, parent or extra phase',()=>{for(const mutate of [(e:any[])=>e.splice(2,1),(e:any[])=>e[1].data.route='application:/workspace/:id/scope1-inventory',(e:any[])=>e[2].data.status=503,(e:any[])=>e[0].data.failedBaselineSha256='0'.repeat(64),(e:any[])=>e.splice(1,0,{kind:'phase_started',data:{}}),(e:any[])=>e.at(-1).data.status='failed']){const es=seed();mutate(es);const f=freeze(es);expect(()=>verifyDiagnostics(f.text,f.sha,f.head,16)).toThrow()}})
test('preserved actual failed24 fixture is never admitted as a completed baseline',async()=>{const text=await readFile('tools/staging/m78-continuation2-failed-baseline.jsonl','utf8');await expect(verifyBaseline(text,'',{journalSha256:sha(text),journalHead:'e766f74b730bebf69849945407598c011f918b9a77b7ff9c3a5913cd6964f744'}as any)).rejects.toThrow()})
