import {readFile,writeFile} from 'node:fs/promises';
const sha=(b:Uint8Array)=>new Bun.CryptoHasher('sha256').update(b).digest('hex'),pin=async(path:string)=>({path,sha256:sha(await readFile(path))});
const report='evaluations/research-qa/m78-continuation3-independent-private-review.md',test='evaluations/research-qa/m78-continuation3-independent-private.test.ts',evaluator='evaluations/research-qa/m78-continuation3-independent-runtime.py',result='evaluations/research-qa/m78-continuation3-independent-runtime-result.json',receipt='evaluations/research-qa/m78-continuation3-independent-private-result.json';
const privateSources=await Promise.all(['.superpowers/m78-private-continuation3-journey.ps1','.superpowers/m78-continuation3-disposition-preflight.ts','.superpowers/m78-continuation3-refresh-runtime.py'].map(pin));const expected=['b36cbf0e1a0041daffe54e76ce2d44625270c0e4cacfa3e0a587dbebd17b8719','265bcc4812f8c1c2a454d3297c4171893cdd656bc2bd023419b1216196d87c3a','702fe3343ba67d3a43373ad0c106e66d770659430fef616d5697c212841a37da'];if(privateSources.some((p,i)=>p.sha256!==expected[i]))throw Error('Private source changed');
await writeFile(receipt,JSON.stringify({status:'m78_independent_continuation3_private_preparation_passed',reviewerId:'/root/m78_cont3_review',createdAt:new Date().toISOString(),privateSources,workflow:await pin('.github/workflows/verify.yml'),workflowDeltaAccepted:true,adapterSourceGate:await pin('evaluations/research-qa/m78-continuation3-independent-source-gate.json'),review:await pin(report),test:await pin(test),runtimeEvaluator:await pin(evaluator),runtimeResult:await pin(result),privateSourceChecks:{tests:2,assertions:74,preflightCases:9,powershellParse:'passed',wrapperExecuted:false,dpapiInvoked:false},runtimeCases:28,portableSubset:{tests:2,assertions:108,filtered:2},admission:'source_preparation_only',actualCleanupAccepted:false,actualDispositionAccepted:false,actualBaselineAccepted:false,hostedExecutionAccepted:false,actualDeploymentOrRestartVerified:false},null,2)+'\n',{flag:'wx'});
const files=[report,test,evaluator,result,receipt,'.github/workflows/verify.yml'],source_artifacts=await Promise.all(files.map(async path=>({...await pin(path),text:await readFile(path,'utf8')}))),snapshot='operations/agent-improvement/snapshots/M78-CONTINUATION3-PRIVATE-INDEPENDENT-REVIEW-01.json';
await writeFile(snapshot,JSON.stringify({task_id:'M78-CONTINUATION3-PRIVATE-INDEPENDENT-REVIEW-01',source_artifacts},null,2)+'\n',{flag:'wx'});
const run=JSON.parse(await readFile('operations/agent-improvement/run-template.json','utf8'));run.id='M78-CONTINUATION3-PRIVATE-INDEPENDENT-REVIEW-01';run.role='qa-lead';run.execution_context='/root/m78_cont3_review';run.prompt_sha256=(await pin('operations/agents/qa-lead.md')).sha256;run.artifacts=[await pin(snapshot)];run.source_artifacts=await Promise.all(files.map(pin));run.criteria=[{id:'PRIVATE_SOURCE_AND_PORTABLE_CI',status:'pass',evidence:[report,test,result,receipt],reason:'Exact source-only pass; actual cleanup/disposition/runtime/hosted acceptance remains separate.'}];run.compute.requested={model:'gpt-6-astra',effort:'high'};run.compute.observation_evidence=[report];run.notes=['Root accepted original adapter review before this new supplementary assignment. Root acceptance of supplementary reviewer artifacts remains pending. No private source changes or execution of wrapper/DPAPI/live observer.'];
await writeFile('operations/agent-improvement/runs/M78-CONTINUATION3-PRIVATE-INDEPENDENT-REVIEW-01.json',JSON.stringify(run,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({receipt:await pin(receipt),snapshot:await pin(snapshot),report:await pin(report),privateSources}));
