import {test,expect} from 'bun:test'
import {exerciseM78,m78FactualCorporateSuccessor,m78FictionalDiscovery} from '../../tools/staging/m78-hosted-plan'
import {m78CanonicalJson,validateM78InventorySave,deriveM78ProcessFindings} from '../../packages/neuvetra-database/src/m78-validation'
import {buildM78Dependencies} from '../../packages/neuvetra-database/src/m78-reconciliation'
import {createHash} from 'node:crypto'
const hash=(v:unknown)=>createHash('sha256').update(m78CanonicalJson(v)).digest('hex')
// Exact fictional register only; historical receipt provenance and privacy review are retained in m78-ci-portability.md.
const fixture=async()=>{const bytes=await Bun.file(new URL('./fixtures/m78-hosted-plan-fictional.json',import.meta.url)).arrayBuffer();expect(createHash('sha256').update(new Uint8Array(bytes)).digest('hex')).toBe('ee115a94cddaca62b0e13c459b1c32fd120e6de929ff8fca37c74957334c7028');return JSON.parse(new TextDecoder('utf8',{fatal:true}).decode(bytes))}
test('factual successor preserves all graph identities and changes only controlled inclusion facts',async()=>{const r=await fixture(),v=r.versionProofs.find((p:any)=>p.versionId===r.process.versions[0].id).proof.coverageVersion,s=m78FactualCorporateSuccessor(v);for(const key of ['entities','facilities','sources','coverageItems']as const)expect(s[key]).toEqual(v.snapshot[key]);expect(s.relationships.map((x:any)=>({...x,controlFacts:null,evidenceRefs:[]}))).toEqual(v.snapshot.relationships.map((x:any)=>({...x,controlFacts:null,evidenceRefs:[]})));expect(s.boundaryDecisions.map((x:any)=>({...x,disposition:null,reason:null,evidenceRefs:[]}))).toEqual(v.snapshot.boundaryDecisions.map((x:any)=>({...x,disposition:null,reason:null,evidenceRefs:[]})));expect(s.boundaryDecisions.every((b:any)=>b.disposition==='included_activity')).toBe(true)})
test('new process evidence covers every location/offsite and keeps opaque HFC sources exact',async()=>{const r=await fixture();r.process.versions=[];const a=m78FictionalDiscovery(r,hash);expect(a.locations).toHaveLength(5);expect(a.evidenceStatements).toHaveLength(10);expect(a.gasCoverage).toHaveLength(7);expect(a.assessments).toHaveLength(7);for(const row of a.gasCoverage)expect(row.locationRowIds).toEqual(a.locations.map(x=>x.rowId).sort());expect(a.gasCoverage.find(x=>x.gasGroup==='HFCs')!.sourceIds).toEqual(r.proof.sourceVersions.filter((x:any)=>x.family==='fugitive').map((x:any)=>x.version.activity.binding.sourceId).sort());expect(deriveM78ProcessFindings(a,r.coverageVersion)).toEqual([]);expect(a.evidenceStatements.every(x=>x.description.includes('SYNTHETIC SCENARIO'))).toBe(true)})
test('fixed recipe refuses prior saved process/inventory before any intent callback',async()=>{const r=await fixture();let writes=0;await expect(exerciseM78({root:'/workspace-api/workspace/'+r.companyId,accounts:[],scope1:async()=>r,post:async()=>{writes++}})).rejects.toThrow();expect(writes).toBe(0)})
test('first blocked inventory input validates exact current coverage/dependencies with null predecessor',async()=>{const r=await fixture();r.process.versions=[];r.inventory.versions=[];r.proof.process=null;r.reconciliation.status='blocked';r.reconciliation.totals=null;r.dependencies=buildM78Dependencies(r.proof,'inventory',hash);let seen=false;await expect(exerciseM78({root:'/workspace-api/workspace/'+r.companyId,accounts:[],scope1:async()=>r,post:async(name,path,role,input)=>{const a=validateM78InventorySave(input);expect(name).toBe('m78_initial_blocked_inventory');expect(path).toBe('/workspace-api/workspace/'+r.companyId+'/scope1-inventory');expect(role).toBe('manager1');expect(a.expectedVersionId).toBeNull();expect(a.expectedDependencySha256).toBe(r.dependencies.dependencySha256);expect(a.binding.coverageVersionId).toBe(r.coverageVersion.id);seen=true;throw Error('Stop pure recipe before any write.')}})).rejects.toThrow();expect(seen).toBe(true)})
test('changed source shape or previously retained process cannot be replaced by negative evidence',async()=>{const r=await fixture();expect(()=>m78FictionalDiscovery(r,hash)).toThrow();r.process.versions=[];r.proof.sourceVersions.pop();expect(()=>m78FictionalDiscovery(r,hash)).toThrow();const v=r.versionProofs[0].proof.coverageVersion;v.snapshot.relationships[0].ownershipPercent='50';expect(()=>m78FactualCorporateSuccessor(v)).toThrow()})
