import {M78_CONTINUATION4_PRIOR_FAILURE,M78_CONTINUATION4_PATHS} from '../../tools/staging/check-m78-continuation4'
import {M78_CONTINUATION3_INTERRUPTION} from '../../tools/staging/check-m78-continuation3'
import {test,expect} from 'bun:test'
import {verifyDiagnostics,verifyBaseline,verifyCI,REQUIRED_CHECKS,DISPOSITION_PIN} from './m78-continuation4-baseline-independent-review'
import {m78CanonicalJson as canonical} from '../../packages/neuvetra-database/src/m78-validation'
import {readFile} from 'node:fs/promises'
const sha=(v:string)=>new Bun.CryptoHasher('sha256').update(v).digest('hex')
const seed=()=>{const es:any[]=[{kind:'phase_started',data:{priorFailure:{...M78_CONTINUATION4_PRIOR_FAILURE,main:M78_CONTINUATION4_PATHS.failedMain,diagnostics:M78_CONTINUATION4_PATHS.failedDiagnostics,review:M78_CONTINUATION4_PATHS.failedReview},transport:{runtime:'bun-fetch',pooling:'disabled',keepalive:false,retries:0},journal:'.superpowers/m78-hosted-continuation4.jsonl',interruption:{...M78_CONTINUATION3_INTERRUPTION},disposition:{...DISPOSITION_PIN}}}];for(let i=1;i<=16;i++){es.push({kind:'request_intent',data:{ordinal:i,method:'POST',route:'auth:/auth/v1/'+(i<=8?'token':'logout')}});es.push({kind:'response_headers',data:{ordinal:i,status:i<=8?200:204,elapsedMs:1}})}es.push({kind:'phase_finished',data:{status:'passed',diagnosticsHealthy:true,paused:false,applicationPostRequests:0,allCreatedAuthSessionsClosed:true}});return es}
const freeze=(es:any[])=>{let previous:string|null=null;const lines=es.map((e,i)=>{const body={sequence:i+1,previousSha256:previous,profile:'m78-continuation4-diagnostic-v1',mode:'baseline',...e,createdAt:new Date(100000+i).toISOString()},hash=sha(canonical(body));previous=hash;return JSON.stringify({...body,sha256:hash})});const text=lines.join('\n')+'\n';return {text,sha:sha(text),head:previous!}}
test('diagnostic success pairs every header with intent and exact parent/phase/auth closure',()=>{const f=freeze(seed());expect(verifyDiagnostics(f.text,f.sha,f.head,16).requests).toBe(16);expect(()=>verifyDiagnostics(f.text,'0'.repeat(64),f.head,16)).toThrow();expect(()=>verifyDiagnostics(f.text,f.sha,f.head,17)).toThrow()})
test('rehashing cannot admit missing headers, application write, wrong status, parent or extra phase',()=>{for(const mutate of [(e:any[])=>e.splice(2,1),(e:any[])=>e[1].data.route='application:/workspace/:id/scope1-inventory',(e:any[])=>e[2].data.status=503,(e:any[])=>e[0].data.priorFailure.mainSha256='0'.repeat(64),(e:any[])=>e.splice(1,0,{kind:'phase_started',data:{}}),(e:any[])=>e.at(-1).data.status='failed']){const es=seed();mutate(es);const f=freeze(es);expect(()=>verifyDiagnostics(f.text,f.sha,f.head,16)).toThrow()}})
test('preserved actual failed24 fixture is never admitted as a completed baseline',async()=>{const text=await readFile('tools/staging/m78-continuation2-failed-baseline.jsonl','utf8');await expect(verifyBaseline(text,'',{journalSha256:sha(text),journalHead:'e766f74b730bebf69849945407598c011f918b9a77b7ff9c3a5913cd6964f744'}as any)).rejects.toThrow()})

test('continuation3 refuses changed interruption/disposition, paused or unterminated diagnostics',()=>{for(const mutate of [(e:any[])=>e[0].data.interruption.mainHead='0'.repeat(64),(e:any[])=>e[0].data.disposition.sha256='0'.repeat(64),(e:any[])=>e[0].data.disposition.path='wrong.json',(e:any[])=>e.at(-1).data.paused=true,(e:any[])=>delete e.at(-1).data.paused,(e:any[])=>e.pop()]){const es=seed();mutate(es);const f=freeze(es);expect(()=>verifyDiagnostics(f.text,f.sha,f.head,16)).toThrow()}})
test('exact tooling CI requires all six distinct completed check names at supplied commit',()=>{const commit='a'.repeat(40),ci=()=>({sha:commit,pr_head:commit,checks:REQUIRED_CHECKS.map(name=>({name,status:'completed',conclusion:'success'}))});expect(()=>verifyCI(ci(),commit)).not.toThrow();for(const mutate of [(c:any)=>c.sha='b'.repeat(40),(c:any)=>c.pr_head='b'.repeat(40),(c:any)=>c.checks[0].status='in_progress',(c:any)=>c.checks[0].conclusion='failure',(c:any)=>c.checks[0].name=c.checks[1].name,(c:any)=>c.checks.pop()]){const c=ci();mutate(c);expect(()=>verifyCI(c,commit)).toThrow()}})
test('preserved interrupted15 is rejected even with its exact supplied hash and head',async()=>{const text=await readFile('tools/staging/m78-continuation3-interrupted-main.jsonl','utf8');await expect(verifyBaseline(text,'',{journalSha256:sha(text),journalHead:M78_CONTINUATION3_INTERRUPTION.mainHead}as any)).rejects.toThrow()})

test('continuation4 rejects altered transport and the exact closed failed3 journal',async()=>{for(const mutate of [(e:any[])=>e[0].data.transport.keepalive=true,(e:any[])=>e[0].data.transport.retries=1,(e:any[])=>e[0].data.priorFailure.review='wrong.json']){const es=seed();mutate(es);const f=freeze(es);expect(()=>verifyDiagnostics(f.text,f.sha,f.head,16)).toThrow()}const text=await readFile(M78_CONTINUATION4_PATHS.failedMain,'utf8');await expect(verifyBaseline(text,'',{journalSha256:sha(text),journalHead:M78_CONTINUATION4_PRIOR_FAILURE.mainHead}as any)).rejects.toThrow()})
