import {readM78Continuation4Diagnostics,M78_CONTINUATION4_PATHS,M78_CONTINUATION4_PRIOR_FAILURE,verifyM78Continuation4PriorFailure} from '../../tools/staging/check-m78-continuation4';
/** Offline completed-baseline review only: never authenticates or calls a host/database. */
import {readFile,writeFile} from 'node:fs/promises';
import {readM78ContinuationJournal,cleanM78ContinuationJournal,readM78Prior} from '../../tools/staging/check-m78-continuation';
import {assertM78ContinuationBaseline} from '../../tools/staging/m78-continuation-plan';
import {preservesM77History} from '../../tools/staging/check-m77-hosted';
import {decodeScope1Register} from '../../apps/site-web/src/lib/m78-api';
import {m78Continuation4SourcePins,M78_CONTINUATION4_EVIDENCE_PINS} from '../../tools/staging/m78-continuation4-source-pins';
import {M78_CONTINUATION3_INTERRUPTION,verifyM78Continuation3Disposition} from '../../tools/staging/check-m78-continuation3';
import {m78CanonicalJson as canonical} from '../../packages/neuvetra-database/src/m78-validation';
const sha=(b:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(b).digest('hex'),check=(v:unknown,m:string)=>{if(!v)throw Error(m)},same=(a:unknown,b:unknown)=>canonical(a)===canonical(b);
export const DISPOSITION_PIN={path:'.superpowers/m78-continuation3-cleanup-disposition.json',sha256:'9ce4d682156c32771f8bb6fe8dfa249cf0060b39a8ce90c6ea3daf83c209342f'};
export const REQUIRED_CHECKS=['Typecheck, lint, unit tests and web builds','Offline research catalog tests','Native PostgreSQL worksheet and tenant regression','Dedicated staging image and offline runtime smoke','GHG calculation specifications and engine','Role routing and evidence records'];
export function verifyCI(ci:any,commit:string){check(/^[a-f0-9]{40}$/.test(commit)&&ci.sha===commit&&ci.pr_head===commit&&Array.isArray(ci.checks)&&ci.checks.length===6&&same(ci.checks.map((c:any)=>c.name).sort(),[...REQUIRED_CHECKS].sort())&&ci.checks.every((c:any)=>c.status==='completed'&&c.conclusion==='success'),'Exact six completed tooling checks');}
export interface ClosedBaselineAdmission {journalSha256:string;journalHead:string;diagnosticsSha256:string;diagnosticsHead:string;gatePath:string;gateSha256:string;toolingCommit:string}
export async function verifyBaseline(text:string,diagnosticText:string,admission:ClosedBaselineAdmission){
 const expectedSha=admission.journalSha256,expectedHead=admission.journalHead;
 check(sha(text)===expectedSha,'Exact closed journal hash');const raw=JSON.parse(text.split('\n')[0]!),company=raw.workspaceId,events=readM78ContinuationJournal(text,company);cleanM78ContinuationJournal(events);
 const finish=events.at(-1)!;check(finish.kind==='attempt_finished'&&finish.mode==='baseline'&&finish.sha256===expectedHead&&finish.data.status==='passed'&&finish.data.applicationPostRequests===0&&finish.data.unknownAuthSessions===0&&finish.data.allCreatedAuthSessionsClosed===true,'Closed successful baseline required');
 check(events.every(e=>e.mode==='baseline'&&!e.kind.startsWith('post_'))&&events.filter(e=>e.kind==='baseline').length===1&&events.filter(e=>e.kind==='attempt_started').length===1,'Single zero-write baseline');
 const gatePath=admission.gatePath;check(/^\.superpowers\/m78-continuation4-[a-z0-9-]*gate\.json$/.test(gatePath),'Fixed continuation4 gate namespace');const gb=await readFile(gatePath);check(sha(gb)===admission.gateSha256,'Immutable gate');const gate=JSON.parse(gb.toString());check(same(events.find(e=>e.kind==='attempt_started')!.data.gate,gate.gate),'Journal gate');
 for(const pin of Object.values(gate.artifacts) as {path:string;sha256:string}[])check(sha(await readFile(pin.path))===pin.sha256,'Gate artifact '+pin.path);
 const pins=await m78Continuation4SourcePins(),receipt=JSON.parse(await readFile(gate.artifacts.independentReview.path,'utf8'));check(pins.length===173&&same(pins,gate.sourcePins)&&same(pins,receipt.sourcePins)&&same(receipt.evidencePins,M78_CONTINUATION4_EVIDENCE_PINS),'Exact full source/evidence closure');for(const pin of M78_CONTINUATION4_EVIDENCE_PINS)check(sha(await readFile(pin.path))===pin.sha256,'Original evidence');
 check(same(gate.artifacts.interruptionDisposition,DISPOSITION_PIN),'Accepted actual cleanup disposition');await verifyM78Continuation3Disposition({roster:{workspaceId:company},interruptionDisposition:DISPOSITION_PIN}as any,{read:async path=>{try{return await readFile(path,'utf8')}catch{return null}}});
 const actualFailedMain=await readFile(M78_CONTINUATION4_PATHS.actualFailedMain,'utf8'),actualFailedDiagnostics=await readFile(M78_CONTINUATION4_PATHS.actualFailedDiagnostics,'utf8');check(actualFailedMain===await readFile(M78_CONTINUATION4_PATHS.failedMain,'utf8')&&actualFailedDiagnostics===await readFile(M78_CONTINUATION4_PATHS.failedDiagnostics,'utf8'),'Exact actual/public prior failure');verifyM78Continuation4PriorFailure(actualFailedMain,actualFailedDiagnostics,await readFile(M78_CONTINUATION4_PATHS.failedReview,'utf8'),company,{interruptionDisposition:DISPOSITION_PIN}as any);
 const runtime=JSON.parse(await readFile(gate.artifacts.runtime.path,'utf8')),ci=JSON.parse(await readFile(gate.artifacts.ciChecks.path,'utf8')),commit='59cda7a62d8dcc6b554c92372e3b032577e410c9';check(runtime.status==='m78_runtime_verified'&&runtime.schemaVersion===21&&runtime.commit===commit&&runtime.deploymentId==='0f2e99f3-67ef-4f4c-b3c3-a39c62eabc78'&&runtime.imageDigest==='sha256:fe46a0e354252026f2bcbf6672e10ec550e52a56f064ab3e75a8af17625749c9'&&runtime.httpStatus===200,'Accepted runtime');verifyCI(ci,admission.toolingCommit);
 check(gate.profile==='m78-root-continuation4-journey-gate-v1'&&gate.mode==='baseline'&&receipt.status==='m78_independent_continuation4_preparation_passed'&&gate.gate.reviewedApplicationCommit===commit,'Correct outer gate and source receipt');
 const age=Date.parse(events.find(e=>e.kind==='attempt_started')!.createdAt)-Date.parse(runtime.observedAt);check(age>=0&&age<=15*60*1000,'Runtime fresh at admission');
 const diag=verifyDiagnostics(diagnosticText,admission.diagnosticsSha256,admission.diagnosticsHead,finish.data.requests);check(Date.parse(diag.startedAt)<=Date.parse(events[0]!.createdAt)&&Date.parse(diag.finishedAt)>=Date.parse(finish.createdAt),'Diagnostic phase brackets actual main journal');
 for(const role of ['manager1','manager2','member','outsider'])check(events.filter(e=>e.kind==='auth_outcome'&&e.data.role===role&&e.data.status===200&&e.data.tokenObserved===true&&e.data.subjectMatched===true).length===1&&events.filter(e=>e.kind==='logout_outcome'&&e.data.role===role&&e.data.status===204).length===1,'Exact main session closure');check(events.filter(e=>e.kind==='legacy_auth_outcome'&&e.data.action==='login'&&e.data.status===200).length===4&&events.filter(e=>e.kind==='legacy_auth_outcome'&&e.data.action==='logout'&&e.data.status===204).length===4,'Exact legacy session closure');
 const ready=events.find(e=>e.kind==='actual_readiness')!.data;check(ready.schemaVersion===21&&ready.applicationCommitAttestation===commit&&ready.sourceGate===gate.gate.independentReviewSha256&&ready.migrationSha256===gate.gate.migrationSha256,'Actual journal readiness');
 const baseline=events.find(e=>e.kind==='baseline')!.data,prior=await readM78Prior(company),decoded=await decodeScope1Register(baseline.scope1,company);assertM78ContinuationBaseline(decoded);check(same(decoded,baseline.scope1)&&same(decoded.inventory.versions[0],prior.observation.version.payload),'Retained exact committed version');let downloadCount=0;for(const old of [prior.previous,prior.failed]){preservesM77History(old.registers,baseline.registers);for(const family of Object.keys(old.downloads))for(const[key,value]of Object.entries(old.downloads[family])){check(same(value,baseline.downloads[family]?.[key]),'Old exact download');downloadCount++}}check(same(baseline.legacy,prior.old.legacy)&&same(baseline.legacy,prior.failed.legacy),'Exact legacy state');
 const v=decoded.inventory.versions[0]!,expected=canonical({...v,review:null}),entries:Record<string,{sha256:string;byteLength:number}>={['version_'+v.id]:{sha256:sha(expected),byteLength:Buffer.byteLength(expected)}};for(const s of v.statements)entries['statement_'+s.id]={sha256:sha(s.text),byteLength:Buffer.byteLength(s.text)};check(same(entries,baseline.m78bytes),'Exact retained version export/statement bytes');
 return {status:'m78_independent_continuation4_hosted_baseline_passed',createdAt:new Date().toISOString(),reviewerId:'/root',journalPath:'.superpowers/m78-hosted-continuation4.jsonl',prefixSha256:expectedSha,headSha256:expectedHead,verifiedPrefixEvents:events.length,verifiedPrefixBytes:Buffer.byteLength(text),completedAt:finish.createdAt,requests:finish.data.requests,applicationPostRequests:0,allCreatedAuthSessionsClosed:true,unknownAuthSessions:0,mainLogins:events.filter(e=>e.kind==='auth_outcome').length,mainLogouts:events.filter(e=>e.kind==='logout_outcome').length,legacyAuthOutcomes:events.filter(e=>e.kind==='legacy_auth_outcome').length,sourcePinCount:173,historicalEvidencePinCount:9,interruptionDisposition:DISPOSITION_PIN,applicationCommit:commit,schemaVersion:21,gatePath,gateSha256:sha(gb),oldHistoryAndDownloadsPreserved:true,priorDownloadComparisons:downloadCount,retainedInitialInventoryId:v.id,retainedInitialInventorySha256:v.versionSha256,m78ExactDownloadCount:Object.keys(entries).length,actualDecoderPassed:true,diagnosticSha256:admission.diagnosticsSha256,diagnosticHead:admission.diagnosticsHead,diagnosticEvents:diag.events,diagnosticRequests:diag.requests,diagnosticsVerifyBodies:false,toolingCommit:admission.toolingCommit,qaNetworkUsed:false,qaDatabaseUsed:false,hostedExerciseAccepted:false,fullLifecycleVerified:false};
}
export function verifyDiagnostics(text:string,expectedSha:string,expectedHead:string,expectedRequests:number){
 check(sha(text)===expectedSha,'Exact diagnostic hash');const es=readM78Continuation4Diagnostics(text),first=es[0]!,last=es.at(-1)!;check(first.kind==='phase_started'&&same(first.data.priorFailure,{...M78_CONTINUATION4_PRIOR_FAILURE,main:M78_CONTINUATION4_PATHS.failedMain,diagnostics:M78_CONTINUATION4_PATHS.failedDiagnostics,review:M78_CONTINUATION4_PATHS.failedReview})&&same(first.data.transport,{runtime:'bun-fetch',pooling:'disabled',keepalive:false,retries:0})&&same(first.data.interruption,M78_CONTINUATION3_INTERRUPTION)&&same(first.data.disposition,DISPOSITION_PIN)&&first.data.journal==='.superpowers/m78-hosted-continuation4.jsonl','Exact diagnostic parent');check(last.sha256===expectedHead&&last.kind==='phase_finished'&&last.data.status==='passed'&&last.data.diagnosticsHealthy===true&&last.data.paused===false&&last.data.applicationPostRequests===0&&last.data.allCreatedAuthSessionsClosed===true,'Diagnostic passed closure');
 const requests=new Map<number,any>();let ordinal=0,lastTime=0;for(const e of es){const timestamp=Date.parse(e.createdAt);check(Number.isFinite(timestamp)&&timestamp>=lastTime&&e.mode==='baseline','Diagnostic chronology/mode');lastTime=timestamp;if(e.kind==='request_intent'){check(e.data.ordinal===++ordinal&&['GET','POST'].includes(e.data.method),'Diagnostic request order');check(e.data.method!=='POST'||['auth:/auth/v1/token','auth:/auth/v1/logout'].includes(e.data.route),'No diagnostic application POST');requests.set(ordinal,{...e.data,outcome:null})}else if(e.kind==='response_headers'){const r=requests.get(e.data.ordinal);check(r&&r.outcome===null&&Number.isInteger(e.data.status)&&[200,204,401,403].includes(e.data.status)&&Number.isFinite(e.data.elapsedMs)&&e.data.elapsedMs>=0,'Paired successful/expected-denial headers');if(r.route==='auth:/auth/v1/token')check(e.data.status===200,'Login headers');if(r.route==='auth:/auth/v1/logout')check(e.data.status===204,'Logout headers');r.outcome=e.data}else check((e===first&&e.kind==='phase_started')||(e===last&&e.kind==='phase_finished'),'No errors or extra diagnostic phase')}
 check(requests.size===expectedRequests&&[...requests.values()].every(r=>r.outcome!==null),'Complete paired requests');check([...requests.values()].filter(r=>r.route==='auth:/auth/v1/token').length===8&&[...requests.values()].filter(r=>r.route==='auth:/auth/v1/logout').length===8,'All main and legacy diagnostic sessions');return {events:es.length,requests:requests.size,startedAt:first.createdAt,finishedAt:last.createdAt};
}
if(import.meta.main){check(process.argv.length===3,'Explicit closed admission file required');const admission=JSON.parse(await readFile(process.argv[2]!,'utf8'))as ClosedBaselineAdmission;const result=await verifyBaseline(await readFile('.superpowers/m78-hosted-continuation4.jsonl','utf8'),await readFile('.superpowers/m78-hosted-continuation4-diagnostics.jsonl','utf8'),admission);const out='evaluations/research-qa/m78-continuation4-baseline-independent-result.json';await writeFile(out,JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({path:out,sha256:sha(await readFile(out)),...result}))}
