/** Explicit root-approved fictional sources/clones. Read-only; no host or credentials. */
import {createPostgresConnection,HostedWorkspaceDatabase} from '../../packages/neuvetra-database/src/index'
import {inventory,content,sameExactInventory,sameUpgradeInventory,sameContent,PATH_FUNCTIONS,hash} from '../../tools/staging/m78-inventory'
import {createM73Authority} from '../../apps/site-api/src/calculation/m73-authority'
import {createM74Authority} from '../../apps/site-api/src/calculation/m74-authority'
import {createM76DieselAuthority} from '../../apps/site-api/src/calculation/m76-authority'
import {createM77Authority} from '../../apps/site-api/src/calculation/m77-authority'
import {M78_REVIEWED_POLICY} from '../../packages/neuvetra-database/src/m78-policy'
import {createM78Routes} from '../../apps/site-api/src/workspace/m78-routes'
import {decodeScope1Register,decodeScope1Version,decodeScope1Report} from '../../apps/site-web/src/lib/m78-api'
import {createHash} from 'node:crypto'
const names=['m77_ops_failed_state20','m78_ops_upgrade_1789620512810','m78_author_native_1789620106488','m78_ops_recovery_1789620512810'] as const
const check=(v:unknown,m:string)=>{if(!v)throw Error(m)},sha=(b:string|Uint8Array)=>createHash('sha256').update(b).digest('hex')
const receiptPath='.superpowers/m78-operators-1789620512810/result.json',receiptBytes=new Uint8Array(await Bun.file(receiptPath).arrayBuffer()),receipt=JSON.parse(new TextDecoder().decode(receiptBytes))
check(receipt.status==='m78_local_operator_rehearsal_passed'&&receipt.migrationSha256==='546673470c33da80dc1e0b377646fa09b921e1231535da7c1af43ec866d48736'&&receipt.clone20===names[1]&&receipt.clone21===names[3],'Exact completed local rehearsal required')
const connections=names.map(n=>createPostgresConnection('postgres://supabase_admin@127.0.0.1:55472/'+n,{tls:false,maxConnections:1})),runtime=createPostgresConnection('postgres://neuvetra_runtime@127.0.0.1:55472/'+names[3],{tls:false,maxConnections:1})
try{
 const snapshots=[]
 for(let i=0;i<connections.length;i++)snapshots.push(await connections[i]!.transaction(async tx=>{await tx.exec('set transaction isolation level repeatable read read only');return {inventory:await inventory(tx),content:await content(tx,i===0?20:21)}}))
 const [old,upgraded,source,restored]=snapshots as [typeof snapshots[number],typeof snapshots[number],typeof snapshots[number],typeof snapshots[number]]
 sameUpgradeInventory(old.inventory,upgraded.inventory);sameContent(old.content,upgraded.content,true);sameExactInventory(source.inventory,restored.inventory);sameContent(source.content,restored.content)
 // Explicitly inspect preserved original row multiplicities/catalog identities and six exact function deltas.
 for(const t of old.inventory.tables){const u=upgraded.inventory.tables.find(x=>x.name===t.name)!;check(t.name==='schema_migrations'||JSON.stringify(t)===JSON.stringify(u),'Old rows/multiplicities changed')}
 for(const k of ['roles','memberships','defaultAcls','dependencies'] as const)check(JSON.stringify(old.inventory[k])===JSON.stringify(upgraded.inventory[k])&&JSON.stringify(source.inventory[k])===JSON.stringify(restored.inventory[k]),'Original role/default/dependency bytes differ')
 check(JSON.stringify(old.inventory.tableObjects)===JSON.stringify(upgraded.inventory.tableObjects.filter(o=>old.inventory.tables.some(t=>t.name===o.table_name))),'Old column/constraint/index/policy/trigger definitions differ')
 let explicitFunctionDeltas=0
 for(const f of old.inventory.functions){const u=upgraded.inventory.functions.find(x=>x.signature===f.signature)!;if(PATH_FUNCTIONS.includes(f.signature)){check(u.definition.replace(" SET search_path TO 'pg_catalog', 'pg_temp'\n",'')===f.definition&&JSON.stringify({...u,definition:f.definition,proconfig:null})===JSON.stringify(f),'Six-function exact allowance exceeded');explicitFunctionDeltas++}else check(JSON.stringify(f)===JSON.stringify(u),'Old function changed')}
 check(explicitFunctionDeltas===6,'Exact six invoker deltas required')
 const fixture=JSON.parse(await Bun.file('.superpowers/m78_author_native_1789620106488-result.json').text()),company=fixture.companyId,actor=fixture.users.owner,authorities={gas:createM73Authority(),mobile:createM74Authority(),diesel:createM76DieselAuthority(),fugitive:createM77Authority()},db=new(HostedWorkspaceDatabase as any)(runtime,'icockcoguyadhryzydvl')
 const route=createM78Routes({database:db,authorities,policy:M78_REVIEWED_POLICY,origin:'http://127.0.0.1:47805',validateUser:async t=>t==='fictional-recovery-owner'?{id:actor,email:null,phone:null,fullName:null}:null}),counters={process_screen:{authorizedGetRequests:0,exactDownloadRequests:0},inventory:{authorizedGetRequests:0,exactDownloadRequests:0}}
 const get=async(family:'process_screen'|'inventory',path:string)=>{counters[family].authorizedGetRequests++;const r=await route(new Request('http://127.0.0.1:47805/workspace/'+company+'/'+path,{headers:{authorization:'Bearer fictional-recovery-owner'}}));check(r.status===200&&r.headers.get('cache-control')==='no-store','Authorized read failed');return r}
 const register=await decodeScope1Register(await(await get('inventory','scope1-inventory')).json(),company);check(register.process.versions.length===3&&register.inventory.versions.length===2&&register.reconciliation.totals?.company.kgCo2eExact==='126850.17632025','Complete corrected occupied fixture required')
 let nullReports=0,contributorsChecked=0
 const families=[]
 for(const family of ['process_screen','inventory'] as const){const stream=family==='process_screen'?register.process:register.inventory,prefix=family==='process_screen'?'process-screen':'scope1-inventory';let previous:any=null
  for(const v of stream.versions){const base=prefix+'/'+stream.streamId+'/versions/'+v.id,e=await decodeScope1Version(await(await get(family,base)).json(),company,previous);check(e.version.id===v.id&&e.version.previousVersionId===(previous?.id??null),'Historical lineage differs');if(previous)check(previous.contributorIds.every((id:string)=>v.contributorIds.includes(id)),'Contributor history shrank');contributorsChecked++;const row=(await connections[3]!.query<{export_text:string}>('select export_text from neuvetra.scope1_versions where id=$1',[v.id])).rows[0]!;check(await(await get(family,base+'/inventory-export')).text()===row.export_text,'Version export changed');counters[family].exactDownloadRequests++;previous=v}
  for(const meta of stream.reports){const base=prefix+'/'+stream.streamId+'/reports/'+meta.id,r=await decodeScope1Report(await(await get(family,base)).json(),company);if(JSON.parse(r.snapshotJson).review===null)nullReports++;for(const [suffix,expected]of [['download',r.html],['snapshot',r.snapshotJson]]as const){check(await(await get(family,base+'/'+suffix)).text()===expected,'Report bytes differ');counters[family].exactDownloadRequests++}}
  families.push({family,versionIds:stream.versions.map(v=>v.id),reportIds:stream.reports.map(r=>r.id),...counters[family],semanticAndDownloadVerification:true})
 }
 check(nullReports>=2&&contributorsChecked===5,'Captured null reviews/complete history missing')
 for(const name of ['scope1_heads','scope1_versions','scope1_statements','scope1_reviews','scope1_reports','scope1_requests','scope1_audit','scope1_process_discoveries'])check((await runtime.query('select 1 from neuvetra.'+name+' limit 1')).rows.length===0,'No-claim runtime exposed rows')
 const after=await connections[3]!.transaction(async tx=>{await tx.exec('set transaction isolation level repeatable read read only');return {inventory:await inventory(tx),content:await content(tx,21)}});sameExactInventory(restored.inventory,after.inventory);sameContent(restored.content,after.content)
 const occupiedPath='evaluations/research-qa/m78-occupied21-evidence.json',occupiedBytes=new Uint8Array(await Bun.file(occupiedPath).arrayBuffer()),occupied=JSON.parse(new TextDecoder().decode(occupiedBytes));check(occupied.status==='independent_actual_occupied21_restore_refused'&&occupied.target===names[3]&&occupied.targetInventoryUnchanged&&occupied.clusterRolePrerequisitesPositiveControl,'Actual21 occupied target control required');
 const attestation={status:'m78_independent_occupied21_forward_recovery_passed',createdAt:new Date().toISOString(),reviewerId:'/root/m76_backend',project:'icockcoguyadhryzydvl',schemaVersion:21,migrationSha256:receipt.migrationSha256,hostedEvidence:false,occupiedTargetRefused:true,actualOccupied21Refusal:{path:occupiedPath,sha256:sha(occupiedBytes),schemaVersion:21,cloneCreated:false},freshCloneRestored:true,processAndInventoryHistoryVerified:true,capturedNullReviewsVerified:true,correctionsAndContributorsVerified:true,completeApplicationBytesAndCatalogVerified:true,noMutationVerified:true,providerRecoveryExcluded:true,semanticReplay:{fullHistoricalSemanticReplay:false,families},sourceInventory:source.inventory,restoredInventory:restored.inventory,sourceContent:source.content,restoredContent:restored.content,sourceDatabase:names[2],restoredDatabase:names[3],localOperatorReceipt:{path:'operations/agent-improvement/snapshots/M78-OPERATORS-01-NATIVE-RESULT.json',sha256:sha(receiptBytes)},schema20ForwardPreservation:{originalTables:old.inventory.tables.length,upgradedTables:upgraded.inventory.tables.length,explicitFunctionDeltas,rolesMembershipsDefaultAclsAndDependenciesExact:true,oldTableObjectsExact:true,oldContentPreserved:true},runtimeNoClaimDenied:true,nullReportsChecked:nullReports,actualRoutes:true,actualBrowserDecoders:true,legacyFullHistoricalSemanticReplay:false,encryptedBackupVerified:false,providerRecoveryVerified:false}
 await Bun.write('evaluations/research-qa/m78-forward-recovery.json',JSON.stringify(attestation,null,2)+'\n');console.log(JSON.stringify({status:attestation.status,families,nullReports,originalTables:113,restoredTables:121,contentEntries:source.content.entries.length,artifactSha256:sha(await Bun.file('evaluations/research-qa/m78-forward-recovery.json').text())}))
}finally{await runtime.close();for(const c of connections)await c.close()}
