import {test,expect} from 'bun:test'
import {createM78QaFixture,m78QaBaseline,m78QaName,m78QaProcessInput} from './m78-integrated-fixture'
import {createM78Routes} from '../../apps/site-api/src/workspace/m78-routes'
import {decodeScope1Register,decodeScope1Version,decodeScope1Report} from '../../apps/site-web/src/lib/m78-api'
import {M78_REVIEWED_POLICY} from '../../packages/neuvetra-database/src/m78-policy'
import {M78_LIMITATIONS,type M78VersionEnvelope,type M78Report} from '../../packages/neuvetra-database/src/m78-contract'
import {buildM78Dependencies} from '../../packages/neuvetra-database/src/m78-reconciliation'
import {m78Hash} from '../../packages/neuvetra-database/src/m78'
const baseline=process.env.M78_QA_CI_BASELINE_URL
if(baseline)m78QaBaseline(baseline)
test('M78 QA rejects hosted, credentialed and non-CI targets',()=>{for(const raw of ['postgres://m63_test_admin@remote.example:55463/m63_integration','postgres://m63_test_admin:private@127.0.0.1:55463/m63_integration','postgres://supabase_admin@127.0.0.1:55472/m63_integration','postgres://m63_test_admin@127.0.0.1:55463/postgres'])expect(()=>m78QaBaseline(raw)).toThrow();for(const name of ['m63_integration','m78_author_x','m78_qa_x;drop'])expect(()=>m78QaName(name)).toThrow()})
;(baseline?test:test.skip)('M78 CI fictional blocked lifecycle, tenant isolation and exact historical downloads',async()=>{
 const f=await createM78QaFixture(baseline!,'m78_qa_ci_'+Date.now()),origin='http://127.0.0.1:47801',routes=createM78Routes({database:new Proxy(f.database,{get(target,key){const value=(target as any)[key];return typeof value==='function'?async(...args:unknown[])=>{try{return await value.apply(target,args)}catch(error){console.error(JSON.stringify({fictionalQaBoundary:String(key),code:(error as any).code,message:(error as Error).message}));throw error}}:value}}),authorities:f.authorities,policy:M78_REVIEWED_POLICY,origin,validateUser:async token=>f.users[token as keyof typeof f.users]?{id:f.users[token as keyof typeof f.users],email:null,phone:null,fullName:null}:null})
 const call=(path:string,actor:string|null='owner',body?:unknown,company=f.companyId,requestOrigin=origin)=>{console.info(JSON.stringify({qaNativeStage:path,actor,method:body===undefined?'GET':'POST'}));return routes(new Request(origin+'/workspace/'+company+'/'+path,{method:body===undefined?'GET':'POST',headers:{origin:requestOrigin,...(actor?{authorization:'Bearer '+actor}:{}),...(body===undefined?{}:{'content-type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)}))}
 const get=async()=>{const response=await call('scope1-inventory');console.info(JSON.stringify({qaNativeStage:'register_response',status:response.status}));expect(response.status).toBe(200);const body=await response.json();console.info(JSON.stringify({qaNativeStage:'register_decode'}));const decoded=await decodeScope1Register(body,f.companyId);console.info(JSON.stringify({qaNativeStage:'register_decoded'}));return decoded}
 const post=async(path:string,body:unknown,actor='owner')=>{const response=await call(path,actor,body);expect(response.status,await response.clone().text()).toBe(201);return response.json()}
 const reportInput=(e:M78VersionEnvelope)=>({versionId:e.version.id,expectedVersionSha256:e.version.versionSha256,expectedDecisionId:e.version.review?.id??null,expectedDecisionSha256:e.version.review?.decisionSha256??null,expectedReconciliationSha256:e.version.reconciliation?.contentSha256??null,idempotencyKey:crypto.randomUUID()})
 const changesInput=(e:M78VersionEnvelope)=>({versionId:e.version.id,expectedVersionSha256:e.version.versionSha256,expectedDependencySha256:e.version.dependencies.dependencySha256,decision:'changes_requested',note:'Separate fictional review retains unknown applicability and missing sources.',acknowledgedLimitations:[...M78_LIMITATIONS],idempotencyKey:crypto.randomUUID()})
 const exactReport=async(path:string,r:M78Report)=>{const read=await call(path+'/'+r.id);expect(read.status).toBe(200);expect(await read.json()).toEqual(r);for(const [format,text]of [['download',r.html],['snapshot',r.snapshotJson]]as const){const response=await call(path+'/'+r.id+'/'+format);expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toBe('no-store');expect(response.headers.get('x-content-type-options')).toBe('nosniff');expect(await response.text()).toBe(text);expect((await call(path+'/'+r.id+'/'+format,'outsider')).status).toBe(404);expect((await call(path+'/'+r.id+'/'+format,null)).status).toBe(401)}}
 try{
  expect((await call('scope1-inventory',null)).status).toBe(401);expect((await call('scope1-inventory','outsider')).status).toBe(404);expect((await call('scope1-inventory','uninvited')).status).toBe(403);expect((await call('scope1-inventory','member')).status).toBe(200);expect((await call('scope1-inventory','owner',undefined,f.otherCompanyId)).status).toBe(404);expect((await call('scope1-inventory','owner',undefined,f.companyId,'https://invalid.example')).status).toBe(403)
  let register=await get();expect(register.reconciliation.status).toBe('blocked');expect(register.reconciliation.totals).toBeNull();const input=m78QaProcessInput(register)
  expect((await call('process-screen','member',input)).status).toBe(403)
  const first=await decodeScope1Version(await post('process-screen',input),f.companyId);expect(first.version.findings.some(x=>x.classification==='functional_blocker')).toBe(true);expect(first.version.activity.profile==='synthetic-process-screen-v1'&&first.version.activity.gasCoverage.length).toBe(7)
  expect((await post('process-screen',input)).version.id).toBe(first.version.id)
  const processReports='process-screen/'+first.version.streamId+'/reports',pending=await decodeScope1Report(await post(processReports,reportInput(first)),f.companyId);expect(JSON.parse(pending.snapshotJson).review).toBeNull()
  expect((await call('process-screen/'+first.version.streamId+'/reviews','owner',changesInput(first))).status).toBe(403)
  await post('process-screen/'+first.version.streamId+'/reviews',changesInput(first),'reviewer');await exactReport(processReports,pending)
  const statement=first.version.statements[0];expect(statement).toBeDefined();const evidence=await call('process-screen/'+first.version.streamId+'/statements/'+statement.id+'/download');expect(evidence.status).toBe(200);expect(await evidence.text()).toBe(statement.text);expect((await call('process-screen/'+first.version.streamId+'/statements/'+statement.id+'/download','outsider')).status).toBe(404)
  register=await get();const correction={...first.version.activity,manualConfirmation:true,expectedVersionId:first.version.id,expectedVersionSha256:first.version.versionSha256,expectedDependencySha256:buildM78Dependencies(register.proof,'process_screen',m78Hash).dependencySha256,correctionReason:'Fictional confirmation-only correction retains all unresolved applicability.',idempotencyKey:crypto.randomUUID()}
  const second=await decodeScope1Version(await post('process-screen/'+first.version.streamId+'/versions',correction,'preparer'),f.companyId);expect(second.proof.priorVersions.map(v=>v.id)).toEqual([first.version.id]);expect(second.version.contributorIds).toContain(f.users.owner);expect(second.version.contributorIds).toContain(f.users.preparer);expect(second.proof.priorVersions[0].review).toBeNull()
  expect((await call('process-screen/'+first.version.streamId+'/versions','owner',{...correction,idempotencyKey:crypto.randomUUID()})).status).toBe(409);expect((await call('process-screen/'+first.version.streamId+'/reviews','owner',changesInput(second))).status).toBe(403);expect((await call('process-screen/'+first.version.streamId+'/reviews','preparer',changesInput(second))).status).toBe(403)
  await post('process-screen/'+first.version.streamId+'/reviews',changesInput(second),'reviewer')
  register=await get();const inventoryInput={profile:'synthetic-scope1-inventory-v1',binding:second.version.activity.binding,note:'Fictional blocked CI inventory preserves unknown seven-gas coverage and missing source workpapers.',expectedVersionId:null,expectedVersionSha256:null,expectedDependencySha256:buildM78Dependencies(register.proof,'inventory',m78Hash).dependencySha256,correctionReason:null,idempotencyKey:crypto.randomUUID()}
  const inventory=await decodeScope1Version(await post('scope1-inventory',inventoryInput),f.companyId);expect(inventory.version.reconciliation?.totals).toBeNull();expect(inventory.version.findings.some(x=>x.classification==='functional_blocker')).toBe(true);expect(inventory.version.contributorIds).toContain(f.users.preparer)
  const inventoryReports='scope1-inventory/'+inventory.version.streamId+'/reports',old=await decodeScope1Report(await post(inventoryReports,reportInput(inventory)),f.companyId);expect(JSON.parse(old.snapshotJson).review).toBeNull();await post('scope1-inventory/'+inventory.version.streamId+'/reviews',changesInput(inventory),'reviewer');await exactReport(inventoryReports,old);await exactReport(processReports,pending)
  const final=await get();expect(final.process.versions).toHaveLength(2);expect(final.inventory.versions).toHaveLength(1);expect(final.versionProofs).toHaveLength(3);expect(final.inventory.versions[0].review?.decision).toBe('changes_requested')
  console.info(JSON.stringify({qaNativeStage:'grant_state'}));const grantState=async()=> (await f.runtime.query("select relacl::text acl,has_table_privilege(current_user,'neuvetra.scope1_versions','INSERT') can_insert from pg_class where oid='neuvetra.scope1_versions'::regclass")).rows
  const aclBefore=await grantState();expect(aclBefore[0]?.can_insert).toBe(false)
  console.info(JSON.stringify({qaNativeStage:'grant_transaction'}));let grantRolledBack=false;try{await f.runtime.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[f.users.member]);console.info(JSON.stringify({qaNativeStage:'grant_query'}));await tx.query('grant insert on neuvetra.scope1_versions to neuvetra_runtime');console.info(JSON.stringify({qaNativeStage:'grant_query_returned'}));expect((await tx.query("select has_table_privilege(current_user,'neuvetra.scope1_versions','INSERT') can_insert")).rows[0]?.can_insert).toBe(false);throw Error('qa_grant_probe_rollback')})}catch(e){if((e as Error).message!=='qa_grant_probe_rollback')throw e;grantRolledBack=true}expect(grantRolledBack).toBe(true)
  expect(await grantState()).toEqual(aclBefore)
  await Bun.write('.superpowers/'+f.name+'-result.json',JSON.stringify({status:'independent_ci_blocked_lifecycle_pass',database:f.name,migrationSha256:f.migrationSha256,syntheticAuth:true,actualRoutes:true,actualBrowserDecoders:true,customerData:false,reactRaceTested:false},null,2)+'\n')
 }finally{console.info(JSON.stringify({qaNativeStage:'close',database:f.name}));await f.close();console.info(JSON.stringify({qaNativeStage:'closed'}))}
},120000)
