import {test,expect} from 'bun:test';
import {readFile} from 'node:fs/promises';
import {dirname,resolve,relative} from 'node:path';
import {parseM78Continuation3Input,verifyM78Continuation3Disposition,runM78Continuation3,m78Continuation3PauseFetch,m78Continuation3DiagnosticFetch,M78_CONTINUATION3_PATHS as P,M78_CONTINUATION3_INTERRUPTION as I} from '../../tools/staging/check-m78-continuation3';
import {M78_ACCEPTED_M77} from '../../tools/staging/check-m78-continuation';
import {m78Continuation3SourcePins,M78_CONTINUATION3_EVIDENCE_PINS} from '../../tools/staging/m78-continuation3-source-pins';
const sha=(x:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(x).digest('hex');
const AUTH='https://icockcoguyadhryzydvl.supabase.co',APP='https://www.neuvetra.ai',digest='a'.repeat(64);
async function fixture(){
 const files=new Map<string,string>();for(const [path,source]of [[P.interrupted,'tools/staging/m78-continuation3-interrupted-main.jsonl'],[P.interruptedDiagnostics,'tools/staging/m78-continuation3-interrupted-diagnostics.jsonl'],[P.failed,'tools/staging/m78-continuation2-failed-baseline.jsonl']])files.set(path!,await readFile(source!,'utf8'));
 const result={path:'.superpowers/qa-synthetic-result.json',sha256:sha('synthetic result')},review={path:'evaluations/research-qa/qa-synthetic-review.md',sha256:sha('synthetic review')};files.set(result.path,'synthetic result');files.set(review.path,'synthetic review');
 const receipt:any={status:'m78_interrupted_sessions_independently_disposed',independent:true,reviewerId:'/root/qa_fixture',interruption:{...I},knownSessions:4,resolvedSessions:4,unresolvedSessions:0,sessionResolutionScope:'session_rows_and_linked_refresh_rows',disposition:'exact_session_cleanup',tokenUsability:'not_verified',expiryVerified:false,syntheticContinuationApproved:true,actualCleanupCommitted:true,refreshDispositionVerified:true,nonselectedSessionsPreserved:true,reviewedAt:'2026-09-22T22:00:00.000Z',evidencePins:[result,review],actualCleanupResult:result,independentPostconditionReview:review};
 const raw:any={mode:'baseline',acceptedM77:M78_ACCEPTED_M77,gate:{status:'m78_continuation_candidate_reviewed',migrationSha256:sha(await readFile('packages/neuvetra-database/src/migrations/0021_scope1_inventory.sql')),recipeSha256:sha(await readFile('tools/staging/m78-continuation-plan.ts')),harnessSha256:sha(await readFile('tools/staging/check-m78-continuation.ts')),independentReviewSha256:digest,operatorRecoveryReceiptSha256:digest,reviewedApplicationCommit:'b'.repeat(40),expectedApplicationPosts:37},env:{SUPABASE_URL:AUTH,SUPABASE_ANON_KEY:'sb_publishable_'+'a'.repeat(30)},roster:{workspaceId:'8b90c706-1710-494d-b12d-02eef88eacb7'},accounts:['manager1','manager2','member','outsider'].map((role,i)=>({role,id:`78000000-0000-4000-8000-00000000000${i}`,email:role+'@synthetic.invalid',password:'synthetic-only'}))};
 const bind=()=>{const text=JSON.stringify(receipt);files.set(P.disposition,text);return parseM78Continuation3Input({...raw,interruptionDisposition:{path:P.disposition,sha256:sha(text)}})};
 return{files,receipt,raw,bind,storage:{read:async(path:string)=>files.get(path)??null}};
}
test('independent admission challenges reject rehashed stale, missing, unsafe and cross-record evidence before transport or journal writes',async()=>{
 const mutations:Array<(f:Awaited<ReturnType<typeof fixture>>)=>void>=[
 f=>f.receipt.reviewedAt='2026-09-21T22:00:00.000Z',f=>f.receipt.interruption.mainSha256=digest,f=>f.receipt.unresolvedSessions=1,f=>f.receipt.knownSessions=3,f=>f.receipt.resolvedSessions=3,f=>f.receipt.sessionResolutionScope='session_rows_only',f=>f.receipt.tokenUsability='expired',f=>delete f.receipt.expiryVerified,f=>f.receipt.independent=false,f=>f.receipt.reviewerId='/root',f=>f.receipt.reviewerId='/root/resume_recipe',f=>delete f.receipt.actualCleanupCommitted,f=>delete f.receipt.actualCleanupResult,f=>f.receipt.independentPostconditionReview=f.receipt.actualCleanupResult,f=>f.receipt.evidencePins.push(f.receipt.evidencePins[0]),f=>f.receipt.actualCleanupResult.sha256=digest,
 ...['../outside.json','.superpowers/../outside.json','C:/outside.json','.superpowers/sub/result.json','.superpowers\\result.json','.superpowers/result.json:stream','.superpowers/%2e%2e.json'].map(path=>(f:Awaited<ReturnType<typeof fixture>>)=>{f.receipt.actualCleanupResult.path=path;f.files.set(path,'synthetic result')})];
 for(const mutate of mutations){const f=await fixture();mutate(f);const input=f.bind();let calls=0,writes=0;await expect(runM78Continuation3(input,{io:{...f.storage,append:async()=>{writes++}},fetch:(async()=>{calls++;throw Error('transport forbidden')})as any})).rejects.toThrow();expect(calls).toBe(0);expect(writes).toBe(0)}
 for(const change of ['receipt_bytes','evidence_bytes','missing_review','old_main','old_diagnostics','old_failed','stop','existing_main','existing_diagnostics']){const f=await fixture(),input=f.bind();if(change==='receipt_bytes')f.files.set(P.disposition,f.files.get(P.disposition)+' ');if(change==='evidence_bytes')f.files.set(f.receipt.actualCleanupResult.path,'changed');if(change==='missing_review')f.files.delete(f.receipt.independentPostconditionReview.path);if(change==='old_main')f.files.set(P.interrupted,f.files.get(P.interrupted)+' ');if(change==='old_diagnostics')f.files.set(P.interruptedDiagnostics,f.files.get(P.interruptedDiagnostics)+' ');if(change==='old_failed')f.files.set(P.failed,f.files.get(P.failed)+' ');if(change==='stop')f.files.set(P.stop,'');if(change==='existing_main')f.files.set(P.journal,f.files.get(P.interrupted)!);if(change==='existing_diagnostics')f.files.set(P.diagnostics,'');let calls=0,writes=0;await expect(runM78Continuation3(input,{io:{...f.storage,append:async()=>{writes++}},fetch:(async()=>{calls++;throw Error('forbidden')})as any})).rejects.toThrow();expect(calls).toBe(0);expect(writes).toBe(0)}
});
test('public adapter stop after third login preserves all previous bytes and closes three sessions with exclusive new journals',async()=>{
 const f=await fixture(),input=f.bind(),before=new Map(f.files),written:string[]=[],main:any[]=[],diag:any[]=[];let login=0,logout=0,posts=0;
 const transport=(async(raw:any,init:any)=>{const u=String(raw);expect(init.signal).toBeInstanceOf(AbortSignal);expect(init.redirect).toBe('error');if(u===APP+'/ready')return Response.json({status:'ready',schemaVersion:21,profile:'neuvetra.private-synthetic-staging.v1',legacyContainmentVerified:true});if(u===APP+'/workspace-api/config')return Response.json({profile:'neuvetra.private-synthetic-staging.v1',supabaseUrl:AUTH,anonKey:input.env.SUPABASE_ANON_KEY},{headers:{'cache-control':'no-store'}});if(u===AUTH+'/auth/v1/token?grant_type=password'){const a=input.accounts[login++]!;if(login===3)f.files.set(P.stop,'');return Response.json({access_token:'synthetic-qa-token-'+login,user:{id:a.id}})}if(u===AUTH+'/auth/v1/logout?scope=local'){logout++;return new Response(null,{status:204})}if(init.method==='POST')posts++;throw Error('unexpected transport')})as any;
 const result=await runM78Continuation3(input,{fetch:transport,io:{...f.storage,append:async(path,line,exclusive)=>{expect([P.journal,P.diagnostics]).toContain(path as any);expect(exclusive).toBe(!f.files.has(path));f.files.set(path,(f.files.get(path)??'')+line);written.push(path);(path===P.journal?main:diag).push(JSON.parse(line))}}});
 expect(result.status).toBe('failed');expect(result.paused).toBe(true);expect(result.allCreatedAuthSessionsClosed).toBe(true);expect(result.applicationPostRequests).toBe(0);expect([login,logout,posts]).toEqual([3,3,0]);expect(main.at(-1).kind).toBe('attempt_finished');expect(main.at(-1).data.unknownAuthSessions).toBe(0);expect(diag.at(-1).data).toMatchObject({status:'failed',paused:true,allCreatedAuthSessionsClosed:true});expect(new Set(written).size).toBe(2);for(const[path,text]of before)expect(f.files.get(path)).toBe(text);expect(JSON.stringify(diag)).not.toContain('synthetic-qa-token');
});
test('diagnostic failure after login headers returns identical unread response and still admits logout after stop-storage failure',async()=>{
 let calls=0;const response=new Response('synthetic-body');const paused=m78Continuation3PauseFetch((async()=>{calls++;return response})as any,{read:async()=>{throw Error('stop storage unavailable')}});expect(await paused.fetch(AUTH+'/auth/v1/logout?scope=local',{method:'POST'})).toBe(response);expect(calls).toBe(1);await expect(paused.fetch(APP+'/ready')).rejects.toThrow();expect(calls).toBe(1);
 const events:any[]=[];const observed=m78Continuation3DiagnosticFetch((async()=>{calls++;return response})as any,async(kind,data)=>{events.push({kind,data});if(kind==='response_headers')throw Error('storage unavailable')});expect(await observed.fetch(AUTH+'/auth/v1/token?grant_type=password',{method:'POST',body:'synthetic-secret'})).toBe(response);expect(response.bodyUsed).toBe(false);expect(observed.healthy()).toBe(false);await expect(observed.fetch(APP+'/ready')).rejects.toThrow();expect(await observed.fetch(AUTH+'/auth/v1/logout?scope=local',{method:'POST'})).toBe(response);expect(calls).toBe(3);expect(JSON.stringify(events)).not.toContain('synthetic-secret');expect(JSON.stringify(events)).not.toContain('synthetic-body');
});
test('independent exact candidate,166 current pins,160 parent pins and transitive relative import closure',async()=>{
 const candidate=await readFile('operations/agent-improvement/snapshots/M78-PLATFORM-CONTINUATION-PREP-01-CANDIDATE1.json');expect(sha(candidate)).toBe('9961619a5d6d2dcac500b7cdc9dd07b81f74b7e9617f53121daf5db55cd098ae');for(const a of JSON.parse(candidate.toString()).source_artifacts){expect(sha(a.text)).toBe(a.sha256);expect(sha(await readFile(a.path))).toBe(a.sha256)}
 const pins=await m78Continuation3SourcePins(),map=new Map(pins.map(p=>[p.path,p.sha256]));expect(pins).toHaveLength(166);expect(map.size).toBe(166);expect(pins).toEqual(JSON.parse(await readFile('evaluations/research-qa/m78-continuation3-preparation-source-pins.json','utf8')));const parent=JSON.parse(await readFile('evaluations/research-qa/m78-continuation2-journey-preparation.json','utf8')).sourcePins;expect(parent).toHaveLength(160);for(const p of parent)expect(map.get(p.path)).toBe(p.sha256);
 for(const p of pins){expect(sha(await readFile(p.path))).toBe(p.sha256);if(!/\.tsx?$/.test(p.path))continue;const text=await readFile(p.path,'utf8');for(const m of text.matchAll(/(?:\bfrom\s*|\bimport\s*\(\s*|\bimport\s*)['"](\.[^'"]+)['"]/g)){const base=resolve(dirname(p.path),m[1]!);let found:string|undefined;for(const suffix of ['', '.ts','.tsx','/index.ts']){try{await readFile(base+suffix);found=relative(resolve('.'),base+suffix).replaceAll('\\','/');break}catch{}}expect(found).toBeDefined();expect(map.has(found!)).toBe(true)}}
 for(const p of M78_CONTINUATION3_EVIDENCE_PINS)expect(sha(await readFile(p.path))).toBe(p.sha256);
});
