import {test,expect} from 'bun:test'
import {scope1ReportRead} from '../../apps/site-web/src/lib/m78-api'
const id=(n:number)=>`78000000-0000-4000-8000-${String(n).padStart(12,'0')}`
const read=(signal?:AbortSignal)=>scope1ReportRead({accessToken:'fictional-capacity-review',userId:id(2),role:'owner',signal},id(1),'inventory',id(3),id(4))
const capacity='History capacity reached. Saved records remain available. Ask an administrator before adding more versions.'
test('422 known capacity code uses fixed local guidance and never renders server prose',async()=>{const before=globalThis.fetch;globalThis.fetch=async()=>Response.json({code:'history_limit',error:'<script>fictional-server-text</script>'},{status:422});try{await expect(read()).rejects.toThrow(capacity)}finally{globalThis.fetch=before}})
test('unknown, malformed, duplicate and oversized422 bodies retain fixed input guidance',async()=>{const before=globalThis.fetch;try{for(const body of ['{"code":"other","error":"fictional-server-text"}','{"code":1}','null','"history_limit"','{"code":"history_limit","code":"other"}','not JSON',JSON.stringify({code:'history_limit',padding:'x'.repeat(2000)})]){globalThis.fetch=async()=>new Response(body,{status:422});await expect(read()).rejects.toThrow('Check the complete discovery, evidence, source bindings and review explanations. The request was not accepted.')}}finally{globalThis.fetch=before}})
test('abort while reading capacity body refuses stale response before guidance',async()=>{const before=globalThis.fetch,c=new AbortController();let resolve!:(s:string)=>void;globalThis.fetch=async()=>({status:422,text:()=>new Promise<string>(r=>resolve=r)}as Response);try{const pending=read(c.signal);await Promise.resolve();c.abort();resolve('{"code":"history_limit"}');await expect(pending).rejects.toMatchObject({name:'AbortError'})}finally{globalThis.fetch=before}})
test('capacity code cannot override409 or503 status guidance',async()=>{const before=globalThis.fetch;try{for(const [status,message]of [[409,'Coverage, sources or review changed. Refresh before continuing.'],[503,'Scope 1 records are unavailable. Refresh before continuing.']]as const){globalThis.fetch=async()=>Response.json({code:'history_limit'},{status});await expect(read()).rejects.toThrow(message)}}finally{globalThis.fetch=before}})
