import {test,expect} from 'bun:test'
import {readFile} from 'node:fs/promises'
import {parseM78ContinuationInput,cleanM78ContinuationJournal,readM78ContinuationJournal,M78_ACCEPTED_M77,M78_ACCEPTED_FAILURE,type M78Event} from '../../tools/staging/check-m78-continuation'
import {m78ContinuationSourcePins,JOURNEY_RESOLVER_ROOTS,M78_CONTINUATION_EVIDENCE_PINS} from '../../tools/staging/m78-continuation-source-pins'
import {verifyM78RecipeOldRows,m78NativeContinuationSourcePins} from '../../tools/staging/m78-continuation-native'
import {m78CanonicalJson as canonical} from '../../packages/neuvetra-database/src/m78-validation'
const company='8b90c706-1710-494d-b12d-02eef88eacb7',id='78000000-0000-4000-8000-000000000001',sha=(x:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(x).digest('hex'),digest='a'.repeat(64);
const input=()=>({mode:'revisit',acceptedM77:M78_ACCEPTED_M77,gate:{status:'m78_continuation_candidate_reviewed',migrationSha256:digest,recipeSha256:digest,harnessSha256:digest,independentReviewSha256:digest,operatorRecoveryReceiptSha256:digest,reviewedApplicationCommit:'b'.repeat(40),expectedApplicationPosts:37},env:{SUPABASE_URL:'https://icockcoguyadhryzydvl.supabase.co',SUPABASE_ANON_KEY:'sb_publishable_'+'a'.repeat(30)},roster:{workspaceId:company},accounts:['manager1','manager2','member','outsider'].map((role,i)=>({role,id:`78000000-0000-4000-8000-00000000000${i}`,email:role+'@synthetic.invalid',password:'fictional-test-password'})),restartAttestation:{path:'.superpowers/m78-after-restart-verified.json',sha256:digest}});
test('CLI parsing retains the exact restart artifact required by revisit',()=>{const raw=input(),parsed=parseM78ContinuationInput(raw);expect(parsed.restartAttestation).toEqual(raw.restartAttestation)});
test('CLI revisit refuses absent, foreign and malformed restart pins before runtime',()=>{
 for(const pin of [undefined,null,{path:'../outside.json',sha256:digest},{path:'.superpowers/m78-after-restart-verified.json',sha256:'bad'},{path:'https://outside.invalid/m78-verified.json',sha256:digest}])expect(()=>parseM78ContinuationInput({...input(),restartAttestation:pin})).toThrow();
});
function journal(){const es:M78Event[]=[];const add=(mode:any,kind:string,data:any)=>{const body={sequence:es.length+1,previousSha256:es.at(-1)?.sha256??null,profile:'m78-hosted-continuation-v1',workspaceId:company,mode,kind,data,createdAt:'2026-09-22T18:00:00.000Z'};es.push({...body,sha256:sha(canonical(body))})};add('baseline','provenance',{acceptedM77:M78_ACCEPTED_M77,acceptedM78Failure:M78_ACCEPTED_FAILURE});for(const mode of ['baseline','exercise']){add(mode,'attempt_started',{mode});const attempt=es.at(-1)!.sequence;for(const role of ['manager1','manager2','member','outsider']){add(mode,'auth_intent',{role});add(mode,'auth_outcome',{role,status:200,tokenObserved:true,subjectMatched:true})}if(mode==='exercise')for(let n=0;n<37;n++){const name=n===0?'m78_initial_unreviewed_report':'independent_step_'+n,route='/workspace-api/workspace/'+company+'/scope1-inventory/'+id+'/reports';add(mode,'post_intent',{name,route,role:'manager1',expected:201,request:{}});add(mode,'post_outcome',{name,route,role:'manager1',status:201,responseSha256:digest,byteLength:100});add(mode,'post_verified',{name,responseSha256:digest,verifiedIdentity:{id,companyId:company}})}for(let i=1;i<=8;i++){const action=i<=4?'login':'logout';add(mode,'legacy_auth_intent',{requestId:i,action});add(mode,'legacy_auth_outcome',{requestId:i,action,status:action==='login'?200:204})}add(mode,'legacy_read_verified',{unchanged:true,applicationPostRequests:0,allCreatedAuthSessionsClosed:true});add(mode,mode==='baseline'?'baseline':'exercise_complete',{});for(const role of ['manager1','manager2','member','outsider']){add(mode,'logout_intent',{role});add(mode,'logout_outcome',{role,status:204})}add(mode,'attempt_finished',{attemptSequence:attempt,status:'passed',allCreatedAuthSessionsClosed:true,unknownAuthSessions:0,applicationPostRequests:mode==='exercise'?37:0})}return es}
const rehash=(es:M78Event[])=>{let previous:string|null=null;return es.map((e,i)=>{const {sha256:_,...body}=e;body.sequence=i+1;body.previousSha256=previous;const out={...body,sha256:sha(canonical(body))};previous=out.sha256;return JSON.stringify(out)}).join('\n')+'\n'};
test('fully rehashed continuation cannot absorb original save, denial or wrong predecessor',()=>{
 expect(()=>cleanM78ContinuationJournal(readM78ContinuationJournal(rehash(journal()),company))).not.toThrow();
 for(const mutate of [(es:M78Event[])=>{es[0]!.data.acceptedM78Failure={...M78_ACCEPTED_FAILURE,observationSha256:'0'.repeat(64)}},(es:M78Event[])=>{es.find(e=>e.kind==='post_intent')!.data.route='/workspace-api/workspace/'+company+'/scope1-inventory'},(es:M78Event[])=>{es.find(e=>e.kind==='post_intent')!.data.name='m78_initial_blocked_inventory'},(es:M78Event[])=>{const e=es.find(e=>e.kind==='post_intent')!;e.data.name='m78_member_write_refused';e.data.expected=403;e.data.role='member'},(es:M78Event[])=>{es.find(e=>e.kind==='post_verified')!.data.verifiedIdentity.companyId=id}]){const es=journal();mutate(es);expect(()=>cleanM78ContinuationJournal(readM78ContinuationJournal(rehash(es),company))).toThrow()}
 const es=journal(),cut=es.findIndex(e=>e.kind==='post_outcome');expect(()=>cleanM78ContinuationJournal(readM78ContinuationJournal(rehash(es.slice(0,cut+1)),company))).toThrow();
});
test('remaining recipe body is exactly the old suffix; prior review and denial code is not replayed',async()=>{
 const original=(await readFile('tools/staging/m78-hosted-plan.ts','utf8')).replaceAll('\r\n','\n'),continued=(await readFile('tools/staging/m78-continuation-plan.ts','utf8')).replaceAll('\r\n','\n'),marker=" await report('m78_initial_unreviewed_report',initial)";
 expect(continued.slice(continued.indexOf(marker)).trim()).toBe(original.slice(original.indexOf(marker),original.indexOf('export function m78FictionalDiscovery')).trim());expect(continued).not.toContain("inventory('m78_initial_blocked_inventory'");
 const native=await readFile('tools/staging/m78-continuation-native.ts','utf8');expect(native).toContain('delta===37');expect(native).toContain('posts===37');expect(native).toContain("name==='m78_initial_unreviewed_report'");
});
test('native preservation refuses multiplicity loss, old request changes and foreign additions',()=>{
 const row=(x:any)=>JSON.stringify(x),old={scope1_versions:[row({company_id:company,id})],scope1_requests:[row({company_id:company,idempotency_key:id})],scope1_heads:[row({company_id:company,id,version_id:id,revision:1})]};expect(()=>verifyM78RecipeOldRows(old,structuredClone(old))).not.toThrow();
 for(const mutate of [(x:any)=>x.scope1_versions=[],(x:any)=>x.scope1_requests=[row({company_id:company,idempotency_key:'changed'})],(x:any)=>x.scope1_versions.push(row({company_id:id,id})),(x:any)=>x.scope1_heads=[row({company_id:company,id:'changed',version_id:id,revision:2})]]){const next=structuredClone(old);mutate(next);expect(()=>verifyM78RecipeOldRows(old,next)).toThrow()}
 expect(()=>verifyM78RecipeOldRows({...old,scope1_versions:[...old.scope1_versions,...old.scope1_versions]},old)).toThrow();
});
test('both closure maps pin resolver metadata, current runtime and exact SQL21',async()=>{for(const [index,pins] of [await m78ContinuationSourcePins(),await m78NativeContinuationSourcePins()].entries()){expect(new Set(pins.map(p=>p.path)).size).toBe(pins.length);for(const path of [...JOURNEY_RESOLVER_ROOTS,...(index===1?['apps/site-api/src/workspace/m78-routes.ts','packages/neuvetra-database/src/m78.ts']:['apps/site-web/src/lib/m78-api.ts']),'packages/neuvetra-database/src/migrations/0021_scope1_inventory.sql']){const found=pins.find(p=>p.path===path);expect(found).toBeDefined();expect(found!.sha256).toBe(sha(await readFile(path)))}}expect(M78_CONTINUATION_EVIDENCE_PINS.map(p=>p.sha256)).toEqual([M78_ACCEPTED_FAILURE.journalSha256,M78_ACCEPTED_FAILURE.observationSha256,M78_ACCEPTED_FAILURE.independentActualReviewSha256])});
