import {expect,test} from 'bun:test';
import {m78CanonicalJson as canonical} from '../../packages/neuvetra-database/src/m78-validation';
import {verifyRecovery2ObservationBinding,verifyRecovery2TransportEvidence,type Recovery2ReviewAdmission} from './m78-readonly-recovery2-independent-review';
const sha=(value:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(value).digest('hex');
function chain(profile:string,raw:{kind:string;data:any}[]){let prior:string|null=null;const events=raw.map((item,index)=>{const body={sequence:index+1,previousSha256:prior,profile,workspaceId:'8b90c706-1710-494d-b12d-02eef88eacb7',...item,createdAt:new Date(Date.UTC(2026,8,23,4,0,index)).toISOString()},event={...body,sha256:sha(canonical(body))};prior=event.sha256;return event});return{text:events.map(event=>JSON.stringify(event)).join('\n')+'\n',events}}
function fixture(){
 const roles=['manager1','manager2','member','outsider'],scope='application:/workspace-api/workspace/:id/scope1-inventory',upstream=['corporate-inventories','stationary-natural-gas','mobile-diesel','controlled-fleet','stationary-diesel','stationary-equipment','fugitive-sources'].map(family=>`application:/workspace-api/workspace/:id/${family}`),reports=Array.from({length:5},()=>`application:/workspace-api/workspace/:id/scope1-inventory/:id/reports/:id`),artifacts=(family:string,count:number)=>Array.from({length:count},()=>['download','snapshot','proof'].map(operation=>`application:/workspace-api/workspace/:id/${family}/:id/reports/:id/${operation}`)).flat(),appRoutes=[scope,scope,scope,scope,...upstream,...reports,...artifacts('controlled-fleet',3),...artifacts('stationary-equipment',5),'application:/workspace-api/workspace/:id/legacy'];
 const diagnostics:{kind:string;data:any}[]=[],captures:any[]=[];let ordinal=0,previous:string|null=null;
 const pair=(route:string,method:string,status:number)=>{ordinal++;diagnostics.push({kind:'request_intent',data:{ordinal,method,route,...(route==='auth:/auth/v1/logout'?{logoutScope:'local'}:{})}},{kind:'response_headers',data:{ordinal,status}});if(route.startsWith('application:')){const body=new TextEncoder().encode(JSON.stringify({ordinal})),base={sequence:captures.length+1,previousSha256:previous,profile:'m78-continuation4-readonly-recovery2-raw-capture-v1',status:'captured_unreviewed',requestOrdinal:ordinal,route,responseStatus:status,headers:{'cache-control':'no-store','content-type':'application/json'},encoding:'base64',body:Buffer.from(body).toString('base64'),bodySha256:sha(body),byteLength:body.length,createdAt:new Date(Date.UTC(2026,8,23,5,0,captures.length)).toISOString()},event={...base,sha256:sha(canonical(base))};previous=event.sha256;captures.push(event)}};
 for(let i=0;i<4;i++)pair('auth:/auth/v1/token','POST',200);for(let i=0;i<appRoutes.length-1;i++)pair(appRoutes[i]!,'GET',i===0?403:i===1?401:200);for(let i=0;i<4;i++)pair('auth:/auth/v1/token','POST',200);pair(appRoutes.at(-1)!,'GET',200);for(let i=0;i<8;i++)pair('auth:/auth/v1/logout','POST',204);diagnostics.push({kind:'phase_finished',data:{status:'passed',requests:ordinal,applicationPostRequests:0,allCreatedAuthSessionsClosed:true,unknownAuthSessions:0,diagnosticsHealthy:true}});
 const observationText=JSON.stringify({status:'fixture'})+'\n',rawCaptureText=captures.map(event=>JSON.stringify(event)).join('\n')+'\n',rawCaptureSha256=sha(rawCaptureText),sourceGateSha256='c'.repeat(64),mainRaw:any[]=[{kind:'attempt_started',data:{currentSourceGateSha256:sourceGateSha256}}];for(const role of roles)mainRaw.push({kind:'auth_intent',data:{role}},{kind:'auth_outcome',data:{role,status:200,subjectMatched:true,sessionCreationUncertain:false}});for(const role of roles)mainRaw.push({kind:'logout_intent',data:{role}},{kind:'logout_outcome',data:{role,status:204}});mainRaw.push({kind:'recovery2_observed',data:{observationSha256:sha(observationText),rawCaptureSha256,applicationPostRequests:0,allMainSessionsClosed:true,allLegacySessionsClosed:true}},{kind:'attempt_finished',data:{status:'passed',requests:ordinal,applicationPostRequests:0,allCreatedAuthSessionsClosed:true,unknownAuthSessions:0,diagnosticsHealthy:true}});
 const main=chain('m78-continuation4-readonly-recovery2-v1',mainRaw),diag=chain('m78-continuation4-readonly-recovery2-diagnostic-v1',diagnostics),admission:Recovery2ReviewAdmission={journalSha256:sha(main.text),journalHead:main.events.at(-1)!.sha256,diagnosticsSha256:sha(diag.text),diagnosticsHead:diag.events.at(-1)!.sha256,rawCaptureSha256,rawCaptureHead:captures.at(-1)!.sha256,observationSha256:sha(observationText),currentSourceGateSha256:sourceGateSha256};return{main,diag,captures,rawCaptureText,observationText,admission};
}
test('recovery2 transport accepts exactly the main reads, 24 roster artifacts, finite legacy reads and paired raw captures',()=>{const value=fixture(),result=verifyRecovery2TransportEvidence(value.main.text,value.diag.text,value.rawCaptureText,value.admission);expect(result.captures).toHaveLength(41);expect(result.requests.size).toBe(57);expect(result.journal).toHaveLength(19);expect(verifyRecovery2ObservationBinding(result.journal,value.observationText,value.admission.rawCaptureSha256,value.admission.currentSourceGateSha256).kind).toBe('recovery2_observed')});
test('transport rejects artifact route drift and capture body, route, status or auth method changes',()=>{for(const mutation of ['artifact','body','route','status','auth']as const){const value=fixture();if(mutation==='artifact')value.diag.text=value.diag.text.replace('/controlled-fleet/:id/reports/:id/download','/controlled-fleet/:id/reports/:id/proof');if(mutation==='body')value.rawCaptureText=value.rawCaptureText.replace('eyJvcmRpbmFsIjo1fQ==','eyJvcmRpbmFsIjo2fQ==');if(mutation==='route')value.rawCaptureText=value.rawCaptureText.replace('scope1-inventory','other-route');if(mutation==='status')value.rawCaptureText=value.rawCaptureText.replace('"responseStatus":403','"responseStatus":200');if(mutation==='auth')value.diag.text=value.diag.text.replace('"method":"POST","route":"auth:/auth/v1/token"','"method":"GET","route":"auth:/auth/v1/token"');expect(()=>verifyRecovery2TransportEvidence(value.main.text,value.diag.text,value.rawCaptureText,{...value.admission,diagnosticsSha256:sha(value.diag.text),rawCaptureSha256:sha(value.rawCaptureText)})).toThrow()}});
test('observation binding rejects a changed raw capture pin',()=>{const value=fixture(),transport=verifyRecovery2TransportEvidence(value.main.text,value.diag.text,value.rawCaptureText,value.admission);expect(()=>verifyRecovery2ObservationBinding(transport.journal,value.observationText,'d'.repeat(64),value.admission.currentSourceGateSha256)).toThrow('journal observation/source binding')});
