/** Independent extension of the preserved author concurrency fixture. Adds all upstream review/report lock paths, diesel and fugitive discovery; fresh clone only. */
import {test,expect} from 'bun:test'
import {createM78QaFixture,m78QaBaseline} from './m78-integrated-fixture'
import {createPostgresConnection,HostedWorkspaceDatabase,createM71Seed,type WorkspaceConnection} from '../../packages/neuvetra-database/src/index'
import {createM78Routes} from '../../apps/site-api/src/workspace/m78-routes'
import {M78_REVIEWED_POLICY} from '../../packages/neuvetra-database/src/m78-policy'
import {M78_PERIOD,type M78InventorySaveInput} from '../../packages/neuvetra-database/src/m78-contract'
import {m78CanonicalJson} from '../../packages/neuvetra-database/src/m78-validation'
const baseline=process.env.M78_PERF_NATIVE_BASELINE_URL;
if(baseline)m78QaBaseline(baseline);
test('M78 POST denies early without register reconstruction, and maps only explicit missing stream to404',async()=>{
 let reads=0,writes=0,errorCode='M78_STREAM_NOT_FOUND';const db:any={hasStagingAccess:async()=>true,canManageWorkspace:async()=>true,findScope1:async()=>{reads++;throw Error('Unexpected preflight')},saveScope1Inventory:async()=>{writes++;throw Object.assign(Error('missing'),{code:errorCode})}};
 const company='78000000-0000-4000-8000-000000000001',routes=createM78Routes({database:db,authorities:{}as any,origin:'http://localhost',validateUser:async token=>token==='owner'?{id:company,phone:null,email:null,fullName:null}:null});
 const request=(method:string,token:string|null,body:unknown={})=>new Request('http://localhost/workspace/'+company+'/scope1-inventory',{method,headers:{origin:'http://localhost',...(token?{authorization:'Bearer '+token}:{}),'content-type':'application/json'},body:['GET','HEAD'].includes(method)?undefined:JSON.stringify(body)});
 expect((await routes(request('POST',null))).status).toBe(401);expect((await routes(request('DELETE','owner'))).status).toBe(405);expect((await routes(request('POST','owner'))).status).toBe(422);expect(reads).toBe(0);expect(writes).toBe(0);
 const body={profile:'synthetic-scope1-inventory-v1',binding:{coverageVersionId:company,coverageVersionSha256:'a'.repeat(64),processCoverageItemId:company,period:M78_PERIOD},note:'Fictional route boundary',expectedVersionId:null,expectedVersionSha256:null,expectedDependencySha256:'b'.repeat(64),correctionReason:null,idempotencyKey:company};
 expect((await routes(request('POST','owner',body))).status).toBe(404);errorCode='unrecognized_integrity_error';expect((await routes(request('POST','owner',body))).status).toBe(503);expect(reads).toBe(0);expect(writes).toBe(2);
});
;(baseline?test:test.skip)('M78 locked reuse preserves races, tenant independence, revocation and rollback',async()=>{
 const f=await createM78QaFixture(baseline!,'m78_qa_perf_independent_'+Date.now()),target=m78QaBaseline(baseline!);target.pathname='/'+f.name;target.username='neuvetra_runtime';
 const secondConnection=createPostgresConnection(target.toString(),{tls:false,maxConnections:1}),second=new(HostedWorkspaceDatabase as any)(secondConnection,(await f.operator.query<any>('select project_ref from neuvetra.staging_target')).rows[0].project_ref)as HostedWorkspaceDatabase;
 let pause:(()=>Promise<void>)|null=null,corrupt=false,written=false,stateReads=0,corporateReads=0;
 const wrapped={...f.runtime,transaction:(fn:any)=>f.runtime.transaction(tx=>fn({...tx,query:async(sql:string,args?:any[])=>{
  const state=sql.includes('from neuvetra.scope1_heads x');if(state){stateReads++;if(pause){const wait=pause;pause=null;await wait()}}
  if(sql.includes('jsonb_agg(h) from neuvetra.corporate_inventory_heads'))corporateReads++;
  const result=await tx.query<any>(sql,args);if(sql.startsWith('select neuvetra.save_scope1_version'))written=true;
  if(state&&written&&corrupt){result.rows[0].versions[0].payload.contentSha256='0'.repeat(64);corrupt=false}return result;
 }}))}as WorkspaceConnection;
 const db=new(HostedWorkspaceDatabase as any)(wrapped,(await f.operator.query<any>('select project_ref from neuvetra.staging_target')).rows[0].project_ref)as HostedWorkspaceDatabase;
 const save=(body:M78InventorySaveInput,stream:string|null=null)=>db.saveScope1Inventory(f.users.owner,f.companyId,stream,body,f.authorities,M78_REVIEWED_POLICY);
 const rows=async()=> (await f.operator.query<any>("select (select jsonb_agg(to_jsonb(t)order by id)from neuvetra.scope1_versions t)versions,(select jsonb_agg(to_jsonb(t)order by idempotency_key)from neuvetra.scope1_requests t)requests,(select jsonb_agg(to_jsonb(t)order by id)from neuvetra.scope1_audit t)audits")).rows[0];
 let release:(()=>void)|undefined,inflight:Promise<unknown>|undefined;
 try{
  const r=(await db.findScope1(f.users.owner,f.companyId,f.authorities,M78_REVIEWED_POLICY))!,item=r.coverageVersion.snapshot.coverageItems.find(i=>i.domain==='process'&&i.entityId===null&&i.sourceId===null)!;
  const input:M78InventorySaveInput={profile:'synthetic-scope1-inventory-v1',binding:{coverageVersionId:r.coverageVersion.id,coverageVersionSha256:r.coverageVersion.versionSha256,processCoverageItemId:item.id,period:M78_PERIOD},note:'Fictional concurrency fixture',expectedVersionId:null,expectedVersionSha256:null,expectedDependencySha256:r.dependencies.dependencySha256,correctionReason:null,idempotencyKey:crypto.randomUUID()};
  const before=await rows();corrupt=true;written=false;await expect(save(input)).rejects.toThrow('could not be verified');expect(await rows()).toEqual(before);
  let reached!:()=>void;const entered=new Promise<void>(r=>reached=r),hold=new Promise<void>(r=>release=r);pause=async()=>{reached();await hold};stateReads=0;corporateReads=0;written=false;
  const first=save(input);inflight=first;await entered;
  // Exercise actual supported native writer entrypoints; each must wait before validating/mutating its payload.
  for(const [name,sql]of [["corporate", "select neuvetra.save_corporate_inventory($1,null,$2::jsonb)"], ["corporate review", "select neuvetra.review_corporate_inventory($1,null,$2::jsonb)"], ["stationary_gas save", "select neuvetra.save_stationary_gas($1,null,$2::jsonb,$2::jsonb)"], ["stationary_gas review", "select neuvetra.review_stationary_gas($1,null,$2::jsonb)"], ["stationary_gas report", "select neuvetra.create_stationary_gas_report($1,null,$2::jsonb)"], ["mobile_diesel save", "select neuvetra.save_mobile_diesel($1,null,$2::jsonb,$2::jsonb)"], ["mobile_diesel review", "select neuvetra.review_mobile_diesel($1,null,$2::jsonb)"], ["mobile_diesel report", "select neuvetra.create_mobile_diesel_report($1,null,$2::jsonb)"], ["stationary_diesel save", "select neuvetra.save_stationary_diesel($1,null,$2::jsonb,$2::jsonb)"], ["stationary_diesel review", "select neuvetra.review_stationary_diesel($1,null,$2::jsonb)"], ["stationary_diesel report", "select neuvetra.create_stationary_diesel_report($1,null,$2::jsonb)"], ["controlled_fleet save", "select neuvetra.save_controlled_fleet($1,null,$2::jsonb,$2::jsonb,$2::jsonb)"], ["controlled_fleet review", "select neuvetra.review_controlled_fleet($1,null,$2::jsonb,$2::jsonb)"], ["controlled_fleet report", "select neuvetra.create_controlled_fleet_report($1,null,$2::jsonb,$2::jsonb)"], ["stationary_equipment save", "select neuvetra.save_stationary_equipment($1,null,$2::jsonb,$2::jsonb,$2::jsonb)"], ["stationary_equipment review", "select neuvetra.review_stationary_equipment($1,null,$2::jsonb,$2::jsonb)"], ["stationary_equipment report", "select neuvetra.create_stationary_equipment_report($1,null,$2::jsonb,$2::jsonb)"], ["source save_fugitive_version", "select neuvetra.save_fugitive_version($1,null,'source',$2::jsonb,$2::jsonb)"], ["source review_fugitive_version", "select neuvetra.review_fugitive_version($1,null,'source',$2::jsonb,$2::jsonb)"], ["source create_fugitive_report", "select neuvetra.create_fugitive_report($1,null,'source',$2::jsonb,$2::jsonb)"], ["population save_fugitive_version", "select neuvetra.save_fugitive_version($1,null,'population',$2::jsonb,$2::jsonb)"], ["population review_fugitive_version", "select neuvetra.review_fugitive_version($1,null,'population',$2::jsonb,$2::jsonb)"], ["population create_fugitive_report", "select neuvetra.create_fugitive_report($1,null,'population',$2::jsonb,$2::jsonb)"]]){
   let code:string|null=null;try{await secondConnection.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[f.users.owner]);await tx.exec("set local lock_timeout='100ms'");await tx.query(sql!,[f.companyId,'{}'])})}catch(e){code=(e as any).code}expect(code,name).toBe('55P03');
  }
  // Another tenant can make progress while this company's upstream graph is captured.
  const emptyRoutes=createM78Routes({database:second,authorities:f.authorities,policy:M78_REVIEWED_POLICY,origin:'http://localhost',validateUser:async()=>({id:f.users.outsider,phone:null,email:null,fullName:null})});
  for(const method of ['GET','POST']){const empty=await emptyRoutes(new Request('http://localhost/workspace/'+f.otherCompanyId+'/scope1-inventory',{method,headers:{origin:'http://localhost',authorization:'Bearer fictional-empty-company','content-type':'application/json'},body:method==='POST'?JSON.stringify(input):undefined}));expect(empty.status).toBe(503)}
  const other=await second.saveCorporateInventory(f.users.outsider,f.otherCompanyId,null,{snapshot:createM71Seed(),expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()});expect(other.companyId).toBe(f.otherCompanyId);
  // Revocation-after-admission cannot change held membership/access facts mid-transaction.
  let revokedCode:string|null=null;try{await f.operator.transaction(async tx=>{await tx.exec("set local lock_timeout='100ms'");await tx.query('update neuvetra.staging_access set active=false where user_id=$1',[f.users.owner])})}catch(e){revokedCode=(e as any).code}expect(revokedCode).toBe('55P03');
  const competing=second.saveScope1Inventory(f.users.owner,f.companyId,null,{...input,idempotencyKey:crypto.randomUUID()},f.authorities,M78_REVIEWED_POLICY).then(()=>null,e=>e.code);
  release!();const saved=await first;expect(await competing).toBe('23505');expect(stateReads).toBe(2);expect(corporateReads).toBe(10);
  const replay=await save(input);expect(replay).toEqual(saved);const exact=await rows();expect(exact.versions.filter((v:any)=>v.id===saved.version.id)).toHaveLength(1);expect(exact.requests.filter((v:any)=>v.idempotency_key===input.idempotencyKey)).toHaveLength(1);expect(exact.audits.filter((v:any)=>v.record_id===saved.version.id)).toHaveLength(1);
  await expect(save(input,crypto.randomUUID())).rejects.toMatchObject({code:'M78_STREAM_NOT_FOUND'});
  const changed=await second.saveCorporateInventory(f.users.owner,f.companyId,r.coverageVersion.inventoryId,{snapshot:{...r.coverageVersion.snapshot,companyLabel:'Fictional changed corporate coverage after lock release'},expectedVersionId:r.coverageVersion.id,expectedVersionSha256:r.coverageVersion.versionSha256,correctionReason:'Fictional race test changes the current corporate dependency.',idempotencyKey:crypto.randomUUID()});expect(changed.id).not.toBe(r.coverageVersion.id);
  await expect(save({...input,note:'Stale captured dependency after corporate change',expectedVersionId:saved.version.id,expectedVersionSha256:saved.version.versionSha256,correctionReason:'Fictional stale attempt',idempotencyKey:crypto.randomUUID()},saved.version.streamId)).rejects.toMatchObject({code:'23505'});expect(await rows()).toEqual(exact);
  // A request after completed revocation is refused, with no state reuse from the admitted request.
  await f.operator.query('update neuvetra.staging_access set active=false where user_id=$1',[f.users.owner]);await expect(save(input)).rejects.toThrow();expect(m78CanonicalJson(await rows())).toBe(m78CanonicalJson(exact));
 }finally{release?.();await inflight?.catch(()=>{});await secondConnection.close();await f.close()}
},120000);
