import {test,expect} from 'bun:test';
import {readFile,mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {resolve,join} from 'node:path';
import {M78_CONTINUATION3_INTERRUPTION as I,M78_CONTINUATION3_PATHS as P} from '../../tools/staging/check-m78-continuation3';
const sha=(x:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(x).digest('hex');
const wrapper='.superpowers/m78-private-continuation3-journey.ps1',preflight='.superpowers/m78-continuation3-disposition-preflight.ts',observer='.superpowers/m78-continuation3-refresh-runtime.py';
test('private exact wrapper preserves admitted checks and semantically verifies same disposition before credential unseal',async()=>{
 const w=await readFile(wrapper,'utf8'),p=await readFile(preflight,'utf8'),o=await readFile(observer,'utf8');expect(sha(w)).toBe('b36cbf0e1a0041daffe54e76ce2d44625270c0e4cacfa3e0a587dbebd17b8719');expect(sha(p)).toBe('265bcc4812f8c1c2a454d3297c4171893cdd656bc2bd023419b1216196d87c3a');expect(sha(o)).toBe('702fe3343ba67d3a43373ad0c106e66d770659430fef616d5697c212841a37da');
 const predecessor=await readFile('.superpowers/m78-continuation2-refresh-runtime.py','utf8');expect(sha(predecessor)).toBe('dd52a4c310bb41fbb9712aaf4796a6263a4d52f0787f995697929526177f7d7b');expect(o).toBe(predecessor.replaceAll('m78-continuation2-','m78-continuation3-'));
 const unseal=w.indexOf('[Security.Cryptography.ProtectedData]::Unprotect');expect(unseal).toBeGreaterThan(0);for(const required of ['complete source closure changed','reviewed closure mismatch','missing original outcome evidence','wrong disposition path',"sha256='265bcc4812f8c1c2a454d3297c4171893cdd656bc2bd023419b1216196d87c3a'",'$preflightProcess.WaitForExit()',"$preflightProcess.ExitCode -ne 0 -or $preflightOutput.Result.Trim() -cne 'verified'"]){expect(w.indexOf(required)).toBeGreaterThan(0);expect(w.indexOf(required)).toBeLessThan(unseal)}
 expect(w).toContain('$preflightProcess.StandardInput.Write(($dispositionPin | ConvertTo-Json -Compress))');expect(w).toContain('-NotePropertyName interruptionDisposition -NotePropertyValue $dispositionPin -Force');expect(w).toContain('$review.evidencePins.Count -ne 6');expect(w).toContain("tools/staging/m78-continuation3-source-pins.ts");expect(w).toContain("tools/staging/check-m78-continuation3.ts");expect(w.match(/::Unprotect/g)).toHaveLength(1);expect(p).toContain('verifyM78Continuation3Disposition(');expect(p).toContain("workspaceId:'8b90c706-1710-494d-b12d-02eef88eacb7'");expect(p).not.toMatch(/password|Unprotect|fetch\(/);
});
test('exact private preflight accepts only bound synthetic cleanup and rejects missing stale mutated and unsafe cases without credentials',async()=>{
 const executable=resolve(preflight),main=await readFile('tools/staging/m78-continuation3-interrupted-main.jsonl','utf8'),diagnostics=await readFile('tools/staging/m78-continuation3-interrupted-diagnostics.jsonl','utf8');
 for(const kind of ['accepted','not_committed','self_review','stale','scope','missing_evidence','changed_receipt','unsafe_path','missing_receipt']){
  const directory=await mkdtemp(join(tmpdir(),'neuvetra-m78-preflight-qa-'));try{await mkdir(join(directory,'.superpowers'));await mkdir(join(directory,'evaluations/research-qa'),{recursive:true});await writeFile(join(directory,P.interrupted),main);await writeFile(join(directory,P.interruptedDiagnostics),diagnostics);
   const r={path:'.superpowers/qa-result.json',sha256:sha('synthetic result')},q={path:'evaluations/research-qa/qa-review.md',sha256:sha('synthetic review')};await writeFile(join(directory,r.path),'synthetic result');if(kind!=='missing_evidence')await writeFile(join(directory,q.path),'synthetic review');
   const receipt:any={status:'m78_interrupted_sessions_independently_disposed',independent:true,reviewerId:'/root/independent_synthetic',interruption:I,knownSessions:4,resolvedSessions:4,unresolvedSessions:0,sessionResolutionScope:'session_rows_and_linked_refresh_rows',disposition:'exact_session_cleanup',tokenUsability:'not_verified',expiryVerified:false,syntheticContinuationApproved:true,actualCleanupCommitted:true,refreshDispositionVerified:true,nonselectedSessionsPreserved:true,reviewedAt:'2026-09-22T22:00:00.000Z',evidencePins:[r,q],actualCleanupResult:r,independentPostconditionReview:q};
   if(kind==='not_committed')receipt.actualCleanupCommitted=false;if(kind==='self_review')receipt.reviewerId='/root';if(kind==='stale')receipt.reviewedAt='2026-09-21T00:00:00Z';if(kind==='scope')receipt.sessionResolutionScope='session_rows';if(kind==='unsafe_path')receipt.actualCleanupResult.path='../outside.json';const bytes=JSON.stringify(receipt),pin={path:P.disposition,sha256:sha(bytes)};if(kind!=='missing_receipt')await writeFile(join(directory,P.disposition),bytes+(kind==='changed_receipt'?' ':''));
   const child=Bun.spawn([process.execPath,executable],{cwd:directory,stdin:new TextEncoder().encode(JSON.stringify(pin)),stdout:'pipe',stderr:'pipe'});const [exit,out,err]=await Promise.all([child.exited,new Response(child.stdout).text(),new Response(child.stderr).text()]);expect(exit).toBe(kind==='accepted'?0:1);expect(out.trim()).toBe(kind==='accepted'?'verified':'refused');expect(err).toBe('');expect(await Bun.file(join(directory,P.journal)).exists()).toBe(false);expect(await Bun.file(join(directory,P.diagnostics)).exists()).toBe(false);
  }finally{const target=resolve(directory);if(!target.startsWith(resolve(tmpdir())+'\\')&&!target.startsWith(resolve(tmpdir())+'/'))throw Error('Unsafe temporary cleanup');await rm(target,{recursive:true,force:true})}
 }
});
