/** Static review of the two root-owned recovery2 private helpers. Never executes them. */
const sha=(value:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(value).digest('hex');
const check:(value:unknown,message:string)=>asserts value=(value,message)=>{if(!value)throw Error(message)};
const count=(text:string,needle:string)=>text.split(needle).length-1;
const ordered=(text:string,needles:string[])=>{let cursor=-1;for(const needle of needles){const next=text.indexOf(needle,cursor+1);check(next>cursor,'ordering '+needle);cursor=next}};
export type Recovery2PrivatePins={entrySha256:string;wrapperSha256:string;privateConfigSha256:string};

export function reviewM78ReadonlyRecovery2PrivateSources(entry:string,wrapper:string,runner:string,pins:Recovery2PrivatePins){
 check(sha(entry)===pins.entrySha256&&sha(wrapper)===pins.wrapperSha256,'exact helper pins');
 check(pins.privateConfigSha256==='39a9a9ce6820ad75956ffadb1f23f80359d41c72b18f52674271c44e542d0f8a','approved encrypted config pin');
 for(const forbidden of ['process.env','Bun.env','Deno.env','child_process','exec(','spawn(','console.error','console.log(body','unlink(lockPath'])check(!entry.includes(forbidden),'entry secret/process boundary '+forbidden);
 check(entry.includes("gate.status==='m78_readonly_recovery2_execution_admitted'")&&entry.includes('gate.applicationPostRequests===0')&&entry.includes('gate.workspaceId===input.roster.workspaceId'),'entry exact admission');
 check(entry.includes("failedRecoveryJournalText:'.superpowers/m78-continuation4-readonly-recovery.jsonl'")&&entry.includes("failedRecoveryDiagnosticText:'.superpowers/m78-continuation4-readonly-recovery-diagnostics.jsonl'")&&entry.includes("failedRecoveryReviewText:'evaluations/research-qa/m78-readonly-failure-review2-result.json'"),'preserved failure inputs');
 ordered(entry,['const gateText=await readFile(gatePath','for(const p of gate.pins)','const runtime=JSON.parse','const sourceText=await readFile','const loaded=Object.fromEntries','await verifyM78ReadonlyRecovery2PreAuth(admission)','const expectedSubjects=Object.fromEntries','gate.privateConfigSha256','for(const p of Object.values(paths))','lock=await open(lockPath','runM78Continuation4ReadonlyRecovery2']);
 check(entry.includes("runtime.status==='m78_get_route_deployed_runtime_verified'")&&entry.includes('runtime.ready.schemaVersion===21')&&entry.includes('age>=0&&age<15*60*1000')&&entry.includes('source.runtime.commit===runtime.commit&&source.runtime.deploymentId===runtime.deploymentId'),'runtime/source binding');
 check(entry.includes('for(const p of gate.pins)check(sha(await readFile(p.path))===p.sha256)')&&entry.includes('currentSourcePins:source.sourcePins')&&entry.includes('load:async(p:string)=>new Uint8Array(await readFile(p))'),'source pin rehash input');
 check(entry.includes("gate.privateConfigSha256==='"+pins.privateConfigSha256+"'")&&entry.includes("sha(await readFile('C:/Users/nimab/Neuvetra/m63-runtime/recovery/m63-private-config.json.dpapi'))===gate.privateConfigSha256"),'entry encrypted config binding');
 check(entry.includes("check(Object.values(paths).includes(p as any))")&&entry.includes("exclusive?'wx':'a'")&&entry.includes('await f.sync()'),'bounded exclusive IO');
 check(entry.includes("open(lockPath,'wx',0o600)")&&entry.includes("lock.writeFile('{\"profile\":\"m78-readonly-recovery2-exclusive-v1\"}\\n')")&&entry.includes('await lock.sync()')&&entry.includes('Keep the lock as a durable no-replay marker'),'durable recovery2 lock');
 check(entry.includes("AUTH+'/auth/v1/token?grant_type=password'")&&entry.includes("AUTH+'/auth/v1/logout?scope=local'")&&!entry.includes('/logout?scope=global'),'fixed auth and local logout');
 check(entry.includes("runM72Journey({...input,mode:'baseline'}")&&entry.includes('load:async()=>null')&&entry.includes('save:async value=>{captured=value}')&&entry.includes('result.applicationPostRequests===0')&&entry.includes('result.allCreatedAuthSessionsClosed===true')&&entry.includes('canonical(captured?.baseline)===canonical(expected)'),'read-only legacy verification');
 check(count(entry,'console.log(')===2&&entry.includes('failureStage:result.failureStage,failureCategory:result.failureCategory')&&entry.includes("{status:'failed',stage:'readonly_recovery2_entry',successNotInferred:true}"),'bounded entry output');

 const expectedPaths=['journal','diagnostics','rawCapture','observation'];for(const name of expectedPaths)check(runner.includes(name+":"),'runner path '+name);check(runner.includes("export const M78_READONLY_RECOVERY2_LOCK = M78_READONLY_RECOVERY2_PATHS.journal + '.lock'"),'runner lock contract');
 check(runner.includes("rawCapture: '.superpowers/m78-continuation4-readonly-recovery2-raw-capture.jsonl'")&&runner.includes('await input.io.append(M78_READONLY_RECOVERY2_PATHS.rawCapture'),'raw capture uses whitelisted IO path');

 for(const forbidden of ['$env:','Write-Host','$errors.Result','Write-Output $errors','Remove-Item','Start-Process','Invoke-WebRequest','Invoke-RestMethod'])check(!wrapper.includes(forbidden),'wrapper secret/process boundary '+forbidden);
 check(wrapper.includes("[ValidatePattern('^[a-f0-9]{64}$')]")&&wrapper.includes("path='.superpowers/m78-readonly-recovery2-execution-admission.json';sha256=$AdmissionSha256"),'safe exact admission input');
 check(wrapper.includes("$gate.status -cne 'm78_readonly_recovery2_execution_admitted'")&&wrapper.includes("$source.status -cne 'm78_continuation4_readonly_recovery2_source_admitted'")&&wrapper.includes("$gate.workspaceId -cne '8b90c706-1710-494d-b12d-02eef88eacb7'")&&wrapper.includes('$runtime.autodeploy -ne $false')&&wrapper.includes('$runtime.ready.schemaVersion -ne 21')&&wrapper.includes('$age.TotalMinutes -ge 15'),'wrapper admission/runtime/source');
 check(wrapper.includes('StartsWith($workspace+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)')&&wrapper.includes('Get-FileHash -LiteralPath $resolved -Algorithm SHA256')&&wrapper.includes('Hash.ToLowerInvariant() -cne $pin.sha256'),'contained pinned reads');
 for(const required of ['.superpowers/m78-private-readonly-recovery2.ps1','.superpowers/m78-readonly-recovery2-entry.ts','tools/staging/check-m78-continuation4-readonly-recovery2.ts'])check(wrapper.includes(required),'required source '+required);
 for(const name of ['m78-continuation4-readonly-recovery2.jsonl','m78-continuation4-readonly-recovery2-diagnostics.jsonl','m78-continuation4-readonly-recovery2-observation.json','m78-continuation4-readonly-recovery2-raw-capture.jsonl','m78-continuation4-readonly-recovery2.jsonl.lock'])check(wrapper.includes(name),'exclusive preflight '+name);
 ordered(wrapper,['$gate=Read-Pinned','foreach($pin in $gate.pins)','$runtime=Read-Pinned','$source=Read-Pinned','foreach($pin in $source.sourcePins)','execution exists','$gate.privateConfigSha256','Add-Type -AssemblyName System.Security','ProtectedData]::Unprotect','[Array]::Clear','$start=[Diagnostics.ProcessStartInfo]::new()','$process.StandardInput.Write','$data=$null','$process.WaitForExit()','Write-Output $output.Result']);
 check(wrapper.includes("$gate.privateConfigSha256 -cne '"+pins.privateConfigSha256+"'")&&wrapper.includes("Get-FileHash -LiteralPath 'C:/Users/nimab/Neuvetra/m63-runtime/recovery/m63-private-config.json.dpapi'")&&wrapper.includes('ProtectedData]::Unprotect')&&wrapper.includes('[Array]::Clear($clearBytes,0,$clearBytes.Length)'),'approved DPAPI only');
 check(wrapper.includes("$start.FileName='C:/Users/nimab/.bun/bin/bun.exe'")&&wrapper.includes("$start.ArgumentList.Add('run')")&&wrapper.includes('.superpowers/m78-readonly-recovery2-entry.ts')&&wrapper.includes('$start.UseShellExecute=$false')&&wrapper.includes('$start.CreateNoWindow=$true'),'fixed hidden child');
 check(wrapper.includes('$start.RedirectStandardInput=$true')&&wrapper.includes('$start.RedirectStandardOutput=$true')&&wrapper.includes('$start.RedirectStandardError=$true')&&wrapper.includes('ConvertTo-Json -Depth 20 -Compress')&&wrapper.includes("Write-Output 'Read-only recovery failed; sensitive diagnostics withheld.'")&&wrapper.includes("Write-Output 'Read-only recovery unavailable; sensitive diagnostics withheld.'"),'private stdin and withheld diagnostics');
 return{status:'m78_readonly_recovery2_private_independent_review_passed',entrySha256:pins.entrySha256,wrapperSha256:pins.wrapperSha256,actualExecution:false,dpapiUsed:false,networkUsed:false,databaseUsed:false,providerUsed:false};
}
