import pathlib,json,hashlib,datetime
H=lambda b:hashlib.sha256(b).hexdigest()
def canonical(v):return json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':'))
def hv(v):return H(canonical(v).encode())
obs_path=pathlib.Path('.superpowers/m78-timeout-observation.json');obs_bytes=obs_path.read_bytes();assert H(obs_bytes)=='995f91359f1b5ce38ad5b2f1324194c24c222a73ef2f2108944b6a4bf1797d67';o=json.loads(obs_bytes)
journal_bytes=pathlib.Path('.superpowers/m78-hosted-journey.jsonl').read_bytes();assert H(journal_bytes)=='d3301eb226c0cae4428c1e20cde4e2afdcf572b622e96d690cc8c262d6e44058';events=[json.loads(x)for x in journal_bytes.decode().splitlines()];assert len(events)==72
prev=None
for i,event in enumerate(events):
 body={k:v for k,v in event.items()if k!='sha256'};assert body['sequence']==i+1 and body['previousSha256']==prev and hv(body)==event['sha256'];prev=event['sha256']
intent=events[62];assert intent['kind']=='post_intent'and intent['data']['name']=='m78_initial_blocked_inventory'and intent['data']['role']=='manager1';assert not any(e['kind']in('post_outcome','post_verified')and e['data'].get('name')==intent['data']['name']for e in events);assert events[-1]['data']['status']=='failed'
backup_bytes=pathlib.Path('.superpowers/m78-actual20-20260922-backup.jsonl').read_bytes();assert H(backup_bytes)=='0ee30fa42dd303502b5b1b974408a75ad00079512c910883be20f45d78dbbbd5';backup=json.loads(backup_bytes.decode().strip().splitlines()[1]);company='8b90c706-1710-494d-b12d-02eef88eacb7';actor='7f0c488a-a645-4a9a-97b1-f043e77322a8';request={k:v for k,v in intent['data']['request'].items()if k!='idempotencyKey'};r=o['request'];v=o['version'];p=v['payload'];head=o['heads'];audit=o['audits']
assert o['status']=='m78_timed_out_save_confirmed_committed'and o['readOnly']is True and o['identity']=={'database':'postgres','actor':'postgres','read_only':'on'}and o['journalSha256']==H(journal_bytes)and o['intentSequence']==63 and o['companyId']==company and o['actor']==actor and o['applicationWrites']==o['authSessionsCreated']==0
assert r['company_id']==company and r['actor_id']==actor and r['kind']=='save'and r['family']=='inventory'and r['stream_id']is None and r['idempotency_key']==intent['data']['request']['idempotencyKey'];assert r['fingerprint']==hv({'operation':'save','actor':actor,'companyId':company,'family':'inventory','streamId':None,'request':request})
assert r['record_id']==v['id']==p['id']=='3e45de5d-d312-4a22-8418-35cb740a3a12'and v['company_id']==p['companyId']==company and v['created_by']==p['createdBy']==actor and v['family']==p['family']=='inventory'and v['version']==p['version']==1
assert v['previous_version_id']is None and p['previousVersionId']is None and p['previousVersionSha256']is None and v['stream_id']==p['streamId']and v['coverage_version_id']==p['activity']['binding']['coverageVersionId']
assert hv({**p['activity'],'expectedVersionId':p['previousVersionId'],'expectedVersionSha256':p['previousVersionSha256'],'expectedDependencySha256':p['dependencies']['dependencySha256'],'correctionReason':p['correctionReason']})==hv(request)
assert hv(p['activity'])==v['input_sha256']==p['inputSha256'];assert hv({k:p[k]for k in ['activity','dependencies','statements','findings','reconciliation']})==p['contentSha256']==v['content_sha256'];assert hv({k:val for k,val in p.items()if k not in ['versionSha256','review']})==p['versionSha256']==v['version_sha256']=='977fdd9d6a5cffb07bea34ff3bee2afaadfe3cf120440cc148a2ed45501bee6e';assert json.loads(v['export_text'])==p
assert len(head)==len(audit)==1 and head[0]['company_id']==audit[0]['company_id']==company and head[0]['family']=='inventory'and head[0]['id']==v['stream_id']and head[0]['version_id']==v['id']and head[0]['revision']==1
assert audit[0]['kind']=='save'and audit[0]['record_id']==v['id']and audit[0]['record_sha256']==v['version_sha256']and audit[0]['actor_id']==actor
new={'scope1_audit','scope1_heads','scope1_process_discoveries','scope1_reports','scope1_requests','scope1_reviews','scope1_statements','scope1_versions'};old_content=[e for e in o['content']['entries']if e['table']not in new];assert old_content==backup['content']['entries']and len(old_content)==377 and hv(old_content)==backup['content']['sha256'];current={t['name']:t for t in o['inventory']['tables']};assert len(current)==121
for old in backup['inventory']['tables']:
 if old['name']=='schema_migrations':continue
 actual=current[old['name']];assert actual['count']==old['count']and actual['sha256']==old['sha256']and actual['rowHashes']==old['rowHashes']
for table in new:assert current[table]['count']==(1 if table in {'scope1_heads','scope1_versions','scope1_requests','scope1_audit'}else 0)
assert current['schema_migrations']['count']==21
assert o['createdAt']>events[-1]['createdAt'];intents=[e for e in events if e['kind']=='post_intent'];outcomes=[e for e in events if e['kind']=='post_outcome'];assert len(intents)==4 and len(outcomes)==3;assert all(e['data']['status']==e['data']['expected']and e['data']['status']!=201 for e in outcomes)
result={'status':'m78_independent_timed_out_save_commit_reconciled','createdAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'reviewerId':'/root/resume_recovery','observationSha256':H(obs_bytes),'journalSha256':H(journal_bytes),'backupSha256':H(backup_bytes),'originalJournalStillFailed':True,'journalEvents':72,'originalPostIntents':4,'originalRecordedRefusals':3,'originalSaveResponseAbsent':True,'laterDatabaseCommitConfirmed':True,'versionId':v['id'],'versionSha256':v['version_sha256'],'exactIdempotencyActorRequestVersionHeadAuditLink':True,'priorTablesPreserved':112,'priorContentEntriesPreserved':377,'newTableCountsVerified':8,'observationReadOnly':True,'reviewHostedCalls':0,'reviewCredentialReads':0,'safeContinuationBoundary':'Do not repeat original saved inventory. Admit a separate continuation from exact observed inventory1 and originalfailed journal; validate all remaining operations and sessions separately.'}
pathlib.Path('evaluations/research-qa/m78-timeout-actual-independent-result.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result))
