import {test,expect} from 'bun:test'
import {readFile,mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {m78JourneySourcePins,JOURNEY_RESOLVER_ROOTS} from '../../tools/staging/m78-journey-source-pins'
const sha=(v:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(v).digest('hex');
test('140 current pins retain original127 closure except reviewed helper and add exact13 resolver inputs',async()=>{
 const bytes=await readFile('evaluations/research-qa/m78-hosted-journey-preparation.json');expect(sha(bytes)).toBe('e1be639d0a5c9bcc1832346dc59334a3e93acf2aa774952d01f825bdd214b8a3');const prior=JSON.parse(bytes.toString()),pins=await m78JourneySourcePins();expect(prior.sourcePins.length).toBe(127);expect(pins.length).toBe(140);expect(JOURNEY_RESOLVER_ROOTS.length).toBe(13);expect(pins).toEqual(await m78JourneySourcePins());expect(pins.map(p=>p.path)).toEqual([...new Set(pins.map(p=>p.path))].sort());
 expect(pins.filter(p=>!prior.sourcePins.some((o:any)=>o.path===p.path)).map(p=>p.path)).toEqual([...JOURNEY_RESOLVER_ROOTS].sort());expect(pins.filter(p=>prior.sourcePins.some((o:any)=>o.path===p.path&&o.sha256!==p.sha256)).map(p=>p.path)).toEqual(['tools/staging/m78-journey-source-pins.ts']);for(const p of pins)expect(sha(await readFile(p.path))).toBe(p.sha256);
 const map=new Map(pins.map(p=>[p.path,p.sha256])),pkg=JSON.parse(await readFile('packages/neuvetra-database/package.json','utf8'));expect(pkg.name).toBe('@neuvetra/database');expect(pkg.exports['.']).toBe('./src/index.ts');expect(map.has('packages/neuvetra-database/src/index.ts')).toBe(true);for(const path of JOURNEY_RESOLVER_ROOTS)expect(map.has(path)).toBe(true);expect(pins.filter(p=>p.path.startsWith('packages/neuvetra-database/src/migrations/')).length).toBe(21);
 const expectedChain=[['apps/site-api/tsconfig.json','../../config/typescript/api.json'],['config/typescript/api.json','../../tsconfig.base.json'],['packages/neuvetra-database/tsconfig.json','../../tsconfig.base.json'],['apps/site-web/tsconfig.app.json','../../config/typescript/web.json'],['apps/site-web/tsconfig.node.json','../../config/typescript/vite.json']];for(const [path,parent]of expectedChain)expect(JSON.parse(await readFile(path!,'utf8')).extends).toBe(parent);expect(JSON.parse(await readFile('package.json','utf8')).workspaces).toEqual(['apps/*','packages/*']);
 const changed=structuredClone(pkg);changed.exports['.']='./src/reviewer-redirect.ts';expect(sha(JSON.stringify(changed))).not.toBe(map.get('packages/neuvetra-database/package.json'));
});
test('isolated fresh Bun resolver redirects with exports metadata alone and invalidates mapped package bytes',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'neuvetra-m78-resolver-review-'));try{const pkgDir=join(directory,'node_modules','@neuvetra','database'),src=join(pkgDir,'src');await mkdir(src,{recursive:true});const first='export const marker="original";\n',second='export const marker="redirected";\n';await writeFile(join(src,'index.ts'),first);await writeFile(join(src,'redirect.ts'),second);const entry=join(directory,'entry.ts');await writeFile(entry,'import {marker} from "@neuvetra/database";console.log(marker);\n');const metadata={name:'@neuvetra/database',version:'0.0.0',type:'module',exports:{'.':'./src/index.ts'}};await writeFile(join(pkgDir,'package.json'),JSON.stringify(metadata));const reviewed=sha(await readFile(join(pkgDir,'package.json'))),originalBodies=[sha(first),sha(second)];const invoke=async()=>{const child=Bun.spawn([process.execPath,entry],{cwd:directory,stdout:'pipe',stderr:'pipe'});const [output,error,exit]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);expect(exit).toBe(0);expect(error).toBe('');return output.trim()};expect(await invoke()).toBe('original');metadata.exports['.']='./src/redirect.ts';await writeFile(join(pkgDir,'package.json'),JSON.stringify(metadata));expect(await invoke()).toBe('redirected');expect([sha(await readFile(join(src,'index.ts'))),sha(await readFile(join(src,'redirect.ts')))]).toEqual(originalBodies);expect(sha(await readFile(join(pkgDir,'package.json')))).not.toBe(reviewed)}finally{await rm(directory,{recursive:true,force:true})}
});
test('unchanged wrapper validates reviewed actual closure before private credential unseal',async()=>{
 const snapshot=JSON.parse(await readFile('operations/agent-improvement/snapshots/M78-HOSTED-JOURNEY-REVIEW-01-CANDIDATE4-ACCEPTED.json','utf8')),entry=snapshot.artifacts.find((a:any)=>a.path==='.superpowers/m78-private-journey.ps1');expect(entry.sha256).toBe('41158e4212ac4cf14f0b09cfe29aedc2fd4c0c7b478860d5a215e309254cbc6c');expect(sha(entry.text)).toBe(entry.sha256);const text=entry.text as string,unseal=text.indexOf('[Security.Cryptography.ProtectedData]::Unprotect');expect(unseal).toBeGreaterThan(0);for(const marker of ['m78_independent_hosted_journey_preparation_passed','reviewed closure mismatch','complete source closure changed','source gate mismatch','prior closure changed']){expect(text.indexOf(marker)).toBeGreaterThan(0);expect(text.indexOf(marker)).toBeLessThan(unseal)}expect(text).toContain('$review.reviewerId -ceq');expect(text).toContain('foreach($pin in $admission.sourcePins)');expect(text).toContain('Read-PinnedFile $pin');expect(text).toContain('$pinProcess.ExitCode -ne 0');
});
