/** Root-authorized actual20 recovered fictional application. Read-only; no DPAPI/host/provider. */
import {readFile,writeFile} from 'node:fs/promises'
import {createHash} from 'node:crypto'
import {createPostgresConnection,HostedWorkspaceDatabase,readMigrationManifest} from '../../packages/neuvetra-database/src/index'
import {inventory,content,sameExactInventory,sameContent,hash,runtimeSafe} from '../../tools/staging/m78-inventory'
import {pinnedReceipt,verifyHostedApplicationRestore} from '../../tools/staging/m78-hosted-database'
import {auditLegacyStagingExposure} from '../../packages/neuvetra-database/src/staging-audit'
import {createM73Authority} from '../../apps/site-api/src/calculation/m73-authority'
import {createM74Authority} from '../../apps/site-api/src/calculation/m74-authority'
import {createM76Authority} from '../../apps/site-api/src/calculation/m76-authority'
import {createM77Authority} from '../../apps/site-api/src/calculation/m77-authority'
import {createCorporateInventoryRoutes} from '../../apps/site-api/src/workspace/m71-routes'
import {createM73Routes} from '../../apps/site-api/src/workspace/m73-routes'
import {createM74Routes} from '../../apps/site-api/src/workspace/m74-routes'
import {createM75Routes} from '../../apps/site-api/src/workspace/m75-routes'
import {createM76Routes} from '../../apps/site-api/src/workspace/m76-routes'
import {createM77Routes} from '../../apps/site-api/src/workspace/m77-routes'
import {createSourceWorksheetRoutes} from '../../apps/site-api/src/workspace/m66-routes'
import {createSourceWorksheetReportRoutes} from '../../apps/site-api/src/workspace/m66-report-routes'
import {createWorkspaceRoutes} from '../../apps/site-api/src/workspace/routes'
import {createWorkspaceStore} from '../../apps/site-api/src/workspace/service'
import {decodeCorporateRegister} from '../../apps/site-web/src/lib/m71-api'
import {decodeGasRegister} from '../../apps/site-web/src/lib/m73-api'
import {decodeMobileRegister} from '../../apps/site-web/src/lib/m74-api'
import {fleetRegisterRequest,fleetReportDownload,fleetReportSnapshotDownload} from '../../apps/site-web/src/lib/m75-api'
import {stationaryRegisterRequest,stationaryReportDownload,stationaryReportSnapshotDownload} from '../../apps/site-web/src/lib/m76-api'
import {decodeGeneratorRegister} from '../../apps/site-web/src/lib/m76-diesel-api'
import {decodeFugitiveRegister} from '../../apps/site-web/src/lib/m77-api'
const name='m78_ops_actual20_20260917c',project='icockcoguyadhryzydvl',origin='http://127.0.0.1:47821',check=(v:unknown,m:string)=>{if(!v)throw Error(m)},sha=(b:string|Uint8Array)=>createHash('sha256').update(b).digest('hex')
const backupPath='.superpowers/m78-actual20-backup.jsonl',restorePath='.superpowers/m78-actual20c-hosted-restore.jsonl',localPath='.superpowers/m78-actual20c-local-restore.jsonl'
const backupBytes=await readFile(backupPath),restoreBytes=await readFile(restorePath),localBytes=await readFile(localPath),backup=pinnedReceipt(backupBytes.toString('utf8'),'backup'),restored=pinnedReceipt(restoreBytes.toString('utf8'),'restore')
check(sha(backupBytes)==='54ab59711c68eca841b4a894526bd200ae482364cdcabcee834ba6ccc0bc5648'&&restored.database===name&&restored.status==='m78_hosted_snapshot_restored_locally','Original successful restore receipt required')
check(restored.archiveSha256===backup.archiveSha256&&restored.snapshotSha256===backup.snapshotSha256&&restored.dumpSha256===backup.dumpSha256&&restored.sourceBackupCreatedAt===backup.createdAt,'Original archive/snapshot/dump provenance differs')
sameExactInventory(backup.inventory,restored.sourceFullInventory);verifyHostedApplicationRestore(backup.inventory,restored.inventory,restored.applicationRestoreComparison);sameContent(backup.content,restored.content)
const localEvents=localBytes.toString('utf8').trim().split('\n').map(x=>JSON.parse(x));check(localEvents.length===2&&localEvents[1].status==='m78_local_application_restored'&&localEvents[1].database===name&&localEvents[1].bundleSha256===restored.transferBundleSha256&&localEvents[1].bundleSha256===restored.bundleSha256,'Original local transfer journal differs');sameExactInventory(localEvents[1].inventory,restored.inventory);sameContent(localEvents[1].content,restored.content)
const admin=createPostgresConnection('postgres://supabase_admin@127.0.0.1:55472/'+name,{tls:false,maxConnections:1}),runtime=createPostgresConnection('postgres://neuvetra_runtime@127.0.0.1:55472/'+name,{tls:false,maxConnections:1}),db=new(HostedWorkspaceDatabase as any)(runtime,project),families:any[]=[],gas=createM73Authority(),mobile=createM74Authority(),diesel=createM76Authority(),fugitive=createM77Authority()
const savedFetch=globalThis.fetch
try{
 const before=await admin.transaction(async tx=>{await tx.exec('set transaction isolation level repeatable read read only');return {inventory:await inventory(tx),content:await content(tx,20)}});sameExactInventory(restored.inventory,before.inventory);sameContent(restored.content,before.content)
 const manifest=await readMigrationManifest(),receipts=(await admin.query<{name:string;sha256:string}>('select name,sha256 from neuvetra.schema_migrations order by name')).rows;check(receipts.length===20&&receipts.every((r,i)=>r.name===manifest[i]!.name&&r.sha256===manifest[i]!.sha256),'Exact retained20 receipts differ');await runtimeSafe(runtime);check((await auditLegacyStagingExposure(admin)).legacyContainmentVerified,'Legacy containment changed')
 const actors=(await admin.query<any>("select distinct on(m.company_id)m.company_id,m.user_id from neuvetra.company_members m join neuvetra.staging_access a on a.company_id=m.company_id and a.user_id=m.user_id where a.active order by m.company_id,case m.role when 'owner' then 0 when 'admin' then 1 else 2 end,m.user_id")).rows
 for(const actor of actors){
  const company=actor.company_id as string,user=actor.user_id as string,deps={database:db,origin,validateUser:async(t:string)=>t==='fictional-actual20-reader'?{id:user,email:null,phone:null,fullName:null}:null},a={accessToken:'fictional-actual20-reader',userId:user,role:'owner' as const}
  const calls=(family:string,route:(r:Request)=>Promise<Response>)=>{const counter={family,versionIds:[]as string[],reportIds:[]as string[],authorizedGetRequests:0,exactDownloadRequests:0,semanticAndDownloadVerification:true,companyId:company};const get=async(path:string)=>{counter.authorizedGetRequests++;const r=await route(new Request(origin+'/workspace/'+company+path,{headers:{authorization:'Bearer fictional-actual20-reader'}}));check(r.status===200,'Authorized '+family+' GET failed '+path+' '+r.status);check((r.headers.get('cache-control')??'').includes('no-store'),'Cached runtime download');return r};const exact=async(path:string,expected:string|Uint8Array)=>{const r=await get(path),b=new Uint8Array(await r.arrayBuffer());check(sha(b)===sha(expected),'Exact '+family+' bytes differ');counter.exactDownloadRequests++;return b};return {counter,get,exact}}
  if(!families.some(x=>x.family==='legacy_electricity')){
   const reg=await db.findSourceElectricityWorksheet(user,company);if(reg?.versions.length){const sr=createSourceWorksheetRoutes(deps),rr=createSourceWorksheetReportRoutes(deps),c=calls('legacy_electricity',r=>new URL(r.url).pathname.includes('/reports')?rr(r):sr(r));const returned=await(await c.get('/source-electricity-worksheet')).json();check(hash(returned)===hash(reg),'Legacy deterministic register differs');const reports=await db.findSourceWorksheetReports(user,company),r=reports?.reports?.at(-1)??reports?.at?.(-1);check(r,'Existing electricity report absent');const id=r.id,raw=(await admin.query<any>('select source_version_id,report_bytes from neuvetra.source_worksheet_reports where id=$1',[id])).rows[0];const meta=await(await c.get('/source-electricity-worksheet/reports/'+id)).json();check(meta.id===id,'Electricity report identity');await c.exact('/source-electricity-worksheet/reports/'+id+'/download',new Uint8Array(raw.report_bytes));c.counter.versionIds=[raw.source_version_id];c.counter.reportIds=[id];families.push(c.counter)}
  }
  const cov=await db.findCorporateInventory(user,company)
  if(cov&&!families.some(x=>x.family==='corporate')){const c=calls('corporate',createCorporateInventoryRoutes(deps)),decoded=await decodeCorporateRegister(await(await c.get('/corporate-inventories')).json(),company),v=decoded.versions.at(-1)!;check(v.version===8&&v.snapshot.facilities.length===3,'Completed-M77 corporate8 expected');await c.get('/corporate-inventories/'+v.inventoryId+'/versions/'+v.id);const raw=(await admin.query<any>('select export_text from neuvetra.corporate_inventory_versions where id=$1',[v.id])).rows[0];await c.exact('/corporate-inventories/'+v.inventoryId+'/versions/'+v.id+'/coverage-export',raw.export_text);c.counter.versionIds=[v.id];families.push(c.counter)}
  for(const spec of [{family:'natural_gas',prefix:'/stationary-natural-gas',table:'stationary_gas',find:()=>db.findStationaryGas(user,company,gas),route:createM73Routes({...deps,authority:gas}),decode:decodeGasRegister},{family:'mobile_diesel',prefix:'/mobile-diesel',table:'mobile_diesel',find:()=>db.findMobileDiesel(user,company,mobile),route:createM74Routes({...deps,authority:mobile}),decode:decodeMobileRegister},{family:'stationary_diesel',prefix:'/stationary-diesel',table:'stationary_diesel',find:()=>db.findStationaryDiesel(user,company,diesel),route:createM76Routes({...deps,authorities:{gas,diesel}}),decode:decodeGeneratorRegister}]){
   if(families.some(x=>x.family===spec.family))continue;const rawReg=await spec.find();if(!rawReg?.worksheets.length)continue;const c=calls(spec.family,spec.route),reg=await spec.decode(await(await c.get(spec.prefix)).json(),company),w=reg.worksheets.find((w:any)=>w.reports.length);check(w,'Saved source report missing');const v=w.versions.at(-1)!,r=w.reports.at(-1)!;await c.get(spec.prefix+'/'+w.worksheetId+'/versions/'+v.id);const row=(await admin.query<any>('select export_text from neuvetra.'+spec.table+'_versions where id=$1',[v.id])).rows[0];await c.exact(spec.prefix+'/'+w.worksheetId+'/versions/'+v.id+'/calculation-export',row.export_text);await c.exact(spec.prefix+'/'+w.worksheetId+'/reports/'+r.id+'/download',r.html);c.counter.versionIds=[v.id];c.counter.reportIds=[r.id];families.push(c.counter)
  }
  for(const spec of [{family:'fleet',prefix:'/controlled-fleet',table:'controlled_fleet',find:()=>db.findControlledFleet(user,company,mobile),route:createM75Routes({...deps,authority:mobile}),register:fleetRegisterRequest,html:fleetReportDownload,snapshot:fleetReportSnapshotDownload},{family:'stationary',prefix:'/stationary-equipment',table:'stationary_equipment',find:()=>db.findStationaryEquipment(user,company,{gas,diesel}),route:createM76Routes({...deps,authorities:{gas,diesel}}),register:stationaryRegisterRequest,html:stationaryReportDownload,snapshot:stationaryReportSnapshotDownload}]){
   if(families.some(x=>x.family===spec.family))continue;const r0=await spec.find();if(!r0?.versions.length)continue;const c=calls(spec.family,spec.route);globalThis.fetch=(async(input:any,init?:RequestInit)=>{check(typeof input==='string'&&input.startsWith('/workspace-api/workspace/'+company+spec.prefix)&&(!init?.method||init.method==='GET')&&!init?.body,'Restricted read-only native frontend transport');return c.get(input.slice(('/workspace-api/workspace/'+company).length))})as typeof fetch;const reg:any=await spec.register(a,company),v=reg.versions.at(-1),r=reg.reports.at(-1);check(v&&r,'Existing physical history absent');await c.get(spec.prefix+'/'+reg.rosterId+'/versions/'+v.id);const vr=(await admin.query<any>('select export_text from neuvetra.'+spec.table+'_versions where id=$1',[v.id])).rows[0];await c.exact(spec.prefix+'/'+reg.rosterId+'/versions/'+v.id+'/roster-export',vr.export_text);const rr=(await admin.query<any>('select payload from neuvetra.'+spec.table+'_reports where id=$1',[r.id])).rows[0].payload;check(await spec.snapshot(a,company,r)===rr.snapshotJson,'Historical physical proof/snapshot differs');c.counter.exactDownloadRequests++;check(await spec.html(a,company,r)===rr.html,'Historical physical proof/HTML differs');c.counter.exactDownloadRequests++;c.counter.versionIds=[v.id];c.counter.reportIds=[r.id];families.push(c.counter);globalThis.fetch=savedFetch
  }
  if(!families.some(x=>x.family==='fugitive')){const r0=await db.findFugitive(user,company,fugitive);if(r0?.population.versions.length){const c=calls('fugitive',createM77Routes({...deps,authority:fugitive})),reg=await decodeFugitiveRegister(await(await c.get('/fugitive-sources')).json(),company),v=reg.population.versions.at(-1)!,r=reg.population.reports.at(-1)!;check(v.version===4&&v.review?.decision==='accepted_bounded_reconciliation'&&r0.worksheets.length===5,'Completed-M77 accepted population4/five devices expected');const base='/fugitive-population/'+reg.population.rosterId;await c.get(base+'/versions/'+v.id);const row=(await admin.query<any>('select export_text from neuvetra.fugitive_versions where id=$1',[v.id])).rows[0];await c.exact(base+'/versions/'+v.id+'/calculation-export',row.export_text);await c.get(base+'/reports/'+r.id);await c.exact(base+'/reports/'+r.id+'/download',r.html);await c.exact(base+'/reports/'+r.id+'/snapshot',r.snapshotJson);c.counter.versionIds=[v.id];c.counter.reportIds=[r.id];families.push(c.counter)}}
 }
 // Corporate M71 has coverage exports, not reports. Verify the retained historical M60 corporate draft explicitly.
 const draft=(await admin.query<any>('select id,company_id,annual_inventory_version_id,report_bytes from neuvetra.inventory_draft_reports order by id limit 1')).rows[0];check(draft,'Existing M60 draft absent');const actor=actors.find((a:any)=>a.company_id===draft.company_id);check(actor,'Retained draft actor absent');const user=actor.user_id,app=createWorkspaceRoutes({allowedOrigins:[origin],validateUser:async()=>({id:user,email:null,phone:null,fullName:null}),store:createWorkspaceStore(db,async()=>{throw Error('Read-only')})});const corp=families.find(f=>f.family==='corporate');check(corp,'Corporate coverage absent');const path='/workspace/'+draft.company_id+'/annual-inventories/'+draft.annual_inventory_version_id+'/draft-reports';for(const suffix of ['/current','/'+draft.id+'/download']){corp.authorizedGetRequests++;const response=await app.handle(new Request(origin+path+suffix,{headers:{authorization:'Bearer fictional-actual20-reader'}}));check(response.status===200,'Authorized M60 draft failed '+response.status);if(suffix.endsWith('/download')){check(sha(new Uint8Array(await response.arrayBuffer()))===sha(new Uint8Array(draft.report_bytes)),'Retained M60 bytes differ');corp.exactDownloadRequests++}else check((await response.json()).id===draft.id,'Retained M60 identity differs')}corp.reportIds=[draft.id];corp.reportScope='historical M60 annual corporate draft, distinct from M71 coverage export';corp.reportCompanyId=draft.company_id
 const required=['legacy_electricity','corporate','natural_gas','mobile_diesel','fleet','stationary_diesel','stationary','fugitive'];check(required.every(f=>families.some(x=>x.family===f))&&families.length===8,'Eight families missing');for(const f of families)check(f.versionIds.length&&f.reportIds.length&&f.authorizedGetRequests>=f.versionIds.length+f.reportIds.length&&f.exactDownloadRequests>=f.reportIds.length,'Bounded IDs/counters inadequate')
 for(const t of ['companies','corporate_inventory_versions','fugitive_versions'])check((await runtime.query('select 1 from neuvetra.'+t+' limit 1')).rows.length===0,'No-claim runtime exposed rows')
 const after=await admin.transaction(async tx=>{await tx.exec('set transaction isolation level repeatable read read only');return{inventory:await inventory(tx),content:await content(tx,20)}});sameExactInventory(before.inventory,after.inventory);sameContent(before.content,after.content)
 const priorPath='evaluations/research-qa/m77-binding-root-acceptance.md';const priorBytes=await readFile(priorPath)
 const result={status:'m78_independent_actual_backup_recovery_passed',createdAt:new Date().toISOString(),reviewerId:'/root/m76_backend',project,database:name,schemaVersion:20,archiveSha256:backup.archiveSha256,snapshotSha256:backup.snapshotSha256,restoreReceiptSha256:sha(restoreBytes),localRestoreReceiptSha256:sha(localBytes),originalBackupJournalSha256:sha(backupBytes),actualArchiveRestoreVerified:true,completeApplicationBytesAndCatalogVerified:true,boundedSemanticReplayVerified:true,noMutationVerified:true,providerRecoveryExcluded:true,inventory:after.inventory,content:after.content,sourceFullInventory:backup.inventory,applicationRestoreComparison:restored.applicationRestoreComparison,semanticReplay:{fullHistoricalSemanticReplay:false,families},priorAcceptedClosure:{artifact:{path:priorPath,sha256:sha(priorBytes)},currentCompleteContentSha256:backup.content.sha256,preservationVerified:true},legacyContainmentVerified:true,runtimeNoClaimDenied:true,hostedCalls:false,decryption:false,databaseWrites:false,providerAuthentication:false,reactRendering:false}
 await writeFile('evaluations/research-qa/m78-actual20-recovery.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,database:name,tables:after.inventory.tables.length,content:after.content.entries.length,excluded:restored.applicationRestoreComparison.excludedDefaultAclCount,semanticReplay:result.semanticReplay}))
}finally{globalThis.fetch=savedFetch;await runtime.close();await admin.close()}