import {test,expect} from 'bun:test'
import {localSource} from '../../tools/staging/m78-backup'
import {sameFunctionsAfterUpgrade,PATH_FUNCTIONS,hash,REVIEWED_MIGRATION_SHA256,canonicalReceipts,type FunctionRow,type Inventory} from '../../tools/staging/m78-inventory'
import {validateLocalGate,type LocalUpgradeGate} from '../../tools/staging/m78-upgrade'
import {validateBundle} from '../../tools/staging/m78-restore'
import {verifyRehearsalAdmission,type RehearsalAdmission} from '../../tools/staging/m78-operators-native'
import {readFile} from 'node:fs/promises'
import {createHash} from 'node:crypto'
const digest='a'.repeat(64)
function gate():LocalUpgradeGate{const inventory:Inventory={tables:[{name:'schema_migrations',count:20,sha256:digest,rowHashes:Array(20).fill(digest)},...Array.from({length:112},(_,i)=>({name:'original_'+i,count:0,sha256:hash([]),rowHashes:[]}))],metadata:{functions:hash([])},catalogRowHashes:{functions:[]},functions:[],tableObjects:[],sequences:[],roles:[],memberships:[],defaultAcls:[],dependencies:[]};return {profile:'neuvetra.m78.local-upgrade-gate.v1',project:'icockcoguyadhryzydvl',database:'m78_qa_independent',createdAt:'2026-09-17T00:00:00.000Z',operatorId:'/root/m78_security',reviewerId:'/root/m76_backend',reviewSnapshotSha256:digest,migrationSha256:digest,baselineBundleSha256:digest,restoreReceiptSha256:digest,baselineInventory:inventory,baselineContent:{profile:'neuvetra.m78.recovery-content.v1',schemaVersion:20,entries:[],sha256:hash([])},localOnly:true}}
test('independent local source target checks refuse remote, runtime, hosted and wrong port',async()=>{const good={name:'m78_qa_independent',address:'127.0.0.1',port:55472,actor:'supabase_admin'},sql=(row:unknown)=>({query:async()=>({rows:[row]})}as any);expect((await localSource(sql(good))).name).toBe(good.name);for(const change of [{address:'192.0.2.1'},{port:5432},{port:55463},{actor:'neuvetra_runtime'},{name:'postgres'},{name:'m78_author_fixture'},{name:'m78_qa_x;drop'}])await expect(localSource(sql({...good,...change}))).rejects.toThrow()})
test('independent frozen pin admits exact gate and refuses null, identity, receipt and time drift',()=>{expect(REVIEWED_MIGRATION_SHA256).toBe('546673470c33da80dc1e0b377646fa09b921e1231535da7c1af43ec866d48736');const g=gate(),now=Date.parse('2026-09-17T00:01:00Z');expect(()=>validateLocalGate(g,digest,now)).not.toThrow();expect(()=>validateLocalGate({...g,migrationSha256:REVIEWED_MIGRATION_SHA256!},undefined,now)).not.toThrow();expect(()=>validateLocalGate(g,null,now)).toThrow();for(const change of [{reviewerId:g.operatorId},{reviewerId:' reviewer '},{operatorId:'operator\n'},{reviewSnapshotSha256:'not-a-snapshot-hash'},{baselineBundleSha256:'b'.repeat(63)},{restoreReceiptSha256:null},{migrationSha256:'b'.repeat(64)},{createdAt:'2026-09-17T00:01:00.001Z'}])expect(()=>validateLocalGate({...g,...change}as any,digest,now)).toThrow()})
test('schema21 receipt check refuses explicitly absent pin before supplied SQL connection',async()=>{let reads=0;await expect(canonicalReceipts({query:async()=>{reads++;throw Error('SQL should not be called')}}as any,21,null)).rejects.toThrow();expect(reads).toBe(0)})
test('all six exact function changes keep bodies and ACLs; additional SET or security flags refuse',()=>{const before:FunctionRow[]=PATH_FUNCTIONS.map(signature=>({signature,owner:'postgres',prosecdef:false,proconfig:null,acl:[{grantee:'postgres',privilege:'EXECUTE'}],definition:`CREATE OR REPLACE FUNCTION ${signature}\n RETURNS text\n LANGUAGE sql\nAS $function$SELECT 'π'$function$\n`})),line=" SET search_path TO 'pg_catalog', 'pg_temp'\n",after=before.map(f=>({...f,proconfig:['search_path=pg_catalog, pg_temp'],definition:f.definition.replace('AS $function$',line+'AS $function$')}));expect(()=>sameFunctionsAfterUpgrade(before,after)).not.toThrow();for(const mutate of [(v:FunctionRow[])=>v[0].definition=v[0].definition.replace('AS $function$',line+'AS $function$'),(v:FunctionRow[])=>v[0].definition=v[0].definition.replace('π','replacement'),(v:FunctionRow[])=>v[0].prosecdef=true,(v:FunctionRow[])=>v[0].acl=[{grantee:'PUBLIC',privilege:'EXECUTE'}]]){const bad=structuredClone(after);mutate(bad);expect(()=>sameFunctionsAfterUpgrade(before,bad)).toThrow()}})
test('untrusted restore bundle refuses without database connection or target creation',()=>{const raw={profile:'neuvetra.m78.local-application-bundle.v1',project:'foreign',schemaVersion:20,migrationSha256:null};expect(()=>validateBundle(raw as any,hash(raw))).toThrow()})
test('exact seven-source rehearsal admission refuses reviewer, pin, stale time, duplicates and missing sources before native work',async()=>{const paths=['inventory','backup','upgrade','restore','replay','operators.test','operators-native'].map(n=>'tools/staging/m78-'+n+'.ts'),g:RehearsalAdmission={profile:'neuvetra.m78.local-rehearsal-admission.v1',createdAt:new Date().toISOString(),reviewerId:'/root/m76_backend',reviewSnapshotSha256:digest,migrationSha256:REVIEWED_MIGRATION_SHA256!,reviewedArtifacts:await Promise.all(paths.map(async path=>({path,sha256:createHash('sha256').update(await readFile(path)).digest('hex')}))),localOnly:true};await expect(verifyRehearsalAdmission(g)).resolves.toBeUndefined();for(const change of [{reviewerId:'/root/m78_security'},{migrationSha256:digest},{localOnly:false},{createdAt:new Date(Date.now()-14400001).toISOString()},{reviewedArtifacts:g.reviewedArtifacts.slice(1)},{reviewedArtifacts:[g.reviewedArtifacts[0],...g.reviewedArtifacts.slice(0,-1)]},{reviewedArtifacts:g.reviewedArtifacts.map((a,i)=>i===6?{...a,sha256:digest}:a)}])await expect(verifyRehearsalAdmission({...g,...change}as any)).rejects.toThrow()})
