import {test,expect} from 'bun:test'
import {createM78QaFixture} from './m78-integrated-fixture'
import {HostedWorkspaceDatabase,type WorkspaceConnection} from '../../packages/neuvetra-database/src/index'
import {M78_REVIEWED_POLICY} from '../../packages/neuvetra-database/src/m78-policy'
import {m78CanonicalJson,m78ReportHashPayload} from '../../packages/neuvetra-database/src/m78-validation'
import {m78Hash} from '../../packages/neuvetra-database/src/m78'
import {m78RenderReport} from '../../packages/neuvetra-database/src/m78-report'
import {decodeScope1Register,decodeScope1Report} from '../../apps/site-web/src/lib/m78-api'
import {createM78Routes} from '../../apps/site-api/src/workspace/m78-routes'
import {createHash} from 'node:crypto'
const target=process.env.M78_QA_CI_BASELINE_URL,enabled=process.env.M78_QA_POSITIVE_NATIVE==='1',sha=(s:string)=>createHash('sha256').update(s).digest('hex')
test.skipIf(!target||!enabled)('M78 independent positive runtime replay and coordinated historical-review forgery refusal',async()=>{
 const receiptBytes=await Bun.file('.superpowers/m78_author_native_1789620106488-result.json').arrayBuffer();expect(createHash('sha256').update(new Uint8Array(receiptBytes)).digest('hex')).toBe('e2cb73a1a3c80f4b2adb62d564ff8ab9eb02809444a5734794c3f64cb11732ae');const receipt=JSON.parse(new TextDecoder().decode(receiptBytes)),company=receipt.companyId,owner=receipt.users.owner
 const f=await createM78QaFixture(target!,'m78_qa_positive_'+Date.now()),routes=createM78Routes({database:f.database,authorities:f.authorities,policy:M78_REVIEWED_POLICY,origin:'http://127.0.0.1:47802',validateUser:async token=>token==='fictional-positive-owner'?{id:owner,email:null,phone:null,fullName:null}:null}),get=(suffix:string)=>routes(new Request('http://127.0.0.1:47802/workspace/'+company+'/'+suffix,{headers:{authorization:'Bearer fictional-positive-owner'}}))
 try{
  const registerResponse=await get('scope1-inventory');expect(registerResponse.status).toBe(200);const register=await decodeScope1Register(await registerResponse.json(),company);expect(register.proof.sourceVersions).toHaveLength(10);expect(register.reconciliation.status).toBe('reconciled_bounded_synthetic');expect(register.reconciliation.totals?.company.kgCo2eExact).toBe('126850.17632025');expect(register.reconciliation.totals?.company.kgCo2eDisplay).toBe('126850.1763')
  for(const [path,stream]of [['process-screen',register.process],['scope1-inventory',register.inventory]]as const){for(const meta of stream.reports){const base=path+'/'+stream.streamId+'/reports/'+meta.id,r=await get(base);expect(r.status).toBe(200);const report=await decodeScope1Report(await r.json(),company);expect(await(await get(base+'/download')).text()).toBe(report.html);expect(await(await get(base+'/snapshot')).text()).toBe(report.snapshotJson)}}
  const originals=(await f.operator.query<{id:string;payload:any}>('select id,payload from neuvetra.scope1_reports where company_id=$1 and family=$2',[company,'inventory'])).rows,pending=originals.find(r=>JSON.parse(r.payload.snapshotJson).review===null)!,accepted=originals.find(r=>JSON.parse(r.payload.snapshotJson).review!==null)!,laterReview=JSON.parse(accepted.payload.snapshotJson).review;expect(pending).toBeDefined();expect(accepted).toBeDefined()
  const before=(await f.operator.query<{text:string}>("select neuvetra.m67_canonical(to_jsonb(t))text from neuvetra.scope1_reports t where id=$1",[pending.id])).rows[0]!.text,auditBefore=(await f.operator.query<{text:string}>('select neuvetra.m67_canonical(to_jsonb(t))text from neuvetra.scope1_audit t where record_id=$1',[pending.id])).rows[0]!.text
  const forged=structuredClone(pending.payload),snapshot=JSON.parse(forged.snapshotJson);snapshot.review=laterReview;forged.createdAt=new Date(Date.parse(laterReview.reviewedAt)+1).toISOString();forged.snapshotJson=m78CanonicalJson(snapshot);forged.snapshotSha256=sha(forged.snapshotJson);forged.html=m78RenderReport(snapshot);forged.htmlSha256=sha(forged.html);forged.htmlByteLength=Buffer.byteLength(forged.html);forged.reportSha256=m78Hash(m78ReportHashPayload(forged))
  // Positive standalone control proves hashes, renderer and capture times are valid.
  // Retained native audit sequence, rather than bytes alone, must reject this history.
  expect((await decodeScope1Report(forged,company)).id).toBe(pending.id)
  const order=(await f.operator.query<{record_id:string;sequence:string}>('select record_id,sequence::text sequence from neuvetra.scope1_audit where record_id in($1,$2)',[pending.id,laterReview.id])).rows;expect(BigInt(order.find(x=>x.record_id===pending.id)!.sequence)<BigInt(order.find(x=>x.record_id===laterReview.id)!.sequence)).toBe(true)
  let refused=false,refusalMessage:string|null=null
  try{await f.operator.transaction(async tx=>{
   for(const table of ['scope1_reports','scope1_audit','scope1_requests'])await tx.exec('alter table neuvetra.'+table+' disable trigger m78_immutable')
   await tx.query('update neuvetra.scope1_reports set payload=$1::text::jsonb,report_sha256=$2,created_at=$3 where id=$4',[m78CanonicalJson(forged),forged.reportSha256,forged.createdAt,pending.id]);await tx.query('update neuvetra.scope1_audit set record_sha256=$1,created_at=$2 where record_id=$3',[forged.reportSha256,forged.createdAt,pending.id])
   const q=(await tx.query<{actor_id:string;stream_id:string;family:string}>('select actor_id,stream_id,family from neuvetra.scope1_requests where company_id=$1 and record_id=$2',[company,pending.id])).rows[0]!,request={versionId:forged.versionId,expectedVersionSha256:forged.versionSha256,expectedDecisionId:laterReview.id,expectedDecisionSha256:laterReview.decisionSha256,expectedReconciliationSha256:snapshot.reconciliation.contentSha256},fingerprint=m78Hash({operation:'report',actor:q.actor_id,companyId:company,family:q.family,streamId:q.stream_id,request});await tx.query('update neuvetra.scope1_requests set fingerprint=$1 where company_id=$2 and record_id=$3',[fingerprint,company,pending.id])
   await tx.exec('set local role neuvetra_runtime');const adapter={transaction:async(fn:(sql:unknown)=>Promise<unknown>)=>fn(tx)}as WorkspaceConnection,database=new(HostedWorkspaceDatabase as unknown as new(c:WorkspaceConnection,r:string)=>HostedWorkspaceDatabase)(adapter,'icockcoguyadhryzydvl');try{await database.findScope1(owner,company,f.authorities,M78_REVIEWED_POLICY)}catch(error){refusalMessage=(error as Error).message;refused=refusalMessage==='Stored Scope 1 records could not be verified.'}throw Error('Rollback fictional coordinated tamper regardless of result.')
  })}catch{}
  expect(refused).toBe(true);expect((await f.operator.query<{text:string}>('select neuvetra.m67_canonical(to_jsonb(t))text from neuvetra.scope1_reports t where id=$1',[pending.id])).rows[0]!.text).toBe(before);expect((await f.operator.query<{text:string}>('select neuvetra.m67_canonical(to_jsonb(t))text from neuvetra.scope1_audit t where record_id=$1',[pending.id])).rows[0]!.text).toBe(auditBefore);expect((await f.operator.query<{enabled:boolean}>("select bool_and(tgenabled='O')enabled from pg_trigger where not tgisinternal and tgname='m78_immutable'")).rows[0]!.enabled).toBe(true)
  await Bun.write('.superpowers/'+f.name+'-result.json',JSON.stringify({status:'independent_positive_replay_and_coordinated_history_tamper_pass',database:f.name,migrationSha256:f.migrationSha256,sourceReceiptSha256:'e2cb73a1a3c80f4b2adb62d564ff8ab9eb02809444a5734794c3f64cb11732ae',sourceCount:10,companyExact:register.reconciliation.totals?.company.kgCo2eExact,standaloneRehashedForgedReportAccepted:true,retainedNativeForgeryRefused:refused,refusalMessage,originalReportAuditOrder:order,reportAndAuditBytesRestored:true,immutableTriggersReenabled:true,actualRoutes:true,actualBrowserDecoders:true,syntheticAuth:true,customerData:false,hostedEvidence:false},null,2)+'\n')
 }finally{await f.close()}
},120000)
