import {test,expect} from 'bun:test'
import {readFile} from 'node:fs/promises'
import {resolve,dirname,relative} from 'node:path'
import {m78Continuation2SourcePins,M78_CONTINUATION2_EVIDENCE_PINS} from '../../tools/staging/m78-continuation2-source-pins'
import {m78Continuation2DiagnosticFetch,verifyM78Continuation2Failure} from '../../tools/staging/check-m78-continuation2'
const sha=(b:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(b).digest('hex')
test('union covers every transitive relative import of new roots and preserved155; missing runtime pins fail equality',async()=>{const pins=await m78Continuation2SourcePins(),map=new Map(pins.map(p=>[p.path,p.sha256]));expect(pins).toHaveLength(160);const prior=JSON.parse(await readFile('evaluations/research-qa/m78-continuation-journey-preparation-final.json','utf8'));for(const pin of prior.sourcePins)expect(map.get(pin.path)).toBe(pin.sha256);const queue=['tools/staging/check-m78-continuation2.ts','tools/staging/check-m78-continuation2.test.ts','tools/staging/m78-continuation2-source-pins.ts'],seen=new Set<string>();while(queue.length){const p=queue.pop()!;if(seen.has(p))continue;seen.add(p);expect(map.get(p)).toBe(sha(await readFile(p)));const body=await readFile(p,'utf8');for(const m of body.matchAll(/(?:from\s*|import\s*\(\s*|import\s*)['"](\.[^'"]+)['"]/g)){const base=resolve(dirname(p),m[1]!);let found:string|undefined;for(const path of [base,base+'.ts',base+'.tsx',resolve(base,'index.ts')])try{await readFile(path);found=relative('.',path).replaceAll('\\','/');break}catch{}expect(found).toBeDefined();queue.push(found!)}}for(const path of ['apps/site-api/src/workspace/m78-routes.ts','packages/neuvetra-database/src/m78.ts','packages/neuvetra-database/src/hosted.ts','tools/staging/check-m78-continuation2.ts']){expect(map.has(path)).toBe(true);expect(JSON.stringify(pins.filter(p=>p.path!==path))).not.toBe(JSON.stringify(pins))}})
test('exact parent file equals frozen fixture; wrapper checks four evidence pins and full union before unseal',async()=>{const fixture=await readFile('tools/staging/m78-continuation2-failed-baseline.jsonl','utf8'),actual=await readFile('.superpowers/m78-hosted-continuation.jsonl','utf8');expect(actual).toBe(fixture);expect(verifyM78Continuation2Failure(actual,'8b90c706-1710-494d-b12d-02eef88eacb7')).toHaveLength(24);expect(M78_CONTINUATION2_EVIDENCE_PINS).toHaveLength(4);for(const pin of M78_CONTINUATION2_EVIDENCE_PINS)expect(sha(await readFile(pin.path))).toBe(pin.sha256);const s=await readFile('.superpowers/m78-private-continuation2-journey.ps1','utf8');expect(sha(s)).toBe('01e7317590e3e9f287141ecffab4f69d56d7eeca8c683912b8bd437a184bd910');const unseal=s.indexOf('[Security.Cryptography.ProtectedData]::Unprotect');for(const marker of ['m78_independent_continuation2_preparation_passed','complete source closure changed','reviewed closure mismatch','missing original outcome evidence']){expect(s.indexOf(marker)).toBeGreaterThan(0);expect(s.indexOf(marker)).toBeLessThan(unseal)}expect(s).toContain('$review.evidencePins.Count -ne 4');expect(s).toContain('tools/staging/check-m78-continuation2.ts');expect(s).toContain('-NotePropertyName restartAttestation -NotePropertyValue $admission.artifacts.restart')})
test('failed diagnostic intent stops login but permits all cleanup requests even if diagnostic writes keep failing',async()=>{let network=0;const observer=m78Continuation2DiagnosticFetch((async()=>{network++;return new Response(null,{status:204})})as any,async()=>{throw Error('disk failure')});await expect(observer.fetch('https://icockcoguyadhryzydvl.supabase.co/auth/v1/token',{method:'POST'})).rejects.toThrow();expect(network).toBe(0);for(let i=0;i<4;i++)expect((await observer.fetch('https://icockcoguyadhryzydvl.supabase.co/auth/v1/logout',{method:'POST'})).status).toBe(204);expect(network).toBe(4);expect(observer.healthy()).toBe(false);await expect(observer.fetch('https://www.neuvetra.ai/ready')).rejects.toThrow();expect(network).toBe(4)})
