/** Offline completed-baseline review only: never authenticates or calls a host/database. */
import {readFile,writeFile} from 'node:fs/promises';
import {readM78ContinuationJournal,cleanM78ContinuationJournal,readM78Prior} from '../../tools/staging/check-m78-continuation';
import {assertM78ContinuationBaseline} from '../../tools/staging/m78-continuation-plan';
import {preservesM77History} from '../../tools/staging/check-m77-hosted';
import {decodeScope1Register} from '../../apps/site-web/src/lib/m78-api';
import {m78ContinuationSourcePins,M78_CONTINUATION_EVIDENCE_PINS} from '../../tools/staging/m78-continuation-source-pins';
import {m78CanonicalJson as canonical} from '../../packages/neuvetra-database/src/m78-validation';
const sha=(b:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(b).digest('hex'),check=(v:unknown,m:string)=>{if(!v)throw Error(m)},same=(a:unknown,b:unknown)=>canonical(a)===canonical(b);
export async function verifyBaseline(text:string,expectedSha:string,expectedHead:string){
 check(sha(text)===expectedSha,'Exact closed journal hash');const raw=JSON.parse(text.split('\n')[0]!),company=raw.workspaceId,events=readM78ContinuationJournal(text,company);cleanM78ContinuationJournal(events);
 const finish=events.at(-1)!;check(finish.kind==='attempt_finished'&&finish.mode==='baseline'&&finish.sha256===expectedHead&&finish.data.status==='passed'&&finish.data.applicationPostRequests===0&&finish.data.unknownAuthSessions===0&&finish.data.allCreatedAuthSessionsClosed===true,'Closed successful baseline required');
 check(events.every(e=>e.mode==='baseline'&&!e.kind.startsWith('post_'))&&events.filter(e=>e.kind==='baseline').length===1&&events.filter(e=>e.kind==='attempt_started').length===1,'Single zero-write baseline');
 const gatePath='.superpowers/m78-continuation-baseline-journey-gate.json',gb=await readFile(gatePath);check(sha(gb)==='bcfe8f8bd7741580c7cbe8b4f5bdcbe14d862dfa76a58209a2bec55bbdcc235d','Immutable gate');const gate=JSON.parse(gb.toString());check(same(events.find(e=>e.kind==='attempt_started')!.data.gate,gate.gate),'Journal gate');
 for(const pin of Object.values(gate.artifacts) as {path:string;sha256:string}[])check(sha(await readFile(pin.path))===pin.sha256,'Gate artifact '+pin.path);
 const pins=await m78ContinuationSourcePins(),receipt=JSON.parse(await readFile(gate.artifacts.independentReview.path,'utf8'));check(pins.length===155&&same(pins,gate.sourcePins)&&same(pins,receipt.sourcePins)&&same(receipt.evidencePins,M78_CONTINUATION_EVIDENCE_PINS),'Exact full source/evidence closure');for(const pin of M78_CONTINUATION_EVIDENCE_PINS)check(sha(await readFile(pin.path))===pin.sha256,'Original evidence');
 const runtime=JSON.parse(await readFile(gate.artifacts.runtime.path,'utf8')),ci=JSON.parse(await readFile(gate.artifacts.ciChecks.path,'utf8')),commit='59cda7a62d8dcc6b554c92372e3b032577e410c9';check(runtime.status==='m78_runtime_verified'&&runtime.schemaVersion===21&&runtime.commit===commit&&runtime.deploymentId==='0f2e99f3-67ef-4f4c-b3c3-a39c62eabc78'&&runtime.imageDigest==='sha256:fe46a0e354252026f2bcbf6672e10ec550e52a56f064ab3e75a8af17625749c9'&&runtime.httpStatus===200&&ci.sha===commit&&ci.pr_head===commit&&ci.checks.length===6&&ci.checks.every((c:any)=>c.conclusion==='success'),'Accepted runtime and CI');
 const ready=events.find(e=>e.kind==='actual_readiness')!.data;check(ready.schemaVersion===21&&ready.applicationCommitAttestation===commit&&ready.sourceGate===gate.gate.independentReviewSha256&&ready.migrationSha256===gate.gate.migrationSha256,'Actual journal readiness');
 const baseline=events.find(e=>e.kind==='baseline')!.data,prior=await readM78Prior(company),decoded=await decodeScope1Register(baseline.scope1,company);assertM78ContinuationBaseline(decoded);check(same(decoded,baseline.scope1)&&same(decoded.inventory.versions[0],prior.observation.version.payload),'Retained exact committed version');let downloadCount=0;for(const old of [prior.previous,prior.failed]){preservesM77History(old.registers,baseline.registers);for(const family of Object.keys(old.downloads))for(const[key,value]of Object.entries(old.downloads[family])){check(same(value,baseline.downloads[family]?.[key]),'Old exact download');downloadCount++}}check(same(baseline.legacy,prior.old.legacy)&&same(baseline.legacy,prior.failed.legacy),'Exact legacy state');
 const v=decoded.inventory.versions[0]!,expected=canonical({...v,review:null}),entries:Record<string,{sha256:string;byteLength:number}>={['version_'+v.id]:{sha256:sha(expected),byteLength:Buffer.byteLength(expected)}};for(const s of v.statements)entries['statement_'+s.id]={sha256:sha(s.text),byteLength:Buffer.byteLength(s.text)};check(same(entries,baseline.m78bytes),'Exact retained version export/statement bytes');
 return {status:'m78_independent_continuation_hosted_baseline_passed',createdAt:new Date().toISOString(),reviewerId:'/root/resume_recipe',journalPath:'.superpowers/m78-hosted-continuation.jsonl',prefixSha256:expectedSha,headSha256:expectedHead,verifiedPrefixEvents:events.length,verifiedPrefixBytes:Buffer.byteLength(text),completedAt:finish.createdAt,requests:finish.data.requests,applicationPostRequests:0,allCreatedAuthSessionsClosed:true,unknownAuthSessions:0,mainLogins:events.filter(e=>e.kind==='auth_outcome').length,mainLogouts:events.filter(e=>e.kind==='logout_outcome').length,legacyAuthOutcomes:events.filter(e=>e.kind==='legacy_auth_outcome').length,sourcePinCount:155,applicationCommit:commit,schemaVersion:21,gatePath,gateSha256:sha(gb),oldHistoryAndDownloadsPreserved:true,priorDownloadComparisons:downloadCount,retainedInitialInventoryId:v.id,retainedInitialInventorySha256:v.versionSha256,m78ExactDownloadCount:Object.keys(entries).length,actualDecoderPassed:true,qaNetworkUsed:false,qaDatabaseUsed:false,hostedExerciseAccepted:false,fullLifecycleVerified:false};
}
if(import.meta.main){const r=await verifyBaseline(await readFile('.superpowers/m78-hosted-continuation.jsonl','utf8'),process.argv[2]!,process.argv[3]!);const path='evaluations/research-qa/m78-continuation-baseline-independent-result.json';await writeFile(path,JSON.stringify(r,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({path,sha256:sha(await readFile(path)),...r}))}
