// Positive input fixture copied from frozen author test; all challenge mutations are independent.
import {
  M80_ACCEPTED_CANDIDATE_SHA256,
  M80_HOSTED_INPUT_PROFILE,
  M80_MIGRATION_0022_SHA256,
  M80_NEW_TABLES,
  M80_REQUIRED_CHECKS,
  M80_RUNTIME_ROOT_CLOSURE_SHA256,
  buildM80HostedPreparationPlan,
  type EvidencePin,
  type HostedPreparationInput,
} from "../../.superpowers/m80-foundation-hosted-prepare"
import {
  M80_HOSTED_GATE_PROFILE,
  M80_HOSTED_OBSERVATION_PROFILE,
  recordM80HostedOutcome,
  sealM80HostedIntent,
  m80HostedIntentPath,
  writeM80HostedEvidenceOnce,
} from "../../.superpowers/m80-foundation-hosted-once"

export const NOW = new Date("2026-09-24T22:12:00.000Z")
export const sha = (character: string) => character.repeat(64)
export const pin = (path: string, character: string): EvidencePin => ({ path, sha256: sha(character) })
export function input(): HostedPreparationInput {
  return {
    profile: M80_HOSTED_INPUT_PROFILE,
    operatorId: "/root",
    observedTarget: {
      observedAt: "2026-09-24T22:10:00.000Z",
      observationReceipt: pin(".superpowers/m80-foundation-hosted-target-observation.json", "0"),
      projectRef: "abcdefghijklmnopqrst",
      environmentId: "80000000-0000-4000-8000-000000000001",
      serviceId: "80000000-0000-4000-8000-000000000002",
      deploymentId: "80000000-0000-4000-8000-000000000003",
      deploymentStatus: "SUCCESS",
      deployedCommitSha: "1".repeat(40),
      deployedImageSha256: sha("2"),
      targetClassification: "private_synthetic_staging",
      syntheticDataOnlyVerified: true,
      schemaVersion: 21,
      migrationReceiptCount: 21,
      observedNonReceiptTableCount: 123,
      historicalReferenceNonReceiptTableCount: 120,
      applicationReadinessSchemaVersion: 21,
      applicationStateSha256: sha("3"),
      automaticDeploymentsPaused: true,
      maintenanceEnabled: true,
      noActiveApplicationWritesObserved: true,
    },
    publication: {
      reviewedHeadCommitSha: "4".repeat(40),
      headObservedAt: "2026-09-24T22:11:00.000Z",
      checksObservedAt: "2026-09-24T22:11:00.000Z",
      requiredChecks: M80_REQUIRED_CHECKS.map(name => ({ name, status: "completed", conclusion: "success" })),
      publicationReviewVerdict: "pass",
      publicationReview: pin("evaluations/research-qa/m80-publication-review.json", "4"),
      integrationAcceptanceVerdict: "pass",
      integrationAcceptance: pin("evaluations/research-qa/m80-integration-acceptance.json", "5"),
    },
    acceptedRuntime: {
      candidate: { path: "operations/agent-improvement/snapshots/M80-FOUNDATION-RUNTIME-20260924-CANDIDATE2.json", sha256: M80_ACCEPTED_CANDIDATE_SHA256 },
      migration: { path: "packages/neuvetra-database/src/migrations/0022_scope1_beta_foundation.sql", sha256: M80_MIGRATION_0022_SHA256 },
      rootClosure: { path: "evaluations/research-qa/m80-foundation-runtime-root-closure-20260924.json", sha256: M80_RUNTIME_ROOT_CLOSURE_SHA256 },
    },
    backup: {
      completedAt: "2026-09-24T22:00:00.000Z",
      sourceSchemaVersion: 21,
      sourceApplicationStateSha256: sha("3"),
      applicationOnly: true,
      syntheticDataOnly: true,
      providerRecoveryExcluded: true,
      backupReceipt: pin(".superpowers/m80-foundation-hosted-backup-receipt.json", "6"),
      encryptedArchiveSha256: sha("7"),
      snapshotSha256: sha("8"),
      customDumpSha256: sha("9"),
    },
    rehearsal: {
      completedAt: "2026-09-24T22:05:00.000Z",
      disposableDatabaseName: "m80_ops_foundation_1790287200",
      hostedEvidence: false,
      sourceSchemaVersion: 21,
      targetSchemaVersion: 22,
      sourceBackupReceiptSha256: sha("6"),
      migrationSha256: M80_MIGRATION_0022_SHA256,
      sourceObservedNonReceiptTableCount: 123,
      historicalReferenceNonReceiptTableCount: 120,
      oldMigrationReceiptCount: 21,
      oldContentExact: true,
      oldMetadataExact: true,
      expectedNewTables: [...M80_NEW_TABLES],
      forcedRlsVerified: true,
      runtimeSelectOnlyVerified: true,
      runtimeDirectWritesDenied: true,
      operatorAdmissionNotExecuted: true,
      allConnectionsClosed: true,
      restoreReceipt: pin("evaluations/research-qa/m80-hosted-restore.json", "a"),
      preservationReceipt: pin("evaluations/research-qa/m80-hosted-preservation.json", "b"),
      migrationReceipt: pin("evaluations/research-qa/m80-hosted-rehearsal.json", "c"),
    },
    admission: {
      verifiedAt: "2026-09-24T22:11:00.000Z",
      observationReceipt: pin(".superpowers/m80-foundation-hosted-admission-observation.json", "f"),
      companyId: "80000000-0000-4000-8000-000000000101",
      managerUserId: "80000000-0000-4000-8000-000000000102",
      managerRole: "owner",
      existingSyntheticCompanyVerified: true,
      existingManagerMembershipVerified: true,
      noCompanyCreation: true,
      noUserCreation: true,
      noRoleOrPermissionCreation: true,
    },
  }
}

export const gate = (plan: Awaited<ReturnType<typeof buildM80HostedPreparationPlan>>, planPin: EvidencePin, stage: "migration" | "admission" | "deployment" = "migration") => ({
  profile: M80_HOSTED_GATE_PROFILE,
  stage,
  reviewedAt: "2026-09-24T22:12:00.000Z",
  expiresAt: "2026-09-24T22:22:00.000Z",
  verdict: "pass",
  operatorId: "/root",
  independentReviewerId: "/root/m80_foundation_hosted_qa",
  plan: planPin,
  planSha256: plan.planSha256,
  candidateSha256: M80_ACCEPTED_CANDIDATE_SHA256,
  migrationSha256: M80_MIGRATION_0022_SHA256,
  reviewedHeadCommitSha: plan.publication.reviewedHeadCommitSha,
  exactRequiredChecksPassed: true,
  targetReobservedAt: "2026-09-24T22:12:00.000Z",
  targetProjectRef: plan.target.projectRef,
  currentSchemaVersion: stage === "migration" ? 21 : 22,
  currentMigrationReceiptCount: stage === "migration" ? 21 : 22,
  currentApplicationStateSha256: stage === "migration" ? plan.target.applicationStateSha256 : sha("d"),
  maintenanceEnabled: true,
  noActiveApplicationWritesObserved: true,
  securityReview: pin("evaluations/research-qa/m80-hosted-preparation-security.json", "d"),
  integrationAcceptance: plan.pins.integrationAcceptance,
  rootSoleExecutorAccepted: true,
  noAutomaticRetryAccepted: true,
})

