import {readFile,writeFile} from 'node:fs/promises'
import * as paths from 'node:path'
import {input,NOW} from './m80-hosted-prep-independent-20260924-fixture'
import {m80HostedSha256} from './m80-hosted-prep-independent-20260924-frozen-prepare'
import {parseM80Json} from '../../packages/neuvetra-database/src/m80-validation'
const snapshot=JSON.parse(await readFile('operations/agent-improvement/snapshots/M80-FOUNDATION-HOSTED-PREP-20260924-CANDIDATE1.json','utf8')),frozen=snapshot.files.find((x:any)=>x.path.endsWith('prepare.ts')).text,v=input(),receiptPath='evaluations/research-qa/m80-hosted-prep-independent-20260924-contradictory-receipt.json',receipt=await readFile(receiptPath),pin={path:receiptPath,sha256:m80HostedSha256(receipt)}
v.observedTarget.observationReceipt=pin;v.publication.publicationReview=pin;v.publication.integrationAcceptance=pin;v.backup.backupReceipt=pin;v.rehearsal.sourceBackupReceiptSha256=pin.sha256;v.rehearsal.restoreReceipt=pin;v.rehearsal.preservationReceipt=pin;v.rehearsal.migrationReceipt=pin;v.admission.observationReceipt=pin
const inputPath='evaluations/research-qa/m80-hosted-prep-independent-20260924-virtual-input.json',outputPath='.superpowers/m80-foundation-hosted-unused/../../evaluations/research-qa/m80-hosted-prep-independent-20260924-ESCAPE.json',files=new Map<string,Buffer>([[paths.resolve(inputPath),Buffer.from(JSON.stringify(v))],[paths.resolve(receiptPath),receipt]]),writes:string[]=[],reads:string[]=[];for(const p of Object.values(v.acceptedRuntime))files.set(paths.resolve(p.path),await readFile(p.path))
const read=async(p:string,encoding?:string)=>{reads.push(p);const b=files.get(p);if(!b)throw Error('missing virtual file');return encoding?b.toString('utf8'):b},write=async(p:string,data:string,opts:any)=>{if(opts?.flag!=='wx'||files.has(p))throw Error('exclusive refusal');writes.push(p);files.set(p,Buffer.from(data))},FakeDate=class extends Date{constructor(value?:any){super(value===undefined?NOW.getTime():value)}}
const code=frozen.replace(/^import[\s\S]*?from ["'][^"']+["']\r?\n/gm,'').replace(/^export /gm,'').replaceAll('import.meta.dir',JSON.stringify(paths.resolve('.superpowers'))).replace('if (import.meta.main)','if (true)'),compiled=new Bun.Transpiler({loader:'ts'}).transformSync(code),bindings={readFile:read,writeFile:write,isAbsolute:paths.isAbsolute,relative:paths.relative,resolve:paths.resolve,parseM80Json,process:{argv:['bun','frozen-prepare',inputPath,outputPath]},console:{log:()=>{}},Date:FakeDate},AsyncFunction=Object.getPrototypeOf(async()=>{}).constructor
await new AsyncFunction(...Object.keys(bindings),compiled)(...Object.values(bindings));const result={boundary:'Frozen actual prepare CLI executed with virtual fs and fixed clock. No actual output filesystem mutation.',acceptedTraversalOutput: true,requestedPath:outputPath,resolvedWrites:writes.map(p=>paths.relative(process.cwd(),p).replaceAll('\\','/')),leftRequiredSuperpowersDirectory:writes.some(p=>!p.startsWith(paths.resolve('.superpowers')+paths.sep)),actualPinReads:reads.length};await writeFile('evaluations/research-qa/m80-hosted-prep-independent-20260924-path-probes.json',JSON.stringify(result,null,2)+'\n');console.log(result)
