import {test,expect} from 'bun:test'
import {decodeM80Foundation,decodeM80Version} from '../../apps/site-web/src/lib/m80-beta-api'
import {createHash} from 'node:crypto'
import {readFileSync} from 'node:fs'
const fixture=JSON.parse(readFileSync('evaluations/research-qa/m80-setup-integration-independent-20260924-fixture.json','utf8')),company=fixture.fixtureAdmission.companyId
const canonical=(v:any):string=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}'
const hash=(v:any)=>createHash('sha256').update(canonical(v)).digest('hex')
const rehash=(v:any)=>{v.versionSha256=hash({profile:fixture.profile,id:v.id,companyId:v.companyId,reportingYear:v.reportingYear,revision:v.revision,previousVersionId:v.previousVersionId,previousVersionSha256:v.previousVersionSha256,fixtureProfileId:fixture.fixtureAdmission.fixtureProfileId,fixtureVersion:1,fixtureSha256:fixture.fixtureAdmission.fixtureSha256,payloadSha256:v.payloadSha256,createdBy:v.createdBy,createdAt:v.createdAt,dataClassification:'synthetic_rehearsal',completeness:'incomplete',releasedSupportedCount:0})}
test('independent decoder novel negative matrix and native positive fixture',async()=>{
 const checks:{name:string;refused:boolean}[]=[],open:any={...structuredClone(fixture),currentVersion:null,history:[]}
 expect((await decodeM80Foundation(fixture,company)).history.length).toBe(2);expect((await decodeM80Foundation(open,company)).history.length).toBe(0);expect((await decodeM80Version(fixture.currentVersion,company)).revision).toBe(2)
 const refuse=async(name:string,v:any,version=false)=>{let refused=false;try{if(version)await decodeM80Version(v,company);else await decodeM80Foundation(v,company)}catch{refused=true}checks.push({name,refused})}
 const walk=async(value:any,path:(string|number)[]=[])=>{if(typeof value==='string'){const v=structuredClone(open);let o:any=v;for(const k of path.slice(0,-1))o=o[k];o[path.at(-1)!]=[value];await refuse('array scalar '+path.join('.'),v)}else if(value&&typeof value==='object')for(const[k,item]of Object.entries(value))await walk(item,[...path,k])}
 await walk(open.setup,['setup']);await walk(open.eligibility,['eligibility'])
 for(let index=0;index<14;index++){const v=structuredClone(open);v.setup.sources[index].locationId=v.setup.sources[index].locationId===v.setup.locations[0].locationId?v.setup.locations[1].locationId:v.setup.locations[0].locationId;await refuse('source location swap '+index,v)}
 for(let index=0;index<14;index++)for(const field of ['state','candidateProfileId','blockerCodes','requiredFactCodes']){const v=structuredClone(open),row=v.eligibility.results[index];row[field]=field==='state'?(row.state==='held_candidate'?'unsupported':'held_candidate'):field==='candidateProfileId'?(row.candidateProfileId===null?v.releaseRegistry[0].profileId:null):[...row[field],'fabricated_qa_code'];await refuse('eligibility '+index+' '+field,v)}
 for(let index=0;index<2;index++)for(const field of ['createdBy','createdAt','payloadSha256','versionSha256','id','revision']){const v=structuredClone(fixture);v.history[index][field]=field==='createdBy'||field==='id'?crypto.randomUUID():field==='createdAt'?'2026-09-25T00:00:00.000Z':field==='revision'?7:'0'.repeat(64);await refuse('history '+index+' '+field,v)}
 for(const[name,mutate]of [['invalid calendar',(v:any)=>v.createdAt='2026-02-30T00:00:00.000Z'],['first with predecessor',(v:any)=>v.revision=1],['successor without predecessor',(v:any)=>{v.previousVersionId=null;v.previousVersionSha256=null}],['self predecessor',(v:any)=>v.previousVersionId=v.id],['unpaired previous hash',(v:any)=>v.previousVersionSha256=null]] as const){const v=structuredClone(fixture.currentVersion);mutate(v);rehash(v);await refuse(name,v,true)}
 const failures=checks.filter(c=>!c.refused);await Bun.write('evaluations/research-qa/m80-setup-integration-independent-20260924-decoder-matrix.json',JSON.stringify({clientSha256:createHash('sha256').update(readFileSync('apps/site-web/src/lib/m80-beta-api.ts')).digest('hex'),positiveControls:3,negativeChecks:checks.length,failures,checks},null,2)+'\n');expect(failures).toEqual([])
},30000)
