import {readFile} from 'node:fs/promises'
import {validateM80ExecutorReview,loadM80ExecutorEvidence,loadM80ExecutorSourceEvidence} from '../../.superpowers/m80-foundation-executor-v2'
import {m80HostedSha256 as sha} from '../../.superpowers/m80-foundation-hosted-prepare-v2'
const snapshotPath='operations/agent-improvement/snapshots/M80-NORMALIZED-EXECUTOR-CONSUMER-20260925-CANDIDATE2.json',snapshotBytes=await readFile(snapshotPath),snapshot=JSON.parse(snapshotBytes.toString())
if(sha(snapshotBytes)!=='f690767d4b3ce0d19a6024be2822582f70378be23e53d46afa07d65838bd27cf')throw Error('Frozen snapshot changed')
const reviewPath='evaluations/research-qa/virtual-executor-review.json',review={reviewer:'/root/m80_foundation_runtime_qa',verdict:'pass_m80_executor_transport_only',source_snapshot:{path:snapshotPath,sha256:sha(snapshotBytes)},source_pins:snapshot.artifacts.map((a:any)=>({path:a.path,sha256:a.sha256}))},reviewBytes=Buffer.from(JSON.stringify(review)),reviewPin={path:reviewPath,sha256:sha(reviewBytes)},seen=new Set<string>()
const frozenOuter=new Map<string,Uint8Array>(snapshot.artifacts.map((a:any)=>[a.path,Buffer.from(a.text)]));const currentOverrides:string[]=[];const reader=async(path:string)=>{if(path===reviewPath)return reviewBytes;seen.add(path);const bytes=await readFile(path),frozen=frozenOuter.get(path);if(frozen&&sha(bytes)!==sha(frozen)){throw Error('Live C9 source drifted '+path)}return bytes}
await validateM80ExecutorReview(reviewPin,reader)
const actualClosureCount=seen.size-1,results:any[]=[]
for(const leaf of ['tools/staging/m78-inventory.ts','tools/staging/m73-common.ts','packages/neuvetra-database/src/migrations/0001_company_workspace.sql','packages/neuvetra-database/src/migrations/0022_scope1_beta_foundation.sql','tools/cloud/fixtures/supabase-prod-ca-2021.crt','bun.lock','.superpowers/m80-backup-private.ps1','.superpowers/m80-foundation-hosted-once.ts','.superpowers/m80-foundation-hosted-once-v2.ts','.superpowers/m80-foundation-hosted-prepare-v2.ts','.superpowers/m80-backup-v2-core.ts','.superpowers/m80-foundation-hosted-prepare-v3.ts','.superpowers/m80-foundation-hosted-once-v3.ts']){
 let error='';try{await validateM80ExecutorReview(reviewPin,async path=>path===leaf?Buffer.from('synthetic mutated bytes'):reader(path))}catch(e){error=String(e)}
 if(!error.includes('Reviewed executor source changed'))throw Error('Nested mutation not refused '+leaf+': '+error);results.push({leaf,rejected:true})
}
const nativePath='.tmp/m80-executor-native-source-receipt.json',nativeBytes=await readFile(nativePath);if(sha(nativeBytes)!=='512d0368b714ab68bb2c0563cde3716716ff217847184174573f1838cb28a604')throw Error('Native source pin changed');await loadM80ExecutorSourceEvidence({path:nativePath,sha256:sha(nativeBytes)});
const prepPath='operations/agent-improvement/snapshots/M80-FOUNDATION-HOSTED-PREP-20260924-CANDIDATE6.json',prep=await readFile(prepPath);await loadM80ExecutorEvidence({path:prepPath,sha256:sha(prep)})
for(const [name,text,max,positive] of [['ordinary_exact_bound','"'+'x'.repeat(999_998)+'"',1_000_000,true],['ordinary_over_bound','"'+'x'.repeat(999_999)+'"',1_000_000,false],['source_exact_bound','"'+'x'.repeat(3_999_998)+'"',4_000_000,true],['source_over_bound','"'+'x'.repeat(3_999_999)+'"',4_000_000,false],['duplicate_top','{"a":1,"a":2}',4_000_000,false],['duplicate_escaped','{"a":1,"\\u0061":2}',4_000_000,false],['duplicate_nested','{"x":[{"a":1,"a":2}]}',1_000_000,false]] as const){
 const bytes=Buffer.from(text),pin={path:'virtual.json',sha256:sha(bytes)};let rejected=false;try{await (max===4_000_000?loadM80ExecutorSourceEvidence:loadM80ExecutorEvidence)(pin,async()=>bytes)}catch{rejected=true}if(rejected===positive)throw Error('Unexpected parser result '+name);results.push({name,bytes:bytes.length,rejected})
}
await Bun.write('evaluations/research-qa/m80-normalized-executor-independent-20260925-loaders.json',JSON.stringify({boundary:'Real frozen source validator, actual delivered snapshot/nested source reads; mutations virtual only; no network/DB',currentOverrides,nativeSourceBytes:nativeBytes.length,nativeSourceSha256:sha(nativeBytes),outerBytes:snapshotBytes.length,outerArtifacts:snapshot.artifacts.length,actualClosureCount,acceptedPreparationBytes:prep.length,results},null,2)+'\n');console.log(JSON.stringify({actualClosureCount,outerBytes:snapshotBytes.length,mutationCases:13,parserCases:7}))
