// Actual admission evidence review only: no transport, DB, Git or credential calls.
import {readFile,readdir} from 'node:fs/promises'
import {createHash} from 'node:crypto'
import {validateM80HostedPlan,validateM80HostedGate,sealM80HostedIntent,writeM80HostedEvidenceOnce,m80HostedIntentPath} from '../../.superpowers/m80-foundation-hosted-once-v3'
import {validateM80ExecutorReview,loadM80ExecutorSourceEvidence} from '../../.superpowers/m80-foundation-executor-v2'
import {M80_REQUIRED_CHECKS,m80HostedCanonicalJson} from '../../.superpowers/m80-foundation-hosted-prepare-v3'
import {m80BackupV2NormalizedMetadataSha256} from '../../.superpowers/m80-backup-v2-core'
const sha=(x:Uint8Array|string)=>createHash('sha256').update(x).digest('hex'), hash=(x:unknown)=>sha(m80HostedCanonicalJson(x))
const require=(x:unknown,m:string)=>{if(!x)throw Error(m)}
const load=async(path:string,pin?:string)=>{const bytes=await readFile(path);require(!pin||sha(bytes)===pin,'Evidence changed: '+path);return{value:JSON.parse(bytes.toString()),pin:{path,sha256:sha(bytes)}}}
const now=new Date(),planFile=await load('.superpowers/m80-foundation-hosted-live002-plan.json','5934bb3eeb4093ed68caa644fa6b0c3b44fc70ec8cb9dd466de7cd7efdf9c285'),plan=validateM80HostedPlan(planFile.value,now),scope=plan.operationScopeSha256
const intent=await load(`.superpowers/m80-foundation-hosted-${scope}-migration-intent.json`,'0d60861f836a3996e00937f69ffe5ae0fc719be095450c3dc068401d4edd0b7e')
const attempt=await load(`.superpowers/m80-foundation-executor-${scope}-migration-attempt.json`,'d97cfd71cd860c64dfad9077087ad20204b04825c29e6f126e788c071b951f03')
const observation=await load(`.superpowers/m80-foundation-executor-${scope}-migration-observation.json`,'16f8d15a9843fb90e1e751e598d8167ee485498f987ba06df938bb940c9d60af')
const outcome=await load(`.superpowers/m80-foundation-executor-${scope}-migration-outcome.json`,'3d8f5656c6e1b8a24fe68b0e37ec57c1cebbde7d78ea6b46f34a83aa073f25e8')
const oldGate=await load(intent.value.gate.path,intent.value.gate.sha256)
const oldGateEvidence={securityReview:await load(oldGate.value.securityReview.path,oldGate.value.securityReview.sha256),integrationAcceptance:await load(oldGate.value.integrationAcceptance.path,oldGate.value.integrationAcceptance.sha256),targetObservation:await load(oldGate.value.targetObservation.path,oldGate.value.targetObservation.sha256)}
const migration={intent:intent.value,intentPin:intent.pin,gate:oldGate.value,gatePin:oldGate.pin,gateEvidence:oldGateEvidence,observation:observation.value,observationPin:observation.pin,outcome:outcome.value,outcomePin:outcome.pin}
const at=attempt.value, unsigned={...at};delete unsigned.attemptSha256
require(hash(unsigned)===at.attemptSha256&&at.profile==='neuvetra.m80.foundation-executor-attempt.v2'&&at.stage==='migration'&&at.operatorId==='/root'&&at.operationScopeSha256===scope&&at.durableBeforeTransport===true&&at.noAutomaticRetry===true,'Invalid actual attempt')
require(m80HostedCanonicalJson(at.plan)===m80HostedCanonicalJson(planFile.pin)&&m80HostedCanonicalJson(at.intent)===m80HostedCanonicalJson(intent.pin)&&m80HostedCanonicalJson(at.actionIdentity)===m80HostedCanonicalJson(intent.value.actionIdentity),'Attempt identity differs')
require(at.targetProjectRef===plan.target.projectRef&&at.targetEnvironmentId===plan.target.environmentId&&at.targetServiceId===plan.target.serviceId,'Attempt target differs')
await validateM80ExecutorReview(at.executorReview)
const source:any=await loadM80ExecutorSourceEvidence(at.preMigrationState),state=source.state,iv=state.inventory
require(source.profile==='neuvetra.m80.foundation-executor-migration-source.v2'&&source.capturedAt===at.startedAt&&source.projectRef===plan.target.projectRef&&source.applicationStateSha256===plan.target.applicationStateSha256&&state.applicationStateSha256===source.applicationStateSha256,'Source capture differs from reviewed backup')
require(state.contentSha256===hash({tables:iv.tables.filter((t:any)=>t.name!=='schema_migrations').map((t:any)=>({name:t.name,count:t.count,rowHashes:t.rowHashes})),migrationReceipts:state.migrationReceipts}),'Source content hash inconsistent')
require(state.metadataSha256===hash({nonReceiptTables:state.observedNonReceiptTables,tableSecurity:state.tableSecurity,schemaSecurity:state.schemaSecurity,internalTriggers:state.internalTriggers,functions:iv.functions,tableObjects:iv.tableObjects,sequences:iv.sequences,roles:iv.roles,memberships:iv.memberships,defaultAcls:iv.defaultAcls,dependencies:iv.dependencies}),'Source raw metadata hash inconsistent')
require(state.applicationStateSha256===hash({contentSha256:state.contentSha256,metadataSha256:state.metadataSha256})&&m80BackupV2NormalizedMetadataSha256(state)===plan.rehearsal.sourceNormalizedMetadataSha256,'Raw or normalized source binding differs')
require(state.observedNonReceiptTables.length===120&&state.migrationReceipts.length===21,'Source inventory differs')
require(Date.parse(intent.value.createdAt)<=Date.parse(at.startedAt)&&Date.parse(at.startedAt)<=Date.parse(observation.value.observedAt)&&Date.parse(observation.value.observedAt)<=Date.parse(outcome.value.recordedAt),'Attempt chronology differs')
const provider=await load('.superpowers/m80-provider-observation-recovered21-stopped-admission-001.json','a93b29c27b48849e8e98c50a42e49ad880e28e6971bc71d0f73434bcdb466a9c'),db=await load('.superpowers/m80-stage-observation-normalized-admission-001.json','42684a73edfcae96e35acf2eee2c8efe63b1b01184c51e0835f23336adfc66ea'),ci=await load('.superpowers/m80-ci-observation-controller-006.json','a0f2235262386aeaf2356d26e0b66e1a4a6047a8ecc7fcd606509d032055cdc1')
const p=provider.value,d=db.value,c=ci.value
for(const t of[p.observed_at,d.observedAt,c.observed_at])require(Date.parse(t)<=+now&&+now-Date.parse(t)<900000,'Expired or future observation')
require(Date.parse(p.observed_at)>=Date.parse(outcome.value.recordedAt)&&Date.parse(d.observedAt)>=Date.parse(outcome.value.recordedAt),'Stage observation predates migration result')
require(p.profile==='neuvetra.m80.provider-readonly-observation.v1'&&p.mode==='stopped'&&p.read_only===true&&p.active_deployment_count===0&&p.automatic_deployments_enabled===false&&p.origin_http_status===404&&p.readiness===null&&p.environment===plan.target.environmentId&&p.service===plan.target.serviceId&&p.deployments.every((x:any)=>['REMOVED','FAILED','CRASHED','SKIPPED'].includes(x.status)),'Provider is not stopped at exact target')
require(p.observer_sha256==='63d8cb410a627dcdb0c13151cf7ddf7c68b6a6d88d46d7cc72041c0c1398b770'&&p.deployments.some((x:any)=>x.id===plan.target.deploymentId&&x.status==='REMOVED'),'Wrong provider observer/target')
require(d.profile==='neuvetra.m80.stopped-database-observation.v1'&&d.projectRef===plan.target.projectRef&&d.currentSchemaVersion===22&&d.currentMigrationReceiptCount===22&&d.observedNonReceiptTableCount===126&&d.activeRuntimeSessionCount===0&&d.noActiveApplicationWritesObserved===true&&d.readOnly===true,'Schema22 or stopped DB boundary differs')
require(d.acceptedBackupHelperSha256==='429ac122e20aec4230300ef092d9534a7cd912ec39ee65d2c6e33f8b040faf07','Collector dependency differs')
require(c.sha===c.pr_head&&c.sha==='1ae0074f662394f66172b6b80aab9a0a1414773e'&&c.state==='open'&&c.checks.length===6&&JSON.stringify(c.checks.map((x:any)=>x.name).sort())===JSON.stringify([...M80_REQUIRED_CHECKS].sort())&&c.checks.every((x:any)=>x.status==='completed'&&x.conclusion==='success'),'Ops head checks incomplete')
require(Date.parse(c.observed_at)<Date.parse(at.startedAt),'Migration preceded required controller CI')
require(!(await readdir('.superpowers')).includes(m80HostedIntentPath(plan,'admission').split('/').at(-1)!),'Admission already reserved')
const stem='.superpowers/m80-foundation-hosted-live002-admission-qa-001',reviewedAt=now.toISOString(),expiresAt=new Date(Math.min(+now+900000,Date.parse(p.observed_at)+900000,Date.parse(d.observedAt)+900000,Date.parse(plan.expiresAt))).toISOString()
const target={profile:'neuvetra.m80.foundation-hosted-stage-target-observation.v1',observedAt:d.observedAt,stage:'admission',projectRef:plan.target.projectRef,environmentId:plan.target.environmentId,serviceId:plan.target.serviceId,schemaVersion:22,migrationReceiptCount:22,applicationStateSha256:d.currentApplicationStateSha256,writeQuiescenceMechanism:'provider_deployment_stopped_and_origin_readiness_unavailable',activeDeploymentCount:0,originReadinessUnavailable:true,noActiveApplicationWritesObserved:true}
const security={profile:'neuvetra.m80.foundation-hosted-security-review.v1',observedAt:reviewedAt,verdict:'pass',reviewerId:'/root/m80_foundation_runtime_qa',implementationAuthor:'/root/m80_setup_ui',independent:true,plan:planFile.pin,planSha256:plan.planSha256,operationScopeSha256:scope,stage:'admission',targetProjectRef:plan.target.projectRef,reviewedHeadCommitSha:plan.publication.reviewedHeadCommitSha,candidateSha256:plan.pins.candidate.sha256,migrationSha256:plan.pins.migration.sha256,materialFindingsOpen:0}
const asLoaded=(path:string,value:unknown)=>({value,pin:{path,sha256:sha(JSON.stringify(value,null,2)+'\n')}}),t=asLoaded(stem+'-target.json',target),s=asLoaded(stem+'-security.json',security),integration=await load(plan.pins.integrationAcceptance.path,plan.pins.integrationAcceptance.sha256)
const gate={profile:'neuvetra.m80.foundation-hosted-execution-gate.v1',stage:'admission',reviewedAt,expiresAt,verdict:'pass',operatorId:'/root',independentReviewerId:'/root/m80_foundation_runtime_qa',plan:planFile.pin,planSha256:plan.planSha256,candidateSha256:plan.pins.candidate.sha256,migrationSha256:plan.pins.migration.sha256,reviewedHeadCommitSha:plan.publication.reviewedHeadCommitSha,exactRequiredChecksPassed:true,targetObservation:t.pin,targetReobservedAt:d.observedAt,targetProjectRef:plan.target.projectRef,targetEnvironmentId:plan.target.environmentId,targetServiceId:plan.target.serviceId,currentSchemaVersion:22,currentMigrationReceiptCount:22,currentApplicationStateSha256:d.currentApplicationStateSha256,writeQuiescenceMechanism:target.writeQuiescenceMechanism,activeDeploymentCount:0,originReadinessUnavailable:true,noActiveApplicationWritesObserved:true,securityReview:s.pin,integrationAcceptance:integration.pin,rootSoleExecutorAccepted:true,noAutomaticRetryAccepted:true}
const g=asLoaded(stem+'-gate.json',gate),gateEvidence={securityReview:s,targetObservation:t,integrationAcceptance:integration}
validateM80HostedGate(gate,plan,planFile.pin,'admission',gateEvidence,now)
sealM80HostedIntent({plan,planPin:planFile.pin,gate,gatePin:g.pin,gateEvidence,stage:'admission',migration,now}) // Exact predecessor reconstruction; no intent written.
for(const e of[t,s,g])await writeM80HostedEvidenceOnce(e.pin.path,e.value)
const receipt={profile:'neuvetra.m80.actual-admission-independent-review.v1',reviewer:'/root/m80_foundation_runtime_qa',verdict:'pass_existing_synthetic_admission_stage_only',reviewedAt,expiresAt,plan:planFile.pin,gate:g.pin,security:s.pin,target:t.pin,migrationEvidence:[intent.pin,attempt.pin,at.preMigrationState,observation.pin,outcome.pin],freshEvidence:[provider.pin,db.pin,ci.pin],rawSourceStateRecomputed:true,sourceBytes:(await readFile(at.preMigrationState.path)).byteLength,sourceNonReceiptTables:120,sourceMigrationReceipts:21,actualMigrationObserverReportedRawContentAndMetadataExact:true,freshSchemaVersion:22,freshMigrationReceipts:22,freshRuntimeSessions:0,controllerSixChecksPrecededMigration:true,onceV3ExactPredecessorAndGateValidationPassed:true,schema21RecoveryNowForbidden:true,noCompanyUserOrRoleCreation:true,actualIntentWritten:false,limits:'Independent receipt/source review; no independent DB query. Admission only, bound original plan existing company/manager and exact fixture. Root alone executes; deployment needs a new actual outcome and fresh gate.'}
await writeM80HostedEvidenceOnce('evaluations/research-qa/m80-normalized-actual-upgrade-independent-20260925-admission-review.json',receipt)
console.log(JSON.stringify({gate:g.pin,security:s.pin,target:t.pin,reviewedAt,expiresAt,intentWritten:false}))
