// Independent actual evidence review only. No provider, database, credential or Git calls.
import { readFile, readdir } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { validateM80HostedPlan,validateM80HostedGate,sealM80HostedIntent,writeM80HostedEvidenceOnce,m80HostedIntentPath } from '../../.superpowers/m80-foundation-hosted-once-v3'
import { validateM80ExecutorReview } from '../../.superpowers/m80-foundation-executor-v2'
import { M80_REQUIRED_CHECKS } from '../../.superpowers/m80-foundation-hosted-prepare-v3'
const sha=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex')
const load=async(path:string,expected?:string)=>{const b=await readFile(path);if(expected&&sha(b)!==expected)throw Error('Changed pinned evidence: '+path);return {value:JSON.parse(b.toString()),pin:{path,sha256:sha(b)}}}
const require=(ok:unknown,message:string)=>{if(!ok)throw Error(message)}
const planFile=await load('.superpowers/m80-foundation-hosted-live002-plan.json','5934bb3eeb4093ed68caa644fa6b0c3b44fc70ec8cb9dd466de7cd7efdf9c285')
const now=new Date(),plan=validateM80HostedPlan(planFile.value,now)
const provider=await load('.superpowers/m80-provider-observation-recovered21-stopped-resumed-001.json','79a6af24969f38f4c65919edd09bb11c87ae4808b3546978aee2388e1fffb08f')
const db=await load('.superpowers/m80-stage-observation-normalized-migration-resumed-001.json','44d83cf8017bbd5a623b81025ebd6f24fca1df12ac5bb2388e470632ae74be2f')
const membership=await load('.superpowers/m80-backup-hosted-preflight-resumed-001.json','81056f224a83e10ed1cf6833f08e6be2755d0804f7cd27a07f5f506513a6812c')
const ci=await load('.superpowers/m80-ci-observation-original-plan-resumed-001.json','d36dc89b26c616cd8b7428ac299585007d03dfa034dc0fe8a96043810c1864c3')
const ops=await load('evaluations/research-qa/ops-graph-01-product-integration-20260925.json','6441487b78b4e0aef0d87d963badfc71c89cc0941a078e3b71659943fad3c9af')
const baseline=await load('.superpowers/m80-provider-observation-recovered21-baseline-001.json','53a7eff99589d1de498426d84c9cec3a3928d8dc7b437ae3448fdf543184f623')
const sourceReview=await load('evaluations/research-qa/m80-normalized-executor-independent-20260925-review.json','9fa7c2c588d26f2596a61d92854d031a77a11a9015b63232b8a7c29105a50361')
await validateM80ExecutorReview(sourceReview.pin)
const p=provider.value,d=db.value,c=ci.value,m=membership.value,o=ops.value
for(const time of [p.observed_at,d.observedAt,m.observedAt,c.observed_at])require(now.getTime()-Date.parse(time)>=0&&now.getTime()-Date.parse(time)<15*60_000,'Expired or future raw observation')
require(p.profile==='neuvetra.m80.provider-readonly-observation.v1'&&p.mode==='stopped'&&p.read_only===true&&p.automatic_deployments_enabled===false&&p.active_deployment_count===0&&p.origin_http_status===404&&p.readiness===null,'Provider is not stopped')
require(p.project===baseline.value.project&&p.environment===plan.target.environmentId&&p.service===plan.target.serviceId,'Provider target differs')
require(p.observer_sha256==='63d8cb410a627dcdb0c13151cf7ddf7c68b6a6d88d46d7cc72041c0c1398b770','Observer source changed')
require(p.deployments.every((x:any)=>['REMOVED','FAILED','CRASHED','SKIPPED'].includes(x.status))&&p.deployments.some((x:any)=>x.id===plan.target.deploymentId&&x.status==='REMOVED'&&x.meta.commitHash===plan.target.deployedCommitSha&&x.meta.imageDigest==='sha256:'+plan.target.deployedImageSha256),'Prior deployment not authoritatively removed')
require(d.profile==='neuvetra.m80.stopped-database-observation.v1'&&d.projectRef===plan.target.projectRef&&d.currentSchemaVersion===21&&d.currentMigrationReceiptCount===21&&d.currentApplicationStateSha256===plan.target.applicationStateSha256&&d.activeRuntimeSessionCount===0&&d.noActiveApplicationWritesObserved===true&&d.readOnly===true&&d.observedNonReceiptTableCount===120,'Database target/state/quiescence differs')
require(d.acceptedBackupHelperSha256==='429ac122e20aec4230300ef092d9534a7cd912ec39ee65d2c6e33f8b040faf07','DB observation collector dependency differs')
require(m.profile==='neuvetra.m80.foundation-backup-source-preflight.v1'&&m.projectRef===plan.target.projectRef&&m.sourceSchemaVersion===21&&m.migrationReceiptCount===21&&m.applicationStateSha256===d.currentApplicationStateSha256&&m.activeRuntimeSessionCount===0&&m.readOnly===true&&m.observedNonReceiptTableCount===120,'Fresh membership source differs')
require(JSON.stringify(m.observedNonReceiptTables)===JSON.stringify(plan.target.observedNonReceiptTables),'Old table inventory differs')
require(['existingSyntheticCompanyVerified','existingManagerMembershipsVerified','noCompanyCreation','noUserCreation','noRoleOrPermissionCreation','applicationOnly','providerRecoveryExcluded'].every(k=>m[k]===true),'Membership verification flags differ')
require(m.existingSyntheticCompanyManagers.filter((x:any)=>['companyId','managerUserId','managerRole'].every(k=>x[k]===plan.admission[k])).length===1,'Original existing owner membership not corroborated')
for(const pin of m.sourceHelperPins.pins)await loadHash(pin)
async function loadHash(pin:{path:string,sha256:string}){require(sha(await readFile(pin.path))===pin.sha256,'Changed source: '+pin.path)}
require(c.sha===plan.publication.reviewedHeadCommitSha&&c.pr_head===o.head&&c.state==='open'&&c.pr==='https://github.com/neuvetra-hq/neuvetra/pull/6','Fresh original-head CI provenance differs')
require(c.checks.length===6&&JSON.stringify(c.checks.map((x:any)=>x.name).sort())===JSON.stringify([...M80_REQUIRED_CHECKS].sort())&&c.checks.every((x:any)=>x.status==='completed'&&x.conclusion==='success'),'Original app checks not exact six successes')
require(o.parent===plan.publication.reviewedHeadCommitSha&&o.head===o.remote_verified&&o.exact_commit_integrated===true&&o.application_files_changed===false&&o.existing_m80_plan_unchanged===true&&o.files.length===11,'Ops-only parent/integration receipt differs')
const allowed=['.github/workflows/agent-ops.yml','operations/agent-improvement/README.md','operations/agent-improvement/runs/OPS-GRAPH-01.json','operations/agent-improvement/snapshots/OPS-GRAPH-01-v1.json','operations/agent-improvement/workflow/README.md','operations/agent-improvement/workflow/acceptance.md','operations/agent-improvement/workflow/demo-result.json','operations/agent-improvement/workflow/example-plan.json','operations/agent-improvement/workflow/qa-review.md','tools/agent_workflow.py','tools/test_agent_workflow.py']
require(JSON.stringify(o.files.map((x:any)=>x.path).sort())===JSON.stringify(allowed.sort()),'Unexpected ops delta')
for(const pin of o.files)await loadHash(pin)
const existing=await readdir('.superpowers');require(!existing.includes(m80HostedIntentPath(plan,'migration').split('/').at(-1)!), 'Migration intent already reserved')
const summary=await load('evaluations/research-qa/m80-normalized-actual-upgrade-independent-20260925-plan-check.json')
require(summary.value.plan.sha256===planFile.pin.sha256&&summary.value.exactOriginalPlanRebuilt&&summary.value.journalAndFourReceiptsExact,'Prior exact actual-chain review missing')
for(const pin of Object.values(plan.pins))await loadHash(pin)
const integration=await load(plan.pins.integrationAcceptance.path,plan.pins.integrationAcceptance.sha256)
const stem='.superpowers/m80-foundation-hosted-live002-migration-qa-resumed-001'
const reviewedAt=now.toISOString(),expiresAt=new Date(Math.min(now.getTime()+15*60_000,Date.parse(p.observed_at)+15*60_000,Date.parse(d.observedAt)+15*60_000,Date.parse(c.observed_at)+15*60_000,Date.parse(plan.expiresAt))).toISOString()
const target={profile:'neuvetra.m80.foundation-hosted-stage-target-observation.v1',observedAt:d.observedAt,stage:'migration',projectRef:plan.target.projectRef,environmentId:plan.target.environmentId,serviceId:plan.target.serviceId,schemaVersion:21,migrationReceiptCount:21,applicationStateSha256:d.currentApplicationStateSha256,writeQuiescenceMechanism:'provider_deployment_stopped_and_origin_readiness_unavailable',activeDeploymentCount:0,originReadinessUnavailable:true,noActiveApplicationWritesObserved:true}
const security={profile:'neuvetra.m80.foundation-hosted-security-review.v1',observedAt:reviewedAt,verdict:'pass',reviewerId:'/root/m80_foundation_runtime_qa',implementationAuthor:'/root/m80_setup_ui',independent:true,plan:planFile.pin,planSha256:plan.planSha256,operationScopeSha256:plan.operationScopeSha256,stage:'migration',targetProjectRef:plan.target.projectRef,reviewedHeadCommitSha:plan.publication.reviewedHeadCommitSha,candidateSha256:plan.pins.candidate.sha256,migrationSha256:plan.pins.migration.sha256,materialFindingsOpen:0}
const asLoaded=(path:string,value:unknown)=>({pin:{path,sha256:sha(JSON.stringify(value,null,2)+'\n')},value})
const targetEvidence=asLoaded(stem+'-target.json',target),securityEvidence=asLoaded(stem+'-security.json',security)
const gate={profile:'neuvetra.m80.foundation-hosted-execution-gate.v1',stage:'migration',reviewedAt,expiresAt,verdict:'pass',operatorId:'/root',independentReviewerId:'/root/m80_foundation_runtime_qa',plan:planFile.pin,planSha256:plan.planSha256,candidateSha256:plan.pins.candidate.sha256,migrationSha256:plan.pins.migration.sha256,reviewedHeadCommitSha:plan.publication.reviewedHeadCommitSha,exactRequiredChecksPassed:true,targetObservation:targetEvidence.pin,targetReobservedAt:d.observedAt,targetProjectRef:plan.target.projectRef,targetEnvironmentId:plan.target.environmentId,targetServiceId:plan.target.serviceId,currentSchemaVersion:21,currentMigrationReceiptCount:21,currentApplicationStateSha256:d.currentApplicationStateSha256,writeQuiescenceMechanism:target.writeQuiescenceMechanism,activeDeploymentCount:0,originReadinessUnavailable:true,noActiveApplicationWritesObserved:true,securityReview:securityEvidence.pin,integrationAcceptance:integration.pin,rootSoleExecutorAccepted:true,noAutomaticRetryAccepted:true}
const gateEvidence={securityReview:securityEvidence,integrationAcceptance:integration,targetObservation:targetEvidence};validateM80HostedGate(gate,plan,planFile.pin,'migration',gateEvidence,now)
const gateLoaded=asLoaded(stem+'-gate.json',gate)
sealM80HostedIntent({plan,planPin:planFile.pin,gate,gatePin:gateLoaded.pin,gateEvidence,stage:'migration',now}) // Pure validation only; root seals actual intent.
for(const loaded of [targetEvidence,securityEvidence,gateLoaded])await writeM80HostedEvidenceOnce(loaded.pin.path,loaded.value)
const publicReceipt={profile:'neuvetra.m80.actual-migration-independent-review.v1',reviewer:'/root/m80_foundation_runtime_qa',verdict:'pass_original_plan_migration_stage_only',reviewedAt,expiresAt,plan:planFile.pin,gate:gateLoaded.pin,security:securityEvidence.pin,target:targetEvidence.pin,rawEvidence:[provider.pin,db.pin,membership.pin,ci.pin,ops.pin,summary.pin],originalAppCommit:plan.publication.reviewedHeadCommitSha,newOpsCommit:o.head,rawDatabaseObservationTimeUsed:d.observedAt,rawProviderObservationTime:p.observed_at,oldBaselineBackupAndRehearsalTimesUnchanged:true,onceV3GateAndInMemoryIntentValidationPassed:true,actualIntentWritten:false,rootSoleExecutor:true,additionalRootCondition:'Root must separately observe all six successful CI checks on new ops-only head before execution; this gate targets original75d8 app and expires at earliest raw evidence window. Do not execute if expiry passed.',limits:'Migration only. Admission/deployment require actual predecessor success and new fresh stage reviews. No provider/DB/Git/archive-unseal actions by QA.'}
await writeM80HostedEvidenceOnce('evaluations/research-qa/m80-normalized-actual-upgrade-independent-20260925-migration-review.json',publicReceipt)
console.log(JSON.stringify({gate:gateLoaded.pin,security:securityEvidence.pin,target:targetEvidence.pin,reviewedAt,expiresAt,stage:'migration',intentWritten:false}))
