import {test,expect} from 'bun:test'
import {createPostgresConnection,HostedWorkspaceDatabase,migratePrivateStaging,provisionStagingRoster} from '../../packages/neuvetra-database/src/index'
import {M80_FIXTURE_SHA256} from '../../packages/neuvetra-database/src/m80-fixture'
import {createStagingServer} from '../../apps/site-api/src/staging/server'
import {loadM80Foundation,loadM80Version,saveM80Foundation,createM80SaveAttempt,cloneM80Setup,decodeM80Foundation} from '../../apps/site-web/src/lib/m80-beta-api'
import {m80SetupPermissions,m80LoadIsCurrent} from '../../apps/site-web/src/lib/m80-beta-ui-state'
import {createHash} from 'node:crypto'
import {readFileSync} from 'node:fs'
async function refuses(p:Promise<unknown>,status?:number){let error:any;try{await p}catch(e){error=e}expect(error).toBeDefined();if(status)expect(error.status).toBe(status);return error}
const digest=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex')
test('independent actual UI client to native mounted API integration',async()=>{
 const name='m80_setup_qa_'+Date.now(),url=`postgres://supabase_admin@127.0.0.1:55472/${name}`,runtimeUrl=url.replace('supabase_admin','neuvetra_runtime'),admin=createPostgresConnection('postgres://supabase_admin@127.0.0.1:55472/postgres',{tls:false,maxConnections:1})
 try{await admin.exec(`create database ${name} template m78_author_native_1789620106488`)}finally{await admin.close()}
 const op=createPostgresConnection(url,{tls:false,maxConnections:1}),runtime=createPostgresConnection(runtimeUrl,{tls:false,maxConnections:4}),checks:string[]=[],decoderFindings:any[]=[],before=digest('apps/site-web/src/lib/m80-beta-api.ts');let server:any
 const check=async(name:string,fn:()=>Promise<void>)=>{await fn();checks.push(name);console.log('PASS '+name)}
 try{
 const projectRef=(await op.query<{project_ref:string}>('select project_ref from neuvetra.staging_target')).rows[0]!.project_ref
 await migratePrivateStaging(op,{expectedProjectRef:projectRef,syntheticTargetConfirmed:true,reuseExistingProject:true})
 const users={owner:crypto.randomUUID(),member:crypto.randomUUID(),other:crypto.randomUUID()},company=crypto.randomUUID(),otherCompany=crypto.randomUUID()
 for(const id of Object.values(users))await op.query('insert into auth.users(id)values($1)',[id])
 await provisionStagingRoster(op,{expectedProjectRef:projectRef,workspaceId:company,ownerUserId:users.owner,members:[{userId:users.member,role:'member'}]})
 await provisionStagingRoster(op,{expectedProjectRef:projectRef,workspaceId:otherCompany,ownerUserId:users.other,members:[]})
 for(const id of [company,otherCompany])await op.query("insert into neuvetra.scope1_beta_fixture_admissions(company_id,fixture_profile_id,fixture_version,fixture_sha256,active,admitted_by)values($1,'m80-synthetic-scope1-foundation-v1',1,$2,true,$3)",[id,M80_FIXTURE_SHA256,users.owner])
 const origin='http://127.0.0.1:48080',database=new(HostedWorkspaceDatabase as any)(runtime,projectRef,true)
 const app=await createStagingServer({profile:'neuvetra.private-synthetic-staging.v1',origin,projectRef,reuseExistingProject:true,supabaseUrl:'https://synthetic.invalid',supabaseAnonKey:'synthetic-not-a-credential',databaseUrl:runtimeUrl,webRoot:'.',port:0},{database,validateUser:async token=>users[token as keyof typeof users]?{id:users[token as keyof typeof users],email:null,phone:null,fullName:null}:null,verifyAssets:async()=>{},serveAsset:async()=>null,log:()=>{}})
 server=Bun.serve({hostname:'127.0.0.1',port:0,fetch:app.fetch})
 const transport=(async(input:any,init:any)=>{const headers=new Headers(init?.headers);headers.set('origin',origin);return fetch('http://127.0.0.1:'+server.port+input,{...init,headers})}) as typeof fetch
 const owner={accessToken:'owner',userId:users.owner,role:'member' as const},member={accessToken:'member',userId:users.member,role:'owner' as const},other={accessToken:'other',userId:users.other,role:'owner' as const}
 let view=await loadM80Foundation(company,owner,transport),first:any,second:any,attempt=createM80SaveAttempt(view,view.setup)
 await check('actual read plus server permission overrides untrusted client role',async()=>{expect(view.setup.sources.length).toBe(14);expect(view.canManage).toBe(true);const v=await loadM80Foundation(company,member,transport);expect(v.canManage).toBe(false);expect(m80SetupPermissions(v,true,true).canEdit).toBe(false);expect(m80SetupPermissions(view,false,true).canEdit).toBe(true);await refuses(saveM80Foundation(company,attempt,member,transport),403);await refuses(loadM80Foundation(company,other,transport),404)})
 await check('uncertain save then same exact attempt replays one persisted version',async()=>{let lost=false;const lose=(async(i:any,n:any)=>{const r=await transport(i,n);if(!lost){lost=true;await r.text();throw Error('synthetic lost response')}return r})as typeof fetch;await refuses(saveM80Foundation(company,attempt,owner,lose));const r=await saveM80Foundation(company,attempt,owner,transport);expect(r.replayed).toBe(true);expect(r.foundation.history.length).toBe(1);first=r.savedVersion;view=r.foundation;expect(first.createdBy).toBe(users.owner)})
 await check('single correction retains history and stale CAS refuses',async()=>{const draft=cloneM80Setup(view.setup);draft.boundaryProposal.jointVentureState='unknown';const correction=createM80SaveAttempt(view,draft);const r=await saveM80Foundation(company,correction,owner,transport);expect(r.replayed).toBe(false);expect(r.foundation.history.length).toBe(2);second=r.savedVersion;view=r.foundation;expect(second.previousVersionId).toBe(first.id);expect(await loadM80Version(company,first.id,owner,transport)).toEqual(first);await refuses(saveM80Foundation(company,{...correction,request:{...correction.request,idempotencyKey:crypto.randomUUID()}},owner,transport),409)})
 await check('old replay binds original saved version while exposing later head',async()=>{const r=await saveM80Foundation(company,attempt,owner,transport);expect(r.replayed).toBe(true);expect(r.savedVersion).toEqual(first);expect(r.foundation.currentVersion?.id).toBe(second.id)})
 await check('tenant and request bindings reject swapped responses',async()=>{const foreign=await loadM80Foundation(otherCompany,other,transport);const fake=(v:any)=>(async()=>Response.json(v))as typeof fetch;await refuses(loadM80Foundation(company,owner,fake(foreign)));await refuses(loadM80Version(company,first.id,owner,fake(second)));const correct=await saveM80Foundation(company,attempt,owner,transport);await refuses(saveM80Foundation(company,attempt,{...owner,userId:users.member},fake(correct)));const changed=structuredClone(attempt);(changed.request.setup as any).boundaryProposal.jointVentureState='unknown';await refuses(saveM80Foundation(company,changed,owner,fake(correct)));await refuses(loadM80Version(otherCompany,first.id,other,transport),404)})
 await check('role revocation defeats cached authority and triggers unauthorized handler',async()=>{await op.query("update neuvetra.company_members set role='member' where company_id=$1 and user_id=$2",[company,users.owner]);let invalidated=0;await refuses(saveM80Foundation(company,createM80SaveAttempt(view,view.setup),{...owner,onUnauthorized:()=>{invalidated++}},transport),403);expect(invalidated).toBe(1);expect((await loadM80Foundation(company,owner,transport)).canManage).toBe(false);await op.query("update neuvetra.company_members set role='owner' where company_id=$1 and user_id=$2",[company,users.owner])})
 await check('abort during pending successful body prevents stale load/save/history delivery',async()=>{for(const kind of ['load','save','history']){const controller=new AbortController();let started!:()=>void,release!:()=>void;const start=new Promise<void>(r=>started=r),gate=new Promise<void>(r=>release=r);const delayed=(async(i:any,n:any)=>{const response=await transport(i,{...n,signal:undefined});const bytes=await response.arrayBuffer();return new Response(new ReadableStream({async start(c){started();await gate;c.enqueue(new Uint8Array(bytes));c.close()}}),{status:response.status,headers:response.headers})}) as typeof fetch;const actor={...owner,signal:controller.signal};const pending=kind==='load'?loadM80Foundation(company,actor,delayed):kind==='save'?saveM80Foundation(company,attempt,actor,delayed):loadM80Version(company,first.id,actor,delayed);await start;controller.abort();release();await refuses(pending);expect(m80LoadIsCurrent('old','new',false)).toBe(false)}})
 await check('pre-aborted actor sends no request and response byte/duplicate-key limits refuse',async()=>{let sent=0;const dead=new AbortController();dead.abort();await refuses(loadM80Foundation(company,{...owner,signal:dead.signal},(async()=>{sent++;return Response.json(view)})as typeof fetch));expect(sent).toBe(0);for(const text of ['x'.repeat(250001),'{"canManage":true,"canManage":false}',JSON.stringify(view).replace('"canManage":true','"canManage":true,"canManage":true')])await refuses(loadM80Foundation(company,owner,(async()=>new Response(text))as typeof fetch))})
 await check('history decoder independent corruption probes recorded',async()=>{for(const field of ['createdBy','createdAt','payloadSha256']){const v=structuredClone(view) as any;v.history[0][field]=field==='createdBy'?users.member:field==='createdAt'?'2026-09-25T00:00:00.000Z':'0'.repeat(64);let accepted=true;try{await decodeM80Foundation(v,company)}catch{accepted=false}decoderFindings.push({name:'history '+field+' modified without version hash',accepted})}const v=structuredClone(view) as any;v.history[1].createdBy=users.member;let accepted=true;try{await decodeM80Foundation(v,company)}catch{accepted=false}decoderFindings.push({name:'current summary creator differs from current version',accepted});expect(decoderFindings.filter(r=>r.accepted)).toEqual([])})
 }finally{server?.stop(true);await runtime.close();await op.close();await Bun.write('evaluations/research-qa/m80-setup-integration-independent-20260924-native-candidate2.json',JSON.stringify({name,sourceClientSha256:before,sourceClientSha256After:digest('apps/site-web/src/lib/m80-beta-api.ts'),checks,decoderFindings,connectionsClosed:true,clusterOwner:'/root/m80_foundation_runtime',authBoundary:'synthetic token map; actual native adapter and mounted HTTP server; provider authentication untested'},null,2)+'\n')}
},60000)
