import {readFile} from 'node:fs/promises'
import {input,NOW,semanticEvidence} from './m80-hosted-prep-independent-20260924-candidate4-fixture'
import {buildM80HostedPreparationPlan,m80HostedCanonicalJson,m80HostedSha256} from './m80-hosted-prep-independent-20260924-candidate5-frozen-prepare'
const snapshot=JSON.parse(await readFile('operations/agent-improvement/snapshots/M80-BACKUP-REHEARSAL-PREP-20260924-CANDIDATE1.json','utf8'))
const source=(name:string)=>snapshot.artifacts.find((x:any)=>x.path.endsWith(name)).text as string
const entry=source('hosted-entry.ts'),local=source('local-rehearsal.ts'),results:any[]=[]
const prepared='823d176736a7aa0ed979b677bcb5807de8f3d9ece48e3c631dafda043dc21bbe',helper='7'.repeat(64),state={applicationStateSha256:'1'.repeat(64),observedNonReceiptTables:['neuvetra.test']}
const review={verdict:'fail',reviewer:null,unrelatedValues:[prepared,helper,'pass']},reviewBytes=Buffer.from(JSON.stringify(review))
const admission={profile:'neuvetra.m80.foundation-backup-admission.v1',observedAt:new Date().toISOString(),operatorId:'/root',projectRef:'icockcoguyadhryzydvl',targetClassification:'private_synthetic_staging',sourceSchemaVersion:21,migrationReceiptCount:21,...state,observedNonReceiptTableCount:1,syntheticDataOnlyVerified:true,applicationOnly:true,providerRecoveryExcluded:true,candidateSha256:'40c4ac822ef2d045457ade7dd63d471813178c8f3a585425be58eb81013de59b',migrationSha256:'0ee148b366e803e8cf28187393f9e5a6f19b29f5bb54578e359db7cbcd795e35',preparationCandidateSha256:prepared,backupHelperSha256:helper,independentReview:{path:'virtual-review.json',sha256:m80HostedSha256(reviewBytes)},rootBackupExecutionAccepted:true},admissionBytes=Buffer.from(JSON.stringify(admission))
const privateCode=entry.slice(entry.indexOf('function deepContains'),entry.indexOf('export async function helperPins'))+entry.slice(entry.indexOf('async function validateAdmission'),entry.indexOf('export async function backupHostedSource'))
const compiled=new Bun.Transpiler({loader:'ts'}).transformSync(privateCode),AsyncFunction=Object.getPrototypeOf(async()=>{}).constructor
for(const accepted of [null,prepared]){const bindings={ACCEPTED_PREPARATION_CANDIDATE_SHA256:accepted,readFile:async(p:string)=>p==='virtual-review.json'?reviewBytes:admissionBytes,sha:m80HostedSha256,hash:(v:any)=>m80HostedSha256(m80HostedCanonicalJson(v)),check:(v:any,m:string)=>{if(!v)throw Error(m)},exactKeys:(v:any,k:string[],m:string)=>{if(Object.keys(v).sort().join('|')!==[...k].sort().join('|'))throw Error(m)},helperPins:async()=>({helperSha256:helper}),ADMISSION_PROFILE:admission.profile,PROJECT_REF:admission.projectRef,RUNTIME_CANDIDATE_SHA256:admission.candidateSha256,MIGRATION_SHA256:admission.migrationSha256}
 try{await new AsyncFunction(...Object.keys(bindings),compiled+';return validateAdmission("virtual-admission.json",'+JSON.stringify(m80HostedSha256(admissionBytes))+','+JSON.stringify(state)+')')(...Object.values(bindings));results.push({case:'failed_null_reviewer_with_unrelated_pass',enabledOnlyInIsolatedHarness:accepted!==null,accepted:true})}catch(e){results.push({case:'failed_null_reviewer_with_unrelated_pass',enabledOnlyInIsolatedHarness:accepted!==null,accepted:false,error:String(e)})}}
const value=input(),declaration=local.slice(local.indexOf('const migrationReceipt: MigrationRehearsalReceipt'),local.indexOf('const restoreWrite ='))
const FakeDate=class extends Date{constructor(){super(value.rehearsal.completedAt)}}
const receipt=new Function('Date','REHEARSAL_PROFILE','database','MIGRATION_SHA256','EXPECTED_NEW_TABLES','EXPECTED_NEW_TABLE_ROW_COUNTS','runtime',new Bun.Transpiler({loader:'ts'}).transformSync(declaration)+';return migrationReceipt')(FakeDate,'neuvetra.m80.foundation-hosted-migration-rehearsal-receipt.v1',value.rehearsal.disposableDatabaseName,value.rehearsal.migrationSha256,value.rehearsal.expectedNewTables,value.rehearsal.expectedNewTableRowCounts,{selectOnly:true,directWritesDenied:true,admissionNotExecuted:true})
const evidence=semanticEvidence(value);evidence.set(value.rehearsal.migrationReceipt.path,receipt)
try{await buildM80HostedPreparationPlan(value,{now:NOW,verifyPin:async()=>{},loadJsonEvidence:async p=>evidence.get(p.path)});results.push({case:'generated_rehearsal_receipt',accepted:true})}catch(e){results.push({case:'generated_rehearsal_receipt',accepted:false,missingHeldFlag:!('releaseRecordsExactFourHeld'in receipt),error:String(e)})}
const imports=[...entry.matchAll(/from "([^"]+)"/g)].map(x=>x[1]);const pins=entry.slice(entry.indexOf('const HELPER_PATHS'),entry.indexOf('const CA_PATH'));results.push({case:'closure',directImports:imports,pinDeclaration:pins,importedInventoryPinned:pins.includes('m78-inventory'),operatorPinned:pins.includes('m73-common'),freshHostedArchiveRestoreEntrypoint:local.includes('export async function restoreSnapshot')})
await Bun.write('evaluations/research-qa/m80-backup-rehearsal-independent-20260924-probes.json',JSON.stringify({boundary:'Exact frozen private functions evaluated with synthetic virtual files; null pin changed only in isolated latent-gate probe; no DB/process/credential/network action.',results},null,2)+'\n');console.log(JSON.stringify(results,null,2))
