import {test,expect} from 'bun:test'
import {mkdir,readFile} from 'node:fs/promises'
import {resolve} from 'node:path'
import {input,gate,pin,NOW} from './m80-hosted-prep-independent-20260924-fixture'
import {buildM80HostedPreparationPlan} from './m80-hosted-prep-independent-20260924-frozen-prepare'
import {sealM80HostedIntent,recordM80HostedOutcome,m80HostedIntentPath,writeM80HostedEvidenceOnce,M80_HOSTED_OBSERVATION_PROFILE} from './m80-hosted-prep-independent-20260924-frozen-once'
async function rejects(p:Promise<any>){let failed=false;try{await p}catch{failed=true}expect(failed).toBe(true)}
test('independent frozen candidate1 existing fail-closed and durable controls',async()=>{
 const p=await buildM80HostedPreparationPlan(input(),{now:NOW}),planPin=pin('evaluations/research-qa/m80-hosted-prep-independent-20260924-plan.json','e'),gatePin=pin('evaluations/research-qa/m80-hosted-prep-independent-20260924-gate.json','f'),checks:string[]=[]
 for(const[name,edit]of [['stale target',(v:any)=>v.observedTarget.observedAt='2026-09-24T21:00:00.000Z'],['backup mismatch',(v:any)=>v.backup.sourceApplicationStateSha256='f'.repeat(64)],['count mismatch',(v:any)=>v.rehearsal.sourceObservedNonReceiptTableCount=124],['wrong migration',(v:any)=>v.acceptedRuntime.migration.sha256='f'.repeat(64)],['duplicate checks',(v:any)=>v.publication.requiredChecks[1]=v.publication.requiredChecks[0]],['unknown field',(v:any)=>v.surprise=true],['null permission',(v:any)=>v.observedTarget.maintenanceEnabled=null]]as const){const v=input();edit(v);await rejects(buildM80HostedPreparationPlan(v,{now:NOW}));checks.push(name)}
 for(const[name,edit]of [['expired',(g:any)=>g.expiresAt='2026-09-24T22:11:00.000Z'],['self review',(g:any)=>g.independentReviewerId='/root'],['wrong stage',(g:any)=>g.stage='deployment'],['wrong current schema',(g:any)=>g.currentSchemaVersion=22],['wrong app state',(g:any)=>g.currentApplicationStateSha256='e'.repeat(64)],['missing maintenance',(g:any)=>g.maintenanceEnabled=false]]as const){const g=gate(p,planPin);edit(g);expect(()=>sealM80HostedIntent({plan:p,planPin,gate:g,gatePin,stage:'migration',now:NOW})).toThrow();checks.push(name)}
 const intent=sealM80HostedIntent({plan:p,planPin,gate:gate(p,planPin),gatePin,stage:'migration',now:NOW});for(const outcome of ['unknown','definitive_failure']){const o=recordM80HostedOutcome({intent,intentPin:pin('evaluations/research-qa/m80-hosted-prep-independent-20260924-intent.json','d'),observation:{profile:M80_HOSTED_OBSERVATION_PROFILE,stage:'migration',observedAt:NOW.toISOString(),transportOutcome:outcome,authoritativeState:{}},now:NOW});expect(o.nextActionAllowed).toBe(false);expect(()=>sealM80HostedIntent({plan:p,planPin,gate:gate(p,planPin,'admission'),gatePin,stage:'admission',migrationOutcome:o,migrationOutcomePin:pin('evaluations/research-qa/m80-hosted-prep-independent-20260924-outcome.json','9'),now:NOW})).toThrow();checks.push(outcome+' blocks nextstage')}
 const alternate=input();alternate.publication.reviewedHeadCommitSha='7'.repeat(40);const p2=await buildM80HostedPreparationPlan(alternate,{now:new Date(NOW.getTime()+60000)});expect(m80HostedIntentPath(p,'migration')).toBe(m80HostedIntentPath(p2,'migration'));expect(m80HostedIntentPath(p,'admission')).not.toBe(m80HostedIntentPath(p,'migration'));checks.push('equivalent scope deterministic across head/time; distinct stage')
 const directory=resolve('evaluations/research-qa/m80-hosted-prep-independent-20260924-sandbox');await mkdir(directory,{recursive:true});const output=resolve(directory,'concurrent-'+Date.now()+'.json'),results=await Promise.allSettled([writeM80HostedEvidenceOnce(output,{writer:1}),writeM80HostedEvidenceOnce(output,{writer:2})]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected')).toHaveLength(1);const before=await readFile(output,'utf8');await rejects(writeM80HostedEvidenceOnce(output,{writer:3}));expect(await readFile(output,'utf8')).toBe(before);checks.push('actual simultaneous exclusive output and byte-preserving replay refusal');await Bun.write('evaluations/research-qa/m80-hosted-prep-independent-20260924-controls.json',JSON.stringify({candidate:'frozen Candidate1',checks,retainedSyntheticOutput:output,scope:'Offline pure validation and own QA sandbox only; no real journal/helper output or provider activity'},null,2)+'\n')
})
