import {artifacts,reviewReaders,MemoryJournal,fakeDatabase,sourceState,successObservation,artifactPin,NOW} from './m80-executor-independent-20260924-candidate3-fixture'
import {executeM80HostedStage,reconcileM80HostedStage,createM80RailwayTransport} from './m80-executor-independent-20260924-candidate3-frozen'
const input=await artifacts('migration'),journal=new MemoryJournal();let transports=0,observations=0
const deps={journal,database:fakeDatabase(),migrationSourceState:sourceState(input),readSourceBytes:reviewReaders.get(input)!,now:()=>NOW,observer:{observe:async()=>{observations++;throw Error('synthetic observer unavailable')}},migrate:async()=>{transports++;throw Error('synthetic committed then connection timeout')}}
const first=await executeM80HostedStage(input,deps)
const find=(suffix:string)=>[...journal.values].find(([path])=>path.endsWith(suffix))!
const [attemptPath,attempt]=find('-attempt.json'),[sourcePath,source]=find('-migration-source.json'),[observationPath,observation]=find('-observation.json')
const restarted=new MemoryJournal();for(const [path,value] of journal.values)restarted.values.set(path,structuredClone(value))
let reconcileError='';try{await reconcileM80HostedStage(input,attempt,artifactPin(attemptPath,attempt),{journal:restarted,readSourceBytes:reviewReaders.get(input)!,now:()=>NOW,migrationSourceReceipt:{value:source,pin:artifactPin(sourcePath,source)},observationReceipt:{value:observation,pin:artifactPin(observationPath,observation)},observer:{observe:async()=>{observations++;return successObservation(input.intent as any)}}})}catch(e){reconcileError=String(e)}
if(first.status!=='uncertain_do_not_retry'||!reconcileError.includes('already exists')||transports!==1||observations!==1)throw Error('Uncertain-reconciliation failure changed')
const deploymentInput=await artifacts('deployment'),plan=deploymentInput.plan as any,railway=createM80RailwayTransport(async args=>args[0]==='api'?{errors:['synthetic timeout/no ack']}:[{id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',status:'SUCCESS',meta:{commitHash:plan.publication.reviewedHeadCommitSha}}],async()=>({status:'ready',profile:'neuvetra.private-synthetic-staging.v1',schemaVersion:22,legacyContainmentVerified:true}))
let requestRefused=false;try{await railway.serviceInstanceDeployV2({environmentId:plan.target.environmentId,serviceId:plan.target.serviceId,commitSha:plan.publication.reviewedHeadCommitSha})}catch{requestRefused=true}
const providerObservation=await railway.observe({stage:'deployment',plan,intent:deploymentInput.intent as any}) as any
if(!requestRefused||providerObservation.transportOutcome!=='definitive_success')throw Error('Historical-deployment false success changed')
const result={boundary:'Exact frozen C3 executor; synthetic journals/transports/provider only; no DB/network',migration:{firstOutcome:first.status,reconcileError,transports,observations,earlierReceiptsRetained:true},deployment:{requestRefused,observationOutcome:providerObservation.transportOutcome,historicalSameCommitAccepted:true},attribution:{deployment:'Author self-audit announced before independent reproduction',migration:'Independent continuation of root pending reconciliation concern; covers ordinary uncertainty not only process crash'}}
await Bun.write('evaluations/research-qa/m80-executor-independent-20260924-candidate3-uncertainty.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result))
