import {createM80FixtureSetup,M80_HELD_REGISTRY,M80_FIXTURE_SHA256} from '../../packages/neuvetra-database/src/m80-fixture'
import {validateM80Setup,classifyM80Foundation} from '../../packages/neuvetra-database/src/m80-validation'
import {decodeM80Foundation} from '../../apps/site-web/src/lib/m80-beta-api'
const company='80000000-0000-4000-8000-000000000010',raw=createM80FixtureSetup(company),admission={companyId:company,fixtureProfileId:'m80-synthetic-scope1-foundation-v1',fixtureVersion:1,fixtureSha256:M80_FIXTURE_SHA256,active:true} as const
const base={profile:'m80-scope1-beta-foundation-runtime-v1',syntheticOnly:true,canManage:true,fixtureAdmission:admission,releaseRegistry:structuredClone(M80_HELD_REGISTRY),currentVersion:null,history:[],setup:validateM80Setup(raw,admission),eligibility:classifyM80Foundation(raw,admission,M80_HELD_REGISTRY)}
await decodeM80Foundation(base,company)
const probes:[string,(v:any)=>void][]=[['boundary enum array',v=>v.setup.boundaryProposal.jointVentureState=[v.setup.boundaryProposal.jointVentureState]],['known fact enum array',v=>v.setup.sources[0].knownFacts.fuelOrGas=[v.setup.sources[0].knownFacts.fuelOrGas]],['evidence state array',v=>v.setup.evidenceRequirements[0].state=[v.setup.evidenceRequirements[0].state]],['source location swap',v=>v.setup.sources[0].locationId=v.setup.locations[1].locationId],['invented classification',v=>{v.eligibility.results[13].state='held_candidate';v.eligibility.results[13].candidateProfileId=v.releaseRegistry[0].profileId;v.eligibility.results[13].blockerCodes=[];v.eligibility.results[13].requiredFactCodes=[]}]]
const results=[];for(const[name,mutate]of probes){const v=structuredClone(base);mutate(v);let accepted=true;try{await decodeM80Foundation(JSON.parse(JSON.stringify(v)),company)}catch{accepted=false};results.push({name,accepted})}
await Bun.write('evaluations/research-qa/m80-setup-integration-independent-20260924-first-probes.json',JSON.stringify({uiSnapshotSha256:'6944d220e356b76c2ddfc7f36f10ebce1e96128b632ba3301e4a38aae726d684',positiveControl:true,results},null,2)+'\n');console.log(results)
