import {test,expect} from 'bun:test'
import {decodeM80Foundation} from '../../apps/site-web/src/lib/m80-beta-api'
import {createM80FixtureSetup,M80_HELD_REGISTRY} from '../../packages/neuvetra-database/src/m80-fixture'
import {validateM80Setup,classifyM80Foundation} from '../../packages/neuvetra-database/src/m80-validation'
const saved=await Bun.file('evaluations/research-qa/m80-setup-integration-independent-20260924-fixture.json').json(),company=saved.fixtureAdmission.companyId,admission=saved.fixtureAdmission
const edits:[string,(v:any)=>void][]=[]
const values={fuelOrGas:['fossil_natural_gas','fossil_distillate_no2','fossil_diesel','gasoline','propane_lpg','renewable_diesel','other_fuel','HFC-134a','HFC-227ea','R-410A','other_gas','not_applicable','unknown'],equipmentKind:['stationary_other','emergency_generator','medium_heavy_on_road_2007_2022','vehicle_other','non_road_equipment','refrigeration','fixed_hvac','fire_suppression','industrial_process','other','unknown'],activityDataKind:['annual_hhv_energy','metered_gallons','gallons_and_actual_miles','service_refill_mass','screen_only','unknown'],activityUnit:['MMBtu_HHV','US_gallon','US_gallon_and_vehicle_mile','kg_named_gas_or_blend','not_applicable','unknown']}
for(let i=0;i<14;i++)for(const[k,vs]of Object.entries(values))for(const value of vs)edits.push([`source${i}.${k}=${value}`,v=>v.sources[i].knownFacts[k]=value])
for(let i=0;i<19;i++)for(const value of ['unknown','missing','synthetic_fixture_reference'])edits.push([`evidence${i}=${value}`,v=>v.evidenceRequirements[i].state=value])
for(const group of ['categories','gasGroups'])for(let i=0;i<7;i++)for(const value of ['unknown','indicated','not_applicable_pending_review'])edits.push([`process.${group}${i}=${value}`,v=>v.sources.find((s:any)=>s.processScreen).processScreen[group][i].state=value])
test('independent legitimate fact/evidence/screen corrections stay decodable',async()=>{const failures:any[]=[];let accepted=0;for(const[name,edit]of edits){const raw=createM80FixtureSetup(company);edit(raw);const setup=validateM80Setup(raw,admission),eligibility=classifyM80Foundation(raw,admission,M80_HELD_REGISTRY);try{await decodeM80Foundation({...saved,currentVersion:null,history:[],setup,eligibility},company);accepted++}catch(e){failures.push({name,error:(e as Error).message})}}await Bun.write('evaluations/research-qa/m80-setup-integration-independent-20260924-valid-matrix.json',JSON.stringify({variants:edits.length,accepted,failures,authority:'Accepted pure contract classifyM80Foundation and validateM80Setup; independent one-field synthetic corrections, no numerical calculation or source release.'},null,2)+'\n');expect(failures).toEqual([]);expect(accepted).toBe(edits.length)},30000)
