import {createPostgresConnection,HostedWorkspaceDatabase} from '../../packages/neuvetra-database/src/index'
import {decodeM80Version} from './m80-setup-integration-independent-20260924-candidate1-api'
import {m80HashCanonical} from '../../packages/neuvetra-database/src/m80-fixture'
const op=createPostgresConnection('postgres://supabase_admin@127.0.0.1:55472/m80_setup_qa_1790287311429',{tls:false,maxConnections:1}),runtime=createPostgresConnection('postgres://neuvetra_runtime@127.0.0.1:55472/m80_setup_qa_1790287311429',{tls:false,maxConnections:1});try{
const r=(await op.query<any>('select company_id,created_by from neuvetra.scope1_beta_setup_versions order by revision desc limit 1')).rows[0],ref=(await op.query<any>('select project_ref from neuvetra.staging_target')).rows[0].project_ref,db=new(HostedWorkspaceDatabase as any)(runtime,ref,true),view=await db.findM80Foundation(r.created_by,r.company_id)
await Bun.write('evaluations/research-qa/m80-setup-integration-independent-20260924-fixture.json',JSON.stringify(view,null,2)+'\n')
await decodeM80Version(view.currentVersion,r.company_id,view.currentVersion.id);console.log("FROZEN POSITIVE CONTROL PASS");
const rehash=(v:any)=>{v.versionSha256=m80HashCanonical({profile:view.profile,id:v.id,companyId:v.companyId,reportingYear:v.reportingYear,revision:v.revision,previousVersionId:v.previousVersionId,previousVersionSha256:v.previousVersionSha256,fixtureProfileId:view.fixtureAdmission.fixtureProfileId,fixtureVersion:1,fixtureSha256:view.fixtureAdmission.fixtureSha256,payloadSha256:v.payloadSha256,createdBy:v.createdBy,createdAt:v.createdAt,dataClassification:'synthetic_rehearsal',completeness:'incomplete',releasedSupportedCount:0})}
const results=[];for(const[name,mutate]of [['invalid calendar date',(v:any)=>v.createdAt='2026-02-30T00:00:00.000Z'],['revision1 with predecessor',(v:any)=>v.revision=1],['revision2 with null predecessor',(v:any)=>{v.previousVersionId=null;v.previousVersionSha256=null}],['self predecessor',(v:any)=>v.previousVersionId=v.id]]as const){const v=structuredClone(view.currentVersion);mutate(v);rehash(v);let accepted=true;try{await decodeM80Version(v,r.company_id,v.id)}catch{accepted=false}results.push({name,accepted})}console.log(results);await Bun.write('evaluations/research-qa/m80-setup-integration-independent-20260924-extra-probes.json',JSON.stringify(results,null,2)+'\n')
}finally{await runtime.close();await op.close()}
