/** Explicit bounded operator journey. Imports never authenticate, read ENV/private files, or write. */
import path from 'node:path'
import {open,unlink} from 'node:fs/promises'
import {parseJourneyInput} from './check-hosted-journey'
import {readM74Journal} from './check-m74-hosted'
import {runM72Journey} from './check-m72-hosted'
import {decodeCorporateRegister,decodeCorporateVersion,decodeCorporateReview} from '../../apps/site-web/src/lib/m71-api'
import {decodeGasRegister} from '../../apps/site-web/src/lib/m73-api'
import {decodeMobileRegister,decodeMobileVersion,decodeMobileReview} from '../../apps/site-web/src/lib/m74-api'
import {decodeFleetRegister,decodeFleetVersion,decodeFleetReview,fleetReportDownload,fleetReportSnapshotDownload} from '../../apps/site-web/src/lib/m75-api'
import {M71_ARTIFACT,M71_EVIDENCE_SHA256,M71_LIMITATIONS,M74_PROFILE,M74_PERIOD,M74_LIMITATIONS,M75_PROFILE,M75_PERIOD,M75_LIMITATIONS,m74SourceChoices,m74CanonicalJson,m74Export,m73Export,m75Export,m75ReportHashPayload,m75RenderReport,type M74Version,type M75Version,type M75Register,type M75Report,type M75SaveInput} from '../../packages/neuvetra-database/src/index'
const HOST='https://www.neuvetra.ai',AUTH='https://icockcoguyadhryzydvl.supabase.co'
const RECEIPT=path.resolve(import.meta.dir,'../../.superpowers/m75-hosted-journey.jsonl'),PREVIOUS=path.resolve(import.meta.dir,'../../.superpowers/m74-hosted-journey.jsonl')
type Mode='baseline'|'exercise'|'revisit'
type Input=ReturnType<typeof parseJourneyInput>&{mode:Mode}
type Role=Input['accounts'][number]['role']|'signed_out'
type Event={sequence:number;previousSha256:string|null;workspaceId:string;mode:Mode;kind:string;data:any;createdAt:string;sha256:string}
type Dependencies={fetch?:typeof fetch;load?:()=>Promise<string|null>;append?:(line:string,exclusive:boolean)=>Promise<void>;loadPrevious?:()=>Promise<string>;legacy?:typeof runM72Journey}
const check=(v:unknown):void=>{if(!v)throw Error('Bounded M75 journey refused.')}
const hash=(v:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(v).digest('hex'),canonical=m74CanonicalJson,same=(a:unknown,b:unknown)=>canonical(a)===canonical(b)
const observation=(text:string)=>({sha256:hash(text),byteLength:Buffer.byteLength(text)})
export function parseM75JourneyInput(value:unknown):Input{const mode=(value as any)?.mode;check(['baseline','exercise','revisit'].includes(mode));return {...parseJourneyInput(value),mode}}
export function validateM75JourneyRoute(url:string,method:string,company:string){
 const u=new URL(url);check(!u.hash&&!u.username&&!u.password);const root=`/workspace-api/workspace/${company}`
 if(u.origin===AUTH){check(method==='POST'&&(u.pathname==='/auth/v1/token'&&u.search==='?grant_type=password'||u.pathname==='/auth/v1/logout'&&u.search==='?scope=local'));return}
 check(u.origin===HOST&&!u.search&&(u.pathname==='/ready'||u.pathname==='/workspace-api/config'||u.pathname==='/workspace-api/session'||u.pathname===root||u.pathname.startsWith(root+'/')))
 if(method!=='GET')check(method==='POST'&&(u.pathname===root+'/mobile-diesel'||u.pathname===root+'/controlled-fleet'||new RegExp('^'+root+'/corporate-inventories/[0-9a-f-]{36}/(versions|reviews)$').test(u.pathname)||new RegExp('^'+root+'/(mobile-diesel|controlled-fleet)/[0-9a-f-]{36}/(versions|reviews|reports)$').test(u.pathname)))
}
export function readM75Journal(text:string|null,company:string):Event[]{if(text===null)return [];check(text.length<=48_000_000&&text.endsWith('\n'));const events=text.trimEnd().split('\n').map(line=>JSON.parse(line)) as Event[];let previous:string|null=null;for(const[i,event]of events.entries()){const{sha256,...payload}=event;check(event.sequence===i+1&&event.previousSha256===previous&&event.workspaceId===company&&['baseline','exercise','revisit'].includes(event.mode)&&typeof event.kind==='string'&&typeof event.createdAt==='string'&&hash(canonical(payload))===sha256);previous=sha256}return events}
export async function runM75Journey(input:Input,deps:Dependencies={}){
 const events:Event[]=[],tokens=new Map<Role,string>(),company=input.roster.workspaceId,root=`/workspace-api/workspace/${company}`,corporateRoot=root+'/corporate-inventories',mobileRoot=root+'/mobile-diesel',fleetRoot=root+'/controlled-fleet'
 let stage='receipt_load',writes=0,unknownSessions=0,closed=true,legacyClosed=true,failed=false,loaded=false,attemptSequence:number|null=null
 const transport=deps.fetch??globalThis.fetch
 const network=async(url:string,init:RequestInit={})=>{validateM75JourneyRoute(url,init.method??'GET',company);return transport(url,{...init,redirect:'error',signal:AbortSignal.timeout(30000)})}
 const append=async(kind:string,data:any)=>{const payload={sequence:events.length+1,previousSha256:events.at(-1)?.sha256??null,workspaceId:company,mode:input.mode,kind,data,createdAt:new Date().toISOString()},event={...payload,sha256:hash(canonical(payload))},line=JSON.stringify(event)+'\n';await(deps.append??(async(line,exclusive)=>{const f=await open(RECEIPT,exclusive?'wx':'a');try{await f.writeFile(line);await f.sync()}finally{await f.close()}}))(line,events.length===0);events.push(event)}
 const completed=(name:string)=>events.find(e=>e.kind==='post_outcome'&&e.data.name===name)
 const decodeOutcome=async(name:string,value:any)=>{
  if(name==='m71_fleet_sources')return decodeCorporateVersion(value,company)
  if(name==='m71_fleet_review')return decodeCorporateReview(value,company)
  if(/^m74_(a_relink|b_save|b_correction)$/.test(name))return decodeMobileVersion(value,company)
  if(/^m74_.*_review$/.test(name))return decodeMobileReview(value,company)
  if(/^m75_save_[1-4]$/.test(name))return decodeFleetVersion(value,company)
  if(/^m75_review_[1-4]$/.test(name))return decodeFleetReview(value,company)
  if(/^m75_report_[1-3]$/.test(name)){
   check(value?.companyId===company&&typeof value.html==='string'&&typeof value.snapshotJson==='string'&&value.rendererVersion==='m75-fleet-reconciliation-report-v1')
   check(hash(value.html)===value.htmlSha256&&Buffer.byteLength(value.html)===value.htmlByteLength&&hash(value.snapshotJson)===value.snapshotSha256&&hash(canonical(m75ReportHashPayload(value)))===value.reportSha256)
   const snap=JSON.parse(value.snapshotJson);await decodeFleetVersion(snap.version,company);if(snap.review)await decodeFleetReview(snap.review,company,snap.version);check(canonical(snap)===value.snapshotJson&&m75RenderReport(snap)===value.html);return value as M75Report
  }
  throw Error('Unknown successful operation')
 }
 const get=async(name:string,route:string,role:Role='manager1'):Promise<any>=>{stage=name;const r=await network(HOST+route,{headers:{origin:HOST,...(tokens.has(role)?{authorization:'Bearer '+tokens.get(role)}:{})}}),bytes=new Uint8Array(await r.arrayBuffer());check(r.status===200&&r.headers.get('cache-control')?.includes('no-store')&&bytes.length<=4_000_000);const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);try{return JSON.parse(text)}catch{return text}}
 const post=async(name:string,route:string,role:Role,build:()=>Promise<unknown>|unknown,expected=201):Promise<any>=>{
  stage=name;check(input.mode==='exercise');const old=completed(name)
  if(old){check(old.data.route===route&&old.data.role===role&&old.data.expected===expected&&old.data.status===expected);return expected===201?decodeOutcome(name,old.data.response):undefined}
  check(!events.some(e=>e.kind==='post_intent'&&e.data.name===name));const request=await build();await append('post_intent',{name,route,role,expected,request});writes++
  const r=await network(HOST+route,{method:'POST',headers:{origin:HOST,...(tokens.has(role)?{authorization:'Bearer '+tokens.get(role)}:{}),'content-type':'application/json'},body:JSON.stringify(request)}),bytes=new Uint8Array(await r.arrayBuffer());check(bytes.length<=4_000_000&&r.headers.get('cache-control')?.includes('no-store'))
  if(r.status!==expected||expected!==201){await append('post_outcome',{name,route,role,expected,status:r.status,responseObservation:{sha256:hash(bytes),byteLength:bytes.length}});check(r.status===expected);return undefined}
  const decoded=await decodeOutcome(name,JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes)));await append('post_outcome',{name,route,role,expected,status:r.status,response:decoded});return decoded
 }
 const download=async(name:string,route:string,expected:string)=>{stage=name;const r=await network(HOST+route,{headers:{origin:HOST,authorization:'Bearer '+tokens.get('member')}}),bytes=new Uint8Array(await r.arrayBuffer());check(r.status===200&&r.headers.get('cache-control')?.includes('no-store')&&bytes.length<=4_000_000&&new TextDecoder('utf-8',{fatal:true}).decode(bytes)===expected);return observation(expected)}
 const corporate=async()=>decodeCorporateRegister(await get('corporate_read',corporateRoot),company),mobile=async()=>decodeMobileRegister(await get('mobile_read',mobileRoot),company),fleet=async()=>decodeFleetRegister(await get('fleet_read',fleetRoot),company)
 const corporateDownloads=async(reg:any)=>{const out:Record<string,unknown>={};for(const v of reg.versions)out[v.id]=await download('coverage_export',`${corporateRoot}/${v.inventoryId}/versions/${v.id}/coverage-export`,canonical({...v,review:null}));return out}
 const mobileDownloads=async(reg:any)=>{const out:Record<string,unknown>={};for(const w of reg.worksheets){for(const v of w.versions){out['version_'+v.id]=await download('mobile_export',`${mobileRoot}/${w.worksheetId}/versions/${v.id}/calculation-export`,m74Export(v));for(const[kind,s]of[['fuel',v.fuelStatement],['mileage',v.mileageStatement]] as const)if(s)out[kind+'_'+s.id]=await download('mobile_statement',`${mobileRoot}/${w.worksheetId}/statements/${s.id}/download`,s.text)}for(const r of w.reports)out['report_'+r.id]=await download('mobile_report',`${mobileRoot}/${w.worksheetId}/reports/${r.id}/download`,r.html)}return out}
 const fleetDownloads=async(reg:M75Register)=>{
  const out:Record<string,unknown>={};for(const v of reg.versions){out['version_'+v.id]=await download('fleet_export',`${fleetRoot}/${v.rosterId}/versions/${v.id}/roster-export`,m75Export(v));if(v.statement)out['statement_'+v.statement.id]=await download('fleet_statement',`${fleetRoot}/${v.rosterId}/statements/${v.statement.id}/download`,v.statement.text)}
  const saved=globalThis.fetch
  try{globalThis.fetch=(async(url:any,init:RequestInit={})=>{check(typeof url==='string'&&url.startsWith(fleetRoot)&&(init.method??'GET')==='GET'&&!init.body);return network(HOST+url,{...init,headers:{...Object.fromEntries(new Headers(init.headers)),origin:HOST}})}) as typeof fetch
   const actor={accessToken:tokens.get('member')!,userId:input.accounts.find(a=>a.role==='member')!.id,role:'member' as const}
   for(const r of reg.reports){out['snapshot_'+r.id]=observation(await fleetReportSnapshotDownload(actor,company,r));out['report_'+r.id]=observation(await fleetReportDownload(actor,company,r));out['proof_'+r.id]=hash(canonical(await get('fleet_report_proof',`${fleetRoot}/${r.rosterId}/reports/${r.id}/proof`,'member')))}
  }finally{globalThis.fetch=saved}return out
 }
 const preserveVersions=(before:any,current:any)=>{for(const v of before.versions)check(same(current.versions.find((x:any)=>x.id===v.id),v))}
 const preserveMobile=(before:any,current:any)=>{for(const w of before.worksheets){const now=current.worksheets.find((x:any)=>x.worksheetId===w.worksheetId);check(now);preserveVersions(w,now);for(const r of w.reports)check(same(now.reports.find((x:any)=>x.id===r.id),r))}}
 try{
  events.push(...readM75Journal(deps.load?await deps.load():await Bun.file(RECEIPT).exists()?await Bun.file(RECEIPT).text():null,company));loaded=true;stage='resume_preconditions'
  check(!events.some(e=>e.kind==='attempt_started'&&!events.some(x=>x.kind==='attempt_finished'&&x.data.attemptSequence===e.sequence))&&!events.some(e=>e.kind==='post_intent'&&!completed(e.data.name))&&!events.some(e=>e.kind==='attempt_finished'&&e.data.allCreatedAuthSessionsClosed===false)&&!events.some(e=>e.kind==='post_outcome'&&e.data.status!==e.data.expected))
  const baseline=events.find(e=>e.kind==='baseline'),success=events.find(e=>e.kind==='exercise_complete');check(input.mode==='baseline'?!baseline:!!baseline);check(input.mode==='revisit'?!!success:input.mode==='exercise'?!success:true)
  await append('attempt_started',{mode:input.mode});attemptSequence=events.at(-1)!.sequence
  const priorEvents=readM74Journal(await(deps.loadPrevious?deps.loadPrevious():Bun.file(PREVIOUS).text()),company),prior=priorEvents.find(e=>e.kind==='exercise_complete')?.data,priorBaseline=priorEvents.find(e=>e.kind==='baseline')?.data
  check(prior&&priorBaseline&&priorEvents.some(e=>e.kind==='revisit_verified')&&!priorEvents.some(e=>e.kind==='attempt_started'&&!priorEvents.some(x=>x.kind==='attempt_finished'&&x.data.attemptSequence===e.sequence))&&!priorEvents.some(e=>e.kind==='attempt_finished'&&e.data.allCreatedAuthSessionsClosed===false))
  let legacy:any;stage='legacy_read_only'
  const verifyLegacy=async()=>{const legacyResult=await(deps.legacy??runM72Journey)({...input,mode:'baseline'},{load:async()=>null,save:async value=>{legacy=value},fetch:(async(url,init)=>{const target=String(url);check(!(target.startsWith(HOST)&&init?.method==='POST'));const r=await network(target,init);if(target===HOST+'/ready'){const v=await r.json() as any;check(r.status===200&&v.schemaVersion===(input.mode==='baseline'?17:18));await append('actual_readiness',{schemaVersion:v.schemaVersion});return Response.json({...v,schemaVersion:14},{status:r.status,headers:r.headers})}return r}) as typeof fetch});legacyClosed&&=legacyResult.allCreatedAuthSessionsClosed;check(legacyResult.status==='passed'&&legacyClosed&&legacyResult.applicationPostRequests===0&&same(legacy.baseline,priorBaseline.legacy));if(baseline)check(same(legacy.baseline,baseline.data.legacy))}
  await verifyLegacy()
  for(const account of input.accounts){stage='sign_in_'+account.role;unknownSessions++;const r=await network(AUTH+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:input.env.SUPABASE_ANON_KEY,'content-type':'application/json'},body:JSON.stringify({email:account.email,password:account.password})}),s=await r.json() as any;if(typeof s.access_token==='string'&&s.access_token.length>0&&s.access_token.length<=8192){tokens.set(account.role,s.access_token);unknownSessions--}check(r.status===200&&s.user?.id===account.id&&tokens.has(account.role))}
  const verifyGas=async()=>{const gas=await decodeGasRegister(await get('gas_preserved',root+'/stationary-natural-gas'),company);check(same(gas.worksheets.map(({findings:_,...w})=>w),priorBaseline.priorGas.register.worksheets.map(({findings:_,...w}:any)=>w)))
  const gasBytes:Record<string,unknown>={};for(const w of gas.worksheets){for(const v of w.versions){gasBytes['version_'+v.id]=await download('gas_export',`${root}/stationary-natural-gas/${w.worksheetId}/versions/${v.id}/calculation-export`,m73Export(v));if(v.statement)gasBytes['statement_'+v.statement.id]=await download('gas_statement',`${root}/stationary-natural-gas/${w.worksheetId}/statements/${v.statement.id}/download`,v.statement.text)}for(const r of w.reports)gasBytes['report_'+r.id]=await download('gas_report',`${root}/stationary-natural-gas/${w.worksheetId}/reports/${r.id}/download`,r.html)}check(same(gasBytes,priorBaseline.priorGas.downloads))
  return gasBytes};const gasBytes=await verifyGas()
  let cv=await corporate(),mr=await mobile();preserveVersions(prior.corporate,cv);preserveMobile(prior.register,mr)
  const cvBytes=await corporateDownloads(cv),mrBytes=await mobileDownloads(mr)
  if(input.mode==='baseline'){check(same(cv,prior.corporate)&&same(cvBytes,prior.exports)&&same(mr,prior.register)&&same(mrBytes,prior.downloads));await append('baseline',{legacy:legacy.baseline,corporate:cv,exports:cvBytes,mobile:mr,mobileDownloads:mrBytes,gasDownloads:gasBytes})}
  else if(input.mode==='revisit'){const fr=await fleet();check(same(cv,success!.data.corporate)&&same(cvBytes,success!.data.exports)&&same(mr,success!.data.mobile)&&same(mrBytes,success!.data.mobileDownloads)&&same(fr,success!.data.fleet)&&same(await fleetDownloads(fr),success!.data.fleetDownloads));await append('revisit_verified',{exerciseSha256:success!.sha256})}
  else{
   const original=baseline!.data.mobile,originalHead=baseline!.data.corporate.versions.at(-1),reviewer=input.accounts.find(a=>a.role==='manager2')!.id;check(original.worksheets.length===1&&original.worksheets[0].versions.length<=35&&originalHead.version<=35&&!originalHead.contributorIds.includes(reviewer))
   const aOld=original.worksheets[0].versions.at(-1) as M74Version;check(aOld.activity.vehicle.assetId==='M74-HOSTED-TRUCK-001'&&!aOld.contributorIds.includes(reviewer))
   let plan=events.find(e=>e.kind==='plan')?.data;if(!plan){plan={sourceB:crypto.randomUUID(),coverageB:crypto.randomUUID(),rowA:crypto.randomUUID(),rowB:crypto.randomUUID(),assetB:'M75-HOSTED-TRUCK-002'};await append('plan',plan)}
   const refs=[{artifactId:M71_ARTIFACT.id,expectedSha256:M71_EVIDENCE_SHA256,locator:M71_ARTIFACT.locator,purpose:'Synthetic whole-fleet operational-control and source-screening basis'}]
   const linked=await post('m71_fleet_sources',`${corporateRoot}/${originalHead.inventoryId}/versions`,'manager1',()=>{const snapshot=structuredClone(originalHead.snapshot),sourceA=snapshot.sources.find((s:any)=>s.id===aOld.activity.binding.sourceId);check(sourceA);snapshot.sources.push({...sourceA,id:plan.sourceB,name:'Synthetic second controlled diesel vehicle',evidenceRefs:refs});snapshot.coverageItems.push({...snapshot.coverageItems.find((x:any)=>x.sourceId===sourceA.id),id:plan.coverageB,sourceId:plan.sourceB});for(const c of snapshot.coverageItems.filter((x:any)=>x.sourceId===sourceA.id||x.sourceId===plan.sourceB)){Object.assign(c,{disposition:'included_activity',activityDataState:'entered',evidenceState:'linked',methodReadiness:'candidate',reason:'Synthetic separate consumed-fuel and all-trip mileage workpapers required for each registered controlled vehicle.',evidenceRefs:refs,quantity:null,unit:null,estimateBasis:null})}return {snapshot,expectedVersionId:originalHead.id,expectedVersionSha256:originalHead.versionSha256,correctionReason:'Reconcile two declared controlled vehicles, retaining unsupported family gaps and all earlier sources.',idempotencyKey:crypto.randomUUID()}})
   await post('m71_fleet_review',`${corporateRoot}/${linked.inventoryId}/reviews`,'manager2',()=>({versionId:linked.id,expectedVersionSha256:linked.versionSha256,decision:'accepted_bounded_internal',note:'Separate synthetic boundary/source review; broader corporate coverage remains incomplete.',acknowledgedLimitations:[...M71_LIMITATIONS],idempotencyKey:crypto.randomUUID()}))
   cv=await corporate();check(cv.headVersionId===linked.id);const choices=m74SourceChoices(cv.versions.at(-1)!),choiceA=choices.find(c=>c.binding.sourceId===aOld.activity.binding.sourceId),choiceB=choices.find(c=>c.binding.sourceId===plan.sourceB);check(choiceA?.eligible&&choiceB?.eligible)
   const a=await post('m74_a_relink',`${mobileRoot}/${aOld.worksheetId}/versions`,'manager1',()=>({...aOld.activity,binding:choiceA!.binding,mileageStatement:{...aOld.activity.mileageStatement!,reference:'M75-HOSTED-MILES-A-2025',statedDistanceMiles:aOld.activity.distanceMiles!,description:'Corrected synthetic annual statement covering the exact entered all-trip miles.'},mileageDiscrepancyReason:null,expectedVersionId:aOld.id,expectedVersionSha256:aOld.versionSha256,correctionReason:'Relink current corporate boundary and resolve the documented mileage discrepancy with a corrected synthetic statement.',idempotencyKey:crypto.randomUUID()})) as M74Version
   const reviewMobile=(name:string,v:M74Version)=>post(name,`${mobileRoot}/${v.worksheetId}/reviews`,'manager2',()=>({versionId:v.id,expectedVersionSha256:v.versionSha256,decision:'accepted_bounded_internal',note:'Separate review of exact synthetic fuel and mileage evidence; method remains unreleased.',acknowledgedLimitations:[...M74_LIMITATIONS],idempotencyKey:crypto.randomUUID()}))
   await reviewMobile('m74_a_review',a)
   const declaration={issuer:'Fictional controlled-fleet register custodian',reference:'M75-HOSTED-FLEET-2025',description:'Independent synthetic declaration of two controlled on-road vehicles, prepared from fictional ownership and operating records.',discoveryBasis:'Fictional asset, ownership/control and full-year operating records reviewed for every declared corporate entity; the declared roster is not inferred from saved vehicle workpapers.',coveredEntityIds:linked.snapshot.entities.map((e:any)=>e.id).sort(),completeness:'declared_complete' as const,allTripLocationsIncluded:true,assets:[{rowId:plan.rowA,assetId:'M74-HOSTED-TRUCK-001',aliases:[],entityId:a.activity.binding.entityId,facilityId:a.activity.binding.facilityId,period:{...M75_PERIOD},mode:'on_road' as const,vehicleClass:'Medium- and Heavy-Duty Vehicles',modelYear:2018,fuel:'Fossil Diesel',controlBasis:'owned_operational_control_full_year' as const,classificationBasis:'Fictional 2018 medium/heavy-duty registration.',controlExplanation:'Owned and operationally controlled for all of 2025.'},{rowId:plan.rowB,assetId:plan.assetB,aliases:[],entityId:choiceB!.binding.entityId,facilityId:choiceB!.binding.facilityId,period:{...M75_PERIOD},mode:'on_road' as const,vehicleClass:'Medium- and Heavy-Duty Vehicles',modelYear:2018,fuel:'Fossil Diesel',controlBasis:'owned_operational_control_full_year' as const,classificationBasis:'Fictional 2018 medium/heavy-duty registration.',controlExplanation:'Owned and operationally controlled for all of 2025.'}]}
   const saveFleet=(name:string,previous:M75Version|null,reason:string|null)=>post(name,previous?`${fleetRoot}/${previous.rosterId}/versions`:fleetRoot,'manager1',async()=>{const current=await fleet();return {profile:M75_PROFILE,coverageVersionId:linked.id,coverageVersionSha256:linked.versionSha256,expectedDependencySha256:current.reconciliation.dependencySha256,period:{...M75_PERIOD},rosterStatement:declaration,manualConfirmation:true,links:[{rowId:plan.rowA,sourceId:a.activity.binding.sourceId},{rowId:plan.rowB,sourceId:plan.sourceB}],expectedVersionId:previous?.id??null,expectedVersionSha256:previous?.versionSha256??null,correctionReason:reason,idempotencyKey:crypto.randomUUID()} satisfies M75SaveInput})
   const reviewFleet=(name:string,v:M75Version,decision:'accepted_bounded_reconciliation'|'changes_requested',role:Role='manager2',expected=201)=>post(name,`${fleetRoot}/${v.rosterId}/reviews`,role,async()=>({versionId:v.id,expectedVersionSha256:v.versionSha256,expectedDependencySha256:(await fleet()).reconciliation.dependencySha256,decision,note:decision==='changes_requested'?'The independently declared second vehicle needs its current workpaper.':'Exact declared synthetic roster reconciles to current accepted source workpapers; no aggregate, released method, complete Scope 1 or assurance.',acknowledgedLimitations:[...M75_LIMITATIONS],idempotencyKey:crypto.randomUUID()}),expected)
   const first=await saveFleet('m75_save_1',null,null) as M75Version
   if(!completed('m74_b_save'))check((await fleet()).reconciliation.rows.some(r=>r.status==='missing_workpaper'))
   await reviewFleet('m75_contributor_review_refused',first,'changes_requested','manager1',403)
   await reviewFleet('m75_member_review_refused',first,'changes_requested','member',403)
   await reviewFleet('m75_review_1',first,'changes_requested')
   const bInput={...a.activity,binding:choiceB!.binding,vehicle:{...a.activity.vehicle,assetId:plan.assetB},quantityGallons:'500.000',distanceMiles:'6000.000',fuelStatement:{...a.activity.fuelStatement!,reference:'M75-HOSTED-FUEL-B-2025',statedQuantityGallons:'500.000'},mileageStatement:{...a.activity.mileageStatement!,reference:'M75-HOSTED-MILES-B-2025',statedDistanceMiles:'6000.000'},fuelDiscrepancyReason:null,mileageDiscrepancyReason:null,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()}
   await post('m74_member_save_refused',mobileRoot,'member',()=>bInput,403);await post('m74_signed_out_save_refused',mobileRoot,'signed_out',()=>bInput,401)
   const b=await post('m74_b_save',mobileRoot,'manager1',()=>bInput) as M74Version;await reviewMobile('m74_b_review',b)
   const second=await saveFleet('m75_save_2',first,'Capture the newly completed second vehicle and exact accepted workpaper heads.') as M75Version;await reviewFleet('m75_review_2',second,'accepted_bounded_reconciliation')
   const report=(name:string,v:M75Version)=>post(name,`${fleetRoot}/${v.rosterId}/reports`,'manager1',async()=>({expectedReconciliationSha256:(await fleet()).reconciliation.contentSha256,idempotencyKey:crypto.randomUUID()}))
   await report('m75_report_1',second)
   const b2=await post('m74_b_correction',`${mobileRoot}/${b.worksheetId}/versions`,'manager1',()=>({...bInput,distanceMiles:'6100.000',mileageStatement:{...bInput.mileageStatement,reference:'M75-HOSTED-MILES-B-2025-CORRECTED',statedDistanceMiles:'6100.000'},expectedVersionId:b.id,expectedVersionSha256:b.versionSha256,correctionReason:'Correct the second vehicle mileage with matching synthetic evidence; a separate review is required again.',idempotencyKey:crypto.randomUUID()})) as M74Version
   if(!completed('m75_save_3'))check((await fleet()).reconciliation.status==='blocked')
   const third=await saveFleet('m75_save_3',second,'Capture the corrected second vehicle while its new workpaper review remains pending.') as M75Version;await report('m75_report_2',third)
   await reviewMobile('m74_b_corrected_review',b2)
   const fourth=await saveFleet('m75_save_4',third,'Capture the corrected vehicle approval; obtain a fresh exact fleet reconciliation review.') as M75Version;await reviewFleet('m75_review_4',fourth,'accepted_bounded_reconciliation');await report('m75_report_3',fourth)
   const finalFleet=await fleet();check(finalFleet.headVersionId===fourth.id&&finalFleet.versions.length===4&&finalFleet.reports.length===3&&finalFleet.reconciliation.status==='reconciled_bounded_synthetic'&&finalFleet.reconciliation.rows.length===2&&finalFleet.reconciliation.rows.every(r=>r.status==='matched_reviewed'))
   mr=await mobile();cv=await corporate();preserveMobile(original,mr);preserveVersions(baseline!.data.corporate,cv);check(mr.worksheets.length===2&&same(gasBytes,baseline!.data.gasDownloads))
   const finalDownloads=await fleetDownloads(finalFleet);check(same(await verifyGas(),gasBytes));await verifyLegacy();await append('exercise_complete',{corporate:cv,exports:await corporateDownloads(cv),mobile:mr,mobileDownloads:await mobileDownloads(mr),fleet:finalFleet,fleetDownloads:finalDownloads,gasDownloads:gasBytes})
  }
 }catch{failed=true}
 finally{for(const token of tokens.values()){try{const r=await network(AUTH+'/auth/v1/logout?scope=local',{method:'POST',headers:{apikey:input.env.SUPABASE_ANON_KEY,authorization:'Bearer '+token}});await r.body?.cancel();if(r.status!==204)closed=false}catch{closed=false}}tokens.clear()}
 const allCreatedAuthSessionsClosed=closed&&legacyClosed&&unknownSessions===0;failed||=!allCreatedAuthSessionsClosed
 if(loaded)try{await append('attempt_finished',{attemptSequence,status:failed?'failed':'passed',stage,applicationPostRequests:writes,allCreatedAuthSessionsClosed})}catch{failed=true;stage='receipt_append'}
 return {status:failed?'failed':'passed',mode:input.mode,stage,applicationPostRequests:writes,allCreatedAuthSessionsClosed,receiptSha256:events.at(-1)?.sha256??null}
}
if(import.meta.main){let lock:Awaited<ReturnType<typeof open>>|undefined;try{const text=await Bun.stdin.text();check(text.length<=128000);const input=parseM75JourneyInput(JSON.parse(text));lock=await open(RECEIPT+'.lock','wx');const result=await runM75Journey(input);console.log(JSON.stringify(result));if(result.status!=='passed')process.exitCode=1}catch{console.log(JSON.stringify({status:'failed',stage:'input_or_exclusive_lock'}));process.exitCode=1}finally{if(lock){await lock.close();await unlink(RECEIPT+'.lock')}}}
