import {test,expect} from 'bun:test'
import {parseM76JourneyInput,readM76Journal,runM76Journey,validateM76JourneyRoute} from './check-m76-hosted'
import {createM71Seed,validateM71Snapshot,deriveM71Findings,m71VersionHashPayload,m71Hash,m71Export,M71_PROFILE,M71_LIMITATIONS,M73_PROFILE,M73_LIMITATIONS,M74_PROFILE,M74_LIMITATIONS,M75_PROFILE,M75_LIMITATIONS,deriveM75Reconciliation,m74CanonicalJson,type M71Version} from '../../packages/neuvetra-database/src/index'
const HOST='https://www.neuvetra.ai',AUTH='https://icockcoguyadhryzydvl.supabase.co',company='75000000-0000-4000-8000-000000000001'
const input=(mode='baseline')=>({mode,env:{SUPABASE_URL:AUTH,SUPABASE_ANON_KEY:'sb_publishable_'+'a'.repeat(30)},roster:{workspaceId:company},accounts:['manager1','manager2','member','outsider'].map((role,i)=>({role,id:`75000000-0000-4000-8000-00000000001${i}`,email:role+'@synthetic.invalid',password:'fictional-local-only'}))})
const hash=(v:string)=>new Bun.CryptoHasher('sha256').update(v).digest('hex')
const line=(events:any[],kind:string,data:any,mode='exercise')=>{const payload={sequence:events.length+1,previousSha256:events.at(-1)?.sha256??null,workspaceId:company,mode,kind,data,createdAt:'2026-09-15T12:00:00.000Z'};return {...payload,sha256:hash(m74CanonicalJson(payload))}}
function fixture(){
 const snapshot=validateM71Snapshot(createM71Seed()),version={id:'75000000-0000-4000-8000-000000000020',inventoryId:'75000000-0000-4000-8000-000000000021',companyId:company,version:1,previousVersionId:null,previousVersionSha256:null,createdBy:input().accounts[0]!.id,createdAt:'2026-09-15T12:00:00.000Z',contributorIds:[input().accounts[0]!.id],correctionReason:null,snapshot,contentSha256:m71Hash(snapshot),versionSha256:'',findings:deriveM71Findings(snapshot),synthetic:true,corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none',emissionsTotals:null,review:null} as M71Version
 version.versionSha256=m71Hash(m71VersionHashPayload(version))
 const corporate={profile:M71_PROFILE,companyId:company,inventoryId:version.inventoryId,headVersionId:version.id,versions:[version],limitations:[...M71_LIMITATIONS]},text=m71Export(version),exports={[version.id]:{sha256:hash(text),byteLength:Buffer.byteLength(text)}},legacy={records:{prior:'a'.repeat(64)},downloads:{prior:{sha256:'b'.repeat(64),byteLength:12}}}
 const common={companyId:company,coverageHeadVersionId:version.id,worksheets:[],sources:[],coverageFindings:[],synthetic:true,scope1Completeness:'incomplete',corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none'},gas={...common,profile:M73_PROFILE,limitations:[...M73_LIMITATIONS]},mobile={...common,profile:M74_PROFILE,limitations:[...M74_LIMITATIONS]}
 const fleet={profile:M75_PROFILE,companyId:company,rosterId:null,headVersionId:null,versions:[],reviews:[],reports:[],proof:{coverageVersion:version,boundCoverageVersion:null,workpaperVersions:[]},reconciliation:deriveM75Reconciliation(company,version,[],null,[],m71Hash),limitations:[...M75_LIMITATIONS]}
 const previousEvents:any[]=[];for(const [kind,data]of [['baseline',{legacy}],['exercise_complete',{corporate,exports,mobile,mobileDownloads:{},fleet,fleetDownloads:{},gasDownloads:{}}],['revisit_verified',{}]])previousEvents.push(line(previousEvents,kind as string,data,'baseline'))
 return {corporate,text,exports,legacy,gas,mobile,fleet,previous:previousEvents.map(e=>JSON.stringify(e)).join('\n')+'\n'}
}
function harness(){const f=fixture();let journal:string|null=null,schema=18,logoutFailure=false;const calls:{url:string;method:string}[]=[]
 const dependencies={load:async()=>journal,append:async(text:string,exclusive:boolean)=>{expect(exclusive).toBe(journal===null);journal=(journal??'')+text},loadPrevious:async()=>f.previous,legacy:async(_input:any,deps:any)=>{const r=await deps.fetch(HOST+'/ready',{method:'GET'});expect((await r.json()).schemaVersion).toBe(14);await deps.save({baseline:f.legacy});return {status:'passed',allCreatedAuthSessionsClosed:true,applicationPostRequests:0}},fetch:async(url:any,init:any={})=>{const target=String(url),method=init.method??'GET';calls.push({url:target,method});const json=(v:any,status=200)=>Response.json(v,{status,headers:{'cache-control':'no-store'}});if(target===HOST+'/ready')return json({status:'ready',schemaVersion:schema});if(target.startsWith(AUTH+'/auth/v1/token')){const account=input().accounts.find(a=>a.email===JSON.parse(init.body).email)!;return json({access_token:'synthetic-token-'+account.role,user:{id:account.id}})}if(target.startsWith(AUTH+'/auth/v1/logout'))return new Response(null,{status:logoutFailure?500:204});if(target.endsWith('/corporate-inventories'))return json(f.corporate);if(target.endsWith('/coverage-export'))return new Response(f.text,{headers:{'cache-control':'no-store'}});if(target.endsWith('/stationary-natural-gas'))return json(f.gas);if(target.endsWith('/mobile-diesel'))return json(f.mobile);if(target.endsWith('/controlled-fleet'))return json(f.fleet);throw Error('Unexpected offline route')}}
 return {f,dependencies:dependencies as any,calls,append(kind:string,data:any){const es=readM76Journal(journal,company);journal=(journal??'')+JSON.stringify(line(es,kind,data))+'\n'},get journal(){return journal},set journal(v:string|null){journal=v},set schema(v:number){schema=v},set logoutFailure(v:boolean){logoutFailure=v}}
}

test('M76 route allowlist refuses unrelated writes, other tenants, redirects and auth admin',()=>{
 expect(parseM76JourneyInput(input()).mode).toBe('baseline')
 for(const mode of ['deploy','delete',''])expect(()=>parseM76JourneyInput(input(mode))).toThrow()
 for(const route of ['stationary-natural-gas','stationary-diesel','stationary-equipment',`corporate-inventories/${company}/reviews`,`stationary-equipment/${company}/reports`])validateM76JourneyRoute(`${HOST}/workspace-api/workspace/${company}/${route}`,'POST',company)
 for(const [url,method]of [[HOST+'/ready?x=1','GET'],[HOST+`/workspace-api/workspace/${company}/members`,'POST'],[HOST+`/workspace-api/workspace/${company}/controlled-fleet`,'POST'],[HOST+`/workspace-api/workspace/${company}/mobile-diesel`,'POST'],[HOST+`/workspace-api/workspace/${company}a/stationary-equipment`,'GET'],[AUTH+'/auth/v1/admin/users','POST'],['https://evil.invalid/ready','GET']])expect(()=>validateM76JourneyRoute(url!,method!,company)).toThrow()
})
test('baseline18 verifies existing M71/M73/M74/M75 decoders/downloads without app writes',async()=>{
 const h=harness(),r=await runM76Journey(parseM76JourneyInput(input()),h.dependencies)
 expect(r.status).toBe('passed');expect(r.applicationPostRequests).toBe(0);expect(r.allCreatedAuthSessionsClosed).toBe(true)
 expect(h.calls.filter(c=>c.url.startsWith(HOST)&&c.method==='POST')).toHaveLength(0)
 expect(h.calls.filter(c=>c.url.includes('/logout'))).toHaveLength(4)
 const b=readM76Journal(h.journal,company).find(e=>e.kind==='baseline')!
 expect(b.data.fleet).toEqual(h.f.fleet);expect(b.data.downloads.corporate).toEqual(h.f.exports)
 expect(h.journal).not.toContain('synthetic-token');expect(h.journal).not.toContain('fictional-local-only')
})
test('schema mismatch, changed earlier evidence and failed logout refuse success',async()=>{
 const bad=harness();bad.schema=19;expect((await runM76Journey(parseM76JourneyInput(input()),bad.dependencies)).status).toBe('failed')
 const changed=harness();changed.f.text+='\n';expect((await runM76Journey(parseM76JourneyInput(input()),changed.dependencies)).status).toBe('failed')
 const h=harness();h.logoutFailure=true;const r=await runM76Journey(parseM76JourneyInput(input()),h.dependencies)
 expect(r.status).toBe('failed');expect(r.allCreatedAuthSessionsClosed).toBe(false)
 const n=h.calls.length;expect((await runM76Journey(parseM76JourneyInput(input('exercise')),h.dependencies)).stage).toBe('resume_preconditions');expect(h.calls.length).toBe(n)
})
test('unresolved writes/attempts and partial/tampered journals stop before network',async()=>{
 for(const kind of ['post_intent','attempt_started']){
  const h=harness();await runM76Journey(parseM76JourneyInput(input()),h.dependencies);h.append(kind,{name:'uncertain',mode:'exercise'})
  const n=h.calls.length;expect((await runM76Journey(parseM76JourneyInput(input('exercise')),h.dependencies)).stage).toBe('resume_preconditions');expect(h.calls.length).toBe(n)
 }
 const h=harness();await runM76Journey(parseM76JourneyInput(input()),h.dependencies)
 expect(()=>readM76Journal(h.journal!.replace('baseline','exercise'),company)).toThrow()
 expect(()=>readM76Journal(h.journal,'75000000-0000-4000-8000-000000000002')).toThrow()
 expect(()=>readM76Journal(h.journal!.trimEnd(),company)).toThrow()
})

// Native local boundaries; identity and older legacy network are explicitly offline adapters.
const native=process.env.M76_HOSTED_NATIVE_SOURCE?test:test.skip
native('actual18 baseline then19 stationary recipe and zero-write revisit preserve history',async()=>{
 const lib=await import('../../packages/neuvetra-database/src/index'),{createM73Authority}=await import('../../apps/site-api/src/calculation/m73-authority'),{createM74Authority}=await import('../../apps/site-api/src/calculation/m74-authority'),{createM76DieselAuthority}=await import('../../apps/site-api/src/calculation/m76-authority'),{createCorporateInventoryRoutes}=await import('../../apps/site-api/src/workspace/m71-routes'),{createM73Routes}=await import('../../apps/site-api/src/workspace/m73-routes'),{createM74Routes}=await import('../../apps/site-api/src/workspace/m74-routes'),{createM75Routes}=await import('../../apps/site-api/src/workspace/m75-routes'),{createM76Routes}=await import('../../apps/site-api/src/workspace/m76-routes'),{applyExact19}=await import('./m76-apply'),ops=await import('./m76-common'),content=await import('./m76-recovery-manifest')
 const source=process.env.M76_HOSTED_NATIVE_SOURCE!;expect(/^m75_ops_forward18_[0-9]+$/.test(source)).toBe(true)
 const suffix=Date.now(),name='m76_ops_journey_'+suffix,receiptPath='.tmp/m76-hosted-native-'+suffix+'.jsonl',admin=lib.createPostgresConnection('postgres://m63_test_admin@127.0.0.1:55463/postgres',{tls:false,maxConnections:1});let operator:any,runtime:any,sourceRead=lib.createPostgresConnection(`postgres://m63_test_admin@127.0.0.1:55463/${source}`,{tls:false,maxConnections:1})
 try{
  const sourceInventory=await sourceRead.transaction((tx:any)=>ops.inventory(tx));await ops.canonicalReceipts(sourceRead,18);await sourceRead.close()
  expect((await admin.query('select 1 from pg_database where datname=$1',[name])).rows).toHaveLength(0);await admin.exec(`create database ${name} template ${source}`);operator=ops.connectLocal(name)
  await ops.canonicalReceipts(operator,18)
  const projectRef=(await operator.query('select project_ref from neuvetra.staging_target')).rows[0].project_ref,accounts=input().accounts.map(a=>({...a,id:crypto.randomUUID()})),companyId=crypto.randomUUID(),owner=accounts[0]!.id,reviewer=accounts[1]!.id
  for(const a of accounts)await operator.query('insert into auth.users(id) values($1)',[a.id])
  // Exact local synthetic provisioning before schema19; no cluster or existing-company change.
  await operator.query('insert into neuvetra.staging_access(user_id,active) values($1,true)',[owner])
  await operator.transaction(async(tx:any)=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[owner]);await tx.query("select neuvetra.create_company_workspace($1,'Synthetic M76 local journey',$2,'Synthetic California office',$3,2025,$4)",[companyId,crypto.randomUUID(),crypto.randomUUID(),crypto.randomUUID()])})
  for(const[a,role]of[[accounts[0],'owner'],[accounts[1],'admin'],[accounts[2],'member']] as const){await operator.query('insert into neuvetra.company_members(company_id,user_id,role) values($1,$2,$3) on conflict(company_id,user_id) do update set role=excluded.role',[companyId,a!.id,role]);await operator.query('insert into neuvetra.staging_access(user_id,company_id,active) values($1,$2,true) on conflict(user_id) do update set company_id=excluded.company_id,active=true',[a!.id,companyId])}
  runtime=lib.createPostgresConnection(`postgres://neuvetra_runtime@127.0.0.1:55463/${name}`,{tls:false,maxConnections:4});const database=new(lib.HostedWorkspaceDatabase as any)(runtime,projectRef),gasAuthority=createM73Authority(),mobileAuthority=createM74Authority(),authorities={gas:gasAuthority,diesel:createM76DieselAuthority()}
  const snapshot=lib.createM71Seed(),entity=snapshot.entities[0]!,facility=snapshot.facilities[0]!,gasId=crypto.randomUUID(),mobileId=crypto.randomUUID(),refs=[{artifactId:lib.M71_ARTIFACT.id,expectedSha256:lib.M71_EVIDENCE_SHA256,locator:lib.M71_ARTIFACT.locator,purpose:'Synthetic local control and source evidence'}]
  snapshot.companyLabel='Synthetic M76 local office and distribution journey';snapshot.boundaryDecisions[0]!.reason='Fictional full-year operational control.';snapshot.boundaryDecisions[0]!.evidenceRefs=refs
  for(const[id,domain,name]of[[gasId,'stationary_combustion','Synthetic prior dedicated gas boiler'],[mobileId,'mobile_combustion','Synthetic prior controlled truck']]){snapshot.sources.push({id,entityId:entity.id,facilityId:facility.id,name,domain,...lib.M73_PERIOD,evidenceRefs:refs});snapshot.coverageItems.push({id:crypto.randomUUID(),domain,entityId:entity.id,sourceId:id,...lib.M73_PERIOD,disposition:'included_activity',activityDataState:'entered',evidenceState:'linked',methodReadiness:'candidate',reason:'Synthetic dedicated source evidence retained separately.',evidenceRefs:refs,estimateBasis:null,quantity:null,unit:null})}
  const cv=await database.saveCorporateInventory(owner,companyId,null,{snapshot,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()})
  await database.reviewCorporateInventory(reviewer,companyId,cv.inventoryId,{versionId:cv.id,expectedVersionSha256:cv.versionSha256,decision:'accepted_bounded_internal',note:'Synthetic local separate boundary review.',acknowledgedLimitations:[...lib.M71_LIMITATIONS],idempotencyKey:crypto.randomUUID()})
  const gas=await database.saveStationaryGas(owner,companyId,null,{profile:lib.M73_PROFILE,binding:lib.m73SourceChoices(cv)[0]!.binding,period:{...lib.M73_PERIOD},fuel:'Natural Gas',heatBasis:'HHV',unit:'MMBtu',quantityMmbtu:'100.000',statement:{issuer:'Synthetic local gas custodian',reference:'LOCAL-PRIOR-GAS',meterLabel:'LOCAL-OFFICE-BOILER-METER',statedQuantityMmbtu:'100.000',description:'Fictional annual dedicated boiler consumed HHV MMBtu.',consumptionBasis:'dedicated_meter_consumed_no_adjustments'},manualConfirmation:true,discrepancyReason:null,zeroReason:null,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()},gasAuthority)
  await database.reviewStationaryGas(reviewer,companyId,gas.worksheetId,{versionId:gas.id,expectedVersionSha256:gas.versionSha256,decision:'accepted_bounded_internal',note:'Synthetic local separate gas review.',acknowledgedLimitations:[...lib.M73_LIMITATIONS],idempotencyKey:crypto.randomUUID()},gasAuthority)
  const vehicle=await database.saveMobileDiesel(owner,companyId,null,{profile:lib.M74_PROFILE,binding:lib.m74SourceChoices(cv)[0]!.binding,period:{...lib.M74_PERIOD},vehicle:{assetId:'M76-LOCAL-PRIOR-TRUCK',vehicleClass:'Medium- and Heavy-Duty Vehicles',classificationBasis:'Fictional2018 medium/heavy registration.',modelYear:2018,fuel:'Fossil Diesel',controlBasis:'owned_operational_control_full_year'},quantityGallons:'100.000',distanceMiles:'1000.000',fuelStatement:{issuer:'Synthetic local vehicle custodian',reference:'LOCAL-PRIOR-VEHICLE-FUEL',statedQuantityGallons:'100.000',description:'Fictional consumed annual vehicle fuel.',consumptionBasis:'dedicated_vehicle_consumed_no_adjustments'},mileageStatement:{issuer:'Synthetic local telematics',reference:'LOCAL-PRIOR-VEHICLE-MILES',statedDistanceMiles:'1000.000',description:'Fictional all-trip annual mileage.',distanceBasis:'dedicated_vehicle_annual_distance'},fuelManualConfirmation:true,mileageManualConfirmation:true,fuelDiscrepancyReason:null,mileageDiscrepancyReason:null,zeroReason:null,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()},mobileAuthority)
  await database.reviewMobileDiesel(reviewer,companyId,vehicle.worksheetId,{versionId:vehicle.id,expectedVersionSha256:vehicle.versionSha256,decision:'accepted_bounded_internal',note:'Synthetic local separate vehicle review.',acknowledgedLimitations:[...lib.M74_LIMITATIONS],idempotencyKey:crypto.randomUUID()},mobileAuthority)
  let fr=await database.findControlledFleet(owner,companyId,mobileAuthority);const rowId=crypto.randomUUID(),fleet=await database.saveControlledFleet(owner,companyId,null,{profile:lib.M75_PROFILE,coverageVersionId:cv.id,coverageVersionSha256:cv.versionSha256,expectedDependencySha256:fr.reconciliation.dependencySha256,period:{...lib.M75_PERIOD},rosterStatement:{issuer:'Synthetic local fleet custodian',reference:'LOCAL-PRIOR-FLEET',description:'Independent fictional prior fleet declaration.',discoveryBasis:'Fictional ownership/control and operating records across all declared entities before workpaper matching.',coveredEntityIds:snapshot.entities.map((e:any)=>e.id).sort(),completeness:'declared_complete',allTripLocationsIncluded:true,assets:[{rowId,assetId:vehicle.activity.vehicle.assetId,aliases:[],entityId:entity.id,facilityId:facility.id,period:{...lib.M75_PERIOD},mode:'on_road',vehicleClass:vehicle.activity.vehicle.vehicleClass,modelYear:2018,fuel:'Fossil Diesel',controlBasis:'owned_operational_control_full_year',classificationBasis:'Fictional2018 medium/heavy registration.',controlExplanation:'Fictional full-year operational control.'}]},manualConfirmation:true,links:[{rowId,sourceId:mobileId}],expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()},mobileAuthority)
  fr=await database.findControlledFleet(owner,companyId,mobileAuthority);await database.reviewControlledFleet(reviewer,companyId,fleet.rosterId,{versionId:fleet.id,expectedVersionSha256:fleet.versionSha256,expectedDependencySha256:fr.reconciliation.dependencySha256,decision:'accepted_bounded_reconciliation',note:'Synthetic local prior fleet reconciliation.',acknowledgedLimitations:[...lib.M75_LIMITATIONS],idempotencyKey:crypto.randomUUID()},mobileAuthority)
  fr=await database.findControlledFleet(owner,companyId,mobileAuthority);await database.createControlledFleetReport(owner,companyId,fleet.rosterId,{expectedReconciliationSha256:fr.reconciliation.contentSha256,idempotencyKey:crypto.randomUUID()},mobileAuthority)
  const corporate=await database.findCorporateInventory(owner,companyId),gr=await database.findStationaryGas(owner,companyId,gasAuthority),mr=await database.findMobileDiesel(owner,companyId,mobileAuthority);fr=await database.findControlledFleet(owner,companyId,mobileAuthority)
  const obs=(s:string)=>({sha256:hash(s),byteLength:Buffer.byteLength(s)}),exports=Object.fromEntries(corporate.versions.map((v:any)=>[v.id,obs(lib.m71Export(v))])),sourceDownloads=(reg:any,exporter:any,mobile=false)=>{const out:any={};for(const w of reg.worksheets){for(const v of w.versions){out['version_'+v.id]=obs(exporter(v));for(const[k,s]of mobile?[['fuel',v.fuelStatement],['mileage',v.mileageStatement]]:[['statement',v.statement]])if(s)out[k+'_'+s.id]=obs(s.text)}for(const r of w.reports)out['report_'+r.id]=obs(r.html)}return out},fleetDownloads:any={}
  for(const v of fr.versions){fleetDownloads['version_'+v.id]=obs(lib.m75Export(v));if(v.statement)fleetDownloads['statement_'+v.statement.id]=obs(v.statement.text)}for(const r of fr.reports){const report=await database.findControlledFleetReport(owner,companyId,fr.rosterId,r.id,mobileAuthority);fleetDownloads['report_'+r.id]=obs(report.html);fleetDownloads['snapshot_'+r.id]=obs(report.snapshotJson);fleetDownloads['proof_'+r.id]=hash(lib.m71CanonicalJson(await database.findControlledFleetReportProof(owner,companyId,fr.rosterId,r.id,mobileAuthority)))}
  const legacy={records:{synthetic:'a'.repeat(64)},downloads:{}},previous:any[]=[];for(const[kind,data]of[['baseline',{legacy}],['exercise_complete',{corporate,exports,mobile:mr,mobileDownloads:sourceDownloads(mr,lib.m74Export,true),fleet:fr,fleetDownloads,gasDownloads:sourceDownloads(gr,lib.m73Export)}],['revisit_verified',{}]]){const payload={sequence:previous.length+1,previousSha256:previous.at(-1)?.sha256??null,workspaceId:companyId,mode:'exercise',kind,data,createdAt:new Date().toISOString()};previous.push({...payload,sha256:hash(lib.m71CanonicalJson(payload))})}
  const validateUser=async(token:string)=>{const a=accounts.find(a=>token==='local-'+a.id);return a?{id:a.id} as any:null},routeDeps={database,validateUser,origin:HOST},routes={corporate:createCorporateInventoryRoutes(routeDeps),gas:createM73Routes({...routeDeps,authority:gasAuthority}),mobile:createM74Routes({...routeDeps,authority:mobileAuthority}),fleet:createM75Routes({...routeDeps,authority:mobileAuthority}),stationary:createM76Routes({...routeDeps,authorities})};let journal:string|null=null,applicationPosts=0,logouts=0
  const deps:any={load:async()=>journal,append:async(s:string)=>{const{open}=await import('node:fs/promises'),f=await open(receiptPath,journal===null?'wx':'a');try{await f.writeFile(s);await f.sync()}finally{await f.close()}journal=(journal??'')+s},loadPrevious:async()=>previous.map(e=>JSON.stringify(e)).join('\n')+'\n',legacy:async(_i:any,d:any)=>{await d.fetch(HOST+'/ready');await d.save({baseline:legacy});return {status:'passed',allCreatedAuthSessionsClosed:true,applicationPostRequests:0}},fetch:async(url:any,init:RequestInit={})=>{const target=String(url);if(target===HOST+'/ready')return Response.json({schemaVersion:Number((await operator.query('select count(*) n from neuvetra.schema_migrations')).rows[0].n)},{headers:{'cache-control':'no-store'}});if(target.startsWith(AUTH+'/auth/v1/token')){const a=accounts.find(a=>a.email===JSON.parse(init.body as string).email)!;return Response.json({access_token:'local-'+a.id,user:{id:a.id}})}if(target.startsWith(AUTH+'/auth/v1/logout')){logouts++;return new Response(null,{status:204})}if(init.method==='POST')applicationPosts++;const request=new Request(target.replace('/workspace-api/','/'),init);if(target.includes('/corporate-inventories'))return routes.corporate(request);if(target.includes('/stationary-natural-gas'))return routes.gas(request);if(target.includes('/mobile-diesel'))return routes.mobile(request);if(target.includes('/controlled-fleet'))return routes.fleet(request);if(target.includes('/stationary-diesel')||target.includes('/stationary-equipment'))return routes.stationary(request);throw Error('Unknown local route')}}
  const parsed=(mode:string)=>parseM76JourneyInput({...input(mode),accounts,roster:{workspaceId:companyId}})
  expect((await runM76Journey(parsed('baseline'),deps)).status).toBe('passed');expect(applicationPosts).toBe(0)
  const baselineInventory=await operator.transaction((tx:any)=>ops.inventory(tx)),baselineContent=await operator.transaction((tx:any)=>content.recoveryManifest(tx,18));await operator.transaction((tx:any)=>applyExact19(tx,baselineInventory,baselineContent));await ops.canonicalReceipts(operator,19)
  const result=await runM76Journey(parsed('exercise'),deps);console.log(JSON.stringify({status:'m76_local_helper_author',database:name,receipt:receiptPath,...result}));expect(result.status).toBe('passed');expect(applicationPosts).toBeGreaterThan(20)
  const before=applicationPosts,revisit=await runM76Journey(parsed('revisit'),deps);expect(revisit.status).toBe('passed');expect(applicationPosts).toBe(before);expect(logouts).toBe(12)
  const final=await database.findStationaryEquipment(owner,companyId,authorities);expect(final.versions).toHaveLength(4);expect(final.reports).toHaveLength(4);expect(final.reconciliation.status).toBe('reconciled_bounded_synthetic');expect(final.reconciliation.rows).toHaveLength(3)
  sourceRead=lib.createPostgresConnection(`postgres://m63_test_admin@127.0.0.1:55463/${source}`,{tls:false,maxConnections:1});expect(await sourceRead.transaction((tx:any)=>ops.inventory(tx))).toEqual(sourceInventory)
  await ops.exclusiveJson(receiptPath+'.result.json',{status:'m76_local_helper_author_passed',createdAt:new Date().toISOString(),database:name,sourceReadOnly:source,sourceUnchanged:true,migrationHash:ops.MIGRATION,journalPath:receiptPath,journalSha256:hash(journal!),exercise:result,revisit,applicationPostRequests:applicationPosts,revisitApplicationPostRequests:applicationPosts-before,closedOfflineIdentitySessions:logouts,equipmentVersions:final.versions.length,equipmentReports:final.reports.length,reconciliationStatus:final.reconciliation.status,matchedRows:final.reconciliation.rows.length,identityTransport:'offline_local_adapter',legacyTransport:'offline_local_adapter',realLocalApplicationRoutes:true,hostedEvidence:false,independentReview:false})
 }finally{await runtime?.close();await operator?.close();await sourceRead.close();await admin.close()}
},180000)
