import {test,expect} from 'bun:test'
import {parseM77JourneyInput,readM77Journal,cleanM77Journal,acceptedM76Continuation,runM77Journey,validateM77JourneyRoute,preservesM77History} from './check-m77-hosted'
import {M77_HOSTED_MIGRATION,M77_HOSTED_DEVICES,m77HostedReviewer,m77HostedFacilities} from './m77-hosted-plan'
import {m77CanonicalJson as canonical,m77Hash as hash} from '../../packages/neuvetra-database/src/index'
const HOST='https://www.neuvetra.ai',AUTH='https://icockcoguyadhryzydvl.supabase.co',company='77000000-0000-4000-8000-000000000001'
const input=(mode='baseline')=>({mode,acceptedM76:{journalSha256:'a'.repeat(64),headSha256:'b'.repeat(64)},env:{SUPABASE_URL:AUTH,SUPABASE_ANON_KEY:'sb_publishable_'+'a'.repeat(30)},roster:{workspaceId:company},accounts:['manager1','manager2','member','outsider'].map((role,i)=>({role,id:`77000000-0000-4000-8000-00000000001${i}`,email:role+'@synthetic.invalid',password:'fictional-local-only'}))})
const bytesHash=(v:string)=>new Bun.CryptoHasher('sha256').update(v).digest('hex')
function event(es:any[],kind:string,data:any,mode='exercise',previous=false){const body={sequence:es.length+1,previousSha256:es.at(-1)?.sha256??null,profile:previous?'m76-hosted-recovery-v1':'m77-hosted-journey-v1',...(previous?{companyId:company}:{workspaceId:company}),mode,kind,data,createdAt:'2026-09-16T12:00:00.000Z'};return {...body,sha256:hash(body)}}
function syntheticM76Predecessor(companyId:string,registers:any,downloads:any,legacy:any){const es:any[]=[];const add=(kind:string,data:any,mode:string)=>{const body={sequence:es.length+1,previousSha256:es.at(-1)?.sha256??null,profile:'m76-hosted-recovery-v1',planId:'77000000-0000-4000-8000-000000000099',companyId,mode,kind,data,createdAt:'2026-09-16T12:00:00.000Z'};es.push({...body,sha256:hash(body)})};add('continuation_provenance',{syntheticNativeAdapter:true},'baseline');for(const mode of ['baseline','exercise','revisit']){add('attempt_started',{mode},mode);const started=es.at(-1).sequence;if(mode==='exercise'){add('post_intent',{name:'synthetic_prior_operation',route:'/fictional-reference-only',role:'manager1',expected:201,request:{}},mode);add('post_outcome',{name:'synthetic_prior_operation',status:201,response:{synthetic:true},responseObservation:{sha256:'a'.repeat(64),byteLength:18}},mode);add('step_verified',{name:'synthetic_prior_operation',response:{synthetic:true}},mode)}add(mode==='baseline'?'failed_state_baseline':mode==='exercise'?'recovery_complete':'recovery_revisit',mode==='baseline'?{legacy}:mode==='exercise'?{registers,downloads}:{applicationPostRequests:0},mode);add('attempt_finished',{attemptSequence:started,status:'passed',applicationPostRequests:mode==='exercise'?1:0,allCreatedAuthSessionsClosed:true},mode)}return es}
test('fixed M77 input and transport refuse other hosts, tenants, family writes, admin, methods and redirects',()=>{
 expect(parseM77JourneyInput(input()).mode).toBe('baseline');expect(M77_HOSTED_DEVICES).toHaveLength(5);
 for(const bad of [{...input(),mode:'delete'},{...input(),acceptedM76:undefined},{...input(),accounts:input().accounts.slice(0,3)},{...input(),env:{...input().env,SUPABASE_URL:'https://evil.invalid'}}])expect(()=>parseM77JourneyInput(bad)).toThrow();
 for(const route of ['fugitive-sources','fugitive-population',`fugitive-sources/${company}/reviews`,`fugitive-population/${company}/reports`,`corporate-inventories/${company}/versions`])validateM77JourneyRoute(HOST+'/workspace-api/workspace/'+company+'/'+route,'POST',company);
 for(const[url,method]of [[HOST+'/ready?x=1','GET'],[HOST+'/ready','DELETE'],[HOST+'/workspace-api/workspace/'+company+'a/fugitive-sources','GET'],[HOST+'/workspace-api/workspace/'+company+'/members','POST'],[HOST+'/workspace-api/workspace/'+company+'/stationary-diesel','POST'],[HOST+'/workspace-api/workspace/'+company+'/mobile-diesel','POST'],[HOST+'/workspace-api/workspace/'+company+'/corporate-inventories/'+company+'/reports','POST'],[AUTH+'/auth/v1/admin/users','POST'],['https://evil.invalid/ready','GET'],[HOST+'/ready#fragment','GET']])expect(()=>validateM77JourneyRoute(url!,method!,company)).toThrow();
 const accounts=input().accounts;expect(m77HostedReviewer({contributorIds:[accounts[0]!.id]},accounts)).toBe('manager2');expect(m77HostedReviewer({contributorIds:[accounts[1]!.id]},accounts)).toBe('manager1');expect(()=>m77HostedReviewer({contributorIds:accounts.slice(0,2).map(a=>a.id)},accounts)).toThrow()
})
test('uncertain/failed/truncated/tampered journal stops before any network and does not retry',async()=>{
 for(const kind of ['attempt_started','post_intent']){const es:any[]=[];es.push(event(es,kind,{name:'uncertain',expected:201}));const text=es.map(e=>JSON.stringify(e)).join('\n')+'\n';expect(()=>cleanM77Journal(readM77Journal(text,company))).toThrow();let calls=0;const r=await runM77Journey(parseM77JourneyInput(input()),{load:async()=>text,fetch:(async()=>{calls++;throw Error('Unexpected network')}) as unknown as typeof fetch,loadPrevious:async()=>{throw Error('Unexpected predecessor read')}});expect(r.status).toBe('failed');expect(r.applicationPostRequests).toBe(0);expect(calls).toBe(0)}
 const es:any[]=[];es.push(event(es,'baseline',{}));const text=JSON.stringify(es[0])+'\n';expect(()=>readM77Journal(text.trimEnd(),company)).toThrow();expect(()=>readM77Journal(text.replace('baseline','exercise'),company)).toThrow();expect(()=>readM77Journal(text,crypto.randomUUID())).toThrow();
 const failed:any[]=[];failed.push(event(failed,'attempt_started',{}));failed.push(event(failed,'attempt_finished',{attemptSequence:1,status:'failed',allCreatedAuthSessionsClosed:true}));expect(()=>cleanM77Journal(failed)).toThrow();failed[1].data.status='passed';failed[1].data.allCreatedAuthSessionsClosed=false;expect(()=>cleanM77Journal(failed)).toThrow()
})
test('only completed reviewed M76 continuation and exact old cores are admitted',()=>{
 const es=syntheticM76Predecessor(company,{},{},{records:{},downloads:{}});const text=es.map(e=>JSON.stringify(e)).join('\n')+'\n';expect(acceptedM76Continuation(text,company).sha256).toBe(bytesHash(text));expect(()=>acceptedM76Continuation(text.replace('recovery_complete','exercise_complete'),company)).toThrow();const old={corporate:{versions:[{id:company,review:null,snapshot:{sources:[{id:'old'}]}}]}},sameOld=structuredClone(old);preservesM77History(old,sameOld);sameOld.corporate.versions[0]!.snapshot.sources=[];expect(()=>preservesM77History(old,sameOld)).toThrow()
})
test('predecessor pin mismatch is offline and a mismatched signed-in identity closes its known session then stops',async()=>{
 const legacy={records:{},downloads:{}},prior=syntheticM76Predecessor(company,{},{},legacy);const text=prior.map(e=>JSON.stringify(e)).join('\n')+'\n';let journal:string|null=null,calls=0,logouts=0;
 const deps:any={load:async()=>journal,loadPrevious:async()=>text,append:async(line:string)=>{journal=(journal??'')+line},legacy:async(_i:any,d:any)=>{await d.save({baseline:legacy});return {status:'passed',applicationPostRequests:0,allCreatedAuthSessionsClosed:true}},fetch:async(url:any,init:any)=>{calls++;expect(init.redirect).toBe('error');expect(init.signal).toBeInstanceOf(AbortSignal);if(String(url)===HOST+'/ready')return Response.json({schemaVersion:19});if(String(url).includes('/auth/v1/token'))return Response.json({access_token:'fictional-session-never-journaled',user:{id:crypto.randomUUID()}});if(String(url).includes('/auth/v1/logout')){logouts++;return new Response(null,{status:204})}throw Error('Unexpected offline route')}};
 expect((await runM77Journey(parseM77JourneyInput(input()),deps)).status).toBe('failed');expect(calls).toBe(0);expect(journal).toBe(null);
 const value={...input(),acceptedM76:{journalSha256:bytesHash(text),headSha256:prior.at(-1).sha256}},r=await runM77Journey(parseM77JourneyInput(value),deps);expect(r.status).toBe('failed');expect(r.applicationPostRequests).toBe(0);expect(r.allCreatedAuthSessionsClosed).toBe(true);expect(logouts).toBe(1);expect(journal).not.toContain('fictional-session-never-journaled');const n=calls;expect((await runM77Journey(parseM77JourneyInput(value),deps)).status).toBe('failed');expect(calls).toBe(n);
 const orphan:any[]=[event([],'post_outcome',{name:'orphan',status:201})];expect(()=>cleanM77Journal(orphan)).toThrow();const duplicate:any[]=[];duplicate.push(event(duplicate,'post_intent',{name:'same',expected:201}));duplicate.push(event(duplicate,'post_intent',{name:'same',expected:201}));expect(()=>cleanM77Journal(duplicate)).toThrow()
})
test('F05 clean terminal closure rejects orphan finishes, reversed outcomes and cross-attempt closure despite valid hashes',()=>{
 const previous=syntheticM76Predecessor(company,{},{},{records:{},downloads:{}});const orphanBody=event(previous,'attempt_finished',{attemptSequence:999,status:'failed',applicationPostRequests:0,allCreatedAuthSessionsClosed:true},'revisit',true);const orphanText=[...previous,orphanBody].map(e=>JSON.stringify(e)).join('\n')+'\n';expect(()=>acceptedM76Continuation(orphanText,company)).toThrow();
 const current:any[]=[];current.push(event(current,'attempt_started',{mode:'exercise'}));current.push(event(current,'attempt_finished',{attemptSequence:1,status:'passed',applicationPostRequests:0,allCreatedAuthSessionsClosed:true}));current.push(event(current,'attempt_finished',{attemptSequence:999,status:'failed',applicationPostRequests:0,allCreatedAuthSessionsClosed:true}));expect(()=>cleanM77Journal(readM77Journal(current.map(e=>JSON.stringify(e)).join('\n')+'\n',company))).toThrow();
 const reversed:any[]=[];reversed.push(event(reversed,'attempt_started',{mode:'exercise'}));reversed.push(event(reversed,'post_outcome',{name:'reversed',route:'/fake',role:'manager1',expected:201,status:201,response:{}}));reversed.push(event(reversed,'post_intent',{name:'reversed',route:'/fake',role:'manager1',expected:201}));reversed.push(event(reversed,'attempt_finished',{attemptSequence:1,status:'passed',applicationPostRequests:1,allCreatedAuthSessionsClosed:true}));expect(()=>cleanM77Journal(readM77Journal(reversed.map(e=>JSON.stringify(e)).join('\n')+'\n',company))).toThrow();
 const finishBeforeStart:any[]=[];finishBeforeStart.push(event(finishBeforeStart,'attempt_finished',{attemptSequence:2,status:'passed',applicationPostRequests:0,allCreatedAuthSessionsClosed:true}));finishBeforeStart.push(event(finishBeforeStart,'attempt_started',{mode:'exercise'}));expect(()=>cleanM77Journal(finishBeforeStart)).toThrow();
 const outside:any[]=[];outside.push(event(outside,'post_intent',{name:'outside',route:'/fake',role:'manager1',expected:201}));expect(()=>cleanM77Journal(outside)).toThrow()
 const unverified:any[]=[];unverified.push(event(unverified,'attempt_started',{mode:'baseline'},'baseline'));unverified.push(event(unverified,'attempt_finished',{attemptSequence:1,status:'passed',applicationPostRequests:0,allCreatedAuthSessionsClosed:true},'baseline'));expect(()=>cleanM77Journal(readM77Journal(unverified.map(e=>JSON.stringify(e)).join('\n')+'\n',company))).toThrow()
})
const native=process.env.NEUVETRA_M77_HOSTED_NATIVE==='1'?test:test.skip;
test('source-bound facility resolver preserves three locations and refuses ambiguous or stale provenance',()=>{
 const facility=(id:string,entityId:string,name:string)=>({id,entityId,name,countryCode:'US',regionCode:'CA',start:'2025-01-01',endExclusive:'2026-01-01'}),facilities=[facility('office','parent','Office'),facility('original','subsidiary','Distribution'),facility('generator-site','parent','Distribution')],sources=[['boiler','office'],['heater','generator-site'],['generator','generator-site'],['truck','office']].map(([id,facilityId])=>({id,facilityId,entityId:'parent'})),assets=[['M76-HOSTED-BOILER-001','boiler','office'],['M76-HOSTED-HEATER-001','heater','generator-site'],['M76-HOSTED-GENERATOR-001','generator','generator-site']].map(([equipmentId,rowId,facilityId])=>({equipmentId,rowId,facilityId,entityId:'parent'}));
 const version=(sourceId:string)=>({activity:{binding:{sourceId,facilityId:sources.find(s=>s.id===sourceId)!.facilityId,entityId:'parent',coverageVersionId:'coverage',coverageVersionSha256:'sha'}}}),baseline:any={corporate:{versions:[{id:'coverage',versionSha256:'sha',snapshot:{facilities,sources}}]},equipment:{versions:[{activity:{rosterStatement:{assets},links:assets.map(a=>({rowId:a.rowId,sourceId:a.rowId}))}}]},gas:{worksheets:['boiler','heater'].map(s=>({versions:[version(s)]}))},diesel:{worksheets:[{versions:[version('generator')]}]},fleet:{versions:[{activity:{rosterStatement:{assets:[{assetId:'M74-HOSTED-TRUCK-001',rowId:'truck',facilityId:'office',entityId:'parent'}]},links:[{rowId:'truck',sourceId:'truck'}]}}]}};
 const resolved=m77HostedFacilities(baseline);expect(resolved.office.id).toBe('office');expect(resolved.distribution.id).toBe('generator-site');expect(resolved.facilities).toHaveLength(3);expect(resolved.facilities).toEqual(facilities);
 for(const mutate of [(b:any)=>b.equipment.versions[0].activity.rosterStatement.assets.push({...assets[2]}),(b:any)=>b.diesel.worksheets[0].versions[0].activity.binding.facilityId='original',(b:any)=>b.gas.worksheets[0].versions[0].activity.binding.coverageVersionId='stale',(b:any)=>b.fleet.versions[0].activity.rosterStatement.assets[0].facilityId='original']){const bad=structuredClone(baseline);mutate(bad);expect(()=>m77HostedFacilities(bad)).toThrow()}
});
native('real local schema19 baseline, five-device schema20 journey and reopened zero-write revisit',async()=>{
 const lib=await import('../../packages/neuvetra-database/src/index'),{createM73Authority}=await import('../../apps/site-api/src/calculation/m73-authority'),{createM74Authority}=await import('../../apps/site-api/src/calculation/m74-authority'),{createM76DieselAuthority}=await import('../../apps/site-api/src/calculation/m76-authority'),{createM77Authority}=await import('../../apps/site-api/src/calculation/m77-authority'),{createCorporateInventoryRoutes}=await import('../../apps/site-api/src/workspace/m71-routes'),{createM73Routes}=await import('../../apps/site-api/src/workspace/m73-routes'),{createM74Routes}=await import('../../apps/site-api/src/workspace/m74-routes'),{createM75Routes}=await import('../../apps/site-api/src/workspace/m75-routes'),{createM76Routes}=await import('../../apps/site-api/src/workspace/m76-routes'),{createM77Routes}=await import('../../apps/site-api/src/workspace/m77-routes');
 const name='m77_author_facilities_'+Date.now(),admin=lib.createPostgresConnection('postgres://supabase_admin@127.0.0.1:55472/postgres',{tls:false,maxConnections:1});let op:any,runtime:any;const accounts=input().accounts.map(a=>({...a,id:crypto.randomUUID()})),companyIdSeed=crypto.randomUUID();let companyId=companyIdSeed;let journal:string|null=null,appPosts=0,logouts=0;const journalPath='.superpowers/'+name+'-journey.jsonl';
 try{
  expect((await admin.query('select 1 from pg_database where datname=$1',[name])).rows).toHaveLength(0);await admin.exec(`create database ${name} template m77_ops_hosted19_candidate1`);op=lib.createPostgresConnection(`postgres://supabase_admin@127.0.0.1:55472/${name}`,{tls:false,maxConnections:1});const manifest=await lib.readMigrationManifest(),receipts=(await op.query('select name,sha256 from neuvetra.schema_migrations order by name')).rows;expect(receipts).toHaveLength(19);expect(receipts.every((r:any,i:number)=>r.name===manifest[i]!.name&&r.sha256===manifest[i]!.sha256)).toBe(true);expect(manifest[19]!.sha256).toBe(M77_HOSTED_MIGRATION);
  const oldTables=(await op.query("select table_name from information_schema.tables where table_schema='neuvetra'and table_type='BASE TABLE'and table_name<>'schema_migrations'order by table_name")).rows.map((r:any)=>r.table_name);const oldDigest=async()=>{const out:any={};for(const t of oldTables){expect(/^[a-z0-9_]+$/.test(t)).toBe(true);out[t]=(await op.query(`select encode(sha256(convert_to(coalesce(jsonb_agg(to_jsonb(x) order by to_jsonb(x)::text)::text,'[]'),'utf8')),'hex') sha256,coalesce(jsonb_agg(encode(sha256(convert_to(to_jsonb(x)::text,'utf8')),'hex') order by to_jsonb(x)::text),'[]') rows,coalesce(jsonb_agg(jsonb_build_object('sha256',encode(sha256(convert_to(to_jsonb(x)::text,'utf8')),'hex'),'companyId',to_jsonb(x)->>'company_id')),'[]') keys from neuvetra.${t} x`)).rows[0]}return out};const templateBefore=await oldDigest();
  const retainedCompany=(await op.query('select c.id,c.created_by from neuvetra.companies c join neuvetra.stationary_equipment_heads h on h.company_id=c.id order by c.id limit 1')).rows[0];expect(retainedCompany).toBeDefined();companyId=retainedCompany.id;accounts[0]!.id=retainedCompany.created_by;const retainedMember=(await op.query("select user_id from neuvetra.company_members where company_id=$1 and role='member'order by user_id limit 1",[companyId])).rows[0];expect(retainedMember).toBeDefined();accounts[2]!.id=retainedMember.user_id;for(const a of accounts)await op.query('insert into auth.users(id)values($1)on conflict(id)do nothing',[a.id]);const projectRef=(await op.query('select project_ref from neuvetra.staging_target')).rows[0].project_ref;await op.query("insert into neuvetra.company_members(company_id,user_id,role)values($1,$2,'admin')",[companyId,accounts[1]!.id]);await op.query('insert into neuvetra.staging_access(user_id,company_id,active)values($1,$2,true)',[accounts[1]!.id,companyId]);runtime=lib.createPostgresConnection(`postgres://neuvetra_runtime@127.0.0.1:55472/${name}`,{tls:false,maxConnections:5});let db=new(lib.HostedWorkspaceDatabase as any)(runtime,projectRef);
  const gas=createM73Authority(),mobile=createM74Authority(),diesel=createM76DieselAuthority(),fugitive=createM77Authority(),authorities={gas,diesel};const readBaseline=async()=>({corporate:await db.findCorporateInventory(accounts[0]!.id,companyId),gas:await db.findStationaryGas(accounts[0]!.id,companyId,gas),mobile:await db.findMobileDiesel(accounts[0]!.id,companyId,mobile),fleet:await db.findControlledFleet(accounts[0]!.id,companyId,mobile),diesel:await db.findStationaryDiesel(accounts[0]!.id,companyId,diesel),equipment:await db.findStationaryEquipment(accounts[0]!.id,companyId,authorities)}),before=await readBaseline();const observe=(text:string)=>({sha256:bytesHash(text),byteLength:Buffer.byteLength(text)}),priorDownloads:any={corporate:{},gas:{},mobile:{},fleet:{},diesel:{},equipment:{}},legacy={records:{synthetic:'a'.repeat(64)},downloads:{}};for(const v of before.corporate.versions)priorDownloads.corporate[v.id]=observe(lib.m71Export(v));for(const [f,exporter]of[['gas',lib.m73Export],['mobile',lib.m74Export],['diesel',(v:any)=>canonical({...v,review:null})]] as const)for(const w of (before as any)[f].worksheets){for(const v of w.versions){priorDownloads[f]['version_'+v.id]=observe(exporter(v));for(const[k,statement]of f==='mobile'?[['fuel',v.fuelStatement],['mileage',v.mileageStatement]]:[['statement',v.statement]])if(statement)priorDownloads[f][k+'_'+statement.id]=observe(statement.text)}for(const r of w.reports){priorDownloads[f]['report_'+r.id]=observe(r.html);if(f==='diesel')priorDownloads[f]['snapshot_'+r.id]=observe(r.snapshotJson)}}for(const [f,exporter]of[['fleet',lib.m75Export],['equipment',lib.m76Export]] as const){for(const v of (before as any)[f].versions){priorDownloads[f]['version_'+v.id]=observe(exporter(v));if(v.statement)priorDownloads[f]['statement_'+v.statement.id]=observe(v.statement.text)}for(const r of (before as any)[f].reports){const full=f==='fleet'?await db.findControlledFleetReport(accounts[0]!.id,companyId,r.rosterId,r.id,mobile):await db.findStationaryEquipmentReport(accounts[0]!.id,companyId,r.rosterId,r.id,authorities),proof=f==='fleet'?await db.findControlledFleetReportProof(accounts[0]!.id,companyId,r.rosterId,r.id,mobile):await db.findStationaryEquipmentReportProof(accounts[0]!.id,companyId,r.rosterId,r.id,authorities);priorDownloads[f]['report_'+r.id]=observe(full.html);priorDownloads[f]['snapshot_'+r.id]=observe(full.snapshotJson);priorDownloads[f]['proof_'+r.id]=hash(proof)}}expect(before.gas.worksheets.length).toBeGreaterThan(0);expect(before.diesel.worksheets.length).toBeGreaterThan(0);expect(before.equipment.reports.length).toBeGreaterThan(0);const retainedSnapshot=before.corporate.versions.at(-1).snapshot,facilityProof=m77HostedFacilities(before);expect(retainedSnapshot.facilities).toHaveLength(3);expect(facilityProof.distribution.id).toBe('98d69117-f3c9-43a7-bee0-c9e9940ac721');expect(facilityProof.office.id).toBe('71000000-0000-4000-8000-000000000020');
  const previous=syntheticM76Predecessor(companyId,before,priorDownloads,legacy);const priorText=previous.map(e=>JSON.stringify(e)).join('\n')+'\n';
  const routeSet=()=>{const validateUser=async(token:string)=>{const a=accounts.find(a=>token==='native-'+a.id);return a?{id:a.id} as any:null},common={database:db,origin:HOST,validateUser};return {corporate:createCorporateInventoryRoutes(common),gas:createM73Routes({...common,authority:gas}),mobile:createM74Routes({...common,authority:mobile}),fleet:createM75Routes({...common,authority:mobile}),stationary:createM76Routes({...common,authorities}),fugitive:createM77Routes({...common,authority:fugitive})}};let routes=routeSet();
  const deps:any={load:async()=>journal,append:async(line:string,exclusive:boolean)=>{expect(exclusive).toBe(journal===null);const {open}=await import('node:fs/promises'),f=await open(journalPath,exclusive?'wx':'a',0o600);try{await f.writeFile(line);await f.sync()}finally{await f.close()}journal=(journal??'')+line},loadPrevious:async()=>priorText,legacy:async(_i:any,d:any)=>{expect((await d.fetch(HOST+'/ready')).status).toBe(200);await d.save({baseline:legacy});return {status:'passed',applicationPostRequests:0,allCreatedAuthSessionsClosed:true}},fetch:async(url:any,init:RequestInit={})=>{const target=String(url);if(target===HOST+'/ready')return Response.json({schemaVersion:Number((await op.query('select count(*) n from neuvetra.schema_migrations')).rows[0].n)},{headers:{'cache-control':'no-store'}});if(target.startsWith(AUTH+'/auth/v1/token')){const a=accounts.find(a=>a.email===JSON.parse(init.body as string).email)!;return Response.json({access_token:'native-'+a.id,user:{id:a.id}})}if(target.startsWith(AUTH+'/auth/v1/logout')){logouts++;return new Response(null,{status:204})}if(init.method==='POST')appPosts++;const req=new Request(target.replace('/workspace-api/','/'),init);if(target.includes('/corporate-inventories'))return routes.corporate(req);if(target.includes('/stationary-natural-gas'))return routes.gas(req);if(target.includes('/mobile-diesel'))return routes.mobile(req);if(target.includes('/controlled-fleet'))return routes.fleet(req);if(target.includes('/stationary-diesel')||target.includes('/stationary-equipment'))return routes.stationary(req);if(target.includes('/fugitive-'))return routes.fugitive(req);throw Error('Unknown explicit local route')}};
  const parsed=(mode:string)=>parseM77JourneyInput({...input(mode),accounts,roster:{workspaceId:companyId},acceptedM76:{journalSha256:bytesHash(priorText),headSha256:previous.at(-1).sha256}});
  const baseline=await runM77Journey(parsed('baseline'),deps);expect(baseline.status).toBe('passed');expect(appPosts).toBe(0);const before20=await oldDigest();await op.transaction(async(tx:any)=>{await tx.exec(manifest[19]!.sql);await tx.query('insert into neuvetra.schema_migrations(name,sha256)values($1,$2)',[manifest[19]!.name,manifest[19]!.sha256])});expect(await oldDigest()).toEqual(before20);
  const exercise=await runM77Journey(parsed('exercise'),deps);console.log(JSON.stringify({database:name,...exercise}));expect(exercise.status).toBe('passed');expect(exercise.applicationPostRequests).toBeGreaterThan(30);const written=appPosts;await runtime.close();runtime=lib.createPostgresConnection(`postgres://neuvetra_runtime@127.0.0.1:55472/${name}`,{tls:false,maxConnections:5});db=new(lib.HostedWorkspaceDatabase as any)(runtime,projectRef);routes=routeSet();journal=await Bun.file(journalPath).text();const revisit=await runM77Journey(parsed('revisit'),deps);expect(revisit.status).toBe('passed');expect(revisit.applicationPostRequests).toBe(0);expect(appPosts).toBe(written);expect(logouts).toBe(12);expect(journal).not.toContain('native-');expect(journal).not.toContain('fictional-local-only');const final=await db.findFugitive(accounts[0]!.id,companyId,fugitive);expect(final.worksheets).toHaveLength(5);expect(final.population.versions).toHaveLength(4);expect(final.reconciliation.status).toBe('reconciled_bounded_synthetic');const finalCoverage=(await db.findCorporateInventory(accounts[0]!.id,companyId)).versions.at(-1);expect(finalCoverage.snapshot.facilities).toEqual(retainedSnapshot.facilities);for(const source of retainedSnapshot.sources)expect(finalCoverage.snapshot.sources.find((s:any)=>s.id===source.id)).toEqual(source);const discovery=final.population.versions.at(-1).activity.declaration;expect(discovery.coveredFacilityIds).toEqual(retainedSnapshot.facilities.map((f:any)=>f.id).sort());expect(discovery.coveredEntityIds).toEqual(retainedSnapshot.entities.map((e:any)=>e.id).sort());for(const f of retainedSnapshot.facilities)expect(discovery.discoveryBasis).toContain('retained facility '+f.id);expect(discovery.discoveryBasis).toContain('affirmative fictional inspection finding');expect(discovery.assets.filter((a:any)=>a.facilityId==='71000000-0000-4000-8000-000000000021')).toHaveLength(0);const events=readM77Journal(journal,companyId);cleanM77Journal(events);const reports=events.find(e=>e.kind==='exercise_complete')!.data.registers.fugitive;expect(reports.population.reports).toHaveLength(4);expect(reports.worksheets.flatMap((w:any)=>w.reports)).toHaveLength(5);
  // Every original row remains exact while this isolated clone appends corporate successors.
  const templateAfter=await oldDigest();for(const t of oldTables){const remaining=[...templateAfter[t].rows];for(const sha of templateBefore[t].rows){if(t==='corporate_inventory_heads'&&templateBefore[t].keys.some((k:any)=>k.sha256===sha&&k.companyId===companyId))continue;const at=remaining.indexOf(sha);expect(at).toBeGreaterThanOrEqual(0);remaining.splice(at,1)}};
  await Bun.write(journalPath+'.result.json',JSON.stringify({status:'author_native_m77_hosted_journey_pass',database:name,sourceRestore:'m77_ops_hosted19_candidate1',sourcePort:55472,retainedFacilityIds:retainedSnapshot.facilities.map((f:any)=>f.id),selectedOfficeId:facilityProof.office.id,selectedDistributionId:facilityProof.distribution.id,allRetainedLocationsExplicitlyInspected:true,companyId,journalSha256:bytesHash(journal!),migrationSha256:M77_HOSTED_MIGRATION,baseline,exercise,revisit,applicationPostRequests:appPosts,revisitApplicationPostRequests:0,syntheticAuthAndLegacyAdapters:true,realApplicationRoutes:true,realSchema19To20:true,actualHostedEvidence:false,independentReview:'pending'},null,2));
 }finally{await runtime?.close();await op?.close();await admin.close()}
},240000)
