import {test,expect} from 'bun:test'
import {parseM74JourneyInput,readM74Journal,runM74Journey,validateM74JourneyRoute} from './check-m74-hosted'
import {createM71Seed,validateM71Snapshot,deriveM71Findings,m71VersionHashPayload,m71Hash,m71Export,M71_PROFILE,M71_LIMITATIONS,M73_PROFILE,M73_LIMITATIONS,m74CanonicalJson,type M71Version} from '../../packages/neuvetra-database/src/index'
const HOST='https://www.neuvetra.ai',AUTH='https://icockcoguyadhryzydvl.supabase.co',company='74000000-0000-4000-8000-000000000001'
const input=(mode='baseline')=>({mode,env:{SUPABASE_URL:AUTH,SUPABASE_ANON_KEY:'sb_publishable_'+'a'.repeat(30)},roster:{workspaceId:company},accounts:['manager1','manager2','member','outsider'].map((role,i)=>({role,id:`74000000-0000-4000-8000-00000000001${i}`,email:role+'@synthetic.invalid',password:'fictional-local-only'}))})
const hash=(value:string)=>new Bun.CryptoHasher('sha256').update(value).digest('hex')
function fixture(){
 const snapshot=validateM71Snapshot(createM71Seed()),version={id:'74000000-0000-4000-8000-000000000020',inventoryId:'74000000-0000-4000-8000-000000000021',companyId:company,version:1,previousVersionId:null,previousVersionSha256:null,createdBy:input().accounts[0]!.id,createdAt:'2026-09-15T12:00:00.000Z',contributorIds:[input().accounts[0]!.id],correctionReason:null,snapshot,contentSha256:m71Hash(snapshot),versionSha256:'',findings:deriveM71Findings(snapshot),synthetic:true,corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none',emissionsTotals:null,review:null} as M71Version
 version.versionSha256=m71Hash(m71VersionHashPayload(version))
 const corporate={profile:M71_PROFILE,companyId:company,inventoryId:version.inventoryId,headVersionId:version.id,versions:[version],limitations:[...M71_LIMITATIONS]},text=m71Export(version),exports={[version.id]:{sha256:hash(text),byteLength:new TextEncoder().encode(text).length}},legacy={records:{prior:'a'.repeat(64)},downloads:{prior:{sha256:'b'.repeat(64),byteLength:12}}}
 const gas={profile:M73_PROFILE,companyId:company,coverageHeadVersionId:version.id,worksheets:[],sources:[],coverageFindings:[],limitations:[...M73_LIMITATIONS],synthetic:true,scope1Completeness:'incomplete',corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none'}
 let previousSha256:string|null=null
 const previous=[{kind:'baseline',data:{legacy}},{kind:'exercise_complete',data:{corporate,exports,register:gas,downloads:{}}},{kind:'revisit_verified',data:{}}].map((value,i)=>{const body={sequence:i+1,previousSha256,workspaceId:company,mode:i?'revisit':'baseline',...value,createdAt:'2026-09-15T12:00:00.000Z'},sha256=hash(m74CanonicalJson(body));previousSha256=sha256;return JSON.stringify({...body,sha256})}).join('\n')+'\n'
 return {corporate,text,exports,legacy,gas,previous}
}
function harness(){const f=fixture();let journal:string|null=null,schema=16,logoutFailure=false,postResponse:Response|undefined;const calls:{url:string;method:string}[]=[]
 const dependencies={load:async()=>journal,append:async(line:string,exclusive:boolean)=>{expect(exclusive).toBe(journal===null);journal=(journal??'')+line},loadPrevious:async()=>f.previous,legacy:async(_input:any,deps:any)=>{const r=await deps.fetch(HOST+'/ready',{method:'GET'});expect((await r.json()).schemaVersion).toBe(14);await deps.save({baseline:f.legacy});return {status:'passed',allCreatedAuthSessionsClosed:true,applicationPostRequests:0}},fetch:async(url:any,init:any={})=>{const target=String(url),method=init.method??'GET';calls.push({url:target,method});const json=(v:any,status=200)=>Response.json(v,{status,headers:{'cache-control':'no-store'}});if(target===HOST+'/ready')return json({status:'ready',profile:'neuvetra.private-synthetic-staging.v1',legacyContainmentVerified:true,schemaVersion:schema});if(target.startsWith(AUTH+'/auth/v1/token')){const account=input().accounts.find(a=>a.email===JSON.parse(init.body).email)!;return json({access_token:'synthetic-token-'+account.role,user:{id:account.id}})}if(target.startsWith(AUTH+'/auth/v1/logout'))return new Response(null,{status:logoutFailure?500:204});if(method==='POST'&&postResponse)return postResponse;if(target.endsWith('/corporate-inventories'))return json(f.corporate);if(target.endsWith('/coverage-export'))return new Response(f.text,{headers:{'cache-control':'no-store'}});if(target.endsWith('/stationary-natural-gas'))return json(f.gas);throw Error('Unexpected offline route')}}
 return {f,dependencies:dependencies as any,calls,get journal(){return journal},set journal(v:string|null){journal=v},set schema(v:number){schema=v},set logoutFailure(v:boolean){logoutFailure=v},set postResponse(v:Response){postResponse=v}}
}
test('M74 fixed destination and modes reject unrelated changes',()=>{expect(parseM74JourneyInput(input()).mode).toBe('baseline');for(const mode of ['deploy','delete',''])expect(()=>parseM74JourneyInput(input(mode))).toThrow();validateM74JourneyRoute(`${HOST}/workspace-api/workspace/${company}/mobile-diesel`,'POST',company);for(const [url,method]of [[HOST+'/ready?x=1','GET'],[HOST+`/workspace-api/workspace/${company}/members`,'POST'],[HOST+`/workspace-api/workspace/${company}/stationary-natural-gas`,'POST'],[AUTH+'/auth/v1/admin/users','POST'],['https://evil.invalid/ready','GET']])expect(()=>validateM74JourneyRoute(url!,method!,company)).toThrow()})
test('M74 read-only16 baseline binds existing gas and corporate exports and closes all sessions',async()=>{const h=harness(),result=await runM74Journey(parseM74JourneyInput(input()),h.dependencies);expect(result.status).toBe('passed');expect(result.applicationPostRequests).toBe(0);expect(result.allCreatedAuthSessionsClosed).toBe(true);expect(h.calls.filter(c=>c.url.startsWith(HOST)&&c.method==='POST')).toHaveLength(0);expect(h.calls.filter(c=>c.url.includes('/logout'))).toHaveLength(4);const baseline=readM74Journal(h.journal,company).find(e=>e.kind==='baseline')!;expect(baseline.data.priorGas.register).toEqual(h.f.gas);expect(baseline.data.exports).toEqual(h.f.exports);expect(h.journal).not.toContain('synthetic-token');expect(h.journal).not.toContain('fictional-local-only')})
test('unknown prior schema fails before application writes',async()=>{const h=harness();h.schema=17;expect((await runM74Journey(parseM74JourneyInput(input()),h.dependencies)).status).toBe('failed');expect(h.calls.filter(c=>c.url.startsWith(HOST)&&c.method==='POST')).toHaveLength(0)})
test('changed retained gas and failed logout refuse acceptance',async()=>{const changed=harness();changed.f.gas.limitations=[];expect((await runM74Journey(parseM74JourneyInput(input()),changed.dependencies)).status).toBe('failed');const h=harness();h.logoutFailure=true;const result=await runM74Journey(parseM74JourneyInput(input()),h.dependencies);expect(result.status).toBe('failed');expect(result.allCreatedAuthSessionsClosed).toBe(false);const before=h.calls.length;expect((await runM74Journey(parseM74JourneyInput(input('exercise')),h.dependencies)).stage).toBe('resume_preconditions');expect(h.calls.length).toBe(before)})
test('unexpected POST body is not journaled and uncertain success cannot be retried',async()=>{for(const status of [201,403]){const h=harness();expect((await runM74Journey(parseM74JourneyInput(input()),h.dependencies)).status).toBe('passed');h.schema=17;h.postResponse=new Response('PRIVATE_UNEXPECTED_BODY',{status,headers:{'cache-control':'no-store'}});expect((await runM74Journey(parseM74JourneyInput(input('exercise')),h.dependencies)).status).toBe('failed');expect(h.journal).not.toContain('PRIVATE_UNEXPECTED_BODY');const priorCalls=h.calls.length;expect((await runM74Journey(parseM74JourneyInput(input('exercise')),h.dependencies)).stage).toBe('resume_preconditions');expect(h.calls.length).toBe(priorCalls)}})
test('journal edits and wrong workspace are refused',async()=>{const h=harness();await runM74Journey(parseM74JourneyInput(input()),h.dependencies);expect(()=>readM74Journal(h.journal!.replace('baseline','exercise'),company)).toThrow();expect(()=>readM74Journal(h.journal,'74000000-0000-4000-8000-000000000002')).toThrow();expect(()=>readM74Journal(h.journal!.trimEnd(),company)).toThrow()})
