/** Exclusive graph-first continuation4 recovery. Imports are inert and never open credentials or a network. */
import {decodeScope1Register,decodeScope1Report} from '../../apps/site-web/src/lib/m78-api';
import {decodeCorporateRegister} from '../../apps/site-web/src/lib/m71-api';
import {decodeGasRegister} from '../../apps/site-web/src/lib/m73-api';
import {decodeMobileRegister} from '../../apps/site-web/src/lib/m74-api';
import {decodeFleetRegister} from '../../apps/site-web/src/lib/m75-api';
import {decodeGeneratorRegister} from '../../apps/site-web/src/lib/m76-diesel-api';
import {decodeStationaryRegister} from '../../apps/site-web/src/lib/m76-api';
import {decodeFugitiveRegister} from '../../apps/site-web/src/lib/m77-api';
import {m71Export} from '../../packages/neuvetra-database/src/m71';
import {m73Export} from '../../packages/neuvetra-database/src/m73-validation';
import {m74Export} from '../../packages/neuvetra-database/src/m74-validation';
import {m75Export} from '../../packages/neuvetra-database/src/m75-validation';
import {m76Export} from '../../packages/neuvetra-database/src/m76-validation';
import {m76DieselExport} from '../../packages/neuvetra-database/src/m76-diesel-validation';
import {m77Export} from '../../packages/neuvetra-database/src/m77-validation';
import {m78CanonicalJson as canonical,parseM78Json} from '../../packages/neuvetra-database/src/m78-validation';
import {readM78ContinuationJournal,m78VerifiedIdentity} from './check-m78-continuation';
import {verifyExerciseFailure} from '../../evaluations/research-qa/m78-continuation4-exercise-failure-qa-check';

export const M78_READONLY_RECOVERY_PATHS={
 journal:'.superpowers/m78-continuation4-readonly-recovery.jsonl',
 diagnostics:'.superpowers/m78-continuation4-readonly-recovery-diagnostics.jsonl',
 observation:'.superpowers/m78-continuation4-readonly-recovery-observation.json',
}as const;
export const M78_READONLY_RECOVERY_LOCK=M78_READONLY_RECOVERY_PATHS.journal+'.lock';
export const M78_READONLY_RECOVERY_LIMITS={responseBytes:10_000_000,retainedResponseBytes:128_000_000,journalBytes:16_000_000,timeoutMs:30_000}as const;
export const M78_READONLY_RECOVERY_HOST='https://www.neuvetra.ai';
export const M78_READONLY_RECOVERY_AUTH='https://icockcoguyadhryzydvl.supabase.co';
export type RecoveryRole='manager1'|'manager2'|'member'|'outsider';
type Pin={path:string;sha256:string};
type FailureInputs={mainText:string;diagnosticText:string;baselineResultText:string;exerciseGateText:string;providerObservationText:string;browserObservationText:string;failureReviewText:string};
export type RecoveryAdmission=FailureInputs&{currentSourceGateText:string;currentSourcePins:Pin[];load:(path:string)=>Promise<string|Uint8Array>};
export type RecoveryIO={read:(path:string)=>Promise<string|null>;append:(path:string,text:string,exclusive:boolean)=>Promise<void>};
export type RecoverySession={role:RecoveryRole;subject:string;authorization:string;status:200};
export type RecoveryAuth={open:(role:RecoveryRole,request:(url:string,init:RequestInit)=>Promise<Response>)=>Promise<RecoverySession>;close:(session:RecoverySession,request:(url:string,init:RequestInit)=>Promise<Response>)=>Promise<number>};
export type RecoveryDecoders={scope1:typeof decodeScope1Register;corporate:typeof decodeCorporateRegister;gas:typeof decodeGasRegister;mobile:typeof decodeMobileRegister;fleet:typeof decodeFleetRegister;diesel:typeof decodeGeneratorRegister;equipment:typeof decodeStationaryRegister;fugitive:typeof decodeFugitiveRegister;scope1Report:typeof decodeScope1Report};
const productionDecoders:RecoveryDecoders={scope1:decodeScope1Register,corporate:decodeCorporateRegister,gas:decodeGasRegister,mobile:decodeMobileRegister,fleet:decodeFleetRegister,diesel:decodeGeneratorRegister,equipment:decodeStationaryRegister,fugitive:decodeFugitiveRegister,scope1Report:decodeScope1Report};
const sha=(value:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(value).digest('hex');
const check:(value:unknown,message:string)=>asserts value=(value,message)=>{if(!value)throw Error(message)};
const same=(a:unknown,b:unknown)=>canonical(a)===canonical(b);
const validPin=(pin:Pin)=>pin&&pin.path.length>0&&/^[a-f0-9]{64}$/.test(pin.sha256);

export async function verifyM78ReadonlyRecoveryPreAuth(input:RecoveryAdmission){
 const reconciled=await verifyExerciseFailure(input);
 check(sha(input.failureReviewText)==='a97a84ca66ed696a348c8c8a5ecaf65e36ca4eb311803b6f2ecccebf9d16c573','failure review bytes');
 const review=JSON.parse(input.failureReviewText),historicalGate=JSON.parse(input.exerciseGateText),currentGate=JSON.parse(input.currentSourceGateText);
 check(review.status==='m78_continuation4_exercise_failure_independently_reconciled'&&review.exerciseAccepted===false&&review.applicationPostRequests===37,'closed failure review');
 check(Array.isArray(historicalGate.sourcePins)&&historicalGate.sourcePins.length===173&&historicalGate.sourcePins.every(validPin),'historical 173 source pins');
 check(currentGate.status==='m78_continuation4_readonly_recovery_source_admitted'&&currentGate.historicalExerciseGateSha256==='9fe233c964b8c40f6c7a9871eecf75a318e7a800f2ec14570c6803288ff9dce7','fresh recovery source gate');
 check(input.currentSourcePins.length>=173&&input.currentSourcePins.every(validPin)&&new Set(input.currentSourcePins.map(pin=>pin.path)).size===input.currentSourcePins.length,'fresh source pins');
 check(same(currentGate.sourcePins,input.currentSourcePins)&&currentGate.sourcePinsSha256===sha(canonical(input.currentSourcePins)),'fresh source gate pins');
 check(currentGate.runtime&&/^[a-f0-9]{40}$/.test(currentGate.runtime.commit)&&typeof currentGate.runtime.deploymentId==='string'&&currentGate.runtime.deploymentId.length>0,'fresh runtime binding');
 check(input.currentSourcePins.some(pin=>pin.path==='tools/staging/check-m78-continuation4-readonly-recovery.ts'),'recovery source inventoried');
 for(const pin of input.currentSourcePins)check(sha(await input.load(pin.path))===pin.sha256,'fresh source changed '+pin.path);
 return{reconciled,historicalSourcePins:historicalGate.sourcePins,currentSourceGate:currentGate};
}

function graphObjects(value:unknown,result:any[]=[]){if(!value||typeof value!=='object')return result;if(Array.isArray(value)){for(const item of value)graphObjects(item,result);return result}const object=value as Record<string,unknown>;result.push(object);for(const item of Object.values(object))graphObjects(item,result);return result}
function verifiedRecipe(mainText:string){const company=JSON.parse(mainText.split('\n')[0]!).workspaceId,events=readM78ContinuationJournal(mainText,company),triples=events.filter(event=>event.mode==='exercise'&&['post_intent','post_outcome','post_verified'].includes(event.kind));check(triples.length===111,'exact37 recipe');return{company,events,operations:Array.from({length:37},(_,index)=>({intent:triples[index*3]!,outcome:triples[index*3+1]!,verified:triples[index*3+2]!}))}}
function encoded(value:string){return{sha256:sha(value),byteLength:Buffer.byteLength(value)}}
export function reconstructM78ReadonlyRecoveryArtifacts(scope1:any,registers:any,fullReports:Record<string,any>){
 const downloads:Record<string,Record<string,unknown>>={},put=(family:string,key:string,value:unknown)=>((downloads[family]??={})[key]=value);
 for(const version of registers.corporate.versions)put('corporate',version.id,encoded(m71Export(version)));
 for(const [family,exporter]of [['gas',m73Export],['mobile',m74Export],['diesel',m76DieselExport]]as const)for(const worksheet of registers[family].worksheets){for(const version of worksheet.versions){put(family,'version_'+version.id,encoded(exporter(version as never)));for(const statement of family==='mobile'?[version.fuelStatement,version.mileageStatement]:[version.statement])if(statement)put(family,'statement_'+statement.id,encoded(statement.text))}for(const report of worksheet.reports){put(family,'report_'+report.id,encoded(report.html));if(family==='diesel')put(family,'snapshot_'+report.id,encoded(report.snapshotJson))}}
 for(const [family,exporter]of [['fleet',m75Export],['equipment',m76Export]]as const){for(const version of registers[family].versions){put(family,'version_'+version.id,encoded(exporter(version as never)));if(version.statement)put(family,'statement_'+version.statement.id,encoded(version.statement.text))}for(const report of registers[family].reports){put(family,'report_'+report.id,encoded(report.html));put(family,'snapshot_'+report.id,encoded(report.snapshotJson));put(family,'proof_'+report.id,sha(canonical((parseM78Json(report.snapshotJson)as any).proof)))}}
 for(const worksheet of [...registers.fugitive.worksheets,registers.fugitive.population]){for(const version of worksheet.versions){put('fugitive','version_'+version.id,encoded(m77Export(version)));for(const statement of version.statements)put('fugitive','statement_'+statement.id,encoded(statement.text))}for(const report of worksheet.reports){put('fugitive','report_'+report.id,encoded(report.html));put('fugitive','snapshot_'+report.id,encoded(report.snapshotJson))}}
 const m78bytes:Record<string,{sha256:string;byteLength:number}>={};for(const stream of [scope1.process,scope1.inventory]){for(const version of stream.versions){m78bytes['version_'+version.id]=encoded(canonical({...version,review:null}));for(const statement of version.statements)m78bytes['statement_'+statement.id]=encoded(statement.text)}for(const meta of stream.reports){const report=fullReports[meta.id];check(report,'full retained report '+meta.id);m78bytes['html_'+meta.id]=encoded(report.html);m78bytes['snapshot_'+meta.id]=encoded(report.snapshotJson)}}
 return{downloads,m78bytes};
}

export async function runM78Continuation4ReadonlyRecovery(input:{admission:RecoveryAdmission;io:RecoveryIO;fetch:typeof fetch;auth:RecoveryAuth;expectedSubjects:Record<RecoveryRole,string>;readLegacy:(request:(url:string,init:RequestInit)=>Promise<Response>,expected:unknown)=>Promise<{value:unknown;applicationPostRequests:0;allCreatedAuthSessionsClosed:true}>;decoders?:RecoveryDecoders;now?:()=>string}){
 const now=input.now??(()=>new Date().toISOString()),decoders=input.decoders??productionDecoders;
 for(const path of Object.values(M78_READONLY_RECOVERY_PATHS))check(await input.io.read(path)===null,'exclusive recovery path exists');
 const admission=await verifyM78ReadonlyRecoveryPreAuth(input.admission),recipe=verifiedRecipe(input.admission.mainText),company=recipe.company,root=`/workspace-api/workspace/${company}`;
 const events:any[]=[],diagnostics:any[]=[];let journalBytes=0,retainedResponseBytes=0,applicationPosts=0,requests=0,unknownSessions=0,legacyClosed=false,mainClosed=false,diagnosticsHealthy=true,diagnosticFailure:unknown=null,stage='preauth';
 const emit=async(kind:string,data:any)=>{const body={sequence:events.length+1,previousSha256:events.at(-1)?.sha256??null,profile:'m78-continuation4-readonly-recovery-v1',workspaceId:company,kind,data,createdAt:now()},event={...body,sha256:sha(canonical(body))},line=JSON.stringify(event)+'\n';journalBytes+=Buffer.byteLength(line);check(journalBytes<=M78_READONLY_RECOVERY_LIMITS.journalBytes,'recovery journal bound');await input.io.append(M78_READONLY_RECOVERY_PATHS.journal,line,events.length===0);events.push(event)};
 const diagnostic=async(kind:string,data:any)=>{const body={sequence:diagnostics.length+1,previousSha256:diagnostics.at(-1)?.sha256??null,profile:'m78-continuation4-readonly-recovery-diagnostic-v1',kind,data,createdAt:now()},event={...body,sha256:sha(canonical(body))};await input.io.append(M78_READONLY_RECOVERY_PATHS.diagnostics,JSON.stringify(event)+'\n',diagnostics.length===0);diagnostics.push(event)};
 const recordDiagnostic=async(kind:string,data:any)=>{try{await diagnostic(kind,data);return true}catch(error){diagnosticsHealthy=false;diagnosticFailure??=error;return false}};
 const request=async(url:string,init:RequestInit={})=>{const parsed=new URL(url),method=(init.method??'GET').toUpperCase(),auth=parsed.origin===M78_READONLY_RECOVERY_AUTH,app=parsed.origin===M78_READONLY_RECOVERY_HOST,localLogout=auth&&parsed.pathname==='/auth/v1/logout'&&parsed.searchParams.size===1&&parsed.searchParams.get('scope')==='local';check(app||auth,'fixed transport host');if(app)check(method==='GET'&&init.body===undefined,'application GET only');if(auth){check(method==='POST'&&['/auth/v1/token','/auth/v1/logout'].includes(parsed.pathname),'fixed auth POST only');if(parsed.pathname==='/auth/v1/logout')check(localLogout,'local logout only')}if(app&&method==='POST')applicationPosts++;if(!diagnosticsHealthy&&!localLogout)throw diagnosticFailure??Error('diagnostics unhealthy');const ordinal=requests+1,safeRoute=(auth?'auth:':'application:')+parsed.pathname.replaceAll(company,':id').replace(/[0-9a-f]{8}-[0-9a-f-]{27}/gi,':id'),intentRecorded=await recordDiagnostic('request_intent',{ordinal,method,route:safeRoute,...(localLogout?{logoutScope:'local'}:{})});if(!intentRecorded&&!localLogout)throw diagnosticFailure??Error('diagnostics unhealthy');requests=ordinal;try{const response=await input.fetch(url,{...init,keepalive:false,redirect:'error',signal:AbortSignal.timeout(M78_READONLY_RECOVERY_LIMITS.timeoutMs)});await recordDiagnostic('response_headers',{ordinal,status:response.status});return response}catch(error){await recordDiagnostic('request_error',{ordinal,category:error instanceof DOMException&&error.name==='TimeoutError'?'timeout':'transport'});throw error}};
 const sessions=new Map<RecoveryRole,RecoverySession>();
 const responseBytes=async(response:Response)=>{check(response.body,'response body');const reader=response.body.getReader(),chunks:Uint8Array[]=[];let length=0;try{while(true){const{done,value}=await reader.read();if(done)break;length+=value.byteLength;check(length<=M78_READONLY_RECOVERY_LIMITS.responseBytes,'response byte bound');chunks.push(value.slice())}}catch(error){await reader.cancel(error).catch(()=>undefined);throw error}finally{reader.releaseLock()}const bytes=new Uint8Array(length);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}return bytes};
 const get=async(route:string,role:RecoveryRole|'signed_out'='manager1',expected=200)=>{stage='read:'+route;const session=role==='signed_out'?undefined:sessions.get(role);const response=await request(M78_READONLY_RECOVERY_HOST+route,{headers:{origin:M78_READONLY_RECOVERY_HOST,...(session?{authorization:session.authorization}:{})}}),bytes=await responseBytes(response);retainedResponseBytes+=bytes.byteLength;check(retainedResponseBytes<=M78_READONLY_RECOVERY_LIMITS.retainedResponseBytes,'retained response byte bound');check(response.status===expected,'GET status '+route);if(expected!==200)return null;check(response.headers.get('cache-control')?.includes('no-store'),'no-store GET '+route);return parseM78Json(new TextDecoder('utf-8',{fatal:true}).decode(bytes),M78_READONLY_RECOVERY_LIMITS.responseBytes)};
 let observation:any=null,failure:unknown=null;
 await emit('attempt_started',{failedMainSha256:'44e7bec2d2e6a4a554de6ba23775150bfdf29582fd69ff12bc6cfbc73770ba8b',failedDiagnosticsSha256:'d77a8f58ec92a0642a5b0b4a91113920ccd4013b9bcfee9a9c7e5de90d93e651',historicalSourcePins:admission.historicalSourcePins.length,currentSourceGateSha256:sha(input.admission.currentSourceGateText),transport:{runtime:'bun-fetch',pooling:'disabled',keepalive:false,retries:0,timeoutMs:30000},applicationMethods:['GET']});
 try{
  stage='auth';for(const role of ['manager1','manager2','member','outsider']as RecoveryRole[]){await emit('auth_intent',{role});let opened:RecoverySession|undefined;try{opened=await input.auth.open(role,request);sessions.set(role,opened);check(opened.role===role&&opened.status===200&&opened.subject===input.expectedSubjects[role]&&opened.authorization.length>0,'auth session '+role);await emit('auth_outcome',{role,status:200,subjectMatched:true,sessionCreationUncertain:false})}catch(error){if(!opened)unknownSessions++;await emit('auth_outcome',{role,status:opened?.status??null,subjectMatched:false,sessionCreationUncertain:!opened});throw error}}
  await get(root+'/scope1-inventory','outsider',403);await get(root+'/scope1-inventory','signed_out',401);
  const managerScope1=await decoders.scope1(await get(root+'/scope1-inventory','manager1'),company),memberScope1=await decoders.scope1(await get(root+'/scope1-inventory','member'),company);check(same(managerScope1,memberScope1),'manager/member graph equality');
  const registers:any={};for(const [family,base,decode]of [['corporate','corporate-inventories',decoders.corporate],['gas','stationary-natural-gas',decoders.gas],['mobile','mobile-diesel',decoders.mobile],['fleet','controlled-fleet',decoders.fleet],['diesel','stationary-diesel',decoders.diesel],['equipment','stationary-equipment',decoders.equipment],['fugitive','fugitive-sources',decoders.fugitive]]as const)registers[family]=await decode(await get(root+'/'+base,'manager1'),company);
  const graph=graphObjects({scope1:managerScope1,registers}),fullReports:Record<string,any>={},fetched=new Set<string>();for(const operation of recipe.operations){const identity=operation.verified.data.verifiedIdentity as Record<string,string>;check(graph.some(record=>Object.entries(identity).every(([key,value])=>record[key]===value)),'verified identity in fresh graph '+operation.intent.data.name);if(identity.reportSha256){const route=operation.intent.data.route+'/'+identity.id;check(!fetched.has(route),'one full retained record read');fetched.add(route);const report=await decoders.scope1Report(await get(route,'manager1'),company);check(same(m78VerifiedIdentity(report),identity),'full report identity');fullReports[identity.id]=report}}
  check(Object.keys(fullReports).length===5,'five full retained reports');const artifacts=reconstructM78ReadonlyRecoveryArtifacts(managerScope1,registers,fullReports),baselineEvent=recipe.events.find(event=>event.kind==='baseline')!;const legacy=await input.readLegacy(request,baselineEvent.data.legacy);check(legacy.applicationPostRequests===0&&legacy.allCreatedAuthSessionsClosed&&same(legacy.value,baselineEvent.data.legacy),'unchanged legacy');legacyClosed=true;
  observation={status:'m78_continuation4_readonly_recovery_observed',profile:'m78-continuation4-readonly-recovery-observation-v1',workspaceId:company,failedMainSha256:'44e7bec2d2e6a4a554de6ba23775150bfdf29582fd69ff12bc6cfbc73770ba8b',failedDiagnosticsSha256:'d77a8f58ec92a0642a5b0b4a91113920ccd4013b9bcfee9a9c7e5de90d93e651',historicalSourcePins:admission.historicalSourcePins,currentSourcePins:input.admission.currentSourcePins,currentSourceGateSha256:sha(input.admission.currentSourceGateText),scope1:managerScope1,registers,...artifacts,fullReports,legacy:legacy.value,applicationPostRequests:0,retainedResponseBytes,retainedResponseByteLimit:M78_READONLY_RECOVERY_LIMITS.retainedResponseBytes,reportFullRecordReads:fetched.size,extraArtifactEndpointReads:0,observedAt:now()};
 }catch(error){failure=error}finally{
  stage='logout';let closed=0;for(const role of ['manager1','manager2','member','outsider']as RecoveryRole[]){const session=sessions.get(role);if(!session)continue;try{await emit('logout_intent',{role})}catch(error){failure??=error}try{const status=await input.auth.close(session,request);try{await emit('logout_outcome',{role,status})}catch(error){failure??=error}if(status===204)closed++}catch(error){try{await emit('logout_outcome',{role,status:null})}catch(logError){failure??=logError}failure??=error}}mainClosed=closed===sessions.size&&sessions.size===4;
 }failure??=diagnosticFailure;
 let passed=!failure&&observation&&mainClosed&&legacyClosed&&applicationPosts===0&&unknownSessions===0;
 if(passed){const text=JSON.stringify(observation,null,2)+'\n',diagnosticCommitted=await recordDiagnostic('phase_finished',{status:'passed',requests,applicationPostRequests:0,allCreatedAuthSessionsClosed:true,unknownAuthSessions:0,diagnosticsHealthy:true});if(!diagnosticCommitted){failure??=diagnosticFailure;passed=false}else{await emit('recovery_observed',{observationSha256:sha(text),applicationPostRequests:0,allMainSessionsClosed:true,allLegacySessionsClosed:true});await emit('attempt_finished',{status:'passed',stage,requests,applicationPostRequests:0,allCreatedAuthSessionsClosed:true,unknownAuthSessions:0,diagnosticsHealthy:true});await input.io.append(M78_READONLY_RECOVERY_PATHS.observation,text,true);return{status:'passed',observation,requests,applicationPostRequests:0,allCreatedAuthSessionsClosed:true,unknownAuthSessions:0,error:null}}}
 await emit('attempt_finished',{status:'failed',stage,requests,applicationPostRequests:applicationPosts,allCreatedAuthSessionsClosed:mainClosed&&legacyClosed,unknownAuthSessions:unknownSessions,diagnosticsHealthy});await recordDiagnostic('phase_finished',{status:'failed',requests,applicationPostRequests:applicationPosts,allCreatedAuthSessionsClosed:mainClosed&&legacyClosed,unknownAuthSessions:unknownSessions,diagnosticsHealthy});
 return{status:'failed',observation,requests,applicationPostRequests:applicationPosts,allCreatedAuthSessionsClosed:mainClosed&&legacyClosed,unknownAuthSessions:unknownSessions,error:failure instanceof Error?failure.message:null};
}
