import {expect,test} from 'bun:test';
import {readFile} from 'node:fs/promises';
import {decodeScope1Register} from '../../apps/site-web/src/lib/m78-api';
import {decodeCorporateRegister} from '../../apps/site-web/src/lib/m71-api';
import {decodeGasRegister} from '../../apps/site-web/src/lib/m73-api';
import {decodeMobileRegister} from '../../apps/site-web/src/lib/m74-api';
import {decodeFleetRegister} from '../../apps/site-web/src/lib/m75-api';
import {decodeGeneratorRegister} from '../../apps/site-web/src/lib/m76-diesel-api';
import {decodeStationaryRegister} from '../../apps/site-web/src/lib/m76-api';
import {decodeFugitiveRegister} from '../../apps/site-web/src/lib/m77-api';
import {M78_READONLY_RECOVERY_AUTH,M78_READONLY_RECOVERY_HOST,M78_READONLY_RECOVERY_PATHS,runM78Continuation4ReadonlyRecovery,verifyM78ReadonlyRecoveryPreAuth,type RecoveryAdmission,type RecoveryAuth,type RecoveryIO} from './check-m78-continuation4-readonly-recovery';
import {m78CanonicalJson as canonical} from '../../packages/neuvetra-database/src/m78-validation';
const sha=(value:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(value).digest('hex');

async function evidence(){
 const files={mainText:'.superpowers/m78-hosted-continuation4.jsonl',diagnosticText:'.superpowers/m78-hosted-continuation4-diagnostics.jsonl',baselineResultText:'evaluations/research-qa/m78-continuation4-baseline-independent-result.json',exerciseGateText:'.superpowers/m78-continuation4-exercise-gate.json',providerObservationText:'evaluations/research-qa/m78-continuation4-failure-http-observation.json',browserObservationText:'evaluations/research-qa/m78-continuation4-browser-http-observation.json',failureReviewText:'evaluations/research-qa/m78-continuation4-exercise-failure-qa-result.json'}as const,loaded:any={};for(const[key,path]of Object.entries(files))loaded[key]=await readFile(path,'utf8');
 const pins=Array.from({length:173},(_,index)=>{const path=index===0?'tools/staging/check-m78-continuation4-readonly-recovery.ts':`synthetic://current/${index}`,text=`pin-${index}`;return{path,text,sha256:sha(text)}}),currentSourcePins=pins.map(({path,sha256})=>({path,sha256})),currentSourceGateText=JSON.stringify({status:'m78_continuation4_readonly_recovery_source_admitted',historicalExerciseGateSha256:'9fe233c964b8c40f6c7a9871eecf75a318e7a800f2ec14570c6803288ff9dce7',sourcePins:currentSourcePins,sourcePinsSha256:sha(canonical(currentSourcePins)),runtime:{commit:'a'.repeat(40),deploymentId:'synthetic-deployment'}});
 return{...loaded,currentSourcePins,currentSourceGateText,load:async(path:string)=>pins.find(pin=>pin.path===path)!.text}as RecoveryAdmission;
}
function memoryIO(existing:string|null=null){const values=new Map<string,string>();if(existing)values.set(M78_READONLY_RECOVERY_PATHS.observation,existing);const io:RecoveryIO={read:async path=>values.get(path)??null,append:async(path,text,exclusive)=>{if(exclusive&&values.has(path))throw Error('exists');values.set(path,(values.get(path)??'')+text)}};return{io,values}}
function currentGraph(mainText:string){const events=mainText.trimEnd().split('\n').map(line=>JSON.parse(line)),identities=events.filter(event=>event.kind==='post_verified').map(event=>event.data.verifiedIdentity),reports=identities.filter(identity=>identity.reportSha256),processReports=reports.filter(identity=>events.find(event=>event.kind==='post_verified'&&event.data.verifiedIdentity.id===identity.id)!.data.name.includes('process')),inventoryReports=reports.filter(identity=>!processReports.includes(identity));return{identities,reports,scope1:{extra:identities,process:{versions:[],reports:processReports},inventory:{versions:[],reports:inventoryReports}},registers:{corporate:{versions:[]},gas:{worksheets:[]},mobile:{worksheets:[]},fleet:{versions:[],reports:[]},diesel:{worksheets:[]},equipment:{versions:[],reports:[]},fugitive:{worksheets:[],population:{versions:[],reports:[]}}}}}
function harness(admission:RecoveryAdmission,options:{existing?:string;missingIdentity?:boolean;decodeFailure?:boolean;mutatingAuth?:boolean;wrongSubject?:boolean;openFailure?:boolean;oversized?:boolean;closeFailure?:boolean;journalFailure?:boolean;diagnosticHeaderFailure?:boolean;diagnosticLogoutFailures?:boolean;diagnosticPhaseFailure?:boolean;invalidLogoutScope?:boolean}={}){
 const {io,values}=memoryIO(options.existing??null),graph=currentGraph(admission.mainText);if(options.missingIdentity)graph.scope1.extra.splice(1,1);const calls:{url:string;init:RequestInit}[]=[];{const append=io.append;let journalInjected=false,headerInjected=false,phaseInjected=false;io.append=async(path,text,exclusive)=>{const event=path===M78_READONLY_RECOVERY_PATHS.diagnostics?JSON.parse(text):null;if(options.journalFailure&&!journalInjected&&text.includes('"logout_intent"')){journalInjected=true;throw Error('journal write failed')}if(options.diagnosticHeaderFailure&&!headerInjected&&event?.kind==='response_headers'&&event.data.ordinal===1){headerInjected=true;throw Error('diagnostic header write failed')}if(options.diagnosticLogoutFailures&&event?.kind==='request_intent'&&event.data.route==='auth:/auth/v1/logout')throw Error('diagnostic logout write failed');if(options.diagnosticPhaseFailure&&!phaseInjected&&event?.kind==='phase_finished'){phaseInjected=true;throw Error('diagnostic phase write failed')}return append(path,text,exclusive)}}
 let oversizedCancelled=false;
 const reports=Object.fromEntries(graph.reports.map((identity:any)=>[identity.id,{...identity,html:`<p>${identity.id}</p>`,snapshotJson:'{"proof":{}}'}]));
 const transport=(async(raw:RequestInfo|URL,init:RequestInit={})=>{const url=String(raw);calls.push({url,init});if(url.startsWith(M78_READONLY_RECOVERY_AUTH))return new Response(null,{status:url.includes('/logout')?204:200});const parsed=new URL(url),auth=new Headers(init.headers).get('authorization');if(!auth)return Response.json({error:'Authentication required.'},{status:401});if(auth==='Bearer outsider')return Response.json({error:'Forbidden.'},{status:403});if(options.oversized&&auth==='Bearer manager1'&&parsed.pathname.endsWith('/scope1-inventory')){let chunk=0;return new Response(new ReadableStream<Uint8Array>({pull(controller){controller.enqueue(new Uint8Array(chunk++===0?6_000_000:5_000_001))},cancel(){oversizedCancelled=true}}),{headers:{'cache-control':'no-store'}})}const id=parsed.pathname.split('/').at(-1)!;let body:any;if(reports[id])body=reports[id];else if(parsed.pathname.endsWith('/scope1-inventory'))body=graph.scope1;else{const key=({'corporate-inventories':'corporate','stationary-natural-gas':'gas','mobile-diesel':'mobile','controlled-fleet':'fleet','stationary-diesel':'diesel','stationary-equipment':'equipment','fugitive-sources':'fugitive'}as Record<string,string>)[parsed.pathname.split('/').at(-1)!];body=(graph.registers as any)[key!]}return Response.json(body,{headers:{'cache-control':'no-store'}})})as typeof globalThis.fetch;
 const auth:RecoveryAuth={open:async(role,request)=>{if(options.mutatingAuth)await request(M78_READONLY_RECOVERY_HOST+'/workspace-api/workspace/x/scope1-inventory',{method:'POST'});else await request(M78_READONLY_RECOVERY_AUTH+'/auth/v1/token',{method:'POST',body:'private'});if(options.openFailure)throw Error('open failed after token response');return{role,subject:options.wrongSubject?role+'-wrong':role,authorization:'Bearer '+role,status:200}},close:async(session,request)=>{const suffix=options.invalidLogoutScope?'':'?scope=local',status=(await request(M78_READONLY_RECOVERY_AUTH+'/auth/v1/logout'+suffix,{method:'POST',body:'private'})).status;return options.closeFailure&&session.role==='member'?500:status}};
 const identity=async(value:any)=>{if(options.decodeFailure)throw Error('decode');return value};
 const decoders:any={scope1:identity,corporate:identity,gas:identity,mobile:identity,fleet:identity,diesel:identity,equipment:identity,fugitive:identity,scope1Report:identity};
 const readLegacy=async(request:any,expected:unknown)=>{for(let index=0;index<4;index++)await request(M78_READONLY_RECOVERY_AUTH+'/auth/v1/token',{method:'POST',body:'private'});for(let index=0;index<4;index++)await request(M78_READONLY_RECOVERY_AUTH+'/auth/v1/logout?scope=local',{method:'POST',body:'private'});return{value:expected,applicationPostRequests:0 as const,allCreatedAuthSessionsClosed:true as const}};
 return{io,values,calls,oversizedWasCancelled:()=>oversizedCancelled,run:()=>runM78Continuation4ReadonlyRecovery({admission,io,fetch:transport,auth,expectedSubjects:{manager1:'manager1',manager2:'manager2',member:'member',outsider:'outsider'},readLegacy,decoders,now:()=>new Date(2026,8,23,1,0,calls.length).toISOString()})};
}

test('exact closed failure and separate historical/current source gates admit before authentication',async()=>{const admission=await evidence(),result=await verifyM78ReadonlyRecoveryPreAuth(admission);expect(result.reconciled.operationTriplesVerified).toBe(37);expect(result.historicalSourcePins).toHaveLength(173);const changed={...admission,currentSourceGateText:admission.currentSourceGateText.replace('synthetic-deployment','other')};changed.currentSourcePins=[...changed.currentSourcePins].reverse();await expect(verifyM78ReadonlyRecoveryPreAuth(changed)).rejects.toThrow('fresh source gate pins')});

test('graph-first success is GET-only, one-call, no-pool and writes observation after all session cleanup',async()=>{const h=harness(await evidence()),result=await h.run();expect(result.status).toBe('passed');expect(result.applicationPostRequests).toBe(0);expect(result.allCreatedAuthSessionsClosed).toBeTrue();expect(result.requests).toBe(32);expect(h.calls).toHaveLength(32);expect(h.calls.filter(call=>call.url.startsWith(M78_READONLY_RECOVERY_HOST))).toHaveLength(16);expect(h.calls.filter(call=>call.url.startsWith(M78_READONLY_RECOVERY_HOST)).every(call=>(call.init.method??'GET')==='GET'&&call.init.body===undefined)).toBeTrue();expect(h.calls.every(call=>call.init.keepalive===false&&call.init.redirect==='error'&&call.init.signal instanceof AbortSignal)).toBeTrue();expect(result.observation.reportFullRecordReads).toBe(5);expect(result.observation.extraArtifactEndpointReads).toBe(0);expect(h.values.has(M78_READONLY_RECOVERY_PATHS.observation)).toBeTrue();const journal=h.values.get(M78_READONLY_RECOVERY_PATHS.journal)!;expect(journal.indexOf('private')).toBe(-1);expect(JSON.parse(journal.trimEnd().split('\n').at(-1)!).data.status).toBe('passed')});

test('production decoders accept the exact accepted baseline graph',async()=>{const text=await readFile('.superpowers/m78-hosted-continuation4.jsonl','utf8'),baseline=text.trimEnd().split('\n').map(line=>JSON.parse(line)).find(event=>event.kind==='baseline').data,company=JSON.parse(text.split('\n')[0]!).workspaceId;expect(await decodeScope1Register(baseline.scope1,company)).toEqual(baseline.scope1);for(const [family,decode]of [['corporate',decodeCorporateRegister],['gas',decodeGasRegister],['mobile',decodeMobileRegister],['fleet',decodeFleetRegister],['diesel',decodeGeneratorRegister],['equipment',decodeStationaryRegister],['fugitive',decodeFugitiveRegister]]as const)expect(await decode(baseline.registers[family],company)).toEqual(baseline.registers[family])});

test('duplicate execution refuses before auth or evidence writes',async()=>{const h=harness(await evidence(),{existing:'{}'});await expect(h.run()).rejects.toThrow('exclusive recovery path exists');expect(h.calls).toHaveLength(0);expect(h.values.size).toBe(1)});

test('missing graph identity and decode failure close all sessions and never write success observation',async()=>{for(const options of [{missingIdentity:true},{decodeFailure:true}]){const h=harness(await evidence(),options),result=await h.run();expect(result.status).toBe('failed');expect(result.allCreatedAuthSessionsClosed).toBeFalse();expect(h.calls.filter(call=>call.url.includes('/auth/v1/logout'))).toHaveLength(4);expect(h.values.has(M78_READONLY_RECOVERY_PATHS.observation)).toBeFalse();expect(JSON.parse(h.values.get(M78_READONLY_RECOVERY_PATHS.journal)!.trimEnd().split('\n').at(-1)!).data.status).toBe('failed')}});

test('mutating application request is rejected without transport dispatch or success claim',async()=>{const h=harness(await evidence(),{mutatingAuth:true}),result=await h.run();expect(result.status).toBe('failed');expect(result.unknownAuthSessions).toBe(1);expect(h.calls.filter(call=>call.url.startsWith(M78_READONLY_RECOVERY_HOST))).toHaveLength(0);expect(h.values.has(M78_READONLY_RECOVERY_PATHS.observation)).toBeFalse()});

test('wrong known actor is logged out while post-response auth-open failure remains uncertain',async()=>{const wrong=harness(await evidence(),{wrongSubject:true}),wrongResult=await wrong.run();expect(wrongResult.status).toBe('failed');expect(wrongResult.unknownAuthSessions).toBe(0);expect(wrong.calls.filter(call=>call.url.includes('/auth/v1/logout'))).toHaveLength(1);expect(wrongResult.allCreatedAuthSessionsClosed).toBeFalse();expect(wrong.values.has(M78_READONLY_RECOVERY_PATHS.observation)).toBeFalse();const uncertain=harness(await evidence(),{openFailure:true}),uncertainResult=await uncertain.run();expect(uncertainResult.status).toBe('failed');expect(uncertainResult.unknownAuthSessions).toBe(1);expect(uncertain.calls.filter(call=>call.url.includes('/auth/v1/logout'))).toHaveLength(0);expect(uncertainResult.allCreatedAuthSessionsClosed).toBeFalse();expect(uncertain.values.has(M78_READONLY_RECOVERY_PATHS.observation)).toBeFalse()});

test('streaming response limit cancels the oversized body and logout failure prevents admission',async()=>{const oversized=harness(await evidence(),{oversized:true}),oversizedResult=await oversized.run();expect(oversizedResult.status).toBe('failed');expect(oversizedResult.error).toBe('response byte bound');expect(oversized.oversizedWasCancelled()).toBeTrue();expect(oversized.calls.filter(call=>call.url.includes('/auth/v1/logout'))).toHaveLength(4);expect(oversized.values.has(M78_READONLY_RECOVERY_PATHS.observation)).toBeFalse();const logout=harness(await evidence(),{closeFailure:true}),logoutResult=await logout.run();expect(logoutResult.status).toBe('failed');expect(logoutResult.allCreatedAuthSessionsClosed).toBeFalse();expect(logout.values.has(M78_READONLY_RECOVERY_PATHS.observation)).toBeFalse()});

test('journal failure during cleanup cannot prevent all four main logout attempts',async()=>{const h=harness(await evidence(),{journalFailure:true}),result=await h.run();expect(result.status).toBe('failed');expect(result.error).toBe('journal write failed');expect(h.calls.filter(call=>call.url.includes('/auth/v1/logout'))).toHaveLength(8);expect(result.allCreatedAuthSessionsClosed).toBeTrue();expect(h.values.has(M78_READONLY_RECOVERY_PATHS.observation)).toBeFalse()});

test('diagnostic failures after a token response and repeatedly during cleanup still return and close known sessions',async()=>{const header=harness(await evidence(),{diagnosticHeaderFailure:true}),headerResult=await header.run();expect(headerResult.status).toBe('failed');expect(headerResult.error).toBe('diagnostic header write failed');expect(header.calls.filter(call=>call.url.includes('/auth/v1/token'))).toHaveLength(1);expect(header.calls.filter(call=>call.url.includes('/auth/v1/logout'))).toHaveLength(1);expect(header.calls.filter(call=>call.url.startsWith(M78_READONLY_RECOVERY_HOST))).toHaveLength(0);expect(header.values.has(M78_READONLY_RECOVERY_PATHS.observation)).toBeFalse();const repeated=harness(await evidence(),{decodeFailure:true,diagnosticLogoutFailures:true}),repeatedResult=await repeated.run();expect(repeatedResult.status).toBe('failed');expect(repeated.calls.filter(call=>call.url.includes('/auth/v1/logout'))).toHaveLength(4);expect(repeated.values.has(M78_READONLY_RECOVERY_PATHS.observation)).toBeFalse()});

test('only local-scope logout may reach the fixed authentication transport',async()=>{const valid=harness(await evidence(),{decodeFailure:true});await valid.run();expect(valid.calls.filter(call=>call.url.includes('/auth/v1/logout')).every(call=>new URL(call.url).searchParams.get('scope')==='local')).toBeTrue();const invalid=harness(await evidence(),{decodeFailure:true,invalidLogoutScope:true}),invalidResult=await invalid.run();expect(invalidResult.status).toBe('failed');expect(invalid.calls.filter(call=>call.url.includes('/auth/v1/logout'))).toHaveLength(0);expect(invalid.values.has(M78_READONLY_RECOVERY_PATHS.observation)).toBeFalse()});

test('final diagnostic commit precedes observation and can still veto success',async()=>{const h=harness(await evidence(),{diagnosticPhaseFailure:true}),result=await h.run();expect(result.status).toBe('failed');expect(result.error).toBe('diagnostic phase write failed');expect(h.values.has(M78_READONLY_RECOVERY_PATHS.observation)).toBeFalse();expect(JSON.parse(h.values.get(M78_READONLY_RECOVERY_PATHS.journal)!.trimEnd().split('\n').at(-1)!).data.status).toBe('failed')});
