/** Explicit private synthetic operator journey. Imports never authenticate; no ENV or private files. */
import path from 'node:path'
import {open,readFile,unlink} from 'node:fs/promises'
import {parseJourneyInput} from './check-hosted-journey'
import {readM73Journal} from './check-m73-hosted'
import {decodeGasRegister} from '../../apps/site-web/src/lib/m73-api'
import {m73Export} from '../../packages/neuvetra-database/src/index'
import {runM72Journey} from './check-m72-hosted'
import {decodeCorporateRegister,decodeCorporateVersion} from '../../apps/site-web/src/lib/m71-api'
import {decodeMobileRegister,decodeMobileVersion,decodeMobileReview,decodeMobileReport} from '../../apps/site-web/src/lib/m74-api'
import {M71_ARTIFACT,M71_EVIDENCE_SHA256,M74_PROFILE,M74_PERIOD,M74_LIMITATIONS,m74SourceChoices,m74CanonicalJson,m74Export,type M74Version,type M71Register,type M74Register} from '../../packages/neuvetra-database/src/index'
const HOST='https://www.neuvetra.ai',AUTH='https://icockcoguyadhryzydvl.supabase.co',PROFILE='neuvetra.private-synthetic-staging.v1'
const RECEIPT=path.resolve(import.meta.dir,'../../.superpowers/m74-hosted-journey.jsonl'),PREVIOUS=path.resolve(import.meta.dir,'../../.superpowers/m73-hosted-journey.jsonl')
type Mode='baseline'|'exercise'|'revisit'
type Input=ReturnType<typeof parseJourneyInput>&{mode:Mode}
type Role=Input['accounts'][number]['role']|'signed_out'
type Event={sequence:number;previousSha256:string|null;workspaceId:string;mode:Mode;kind:string;data:any;createdAt:string;sha256:string}
type Dependencies={fetch?:typeof fetch;load?:()=>Promise<string|null>;append?:(line:string,exclusive:boolean)=>Promise<void>;loadPrevious?:()=>Promise<any>;legacy?:typeof runM72Journey}
const check=(value:unknown):void=>{if(!value)throw Error('Bounded M74 journey refused.')}
const hash=(value:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(value).digest('hex')
const canonical=m74CanonicalJson
const same=(a:unknown,b:unknown)=>canonical(a)===canonical(b)
const observation=(bytes:Uint8Array)=>({sha256:hash(bytes),byteLength:bytes.length})
export function parseM74JourneyInput(value:unknown):Input{const mode=(value as any)?.mode;check(['baseline','exercise','revisit'].includes(mode));return {...parseJourneyInput(value),mode}}
export function validateM74JourneyRoute(url:string,method:string,workspaceId:string){const u=new URL(url);check(!u.hash&&!u.username&&!u.password);const root=`/workspace-api/workspace/${workspaceId}`;if(u.origin===AUTH){check(method==='POST'&&(u.pathname==='/auth/v1/token'&&u.search==='?grant_type=password'||u.pathname==='/auth/v1/logout'&&u.search==='?scope=local'));return}check(u.origin===HOST&&!u.search&&(u.pathname==='/ready'||u.pathname==='/workspace-api/config'||u.pathname==='/workspace-api/session'||u.pathname===root||u.pathname.startsWith(root+'/')));if(method!=='GET')check(method==='POST'&&(u.pathname===root+'/corporate-inventories'||new RegExp('^'+root+'/corporate-inventories/[0-9a-f-]{36}/versions$').test(u.pathname)||u.pathname===root+'/mobile-diesel'||new RegExp('^'+root+'/mobile-diesel/[0-9a-f-]{36}/(versions|reviews|reports)$').test(u.pathname)))}
export function readM74Journal(text:string|null,workspaceId:string):Event[]{if(text===null)return [];check(text.length<=32_000_000&&text.endsWith('\n'));const events=text.trimEnd().split('\n').map(line=>JSON.parse(line)) as Event[];let previous:string|null=null;for(const [i,event]of events.entries()){const {sha256,...payload}=event;check(event.sequence===i+1&&event.previousSha256===previous&&event.workspaceId===workspaceId&&['baseline','exercise','revisit'].includes(event.mode)&&typeof event.kind==='string'&&typeof event.createdAt==='string'&&hash(canonical(payload))===sha256);previous=sha256}return events}
export async function runM74Journey(input:Input,deps:Dependencies={}){
 const events:Event[]=[],tokens=new Map<Role,string>(),company=input.roster.workspaceId,root=`/workspace-api/workspace/${company}`,corporateRoot=root+'/corporate-inventories',gasRoot=root+'/mobile-diesel';let stage='receipt_load',writes=0,unknownSessions=0,closed=true,failed=false,loaded=false,legacyClosed=true,attemptSequence:number|null=null
 const network=async(url:string,init:RequestInit={})=>{validateM74JourneyRoute(url,init.method??'GET',company);return (deps.fetch??fetch)(url,{...init,redirect:'error',signal:AbortSignal.timeout(30000)})}
 const append=async(kind:string,data:any)=>{const payload={sequence:events.length+1,previousSha256:events.at(-1)?.sha256??null,workspaceId:company,mode:input.mode,kind,data,createdAt:new Date().toISOString()},event={...payload,sha256:hash(canonical(payload))},line=JSON.stringify(event)+'\n';await (deps.append??(async(line,exclusive)=>{const file=await open(RECEIPT,exclusive?'wx':'a');try{await file.writeFile(line,'utf8');await file.sync()}finally{await file.close()}}))(line,events.length===0);events.push(event)}
 const completed=(name:string)=>events.find(e=>e.kind==='post_outcome'&&e.data.name===name)
 const decodeOutcome=async(name:string,value:unknown)=>{let record:unknown;if(name==='m71_add_source')record=await decodeCorporateVersion(value,company);else if(name==='m74_save'||name==='m74_correction')record=await decodeMobileVersion(value,company);else if(name==='m74_review')record=await decodeMobileReview(value,company);else if(name==='m74_unreviewed_report'||name==='m74_reviewed_report')record=await decodeMobileReport(value,company);else throw Error('Unknown successful journey operation.');return JSON.parse(canonical(record))}
 const request=async(name:string,route:string,role:Role='manager1',body?:unknown,expected=body===undefined?200:201):Promise<any>=>{
  stage=name;const old=completed(name);if(body!==undefined){check(input.mode==='exercise');if(old){const intent=events.find(e=>e.kind==='post_intent'&&e.data.name===name)!;const withoutKey=(value:any)=>{const {idempotencyKey:_,...rest}=value;return rest};check(old.data.route===route&&old.data.role===role&&old.data.expected===expected&&same(withoutKey(intent.data.request),withoutKey(body)));if(expected===201)return await decodeOutcome(name,old.data.response);check(!('response' in old.data));return undefined}check(!events.some(e=>e.kind==='post_intent'&&e.data.name===name));await append('post_intent',{name,route,role,expected,request:body});writes++}
  const response=await network(HOST+route,{method:body===undefined?'GET':'POST',headers:{origin:HOST,...(tokens.has(role)?{authorization:'Bearer '+tokens.get(role)}:{}),...(body===undefined?{}:{'content-type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)})
  const bytes=new Uint8Array(await response.arrayBuffer());check(bytes.length<=4_000_000&&response.headers.get('cache-control')?.includes('no-store'))
  if(body!==undefined&&(response.status!==expected||expected!==201)){await append('post_outcome',{name,route,role,expected,status:response.status,responseObservation:observation(bytes)});check(response.status===expected);return undefined}
  const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);let value:any;try{value=JSON.parse(text)}catch{value=text}
  if(body!==undefined){value=await decodeOutcome(name,value);await append('post_outcome',{name,route,role,expected,status:response.status,response:value})}check(response.status===expected)
  return value
 }
 const download=async(name:string,route:string,expected:string)=>{stage=name;const r=await network(HOST+route,{headers:{origin:HOST,authorization:'Bearer '+tokens.get('member')}});const b=new Uint8Array(await r.arrayBuffer());check(r.status===200&&r.headers.get('cache-control')?.includes('no-store')&&b.length<=4_000_000&&new TextDecoder('utf-8',{fatal:true}).decode(b)===expected);return observation(b)}
 const corporate=async()=>decodeCorporateRegister(await request('m71_read',corporateRoot),company)
 const exports=async(register:M71Register)=>{const out:Record<string,unknown>={};for(const v of register.versions)out[v.id]=await download('m71_export',`${corporateRoot}/${v.inventoryId}/versions/${v.id}/coverage-export`,canonical({...v,review:null}));return out}
 const preserved=(original:M71Register,current:M71Register)=>{for(const v of original.versions)check(same(current.versions.find(x=>x.id===v.id),v))}
 const gas=async()=>decodeMobileRegister(await request('m74_read',gasRoot),company)
 const gasDownloads=async(register:M74Register)=>{const out:Record<string,unknown>={};for(const w of register.worksheets){for(const v of w.versions){out['version_'+v.id]=await download('m74_export',`${gasRoot}/${w.worksheetId}/versions/${v.id}/calculation-export`,m74Export(v));for(const kind of ['fuel','mileage'] as const){const statement=kind==='fuel'?v.fuelStatement:v.mileageStatement;if(statement)out[kind+'_'+statement.id]=await download('m74_'+kind,`${gasRoot}/${w.worksheetId}/statements/${statement.id}/download`,statement.text)}}for(const r of w.reports)out['report_'+r.id]=await download('m74_report',`${gasRoot}/${w.worksheetId}/reports/${r.id}/download`,r.html)}return out}
 try{
  const raw=deps.load?await deps.load():await Bun.file(RECEIPT).exists()?await Bun.file(RECEIPT).text():null;events.push(...readM74Journal(raw,company));loaded=true
  stage='resume_preconditions';check(!events.some(e=>e.kind==='attempt_started'&&!events.some(f=>f.kind==='attempt_finished'&&f.data.attemptSequence===e.sequence)));check(!events.some(e=>e.kind==='post_intent'&&!completed(e.data.name)));check(!events.some(e=>e.kind==='attempt_finished'&&e.data.allCreatedAuthSessionsClosed===false));check(!events.some(e=>e.kind==='post_outcome'&&e.data.status!==e.data.expected))
  const baseline=events.find(e=>e.kind==='baseline'),success=events.find(e=>e.kind==='exercise_complete');check(input.mode==='baseline'?!baseline:!!baseline);if(input.mode==='revisit')check(success);if(input.mode==='exercise')check(!success)
  await append('attempt_started',{mode:input.mode});attemptSequence=events.at(-1)!.sequence
  const previous=await(deps.loadPrevious?deps.loadPrevious():Bun.file(PREVIOUS).text());const priorEvents=readM73Journal(previous,company),previousSuccess=priorEvents.find(e=>e.kind==='exercise_complete')?.data,previousBaseline=priorEvents.find(e=>e.kind==='baseline')?.data;check(previousSuccess&&previousBaseline&&priorEvents.some(e=>e.kind==='revisit_verified')&&!priorEvents.some(e=>e.kind==='attempt_started'&&!priorEvents.some(f=>f.kind==='attempt_finished'&&f.data.attemptSequence===e.sequence))&&!priorEvents.some(e=>e.kind==='attempt_finished'&&e.data.allCreatedAuthSessionsClosed===false))
  stage='legacy_read_only';let legacy:any
  const verifyLegacy=async()=>{
  const run=await(deps.legacy??runM72Journey)({...input,mode:'baseline'},{load:async()=>null,save:async value=>{legacy=value},fetch:(async(url,init)=>{
   const target=String(url);check(!(target.startsWith(HOST)&&init?.method==='POST'));const r=await network(target,init);if(target===HOST+'/ready'){const v=await r.json() as any;check(r.status===200&&v.schemaVersion===(input.mode==='baseline'?16:17));await append('actual_readiness',{schemaVersion:v.schemaVersion});return Response.json({...v,schemaVersion:14},{status:r.status,headers:r.headers})}return r
  }) as typeof fetch});legacyClosed=run.allCreatedAuthSessionsClosed;check(run.status==='passed'&&legacyClosed&&run.applicationPostRequests===0&&same(legacy.baseline,previousBaseline.legacy));if(baseline)check(same(legacy.baseline,baseline.data.legacy))
  };await verifyLegacy()
  for(const account of input.accounts){stage='sign_in_'+account.role;unknownSessions++;const r=await network(AUTH+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:input.env.SUPABASE_ANON_KEY,'content-type':'application/json'},body:JSON.stringify({email:account.email,password:account.password})}),session=await r.json() as any;if(typeof session.access_token==='string'&&session.access_token.length>0&&session.access_token.length<=8192){tokens.set(account.role,session.access_token);unknownSessions--}check(r.status===200&&session.user?.id===account.id&&tokens.has(account.role))}
  const verifyGas=async()=>{const prior=await decodeGasRegister(await request('m73_preserved',root+'/stationary-natural-gas'),company);check(same(prior.worksheets.map(({findings:_,...w})=>w),previousSuccess.register.worksheets.map(({findings:_,...w}:any)=>w))&&same(prior.limitations,previousSuccess.register.limitations));const out:Record<string,unknown>={};for(const w of prior.worksheets){for(const v of w.versions){out['version_'+v.id]=await download('m73_export',`${root}/stationary-natural-gas/${w.worksheetId}/versions/${v.id}/calculation-export`,m73Export(v));if(v.statement)out['statement_'+v.statement.id]=await download('m73_statement',`${root}/stationary-natural-gas/${w.worksheetId}/statements/${v.statement.id}/download`,v.statement.text)}for(const r of w.reports)out['report_'+r.id]=await download('m73_report',`${root}/stationary-natural-gas/${w.worksheetId}/reports/${r.id}/download`,r.html)}check(same(out,previousSuccess.downloads));return {register:prior,downloads:out}}
  const priorGas=await verifyGas()
  let cv=await corporate();preserved(previousSuccess.corporate,cv);if(baseline)preserved(baseline.data.corporate,cv);const beforeExports=await exports(cv)
  if(input.mode==='baseline'){check(same(cv,previousSuccess.corporate)&&same(beforeExports,previousSuccess.exports));await append('baseline',{legacy:legacy.baseline,corporate:cv,exports:beforeExports,priorGas})}
  else if(input.mode==='exercise'){
   const owner=input.accounts.find(a=>a.role==='manager1')!.id,reviewer=input.accounts.find(a=>a.role==='manager2')!.id
   const sourceStage=completed('m71_add_source');let linked:any
   if(sourceStage)linked=await decodeCorporateVersion(sourceStage.data.response,company)
   else{check(same(cv,baseline!.data.corporate));const head=cv.versions.at(-1)!;check(!head.contributorIds.includes(reviewer));const snapshot=structuredClone(head.snapshot),facility=snapshot.facilities.find(f=>f.countryCode==='US'&&f.regionCode==='CA'&&f.start<='2025-01-01'&&f.endExclusive>='2026-01-01'&&snapshot.boundaryDecisions.some(b=>b.entityId===f.entityId&&b.disposition==='included_activity'))!;check(facility);const boundary=snapshot.boundaryDecisions.find(b=>b.entityId===facility.entityId&&b.disposition==='included_activity')!;boundary.reason='Synthetic operational control of the owned diesel vehicle throughout 2025; internal draft only.';boundary.evidenceRefs=[{artifactId:M71_ARTIFACT.id,expectedSha256:M71_EVIDENCE_SHA256,locator:M71_ARTIFACT.locator,purpose:'Synthetic operational-control basis'}];const sourceId=crypto.randomUUID();snapshot.sources.push({id:sourceId,entityId:facility.entityId,facilityId:facility.id,name:'Synthetic owned medium-heavy diesel vehicle',domain:'mobile_combustion',...M74_PERIOD,evidenceRefs:[]});snapshot.coverageItems.push({id:crypto.randomUUID(),entityId:facility.entityId,sourceId,domain:'mobile_combustion',...M74_PERIOD,disposition:'missing',activityDataState:'missing',evidenceState:'missing',methodReadiness:'candidate',reason:null,evidenceRefs:[],estimateBasis:null,quantity:null,unit:null});check(m74SourceChoices({...head,snapshot}).some(c=>c.binding.sourceId===sourceId&&c.eligible));linked=await decodeCorporateVersion(await request('m71_add_source',`${corporateRoot}/${head.inventoryId}/versions`,'manager1',{snapshot,expectedVersionId:head.id,expectedVersionSha256:head.versionSha256,correctionReason:'Add one synthetic mobile source without replacing corporate history.',idempotencyKey:crypto.randomUUID()}),company,head)}
   cv=await corporate();check(cv.headVersionId===linked.id);preserved(baseline!.data.corporate,cv);check(!linked.contributorIds.includes(reviewer)&&linked.contributorIds.includes(owner));const oldIds=new Set(baseline!.data.corporate.versions.at(-1).snapshot.sources.map((s:any)=>s.id)),choice=m74SourceChoices(linked).find(c=>!oldIds.has(c.binding.sourceId));check(choice?.eligible)
   const register=await gas();check(register.worksheets.length===(completed('m74_save')?1:0))
   const initial={profile:M74_PROFILE,binding:choice!.binding,period:M74_PERIOD,vehicle:{assetId:'M74-HOSTED-TRUCK-001',vehicleClass:'Medium- and Heavy-Duty Vehicles',classificationBasis:'Fictional heavy-duty on-road registration; owned and operationally controlled throughout calendar 2025.',modelYear:2018,fuel:'Fossil Diesel',controlBasis:'owned_operational_control_full_year'},quantityGallons:'1000.125',distanceMiles:'12000.500',fuelStatement:{issuer:'Fictional fleet fuel team',reference:'M74-HOSTED-FUEL-2025-01',statedQuantityGallons:'1000.125',description:'Fictional fossil-only diesel consumed by this vehicle; no stock, blend, auxiliary engine or shared-fuel adjustments.',consumptionBasis:'dedicated_vehicle_consumed_no_adjustments'},mileageStatement:{issuer:'Fictional fleet distance team',reference:'M74-HOSTED-MILES-2025-01',statedDistanceMiles:'12000.500',description:'Fictional actual full-year vehicle-miles including all locations and interstate travel; no estimated or extrapolated distance.',distanceBasis:'dedicated_vehicle_annual_distance'},fuelManualConfirmation:true,mileageManualConfirmation:true,fuelDiscrepancyReason:null,mileageDiscrepancyReason:null,zeroReason:null,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()}
   await request('m74_member_save_refused',gasRoot,'member',initial,403);await request('m74_outsider_save_refused',gasRoot,'outsider',initial,403);await request('m74_signed_out_save_refused',gasRoot,'signed_out',initial,401)
   const first=await decodeMobileVersion(await request('m74_save',gasRoot,'manager1',initial),company);check(first.review===null&&first.calculation?.total.display==='10351.5321'&&!first.contributorIds.includes(reviewer));const w=gasRoot+'/'+first.worksheetId
   const reportInput=(v:M74Version)=>({versionId:v.id,expectedVersionSha256:v.versionSha256,expectedDecisionId:v.review?.id??null,expectedDecisionSha256:v.review?.decisionSha256??null,idempotencyKey:crypto.randomUUID()})
   const unreviewed=await decodeMobileReport(await request('m74_unreviewed_report',w+'/reports','manager1',reportInput(first)),company,first);check(unreviewed.decisionId===null)
   const review={versionId:first.id,expectedVersionSha256:first.versionSha256,decision:'accepted_bounded_internal',note:'Distinct manager checked the bounded synthetic vehicle source. Scope 1 and corporate inventory remain incomplete; no external assurance.',acknowledgedLimitations:[...M74_LIMITATIONS],idempotencyKey:crypto.randomUUID()}
   await request('m74_contributor_review_refused',w+'/reviews','manager1',review,403);await request('m74_member_review_refused',w+'/reviews','member',review,403)
   const decision=await decodeMobileReview(await request('m74_review',w+'/reviews','manager2',review),company,first);check(decision.reviewerId===reviewer);const reviewed={...first,review:decision}
   const report=await decodeMobileReport(await request('m74_reviewed_report',w+'/reports','manager1',reportInput(reviewed)),company,reviewed);check(report.decisionId===decision.id)
   const second=await decodeMobileVersion(await request('m74_correction',w+'/versions','manager1',{...initial,distanceMiles:'12500.500',expectedVersionId:first.id,expectedVersionSha256:first.versionSha256,correctionReason:'Correct entered annual activity; preserve original evidence and prior review.',mileageDiscrepancyReason:'Synthetic corrected miles exceed the retained mileage statement; discrepancy remains open.',idempotencyKey:crypto.randomUUID()}),company,first);check(second.review===null&&second.calculation?.total.display==='10357.3758'&&second.findings.some(f=>f.code==='mileage_activity_statement_discrepancy'))
   const final=await gas();check(final.worksheets.length===1&&final.worksheets[0]!.versions.length===2&&same(final.worksheets[0]!.versions[0],reviewed)&&same(final.worksheets[0]!.versions[1],second));const downloads=await gasDownloads(final);await verifyLegacy();check(same((await verifyGas()).downloads,priorGas.downloads));check(same(await corporate(),cv));await append('exercise_complete',{corporate:cv,exports:await exports(cv),register:final,downloads})
  }else{const register=await gas();check(same(cv,success!.data.corporate)&&same(beforeExports,success!.data.exports)&&same(register,success!.data.register)&&same(await gasDownloads(register),success!.data.downloads));await append('revisit_verified',{exerciseSha256:success!.sha256})}
 }catch{failed=true}
 finally{for(const token of tokens.values()){try{const r=await network(AUTH+'/auth/v1/logout?scope=local',{method:'POST',headers:{apikey:input.env.SUPABASE_ANON_KEY,authorization:'Bearer '+token}});await r.body?.cancel();if(r.status!==204)closed=false}catch{closed=false}}tokens.clear()}
 const allCreatedAuthSessionsClosed=closed&&legacyClosed&&unknownSessions===0;failed||=!allCreatedAuthSessionsClosed
 if(loaded)try{await append('attempt_finished',{attemptSequence,status:failed?'failed':'passed',stage,applicationPostRequests:writes,allCreatedAuthSessionsClosed})}catch{failed=true;stage='receipt_append'}
 return {status:failed?'failed':'passed',mode:input.mode,stage,applicationPostRequests:writes,allCreatedAuthSessionsClosed,receiptSha256:events.at(-1)?.sha256??null}
}
if(import.meta.main){let lock:Awaited<ReturnType<typeof open>>|undefined;try{const text=await Bun.stdin.text();check(text.length<=128000);const input=parseM74JourneyInput(JSON.parse(text));lock=await open(RECEIPT+'.lock','wx');const result=await runM74Journey(input);console.log(JSON.stringify(result));if(result.status!=='passed')process.exitCode=1}catch{console.log(JSON.stringify({status:'failed',stage:'input_or_exclusive_lock'}));process.exitCode=1}finally{if(lock){await lock.close();await unlink(RECEIPT+'.lock')}}}
