/** Author-only candidate harness. Imports never read credentials, authenticate or write. */
import path from 'node:path'
import {open,readFile,unlink} from 'node:fs/promises'
import {parseJourneyInput} from './check-hosted-journey'
import {runM72Journey} from './check-m72-hosted'
import {readM77Continuation} from './check-m77-continuation'
import {acceptedM76Continuation,preservesM77History} from './check-m77-hosted'
import {continueM78,assertM78ContinuationBaseline,M78_COMMITTED_INITIAL} from './m78-continuation-plan'
import {readM78Journal as readOriginalM78Journal,readM78Prior as readOriginalM78Prior} from './check-m78-hosted'
import {REVIEWED_MIGRATION_SHA256} from './m78-inventory'
import {m78CanonicalJson as canonical,parseM78Json} from '../../packages/neuvetra-database/src/m78-validation'
import {decodeScope1Register,decodeScope1Version,decodeScope1Report} from '../../apps/site-web/src/lib/m78-api'
import {decodeCorporateRegister,decodeCorporateVersion} from '../../apps/site-web/src/lib/m71-api'
import {decodeGasRegister,decodeGasVersion} from '../../apps/site-web/src/lib/m73-api'
import {decodeMobileRegister,decodeMobileVersion} from '../../apps/site-web/src/lib/m74-api'
import {decodeFleetRegister,decodeFleetVersion} from '../../apps/site-web/src/lib/m75-api'
import {decodeGeneratorRegister,decodeGeneratorVersion} from '../../apps/site-web/src/lib/m76-diesel-api'
import {decodeStationaryRegister,decodeStationaryVersion} from '../../apps/site-web/src/lib/m76-api'
import {decodeFugitiveRegister,decodeFugitiveVersion,decodeFugitiveReport} from '../../apps/site-web/src/lib/m77-api'
import {m71Export} from '../../packages/neuvetra-database/src/m71'
import {m73Export} from '../../packages/neuvetra-database/src/m73-validation'
import {m74Export} from '../../packages/neuvetra-database/src/m74-validation'
import {m75Export} from '../../packages/neuvetra-database/src/m75-validation'
import {m76Export} from '../../packages/neuvetra-database/src/m76-validation'
import {m77Export} from '../../packages/neuvetra-database/src/m77-validation'
const HOST='https://www.neuvetra.ai',AUTH='https://icockcoguyadhryzydvl.supabase.co',PROFILE='m78-hosted-continuation-v1'
const JOURNAL=path.resolve(import.meta.dir,'../../.superpowers/m78-hosted-continuation.jsonl')
export const M78_ACCEPTED_M77={journalSha256:'223a91a711026bf4be6c299ed9b83876a9bdc72440889fc607969dcbb338bc0c',headSha256:'19343893f2efa0b35c787c6516b6110c951378470fb8d547087bd7931778709e'} as const
const M76_PIN={journalSha256:'836aa21776e0ea6dc847463ffb15f44a89175b74b9a896835eef8efe103fdf82',headSha256:'60fe0f9dd5d9db08c468de3f2afa227879d031b4318591b8e81bdf5cae924da7'}
export const M78_EXPECTED_POSTS=37 //Only remaining recipe writes; original save and three refusals are preserved.
type Mode='baseline'|'exercise'|'revisit'
type Role='manager1'|'manager2'|'member'|'outsider'|'signed_out'
interface Gate {status:'m78_continuation_candidate_reviewed';migrationSha256:string;recipeSha256:string;harnessSha256:string;independentReviewSha256:string;operatorRecoveryReceiptSha256:string;reviewedApplicationCommit:string;expectedApplicationPosts:37}
export type M78JourneyInput=ReturnType<typeof parseJourneyInput>&{mode:Mode;acceptedM77:typeof M78_ACCEPTED_M77;gate:Gate;restartAttestation?:{path:string;sha256:string}}
export interface M78Event {sequence:number;previousSha256:string|null;profile:string;workspaceId:string;mode:Mode;kind:string;data:any;createdAt:string;sha256:string}
export interface M78Dependencies {fetch?:typeof fetch;load?:()=>Promise<string|null>;append?:(line:string,exclusive:boolean)=>Promise<void>;readPrior?:(company:string)=>Promise<{previous:{registers:any;downloads:any};old:{legacy:any};failed:any;observation:any}>;legacy?:typeof runM72Journey;exercise?:typeof continueM78;verifyGate?:(g:Gate)=>Promise<void>}
const hash=(v:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(v).digest('hex'),same=(a:unknown,b:unknown)=>canonical(a)===canonical(b),core=(v:any)=>({...v,review:null})
function check(v:unknown):asserts v{if(!v)throw Error('Bounded M78 hosted harness refused')}
/** Preserve flat legacy versions, reviews and reports; only M78 version responses are envelopes. */
export function m78VerifiedIdentity(decoded:unknown):Record<string,string>{
 const outer=decoded as Record<string,unknown>|null;
 check(outer&&typeof outer==='object'&&!Array.isArray(outer));
 const value=(outer.version&&typeof outer.version==='object'?outer.version:outer) as Record<string,unknown>;
 check(!Array.isArray(value)&&typeof value.id==='string'&&new RegExp('^'+uuid+'$').test(value.id));
 return Object.fromEntries(['id','companyId','streamId','inventoryId','worksheetId','rosterId','versionId','versionSha256','decisionSha256','reportSha256'].filter(k=>typeof value[k]==='string').map(k=>[k,value[k] as string]));
}
export function m78VerifiedReview(decoded:any,raw:any):void{
 const identity=m78VerifiedIdentity(raw);check(typeof identity.versionId==='string'&&new RegExp('^'+uuid+'$').test(identity.versionId));
 if(Array.isArray(decoded?.reviews)){
  const matches=decoded.reviews.filter((r:any)=>r?.versionId===raw.versionId&&r?.id===raw.id);check(matches.length===1&&same(matches[0],raw));
 }else{
  const version=decoded?.version&&typeof decoded.version==='object'?decoded.version:decoded;
  check(m78VerifiedIdentity(version).id===raw.versionId&&same(version.review,raw));
 }
}
export function m78JournalEventLimit(kind:string){return ['baseline','exercise_complete'].includes(kind)?50_000_000:kind==='post_intent'?220_000:kind==='post_verified'?4_000:64_000}
const digest=(s:unknown)=>typeof s==='string'&&/^[a-f0-9]{64}$/.test(s),uuid='[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'
export function parseM78ContinuationInput(raw:unknown):M78JourneyInput{const v=raw as any,g=v?.gate;check(['baseline','exercise','revisit'].includes(v?.mode)&&same(v.acceptedM77,M78_ACCEPTED_M77)&&g?.status==='m78_continuation_candidate_reviewed'&&g.expectedApplicationPosts===M78_EXPECTED_POSTS&&[g.migrationSha256,g.recipeSha256,g.harnessSha256,g.independentReviewSha256,g.operatorRecoveryReceiptSha256].every(digest)&&/^[a-f0-9]{40}$/.test(g.reviewedApplicationCommit));const pin=v.restartAttestation;check(v.mode==='revisit'?pin&&typeof pin==='object'&&!Array.isArray(pin)&&Object.keys(pin).sort().join(',')==='path,sha256'&&typeof pin.path==='string'&&/^\.superpowers\/m78-[a-z0-9-]+-verified\.json$/.test(pin.path)&&digest(pin.sha256):pin===undefined);return {...parseJourneyInput(raw),mode:v.mode,acceptedM77:M78_ACCEPTED_M77,gate:g,...(v.mode==='revisit'?{restartAttestation:{path:pin.path,sha256:pin.sha256}}:{})}}
export function validateM78ContinuationRestart(value:any,commit:string,exerciseFinishedAt:string){check(value?.status==='m78_runtime_verified'&&value.schemaVersion===21&&value.phase==='restart'&&value.commit===commit&&value.restartAcknowledged===true&&value.deploymentStatus==='SUCCESS'&&value.httpStatus===200&&value.ready?.schemaVersion===21&&value.ready?.status==='ready'&&value.ready?.legacyContainmentVerified===true);const end=Date.parse(exerciseFinishedAt),requested=Date.parse(value.restartRequestedAt),started=Date.parse(value.actualStartupEvent?.timestamp),collected=Date.parse(value.startupCollection?.observedAt),observed=Date.parse(value.observedAt);check([end,requested,started,collected,observed].every(Number.isFinite)&&end<requested&&requested<started&&started<=collected&&collected<=observed&&value.actualStartupEvent?.event==='staging_started'&&value.startupCollection?.deploymentId===value.deploymentId&&value.startupCollection?.commit===commit&&value.startupCollection?.imageDigest===value.imageDigest&&/^sha256:[a-f0-9]{64}$/.test(value.imageDigest)&&digest(value.startupCollection?.logsSha256))}
export async function readM78ContinuationRestart(input:M78JourneyInput,finishedAt:string,load?:(path:string)=>Promise<string>){const pin=input.restartAttestation;check(pin&&typeof pin.path==='string'&&/^\.superpowers\/m78-[a-z0-9-]+-verified\.json$/.test(pin.path)&&digest(pin.sha256));const text=load?await load(pin.path):await readFile(path.resolve(import.meta.dir,'../..',pin.path),'utf8');check(hash(text)===pin.sha256);validateM78ContinuationRestart(JSON.parse(text),input.gate.reviewedApplicationCommit,finishedAt)}
export async function verifyM78SourceGate(g:Gate){check(digest(REVIEWED_MIGRATION_SHA256)&&g.migrationSha256===REVIEWED_MIGRATION_SHA256);for(const [file,pin]of [['tools/staging/m78-continuation-plan.ts',g.recipeSha256],['tools/staging/check-m78-continuation.ts',g.harnessSha256],['packages/neuvetra-database/src/migrations/0021_scope1_inventory.sql',g.migrationSha256]])check(hash(await readFile(file!))===pin)}
export function validateM78Route(url:string,method:string,company:string,mode:Mode){
 const u=new URL(url),root='/workspace-api/workspace/'+company;check(!u.hash&&!u.username&&!u.password)
 if(u.origin===AUTH){check(method==='POST'&&(u.pathname==='/auth/v1/token'&&u.search==='?grant_type=password'||u.pathname==='/auth/v1/logout'&&u.search==='?scope=local'));return}
 check(u.origin===HOST&&!u.search&&['GET','POST'].includes(method))
 if(method==='GET'){check(['/ready','/workspace-api/config','/workspace-api/session',root].includes(u.pathname)||u.pathname.startsWith(root+'/'));return}
 check(mode==='exercise');check(u.pathname===root+'/process-screen'||new RegExp('^'+root+'/(corporate-inventories|stationary-natural-gas|mobile-diesel|stationary-diesel|controlled-fleet|stationary-equipment|fugitive-sources|fugitive-population|process-screen|scope1-inventory)/'+uuid+'/(versions|reviews|reports)$').test(u.pathname))
}
export function readM78ContinuationJournal(text:string|null,company:string):M78Event[]{
 if(text===null)return [];check(Buffer.byteLength(text)<=128_000_000&&text.endsWith('\n'));let previous:string|null=null
 return text.trimEnd().split('\n').map((line,i)=>{const e=JSON.parse(line)as M78Event,{sha256,...body}=e;check(Buffer.byteLength(line+'\n')<=m78JournalEventLimit(e.kind));check(e.sequence===i+1&&e.previousSha256===previous&&e.profile===PROFILE&&e.workspaceId===company&&['baseline','exercise','revisit'].includes(e.mode)&&new Date(e.createdAt).toISOString()===e.createdAt&&hash(canonical(body))===sha256);previous=sha256;return e})
}
export function cleanM78ContinuationJournal(events:M78Event[]){
 if(events.length)check(events[0]!.kind==='provenance')
 let attempt:M78Event|null=null,terminal=false,legacy=false;const names=new Set<string>(),intents=new Map<string,M78Event>(),outcomes=new Map<string,M78Event>(),verified=new Set<string>(),completed=new Set<string>(),auth=new Map<string,string>(),legacyAuth=new Map<number,{action:string;status:number|null}>()
 for(const e of events){
  if(e.kind==='provenance'){check(e.sequence===1&&attempt===null&&same(e.data.acceptedM77,M78_ACCEPTED_M77)&&same(e.data.acceptedM78Failure,M78_ACCEPTED_FAILURE));continue}
  if(e.kind==='attempt_started'){check(attempt===null&&e.mode===e.data.mode&&!completed.has(e.mode)&&(e.mode==='baseline'?completed.size===0:completed.has('baseline'))&&(e.mode!=='revisit'||completed.has('exercise')));attempt=e;terminal=false;legacy=false;intents.clear();outcomes.clear();verified.clear();auth.clear();legacyAuth.clear();continue}
  check(attempt&&e.mode===attempt.mode)
  if(e.kind==='post_intent'){check(!terminal&&e.mode==='exercise'&&!names.has(e.data.name)&&['manager1','manager2','member','outsider','signed_out'].includes(e.data.role)&&e.data.expected===201&&!e.data.name.endsWith('_write_refused')&&e.data.name!=='m78_initial_blocked_inventory'&&typeof e.data.route==='string');check(e.data.expected===201?['manager1','manager2'].includes(e.data.role):e.data.name==='m78_'+e.data.role+'_write_refused'&&['member','outsider','signed_out'].includes(e.data.role)&&e.data.expected===(e.data.role==='signed_out'?401:403)&&e.data.route==='/workspace-api/workspace/'+e.workspaceId+'/scope1-inventory');validateM78Route(HOST+e.data.route,'POST',e.workspaceId,e.mode);names.add(e.data.name);intents.set(e.data.name,e);continue}
  if(e.kind==='post_outcome'){const i=intents.get(e.data.name);check(i&&!outcomes.has(e.data.name)&&e.data.status===i.data.expected&&e.data.route===i.data.route&&e.data.role===i.data.role&&digest(e.data.responseSha256)&&Number.isSafeInteger(e.data.byteLength)&&e.data.byteLength>=0);outcomes.set(e.data.name,e);continue}
  if(e.kind==='post_verified'){const identity=e.data.verifiedIdentity;check(intents.get(e.data.name)?.data.expected===201&&identity&&typeof identity==='object'&&!Array.isArray(identity)&&new RegExp('^'+uuid+'$').test(identity.id)&&Object.entries(identity).every(([k,v])=>['id','companyId','streamId','inventoryId','worksheetId','rosterId','versionId','versionSha256','decisionSha256','reportSha256'].includes(k)&&(k.endsWith('Sha256')?digest(v):typeof v==='string'&&new RegExp('^'+uuid+'$').test(v)))&&(identity.companyId===undefined||identity.companyId===e.workspaceId));check(outcomes.has(e.data.name)&&!verified.has(e.data.name)&&e.data.responseSha256===outcomes.get(e.data.name)!.data.responseSha256);verified.add(e.data.name);continue}
  if(['baseline','exercise_complete','revisit_verified'].includes(e.kind)){check(!terminal&&e.kind===({baseline:'baseline',exercise:'exercise_complete',revisit:'revisit_verified'}as const)[e.mode]);terminal=true;continue}
  if(e.kind==='auth_intent'){check(['manager1','manager2','member','outsider'].includes(e.data.role)&&!auth.has(e.data.role));auth.set(e.data.role,'intent');continue}
  if(e.kind==='auth_outcome'){check(auth.get(e.data.role)==='intent'&&e.data.status===200&&e.data.tokenObserved===true&&e.data.subjectMatched===true);auth.set(e.data.role,'open');continue}
  if(e.kind==='logout_intent'){check(auth.get(e.data.role)==='open');auth.set(e.data.role,'closing');continue}
  if(e.kind==='logout_outcome'){check(auth.get(e.data.role)==='closing'&&e.data.status===204);auth.set(e.data.role,'closed');continue}
  if(e.kind==='legacy_auth_intent'){check(!terminal&&Number.isSafeInteger(e.data.requestId)&&e.data.requestId===legacyAuth.size+1&&['login','logout'].includes(e.data.action));legacyAuth.set(e.data.requestId,{action:e.data.action,status:null});continue}
  if(e.kind==='legacy_auth_outcome'){const intent=legacyAuth.get(e.data.requestId);check(intent&&intent.action===e.data.action&&intent.status===null&&e.data.status===(intent.action==='login'?200:204));intent.status=e.data.status;continue}
  if(e.kind==='legacy_read_verified'){check(!legacy&&legacyAuth.size===8&&[...legacyAuth.values()].filter(v=>v.action==='login'&&v.status===200).length===4&&[...legacyAuth.values()].filter(v=>v.action==='logout'&&v.status===204).length===4&&e.data.unchanged===true&&e.data.applicationPostRequests===0&&e.data.allCreatedAuthSessionsClosed===true);legacy=true;continue}
  if(e.kind==='attempt_finished'){check(terminal&&legacy&&auth.size===4&&[...auth.values()].every(s=>s==='closed')&&e.data.unknownAuthSessions===0&&e.data.attemptSequence===attempt.sequence&&e.data.status==='passed'&&e.data.allCreatedAuthSessionsClosed===true&&e.data.applicationPostRequests===intents.size&&intents.size===(e.mode==='exercise'?M78_EXPECTED_POSTS:0)&&[...intents].every(([name,i])=>outcomes.has(name)&&(i.data.expected!==201||verified.has(name))));if(e.mode==='exercise')check([...intents.values()].every(i=>i.data.expected===201)&&intents.size===37&&!intents.has('m78_initial_blocked_inventory')&&intents.values().next().value?.data.name==='m78_initial_unreviewed_report');completed.add(e.mode);attempt=null;continue}
  check(['actual_readiness','access_verified'].includes(e.kind))
 }
 check(attempt===null)
}
export function acceptedM77(text:string,company:string){check(hash(text)===M78_ACCEPTED_M77.journalSha256);const events=readM77Continuation(text,company);check(events.at(-1)?.sha256===M78_ACCEPTED_M77.headSha256&&events.some(e=>e.kind==='revisit_verified'));return events.find(e=>e.kind==='exercise_complete')!.data as {registers:any;downloads:any}}
/** Production lookup retains exact immutable predecessor hashes. Injection is for hermetic tests only. */
export const M78_ACCEPTED_FAILURE={journalSha256:'d3301eb226c0cae4428c1e20cde4e2afdcf572b622e96d690cc8c262d6e44058',headSha256:'8cac20e87d8d5c4dd1f5f0f4eb6eae9721b56aeb83ef2bda270855da6aea24fd',observationSha256:'995f91359f1b5ce38ad5b2f1324194c24c222a73ef2f2108944b6a4bf1797d67',independentActualReviewSha256:'3147cea316a075ad7e114052d007efeda5202462282b678175531d4a5c056d00'}as const
export async function readM78Prior(company:string){const prior=await readOriginalM78Prior(company),text=await readFile(path.resolve(import.meta.dir,'../../.superpowers/m78-hosted-journey.jsonl'),'utf8');check(hash(text)===M78_ACCEPTED_FAILURE.journalSha256);const original=readOriginalM78Journal(text,company),last=original.at(-1)!;check(original.length===72&&last.sha256===M78_ACCEPTED_FAILURE.headSha256&&last.data.status==='failed'&&last.data.allCreatedAuthSessionsClosed===true&&last.data.unknownAuthSessions===0&&last.data.applicationPostRequests===4);const raw=await readFile(path.resolve(import.meta.dir,'../../.superpowers/m78-timeout-observation.json'),'utf8'),reviewText=await readFile(path.resolve(import.meta.dir,'../../evaluations/research-qa/m78-timeout-actual-independent-result.json'),'utf8');check(hash(raw)===M78_ACCEPTED_FAILURE.observationSha256&&hash(reviewText)===M78_ACCEPTED_FAILURE.independentActualReviewSha256);const observation=JSON.parse(raw),review=JSON.parse(reviewText);check(observation.status==='m78_timed_out_save_confirmed_committed'&&observation.version.id===M78_COMMITTED_INITIAL.id&&observation.version.version_sha256===M78_COMMITTED_INITIAL.versionSha256&&review.status==='m78_independent_timed_out_save_commit_reconciled'&&review.observationSha256===hash(raw)&&review.exactIdempotencyActorRequestVersionHeadAuditLink===true);return {...prior,failed:original.find(e=>e.kind==='baseline')!.data,observation}}

/** Track every legacy Auth POST without storing request/response bodies or credentials. */
export async function readM78Legacy(input:M78JourneyInput,expected:any,network:(url:string,init?:RequestInit)=>Promise<Response>,append:(kind:string,data:any)=>Promise<void>,helper:typeof runM72Journey=runM72Journey){
 let legacy:any,requestId=0,journalHealthy=true
 const result=await helper({...input,mode:'baseline'},{load:async()=>null,save:async value=>{legacy=value},fetch:(async(url:any,init?:RequestInit)=>{
  check(!(String(url).startsWith(HOST)&&init?.method==='POST'));const action=String(url).startsWith(AUTH+'/auth/v1/')?(String(url).includes('/token?')?'login':'logout'):null;let id=0
  if(action){id=++requestId;try{await append('legacy_auth_intent',{requestId:id,action})}catch(e){journalHealthy=false;if(action==='login')throw e}}
  const r=await network(String(url),init)
  // Return a known login response even if audit persistence failed so the helper can close its token.
  if(action)try{await append('legacy_auth_outcome',{requestId:id,action,status:r.status})}catch{journalHealthy=false}
  if(String(url)===HOST+'/ready'){const body=await r.json()as any;check(body.schemaVersion===21&&body.status==='ready');return Response.json({...body,schemaVersion:14},{status:r.status,headers:r.headers})}return r
 })as typeof fetch})
 return {verified:result.status==='passed'&&result.allCreatedAuthSessionsClosed&&journalHealthy&&requestId===8&&result.applicationPostRequests===0&&same(legacy?.baseline??null,expected),allCreatedAuthSessionsClosed:result.allCreatedAuthSessionsClosed,baseline:legacy?.baseline}
}
export async function runM78Continuation(input:M78JourneyInput,deps:M78Dependencies={}){
 const company=input.roster.workspaceId,root='/workspace-api/workspace/'+company,events:M78Event[]=[],tokens=new Map<Role,string>(),transport=deps.fetch??globalThis.fetch
 let journalBytes=0,stage='preconditions',attempt:number|null=null,writes=0,requests=0,unknownSessions=0,closed=true,legacyClosed=true,failed=false,lastStatus:number|null=null
 const network=async(url:string,init:RequestInit={})=>{validateM78Route(url,init.method??'GET',company,input.mode);requests++;const response=await transport(url,{...init,redirect:'error',signal:AbortSignal.timeout(30000)});lastStatus=response.status;return response}
 const append=async(kind:string,data:any)=>{const body={sequence:events.length+1,previousSha256:events.at(-1)?.sha256??null,profile:PROFILE,workspaceId:company,mode:input.mode,kind,data,createdAt:new Date().toISOString()},e={...body,sha256:hash(canonical(body))},line=JSON.stringify(e)+'\n',size=Buffer.byteLength(line);check(size<=m78JournalEventLimit(kind)&&journalBytes+size<=128_000_000);await(deps.append??(async(line,exclusive)=>{const file=await open(JOURNAL,exclusive?'wx':'a',0o600);try{await file.writeFile(line);await file.sync()}finally{await file.close()}}))(line,events.length===0);journalBytes+=size;events.push(e)}
 const responseBytes=async(r:Response)=>{const bytes=new Uint8Array(await r.arrayBuffer());check(bytes.length<=10_000_000&&r.headers.get('cache-control')?.includes('no-store'));return bytes}
 const bytes=async(route:string,role:Role='manager1')=>{stage='read:'+route.slice(root.length);const response=await network(HOST+route,{headers:{origin:HOST,...(tokens.has(role)?{authorization:'Bearer '+tokens.get(role)}:{})}});check(response.status===200);return new TextDecoder('utf8',{fatal:true}).decode(await responseBytes(response))}
 const get=async(route:string,role:Role='manager1')=>parseM78Json(await bytes(route,role),10_000_000)
 const scope1=async()=>decodeScope1Register(await get(root+'/scope1-inventory'),company)
 const read=async()=>{const result:any={};for(const[family,base,decode]of [['corporate','corporate-inventories',decodeCorporateRegister],['gas','stationary-natural-gas',decodeGasRegister],['mobile','mobile-diesel',decodeMobileRegister],['fleet','controlled-fleet',decodeFleetRegister],['diesel','stationary-diesel',decodeGeneratorRegister],['equipment','stationary-equipment',decodeStationaryRegister],['fugitive','fugitive-sources',decodeFugitiveRegister]]as const)result[family]=await decode(await get(root+'/'+base),company);return result}
 const version=async(route:string,raw:any)=>{const family=route.slice(root.length+1).split('/')[0];if(['process-screen','scope1-inventory'].includes(family!))return decodeScope1Version(raw,company);const decode=({'corporate-inventories':decodeCorporateVersion,'stationary-natural-gas':decodeGasVersion,'mobile-diesel':decodeMobileVersion,'stationary-diesel':decodeGeneratorVersion,'controlled-fleet':decodeFleetVersion,'stationary-equipment':decodeStationaryVersion,'fugitive-sources':decodeFugitiveVersion,'fugitive-population':decodeFugitiveVersion}as Record<string,(v:any,c:string)=>any>)[family!];check(decode);return decode(raw,company)}
 const decodeOutcome=async(route:string,raw:any)=>{if(route.endsWith('/reports')){check(route.includes('/process-screen/')||route.includes('/scope1-inventory/'));return decodeScope1Report(raw,company)}if(route.endsWith('/reviews')){let retained:unknown;if(route.includes('/controlled-fleet/')||route.includes('/stationary-equipment/')){const family=route.includes('/controlled-fleet/')?'controlled-fleet':'stationary-equipment';const register=await (family==='controlled-fleet'?decodeFleetRegister:decodeStationaryRegister)(await get(root+'/'+family),company);check(route===root+'/'+family+'/'+register.rosterId+'/reviews');retained=register}else retained=await version(route,await get(route.replace(/\/reviews$/,'/versions/'+raw.versionId)));m78VerifiedReview(retained,raw);return raw}return version(route,raw)}
 const post=async(name:string,route:string,role:string,request:unknown,expected=201)=>{stage=name;check(expected===201&&name!=='m78_initial_blocked_inventory'&&(writes!==0||name==='m78_initial_unreviewed_report'));check(input.mode==='exercise'&&writes<M78_EXPECTED_POSTS&&!events.some(e=>e.kind==='post_intent'&&e.data.name===name)&&['manager1','manager2','member','outsider','signed_out'].includes(role));validateM78Route(HOST+route,'POST',company,input.mode)
  await append('post_intent',{name,route,role,expected,request});writes++
  const response=await network(HOST+route,{method:'POST',headers:{origin:HOST,'content-type':'application/json',...(tokens.has(role as Role)?{authorization:'Bearer '+tokens.get(role as Role)}:{})},body:JSON.stringify(request)}),rawBytes=await responseBytes(response)
  await append('post_outcome',{name,route,role,expected,status:response.status,responseSha256:hash(rawBytes),byteLength:rawBytes.length});check(response.status===expected)
  if(expected!==201)return undefined
  const decoded=await decodeOutcome(route,parseM78Json(new TextDecoder('utf8',{fatal:true}).decode(rawBytes),10_000_000));const identity=m78VerifiedIdentity(decoded);await append('post_verified',{name,responseSha256:hash(rawBytes),verifiedIdentity:identity});return decoded
 }
 const preserveBytes=(before:any,after:any)=>{for(const family of Object.keys(before))for(const[key,value]of Object.entries(before[family]))check(same(after[family]?.[key],value))}
 const verifyFugitiveReport=async(raw:any)=>{const r=await decodeFugitiveReport(raw,company),base=root+'/'+(r.family==='source'?'fugitive-sources':'fugitive-population')+'/'+r.streamId;check(same(r,await decodeFugitiveReport(await get(base+'/reports/'+r.id),company)));const s=parseM78Json(r.snapshotJson,10_000_000)as any;for(const v of [s.version,...(s.proof?.workpaperVersions??[])]){const exact=await decodeFugitiveVersion(await get(root+'/'+(v.family==='source'?'fugitive-sources':'fugitive-population')+'/'+v.streamId+'/versions/'+v.id),company);check(same(core(exact),core(v))&&(!v.review||same(exact.review,v.review)))}return r}
 // Existing M77 exact-download mechanics retained locally; no old journey is invoked or replayed.
 const downloads=async(reg:any):Promise<any>=>{const out:any={};const retain=async(family:string,key:string,route:string,expected:string)=>{const text=await bytes(route,'member');check(text===expected);(out[family]??={})[key]={sha256:hash(text),byteLength:Buffer.byteLength(text)}}
  for(const v of reg.corporate.versions)await retain('corporate',v.id,root+'/corporate-inventories/'+v.inventoryId+'/versions/'+v.id+'/coverage-export',m71Export(v))
  for(const [family,base,exporter]of [['gas','stationary-natural-gas',m73Export],['mobile','mobile-diesel',m74Export],['diesel','stationary-diesel',(v:any)=>canonical(core(v))]]as const)for(const w of reg[family].worksheets){for(const v of w.versions){await retain(family,'version_'+v.id,root+'/'+base+'/'+w.worksheetId+'/versions/'+v.id+'/calculation-export',exporter(v));for(const[k,s]of family==='mobile'?[['fuel',v.fuelStatement],['mileage',v.mileageStatement]]:[['statement',v.statement]])if(s)await retain(family,k+'_'+s.id,root+'/'+base+'/'+w.worksheetId+'/statements/'+s.id+'/download',s.text)}for(const r of w.reports){await retain(family,'report_'+r.id,root+'/'+base+'/'+w.worksheetId+'/reports/'+r.id+'/download',r.html);if(family==='diesel')await retain(family,'snapshot_'+r.id,root+'/'+base+'/'+w.worksheetId+'/reports/'+r.id+'/snapshot',r.snapshotJson)}}
  for(const[family,base,exporter]of [['fleet','controlled-fleet',m75Export],['equipment','stationary-equipment',m76Export]]as const){for(const v of reg[family].versions){await retain(family,'version_'+v.id,root+'/'+base+'/'+v.rosterId+'/versions/'+v.id+'/roster-export',exporter(v));if(v.statement)await retain(family,'statement_'+v.statement.id,root+'/'+base+'/'+v.rosterId+'/statements/'+v.statement.id+'/download',v.statement.text)}for(const r of reg[family].reports){const baseRoute=root+'/'+base+'/'+r.rosterId+'/reports/'+r.id,html=await bytes(baseRoute+'/download','member'),snapshotJson=await bytes(baseRoute+'/snapshot','member');check(hash(html)===r.htmlSha256&&Buffer.byteLength(html)===r.htmlByteLength&&hash(snapshotJson)===r.snapshotSha256);const snapshot=parseM78Json(snapshotJson,10_000_000),render=family==='fleet'?(await import('../../packages/neuvetra-database/src/m75-report')).m75RenderReport:(await import('../../packages/neuvetra-database/src/m76-report')).m76RenderReport;check(canonical(snapshot)===snapshotJson&&render(snapshot as any)===html);(out[family]??={})['report_'+r.id]={sha256:hash(html),byteLength:Buffer.byteLength(html)};out[family]['snapshot_'+r.id]={sha256:hash(snapshotJson),byteLength:Buffer.byteLength(snapshotJson)};out[family]['proof_'+r.id]=hash(canonical(await get(baseRoute+'/proof','member')))}}
  for(const w of [...reg.fugitive.worksheets,reg.fugitive.population]){for(const v of w.versions){const base=root+'/'+(v.family==='source'?'fugitive-sources':'fugitive-population')+'/'+v.streamId;await retain('fugitive','version_'+v.id,base+'/versions/'+v.id+'/calculation-export',m77Export(v));for(const s of v.statements)await retain('fugitive','statement_'+s.id,base+'/statements/'+s.id+'/download',s.text)}for(const raw of w.reports){const r=await verifyFugitiveReport(raw),base=root+'/'+(r.family==='source'?'fugitive-sources':'fugitive-population')+'/'+r.streamId+'/reports/'+r.id;await retain('fugitive','report_'+r.id,base+'/download',r.html);await retain('fugitive','snapshot_'+r.id,base+'/snapshot',r.snapshotJson)}}return out
 }
 const m78Downloads=async(reg:Awaited<ReturnType<typeof scope1>>)=>{const out:Record<string,{sha256:string;byteLength:number}>={};const retain=async(key:string,route:string,expected:string)=>{const value=await bytes(route,'member');check(value===expected);out[key]={sha256:hash(value),byteLength:Buffer.byteLength(value)}};for(const [family,stream]of [['process-screen',reg.process],['scope1-inventory',reg.inventory]]as const){for(const v of stream.versions){const base=root+'/'+family+'/'+v.streamId,exact=await decodeScope1Version(await get(base+'/versions/'+v.id,'member'),company);check(same(exact.version,v));await retain('version_'+v.id,base+'/versions/'+v.id+'/inventory-export',canonical(core(v)));check(same(await get(base+'/versions/'+v.id+'/proof','member'),exact.proof));for(const s of v.statements)await retain('statement_'+s.id,base+'/statements/'+s.id+'/download',s.text)}for(const meta of stream.reports){const base=root+'/'+family+'/'+meta.streamId+'/reports/'+meta.id,r=await decodeScope1Report(await get(base,'member'),company);await retain('html_'+r.id,base+'/download',r.html);await retain('snapshot_'+r.id,base+'/snapshot',r.snapshotJson);check(same(await get(base+'/proof','member'),(parseM78Json(r.snapshotJson)as any).proof))}}return out}
 const legacyRead=async(expected:any)=>{stage='read_only_legacy';legacyClosed=false;const result=await readM78Legacy(input,expected,network,append,deps.legacy);legacyClosed=result.allCreatedAuthSessionsClosed;check(result.verified);await append('legacy_read_verified',{unchanged:true,applicationPostRequests:0,allCreatedAuthSessionsClosed:legacyClosed,adapter:'M72 reader receives14 after actual21 readiness verified'});return result.baseline}
 try{
  events.push(...readM78ContinuationJournal(deps.load?await deps.load():await Bun.file(JOURNAL).exists()?await Bun.file(JOURNAL).text():null,company));cleanM78ContinuationJournal(events);journalBytes=events.reduce((n,e)=>n+Buffer.byteLength(JSON.stringify(e)+'\n'),0);const baseline=events.find(e=>e.kind==='baseline'),complete=events.find(e=>e.kind==='exercise_complete');check(input.mode==='baseline'?events.length===0:input.mode==='exercise'?!!baseline&&!complete:!!complete&&!events.some(e=>e.kind==='revisit_verified'))
  check(events.filter(e=>e.kind==='attempt_started').every(e=>same(e.data.gate,input.gate)));await(deps.verifyGate??verifyM78SourceGate)(input.gate);if(input.mode==='revisit')await readM78ContinuationRestart(input,events.find(e=>e.mode==='exercise'&&e.kind==='attempt_finished')!.createdAt)
  const {previous,old,failed:original,observation}=await(deps.readPrior??readM78Prior)(company)
  if(!events.length)await append('provenance',{acceptedM77:M78_ACCEPTED_M77,acceptedM76:M76_PIN,originalJournalsReplayed:false,acceptedM78Failure:M78_ACCEPTED_FAILURE})
  await append('attempt_started',{mode:input.mode,gate:input.gate});attempt=events.at(-1)!.sequence
  stage='readiness';const ready=await network(HOST+'/ready'),readyBody=await ready.json()as any;check(ready.status===200&&readyBody.schemaVersion===21&&readyBody.status==='ready'&&readyBody.profile==='neuvetra.private-synthetic-staging.v1'&&readyBody.legacyContainmentVerified===true);await append('actual_readiness',{schemaVersion:21,migrationSha256:input.gate.migrationSha256,sourceGate:input.gate.independentReviewSha256,applicationCommitAttestation:input.gate.reviewedApplicationCommit})
  const config=await get('/workspace-api/config','signed_out')as any;check(config.profile==='neuvetra.private-synthetic-staging.v1'&&config.supabaseUrl===AUTH&&config.anonKey===input.env.SUPABASE_ANON_KEY)
  for(const a of input.accounts){stage='sign_in_'+a.role;await append('auth_intent',{role:a.role});unknownSessions++;const r=await network(AUTH+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:input.env.SUPABASE_ANON_KEY,'content-type':'application/json'},body:JSON.stringify({email:a.email,password:a.password})}),body=await r.json()as any;if(typeof body.access_token==='string'&&body.access_token.length>0&&body.access_token.length<=8192){tokens.set(a.role,body.access_token);unknownSessions--}await append('auth_outcome',{role:a.role,status:r.status,tokenObserved:tokens.has(a.role),subjectMatched:body.user?.id===a.id});check(r.status===200&&body.user?.id===a.id&&tokens.has(a.role))}
  for(const role of ['manager1','manager2','member']as const){const s=await get('/workspace-api/session',role)as any;check(s.user.id===input.accounts.find(a=>a.role===role)!.id&&s.access.workspaceId===company&&(role==='member'?s.access.role==='member':['owner','admin'].includes(s.access.role)))}
  for(const family of ['process-screen','scope1-inventory'])for(const [role,status]of [['outsider',403],['signed_out',401]]as const){const r=await network(HOST+root+'/'+family,{headers:{origin:HOST,...(tokens.has(role)?{authorization:'Bearer '+tokens.get(role)}:{})}});check(r.status===status&&r.headers.get('cache-control')?.includes('no-store'));await r.body?.cancel();await append('access_verified',{family,role,status})}
  const current=await scope1();if(input.mode!=='revisit'){assertM78ContinuationBaseline(current);check(same(current.inventory.versions[0],observation.version.payload))}check(same(await decodeScope1Register(await get(root+'/scope1-inventory','member'),company),current))
  if(input.mode==='exercise'){
   check(same(current,baseline!.data.scope1));assertM78ContinuationBaseline(current)
   await(deps.exercise??continueM78)({root,accounts:input.accounts,scope1,post});check(writes===M78_EXPECTED_POSTS)
  }
  const result=input.mode==='exercise'?await scope1():current,registers=await read(),downloaded=await downloads(registers),m78bytes=await m78Downloads(result),legacy=await legacyRead(old.legacy);preservesM77History(previous.registers,registers);preserveBytes(previous.downloads,downloaded);preservesM77History(original.registers,registers);preserveBytes(original.downloads,downloaded);check(same(legacy,original.legacy))
  if(input.mode==='baseline'){assertM78ContinuationBaseline(current);await append('baseline',{scope1:result,registers,downloads:downloaded,m78bytes,legacy})}
  else if(input.mode==='exercise'){preservesM77History(baseline!.data.registers,registers);preserveBytes(baseline!.data.downloads,downloaded);preserveBytes(baseline!.data.m78bytes,m78bytes);check(same(result.inventory.versions[0],baseline!.data.scope1.inventory.versions[0]));check(result.process.versions.length===1&&result.inventory.versions.length===2&&result.process.reports.length===2&&result.inventory.reports.length===3&&result.reconciliation.sourceUnion.length===10&&result.reconciliation.totals?.company.kgCo2eExact==='126850.17632025'&&result.reconciliation.status==='reconciled_bounded_synthetic'&&result.process.versions.at(-1)?.review?.decision==='accepted_bounded_process_screen'&&result.inventory.versions.at(-1)?.review?.decision==='accepted_bounded_inventory');await append('exercise_complete',{scope1:result,registers,downloads:downloaded,m78bytes,legacy,applicationPostRequests:writes,scope1ReleaseReadiness:'incomplete'})}
  else{check(same(result,complete!.data.scope1)&&same(registers,complete!.data.registers)&&same(downloaded,complete!.data.downloads)&&same(m78bytes,complete!.data.m78bytes)&&same(legacy,complete!.data.legacy));await append('revisit_verified',{exerciseSha256:complete!.sha256,applicationPostRequests:0,exactRetainedState:true})}
 }catch{failed=true}
 finally{for(const[role,token]of tokens){try{await append('logout_intent',{role})}catch{failed=true}try{const r=await network(AUTH+'/auth/v1/logout?scope=local',{method:'POST',headers:{apikey:input.env.SUPABASE_ANON_KEY,authorization:'Bearer '+token}});await r.body?.cancel();if(r.status!==204)closed=false;try{await append('logout_outcome',{role,status:r.status})}catch{failed=true}}catch{closed=false}}tokens.clear()}
 const allCreatedAuthSessionsClosed=closed&&legacyClosed&&unknownSessions===0;failed||=!allCreatedAuthSessionsClosed
 if(attempt!==null)try{await append('attempt_finished',{attemptSequence:attempt,status:failed?'failed':'passed',stage,applicationPostRequests:writes,allCreatedAuthSessionsClosed,requests,lastStatus,unknownAuthSessions:unknownSessions})}catch{failed=true;stage='journal_append'}
 return {status:failed?'failed':'passed',mode:input.mode,stage,applicationPostRequests:writes,requests,lastStatus,allCreatedAuthSessionsClosed,receiptSha256:events.at(-1)?.sha256??null}
}
if(import.meta.main){let lock:Awaited<ReturnType<typeof open>>|undefined;try{const text=await Bun.stdin.text();check(text.length<=128000);const input=parseM78ContinuationInput(JSON.parse(text));lock=await open(JOURNAL+'.lock','wx',0o600);await lock.writeFile('{"profile":"m78-exclusive-continuation-v1"}\n');await lock.sync();const result=await runM78Continuation(input);console.log(JSON.stringify(result));if(result.status!=='passed')process.exitCode=1}catch{console.log(JSON.stringify({status:'failed',stage:'input_or_exclusive_lock',journalsReset:false}));process.exitCode=1}finally{if(lock){await lock.close();await unlink(JOURNAL+'.lock')}}}
