import {test,expect} from 'bun:test'
import {parseM73JourneyInput,readM73Journal,runM73Journey,validateM73JourneyRoute} from './check-m73-hosted'
import {createM71Seed,validateM71Snapshot,deriveM71Findings,m71VersionHashPayload,m71Hash,m71Export,M71_PROFILE,M71_LIMITATIONS,type M71Version} from '../../packages/neuvetra-database/src/index'
const HOST='https://www.neuvetra.ai',AUTH='https://icockcoguyadhryzydvl.supabase.co',company='73000000-0000-4000-8000-000000000001'
const input=(mode='baseline')=>({mode,env:{SUPABASE_URL:AUTH,SUPABASE_ANON_KEY:'sb_publishable_'+'a'.repeat(30)},roster:{workspaceId:company},accounts:['manager1','manager2','member','outsider'].map((role,i)=>({role,id:`73000000-0000-4000-8000-00000000001${i}`,email:role+'@synthetic.invalid',password:'fictional-local-only'}))})
function fixture(){const snapshot=validateM71Snapshot(createM71Seed()),version={id:'73000000-0000-4000-8000-000000000020',inventoryId:'73000000-0000-4000-8000-000000000021',companyId:company,version:1,previousVersionId:null,previousVersionSha256:null,createdBy:input().accounts[0]!.id,createdAt:'2026-09-15T12:00:00.000Z',contributorIds:[input().accounts[0]!.id],correctionReason:null,snapshot,contentSha256:m71Hash(snapshot),versionSha256:'',findings:deriveM71Findings(snapshot),synthetic:true,corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none',emissionsTotals:null,review:null} as M71Version;version.versionSha256=m71Hash(m71VersionHashPayload(version));const corporate={profile:M71_PROFILE,companyId:company,inventoryId:version.inventoryId,headVersionId:version.id,versions:[version],limitations:[...M71_LIMITATIONS]},text=m71Export(version),exports={[version.id]:{sha256:new Bun.CryptoHasher('sha256').update(text).digest('hex'),byteLength:new TextEncoder().encode(text).length}},legacy={records:{prior:'a'.repeat(64)},downloads:{prior:{sha256:'b'.repeat(64),byteLength:12}}};return {corporate,exports,text,legacy,previous:{host:HOST,workspaceId:company,baseline:legacy,attempts:[{status:'passed',corporate,exports}]}}}
function harness(){const f=fixture();let journal:string|null=null,postFailure=false,schema=15,logoutFailure=false,signInFailure=false;const calls:{url:string;method:string}[]=[];const dependencies={load:async()=>journal,append:async(line:string,exclusive:boolean)=>{expect(exclusive).toBe(journal===null);journal=(journal??'')+line},loadPrevious:async()=>f.previous,legacy:async(_input:any,deps:any)=>{const r=await deps.fetch(HOST+'/ready',{method:'GET'});expect((await r.json()).schemaVersion).toBe(14);await deps.save({baseline:f.legacy});return {status:'passed',allCreatedAuthSessionsClosed:true,applicationPostRequests:0}},fetch:async(url:any,init:any={})=>{const target=String(url),method=init.method??'GET';calls.push({url:target,method});const json=(v:any,status=200)=>Response.json(v,{status,headers:{'cache-control':'no-store'}});if(target===HOST+'/ready')return json({status:'ready',profile:'neuvetra.private-synthetic-staging.v1',legacyContainmentVerified:true,schemaVersion:schema});if(target.startsWith(AUTH+'/auth/v1/token')){if(signInFailure)throw Error('secret should never appear');const account=input().accounts.find(a=>a.email===JSON.parse(init.body).email)!;return json({access_token:'synthetic-token-'+account.role,user:{id:account.id}})}if(target.startsWith(AUTH+'/auth/v1/logout'))return new Response(null,{status:logoutFailure?500:204});if(method==='POST'&&postFailure)throw Error('uncertain write');if(target.endsWith('/corporate-inventories'))return json(f.corporate);if(target.endsWith('/coverage-export'))return new Response(f.text,{headers:{'cache-control':'no-store'}});throw Error('Unexpected offline route')}};return {dependencies:dependencies as any,calls,get journal(){return journal},set journal(v:string|null){journal=v},set schema(v:number){schema=v},set postFailure(v:boolean){postFailure=v},set logoutFailure(v:boolean){logoutFailure=v},set signInFailure(v:boolean){signInFailure=v}}}
test('M73 stdin accepts only pinned project, accounts and modes',()=>{expect(parseM73JourneyInput(input()).mode).toBe('baseline');for(const change of [{mode:'deploy'},{env:{SUPABASE_URL:'https://evil.invalid',SUPABASE_ANON_KEY:'x'}},{roster:{workspaceId:'../escape'}},{accounts:[]}])expect(()=>parseM73JourneyInput({...input(),...change})).toThrow()})
test('M73 route boundary refuses external hosts, overrides and nonworkflow writes',()=>{validateM73JourneyRoute(HOST+`/workspace-api/workspace/${company}/stationary-natural-gas`,'POST',company);for(const [url,method]of [['https://evil.invalid/ready','GET'],[HOST+'/ready?override=1','GET'],[HOST+`/workspace-api/workspace/${company}/members`,'POST'],[AUTH+'/auth/v1/admin/users','POST'],[HOST+'/workspace-api/workspace/other/corporate-inventories','GET']])expect(()=>validateM73JourneyRoute(url!,method!,company)).toThrow()})
test('M73 baseline is read only, closes four sessions and retains exact corporate exports',async()=>{const h=harness(),r=await runM73Journey(parseM73JourneyInput(input()),h.dependencies);expect(r.status).toBe('passed');expect(r.applicationPostRequests).toBe(0);expect(r.allCreatedAuthSessionsClosed).toBe(true);expect(h.calls.filter(c=>c.url.startsWith(HOST)&&c.method==='POST')).toHaveLength(0);expect(h.calls.filter(c=>c.url.includes('/logout'))).toHaveLength(4);const events=readM73Journal(h.journal,company);expect(events.find(e=>e.kind==='actual_readiness')?.data.schemaVersion).toBe(15);expect(events.find(e=>e.kind==='baseline')?.data.exports).toEqual(fixture().exports);expect(h.journal).not.toContain('synthetic-token');expect(h.journal).not.toContain('fictional-local-only')})
test('M73 uncertain source POST is durably marked and refuses resume before network',async()=>{const h=harness();expect((await runM73Journey(parseM73JourneyInput(input()),h.dependencies)).status).toBe('passed');h.schema=16;h.postFailure=true;const first=await runM73Journey(parseM73JourneyInput(input('exercise')),h.dependencies);expect(first.status).toBe('failed');expect(first.applicationPostRequests).toBe(1);expect(first.allCreatedAuthSessionsClosed).toBe(true);expect(readM73Journal(h.journal,company).some(e=>e.kind==='post_intent'&&e.data.name==='m71_add_source')).toBe(true);const count=h.calls.length;const retry=await runM73Journey(parseM73JourneyInput(input('exercise')),h.dependencies);expect(retry.stage).toBe('resume_preconditions');expect(retry.applicationPostRequests).toBe(0);expect(h.calls.length).toBe(count)})
test('M73 corrupted/truncated journal is not rewritten and does not authenticate',async()=>{const h=harness();h.journal='{"broken":true}';const original=h.journal;expect((await runM73Journey(parseM73JourneyInput(input()),h.dependencies)).status).toBe('failed');expect(h.journal).toBe(original);expect(h.calls).toHaveLength(0)})
test('M73 logout failures are recorded and prevent further writes',async()=>{const h=harness();h.logoutFailure=true;const r=await runM73Journey(parseM73JourneyInput(input()),h.dependencies);expect(r.status).toBe('failed');expect(r.allCreatedAuthSessionsClosed).toBe(false);expect(h.calls.filter(c=>c.url.includes('/logout'))).toHaveLength(4);h.schema=16;const count=h.calls.length;expect((await runM73Journey(parseM73JourneyInput(input('exercise')),h.dependencies)).status).toBe('failed');expect(h.calls.length).toBe(count)})
test('M73 an unaccounted sign-in fails closed without claiming cleanup',async()=>{const h=harness();h.signInFailure=true;const r=await runM73Journey(parseM73JourneyInput(input()),h.dependencies);expect(r.status).toBe('failed');expect(r.allCreatedAuthSessionsClosed).toBe(false);expect(JSON.stringify(r)).not.toContain('secret')})

test('M73 crash before final cleanup receipt refuses all subsequent network',async()=>{const h=harness();await runM73Journey(parseM73JourneyInput(input()),h.dependencies);const lines=h.journal!.trimEnd().split('\n');lines.pop();h.journal=lines.join('\n')+'\n';const count=h.calls.length;expect((await runM73Journey(parseM73JourneyInput(input('exercise')),h.dependencies)).stage).toBe('resume_preconditions');expect(h.calls.length).toBe(count)})
import {m73Activity,validateM73Save,m73StatementText,m73Hash,m73InputHashPayload,m73ContentPayload,m73VersionHashPayload,deriveM73Findings,M73_PROFILE,M73_LIMITATIONS,m73RenderReport,m73ReportSnapshot,m73ReportHashPayload,m73ReviewHashPayload,m73SourceChoices,m73CanonicalJson,m73Export} from '../../packages/neuvetra-database/src/index'
import {createM73Authority} from '../../apps/site-api/src/calculation/m73-authority'
test('M73 full offline exercise/revisit preserves original artifacts and performs each mutation once',async()=>{
 const h=harness(),f=fixture(),baseFetch=h.dependencies.fetch;let corporate=structuredClone(f.corporate),versions:any[]=[],reports:any[]=[],schema=15;const authority=createM73Authority(),flags={synthetic:true,scope1Completeness:'incomplete',corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none'},root=HOST+`/workspace-api/workspace/${company}`,gasRoot=root+'/stationary-natural-gas';let appPosts=0,failFinalReadOnce=true
 const bytesHash=(text:string)=>new Bun.CryptoHasher('sha256').update(text).digest('hex'),now=()=>new Date().toISOString(),json=(v:any,status=200)=>Response.json(v,{status,headers:{'cache-control':'no-store'}})
 const reg=()=>({profile:M73_PROFILE,companyId:company,coverageHeadVersionId:corporate.headVersionId,worksheets:versions.length?[{profile:M73_PROFILE,companyId:company,worksheetId:versions[0].worksheetId,sourceId:versions[0].activity.binding.sourceId,headVersionId:versions.at(-1).id,versions,reports,findings:[],limitations:[...M73_LIMITATIONS],...flags}]:[],sources:m73SourceChoices(corporate.versions.at(-1)!),coverageFindings:corporate.versions.at(-1)!.findings,limitations:[...M73_LIMITATIONS],...flags})
 h.dependencies.fetch=async(url:any,init:any={})=>{const u=String(url),method=init.method??'GET';if(u===HOST+'/ready'){if(schema===16&&versions.length===2&&failFinalReadOnce){failFinalReadOnce=false;return json({error:'temporary read failure'},503)}return json({status:'ready',profile:'neuvetra.private-synthetic-staging.v1',legacyContainmentVerified:true,schemaVersion:schema})}if(!u.startsWith(root))return baseFetch(url,init)
  if(method==='GET'){if(u===root+'/corporate-inventories')return json(corporate);if(u.endsWith('/coverage-export')){const v=corporate.versions.find(v=>u.includes(v.id))!;return new Response(m71Export(v),{headers:{'cache-control':'no-store'}})}if(u===gasRoot)return json(reg());if(u.endsWith('/calculation-export')){const v=versions.find(v=>u.includes(v.id))!;return new Response(m73Export(v),{headers:{'cache-control':'no-store'}})}if(u.includes('/statements/')){const v=versions.find(v=>u.includes(v.statement.id))!;return new Response(v.statement.text,{headers:{'cache-control':'no-store'}})}if(u.includes('/reports/')){const r=reports.find(r=>u.includes(r.id))!;return new Response(r.html,{headers:{'cache-control':'no-store'}})}throw Error('Unrecognized read')}
  appPosts++;const body=JSON.parse(init.body),role=String(init.headers.authorization??'').replace('Bearer synthetic-token-','');if(!role)return json({error:'signed out'},401);if(role==='member'||role==='outsider')return json({error:'forbidden',privateDetail:'HJ_F01_PRIVATE_403_DIAGNOSTIC'},403)
  if(u.includes('/corporate-inventories/')){const prior=corporate.versions.at(-1)!,snapshot=validateM71Snapshot(body.snapshot,prior.snapshot),v={...prior,id:crypto.randomUUID(),version:prior.version+1,previousVersionId:prior.id,previousVersionSha256:prior.versionSha256,createdAt:now(),correctionReason:body.correctionReason,snapshot,findings:deriveM71Findings(snapshot),contentSha256:m71Hash(snapshot),versionSha256:''};v.versionSha256=m71Hash(m71VersionHashPayload(v));corporate.versions.push(v);corporate.headVersionId=v.id;return json(v,201)}
  if(u.endsWith('/reviews')){if(role==='manager1')return json({error:'contributor'},403);const v=versions.find(v=>v.id===body.versionId),r={id:crypto.randomUUID(),versionId:v.id,versionSha256:v.versionSha256,decision:body.decision,note:body.note,acknowledgedLimitations:body.acknowledgedLimitations,reviewerId:input().accounts[1]!.id,reviewedAt:now(),decisionSha256:''};r.decisionSha256=m73Hash(m73ReviewHashPayload(company,r));v.review=r;return json(r,201)}
  if(u.endsWith('/reports')){const v=versions.find(v=>v.id===body.versionId),snapshot=m73ReportSnapshot(v,v.review),snapshotJson=m73CanonicalJson(snapshot),html=m73RenderReport(snapshot),r:any={id:crypto.randomUUID(),companyId:company,worksheetId:v.worksheetId,versionId:v.id,versionSha256:v.versionSha256,decisionId:v.review?.id??null,decisionSha256:v.review?.decisionSha256??null,createdBy:input().accounts[0]!.id,createdAt:now(),rendererVersion:'m73-source-report-v1',html,htmlSha256:bytesHash(html),htmlByteLength:new TextEncoder().encode(html).length,snapshotJson,snapshotSha256:bytesHash(snapshotJson),reportSha256:''};r.reportSha256=m73Hash(m73ReportHashPayload(r));reports.push(r);return json(r,201)}
  const activity=m73Activity(validateM73Save(body)),coverageVersion=corporate.versions.at(-1)!,text=m73StatementText(activity,coverageVersion),statementId=crypto.randomUUID(),statement={id:statementId,profile:'m73-synthetic-gas-statement-v1',input:activity.statement,locator:`m73-statement:${statementId}:annual-activity`,text,sha256:bytesHash(text),byteLength:new TextEncoder().encode(text).length},prior=versions.at(-1),calculation=await authority.calculate({binding:activity.binding,period:activity.period,fuel:activity.fuel,heatBasis:activity.heatBasis,unit:activity.unit,quantityMmbtu:activity.quantityMmbtu!,statementSha256:statement.sha256}),v:any={id:crypto.randomUUID(),companyId:company,worksheetId:prior?.worksheetId??crypto.randomUUID(),version:versions.length+1,previousVersionId:prior?.id??null,previousVersionSha256:prior?.versionSha256??null,createdBy:input().accounts[0]!.id,createdAt:now(),contributorIds:[input().accounts[0]!.id],correctionReason:body.correctionReason,activity,coverageVersion,statement,calculation,findings:deriveM73Findings(activity),inputSha256:'',contentSha256:'',versionSha256:'',...flags,review:null};v.inputSha256=m73Hash(m73InputHashPayload(v));v.contentSha256=m73Hash(m73ContentPayload(v));v.versionSha256=m73Hash(m73VersionHashPayload(v));versions.push(v);return json(v,201)
 }
 expect((await runM73Journey(parseM73JourneyInput(input()),h.dependencies)).status).toBe('passed');schema=16;const partial=await runM73Journey(parseM73JourneyInput(input('exercise')),h.dependencies);expect(partial.status).toBe('failed');expect(partial.allCreatedAuthSessionsClosed).toBe(true);const exercise=await runM73Journey(parseM73JourneyInput(input('exercise')),h.dependencies);expect(exercise.applicationPostRequests).toBe(0);expect(exercise.status,exercise.stage).toBe('passed');expect(exercise.allCreatedAuthSessionsClosed).toBe(true);expect(appPosts).toBe(11);expect(versions).toHaveLength(2);expect(reports).toHaveLength(2);expect(versions[0].review).not.toBeNull();expect(versions[1].review).toBeNull();const priorPosts=appPosts;const revisit=await runM73Journey(parseM73JourneyInput(input('revisit')),h.dependencies);expect(revisit.status,revisit.stage).toBe('passed');expect(appPosts).toBe(priorPosts);expect(h.journal).not.toContain('HJ_F01_PRIVATE_403_DIAGNOSTIC');const refusal=readM73Journal(h.journal,company).find(e=>e.kind==='post_outcome'&&e.data.status===403)!;expect(refusal.data.response).toBeUndefined();expect(refusal.data.responseObservation.sha256).toMatch(/^[0-9a-f]{64}$/);expect(refusal.data.responseObservation.byteLength).toBeGreaterThan(0)
},20000)

test('HJ-F01 unexpected201 private fields never reach durable journal and leave an unresolved intent',async()=>{const h=harness();expect((await runM73Journey(parseM73JourneyInput(input()),h.dependencies)).status).toBe('passed');h.schema=16;const original=h.dependencies.fetch;h.dependencies.fetch=async(url:any,init:any={})=>init.method==='POST'&&String(url).startsWith(HOST)?Response.json({...fixture().corporate.versions[0],access_token:'HJ_F01_PRIVATE_201_TOKEN'},{status:201,headers:{'cache-control':'no-store'}}):original(url,init);const failed=await runM73Journey(parseM73JourneyInput(input('exercise')),h.dependencies);expect(failed.status).toBe('failed');expect(failed.allCreatedAuthSessionsClosed).toBe(true);expect(h.journal).not.toContain('HJ_F01_PRIVATE_201_TOKEN');expect(h.journal).not.toContain('access_token');const events=readM73Journal(h.journal,company);expect(events.some(e=>e.kind==='post_intent'&&e.data.name==='m71_add_source')).toBe(true);expect(events.some(e=>e.kind==='post_outcome'&&e.data.name==='m71_add_source')).toBe(false);expect((await runM73Journey(parseM73JourneyInput(input('exercise')),h.dependencies)).stage).toBe('resume_preconditions')})
test('HJ-F01 unexpected403 diagnostics are reduced to hash and length then fail closed',async()=>{const h=harness();await runM73Journey(parseM73JourneyInput(input()),h.dependencies);h.schema=16;const original=h.dependencies.fetch;h.dependencies.fetch=async(url:any,init:any={})=>init.method==='POST'&&String(url).startsWith(HOST)?new Response('HJ_F01_PRIVATE_UNEXPECTED_403_TEXT',{status:403,headers:{'cache-control':'no-store'}}):original(url,init);const failed=await runM73Journey(parseM73JourneyInput(input('exercise')),h.dependencies);expect(failed.status).toBe('failed');expect(h.journal).not.toContain('HJ_F01_PRIVATE_UNEXPECTED_403_TEXT');const event=readM73Journal(h.journal,company).find(e=>e.kind==='post_outcome')!;expect(event.data.status).toBe(403);expect(event.data.response).toBeUndefined();expect(event.data.responseObservation.byteLength).toBe(34);expect((await runM73Journey(parseM73JourneyInput(input('exercise')),h.dependencies)).stage).toBe('resume_preconditions')})
