import {test,expect} from 'bun:test'
import {m78VerifiedIdentity,m78VerifiedReview} from './check-m78-hosted'
import {m78JournalEventLimit,readM78Legacy,acceptedM77,parseM78JourneyInput,readM78Journal,cleanM78Journal,validateM78Route,runM78Journey,M78_ACCEPTED_M77,M78_EXPECTED_POSTS,type M78Event} from './check-m78-hosted'
import {m78CanonicalJson as canonical} from '../../packages/neuvetra-database/src/m78-validation'
const HOST='https://www.neuvetra.ai',AUTH='https://icockcoguyadhryzydvl.supabase.co',company='8b90c706-1710-494d-b12d-02eef88eacb7',digest='a'.repeat(64)
const input=()=>({mode:'baseline',acceptedM77:M78_ACCEPTED_M77,gate:{status:'m78_hosted_candidate_reviewed',migrationSha256:digest,recipeSha256:digest,harnessSha256:digest,independentReviewSha256:digest,operatorRecoveryReceiptSha256:digest,reviewedApplicationCommit:'b'.repeat(40),expectedApplicationPosts:41},env:{SUPABASE_URL:AUTH,SUPABASE_ANON_KEY:'sb_publishable_'+'a'.repeat(30)},roster:{workspaceId:company},accounts:['manager1','manager2','member','outsider'].map((role,i)=>({role,id:`78000000-0000-4000-8000-00000000000${i}`,email:role+'@synthetic.invalid',password:'synthetic-private-marker'}))})
const sha=(s:string)=>new Bun.CryptoHasher('sha256').update(s).digest('hex')
test('verified identity preserves flat versions, envelope versions and review/report records',()=>{
 for(const stream of ['inventoryId','worksheetId','rosterId','streamId']){
  const flat={id:company,companyId:company,version:9,[stream]:company,versionSha256:digest};
  expect(m78VerifiedIdentity(flat)).toEqual({id:company,companyId:company,[stream]:company,versionSha256:digest});
  expect(m78VerifiedIdentity({version:flat,proof:{}})).toEqual(m78VerifiedIdentity(flat));
 }
 for(const hash of ['decisionSha256','reportSha256'])expect(m78VerifiedIdentity({id:company,versionId:company,[hash]:digest})).toEqual({id:company,versionId:company,[hash]:digest});
 for(const bad of [null,[],{},9,{version:9},{version:{}},{version:{id:'undefined'}},{id:'bad',version:1}])expect(()=>m78VerifiedIdentity(bad)).toThrow();
});
test('hosted exact review verification handles embedded and separately retained discovery reviews',()=>{
 const review={id:company,versionId:company,decisionSha256:digest},flat={id:company,version:9,review};
 for(const record of [flat,{version:flat,proof:{}},{reviews:[review]}])expect(()=>m78VerifiedReview(record,review)).not.toThrow();
 for(const record of [{...flat,review:null},{...flat,id:'78000000-0000-4000-8000-000000000003'},{reviews:[]},{reviews:[review,review]},{reviews:[{...review,decisionSha256:'b'.repeat(64)}]}])expect(()=>m78VerifiedReview(record,review)).toThrow();
 expect(()=>m78VerifiedReview(flat,{...review,versionId:'undefined'})).toThrow();
});
function add(es:M78Event[],mode:M78Event['mode'],kind:string,data:any){const body={sequence:es.length+1,previousSha256:es.at(-1)?.sha256??null,profile:'m78-hosted-journey-v1',workspaceId:company,mode,kind,data,createdAt:'2026-09-17T00:00:00.000Z'};es.push({...body,sha256:sha(canonical(body))})}
function closedJournal(){const es:M78Event[]=[];add(es,'baseline','provenance',{acceptedM77:M78_ACCEPTED_M77});for(const mode of ['baseline','exercise','revisit']as const){add(es,mode,'attempt_started',{mode,gate:input().gate});const sequence=es.at(-1)!.sequence;for(const role of ['manager1','manager2','member','outsider']){add(es,mode,'auth_intent',{role});add(es,mode,'auth_outcome',{role,status:200,tokenObserved:true,subjectMatched:true})}
 if(mode==='exercise')for(let i=0;i<38;i++){const name='step_'+i,route='/workspace-api/workspace/'+company+'/scope1-inventory',role='manager1';add(es,mode,'post_intent',{name,route,role,expected:201,request:{synthetic:true}});add(es,mode,'post_outcome',{name,route,role,status:201,responseSha256:digest,byteLength:4});add(es,mode,'post_verified',{name,responseSha256:digest,verifiedIdentity:{id:company}})}
 if(mode==='exercise')for(const role of ['member','outsider','signed_out']){const name='m78_'+role+'_write_refused',route='/workspace-api/workspace/'+company+'/scope1-inventory',expected=role==='signed_out'?401:403;add(es,mode,'post_intent',{name,route,role,expected,request:{}});add(es,mode,'post_outcome',{name,route,role,status:expected,responseSha256:digest,byteLength:4})}
 for(let id=1;id<=8;id++){const action=id<=4?'login':'logout';add(es,mode,'legacy_auth_intent',{requestId:id,action});add(es,mode,'legacy_auth_outcome',{requestId:id,action,status:action==='login'?200:204})}
 add(es,mode,'legacy_read_verified',{unchanged:true,applicationPostRequests:0,allCreatedAuthSessionsClosed:true});add(es,mode,mode==='baseline'?'baseline':mode==='exercise'?'exercise_complete':'revisit_verified',{});for(const role of ['manager1','manager2','member','outsider']){add(es,mode,'logout_intent',{role});add(es,mode,'logout_outcome',{role,status:204})}add(es,mode,'attempt_finished',{attemptSequence:sequence,status:'passed',allCreatedAuthSessionsClosed:true,unknownAuthSessions:0,applicationPostRequests:mode==='exercise'?M78_EXPECTED_POSTS:0})}return es}
test('fixed provenance, exact recipe count and schema source gate shape',()=>{
 expect(parseM78JourneyInput(input()).mode).toBe('baseline')
 for(const mutate of [(v:any)=>v.mode='retry',(v:any)=>v.acceptedM77.headSha256='0'.repeat(64),(v:any)=>v.gate.expectedApplicationPosts=38,(v:any)=>v.gate.recipeSha256='',(v:any)=>v.env.SUPABASE_URL='https://foreign.invalid']){const v=structuredClone(input());mutate(v);expect(()=>parseM78JourneyInput(v)).toThrow()}
})
test('transport refuses foreign roots, credentials, admin endpoints and writes outside exercise',()=>{
 const root=HOST+'/workspace-api/workspace/'+company;for(const family of ['scope1-inventory','process-screen'])expect(()=>validateM78Route(root+'/'+family,'POST',company,'exercise')).not.toThrow()
 for(const[url,method,mode]of [[root+'/scope1-inventory','POST','baseline'],[root+'/scope1-inventory','POST','revisit'],[root+'/members','POST','exercise'],[root+'/scope1-inventory','DELETE','exercise'],[HOST+'/workspace-api/workspace/'+company+'x/scope1-inventory','GET','baseline'],[HOST+'/ready?secret=1','GET','baseline'],[HOST+'/ready#x','GET','baseline'],['https://foreign.invalid/ready','GET','baseline'],[AUTH+'/auth/v1/admin/users','POST','exercise'],[AUTH+'/auth/v1/token?grant_type=refresh_token','POST','exercise']])expect(()=>validateM78Route(url!,method!,company,mode as any)).toThrow()
})
test('ordered durable journal requires raw outcome, verification, legacy read and every logout',()=>{
 const es=closedJournal();expect(()=>cleanM78Journal(es)).not.toThrow();const text=es.map(e=>JSON.stringify(e)).join('\n')+'\n';expect(readM78Journal(text,company).length).toBe(es.length)
 expect(()=>readM78Journal(text.trimEnd(),company)).toThrow();expect(()=>readM78Journal(text.replace('provenance','tampered'),company)).toThrow()
 for(const mutate of [(v:M78Event[])=>v.splice(v.findIndex(e=>e.kind==='legacy_auth_outcome'),1),(v:M78Event[])=>v.find(e=>e.kind==='legacy_auth_outcome')!.data.status=500,(v:M78Event[])=>v.find(e=>e.kind==='post_intent'&&e.data.role==='member')!.data.expected=201,(v:M78Event[])=>v.find(e=>e.kind==='post_intent'&&e.data.role==='member')!.data.route+='/foreign',(v:M78Event[])=>v.splice(v.findIndex(e=>e.kind==='post_outcome'),1),(v:M78Event[])=>v.splice(v.findIndex(e=>e.kind==='post_verified'),1),(v:M78Event[])=>v.splice(v.findIndex(e=>e.kind==='logout_outcome'),1),(v:M78Event[])=>v.find(e=>e.kind==='post_verified')!.data.responseSha256='b'.repeat(64),(v:M78Event[])=>v.find(e=>e.kind==='attempt_finished')!.data.allCreatedAuthSessionsClosed=false,(v:M78Event[])=>v.find(e=>e.kind==='attempt_finished')!.data.unknownAuthSessions=1,(v:M78Event[])=>v.find(e=>e.kind==='attempt_finished')!.data.status='failed',(v:M78Event[])=>v.splice(v.findIndex(e=>e.kind==='legacy_read_verified'),1)]){const bad=structuredClone(es);mutate(bad);expect(()=>cleanM78Journal(bad)).toThrow()}
})
test('uncertain and failed journals stop before any network or source admission',async()=>{
 for(const kind of ['attempt_started','post_intent']){const es:M78Event[]=[];add(es,'exercise',kind,{mode:'exercise',name:'uncertain'});let calls=0;const r=await runM78Journey(parseM78JourneyInput(input()),{load:async()=>es.map(e=>JSON.stringify(e)).join('\n')+'\n',verifyGate:async()=>{calls++;throw Error('Unexpected gate')},fetch:(async()=>{calls++;throw Error('Unexpected network')})as unknown as typeof fetch});expect(r.status).toBe('failed');expect(r.applicationPostRequests).toBe(0);expect(calls).toBe(0)}
})
test('wrong auth subject closes known tokens, keeps failed journal, logs no credentials and refuses rerun',async()=>{
 let journal:string|null=null,logins=0,logouts=0,calls=0;const v=input(),deps={load:async()=>journal,append:async(line:string)=>{journal=(journal??'')+line},verifyGate:async()=>{},readPrior:async()=>({previous:{registers:{},downloads:{}},old:{legacy:{}}}),fetch:(async(url:any)=>{calls++;const u=String(url);if(u===HOST+'/ready')return Response.json({status:'ready',schemaVersion:21,profile:'neuvetra.private-synthetic-staging.v1',legacyContainmentVerified:true});if(u===HOST+'/workspace-api/config')return Response.json({profile:'neuvetra.private-synthetic-staging.v1',supabaseUrl:AUTH,anonKey:v.env.SUPABASE_ANON_KEY},{headers:{'cache-control':'no-store'}});if(u.includes('/auth/v1/token')){logins++;return Response.json({access_token:'private-token-'+logins,user:{id:logins===1?v.accounts[0]!.id:'wrong-subject'}})}if(u.includes('/auth/v1/logout')){logouts++;return new Response(null,{status:204})}throw Error('Unexpected network')})as unknown as typeof fetch}
 const result=await runM78Journey(parseM78JourneyInput(v),deps);expect(result.status).toBe('failed');expect(result.allCreatedAuthSessionsClosed).toBe(true);expect(logins).toBe(2);expect(logouts).toBe(2);expect(journal).not.toContain('synthetic-private-marker');expect(journal).not.toContain('private-token');expect(journal).not.toContain('@synthetic.invalid');const before=calls;expect((await runM78Journey(parseM78JourneyInput(v),deps)).status).toBe('failed');expect(calls).toBe(before)
})

test('legacy audit append failures preserve all known session cleanup and refuse success',async()=>{
 for(const failure of ['login_outcome','logout_intent']){let logins=0,logouts=0,failedOnce=false;const logged:any[]=[]
  const helper=(async(_input:any,deps:any)=>{const tokens:string[]=[];try{for(let i=0;i<4;i++){const r=await deps.fetch(AUTH+'/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({password:'secret-password',email:'private@synthetic.invalid'})});tokens.push((await r.json()).access_token)}}finally{for(const token of tokens)await deps.fetch(AUTH+'/auth/v1/logout?scope=local',{method:'POST',headers:{authorization:'Bearer '+token}})}await deps.save({baseline:{synthetic:true}});return {status:'passed',allCreatedAuthSessionsClosed:true,applicationPostRequests:0}})as any
  const result=await readM78Legacy(parseM78JourneyInput(input()),{synthetic:true},async(url)=>{if(url.includes('/token?')){logins++;return Response.json({access_token:'secret-token-'+logins})}logouts++;return new Response(null,{status:204})},async(kind,data)=>{logged.push({kind,data});if(!failedOnce&&(failure==='login_outcome'?kind==='legacy_auth_outcome'&&data.action==='login':kind==='legacy_auth_intent'&&data.action==='logout')){failedOnce=true;throw Error('Injected durable append failure')}},helper)
  expect(failedOnce).toBe(true);expect(result.verified).toBe(false);expect(result.allCreatedAuthSessionsClosed).toBe(true);expect(logins).toBe(4);expect(logouts).toBe(4);expect(JSON.stringify(logged)).not.toContain('secret-');expect(JSON.stringify(logged)).not.toContain('@synthetic.invalid')
 }
})
test('production predecessor verifier rejects invented or absent journal bytes',()=>{for(const text of ['', '{}\n','synthetic-pinned-substitute'])expect(()=>acceptedM77(text,company)).toThrow()})

test('UTF8 event budgets bound the fixed three-phase journal below128MB',()=>{const caps={terminal:2*m78JournalEventLimit('baseline'),requests:41*m78JournalEventLimit('post_intent'),verified:38*m78JournalEventLimit('post_verified'),other:164*m78JournalEventLimit('post_outcome')};expect(Object.values(caps).reduce((a,b)=>a+b,0)).toBe(119668000);expect(Object.values(caps).reduce((a,b)=>a+b,0)).toBeLessThan(128000000);const es=closedJournal();const bad=es.find(e=>e.kind==='post_verified')!;bad.data.padding='x'.repeat(4001);const fixed:M78Event[]=[];for(const e of es)add(fixed,e.mode,e.kind,e.data);expect(()=>readM78Journal(fixed.map(e=>JSON.stringify(e)).join('\n')+'\n',company)).toThrow()})

test('fully rehashed durable evidence still refuses foreign routes and invented verification identities',()=>{for(const mutate of [(es:M78Event[])=>{for(const e of es.filter(e=>['post_intent','post_outcome'].includes(e.kind)&&e.data.name==='step_0'))e.data.route='/workspace-api/workspace/'+company+'/members'},(es:M78Event[])=>{for(const e of es.filter(e=>['post_intent','post_outcome'].includes(e.kind)&&e.data.name==='step_0'))e.data.route='/workspace-api/workspace/78000000-0000-4000-8000-000000000099/scope1-inventory'},(es:M78Event[])=>es.find(e=>e.kind==='post_verified')!.data.verifiedIdentity={id:company,companyId:'78000000-0000-4000-8000-000000000099'},(es:M78Event[])=>es.find(e=>e.kind==='post_verified')!.data.verifiedIdentity={id:company,invented:'value'},(es:M78Event[])=>es.find(e=>e.kind==='post_verified')!.data.name='m78_member_write_refused']){const es=closedJournal();mutate(es);const rebuilt:M78Event[]=[];for(const e of es)add(rebuilt,e.mode,e.kind,e.data);const bytes=rebuilt.map(e=>JSON.stringify(e)).join('\n')+'\n';expect(()=>cleanM78Journal(readM78Journal(bytes,company))).toThrow()}})
