/** Fixed synthetic stationary journey recipe; transport and durable intent are caller-owned. */
import {M71_ARTIFACT,M71_LIMITATIONS} from '../../packages/neuvetra-database/src/m71-contract'
import {M71_EVIDENCE_SHA256} from '../../packages/neuvetra-database/src/m71-validation'
import {M73_PROFILE,M73_PERIOD,M73_LIMITATIONS} from '../../packages/neuvetra-database/src/m73-contract'
import {m73SourceChoices} from '../../packages/neuvetra-database/src/m73-validation'
import {M76_PROFILE,M76_PERIOD,M76_LIMITATIONS} from '../../packages/neuvetra-database/src/m76-contract'
import {M76_DIESEL_PROFILE,M76_DIESEL_FUEL,M76_DIESEL_LIMITATIONS} from '../../packages/neuvetra-database/src/m76-diesel-contract'
type Context={root:string;baseline:any;events:any[];append:(kind:string,data:any)=>Promise<void>;post:(name:string,route:string,role:any,build:()=>any,expected?:number)=>Promise<any>;read:()=>Promise<any>;check:(v:unknown)=>void}
export async function exerciseStationary(c:Context){
 const {root,post,check}=c,corporate=root+'/corporate-inventories',gasRoot=root+'/stationary-natural-gas',dieselRoot=root+'/stationary-diesel',equipmentRoot=root+'/stationary-equipment'
 const oldCoverage=c.baseline.corporate.versions.at(-1),oldGas=c.baseline.gas.worksheets[0]?.versions.at(-1)
 check(oldCoverage&&oldCoverage.version<=34&&c.baseline.gas.worksheets.length===1&&oldGas&&oldGas.statement&&oldGas.activity.quantityMmbtu!==null&&oldGas.version<=34)
 let plan=c.events.find(e=>e.kind==='plan')?.data
 if(!plan){plan={facilityId:crypto.randomUUID(),gasSourceId:crypto.randomUUID(),dieselSourceId:crypto.randomUUID(),gasCoverageId:crypto.randomUUID(),dieselCoverageId:crypto.randomUUID(),rowA:crypto.randomUUID(),rowB:crypto.randomUUID(),rowC:crypto.randomUUID(),generatorId:'M76-HOSTED-GENERATOR-001'};await c.append('plan',plan)}
 const refs=[{artifactId:M71_ARTIFACT.id,expectedSha256:M71_EVIDENCE_SHA256,locator:M71_ARTIFACT.locator,purpose:'Synthetic stationary-device control and source-screening evidence'}]
 const coverage=await post('m71_stationary_sources',corporate+'/'+oldCoverage.inventoryId+'/versions','manager1',()=>{
  const snapshot=structuredClone(oldCoverage.snapshot),office=snapshot.facilities.find((f:any)=>f.id===oldGas.activity.binding.facilityId),source=snapshot.sources.find((s:any)=>s.id===oldGas.activity.binding.sourceId),item=snapshot.coverageItems.find((i:any)=>i.sourceId===source?.id);check(office&&source&&item)
  snapshot.facilities.push({...office,id:plan.facilityId,name:'Synthetic California distribution center',evidenceRefs:refs})
  for(const[id,name,itemId]of[[plan.gasSourceId,'Synthetic dedicated gas space heater',plan.gasCoverageId],[plan.dieselSourceId,'Synthetic fixed fossil-diesel emergency generator',plan.dieselCoverageId]]){
   snapshot.sources.push({...source,id,facilityId:plan.facilityId,name,evidenceRefs:refs})
   snapshot.coverageItems.push({...item,id:itemId,sourceId:id,disposition:'included_activity',activityDataState:'missing',evidenceState:'linked',methodReadiness:'candidate',reason:'Synthetic stationary consumed-fuel workpaper is required; no family completeness claim.',evidenceRefs:refs,quantity:null,unit:null,estimateBasis:null})
  }
  return {snapshot,expectedVersionId:oldCoverage.id,expectedVersionSha256:oldCoverage.versionSha256,correctionReason:'Register separately identified distribution stationary devices and retain every earlier source/finding.',idempotencyKey:crypto.randomUUID()}
 })
 await post('m71_stationary_review',corporate+'/'+coverage.inventoryId+'/reviews','manager2',()=>({versionId:coverage.id,expectedVersionSha256:coverage.versionSha256,decision:'accepted_bounded_internal',note:'Separate synthetic boundary/source review; corporate inventory remains incomplete.',acknowledgedLimitations:[...M71_LIMITATIONS],idempotencyKey:crypto.randomUUID()}))
 const current=(await c.read()).corporate.versions.at(-1),choices=m73SourceChoices(current),bindingA=choices.find(x=>x.binding.sourceId===oldGas.activity.binding.sourceId)?.binding,bindingB=choices.find(x=>x.binding.sourceId===plan.gasSourceId)?.binding,bindingC=choices.find(x=>x.binding.sourceId===plan.dieselSourceId)?.binding;check(bindingA&&bindingB&&bindingC)
 const meterA={issuer:oldGas.activity.statement.issuer,meterLabel:oldGas.activity.statement.meterLabel,measurementBasis:'dedicated_single_device_consumption',dedicatedToSingleDevice:true,explanation:'Fictional dedicated office-boiler consumed-fuel meter.'}
 const meterB={issuer:'Synthetic M76 gas custodian',meterLabel:'M76-GAS-HEATER-METER',measurementBasis:'dedicated_single_device_consumption',dedicatedToSingleDevice:true,explanation:'Fictional dedicated distribution space-heater consumed-fuel meter.'}
 const meterC={issuer:'Synthetic M76 generator custodian',meterLabel:'M76-GENERATOR-FUEL-METER',measurementBasis:'dedicated_single_device_consumption',dedicatedToSingleDevice:true,explanation:'Fictional direct device fuel meter including emergency, testing and maintenance consumption.'}
 const row=(rowId:string,equipmentId:string,binding:any,equipmentType:string,fuel:string,meterRelationship:any)=>({rowId,equipmentId,aliases:[],identifierBasis:'Fictional physical equipment plate and facility inventory identity.',entityId:binding.entityId,facilityId:binding.facilityId,period:{...M76_PERIOD},equipmentType,fuel,controlBasis:'owned_operational_control_full_year',classificationBasis:'Fictional device/fuel specification verified for the declared equipment.',controlExplanation:'Operationally controlled for all of calendar2025.',meterRelationship})
 const declaration={issuer:'Synthetic M76 equipment custodian',reference:'M76-HOSTED-EQUIPMENT-2025',description:'Independent fictional office and distribution stationary-equipment inventory.',discoveryBasis:'Fictional equipment, facility walk-through, control and operating records checked for every declared entity/facility before selecting workpapers.',coveredEntityIds:current.snapshot.entities.map((e:any)=>e.id).sort(),coveredFacilityIds:current.snapshot.facilities.map((f:any)=>f.id).sort(),completeness:'declared_complete',allControlledLocationsIncluded:true,assets:[row(plan.rowA,'M76-HOSTED-BOILER-001',bindingA,'boiler','Natural Gas',meterA),row(plan.rowB,'M76-HOSTED-HEATER-001',bindingB,'space_heater','Natural Gas',meterB),{...row(plan.rowC,plan.generatorId,bindingC,'stationary_emergency_generator',M76_DIESEL_FUEL,meterC),identifierBasis:'Fictional physical generator plate and asset register.',controlExplanation:'Fictional full-year operational control at the distribution center.'}]}
 const saveEquipment=(name:string,prior:any,reason:string|null,blocked=false)=>post(name,prior?equipmentRoot+'/'+prior.rosterId+'/versions':equipmentRoot,'manager1',async()=>{const state=await c.read(),statement=structuredClone(declaration);if(blocked)statement.assets[1].meterRelationship={...meterB,measurementBasis:'shared_meter',dedicatedToSingleDevice:false,explanation:'Synthetic unresolved shared relationship requires corrected dedicated-device evidence.'};return {profile:M76_PROFILE,coverageVersionId:coverage.id,coverageVersionSha256:coverage.versionSha256,expectedDependencySha256:state.equipment.reconciliation.dependencySha256,period:{...M76_PERIOD},rosterStatement:statement,manualConfirmation:true,links:[{rowId:plan.rowA,sourceId:bindingA.sourceId},{rowId:plan.rowB,sourceId:bindingB.sourceId},{rowId:plan.rowC,sourceId:blocked?null:bindingC.sourceId}],expectedVersionId:prior?.id??null,expectedVersionSha256:prior?.versionSha256??null,correctionReason:reason,idempotencyKey:crypto.randomUUID()}})
 const reviewEquipment=(name:string,v:any,decision:string,role='manager2',expected=201)=>post(name,equipmentRoot+'/'+v.rosterId+'/reviews',role,async()=>({versionId:v.id,expectedVersionSha256:v.versionSha256,expectedDependencySha256:(await c.read()).equipment.reconciliation.dependencySha256,decision,note:decision==='changes_requested'?'Resolve missing workpapers, orphan source and shared-device fuel relationship.':'Exact synthetic declaration reconciles to current accepted stationary workpapers; no aggregate or complete Scope1 claim.',acknowledgedLimitations:[...M76_LIMITATIONS],idempotencyKey:crypto.randomUUID()}),expected)
 const reportEquipment=(name:string,v:any)=>post(name,equipmentRoot+'/'+v.rosterId+'/reports','manager1',async()=>({expectedReconciliationSha256:(await c.read()).equipment.reconciliation.contentSha256,idempotencyKey:crypto.randomUUID()}))
 const first=await saveEquipment('m76_save_1',null,null,true)
 await reviewEquipment('m76_contributor_review_refused',first,'changes_requested','manager1',403)
 await reviewEquipment('m76_member_review_refused',first,'changes_requested','member',403)
 await reviewEquipment('m76_review_1',first,'changes_requested');await reportEquipment('m76_report_1',first)
 const gasAInput={...oldGas.activity,binding:bindingA,statement:{...oldGas.activity.statement,reference:'M76-HOSTED-BOILER-GAS-2025',statedQuantityMmbtu:oldGas.activity.quantityMmbtu,description:'Corrected fictional annual dedicated office-boiler consumption matching the entered quantity.'},discrepancyReason:null,expectedVersionId:oldGas.id,expectedVersionSha256:oldGas.versionSha256,correctionReason:'Relink current boundary and dedicated boiler consumption evidence.',idempotencyKey:crypto.randomUUID()}
 const gasA=await post('m73_a_relink',gasRoot+'/'+oldGas.worksheetId+'/versions','manager1',()=>gasAInput)
 const reviewGas=(name:string,v:any)=>post(name,gasRoot+'/'+v.worksheetId+'/reviews','manager2',()=>({versionId:v.id,expectedVersionSha256:v.versionSha256,decision:'accepted_bounded_internal',note:'Separate bounded synthetic dedicated natural-gas evidence review.',acknowledgedLimitations:[...M73_LIMITATIONS],idempotencyKey:crypto.randomUUID()}))
 await reviewGas('m73_a_review',gasA)
 const gasBInput={profile:M73_PROFILE,binding:bindingB,period:{...M73_PERIOD},fuel:'Natural Gas',heatBasis:'HHV',unit:'MMBtu',quantityMmbtu:'300.000',statement:{issuer:meterB.issuer,reference:'M76-HOSTED-HEATER-GAS-2025',meterLabel:meterB.meterLabel,statedQuantityMmbtu:'300.000',description:'Fictional annual dedicated space-heater consumption already expressed in HHV MMBtu.',consumptionBasis:'dedicated_meter_consumed_no_adjustments'},manualConfirmation:true,discrepancyReason:null,zeroReason:null,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()}
 const gasB=await post('m73_b_save',gasRoot,'manager1',()=>gasBInput);await reviewGas('m73_b_review',gasB)
 const dieselInput={profile:M76_DIESEL_PROFILE,binding:bindingC,period:{...M76_PERIOD},equipment:{assetId:plan.generatorId,identifierBasis:'Fictional physical generator plate and asset register.',equipmentType:'stationary_emergency_generator',engineType:'compression_ignition',stationaryInstallation:'fixed',controlBasis:'owned_operational_control_full_year',controlExplanation:'Fictional full-year operational control at the distribution center.',fuel:M76_DIESEL_FUEL,fossilFraction:'1.000',fuelGradeBasis:'Fictional supplier specification identifies fossil distillate No.2 without a blend.'},unit:'US_gallon',quantityGallons:'1000.000',statement:{issuer:meterC.issuer,reference:'M76-HOSTED-GENERATOR-FUEL-2025',meterLabel:meterC.meterLabel,statedQuantityGallons:'1000.000',description:'Fictional consumed fuel measured directly at this fixed generator.',consumptionBasis:'dedicated_generator_consumed_no_adjustments',measurementBasis:'direct_device_fuel_meter',dedicatedToSingleDevice:true,includesTesting:true,stockDerivedConsumption:false,sharedFuelAllocation:false,consumptionBoundaryExplanation:'Direct annual device meter includes emergency/testing/maintenance; no tank inventory, shared allocation, deliveries, losses or feedstock adjustments.',supplierSpecificHhvAvailable:false,supplierSpecificCarbonAvailable:false,defaultFactorEligibilityExplanation:'Fictional fuel specification confirms no supplier-specific HHV or carbon available; default HHV is visibly estimated.'},manualConfirmation:true,discrepancyReason:null,zeroReason:null,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()}
 await post('m76_diesel_member_save_refused',dieselRoot,'member',()=>dieselInput,403);await post('m76_diesel_signed_out_save_refused',dieselRoot,'signed_out',()=>dieselInput,401)
 const diesel=await post('m76_diesel_save',dieselRoot,'manager1',()=>dieselInput)
 const reviewDiesel=(name:string,v:any)=>post(name,dieselRoot+'/'+v.worksheetId+'/reviews','manager2',()=>({versionId:v.id,expectedVersionSha256:v.versionSha256,decision:'accepted_bounded_internal',note:'Separate review of exact fossil generator consumption and default-HHV eligibility; candidate not released.',acknowledgedLimitations:[...M76_DIESEL_LIMITATIONS],idempotencyKey:crypto.randomUUID()}))
 const dieselReview=await reviewDiesel('m76_diesel_review',diesel)
 const sourceReport=(name:string,v:any,d:any)=>post(name,dieselRoot+'/'+v.worksheetId+'/reports','manager1',()=>({versionId:v.id,expectedVersionSha256:v.versionSha256,expectedDecisionId:d?.id??null,expectedDecisionSha256:d?.decisionSha256??null,idempotencyKey:crypto.randomUUID()}))
 await sourceReport('m76_diesel_report',diesel,dieselReview)
 const second=await saveEquipment('m76_save_2',first,'Correct the shared-meter declaration and orphan mapping from dedicated-device evidence; capture all completed source workpapers.')
 await reviewEquipment('m76_review_2',second,'accepted_bounded_reconciliation');await reportEquipment('m76_report_2',second)
 const corrected=await post('m76_diesel_correction',dieselRoot+'/'+diesel.worksheetId+'/versions','manager1',()=>({...dieselInput,quantityGallons:'1001.000',statement:{...dieselInput.statement,reference:'M76-HOSTED-GENERATOR-FUEL-2025-CORRECTED',statedQuantityGallons:'1001.000'},expectedVersionId:diesel.id,expectedVersionSha256:diesel.versionSha256,correctionReason:'Correct fictional consumed fuel from matching direct-device evidence; independent review required again.',idempotencyKey:crypto.randomUUID()}))
 const third=await saveEquipment('m76_save_3',second,'Capture corrected generator consumption while its new review remains pending.');await reportEquipment('m76_report_3',third)
 const correctedReview=await reviewDiesel('m76_diesel_corrected_review',corrected);await sourceReport('m76_diesel_corrected_report',corrected,correctedReview)
 const fourth=await saveEquipment('m76_save_4',third,'Capture separate approval of the corrected generator; fresh stationary reconciliation review required.')
 await reviewEquipment('m76_review_4',fourth,'accepted_bounded_reconciliation');await reportEquipment('m76_report_4',fourth)
 const final=await c.read();check(final.equipment.versions.length===4&&final.equipment.reports.length===4&&final.equipment.reconciliation.status==='reconciled_bounded_synthetic'&&final.equipment.reconciliation.rows.length===3&&final.equipment.reconciliation.rows.every((r:any)=>r.status==='matched_reviewed'))
 return final
}
