/** Explicit fixed recovery journey. Imports never read credentials or contact the host. */
import {open,unlink} from 'node:fs/promises'
import path from 'node:path'
import {parseJourneyInput} from './check-hosted-journey'
import {readM76Journal,validateM76JourneyRoute} from './check-m76-hosted'
import {runM72Journey} from './check-m72-hosted'
import {m71CanonicalJson as canonical} from '../../packages/neuvetra-database/src/m71-validation'
import {MIGRATION} from './m76-common'
import * as corporate from '../../apps/site-web/src/lib/m71-api'
import * as gas from '../../apps/site-web/src/lib/m73-api'
import {decodeMobileRegister} from '../../apps/site-web/src/lib/m74-api'
import {decodeFleetRegister,fleetReportDownload,fleetReportSnapshotDownload} from '../../apps/site-web/src/lib/m75-api'
import {m74Export} from '../../packages/neuvetra-database/src/m74-validation'
import {m75Export} from '../../packages/neuvetra-database/src/m75-validation'
import * as generator from '../../apps/site-web/src/lib/m76-diesel-api'
import * as equipment from '../../apps/site-web/src/lib/m76-api'
import {RECOVERY_COMPANY,ORIGINAL_BYTES_SHA256,ORIGINAL_HEAD,RECOVERY_PROFILE,RECOVERY_PLAN_ID,RECOVERY_KEYS,OPERATIONS,recoveryHash as hash,exerciseRecovery,type Operation} from './m76-hosted-recovery-recipe'
export {RECOVERY_KEYS,RECOVERY_PLAN_ID,OPERATIONS}
const HOST='https://www.neuvetra.ai',AUTH='https://icockcoguyadhryzydvl.supabase.co',ORIGINAL=path.resolve(import.meta.dir,'../../.superpowers/m76-hosted-journey.jsonl'),JOURNAL=path.resolve(import.meta.dir,'../../.superpowers/m76-hosted-recovery.jsonl')
type Mode='baseline'|'exercise'|'revisit'
type Input=ReturnType<typeof parseJourneyInput>&{mode:Mode}
type Event={sequence:number;previousSha256:string|null;profile:typeof RECOVERY_PROFILE;planId:string;companyId:string;mode:Mode;kind:string;data:any;createdAt:string;sha256:string}
type Dependencies={fetch?:typeof fetch;load?:()=>Promise<string|null>;loadOriginal?:()=>Promise<string>;append?:(line:string,exclusive:boolean)=>Promise<void>;legacy?:typeof runM72Journey}
export const recoveryCheck=(value:unknown):void=>{if(!value)throw Error('Fixed M76 recovery refused.')}
const same=(a:unknown,b:unknown)=>canonical(a)===canonical(b),core=(v:any)=>Object.hasOwn(v,'review')?{...v,review:null}:v,observation=(text:string)=>({sha256:hash(text),byteLength:Buffer.byteLength(text)})
export function parseRecoveryInput(value:unknown):Input{const mode=(value as any)?.mode;recoveryCheck(['baseline','exercise','revisit'].includes(mode));const input=parseJourneyInput(value);recoveryCheck(input.roster.workspaceId===RECOVERY_COMPANY);return {...input,mode}}
export function validateRecoveryRoute(url:string,method:string){validateM76JourneyRoute(url,method,RECOVERY_COMPANY);const u=new URL(url);if(u.origin===HOST&&method==='POST')recoveryCheck(new RegExp(`^/workspace-api/workspace/${RECOVERY_COMPANY}/(corporate-inventories|stationary-natural-gas|stationary-diesel|stationary-equipment)/[0-9a-f-]{36}/(versions|reviews|reports)$`).test(u.pathname)&&!(u.pathname.includes('/corporate-inventories/')&&u.pathname.endsWith('/reports')))}
export function validateOriginalRecoveryJournal(text:string){
 recoveryCheck(hash(text)===ORIGINAL_BYTES_SHA256)
 const es=readM76Journal(text,RECOVERY_COMPANY);recoveryCheck(es.length===44&&es.at(-1)?.sha256===ORIGINAL_HEAD&&!es.some(e=>e.kind==='exercise_complete'))
 const attempts=es.filter(e=>e.kind==='attempt_started');for(const a of attempts){const finish=es.find(e=>e.kind==='attempt_finished'&&e.data.attemptSequence===a.sequence);recoveryCheck(finish&&finish.data.allCreatedAuthSessionsClosed===true)}
 const intents=es.filter(e=>e.kind==='post_intent');recoveryCheck(intents.length===18)
 for(const intent of intents){const out=es.filter(e=>e.kind==='post_outcome'&&e.data.name===intent.data.name);recoveryCheck(out.length===1&&out[0]!.data.route===intent.data.route&&out[0]!.data.role===intent.data.role&&out[0]!.data.expected===intent.data.expected);recoveryCheck(out[0]!.data.status===(intent.data.name==='m76_review_2'?422:intent.data.expected))}
 const oldKeys=intents.map(e=>e.data.request.idempotencyKey);recoveryCheck(new Set(Object.values(RECOVERY_KEYS)).size===21&&Object.values(RECOVERY_KEYS).every(k=>!oldKeys.includes(k)));return es
}
export function readRecoveryJournal(text:string|null):Event[]{if(text===null)return [];recoveryCheck(text.length<=48_000_000&&text.endsWith('\n'));let previous:string|null=null;return text.trimEnd().split('\n').map((line,i)=>{const e=JSON.parse(line) as Event,{sha256,...body}=e;recoveryCheck(e.sequence===i+1&&e.previousSha256===previous&&e.profile===RECOVERY_PROFILE&&e.planId===RECOVERY_PLAN_ID&&e.companyId===RECOVERY_COMPANY&&['baseline','exercise','revisit'].includes(e.mode)&&hash(canonical(body))===sha256);previous=sha256;return e})}
export function cleanRecoveryJournal(es:Event[]){
 for(const a of es.filter(e=>e.kind==='attempt_started')){const f=es.filter(e=>e.kind==='attempt_finished'&&e.data.attemptSequence===a.sequence);recoveryCheck(f.length===1&&f[0]!.data.status==='passed'&&f[0]!.data.allCreatedAuthSessionsClosed===true)}
 const intents=es.filter(e=>e.kind==='post_intent');recoveryCheck(intents.every((e,i)=>e.data.name===OPERATIONS[i]&&e.data.request.idempotencyKey===RECOVERY_KEYS[e.data.name as Operation]))
 for(const intent of intents){const outcomes=es.filter(e=>e.kind==='post_outcome'&&e.data.name===intent.data.name),verified=es.filter(e=>e.kind==='step_verified'&&e.data.name===intent.data.name);recoveryCheck(outcomes.length===1&&outcomes[0]!.data.status===201&&verified.length===1&&same(outcomes[0]!.data.response,verified[0]!.data.response))}
}
/** Refuse external successors and validate immutable cores plus separate decisions at every step. */
export function assertRecoveryProgress(initial:any,current:any,verified:Event[]){
 recoveryCheck(current.gas.coverageHeadVersionId===current.corporate.headVersionId&&current.diesel.coverageHeadVersionId===current.corporate.headVersionId&&current.mobile.coverageHeadVersionId===current.corporate.headVersionId&&current.equipment.proof.coverageVersion?.id===current.corporate.headVersionId&&current.fleet.proof.coverageVersion?.id===current.corporate.headVersionId)
 const done=(name:Operation)=>verified.find(e=>e.data.name===name)?.data.response
 const versions=(s:any,f:string,w?:string)=>w?s[f].worksheets.find((x:any)=>x.worksheetId===w)?.versions:s[f].versions
 const checkVersions=(f:string,w:string|undefined,names:Operation[],reviews:Operation[])=>{
  const old=versions(initial,f,w),now=versions(current,f,w),added=names.map(done).filter(Boolean);recoveryCheck(now&&now.length===old.length+added.length)
  for(const v of [...old,...added]){const actual=now.find((x:any)=>x.id===v.id);recoveryCheck(actual&&same(core(actual),core(v)));if(Object.hasOwn(v,'review')){const review=reviews.map(done).find(r=>r?.versionId===v.id)??v.review;recoveryCheck(same(actual.review,review))}}
  recoveryCheck(now.at(-1)?.id===(added.at(-1)?.id??old.at(-1)?.id))
 }
 recoveryCheck(current.gas.worksheets.length===initial.gas.worksheets.length&&current.diesel.worksheets.length===initial.diesel.worksheets.length)
 checkVersions('corporate',undefined,['correct_corporate_screening'],['review_corporate_screening'])
 for(const w of initial.gas.worksheets){const boiler=w.sourceId==='76e4e7e0-f4c9-40bd-b133-21e534401cae';checkVersions('gas',w.worksheetId,[boiler?'rebind_boiler':'rebind_heater'],[boiler?'review_boiler':'review_heater'])}
 checkVersions('diesel',initial.diesel.worksheets[0].worksheetId,['rebind_generator','correct_generator_quantity'],['review_rebound_generator','review_corrected_generator'])
 checkVersions('equipment',undefined,['save_reconciled_equipment','save_pending_equipment','save_final_equipment'],[])
 for(const f of ['mobile','fleet']){if(f==='mobile'){recoveryCheck(current.mobile.worksheets.length===initial.mobile.worksheets.length);for(const w of initial.mobile.worksheets)recoveryCheck(same(current.mobile.worksheets.find((x:any)=>x.worksheetId===w.worksheetId),w))}else{recoveryCheck(same(current.fleet.versions,initial.fleet.versions)&&same(current.fleet.reviews,initial.fleet.reviews)&&same(current.fleet.reports,initial.fleet.reports))}}
 const expectedReviews=[...initial.equipment.reviews,...['review_reconciled_equipment','review_final_equipment'].map(n=>done(n as Operation)).filter(Boolean)];recoveryCheck(same(current.equipment.reviews,expectedReviews))
 for(const f of ['gas','diesel','equipment']){const groups=f==='equipment'?[{id:null,old:initial.equipment.reports,now:current.equipment.reports}]:initial[f].worksheets.map((w:any)=>({id:w.worksheetId,old:w.reports,now:current[f].worksheets.find((x:any)=>x.worksheetId===w.worksheetId)?.reports}));for(const g of groups){const added=verified.map(e=>e.data.response).filter(r=>r?.html&&r?.snapshotJson&&(f==='equipment'?r.rosterId&&r.rosterId===initial.equipment.rosterId:r.worksheetId===g.id));recoveryCheck(g.now&&g.now.length===g.old.length+added.length);for(const r of [...g.old,...added]){const actual=g.now.find((x:any)=>x.id===r.id);const expected=f==='equipment'?(({html,snapshotJson,...rest}:any)=>rest)(r):r;recoveryCheck(actual&&same(actual,expected))}}}
}
export async function runHostedRecovery(input:Input,deps:Dependencies={}){
 const es:Event[]=[],tokens=new Map<string,string>(),savedFetch=globalThis.fetch,networkFetch=deps.fetch??savedFetch,company=RECOVERY_COMPANY,root=`/workspace-api/workspace/${company}`
 let stage='journal_preconditions',attempt:number|null=null,writes=0,unknownSessions=0,closed=true,legacyClosed=true,failed=false,active:any=null,original:any[],baseline:any
 const append=async(kind:string,data:any)=>{const body={sequence:es.length+1,previousSha256:es.at(-1)?.sha256??null,profile:RECOVERY_PROFILE,planId:RECOVERY_PLAN_ID,companyId:company,mode:input.mode,kind,data,createdAt:new Date().toISOString()},event={...body,sha256:hash(canonical(body))};await(deps.append??(async(line,exclusive)=>{const f=await open(JOURNAL,exclusive?'wx':'a',0o600);try{await f.writeFile(line);await f.sync()}finally{await f.close()}}))(JSON.stringify(event)+'\n',es.length===0);es.push(event)}
 const network=async(url:string,init:RequestInit={})=>{validateRecoveryRoute(url,init.method??'GET');return networkFetch(url,{...init,redirect:'error',signal:AbortSignal.timeout(30000)})}
 const actor=(role:'manager1'|'manager2'|'member')=>({accessToken:tokens.get(role)!,userId:input.accounts.find(a=>a.role===role)!.id,role:role==='member'?'member' as const:'owner' as const})
 const rawGet=async(route:string)=>{const r=await network(HOST+route,{headers:{origin:HOST,authorization:'Bearer '+tokens.get('manager1')}});recoveryCheck(r.status===200&&r.headers.get('cache-control')?.includes('no-store'));const text=await r.text();recoveryCheck(Buffer.byteLength(text)<=4_000_000);return JSON.parse(text)}
 const read=async()=>{const result=await Promise.all([corporate.corporateRegisterRequest(actor('manager1'),company),gas.gasRegisterRequest(actor('manager1'),company),rawGet(root+'/mobile-diesel').then(value=>decodeMobileRegister(value,company)),rawGet(root+'/controlled-fleet').then(value=>decodeFleetRegister(value,company)),generator.generatorRegisterRequest(actor('manager1'),company),equipment.stationaryRegisterRequest(actor('manager1'),company)]);return {corporate:result[0],gas:result[1],mobile:result[2],fleet:result[3],diesel:result[4],equipment:result[5]}}
 const exact=async(route:string,expected:string)=>{const r=await network(HOST+route,{headers:{origin:HOST,authorization:'Bearer '+tokens.get('member')}});recoveryCheck(r.status===200&&r.headers.get('cache-control')?.includes('no-store'));const text=await r.text();recoveryCheck(Buffer.byteLength(text)<=4_000_000&&text===expected);return observation(text)}
 const downloads=async(s:any)=>{
  const out:any={corporate:{},gas:{},mobile:{},fleet:{},diesel:{},equipment:{}}
  for(const v of s.corporate.versions)out.corporate[v.id]=observation(await corporate.corporateExportRequest(actor('member'),company,v))
  for(const [f,base]of[['gas','stationary-natural-gas'],['mobile','mobile-diesel'],['diesel','stationary-diesel']])for(const w of s[f!].worksheets){for(const v of w.versions){out[f!]['version_'+v.id]=f==='gas'?observation(await gas.gasExportRequest(actor('member'),company,v)):f==='diesel'?observation(await generator.generatorExportRequest(actor('member'),company,v)):await exact(root+'/'+base+'/'+w.worksheetId+'/versions/'+v.id+'/calculation-export',m74Export(v));for(const [kind,statement]of f==='mobile'?[['fuel',v.fuelStatement],['mileage',v.mileageStatement]]:[['statement',v.statement]])if(statement)out[f!][kind+'_'+statement.id]=await exact(root+'/'+base+'/'+w.worksheetId+'/statements/'+statement.id+'/download',statement.text)}for(const r of w.reports){out[f!]['report_'+r.id]=f==='diesel'?observation(await generator.generatorReportDownload(actor('member'),company,w.worksheetId,r)):await exact(root+'/'+base+'/'+w.worksheetId+'/reports/'+r.id+'/download',r.html);if(f==='diesel')out.diesel['snapshot_'+r.id]=await exact(root+'/'+base+'/'+w.worksheetId+'/reports/'+r.id+'/snapshot',r.snapshotJson)}}
  for(const [f,base]of[['fleet','controlled-fleet'],['equipment','stationary-equipment']]){for(const v of s[f!].versions){out[f!]['version_'+v.id]=f==='fleet'?await exact(root+'/'+base+'/'+v.rosterId+'/versions/'+v.id+'/roster-export',m75Export(v)):observation(await equipment.stationaryVersionDownload(actor('member'),company,v));if(v.statement)out[f!]['statement_'+v.statement.id]=await exact(root+'/'+base+'/'+v.rosterId+'/statements/'+v.statement.id+'/download',v.statement.text)}for(const r of s[f!].reports){out[f!]['report_'+r.id]=observation(await(f==='fleet'?fleetReportDownload:equipment.stationaryReportDownload)(actor('member'),company,r));out[f!]['snapshot_'+r.id]=observation(await(f==='fleet'?fleetReportSnapshotDownload:equipment.stationaryReportSnapshotDownload)(actor('member'),company,r));out[f!]['proof_'+r.id]=hash(canonical(await rawGet(root+'/'+base+'/'+r.rosterId+'/reports/'+r.id+'/proof')))}}
  return out
 }
 try{
  original=validateOriginalRecoveryJournal(await(deps.loadOriginal?deps.loadOriginal():Bun.file(ORIGINAL).text()));es.push(...readRecoveryJournal(deps.load?await deps.load():await Bun.file(JOURNAL).exists()?await Bun.file(JOURNAL).text():null));cleanRecoveryJournal(es)
  baseline=es.find(e=>e.kind==='failed_state_baseline')?.data
  const codeSha=hash(await Bun.file(new URL(import.meta.url)).bytes()),recipeSha=hash(await Bun.file(new URL('./m76-hosted-recovery-recipe.ts',import.meta.url)).bytes())
  recoveryCheck(input.mode==='baseline'?!baseline:!!baseline);if(baseline)recoveryCheck(baseline.originalByteSha256===ORIGINAL_BYTES_SHA256&&baseline.originalHead===ORIGINAL_HEAD&&baseline.codeSha256===codeSha&&baseline.recipeSha256===recipeSha&&same(baseline.keys,RECOVERY_KEYS))
  if(input.mode==='revisit')recoveryCheck(es.some(e=>e.kind==='recovery_complete'))
  await append('attempt_started',{mode:input.mode});attempt=es.at(-1)!.sequence
  stage='schema19_readiness';const ready=await network(HOST+'/ready');recoveryCheck(ready.status===200&&(await ready.json() as any).schemaVersion===19)
  stage='legacy_read_only';legacyClosed=false;let legacy:any;const result=await(deps.legacy??runM72Journey)({...input,mode:'baseline'},{load:async()=>null,save:async value=>{legacy=value},fetch:(async(url,init)=>{recoveryCheck(!(String(url).startsWith(HOST)&&init?.method==='POST'));const r=await network(String(url),init);if(String(url)===HOST+'/ready'){const v=await r.json() as any;recoveryCheck(v.schemaVersion===19);return Response.json({...v,schemaVersion:14},{status:r.status,headers:r.headers})}return r}) as typeof fetch});legacyClosed=result.allCreatedAuthSessionsClosed;recoveryCheck(result.status==='passed'&&legacyClosed&&result.applicationPostRequests===0&&same(legacy.baseline,original.find(e=>e.kind==='baseline')!.data.legacy))
  for(const a of input.accounts){stage='sign_in_'+a.role;unknownSessions++;const r=await network(AUTH+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:input.env.SUPABASE_ANON_KEY,'content-type':'application/json'},body:JSON.stringify({email:a.email,password:a.password})}),s=await r.json() as any;if(typeof s.access_token==='string'&&s.access_token.length>0&&s.access_token.length<=8192){tokens.set(a.role,s.access_token);unknownSessions--}recoveryCheck(r.status===200&&s.user?.id===a.id&&tokens.has(a.role))}
  globalThis.fetch=(async(url:any,init:RequestInit={})=>{recoveryCheck(typeof url==='string'&&url.startsWith(root+'/'));const method=init.method??'GET';if(method==='POST'){recoveryCheck(active&&!active.sent&&url===active.route&&same(JSON.parse(init.body as string),active.request)&&new Headers(init.headers).get('authorization')==='Bearer '+tokens.get(active.role));active.sent=true;writes++;const r=await network(HOST+url,{...init,headers:{...Object.fromEntries(new Headers(init.headers)),origin:HOST}}),bytes=new Uint8Array(await r.clone().arrayBuffer());recoveryCheck(bytes.length<=4_000_000&&r.headers.get('cache-control')?.includes('no-store'));let response:any;try{response=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes))}catch{}await append('post_outcome',{name:active.name,status:r.status,response,responseObservation:{sha256:hash(bytes),byteLength:bytes.length}});return r}recoveryCheck(method==='GET'&&!init.body);return network(HOST+url,{...init,headers:{...Object.fromEntries(new Headers(init.headers)),origin:HOST}})}) as typeof fetch
  stage='authoritative_failed_state';let current=await read()
  if(input.mode==='baseline'){
   const response=(n:string)=>original.find(e=>e.kind==='post_outcome'&&e.data.name===n)!.data.response,coverage=response('m71_stationary_sources'),roster=response('m76_save_2')
   recoveryCheck(current.corporate.versions.length===6&&current.corporate.headVersionId===coverage.id&&same(core(current.corporate.versions.at(-1)),coverage)&&same(current.corporate.versions.at(-1).review,response('m71_stationary_review')))
   recoveryCheck(current.gas.worksheets.length===2&&current.diesel.worksheets.length===1&&current.equipment.versions.length===2&&current.equipment.reports.length===1&&current.equipment.headVersionId===roster.id&&same(current.equipment.versions.at(-1),roster)&&!current.equipment.reviews.some((r:any)=>r.versionId===roster.id))
   for(const [f,n,review]of[['gas','m73_a_relink','m73_a_review'],['gas','m73_b_save','m73_b_review'],['diesel','m76_diesel_save','m76_diesel_review']]){const v=response(n!),w=current[f!].worksheets.find((w:any)=>w.worksheetId===v.worksheetId);recoveryCheck(w?.headVersionId===v.id&&same(core(w.versions.at(-1)),v)&&same(w.versions.at(-1).review,response(review!)))}
   recoveryCheck(same(current.equipment.reconciliation.findings.map((f:any)=>f.code).sort(),['roster_review_required','source_screening_unresolved'])&&current.equipment.reconciliation.dependencySha256===roster.dependencies.dependencySha256)
   const b=original.find(e=>e.kind==='baseline')!.data;for(const f of ['corporate','gas','mobile','fleet']){const old=f==='gas'||f==='mobile'?b[f].worksheets.flatMap((w:any)=>w.versions):b[f].versions,now=f==='gas'||f==='mobile'?current[f].worksheets.flatMap((w:any)=>w.versions):current[f].versions;for(const v of old)recoveryCheck(same(now.find((n:any)=>n.id===v.id),v))}
   const bytes=await downloads(current);for(const f of ['corporate','gas','mobile','fleet'])for(const [id,value]of Object.entries(b.downloads[f]))recoveryCheck(same(bytes[f][id],value))
   recoveryCheck(input.accounts.find(a=>a.role==='manager1')!.id===coverage.createdBy&&input.accounts.find(a=>a.role==='manager2')!.id===response('m71_stationary_review').reviewerId)
   await append('failed_state_baseline',{originalByteSha256:ORIGINAL_BYTES_SHA256,originalHead:ORIGINAL_HEAD,originalEvents:44,codeSha256:codeSha,recipeSha256:recipeSha,migrationHash:MIGRATION,keys:RECOVERY_KEYS,legacy:legacy.baseline,registers:current,downloads:bytes})
  }else{
   recoveryCheck(same(baseline.legacy,legacy.baseline));const verified=()=>es.filter(e=>e.kind==='step_verified');assertRecoveryProgress(baseline.registers,current,verified());const existingBytes=await downloads(current);for(const f of ['corporate','gas','mobile','fleet','diesel','equipment'])for(const [id,value]of Object.entries(baseline.downloads[f]))recoveryCheck(same(existingBytes[f][id],value))
   if(input.mode==='exercise'&&es.some(e=>e.kind==='recovery_complete')){const complete=es.find(e=>e.kind==='recovery_complete')!.data;recoveryCheck(same(current,complete.registers)&&same(existingBytes,complete.downloads))}
   else if(input.mode==='exercise'){
    const perform=async(name:Operation,family:string,role:'manager1'|'manager2',suffix:string,build:()=>Promise<any>|any,call:(q:any)=>Promise<any>)=>{
     stage=name;current=await read();assertRecoveryProgress(baseline.registers,current,verified());const old=verified().find(e=>e.data.name===name);if(old)return old.data.response
     recoveryCheck(OPERATIONS[verified().length]===name&&!es.some(e=>e.kind==='post_intent'&&e.data.name===name));const request={...await build(),idempotencyKey:RECOVERY_KEYS[name]},route=root+'/'+family+suffix;validateRecoveryRoute(HOST+route,'POST');await append('post_intent',{name,route,role,expected:201,request});active={name,route,role,request,sent:false};const decoded=await call(request);recoveryCheck(active.sent&&same(es.find(e=>e.kind==='post_outcome'&&e.data.name===name)!.data.response,decoded));active=null;current=await read();assertRecoveryProgress(baseline.registers,current,[...verified(),{data:{name,response:decoded}} as Event]);await append('step_verified',{name,response:decoded,verificationBasis:'authorized_state_and_client_decoder'});return decoded
    }
    // Request builders use the authoritative pre-step view already checked by perform.
    current=await exerciseRecovery({company,initial:baseline.registers,actor,read:async()=>current,perform,check:recoveryCheck});recoveryCheck(verified().length===21&&current.equipment.versions.length===5&&current.equipment.reports.length===5&&current.diesel.worksheets[0].versions.length===3&&current.diesel.worksheets[0].reports.length===3&&current.equipment.reconciliation.status==='reconciled_bounded_synthetic'&&current.equipment.reconciliation.rows.length===3&&current.equipment.reconciliation.rows.every((r:any)=>r.status==='matched_reviewed'))
    const bytes=await downloads(current),oldComplete=es.find(e=>e.kind==='recovery_complete');if(oldComplete)recoveryCheck(same(oldComplete.data.registers,current)&&same(oldComplete.data.downloads,bytes));else await append('recovery_complete',{registers:current,downloads:bytes,originalExerciseStatus:'failed',additivePostRequests:21})
   }else{const complete=es.find(e=>e.kind==='recovery_complete')!.data;recoveryCheck(same(current,complete.registers)&&same(await downloads(current),complete.downloads));await append('recovery_revisit',{applicationPostRequests:0,originalExerciseStatus:'failed'})}
  }
 }catch{failed=true}finally{globalThis.fetch=savedFetch;for(const token of tokens.values())try{const r=await network(AUTH+'/auth/v1/logout?scope=local',{method:'POST',headers:{apikey:input.env.SUPABASE_ANON_KEY,authorization:'Bearer '+token}});await r.body?.cancel();if(r.status!==204)closed=false}catch{closed=false}tokens.clear()}
 const allCreatedAuthSessionsClosed=closed&&legacyClosed&&unknownSessions===0;failed||=!allCreatedAuthSessionsClosed
 if(attempt!==null)try{await append('attempt_finished',{attemptSequence:attempt,status:failed?'failed':'passed',stage,applicationPostRequests:writes,allCreatedAuthSessionsClosed})}catch{failed=true;stage='journal_durability'}
 return {status:failed?'failed':'passed',mode:input.mode,stage,applicationPostRequests:writes,allCreatedAuthSessionsClosed,journalSha256:es.at(-1)?.sha256??null}
}
if(import.meta.main){let lock:Awaited<ReturnType<typeof open>>|undefined;try{const input=parseRecoveryInput(JSON.parse(await Bun.stdin.text()));lock=await open(JOURNAL+'.lock','wx',0o600);const r=await runHostedRecovery(input);console.log(JSON.stringify(r));if(r.status!=='passed')process.exitCode=1}catch{console.log(JSON.stringify({status:'failed',stage:'input_or_exclusive_lock'}));process.exitCode=1}finally{if(lock){await lock.close();await unlink(JOURNAL+'.lock')}}}
