import {test,expect} from 'bun:test'
import {parseRecoveryInput,validateRecoveryRoute,readRecoveryJournal,cleanRecoveryJournal,validateOriginalRecoveryJournal,assertRecoveryProgress,runHostedRecovery} from './m76-hosted-recovery'
import {RECOVERY_COMPANY,RECOVERY_PLAN_ID,RECOVERY_PROFILE,RECOVERY_KEYS,OPERATIONS,ORIGINAL_HEAD,recoveryKey,recoveryHash,exerciseRecovery} from './m76-hosted-recovery-recipe'
import {m71CanonicalJson as canonical} from '../../packages/neuvetra-database/src/m71-validation'
const HOST='https://www.neuvetra.ai',AUTH='https://icockcoguyadhryzydvl.supabase.co'
const input=()=>({mode:'baseline',env:{SUPABASE_URL:AUTH,SUPABASE_ANON_KEY:'sb_publishable_'+'a'.repeat(30)},roster:{workspaceId:RECOVERY_COMPANY},accounts:['manager1','manager2','member','outsider'].map((role,i)=>({role,id:`75000000-0000-4000-8000-00000000001${i}`,email:role+'@synthetic.invalid',password:'fictional-local-only'}))})
const line=(es:any[],kind:string,data:any)=>{const body={sequence:es.length+1,previousSha256:es.at(-1)?.sha256??null,profile:RECOVERY_PROFILE,planId:RECOVERY_PLAN_ID,companyId:RECOVERY_COMPANY,mode:'exercise',kind,data,createdAt:'2026-09-16T00:00:00.000Z'};return {...body,sha256:recoveryHash(canonical(body))}}
test('fixed plan and complete21 distinct deterministic keys, independent of time and actor',()=>{
 expect(RECOVERY_PLAN_ID).toBe('3fb96caa-965a-49d1-84d0-8810c10f2fd0');expect(OPERATIONS).toHaveLength(21);expect(new Set(Object.values(RECOVERY_KEYS)).size).toBe(21)
 expect(RECOVERY_KEYS.capture_failed_report).toBe('ef971102-5c97-42cf-8969-91cec78d3eac');expect(RECOVERY_KEYS.correct_corporate_screening).toBe('dd0c8d6b-8a4e-49d8-87a9-9bf270747a65');expect(RECOVERY_KEYS.report_final_equipment).toBe('d46f8400-83b8-4d3b-8589-444399f59fba')
 for(const n of OPERATIONS){expect(RECOVERY_KEYS[n]).toBe(recoveryKey(n));expect(RECOVERY_KEYS[n]).toMatch(/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-8[a-f0-9]{3}-[a-f0-9]{12}$/);expect(RECOVERY_KEYS[n]).not.toBe('52d0209d-04e7-4bc0-b1d2-e21c0bbf79a3')}
})
test('only fixed company and ordinary existing-record successors; creates/admin/mobile/migration refused',()=>{
 expect(parseRecoveryInput(input()).mode).toBe('baseline')
 for(const mode of ['plan','deploy',''])expect(()=>parseRecoveryInput({...input(),mode})).toThrow()
 expect(()=>parseRecoveryInput({...input(),roster:{workspaceId:'75000000-0000-4000-8000-000000000001'}})).toThrow()
 for(const family of ['corporate-inventories','stationary-natural-gas','stationary-diesel','stationary-equipment'])validateRecoveryRoute(`${HOST}/workspace-api/workspace/${RECOVERY_COMPANY}/${family}/${RECOVERY_COMPANY}/versions`,'POST')
 for(const route of ['stationary-diesel','stationary-equipment','stationary-natural-gas',`mobile-diesel/${RECOVERY_COMPANY}/versions`,`controlled-fleet/${RECOVERY_COMPANY}/reports`,`corporate-inventories/${RECOVERY_COMPANY}/reports`,'members','migrations'])expect(()=>validateRecoveryRoute(`${HOST}/workspace-api/workspace/${RECOVERY_COMPANY}/${route}`,'POST')).toThrow()
 expect(()=>validateRecoveryRoute(AUTH+'/auth/v1/admin/users','POST')).toThrow();expect(()=>validateRecoveryRoute('https://evil.invalid/ready','GET')).toThrow()
})
test('uncertain writes, failed decode/durability, changed key/order and unclosed attempts refuse automatic resume',()=>{
 const base:any[]=[];base.push(line(base,'attempt_started',{}));base.push(line(base,'post_intent',{name:OPERATIONS[0],request:{idempotencyKey:RECOVERY_KEYS.capture_failed_report}}));base.push(line(base,'post_outcome',{name:OPERATIONS[0],status:201,response:{id:'saved'}}));base.push(line(base,'step_verified',{name:OPERATIONS[0],response:{id:'saved'}}));base.push(line(base,'attempt_finished',{attemptSequence:1,status:'passed',allCreatedAuthSessionsClosed:true}))
 expect(()=>cleanRecoveryJournal(base)).not.toThrow();const text=base.map(JSON.stringify).join('\n')+'\n';expect(readRecoveryJournal(text)).toHaveLength(5)
 for(const kind of ['post_outcome','step_verified','attempt_finished'])expect(()=>cleanRecoveryJournal(base.filter(e=>e.kind!==kind))).toThrow()
 for(const mutate of [(es:any[])=>es[2].data.status=422,(es:any[])=>es[3].data.response.id='other',(es:any[])=>es[4].data.status='failed',(es:any[])=>es[4].data.allCreatedAuthSessionsClosed=false,(es:any[])=>es[1].data.request.idempotencyKey='other',(es:any[])=>es[1].data.name=OPERATIONS[1]]){const changed=structuredClone(base);mutate(changed);expect(()=>cleanRecoveryJournal(changed)).toThrow()}
 expect(()=>readRecoveryJournal(text.trimEnd())).toThrow();expect(()=>readRecoveryJournal(text.replace('saved','tampered'))).toThrow();expect(()=>validateOriginalRecoveryJournal(text)).toThrow()
})
test('authoritative progress refuses changed immutable cores, reviews, external heads and completed-write substitution',()=>{
 const v=(id:string)=>({id,review:null,immutable:'saved'}),initial:any={corporate:{versions:[v('c')]},gas:{worksheets:[{worksheetId:'a',sourceId:'76e4e7e0-f4c9-40bd-b133-21e534401cae',versions:[v('a')],reports:[]},{worksheetId:'b',sourceId:'heater',versions:[v('b')],reports:[]}]},diesel:{worksheets:[{worksheetId:'d',versions:[v('d')],reports:[]}]},equipment:{versions:[{id:'e',immutable:'saved'}],reviews:[],reports:[]},mobile:{worksheets:[]},fleet:{versions:[],reviews:[],reports:[]}}
 const next=v('c2'),review={id:'r2',versionId:'c2',decision:'accepted'},verified:any[]=[{data:{name:'correct_corporate_screening',response:next}},{data:{name:'review_corporate_screening',response:review}}],current=structuredClone(initial);current.corporate.versions.push({...next,review});current.corporate.headVersionId='c2';for(const f of ['gas','diesel','mobile'])current[f].coverageHeadVersionId='c2';for(const f of ['equipment','fleet'])current[f].proof={coverageVersion:{id:'c2'}}
 expect(()=>assertRecoveryProgress(initial,current,verified)).not.toThrow()
 for(const change of [(s:any)=>s.corporate.versions[1].immutable='changed',(s:any)=>s.corporate.versions[1].review.id='changed',(s:any)=>s.corporate.versions.push(v('external')),(s:any)=>s.equipment.reviews.push({id:'unexpected'}),(s:any)=>s.gas.worksheets[0].versions[0].review={id:'unexpected'},(s:any)=>s.gas.coverageHeadVersionId='mixed-old-head']){const changed=structuredClone(current);change(changed);expect(()=>assertRecoveryProgress(initial,changed,verified)).toThrow()}
})
test('screening correction changes only three existing source rows; all corporate quantities stay null',async()=>{
 const sources=['76e4e7e0-f4c9-40bd-b133-21e534401cae','625a3fd6-4218-426c-97fa-69c1fee862b4','3c8defbc-6c69-4505-963a-72ddc4dd592f'],snapshot={entities:[{id:'retained'}],sources:sources.map(id=>({id,retained:'unchanged'})),coverageItems:[...sources.map((sourceId,i)=>({id:'row'+i,sourceId,domain:'stationary_combustion',disposition:i?'included_activity':'missing',activityDataState:'missing',evidenceState:'missing',methodReadiness:'candidate',reason:null,evidenceRefs:[],quantity:null,unit:null,estimateBasis:null,untouched:'retained'})),{id:'other',domain:'fugitive',disposition:'missing',reason:null,quantity:null,unit:null}],other:{retained:true}}
 const wp=(source:string)=>({id:source,worksheetId:source,activity:{binding:{sourceId:source}},statement:{input:{reference:'synthetic-'+source}}}),initial:any={corporate:{versions:[{snapshot,inventoryId:'inventory',id:'c6',versionSha256:'sha'}]},gas:{worksheets:sources.slice(0,2).map(sourceId=>({sourceId,versions:[wp(sourceId)]}))},diesel:{worksheets:[{versions:[wp(sources[2]!)]}]},equipment:{versions:[{rosterId:'roster'}]}};let request:any
 try{await exerciseRecovery({company:RECOVERY_COMPANY,initial,actor:()=>({}),read:async()=>({}),check:v=>expect(Boolean(v)).toBe(true),perform:async(name,_family,_role,_suffix,build)=>{if(name==='capture_failed_report')return {};request=await build();throw Error('captured before network')}})}catch{}
 expect(request).toBeDefined();expect(request.snapshot.entities).toEqual(snapshot.entities);expect(request.snapshot.sources).toEqual(snapshot.sources);expect(request.snapshot.other).toEqual(snapshot.other)
 for(const item of request.snapshot.coverageItems){const old=snapshot.coverageItems.find(i=>i.id===item.id)!;if(item.domain!=='stationary_combustion'){expect(item).toEqual(old);continue}expect(item.quantity).toBeNull();expect(item.unit).toBeNull();expect(item.estimateBasis).toBeNull();expect(item.disposition).toBe('included_activity');expect(item.activityDataState).toBe('entered');expect(item.evidenceState).toBe('linked');expect(item.reason).toContain(item.sourceId);expect(item.evidenceRefs).toHaveLength(1);const allowed=new Set(['disposition','activityDataState','evidenceState','methodReadiness','reason','evidenceRefs']);for(const key of Object.keys(old))if(!allowed.has(key))expect(item[key]).toEqual((old as any)[key])}
})
test('altered original attempt refuses before network and credentials never enter output',async()=>{
 let calls=0,appends=0;const r=await runHostedRecovery(parseRecoveryInput(input()),{loadOriginal:async()=>ORIGINAL_HEAD,load:async()=>null,fetch:async()=>{calls++;throw Error('network forbidden')},append:async()=>{appends++}});expect(r.status).toBe('failed');expect(calls).toBe(0);expect(appends).toBe(0);expect(JSON.stringify(r)).not.toContain('fictional-local-only')
})
