/** Fixed additive continuation. No import-time IO or connections. */
import {M71_ARTIFACT,M71_LIMITATIONS} from '../../packages/neuvetra-database/src/m71-contract'
import {M71_EVIDENCE_SHA256} from '../../packages/neuvetra-database/src/m71-validation'
import {M73_LIMITATIONS} from '../../packages/neuvetra-database/src/m73-contract'
import {m73SourceChoices} from '../../packages/neuvetra-database/src/m73-validation'
import {M76_LIMITATIONS} from '../../packages/neuvetra-database/src/m76-contract'
import {M76_DIESEL_LIMITATIONS} from '../../packages/neuvetra-database/src/m76-diesel-contract'
import * as corporate from '../../apps/site-web/src/lib/m71-api'
import * as gas from '../../apps/site-web/src/lib/m73-api'
import * as generator from '../../apps/site-web/src/lib/m76-diesel-api'
import * as equipment from '../../apps/site-web/src/lib/m76-api'

export const RECOVERY_COMPANY='8b90c706-1710-494d-b12d-02eef88eacb7'
export const ORIGINAL_BYTES_SHA256='8b1c1ddbcfefbe398bb6b79390029be34aa2782a5a4c2fa4546e783e7b0b5fb3'
export const ORIGINAL_HEAD='b454b9bffca96d58ce7a0ba065f5c72ca603232541503a956d82d9eed760c844'
export const RECOVERY_PROFILE='m76-hosted-recovery-v1'
export const OPERATIONS=['capture_failed_report','correct_corporate_screening','review_corporate_screening','rebind_boiler','review_boiler','rebind_heater','review_heater','rebind_generator','review_rebound_generator','report_rebound_generator','save_reconciled_equipment','review_reconciled_equipment','report_reconciled_equipment','correct_generator_quantity','save_pending_equipment','report_pending_equipment','review_corrected_generator','report_corrected_generator','save_final_equipment','review_final_equipment','report_final_equipment'] as const
export type Operation=typeof OPERATIONS[number]
export const recoveryHash=(value:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(value).digest('hex')
export function recoveryKey(name?:Operation){const chars=recoveryHash(JSON.stringify(name?[RECOVERY_PROFILE,ORIGINAL_HEAD,name]:[RECOVERY_PROFILE,ORIGINAL_HEAD])).slice(0,32).split('');chars[12]='4';chars[16]='8';const s=chars.join('');return `${s.slice(0,8)}-${s.slice(8,12)}-${s.slice(12,16)}-${s.slice(16,20)}-${s.slice(20)}`}
export const RECOVERY_PLAN_ID=recoveryKey()
export const RECOVERY_KEYS=Object.fromEntries(OPERATIONS.map(name=>[name,recoveryKey(name)])) as Record<Operation,string>
type Context={company:string;initial:any;actor:(role:'manager1'|'manager2')=>any;read:()=>Promise<any>;perform:(name:Operation,family:string,role:'manager1'|'manager2',suffix:string,build:()=>Promise<any>|any,call:(request:any)=>Promise<any>)=>Promise<any>;check:(value:unknown)=>void}
export async function exerciseRecovery(c:Context){
 const {company,initial,perform,actor,check}=c,cv=initial.corporate.versions.at(-1),roster=initial.equipment.versions.at(-1),boiler=initial.gas.worksheets.find((w:any)=>w.sourceId==='76e4e7e0-f4c9-40bd-b133-21e534401cae').versions.at(-1),heater=initial.gas.worksheets.find((w:any)=>w.sourceId==='625a3fd6-4218-426c-97fa-69c1fee862b4').versions.at(-1),diesel=initial.diesel.worksheets[0].versions.at(-1)
 const sourceIds=[boiler.activity.binding.sourceId,heater.activity.binding.sourceId,diesel.activity.binding.sourceId]
 const sourceReport=(name:Operation,v:any,r:any)=>perform(name,'stationary-diesel','manager1',`/${v.worksheetId}/reports`,()=>({versionId:v.id,expectedVersionSha256:v.versionSha256,expectedDecisionId:r.id,expectedDecisionSha256:r.decisionSha256}),q=>generator.generatorReportRequest(actor('manager1'),company,v.worksheetId,q))
 const equipmentReport=(name:Operation)=>perform(name,'stationary-equipment','manager1',`/${roster.rosterId}/reports`,async()=>({expectedReconciliationSha256:(await c.read()).equipment.reconciliation.contentSha256}),q=>equipment.stationaryReportRequest(actor('manager1'),company,roster.rosterId,q))
 await equipmentReport('capture_failed_report')
 const coverage=await perform('correct_corporate_screening','corporate-inventories','manager1',`/${cv.inventoryId}/versions`,()=>{
  const snapshot=structuredClone(cv.snapshot)
  for(const id of sourceIds){const item=snapshot.coverageItems.find((i:any)=>i.sourceId===id&&i.domain==='stationary_combustion');check(item);const v=id===sourceIds[0]?boiler:id===sourceIds[1]?heater:diesel;item.disposition='included_activity';item.activityDataState='entered';item.evidenceState='linked';item.methodReadiness='candidate';item.reason=`Retained synthetic dedicated stationary source ${id}; consumed-fuel statement ${v.statement.input.reference} and separately accepted workpaper ${v.id} support entered activity. Corporate quantity and method release remain undetermined.`;item.evidenceRefs=[{artifactId:M71_ARTIFACT.id,expectedSha256:M71_EVIDENCE_SHA256,locator:M71_ARTIFACT.locator,purpose:`Fictional source screening for retained source ${id}; synthetic statement ${v.statement.input.reference}, not independent measurement.`}]}
  return {snapshot,expectedVersionId:cv.id,expectedVersionSha256:cv.versionSha256,correctionReason:'Correct inherited missing boiler screening and record retained entered heater/generator activity from separate synthetic evidence; preserve all other coverage.'}
 },q=>corporate.corporateSaveRequest(actor('manager1'),company,cv.inventoryId,q))
 await perform('review_corporate_screening','corporate-inventories','manager2',`/${cv.inventoryId}/reviews`,()=>({versionId:coverage.id,expectedVersionSha256:coverage.versionSha256,decision:'accepted_bounded_internal',note:'Separate bounded synthetic source-screening review grounded in retained statements; corporate coverage remains incomplete.',acknowledgedLimitations:[...M71_LIMITATIONS]}),q=>corporate.corporateReviewRequest(actor('manager2'),company,cv.inventoryId,q))
 const binding=async(source:string)=>{const current=(await c.read()).corporate.versions.at(-1);check(current.id===coverage.id);const choice=m73SourceChoices(current).find(x=>x.binding.sourceId===source);check(choice?.eligible);return choice!.binding}
 for(const [v,save,review]of[[boiler,'rebind_boiler','review_boiler'],[heater,'rebind_heater','review_heater']] as const){const next=await perform(save,'stationary-natural-gas','manager1',`/${v.worksheetId}/versions`,async()=>({...v.activity,binding:await binding(v.activity.binding.sourceId),expectedVersionId:v.id,expectedVersionSha256:v.versionSha256,correctionReason:'Rebind unchanged dedicated synthetic consumption to separately reviewed corrected source screening.'}),q=>gas.gasSaveRequest(actor('manager1'),company,v.worksheetId,q));await perform(review,'stationary-natural-gas','manager2',`/${v.worksheetId}/reviews`,()=>({versionId:next.id,expectedVersionSha256:next.versionSha256,decision:'accepted_bounded_internal',note:'Separate review of unchanged synthetic dedicated consumption at corrected current coverage.',acknowledgedLimitations:[...M73_LIMITATIONS]}),q=>gas.gasReviewRequest(actor('manager2'),company,v.worksheetId,q))}
 const rebound=await perform('rebind_generator','stationary-diesel','manager1',`/${diesel.worksheetId}/versions`,async()=>({...diesel.activity,binding:await binding(diesel.activity.binding.sourceId),expectedVersionId:diesel.id,expectedVersionSha256:diesel.versionSha256,correctionReason:'Rebind unchanged fixed-generator consumption/evidence to separately reviewed corrected screening.'}),q=>generator.generatorSaveRequest(actor('manager1'),company,diesel.worksheetId,q))
 const reviewGenerator=(name:Operation,v:any)=>perform(name,'stationary-diesel','manager2',`/${v.worksheetId}/reviews`,()=>({versionId:v.id,expectedVersionSha256:v.versionSha256,decision:'accepted_bounded_internal',note:'Separate exact synthetic generator evidence/default-HHV review; no released method or completeness assertion.',acknowledgedLimitations:[...M76_DIESEL_LIMITATIONS]}),q=>generator.generatorReviewRequest(actor('manager2'),company,v.worksheetId,q))
 await sourceReport('report_rebound_generator',rebound,await reviewGenerator('review_rebound_generator',rebound))
 const saveEquipment=(name:Operation,prior:any,reason:string)=>perform(name,'stationary-equipment','manager1',`/${roster.rosterId}/versions`,async()=>({...roster.activity,coverageVersionId:coverage.id,coverageVersionSha256:coverage.versionSha256,expectedDependencySha256:(await c.read()).equipment.reconciliation.dependencySha256,expectedVersionId:prior.id,expectedVersionSha256:prior.versionSha256,correctionReason:reason}),q=>equipment.stationarySaveRequest(actor('manager1'),company,roster.rosterId,q))
 const reviewEquipment=(name:Operation,v:any)=>perform(name,'stationary-equipment','manager2',`/${roster.rosterId}/reviews`,async()=>({versionId:v.id,expectedVersionSha256:v.versionSha256,expectedDependencySha256:(await c.read()).equipment.reconciliation.dependencySha256,decision:'accepted_bounded_reconciliation',note:'Exact retained independent declaration matches all three separately accepted current stationary workpapers.',acknowledgedLimitations:[...M76_LIMITATIONS]}),q=>equipment.stationaryReviewRequest(actor('manager2'),company,roster.rosterId,q))
 const positive=await saveEquipment('save_reconciled_equipment',roster,'Rebind the independently retained declaration to corrected corporate screening and all current separate source reviews.')
 await reviewEquipment('review_reconciled_equipment',positive);await equipmentReport('report_reconciled_equipment')
 const corrected=await perform('correct_generator_quantity','stationary-diesel','manager1',`/${diesel.worksheetId}/versions`,()=>({...rebound.activity,quantityGallons:'1001.000',statement:{...rebound.activity.statement,reference:'M76-HOSTED-GENERATOR-FUEL-2025-CORRECTED',statedQuantityGallons:'1001.000'},expectedVersionId:rebound.id,expectedVersionSha256:rebound.versionSha256,correctionReason:'Correct fictional direct-generator consumption from matching evidence; a new separate review is required.'}),q=>generator.generatorSaveRequest(actor('manager1'),company,diesel.worksheetId,q))
 const pending=await saveEquipment('save_pending_equipment',positive,'Capture corrected generator consumption while the exact new source review remains absent.');await equipmentReport('report_pending_equipment')
 await sourceReport('report_corrected_generator',corrected,await reviewGenerator('review_corrected_generator',corrected))
 const final=await saveEquipment('save_final_equipment',pending,'Capture separate corrected-generator approval; obtain fresh exact declaration acceptance.')
 await reviewEquipment('review_final_equipment',final);await equipmentReport('report_final_equipment')
 return c.read()
}
