/** Frozen failed-run admission and exact additive closure. No IO on import. */
import {readM77Journal,cleanM77Journal,preservesM77History,validateM77JourneyRoute} from './check-m77-hosted'
import {decodeCorporateVersion,decodeCorporateReview} from '../../apps/site-web/src/lib/m71-api'
import {validateM71Save,validateM71Review} from '../../packages/neuvetra-database/src/m71-validation'
import {decodeFugitiveVersion,decodeFugitiveReport} from '../../apps/site-web/src/lib/m77-api'
import {m77CanonicalJson as canonical,validateM77SourceSave,validateM77PopulationSave,validateM77Review,validateM77Report} from '../../packages/neuvetra-database/src/m77-validation'
export const M77_FAILED_PIN={journalSha256:'84107d09d979d0a5086a575642ddd1f3d596f75213886588f909b047933860ba',headSha256:'b43bfb5b5dc1688324a8734bcc99342a5c273a0c89d4245123ee09b113cb26ad'}
export const continuationCheck=(v:unknown):void=>{if(!v)throw Error('M77 continuation integrity refused.')}
export const continuationHash=(v:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(v).digest('hex')
export const continuationSame=(a:unknown,b:unknown)=>canonical(a)===canonical(b)
export const continuationCore=(v:any)=>'review'in v?{...v,review:null}:v
export const M77_FAILED_NAMES=['m77_corporate_add_sources','m77_corporate_review','m77_member_save_refused','m77_outsider_save_refused','m77_signed_out_save_refused',...Array.from({length:5},(_,i)=>'m77_source_initial_'+i),'m77_unknown_source_report','m77_population_unknown','m77_population_contributor_review_refused','m77_population_member_review_refused','m77_population_blocked_accept_refused','m77_population_unknown_report','m77_fire_known_correction','m77_known_source_pending_report',...Array.from({length:5},(_,i)=>'m77_source_review_'+i),'m77_known_source_accepted_report','m77_population_known','m77_population_known_review','m77_population_known_report','m77_hvac_mass_correction','m77_corrected_source_pending_report','m77_population_corrected_pending','m77_population_corrected_pending_report','m77_corrected_hvac_review','m77_corrected_source_accepted_report']
export async function inspectM77Failure(text:string,company:string,pin=M77_FAILED_PIN){
 const check=continuationCheck,same=continuationSame,es=readM77Journal(text,company);check(continuationHash(text)===pin.journalSha256&&es.length===74&&es.at(-1)?.sha256===pin.headSha256);cleanM77Journal(es.slice(0,4));check(es[2]?.kind==='baseline'&&es[4]?.kind==='attempt_started'&&es[4].mode==='exercise'&&es[4].data.mode==='exercise'&&es[5]?.kind==='actual_readiness'&&es[5].data.schemaVersion===20&&es[6]?.kind==='plan');
 const finish=es.at(-1)!;check(finish.kind==='attempt_finished'&&finish.mode==='exercise'&&finish.data.attemptSequence===5&&finish.data.status==='failed'&&finish.data.applicationPostRequests===33&&finish.data.allCreatedAuthSessionsClosed===true&&finish.data.stage==='authorized_read:/mobile-diesel');
 const pairs:any[]=[];for(let n=0;n<33;n++){const i=es[7+n*2]!,o=es[8+n*2]!;check(i.kind==='post_intent'&&o.kind==='post_outcome'&&i.mode==='exercise'&&o.mode==='exercise'&&i.data.name===M77_FAILED_NAMES[n]&&same({name:i.data.name,route:i.data.route,role:i.data.role,expected:i.data.expected},{name:o.data.name,route:o.data.route,role:o.data.role,expected:o.data.expected})&&o.data.status===i.data.expected);validateM77JourneyRoute('https://www.neuvetra.ai'+i.data.route,'POST',company);
  const r=i.data.request,v=o.data.response;check(r&&typeof r.idempotencyKey==='string');if(i.data.expected!==201){check([401,403,422].includes(i.data.expected)&&v===undefined&&/^[a-f0-9]{64}$/.test(o.data.responseObservation?.sha256)&&Number.isInteger(o.data.responseObservation?.byteLength));pairs.push({intent:i,outcome:o});continue}
  if(n===0){const d=await decodeCorporateVersion(v,company),request=validateM71Save(r);check(same(d.snapshot,request.snapshot)&&d.previousVersionId===r.expectedVersionId&&d.previousVersionSha256===r.expectedVersionSha256)}
  else if(n===1){validateM71Review(r);const d=await decodeCorporateReview(v,company);check(d.versionId===r.versionId&&d.versionSha256===r.expectedVersionSha256&&d.decision===r.decision&&d.note===r.note&&same(d.acknowledgedLimitations,r.acknowledgedLimitations))}
  else if(i.data.route.endsWith('/reports')){validateM77Report(r);const d=await decodeFugitiveReport(v,company),s=JSON.parse(d.snapshotJson);check(d.versionId===r.versionId&&d.versionSha256===r.expectedVersionSha256&&(s.review?.id??null)===r.expectedDecisionId&&(s.review?.decisionSha256??null)===r.expectedDecisionSha256&&(s.reconciliation?.contentSha256??null)===r.expectedReconciliationSha256)}
  else if(i.data.route.endsWith('/reviews')){validateM77Review(r);check(v.versionId===r.versionId&&v.versionSha256===r.expectedVersionSha256&&v.decision===r.decision&&v.note===r.note&&same(v.acknowledgedLimitations,r.acknowledgedLimitations))}
  else{const d=await decodeFugitiveVersion(v,company),validated=d.family==='source'?validateM77SourceSave(r):validateM77PopulationSave(r),activity:any={...validated};for(const k of ['expectedVersionId','expectedVersionSha256','correctionReason','idempotencyKey','expectedDependencySha256'])delete activity[k];check(same(d.activity,activity)&&d.previousVersionId===r.expectedVersionId&&d.previousVersionSha256===r.expectedVersionSha256&&d.correctionReason===r.correctionReason)}pairs.push({intent:i,outcome:o})
 }
 check(pairs.filter(p=>p.outcome.data.status===201).length===27);return {events:es,pairs,baseline:es[2]!.data,pin,company}
}
export function assertM77ContinuationActors(failed:Pick<Awaited<ReturnType<typeof inspectM77Failure>>,'pairs'>,accounts:{role:string;id:string}[]){const preparer=failed.pairs.find(p=>p.intent.data.name==='m77_corporate_add_sources')?.outcome.data.response.createdBy,reviewer=failed.pairs.find(p=>p.intent.data.name==='m77_corrected_hvac_review')?.outcome.data.response.reviewerId;continuationCheck(preparer&&reviewer&&accounts.find(a=>a.role==='manager1')?.id===preparer&&accounts.find(a=>a.role==='manager2')?.id===reviewer);for(const p of failed.pairs.filter(p=>p.outcome.data.status===201)){const actor=p.outcome.data.response.createdBy??p.outcome.data.response.reviewerId;continuationCheck(actor===accounts.find(a=>a.role===p.intent.data.role)?.id)}}
export function verifyM77ContinuationOutcomeClosure(events:any[],current:any){const check=continuationCheck,same=continuationSame,posts=events.filter(e=>e.kind==='post_intent'),outcomes=events.filter(e=>e.kind==='post_outcome'),pop=current.fugitive.population.versions.at(-1);check(posts.length===3&&outcomes.length===3);const v=outcomes[0].data.response,review=outcomes[1].data.response,report=outcomes[2].data.response;check(same(continuationCore(v),continuationCore(pop))&&same(review,pop.review)&&same(report,current.fugitive.population.reports.find((r:any)=>r.id===report.id)));const request=validateM77PopulationSave(posts[0].data.request),activity:any={...request};for(const k of ['expectedDependencySha256','expectedVersionId','expectedVersionSha256','correctionReason','idempotencyKey'])delete activity[k];check(same(activity,pop.activity)&&request.expectedDependencySha256===pop.dependencies.dependencySha256&&request.expectedVersionId===pop.previousVersionId&&request.expectedVersionSha256===pop.previousVersionSha256&&request.correctionReason===pop.correctionReason);const r=validateM77Review(posts[1].data.request);check(r.versionId===pop.id&&r.expectedVersionSha256===pop.versionSha256&&r.expectedDependencySha256===pop.dependencies.dependencySha256&&r.decision===review.decision&&r.note===review.note&&same(r.acknowledgedLimitations,review.acknowledgedLimitations));const q=validateM77Report(posts[2].data.request),snapshot=JSON.parse(report.snapshotJson);check(q.versionId===pop.id&&q.expectedVersionSha256===pop.versionSha256&&q.expectedDecisionId===review.id&&q.expectedDecisionSha256===review.decisionSha256&&q.expectedReconciliationSha256===snapshot.reconciliation.contentSha256)}
/** Fresh server records must account for every admitted write, with no unexplained successor. */
export function verifyM77FailureState(failed:Awaited<ReturnType<typeof inspectM77Failure>>,current:any,continued=false){
 const check=continuationCheck,same=continuationSame,core=continuationCore;preservesM77History(failed.baseline,current);const success=failed.pairs.filter(p=>p.outcome.data.status===201).map(p=>p.outcome.data.response),versions=success.filter(v=>v.family&&v.activity),reports=success.filter(v=>v.rendererVersion==='m77-retained-report-v1'),reviews=success.filter(v=>v.decision&&v.versionId),all=[...current.fugitive.worksheets.flatMap((w:any)=>w.versions),...current.fugitive.population.versions],allReports=[...current.fugitive.worksheets.flatMap((w:any)=>w.reports),...current.fugitive.population.reports];
 const byId=(rows:any[],key='id')=>[...rows].sort((a,b)=>a[key]<b[key]?-1:a[key]>b[key]?1:0);for(const family of ['gas','mobile','fleet','diesel','equipment']){const old=failed.baseline[family],now=current[family];for(const k of ['versions','reviews','reports'])if(k in old)check(same(byId(old[k]),byId(now[k])));if(old.worksheets){const stable=(rows:any[])=>byId(rows.map(w=>{const {findings,...retained}=w;return {...retained,versions:byId(w.versions),reports:byId(w.reports)}}),'worksheetId');check(same(stable(old.worksheets),stable(now.worksheets)))}}
 const corporate=success[0],corpReview=success[1],cv=current.corporate.versions.at(-1);check(current.corporate.versions.length===failed.baseline.corporate.versions.length+1&&same(core(corporate),core(cv))&&same(cv.review,corpReview));for(const v of failed.baseline.corporate.versions)check(same(v,current.corporate.versions.find((x:any)=>x.id===v.id)));
 for(const v of versions){const saved=all.find((x:any)=>x.id===v.id);check(saved&&same(core(saved),core(v)));const review=reviews.find(r=>r.versionId===v.id);check(same(saved.review,review??null))}for(const r of reports)check(same(allReports.find((x:any)=>x.id===r.id),r));
 check(current.fugitive.worksheets.length===5&&current.fugitive.worksheets.flatMap((w:any)=>w.versions).length===7&&current.fugitive.population.versions.length===(continued?4:3)&&allReports.length===(continued?9:8)&&all.length===versions.length+(continued?1:0));
 const sourceHeads=current.fugitive.worksheets.map((w:any)=>w.versions.at(-1));check(sourceHeads.every((v:any)=>v.review?.decision==='accepted_bounded_internal'));const hvac=sourceHeads.find((v:any)=>v.activity.assetId==='M77-HOSTED-OFFICE-HVAC');check(hvac?.calculation.kg_co2e_display==='3848.0000'&&hvac.calculation.known_release_count===1);
 if(!continued){const pop=versions.filter(v=>v.family==='population').at(-1);check(current.fugitive.population.headVersionId===pop.id&&current.fugitive.reconciliation.status==='blocked')}else{const pop=current.fugitive.population.versions.at(-1),prior=versions.filter(v=>v.family==='population').at(-1);check(pop.previousVersionId===prior.id&&pop.previousVersionSha256===prior.versionSha256&&same(pop.activity,prior.activity)&&pop.review?.decision==='accepted_bounded_reconciliation'&&pop.dependencies.dependencySha256===current.fugitive.reconciliation.dependencySha256&&current.fugitive.reconciliation.status==='reconciled_bounded_synthetic')}
 return current
}
