/** Fictional demonstration inputs only. Importing this module performs no IO or writes. */
import {M71_ARTIFACT,type M71Version} from '../../packages/neuvetra-database/src/m71-contract'
import {M71_EVIDENCE_SHA256,validateM71Snapshot} from '../../packages/neuvetra-database/src/m71-validation'
import {M78_CATEGORIES,M78_GAS_GROUPS,M78_PROCESS_PROFILE,M78_PERIOD,type M78Register,type M78ProcessActivity,type M78EvidenceInput} from '../../packages/neuvetra-database/src/m78-contract'
import {m78ProcessActivity,validateM78ProcessSave} from '../../packages/neuvetra-database/src/m78-validation'
import {buildM78Dependencies} from '../../packages/neuvetra-database/src/m78-reconciliation'
import {M71_LIMITATIONS} from '../../packages/neuvetra-database/src/m71-contract'
import {M73_LIMITATIONS} from '../../packages/neuvetra-database/src/m73-contract'
import {M74_LIMITATIONS} from '../../packages/neuvetra-database/src/m74-contract'
import {M75_LIMITATIONS} from '../../packages/neuvetra-database/src/m75-contract'
import {M76_LIMITATIONS} from '../../packages/neuvetra-database/src/m76-contract'
import {M76_DIESEL_LIMITATIONS} from '../../packages/neuvetra-database/src/m76-diesel-contract'
import {M77_LIMITATIONS} from '../../packages/neuvetra-database/src/m77-contract'
import {M78_LIMITATIONS,M78_INVENTORY_PROFILE,type M78Version,type M78VersionEnvelope} from '../../packages/neuvetra-database/src/m78-contract'
import {m78CanonicalJson} from '../../packages/neuvetra-database/src/m78-validation'
const assert=(value:unknown,message:string)=>{if(!value)throw Error(message)}

import {m78FactualCorporateSuccessor,m78FictionalDiscovery,type M78HostedContext} from './m78-hosted-plan'

export const M78_COMMITTED_INITIAL={id:'3e45de5d-d312-4a22-8418-35cb740a3a12',versionSha256:'977fdd9d6a5cffb07bea34ff3bee2afaadfe3cf120440cc148a2ed45501bee6e'}as const
export function assertM78ContinuationBaseline(r:M78Register){const v=r.inventory.versions[0];assert(r.process.versions.length===0&&r.process.reports.length===0&&r.inventory.versions.length===1&&r.inventory.reports.length===0,'Continuation requires exactly the observed sole inventory version and no reports/process.');assert(v&&v.id===M78_COMMITTED_INITIAL.id&&v.versionSha256===M78_COMMITTED_INITIAL.versionSha256&&v.version===1&&v.family==='inventory'&&v.review===null&&v.previousVersionId===null&&v.reconciliation?.status==='blocked'&&v.reconciliation.totals===null,'Exact committed first inventory required.');assert(r.coverageVersion.version===8&&r.proof.sourceVersions.length===10&&r.proof.fugitive.version?.version===4,'Preserved completed-M77 graph required.')}
export async function continueM78(c:M78HostedContext){
 const hash=(value:unknown)=>new Bun.CryptoHasher('sha256').update(m78CanonicalJson(value)).digest('hex')
 const reviewer=(v:{contributorIds:string[]})=>{const account=c.accounts.find(a=>['manager1','manager2'].includes(a.role)&&!v.contributorIds.includes(a.id));assert(account,'No eligible separate manager is configured.');return account!.role}
 const key=()=>crypto.randomUUID(),root=c.root
 let r=await c.scope1();assertM78ContinuationBaseline(r)
 const bound=(r:M78Register)=>{const item=r.coverageVersion.snapshot.coverageItems.find(i=>i.domain==='process'&&i.entityId===null&&i.sourceId===null);assert(item,'Exact corporate process row missing.');return {coverageVersionId:r.coverageVersion.id,coverageVersionSha256:r.coverageVersion.versionSha256,processCoverageItemId:item!.id,period:M78_PERIOD}}
 const report=async(name:string,v:M78Version)=>c.post(name,`${root}/${v.family==='process_screen'?'process-screen':'scope1-inventory'}/${v.streamId}/reports`,'manager1',{versionId:v.id,expectedVersionSha256:v.versionSha256,expectedDecisionId:v.review?.id??null,expectedDecisionSha256:v.review?.decisionSha256??null,expectedReconciliationSha256:v.reconciliation?.contentSha256??null,idempotencyKey:key()})
 const inventory=async(name:string,note:string,reason:string|null)=>{r=await c.scope1();const prior=r.inventory.versions[r.inventory.versions.length-1];return (await c.post(name,root+'/scope1-inventory'+(prior?`/${prior.streamId}/versions`:''),'manager1',{profile:M78_INVENTORY_PROFILE,binding:bound(r),note,expectedVersionId:prior?.id??null,expectedVersionSha256:prior?.versionSha256??null,expectedDependencySha256:r.dependencies.dependencySha256,correctionReason:reason,idempotencyKey:key()}) as M78VersionEnvelope).version}
 const initial=r.inventory.versions[0]!
 assert(initial.reconciliation?.status==='blocked'&&initial.reconciliation.totals===null,'Baseline unexpectedly reconciled; stop and inspect.')
 await report('m78_initial_unreviewed_report',initial)
 const old=r.coverageVersion,snapshot=m78FactualCorporateSuccessor(old)
 const corporate=await c.post('m78_factual_corporate_successor',`${root}/corporate-inventories/${old.inventoryId}/versions`,'manager1',{snapshot,expectedVersionId:old.id,expectedVersionSha256:old.versionSha256,correctionReason:'Apply retained fictional annual ownership and operational-control facts to the subsidiary relationship and complete entity boundaries; retain every source and facility.',idempotencyKey:key()}) as M71Version
 await c.post('m78_corporate_separate_review',`${root}/corporate-inventories/${corporate.inventoryId}/reviews`,reviewer(corporate),{versionId:corporate.id,expectedVersionSha256:corporate.versionSha256,decision:'accepted_bounded_internal',note:'Separate review of the exact fictional full-year ownership/control evidence and preserved complete corporate identity graph. Quantities, requirements and external assurance remain outside this decision.',acknowledgedLimitations:[...M71_LIMITATIONS],idempotencyKey:key()})
 r=await c.scope1()
 assert(r.proof.sourceVersions.length===10,'The ten-source baseline changed; inspect before continuing.')
 const families={natural_gas:{path:'stationary-natural-gas',limitations:M73_LIMITATIONS},stationary_diesel:{path:'stationary-diesel',limitations:M76_DIESEL_LIMITATIONS},mobile_diesel:{path:'mobile-diesel',limitations:M74_LIMITATIONS},fugitive:{path:'fugitive-sources',limitations:M77_LIMITATIONS}}
 for(const {family,version}of r.proof.sourceVersions){const v=version as any,config=families[family],stream=v.worksheetId??v.streamId,newActivity={...v.activity,binding:{...v.activity.binding,coverageVersionId:corporate.id,coverageVersionSha256:corporate.versionSha256}},source=corporate.snapshot.sources.find(s=>s.id===v.activity.binding.sourceId);assert(source&&source.entityId===v.activity.binding.entityId&&source.facilityId===v.activity.binding.facilityId,'Source identity changed.');const next=await c.post(`m78_rebind_${family}_${source!.id}`,`${root}/${config.path}/${stream}/versions`,'manager1',{...newActivity,expectedVersionId:v.id,expectedVersionSha256:v.versionSha256,correctionReason:'Rebind unchanged fictional source activity and evidence to the exact separately reviewed corporate control successor.',idempotencyKey:key()});const beforeTotal=family==='fugitive'?v.calculation?.kg_co2e_exact:v.calculation?.total.unrounded,afterTotal=family==='fugitive'?next.calculation?.kg_co2e_exact:next.calculation?.total.unrounded;assert(beforeTotal!==undefined&&beforeTotal===afterTotal,'Unchanged source quantity no longer reproduces its exact result.');await c.post(`m78_review_${family}_${source!.id}`,`${root}/${config.path}/${stream}/reviews`,reviewer(next),{versionId:next.id,expectedVersionSha256:next.versionSha256,...(family==='fugitive'?{expectedDependencySha256:null}:{}),decision:'accepted_bounded_internal',note:'Separate exact source review after corporate rebinding. Retained fictional activity, evidence and unrounded result are unchanged; methods remain candidates and this is not external assurance.',acknowledgedLimitations:[...config.limitations],idempotencyKey:key()})}
 for(const family of ['fleet','stationary','fugitive'] as const){r=await c.scope1();const d=r.proof[family],v=d.version as any;assert(v,'The retained physical discovery register is missing.');const path=family==='fleet'?'controlled-fleet':family==='stationary'?'stationary-equipment':'fugitive-population',stream=v.rosterId??v.streamId,limitations=family==='fleet'?M75_LIMITATIONS:family==='stationary'?M76_LIMITATIONS:M77_LIMITATIONS,next=await c.post(`m78_rebind_${family}_discovery`,`${root}/${path}/${stream}/versions`,'manager1',{...v.activity,coverageVersionId:corporate.id,coverageVersionSha256:corporate.versionSha256,expectedDependencySha256:d.reconciliation.dependencySha256,expectedVersionId:v.id,expectedVersionSha256:v.versionSha256,correctionReason:'Retain the complete physical population and rebind its unchanged facts to current reviewed corporate and source versions.',idempotencyKey:key()});await c.post(`m78_review_${family}_discovery`,`${root}/${path}/${stream}/reviews`,reviewer(next),{versionId:next.id,expectedVersionSha256:next.versionSha256,expectedDependencySha256:next.dependencies.dependencySha256,decision:'accepted_bounded_reconciliation',note:'Separate review of the complete fictional physical union, preserved locations and exact current source decisions; no additional emissions components or release approval.',acknowledgedLimitations:[...limitations],idempotencyKey:key()})}
 r=await c.scope1();const activity=m78FictionalDiscovery(r,hash),process=(await c.post('m78_complete_process_discovery',root+'/process-screen','manager1',{...activity,expectedVersionId:null,expectedVersionSha256:null,expectedDependencySha256:buildM78Dependencies(r.proof,'process_screen',hash).dependencySha256,correctionReason:null,idempotencyKey:key()}) as M78VersionEnvelope).version
 assert(process.findings.every(f=>f.classification!=='functional_blocker'),'Fictional discovery remains blocked; do not accept.')
 await report('m78_process_unreviewed_report',process)
 const processReview=await c.post('m78_process_separate_review',`${root}/process-screen/${process.streamId}/reviews`,reviewer(process),{versionId:process.id,expectedVersionSha256:process.versionSha256,expectedDependencySha256:process.dependencies.dependencySha256,decision:'accepted_bounded_process_screen',note:'Separate review of the exact complete fictional facility/off-site process and seven-gas matrix, location-specific evidence, complete physical populations and current source bindings. No customer applicability or external assurance is asserted.',acknowledgedLimitations:[...M78_LIMITATIONS],idempotencyKey:key()})
 await report('m78_process_reviewed_report',{...process,review:processReview})
 const complete=await inventory('m78_current_inventory_successor','Retain the reconciled complete fictional ten-source union and independently screened process/seven-gas coverage. Exact compatible gross results are candidates; release readiness remains incomplete.','Replace the unresolved baseline with current separately reviewed corporate, source, discovery and process evidence; preserve the original blocked version and report.')
 assert(complete.reconciliation?.status==='reconciled_bounded_synthetic'&&complete.reconciliation.totals!==null&&complete.reconciliation.sourceUnion.length===10,'Full fictional Scope 1 union did not reconcile; do not accept.')
 await report('m78_inventory_unreviewed_report',complete)
 const inventoryReview=await c.post('m78_inventory_separate_review',`${root}/scope1-inventory/${complete.streamId}/reviews`,reviewer(complete),{versionId:complete.id,expectedVersionSha256:complete.versionSha256,expectedDependencySha256:complete.dependencies.dependencySha256,decision:'accepted_bounded_inventory',note:'Separate exact internal review of the complete fictional source union, gross unrounded gas/source/facility/entity/company reconciliation, retained seven-gas evidence and candidate method compatibility. Customer evidence, production methods, applicable requirements and external assurance remain incomplete.',acknowledgedLimitations:[...M78_LIMITATIONS],idempotencyKey:key()})
 await report('m78_inventory_reviewed_report',{...complete,review:inventoryReview})
 return c.scope1()
}

