/** Post-restart GET-only revisit adapter. Imports are inert; root owns credentials, locks and execution. */
import {decodeScope1Register,decodeScope1Report} from '../../apps/site-web/src/lib/m78-api';
import {decodeCorporateRegister} from '../../apps/site-web/src/lib/m71-api';
import {decodeGasRegister} from '../../apps/site-web/src/lib/m73-api';
import {decodeMobileRegister} from '../../apps/site-web/src/lib/m74-api';
import {decodeFleetRegister} from '../../apps/site-web/src/lib/m75-api';
import {decodeGeneratorRegister} from '../../apps/site-web/src/lib/m76-diesel-api';
import {decodeStationaryRegister} from '../../apps/site-web/src/lib/m76-api';
import {decodeFugitiveRegister} from '../../apps/site-web/src/lib/m77-api';
import {m78CanonicalJson as canonical} from '../../packages/neuvetra-database/src/m78-validation';
import {M78_READONLY_RECOVERY_LOCK,M78_READONLY_RECOVERY_PATHS,runM78Continuation4ReadonlyRecovery,type RecoveryIO} from './check-m78-continuation4-readonly-recovery';
import {verifyM78Continuation4ReadonlyRecovery,type RecoveryReviewAdmission} from '../../evaluations/research-qa/m78-continuation4-readonly-recovery-independent-review';

export const M78_READONLY_REVISIT_RUNTIME={commit:'9dd9c85fb674528a2c1dd1b0138f5a2d87ba683e',deploymentId:'f6d77b2e-6886-429b-a4d2-4873c9199ce8',imageDigest:'sha256:3e4c2c91591a5598a85f63b4099b1b4890588ce79ec832b21b7d284b5aa89d1b'}as const;
export const M78_READONLY_REVISIT_PATHS={journal:'.superpowers/m78-continuation4-readonly-revisit.jsonl',diagnostics:'.superpowers/m78-continuation4-readonly-revisit-diagnostics.jsonl',observation:'.superpowers/m78-continuation4-readonly-revisit-observation.json'}as const;
export const M78_READONLY_REVISIT_LOCK=M78_READONLY_REVISIT_PATHS.journal+'.lock';
const sha=(value:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(value).digest('hex');
const check:(value:unknown,message:string)=>asserts value=(value,message)=>{if(!value)throw Error(message)};
const same=(a:unknown,b:unknown)=>canonical(a)===canonical(b);
const runtime=(value:any)=>value&&value.commit===M78_READONLY_REVISIT_RUNTIME.commit&&value.deploymentId===M78_READONLY_REVISIT_RUNTIME.deploymentId&&value.imageDigest===M78_READONLY_REVISIT_RUNTIME.imageDigest;
type RecoveryInputs=Parameters<typeof verifyM78Continuation4ReadonlyRecovery>[0];
type RecoveryRunInput=Parameters<typeof runM78Continuation4ReadonlyRecovery>[0];
export type AcceptedRecovery={inputs:RecoveryInputs;admission:RecoveryReviewAdmission;resultText:string;resultSha256:string;lockSha256:string};
export type RestartEvidence={admissionText:string;admissionSha256:string;requestText:string;requestSha256:string;startupText:string;startupSha256:string;independentText:string;independentSha256:string};
export type RevisitInput={acceptedRecovery:AcceptedRecovery;restart:RestartEvidence;runner:Omit<RecoveryRunInput,'io'>;io:RecoveryIO};
export type RevisitDependencies={runRecovery:typeof runM78Continuation4ReadonlyRecovery;verifyRecovery:typeof verifyM78Continuation4ReadonlyRecovery};
const defaults:RevisitDependencies={runRecovery:runM78Continuation4ReadonlyRecovery,verifyRecovery:verifyM78Continuation4ReadonlyRecovery};
const pin=(text:string,expected:string,label:string)=>{check(/^[a-f0-9]{64}$/.test(expected)&&sha(text)===expected,label+' pin');return JSON.parse(text)};
const time=(value:unknown,label:string)=>{const parsed=Date.parse(String(value));check(Number.isFinite(parsed),label+' time');return parsed};

export async function verifyM78ReadonlyRevisitAdmission(input:RevisitInput,verifyRecovery:typeof verifyM78Continuation4ReadonlyRecovery=verifyM78Continuation4ReadonlyRecovery){
 const accepted=await verifyRecovery(input.acceptedRecovery.inputs,input.acceptedRecovery.admission);check(accepted.status==='m78_independent_continuation4_readonly_recovery_passed'&&accepted.actualRecoveryAccepted===true,'accepted actual recovery evaluator');
 const receipt=pin(input.acceptedRecovery.resultText,input.acceptedRecovery.resultSha256,'accepted recovery result');check(receipt.status==='m78_independent_continuation4_readonly_recovery_passed'&&receipt.actualRecoveryAccepted===true&&receipt.materialFindingsOpen===0,'independently accepted actual recovery');check(receipt.journalSha256===input.acceptedRecovery.admission.journalSha256&&receipt.diagnosticsSha256===input.acceptedRecovery.admission.diagnosticsSha256&&receipt.observationSha256===input.acceptedRecovery.admission.observationSha256&&receipt.currentSourceGateSha256===input.acceptedRecovery.admission.currentSourceGateSha256,'accepted recovery pins');check(runtime(receipt.runtime),'accepted recovery runtime');
 const restartAdmission=pin(input.restart.admissionText,input.restart.admissionSha256,'restart admission'),request=pin(input.restart.requestText,input.restart.requestSha256,'restart request'),startup=pin(input.restart.startupText,input.restart.startupSha256,'restart startup'),review=pin(input.restart.independentText,input.restart.independentSha256,'restart independent review');
 check(restartAdmission.status==='m78_readonly_recovery_restart_admitted'&&restartAdmission.recoveryResultSha256===input.acceptedRecovery.resultSha256&&restartAdmission.restartRequestsAuthorized===1&&restartAdmission.revisitApplicationPostsAuthorized===0&&runtime(restartAdmission.runtime),'restart admission');
 check(request.status==='m78_readonly_recovery_restart_requested'&&request.recoveryResultSha256===input.acceptedRecovery.resultSha256&&request.restartAdmissionSha256===input.restart.admissionSha256&&typeof request.requestId==='string'&&request.requestId.length>0&&runtime(request.runtime),'restart request');
 check(startup.status==='m78_readonly_recovery_restart_startup_observed'&&startup.requestSha256===input.restart.requestSha256&&startup.requestId===request.requestId&&runtime(startup.runtime)&&startup.ready?.status==='ready'&&startup.ready?.schemaVersion===21&&startup.ready?.legacyContainmentVerified===true,'restart startup');
 check(review.status==='m78_readonly_recovery_restart_independently_verified'&&review.materialFindingsOpen===0&&review.recoveryResultSha256===input.acceptedRecovery.resultSha256&&review.restartAdmissionSha256===input.restart.admissionSha256&&review.requestSha256===input.restart.requestSha256&&review.startupSha256===input.restart.startupSha256&&runtime(review.runtime),'restart independent review');
 const recoveryClosed=time(receipt.completedAt??JSON.parse(input.acceptedRecovery.inputs.observationText).observedAt,'recovery closure'),requested=time(request.requestedAt,'restart request'),started=time(startup.startedAt,'restart startup'),observed=time(startup.observedAt,'restart observation');check(recoveryClosed<requested&&requested<started&&started<=observed,'recovery/restart chronology');
 check(input.runner.admission.mainText===input.acceptedRecovery.inputs.mainText&&input.runner.admission.diagnosticText===input.acceptedRecovery.inputs.diagnosticText&&input.runner.admission.failureReviewText===input.acceptedRecovery.inputs.failureReviewText&&input.runner.admission.currentSourceGateText===input.acceptedRecovery.inputs.currentSourceGateText,'runner evidence identity');
 return{accepted,receipt,restartAdmission,request,startup,review};
}

function remapIO(io:RecoveryIO):RecoveryIO{const map:ReadonlyMap<string,string>=new Map([[M78_READONLY_RECOVERY_PATHS.journal,M78_READONLY_REVISIT_PATHS.journal],[M78_READONLY_RECOVERY_PATHS.diagnostics,M78_READONLY_REVISIT_PATHS.diagnostics],[M78_READONLY_RECOVERY_PATHS.observation,M78_READONLY_REVISIT_PATHS.observation]]);return{read:async path=>{const target=map.get(path);check(target,'revisit read path');return io.read(target)},append:async(path,text,exclusive)=>{const target=map.get(path);check(target,'revisit append path');return io.append(target,text,exclusive)}}}
async function productionDecode(observation:any,workspaceId:string){const scope1=await decodeScope1Register(observation.scope1,workspaceId),registers={corporate:await decodeCorporateRegister(observation.registers.corporate,workspaceId),gas:await decodeGasRegister(observation.registers.gas,workspaceId),mobile:await decodeMobileRegister(observation.registers.mobile,workspaceId),fleet:await decodeFleetRegister(observation.registers.fleet,workspaceId),diesel:await decodeGeneratorRegister(observation.registers.diesel,workspaceId),equipment:await decodeStationaryRegister(observation.registers.equipment,workspaceId),fugitive:await decodeFugitiveRegister(observation.registers.fugitive,workspaceId)},fullReports:Record<string,unknown>={};for(const[id,value]of Object.entries(observation.fullReports))fullReports[id]=await decodeScope1Report(value,workspaceId);check(same(scope1,observation.scope1)&&same(registers,observation.registers)&&same(fullReports,observation.fullReports),'production decoded revisit observation');return{scope1,registers,fullReports}}
function head(text:string){const lines=text.trimEnd().split('\n');check(lines.length>0&&text.endsWith('\n'),'revisit evidence newline');return JSON.parse(lines.at(-1)!).sha256 as string}

export async function runM78ReadonlyRevisit(input:RevisitInput,dependencies:RevisitDependencies=defaults){
 await verifyM78ReadonlyRevisitAdmission(input,dependencies.verifyRecovery);
 const originals=new Map<string,string>();for(const path of [...Object.values(M78_READONLY_RECOVERY_PATHS),M78_READONLY_RECOVERY_LOCK]){const text=await input.io.read(path);check(text!==null,'accepted recovery artifact '+path);originals.set(path,text)}check(sha(originals.get(M78_READONLY_RECOVERY_LOCK)!)===input.acceptedRecovery.lockSha256,'accepted recovery lock');
 for(const path of Object.values(M78_READONLY_REVISIT_PATHS))check(await input.io.read(path)===null,'exclusive revisit path');check(await input.io.read(M78_READONLY_REVISIT_LOCK)!==null,'revisit lock held');
 const result=await dependencies.runRecovery({...input.runner,io:remapIO(input.io)});for(const[path,text]of originals)check(await input.io.read(path)===text,'accepted recovery artifact changed '+path);if(result.status!=='passed')return{status:'failed',stage:'revisit_runner',applicationPostRequests:result.applicationPostRequests,allCreatedAuthSessionsClosed:result.allCreatedAuthSessionsClosed,unknownAuthSessions:result.unknownAuthSessions};
 const journalText=await input.io.read(M78_READONLY_REVISIT_PATHS.journal),diagnosticText=await input.io.read(M78_READONLY_REVISIT_PATHS.diagnostics),observationText=await input.io.read(M78_READONLY_REVISIT_PATHS.observation);check(journalText&&diagnosticText&&observationText,'complete revisit evidence');const observation=JSON.parse(observationText),workspaceId=JSON.parse(input.runner.admission.mainText.split('\n')[0]!).workspaceId;await productionDecode(observation,workspaceId);
 const reviewAdmission:RecoveryReviewAdmission={journalSha256:sha(journalText),journalHead:head(journalText),diagnosticsSha256:sha(diagnosticText),diagnosticsHead:head(diagnosticText),observationSha256:sha(observationText),currentSourceGateSha256:sha(input.runner.admission.currentSourceGateText)};const reviewInputs={...input.acceptedRecovery.inputs,recoveryJournalText:journalText,recoveryDiagnosticText:diagnosticText,observationText,currentSourceGateText:input.runner.admission.currentSourceGateText};const evaluated=await dependencies.verifyRecovery(reviewInputs,reviewAdmission);check(evaluated.status==='m78_independent_continuation4_readonly_recovery_passed'&&evaluated.applicationPostRequests===0&&evaluated.allCreatedAuthSessionsClosed===true,'full revisit evaluator');
 const before=JSON.parse(input.acceptedRecovery.inputs.observationText),retained=['scope1','registers','downloads','m78bytes','fullReports','legacy']as const;for(const key of retained)check(same(observation[key],before[key]),'retained recovery state '+key);
 return{status:'m78_readonly_revisit_passed',applicationPostRequests:0,allCreatedAuthSessionsClosed:true,unknownAuthSessions:0,restartStartupSha256:input.restart.startupSha256,acceptedRecoveryResultSha256:input.acceptedRecovery.resultSha256,journalSha256:reviewAdmission.journalSha256,diagnosticsSha256:reviewAdmission.diagnosticsSha256,observationSha256:reviewAdmission.observationSha256,retainedStateExact:true};
}
