import {test,expect} from 'bun:test'
import {validateHostedGate,localRestorePayload,loadHostedArtifacts,pinnedReceipt,upgradeHosted,hostedOperatorUrl,parseOperatorJson,exclusiveJournal,REQUIRED_SOURCE_ROOTS,RESOLVER_SOURCE_ROOTS,hostedSourcePins,HOSTED_PROFILE,EXCLUSION,APPLICATION_RESTORE_PROFILE,applicationRestoreInventory,compareHostedApplicationRestore,verifyHostedApplicationRestore,type HostedSnapshot,type HostedGate,type HostedArtifacts,type DurableWriter} from './m78-hosted-database'
import {hash,sha,PROJECT,REVIEWED_MIGRATION_SHA256,NEW_TABLES,sameExactInventory,type Inventory,type Content} from './m78-inventory'
import {byteEntry} from './m77-recovery-manifest'
import {mkdtemp,rm} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
const d='a'.repeat(64),commit='b'.repeat(40)
test('source closure pins concrete workspace exports and TypeScript resolver chains',async()=>{
 const pins=await hostedSourcePins();for(const path of RESOLVER_SOURCE_ROOTS){expect(pins.some(p=>p.path===path&&/^[a-f0-9]{64}$/.test(p.sha256))).toBe(true);const {g,a,now}=fixture();g.sourcePins=g.sourcePins.filter(p=>p.path!==path);a.codeReview.sourcePins=g.sourcePins;expect(()=>validateHostedGate(g,a,now)).toThrow('source pin')}
 expect(new Set(pins.map(p=>p.path)).size).toBe(pins.length);
});
function fixture(){
 const now=Date.now(),at=new Date(now-1000).toISOString(),inventory:Inventory={tables:[{name:'schema_migrations',count:20,sha256:d,rowHashes:Array(20).fill(d)},...Array.from({length:112},(_,i)=>({name:'fixture_'+i,count:0,sha256:hash([]),rowHashes:[]}))],metadata:{functions:hash([])},catalogRowHashes:{functions:[]},functions:[],tableObjects:[],sequences:[],roles:[],memberships:[],defaultAcls:[],dependencies:[]},content:Content={profile:'neuvetra.m78.recovery-content.v1',schemaVersion:20,entries:[],sha256:hash([])};
 const sourcePins=[...REQUIRED_SOURCE_ROOTS,'packages/neuvetra-database/src/migrations/0021_scope1_inventory.sql'].map(path=>({path,sha256:d})),pin=(path:string)=>({path,sha256:d});
 const g:HostedGate={profile:'neuvetra.m78.hosted-database-gate.v1',project:PROJECT,createdAt:at,operatorId:'root-operator',independentReviewerId:'separate-reviewer',reviewedCommit:commit,headObservedCommit:commit,headObservedAt:at,requiredChecksCommit:commit,requiredChecksPassed:true,requiredCheckNames:['native','typecheck'],checksObservedAt:at,maintenanceConfirmed:true,maintenanceObservedAt:at,providerRecoveryExclusionAccepted:true,migrationSha256:REVIEWED_MIGRATION_SHA256!,sourcePins,codeReview:pin('review'),checksReceipt:pin('checks'),backup:pin('backup'),restore:pin('restore'),recovery:pin('recovery'),forwardRecovery:pin('forward')};
 const entries=['scope1_versions','scope1_reviews','scope1_reports','scope1_statements','scope1_requests','scope1_audit','scope1_process_discoveries'].map(table=>byteEntry(table,'synthetic','record','retained')),forwardContent:Content={profile:'neuvetra.m78.recovery-content.v1',schemaVersion:21,entries,sha256:hash(entries)};
 const a:HostedArtifacts={codeReview:{status:'m78_independent_hosted_database_review_passed',project:PROJECT,createdAt:at,reviewerId:g.independentReviewerId,operatorId:g.operatorId,reviewedCommit:commit,migrationSha256:g.migrationSha256,sourcePins,requiredCheckNames:g.requiredCheckNames},checksReceipt:{status:'m78_required_checks_passed',project:PROJECT,createdAt:at,commit,allRequiredChecksPassed:true,checks:[{name:'typecheck',conclusion:'success'},{name:'native',conclusion:'success'}]},backup:{status:'m78_hosted_encrypted_application_backup',profile:HOSTED_PROFILE,project:PROJECT,createdAt:at,schemaVersion:20,archiveSha256:d,snapshotSha256:d,dumpSha256:d,inventory,content},restore:{status:'m78_hosted_snapshot_restored_locally',sourceProfile:HOSTED_PROFILE,project:PROJECT,createdAt:at,schemaVersion:20,port:55472,database:'m78_ops_actual_restore',archiveSha256:d,snapshotSha256:d,dumpSha256:d,sourceBackupCreatedAt:at,exactApplicationVerified:true,globalRolesUnchanged:true,runtimeNoClaimDenied:true,runtimeActorRead:true,providerRecoveryExcluded:true,inventory,content},recovery:{status:'m78_independent_actual_backup_recovery_passed',project:PROJECT,createdAt:at,reviewerId:g.independentReviewerId,database:'m78_ops_actual_restore',schemaVersion:20,archiveSha256:d,snapshotSha256:d,restoreReceiptSha256:g.restore.sha256,actualArchiveRestoreVerified:true,allHistoricalProofsVerified:true,allLegacyDownloadsVerified:true,runtimeReplayVerified:true,noMutationVerified:true,providerRecoveryExcluded:true,inventory,content},forwardRecovery:{status:'m78_independent_occupied21_forward_recovery_passed',project:PROJECT,createdAt:at,reviewerId:g.independentReviewerId,schemaVersion:21,migrationSha256:g.migrationSha256,occupiedTargetRefused:true,freshCloneRestored:true,processAndInventoryHistoryVerified:true,capturedNullReviewsVerified:true,correctionsAndContributorsVerified:true,oldFamilyReplayAndDownloadsVerified:true,noMutationVerified:true,providerRecoveryExcluded:true,sourceInventory:inventory,restoredInventory:inventory,sourceContent:forwardContent,restoredContent:forwardContent}};
 const replay=(families:string[])=>({fullHistoricalSemanticReplay:false,families:families.map(family=>({family,versionIds:[crypto.randomUUID()],reportIds:[crypto.randomUUID()],authorizedGetRequests:2,exactDownloadRequests:1,semanticAndDownloadVerification:true}))});
 Object.assign(a.recovery,{completeApplicationBytesAndCatalogVerified:true,boundedSemanticReplayVerified:true,semanticReplay:replay(['legacy_electricity','corporate','natural_gas','mobile_diesel','fleet','stationary_diesel','stationary','fugitive']),priorAcceptedClosure:{artifact:pin('prior-accepted'),currentCompleteContentSha256:content.sha256,preservationVerified:true}});
 const forwardInventory=structuredClone(inventory);forwardInventory.tables[0]!.count=21;forwardInventory.tables[0]!.rowHashes.push(d);forwardInventory.tables.push(...NEW_TABLES.map(name=>({name,count:name==='scope1_process_discoveries'?0:1,sha256:hash([]),rowHashes:name==='scope1_process_discoveries'?[]:[d]})));
 Object.assign(a.forwardRecovery,{hostedEvidence:false,completeApplicationBytesAndCatalogVerified:true,semanticReplay:replay(['process_screen','inventory']),sourceInventory:forwardInventory,restoredInventory:forwardInventory});
 Object.assign(a.restore,{sourceFullInventory:inventory,applicationRestoreComparison:compareHostedApplicationRestore(inventory,inventory),localDefaultAclsPrerequisitesUnchanged:true});Object.assign(a.recovery,{sourceFullInventory:inventory,applicationRestoreComparison:a.restore.applicationRestoreComparison});
 // No indicated process source exists in this legitimate complete synthetic screen.
 a.forwardRecovery.sourceContent.entries=a.forwardRecovery.sourceContent.entries.filter((e:any)=>e.table!=='scope1_process_discoveries');a.forwardRecovery.sourceContent.sha256=hash(a.forwardRecovery.sourceContent.entries);
 return {g,a,now};
}
test('hosted gate binds exact review, checks, actual archive recovery and occupied21 evidence',()=>{
 const {g,a,now}=fixture();expect(()=>validateHostedGate(g,a,now)).not.toThrow();
 const cases:Array<(g:HostedGate,a:HostedArtifacts)=>void>=[g=>g.project='other',g=>g.migrationSha256=d,g=>g.independentReviewerId=g.operatorId,g=>g.reviewedCommit='tag',g=>g.headObservedCommit='c'.repeat(40),g=>g.requiredChecksCommit='c'.repeat(40),g=>g.requiredChecksPassed=false as any,g=>g.requiredCheckNames.push('missing'),g=>g.headObservedAt=new Date(now-900001).toISOString(),g=>g.createdAt=new Date(now+1000).toISOString(),g=>g.maintenanceConfirmed=false as any,g=>g.providerRecoveryExclusionAccepted=false as any,g=>g.sourcePins.pop(),(_g,a)=>a.backup.status='m78_local_backup',(_g,a)=>a.restore.archiveSha256='c'.repeat(64),(_g,a)=>a.restore.snapshotSha256='c'.repeat(64),(_g,a)=>a.restore.port=5432,(_g,a)=>a.restore.database='postgres',(_g,a)=>a.restore.runtimeNoClaimDenied=false,(_g,a)=>a.recovery.reviewerId=g.operatorId,(_g,a)=>a.recovery.restoreReceiptSha256='c'.repeat(64),(_g,a)=>a.recovery.noMutationVerified=false,(_g,a)=>a.forwardRecovery.occupiedTargetRefused=false,(_g,a)=>a.forwardRecovery.capturedNullReviewsVerified=false,(_g,a)=>a.forwardRecovery.restoredContent.entries=[],(_g,a)=>a.checksReceipt.checks[0].conclusion='skipped',(_g,a)=>a.codeReview.sourcePins=[]];
 for(const change of cases){const v=structuredClone({g,a});change(v.g,v.a);expect(()=>validateHostedGate(v.g,v.a,now)).toThrow()}
});
test('reviewed source and exact receipt bytes are loaded without using a self-hashed replacement',async()=>{
 const {g,a}=fixture(),files=new Map<string,Uint8Array>(),encode=(s:string)=>new TextEncoder().encode(s);
 for(const p of g.sourcePins){const bytes=encode('reviewed '+p.path);files.set(p.path,bytes);p.sha256=sha(bytes)}a.codeReview.sourcePins=g.sourcePins;
 const prior=encode('prior independently accepted closure');files.set('prior-accepted',prior);a.recovery.priorAcceptedClosure.artifact.sha256=sha(prior);
 for(const key of ['codeReview','checksReceipt','backup','restore','recovery','forwardRecovery']as const){const start=key==='backup'?{status:'m78_hosted_backup_started',project:PROJECT,createdAt:a.backup.createdAt}:key==='restore'?{status:'m78_hosted_restore_started',project:PROJECT,createdAt:a.restore.createdAt,archiveSha256:d,snapshotSha256:d,database:a.restore.database}:null,bytes=encode(start?JSON.stringify(start)+'\n'+JSON.stringify(a[key])+'\n':JSON.stringify(a[key],null,2));files.set(g[key].path,bytes);g[key].sha256=sha(bytes)}
 const read=async(path:string)=>files.get(path)!;expect((await loadHostedArtifacts(g,read)).backup.status).toBe(a.backup.status);
 files.set(g.sourcePins[0]!.path,encode('coordinated code edit'));await expect(loadHostedArtifacts(g,read)).rejects.toThrow('source bytes');
});
test('durable backup and restore receipts require an exact ordered closed attempt',()=>{
 const {a}=fixture(),at=a.backup.createdAt,start={status:'m78_hosted_backup_started',project:PROJECT,createdAt:at},encode=(s:unknown,o:unknown)=>JSON.stringify(s)+'\n'+JSON.stringify(o)+'\n';
 expect(pinnedReceipt(encode(start,a.backup),'backup')).toEqual(a.backup);
 expect(()=>pinnedReceipt(JSON.stringify(a.backup),'backup')).toThrow();
 for(const text of [JSON.stringify(start)+'\n'+JSON.stringify(a.backup)+'\n'+JSON.stringify(a.backup),encode(a.backup,start),encode({...start,createdAt:new Date(Date.parse(at)+1).toISOString()},a.backup)])expect(()=>pinnedReceipt(text,'backup')).toThrow();
 const restoreStart={status:'m78_hosted_restore_started',project:PROJECT,createdAt:at,archiveSha256:d,snapshotSha256:d,database:a.restore.database};expect(pinnedReceipt(encode(restoreStart,a.restore),'restore')).toEqual(a.restore);expect(()=>pinnedReceipt(encode({...restoreStart,database:'other'},a.restore),'restore')).toThrow();
});
test('hosted snapshot transfer preserves explicit provenance without loosening local guards',()=>{
 const {a}=fixture(),dump=Buffer.from('synthetic dump with enough bytes'),snapshot:HostedSnapshot={profile:HOSTED_PROFILE,source:{transport:'fixed-project-operator-verify-full',database:'postgres',providerRecoveryExcluded:true},project:PROJECT,createdAt:a.backup.createdAt,schemaVersion:20,migrationSha256:null,inventory:a.backup.inventory,content:a.backup.content,dependencies:{authUserIds:[],authUidDefinition:'stub',providerRecovery:EXCLUSION},dumpSha256:sha(dump),dumpBase64:dump.toString('base64')},expected=sha(JSON.stringify(snapshot)),payload=localRestorePayload(snapshot,expected);
 expect(payload.profile).toBe('neuvetra.m78.local-application-bundle.v1');expect(payload.inventory).toEqual(snapshot.inventory);expect(payload.dumpBase64).toBe(snapshot.dumpBase64);expect(payload.dependencies.providerRecovery).toBe(EXCLUSION);
 for(const change of [(s:HostedSnapshot)=>s.profile='local' as any,(s:HostedSnapshot)=>s.schemaVersion=21,(s:HostedSnapshot)=>s.source.providerRecoveryExcluded=false as any,(s:HostedSnapshot)=>s.dependencies.providerRecovery='full provider recovery',(s:HostedSnapshot)=>s.dumpBase64=Buffer.from('changed').toString('base64')]){const v=structuredClone(snapshot);change(v);expect(()=>localRestorePayload(v,sha(JSON.stringify(v)))).toThrow()}
});
test('one upgrade attempt halts on unknown COMMIT, refused SQL and failed receipt durability',async()=>{
 for(const mode of ['success','sql','commit','receipt','started']as const){const {g,a}=fixture(),events:any[]=[],state={transactions:0,applications:0,closed:0},journal:DurableWriter={append:async v=>{events.push(v);if(mode==='started'&&events.length===1||mode==='receipt'&&events.length===2)throw Error('durability')},close:async()=>{state.closed++}},db={transaction:async(callback:any)=>{state.transactions++;const r=await callback({});if(mode==='commit')throw Error('transport');return r}}as WorkspaceConnection,apply=async()=>{state.applications++;if(mode==='sql')throw Error('SQL refusal');return {}as any};
  if(mode==='success'){expect((await upgradeHosted(db,g,a,journal,apply)).status).toBe('m78_hosted_migration_committed');expect(events).toHaveLength(2)}else await expect(upgradeHosted(db,g,a,journal,apply)).rejects.toThrow(mode==='commit'?'commit_unknown':mode==='receipt'?'committed_receipt_failed':'upgrade_refused');
  expect(state.closed).toBe(1);expect(state.transactions).toBe(mode==='started'?0:1);expect(state.applications).toBe(mode==='started'?0:1);expect(events[0].status).toBe('m78_hosted_upgrade_started_verify_before_retry');
 }
});
import type {WorkspaceConnection} from '../../packages/neuvetra-database/src/workspace'
test('fixed project operator refuses alternate hosts, ports, roles, database and URL options',()=>{
 const url='postgres://postgres.'+PROJECT+':fictional-test-value@aws-1-us-west-1.pooler.supabase.com:5432/postgres';expect(hostedOperatorUrl(url).hostname).toBe('aws-1-us-west-1.pooler.supabase.com');
 for(const value of [url.replace('aws-1-us-west-1.pooler.supabase.com','127.0.0.1'),url.replace(':5432/',':6543/'),url.replace('postgres.'+PROJECT,'neuvetra_runtime'),url.replace('/postgres','/other'),url+'?sslmode=disable',url+'#fragment',url.replace(':fictional-test-value',''),' '+url])expect(()=>hostedOperatorUrl(value)).toThrow();
});
test('operator JSON refuses duplicate keys, trailing bytes and unbounded nesting',()=>{
 expect(parseOperatorJson('{"a":[1,"Ï€"]}',100)).toEqual({a:[1,'Ï€']});for(const value of ['{"a":1,"a":2}','{"a":1,"\\u0061":2}','{}{}','[1,]','['.repeat(82)+']'.repeat(82)])expect(()=>parseOperatorJson(value,1000)).toThrow();expect(()=>parseOperatorJson('"Ï€"',3)).toThrow();
});
test('exclusive journal prevents a second writer and retains both original events',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'neuvetra-m78-journal-')),path=join(directory,'exclusive.jsonl');try{const journal=await exclusiveJournal(path);try{await journal.append({status:'started'});await expect(exclusiveJournal(path)).rejects.toMatchObject({code:'EEXIST'});await journal.append({status:'outcome'})}finally{await journal.close()};expect((await Bun.file(path).text()).split('\n')).toEqual(['{"status":"started"}','{"status":"outcome"}',''])}finally{await rm(directory,{recursive:true,force:true})}
});
test('hosted application comparison retains full source and excludes only declared unrelated defaults',()=>{
 const {a}=fixture(),source=structuredClone(a.backup.inventory)as Inventory;source.roles=[{rolname:'postgres'}];source.defaultAcls=[{owner:'postgres',schema:'public',kind:'r',acl:'{postgres=arwdDxtm/postgres}'},{owner:'postgres',schema:'storage',kind:'f',acl:'{postgres=X/postgres}'}];const original=JSON.stringify(source),transfer=applicationRestoreInventory(source),comparison=compareHostedApplicationRestore(source,transfer);expect(JSON.stringify(source)).toBe(original);expect(transfer.defaultAcls).toEqual([]);expect(comparison.profile).toBe(APPLICATION_RESTORE_PROFILE);expect(comparison.excludedDefaultAclCount).toBe(2);expect(hash(comparison.excludedDefaultAcls)).toBe(hash(source.defaultAcls));expect(comparison.sourceFullInventorySha256).toBe(hash(source));expect(comparison.applicationTransferInventorySha256).toBe(hash(transfer));expect(()=>verifyHostedApplicationRestore(source,transfer,comparison)).not.toThrow();expect(()=>sameExactInventory(source,transfer)).toThrow();
 for(const mutate of [(v:Inventory)=>v.defaultAcls[0]!.schema='*',(v:Inventory)=>v.defaultAcls[0]!.schema='neuvetra',(v:Inventory)=>v.defaultAcls[0]!.schema='unreviewed_schema',(v:Inventory)=>v.defaultAcls[0]!.kind='?',(v:Inventory)=>v.defaultAcls[0]!.owner='unknown_owner',(v:Inventory)=>v.defaultAcls[0]!.acl=null as any,(v:Inventory)=>v.defaultAcls[0]!.acl='not an ACL',(v:Inventory)=>(v.defaultAcls[0]as any).extra='unapproved',(v:Inventory)=>v.defaultAcls.push(structuredClone(v.defaultAcls[0]!)),(v:Inventory)=>v.roles=[]]){const value=structuredClone(source);mutate(value);expect(()=>applicationRestoreInventory(value)).toThrow()}
 for(const mutate of [(v:any)=>v.profile='generic_exact_restore',(v:any)=>v.excludedDefaultAcls=[],(v:any)=>v.excludedDefaultAclCount=0,(v:any)=>v.sourceFullInventorySha256='c'.repeat(64),(v:any)=>v.unrelatedSchemaDefaultsRestored=true]){const value=structuredClone(comparison);mutate(value);expect(()=>verifyHostedApplicationRestore(source,transfer,value)).toThrow()}
 for(const mutate of [(v:Inventory)=>v.defaultAcls=structuredClone(source.defaultAcls),(v:Inventory)=>v.roles.push({rolname:'new_role'}),(v:Inventory)=>v.tables[0]!.count=19]){const value=structuredClone(transfer);mutate(value);expect(()=>compareHostedApplicationRestore(source,value)).toThrow()}
});
test('hosted gate preserves full upgrade baseline and binds explicit local comparison into recovery',()=>{
 const {g,a,now}=fixture(),source=structuredClone(a.backup.inventory)as Inventory;source.roles=[{rolname:'postgres'}];source.defaultAcls=[{owner:'postgres',schema:'public',kind:'f',acl:'{postgres=X/postgres}'}];const restored=applicationRestoreInventory(source),comparison=compareHostedApplicationRestore(source,restored);a.backup.inventory=source;Object.assign(a.restore,{sourceFullInventory:source,inventory:restored,applicationRestoreComparison:comparison});Object.assign(a.recovery,{sourceFullInventory:source,inventory:restored,applicationRestoreComparison:comparison});expect(validateHostedGate(g,a,now).inventory).toEqual(source);expect(validateHostedGate(g,a,now).inventory.defaultAcls).toEqual(source.defaultAcls);
 for(const mutate of [(v:HostedArtifacts)=>delete v.restore.applicationRestoreComparison,(v:HostedArtifacts)=>delete v.restore.sourceFullInventory,(v:HostedArtifacts)=>v.restore.localDefaultAclsPrerequisitesUnchanged=false,(v:HostedArtifacts)=>v.recovery.applicationRestoreComparison.excludedDefaultAcls=[],(v:HostedArtifacts)=>v.recovery.sourceFullInventory=restored,(v:HostedArtifacts)=>v.restore.inventory.defaultAcls=source.defaultAcls]){const value=structuredClone(a);mutate(value);expect(()=>validateHostedGate(g,value,now)).toThrow()}
});
