const KEY='neuvetra-company-intake-preview-v1';
const titles=['Company','Reporting period','Entities & boundary','Locations','Changes & shared operations','Source activities','Review'];
const families=[['Heating & process equipment','Boilers, furnaces, ovens or other equipment that burns fuel.'],['Backup generators','Fuel-powered generators, including equipment used only in emergencies.'],['Road & off-road vehicles','Company-controlled cars, trucks, forklifts or other mobile equipment.'],['Cooling & fire suppression','Refrigeration, air-conditioning or fire suppression systems that may release gases.'],['Processes & other direct releases','Manufacturing reactions, industrial gas use or other direct releases.']];
const changes=['Acquisitions or disposals','Site openings or closures','Changes in ownership or control','Joint ventures or shared operations','Franchises, outsourcing or leased assets'];
const blank=()=>({company:{},period:{},boundary:{},entities:[],locations:[],changes:changes.map(()=>({})),sources:families.map(()=>({})),review:{}});
let data=blank(),step=0,all=false,storageOK=true;
function validDraft(d){return CompanyValidation.draftSchema.safeParse(d).success;}
function activeFields(label,obj){const copy={...obj};if(label==='Company'&&copy.industry!=='Other')delete copy.other;if(label==='Period'&&copy.first!=='No')delete copy.base;if(label==='Boundary'&&copy.hasParent!=='Yes')delete copy.parent;if(label.startsWith('Location'))return locationSummary(obj);if(changes.includes(label)&&!['Yes','Not sure'].includes(copy.answer)){delete copy.date;delete copy.details;}if(families.some(f=>f[0]===label)&&!['Yes','Not sure'].includes(copy.answer)){delete copy.names;delete copy.location;delete copy.notes;}return copy;}
const fieldNames={legal:'Legal name',trading:'Trading name',country:'Country',region:'City / region',industry:'Business activity',other:'Other activity',additional:'Additional business activities',naics:'NAICS code (2022)',role:'Preparer role',start:'Period start',end:'Period end',first:'First inventory',base:'Prior inventory / base year',hasParent:'Has a parent',parent:'Parent company',approach:'Proposed approach',operations:'Included operations',name:'Name',relationship:'Relationship',owner:'Parent / owner',share:'Ownership share (%)',included:'Proposed inclusion',reason:'Reason',purpose:'Purpose',entity:'Owning / operating entity',otherEntity:'Other entity',occupancy:'Occupancy',control:'Equipment control',operator:'Control details',locality:'Address / identifying locality',startMode:'Coverage start status',endMode:'Coverage end status',opened:'Original site opening date',from:'Coverage start date',to:'Active through within reporting period',answer:'Answer',date:'Effective date',details:'Details',names:'Equipment / activity names',location:'Location',notes:'Notes'};
try{const saved=localStorage.getItem(KEY);if(saved){const parsed=JSON.parse(saved);if(parsed.version!==1||!validDraft(parsed.data))throw Error();data={...blank(),...parsed.data};}}catch{data=blank();storageOK=false;}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=p=>p.split('.').reduce((o,k)=>o?.[k],data)??'';
function put(p,v){const ks=p.split('.');let o=data;ks.slice(0,-1).forEach(k=>o=o[k]);o[ks.at(-1)]=v;}
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:1,data}));storageOK=true;}catch{storageOK=false;}document.querySelector('#saved').textContent=storageOK?'Changes saved on this device':'Changes could not be saved on this device';const error=document.querySelector('#save-error');if(error){error.hidden=storageOK;error.textContent=storageOK?'':'Your changes could not be saved on this device. Keep this page open to avoid losing information.'}}
if(ensureLocationIds())save();
function field(label,path,options=null,type='text',hint='',full=false){const v=get(path);return `<label class="field ${full?'full':''}">${label}${options?`<select data-path="${path}"><option value="">Select an answer</option>${options.map(x=>{const value=Array.isArray(x)?x[0]:x,label=Array.isArray(x)?x[1]:x;return `<option ${v===value?'selected':''} value="${esc(value)}">${esc(label)}</option>`;}).join('')}</select>`:type==='textarea'?`<textarea data-path="${path}">${esc(v)}</textarea>`:`<input data-path="${path}" type="${type}" value="${esc(v)}" ${type==='number'?'min="0" max="100" step="any"':''}>`}${hint?`<small>${hint}</small>`:''}</label>`;}
function choices(label,path){return `<fieldset style="border:0;padding:0;margin:0"><legend>${label}</legend><div class="choices">${['Yes','No','Not sure'].map(x=>`<label><input type="radio" name="${path}" data-path="${path}" value="${x}" ${get(path)===x?'checked':''}>${x}</label>`).join('')}</div></fieldset>`;}
const grid=x=>`<div class="grid">${x}</div>`;
const note=x=>`<div class="hint">${x}</div>`;
const inclusion=['Include','Exclude — review needed','Not sure'];
function section(n,body,lead){return `<section class="section" data-section="${n}"><h2 tabindex="-1">${String(n+1).padStart(2,'0')} / ${titles[n]}</h2><p class="lead">${lead}</p>${body}</section>`;}
function renderSection(n){
if(n===0)return companySection();
if(n===1)return section(n,note('2025 is the proposed first supported reporting year. Other years and non-calendar periods can be captured here, but need review before calculation support is determined.')+grid(field('Reporting period start','period.start',null,'date')+field('Reporting period end','period.end',null,'date'))+`<button type="button" data-action="year" style="margin:18px 0">Use calendar year 2025</button>`+grid(field('Is this your first inventory?','period.first',['Yes','No','Not sure'])+(get('period.first')==='No'?field('Prior inventory / base-year reference (optional)','period.base',null,'text','Year or a short description; do not upload documents.'):'')),'Choose exact dates. Nothing is assumed from the current calendar year.');
if(n===2)return section(n,grid(field('Does the reporting company have a parent?','boundary.hasParent',['Yes','No','Not sure'])+(get('boundary.hasParent')==='Yes'?field('Parent company name','boundary.parent'):'')+field('Proposed consolidation approach','boundary.approach',['Operational control','Financial control','Equity share','Not sure']))+note('Operational control considers authority to introduce and implement operating policies. Financial control considers the ability to direct financial and operating policies for economic benefit. Equity share reflects economic interest. This selection is a proposal for an authorized reviewer, not a confirmed boundary.')+field('Operations you intend to include','boundary.operations',null,'textarea','Describe the group or business units, including any proposed exclusions.')+data.entities.map((e,i)=>`<div class="card"><div class="cardhead"><h3>Related entity ${i+1}</h3><button type="button" data-remove="entities" data-index="${i}">Remove entity</button></div>${grid(field('Entity legal name',`entities.${i}.name`)+field('Relationship',`entities.${i}.relationship`,['Subsidiary','Joint venture','Affiliate','Other','Not sure'])+field('Direct parent / owner',`entities.${i}.owner`)+field('Ownership share (%) — optional',`entities.${i}.share`,null,'number','Leave blank if not known.')+field('Included in proposed inventory?',`entities.${i}.included`,inclusion)+field('Inclusion / exclusion reason',`entities.${i}.reason`))}</div>`).join('')+`<button type="button" data-add="entities">+ Add subsidiary or related entity</button>`+sourcesHelp(),'Map the corporate structure. Add each related entity; do not assume ownership alone settles control.');
if(n===3)return locationSection();
if(n===4)return section(n,changes.map((c,i)=>`<div class="card">${choices(c,`changes.${i}.answer`)}${get(`changes.${i}.answer`)==='Yes'||get(`changes.${i}.answer`)==='Not sure'?grid(field('Effective date (if known)',`changes.${i}.date`,null,'date')+field('Affected entities / locations and details',`changes.${i}.details`,null,'textarea'))+note('Captured for review. Changes and complex arrangements are not automatically resolved by this beta.'):''}</div>`).join(''),'Consider the whole reporting period. Include arrangements that may change who controls an operation.');
if(n===5)return section(n,note('These questions identify possible source families. A “Yes” does not mean a calculation method is supported or released. Quantities, fuel details and documents come later.')+families.map(([name,help],i)=>`<div class="card"><h3>${name}</h3><p class="lead">${help}</p>${choices('Does this apply within your proposed boundary?',`sources.${i}.answer`)}${['Yes','Not sure'].includes(get(`sources.${i}.answer`))?grid(field('Equipment / activity names (if known)',`sources.${i}.names`,null,'textarea','List a few names, or describe what needs checking.')+field('Location',`sources.${i}.location`,[...data.locations.map((l,i)=>[l.id,locationChoiceLabel(l,i)]),'Multiple locations — describe below','Not sure'])+field('Location details / other notes',`sources.${i}.notes`,null,'textarea'))+note('Applicability recorded; calculation support requires separate review.'):''}</div>`).join('')+`<details><summary>Why these source families?</summary><p>Screening follows the EPA’s stationary combustion, mobile, fugitive and process categories. <a href="https://www.epa.gov/climateleadership/determine-emissions-sources" target="_blank" rel="noreferrer">Read EPA source guidance ↗</a></p></details>`,'Think about activities, not gas codes. Answer each family; unanswered questions are never treated as “No”.');
const issues=validate();return section(n,`<div class="summary"><div><small>REPORTING COMPANY</small><strong>${esc(get('company.legal')||'Not answered')}</strong><small>${esc(get('company.country')||'Country not answered')}</small></div><div><small>PERIOD</small><strong>${esc(get('period.start')||'Not answered')} → ${esc(get('period.end')||'Not answered')}</strong></div><div><small>PROPOSED BOUNDARY</small><strong>${esc(get('boundary.approach')||'Not answered')}</strong><small>${data.entities.length} related entities · ${data.locations.length} locations captured</small></div><div><small>SOURCE SCREENING</small><strong>${data.sources.filter(s=>s.answer==='Yes').length} yes · ${data.sources.filter(s=>s.answer==='No').length} no</strong><small>${data.sources.filter(s=>!s.answer||s.answer==='Not sure').length} unanswered / uncertain families</small></div></div><h3>Items to resolve</h3>${issues.length?`<ul class="issues">${issues.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:note('Core intake questions are answered. An authorized reviewer still needs to review the proposed boundary and support limits.')}<details open><summary>Everything captured · edit any section from the navigation</summary>${titles.slice(0,6).map((t,i)=>`<h3>${t} <button type="button" data-edit="${i}" class="text">Edit</button></h3>${reviewText(i)}`).join('')}</details><label class="check"><input type="checkbox" data-path="review.complete" ${data.review.complete?'checked':''}>I have listed the entities, locations and source types to the best of my knowledge, with uncertainties identified.</label>${field('Authorized boundary reviewer role','review.role',null,'text','Required before a boundary can be approved. No personal details needed.')}<label class="check"><input type="checkbox" data-path="review.needed" ${data.review.needed?'checked':''}>I understand an authorized reviewer must review the proposed boundary and open items.</label>${note('This records a local draft acknowledgment only. It is not professional assurance, boundary approval, an emissions result or permission to release an inventory.')}<p id="review-result" role="status"></p>`,'Review the proposed business setup. Missing answers and unsupported cases remain visible.');
}
function sourcesHelp(){return `<details><summary>Boundary guidance and sources</summary><p>Plain-language summaries are based on <a target="_blank" rel="noreferrer" href="https://www.epa.gov/climateleadership/determine-organizational-boundaries">EPA organizational boundary guidance ↗</a> and the <a target="_blank" rel="noreferrer" href="https://ghgprotocol.org/corporate-standard">GHG Protocol Corporate Standard, chapter 3 ↗</a>. Selecting an approach here does not determine exhaustive compliance.</p></details>`;}
function validate(){const a=[];const req=(p,label)=>{if(!String(get(p)).trim())a.push(label+' is not answered.');else if(get(p)==='Not sure')a.push(label+' is uncertain.');};Object.entries(companyErrors(data.company)).forEach(([k,v])=>a.push(COMPANY_FIELDS[k].label+': '+v));req('period.start','Period start');req('period.end','Period end');req('period.first','First inventory');if(get('period.start')&&get('period.end')&&get('period.end')<get('period.start'))a.push('Reporting period ends before it starts.');if(get('period.start')&&get('period.end')&&(get('period.start')!=='2025-01-01'||get('period.end')!=='2025-12-31'))a.push('This reporting period needs support review; calendar 2025 is the proposed initial scope.');req('boundary.hasParent','Parent relationship');if(get('boundary.hasParent')==='Yes')req('boundary.parent','Parent name');req('boundary.approach','Consolidation approach');req('boundary.operations','Included operations');if(['Financial control','Equity share'].includes(get('boundary.approach')))a.push('Financial control / equity share needs support and authorized boundary review.');data.entities.forEach((e,i)=>{['name','relationship','owner','included','reason'].forEach(k=>req(`entities.${i}.${k}`,`Entity ${i+1}: ${k}`));if(e.share!==''&&e.share!=null&&(Number(e.share)<0||Number(e.share)>100))a.push(`Entity ${i+1}: ownership share must be 0–100%.`);if(!e.share)a.push(`Entity ${i+1}: ownership share is not provided; review relationship.`);if(e.included?.startsWith('Exclude'))a.push(`Entity ${i+1}: proposed exclusion needs review.`);});a.push(...locationOpenItems());data.changes.forEach((c,i)=>{req(`changes.${i}.answer`,changes[i]);if(['Yes','Not sure'].includes(c.answer)){a.push(changes[i]+': retained for boundary/support review.');req(`changes.${i}.details`,changes[i]+' details');if(!c.date)a.push(changes[i]+': effective date not provided.');}});data.sources.forEach((s,i)=>{req(`sources.${i}.answer`,families[i][0]);if(['Yes','Not sure'].includes(s.answer)){if(!s.names)a.push(families[i][0]+': equipment names/details still needed.');req(`sources.${i}.location`,families[i][0]+' location');if(s.location&&!['Not sure','Multiple locations — describe below',...data.locations.map(l=>l.id)].includes(s.location))a.push(families[i][0]+': linked location was removed or is ambiguous; update the link.');if(s.location==='Multiple locations — describe below'&&!s.notes)a.push(families[i][0]+': list the linked locations in notes.');a.push(families[i][0]+': calculation eligibility not established.');}});return a;}
function reviewText(i){const groups=[{Company:data.company},{Period:data.period},{Boundary:data.boundary,...Object.fromEntries(data.entities.map((e,n)=>['Entity '+(n+1),e]))},Object.fromEntries(data.locations.map((l,n)=>['Location '+(n+1),l])),Object.fromEntries(data.changes.map((c,n)=>[changes[n],c])),Object.fromEntries(data.sources.map((s,n)=>[families[n][0],s]))];return Object.entries(groups[i]).map(([label,obj])=>`<div class="hint"><strong>${esc(label)}</strong><br>${Object.entries(activeFields(label,obj)).filter(([k])=>k!=='id').map(([k,v])=>`${esc(fieldNames[k]||k)}: ${esc((k==='location'?sourceLocationLabel(v):v)||'Not answered')}`).join('<br>')||'Not answered'}</div>`).join('')||'<p>None captured — not a completeness claim.</p>';}
function render(focus=false){document.querySelector('#steps').innerHTML=titles.map((t,i)=>`<button type="button" data-step="${i}" ${step===i&&!all?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${t}</button>`).join('');document.querySelector('#questions').innerHTML=all?titles.map((_,i)=>renderSection(i)).join(''):renderSection(step);document.querySelector('#mode').textContent=all?'Return to guided setup':'View all questions';document.querySelector('#back').disabled=!all&&step===0;document.querySelector('#next').textContent=all||step===6?'Save review acknowledgment':'Continue →';document.querySelector('#stepcount').textContent=all?'All questions':`${step+1} of 7`;if(!storageOK){document.querySelector('#saved').textContent='Saved information could not be restored';const error=document.querySelector('#save-error');if(error&&error.hidden){error.hidden=false;error.textContent='Saved information could not be restored. Keep this page open while you check the information.'}}if(focus){document.querySelector('.section h2').focus();document.querySelector('#questions').scrollIntoView({block:'start'});}}
document.addEventListener('input',e=>{const p=e.target.dataset.path;if(!p)return;put(p,e.target.type==='checkbox'?e.target.checked:e.target.value);if(!p.startsWith('review.')){data.review.complete=false;data.review.needed=false;}save();if(p.startsWith('company.'))refreshCompanyErrors();if(p.startsWith('locations.'))refreshLocationErrors();});
document.addEventListener('change',e=>{const p=e.target.dataset.path;if(all&&p&&e.target.tagName!=='SELECT'&&e.target.type!=='radio'){const review=document.querySelector('[data-section="6"]');if(review&&!p.startsWith('review.'))review.outerHTML=renderSection(6);}if(p&&(e.target.tagName==='SELECT'||e.target.type==='radio')){const val=e.target.value;render();const candidates=[...document.querySelectorAll('[data-path]')];candidates.find(x=>x.dataset.path===p&&(x.type!=='radio'||x.value===val))?.focus();}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.step!=null||b.dataset.edit!=null){step=Number(b.dataset.step??b.dataset.edit);all=false;render(true);}if(b.dataset.add){data[b.dataset.add].push(b.dataset.add==='locations'?{id:'loc-'+crypto.randomUUID()}:{});data.review={};save();render();document.querySelector(`[data-path="${b.dataset.add}.${data[b.dataset.add].length-1}.name"]`)?.focus();}if(b.dataset.remove){data[b.dataset.remove].splice(Number(b.dataset.index),1);data.review={};save();render();document.querySelector(`[data-add="${b.dataset.remove}"]`)?.focus();}if(b.dataset.action==='year'){data.period.start='2025-01-01';data.period.end='2025-12-31';data.review={};save();render();}});
document.querySelector('#mode').onclick=()=>{all=!all;render(true);};
document.querySelector('#back').onclick=()=>{all=false;step=Math.max(0,step-1);render(true);};
document.querySelector('#next').onclick=()=>{if(!all&&step===0&&Object.keys(companyErrors(data.company)).length){companyAttempted=true;render();document.querySelector('#company-errors').focus();return;}if(!all&&step===3&&locationPageErrors().length){locationsAttempted=true;render();document.querySelector('#locations-errors').focus();return;}if(!all&&step<6){if(step===0){const accepted=CompanyValidation.parseCompany(data.company);if(accepted.success){data.company=accepted.data;save();}}step++;render(true);}else{save();document.querySelector('#review-result').textContent=!storageOK?'Draft could not be saved. Browser storage is unavailable.':data.review.complete&&data.review.needed&&data.review.role?'Acknowledgment saved locally. '+validate().length+' open items remain; authorized review is still required.':'Please complete both acknowledgments and enter the authorized reviewer role. Your incomplete draft is saved locally.';}};
document.querySelector('#reset').onclick=()=>document.querySelector('#reset-dialog').showModal();document.querySelector('#cancel-reset').onclick=()=>document.querySelector('#reset-dialog').close();document.querySelector('#confirm-reset').onclick=()=>{data=blank();step=0;all=false;companyAttempted=false;companyTouched.clear();locationsAttempted=false;locationTouched.clear();naicsQuery='';naicsPage=0;naicsOpen=false;save();document.querySelector('#reset-dialog').close();render(true);};document.querySelector('#form').onsubmit=e=>e.preventDefault();render();
