// Bounded state checks. Browser interactions are recorded separately in README.md.
const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
function session(raw){const element={textContent:'',innerHTML:'',disabled:false};const ctx=vm.createContext({crypto:require('node:crypto').webcrypto,document:{querySelector:()=>element,addEventListener:()=>{}},localStorage:{getItem:()=>raw,setItem:()=>{}}});vm.runInContext(readFileSync(__dirname+'/validation.bundle.js','utf8'),ctx);vm.runInContext(readFileSync(__dirname+'/company.js','utf8'),ctx);vm.runInContext(readFileSync(__dirname+'/locations.js','utf8'),ctx);vm.runInContext(readFileSync(__dirname+'/app.js','utf8'),ctx);return expression=>vm.runInContext(expression,ctx);}
const run=session(null);
assert.equal(run("data.company.legal??''"),'');
assert.equal(run('data.sources.filter(s=>s.answer===\'No\').length'),0);
assert.equal(run("validate().some(x=>x.includes('not answered'))"),true);
run("data.period={start:'2026-12-31',end:'2026-01-01'}");
assert.equal(run("validate().some(x=>x.includes('ends before'))"),true);
assert.equal(run("validate().some(x=>x.includes('support review'))"),true);
run("data.entities=[{name:'Former entity'}];data.locations=[{entity:'Former entity',name:'Abroad',country:'Canada'}];data.entities=[]");
assert.equal(run("validate().some(x=>x.includes('Choose a current reporting entity'))"),true);
assert.equal(run("validate().some(x=>x.includes('geography retained'))"),true);
run("data.sources[0]={answer:'Not sure',location:'Deleted site'}");
assert.equal(run("validate().some(x=>x.includes('linked location was removed'))"),true);
assert.equal(run("validate().some(x=>x.includes('is uncertain'))"),true);
run("data.sources[0]={answer:'No',names:'obsolete source note'}");
assert.equal(run("reviewText(5).includes('obsolete source note')"),false);
run("data.boundary={hasParent:'No',parent:'obsolete parent'}");
assert.equal(run("reviewText(2).includes('obsolete parent')"),false);
for(const corruption of ["d.company=null","d.locations=[null]","d.locations=[{country:true}]","d.changes[0]=null"]){const d=JSON.parse(run('JSON.stringify(blank())'));new Function('d',corruption)(d);const restored=session(JSON.stringify({version:1,data:d}));assert.equal(restored('storageOK'),false);assert.equal(restored('data.locations.length'),0);}
console.log('Bounded state checks passed.');
const companyRun=session(null);
assert.equal(companyRun('BUSINESS_SECTORS.length'),20);
assert.equal(companyRun("BUSINESS_SECTORS.map(s=>s[0]).join(',')"),'11,21,22,23,31-33,42,44-45,48-49,51,52,53,54,55,56,61,62,71,72,81,92');
assert.equal(companyRun("SECTOR_OPTIONS.includes('Not sure')"),false);
assert.equal(companyRun('Object.keys(companyErrors({})).length'),3);
assert.equal(companyRun("!!companyErrors({legal:'   '}).legal"),true);
companyRun("data.company={legal:'Café & Co. 株式会社',country:'Canada',region:'Toronto, Ontario',industry:'Other',role:'Facilities lead'}");
assert.equal(companyRun("!!companyErrors(data.company).other"),true);
companyRun("data.company.other='Specialized testing activity'");
assert.equal(companyRun('Object.keys(companyErrors(data.company)).length'),0);
companyRun("data.company.industry='Manufacturing';data.company.other=''");
assert.equal(companyRun('Object.keys(companyErrors(data.company)).length'),0);
companyRun("data.company.legal='x'.repeat(201)");
assert.equal(companyRun("!!companyErrors(data.company).legal"),true);
companyRun("data.company.country=' Not sure '");
assert.equal(companyRun("!!companyErrors(data.company).country"),true);
companyRun("data.company.industry='Old unsupported label'");
assert.equal(companyRun("!!companyErrors(data.company).industry"),true);
console.log('First-page coverage, conditional validation, Unicode, whitespace, unknowns, lengths and legacy-choice checks passed.');
const schemaRun=session(null);
assert.equal(schemaRun('CompanyValidation.naics.length'),1012);
assert.equal(schemaRun("CompanyValidation.findCode('541330').title"),'Engineering Services');
assert.equal(schemaRun("CompanyValidation.searchNaics('engineering services').some(r=>r.code==='541330')"),true);
assert.equal(schemaRun("CompanyValidation.searchNaics('999999').length"),0);
assert.equal(schemaRun("CompanyValidation.legalName.safeParse('A').success"),false);
assert.equal(schemaRun("CompanyValidation.legalName.safeParse('3M').success"),true);
assert.equal(schemaRun("CompanyValidation.legalName.safeParse('<script>alert(1)</script>').success"),false);
assert.equal(schemaRun("CompanyValidation.legalName.safeParse('Café & Co. 株式会社').success"),true);
assert.equal(schemaRun("CompanyValidation.numericForm(CompanyValidation.positiveNumber).safeParse('').success"),false);
assert.equal(schemaRun("CompanyValidation.numericForm(CompanyValidation.positiveNumber).safeParse('-1').success"),false);
assert.equal(schemaRun("CompanyValidation.numericForm(CompanyValidation.positiveNumber).safeParse('1.25').data"),1.25);
assert.equal(schemaRun("CompanyValidation.numericForm(CompanyValidation.negativeNumber).safeParse('-1.25').data"),-1.25);
assert.equal(schemaRun("CompanyValidation.numericForm(CompanyValidation.nonnegativeNumber).safeParse('0').data"),0);
assert.equal(schemaRun("CompanyValidation.numericForm(CompanyValidation.percent).safeParse('100.1').success"),false);
assert.equal(schemaRun("CompanyValidation.numericForm(CompanyValidation.integer).safeParse('1.2').success"),false);
assert.equal(schemaRun("CompanyValidation.numericForm(CompanyValidation.finiteNumber).safeParse('Infinity').success"),false);
schemaRun("data.company={legal:'Preview Company',country:'Canada',region:'Toronto',industry:'Manufacturing',role:'Facilities lead',naics:'541330'}");
assert.equal(schemaRun("!!companyErrors(data.company).naics"),true);
schemaRun("data.company.industry='Professional, Scientific, and Technical Services'");
assert.equal(schemaRun('Object.keys(companyErrors(data.company)).length'),0);
schemaRun("data.company.naics='999999'");
assert.equal(schemaRun("!!companyErrors(data.company).naics"),true);
console.log('Official NAICS membership/search, Zod names, markup rejection, numeric signs/types, and sector-code consistency checks passed.');

assert.equal(schemaRun("CompanyValidation.parseCompany({legal:'QA',country:'United States',industry:'Manufacturing'}).success"),true);
assert.equal(schemaRun("CompanyValidation.parseCompany({legal:'QA',country:'United States',industry:'Other'}).success"),false);
