'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Plan=require('./plan-core.js'),Core=require('./readiness-core.js'),catalog=require('./data/collection-catalog.json');
function fixture(){
 const input={company:{legal:'Example, Inc.',country:'United States'},period:{start:'2025-01-01',end:'2025-12-31'},boundary:{approach:'Operational control',operations:'All'},locations:[{id:'l1',name:'Main',included:'Include'}],sources:[{answer:'Yes',names:'Boiler',location:'l1'},...Array.from({length:4},()=>({answer:'No',notes:'Not operated'}))],changes:[],review:{complete:true,needed:true,role:'Owner'}};
 const plan=Plan.createPlan(input,catalog),item=plan.items['scope1:stationary'];
 item.subtypeId='boiler';item.locationIds=['l1'];item.records=[{id:'r1',recordType:'Natural gas bill',quantity:'100',unit:'therm',quality:'actual',periodStart:'2025-01-01',periodEnd:'2025-12-31',reference:'Gas invoice'}];
 item.readinessDetails={'fuel-type':'natural-gas','activity-source':'supplier-invoice','source-identifier':'acct-100'};
 const methods={version:'test',methods:[{id:'test',scope:'1',catalogId:'boiler',status:'candidate',acceptedUnits:['therm','gallon'],requiredInputs:[{id:'fuel'}],requiredFields:[{id:'method-choice',label:'Proposed method'}],approach:'Catalog candidate'}]};
 const reconciled=Plan.reconcile(input,plan,catalog);reconciled.items['scope1:stationary'].needsReview=false;
 return {input,plan:reconciled,methods};
}
const evaluated=f=>Core.evaluate(f.input,f.plan,catalog,f.methods);
const item=f=>evaluated(f).items.find(i=>i.id==='scope1:stationary');
test('customer facts never become reviewer or calculation approval',()=>{const f=fixture(),result=item(f),assessment=evaluated(f);assert.equal(result.status,'facts-collected');assert.equal(result.readyForCalculation,false);assert(result.findings.some(x=>x.code==='method-approval-required'&&x.severity==='review'));assert.equal(assessment.summary.methodReviewsComplete,0);assert.equal(assessment.readyForCalculation,false);assert(!Object.hasOwn(result.method,'requiredFields'));});
test('structured factual fields reject filler and invalid option values',()=>{const f=fixture();f.plan.items['scope1:stationary'].readinessDetails={'fuel-type':'n/a','activity-source':'made-up','source-identifier':'unknown'};const result=item(f);assert.equal(result.status,'needs-input');assert.equal(result.findings.filter(x=>x.code==='fact-missing').length,3);});
test('distinct full-year gasoline and diesel records require review without false blocking',()=>{const f=fixture(),saved=f.plan.items['scope1:stationary'];saved.readinessDetails['fuel-type']='gasoline-and-diesel';saved.records=[{...saved.records[0],id:'gasoline',recordType:'Gasoline purchases',quantity:'12',unit:'gallon',reference:'Gasoline ledger'},{...saved.records[0],id:'diesel',recordType:'Diesel purchases',quantity:'20',unit:'gallon',reference:'Diesel ledger'}];const result=item(f);assert(result.findings.some(x=>x.code==='period-overlap-review'&&x.severity==='review'));assert(!result.findings.some(x=>x.code==='period-overlap'));assert(!result.findings.some(x=>x.code==='fuel-record-linkage'));assert.equal(result.status,'facts-collected');});
test('mixed gasoline and diesel requires per-record fuel labels',()=>{const f=fixture(),saved=f.plan.items['scope1:stationary'];saved.readinessDetails['fuel-type']='gasoline-and-diesel';saved.records.push({...saved.records[0],id:'r2',recordType:'Fleet fuel purchase',quantity:'20',unit:'gallon',reference:'Second ledger'});const result=item(f);assert(result.findings.some(x=>x.code==='fuel-record-linkage'&&x.severity==='blocking'));});
test('vehicle model years accept mixed lists and ranges but retain unknown as a gap',()=>{const f=fixture(),saved=f.plan.items['scope1:stationary'];f.methods.methods[0].requiredInputs.push({id:'vehicle'});Object.assign(saved.readinessDetails,{'vehicle-class':'mixed-fleet','model-year-status':'reported','vehicle-model-years':'2018, 2020-2023'});assert.equal(item(f).status,'facts-collected');saved.readinessDetails['vehicle-model-years']='1899, 2028';assert(item(f).findings.some(x=>x.code==='fact-missing'));saved.readinessDetails['model-year-status']='unknown';saved.readinessDetails['vehicle-model-years']='';assert(item(f).findings.some(x=>x.code==='vehicle-model-year-unknown'));});
test('refrigerant charge quantity and unit are structured and unknown remains a gap',()=>{const f=fixture(),saved=f.plan.items['scope1:stationary'];f.methods.methods[0].requiredInputs=[{id:'gas'}];saved.readinessDetails={'substance-name':'R-410A','equipment-identifier':'RTU-1','movement-source':'service-record','charge-status':'reported','charge-quantity':'12.5','charge-unit':'kg'};assert.equal(item(f).status,'facts-collected');saved.readinessDetails['charge-quantity']='-1';assert(item(f).findings.some(x=>x.code==='fact-missing'));saved.readinessDetails['charge-status']='unknown';assert(item(f).findings.some(x=>x.code==='charge-unknown'));});
test('exact duplicates remain blocking and reporting gaps stay visible',()=>{const f=fixture(),saved=f.plan.items['scope1:stationary'];saved.records[0].periodEnd='2025-03-31';saved.records.push({...saved.records[0],id:'r2'});const result=item(f),codes=result.findings.map(x=>x.code);assert(codes.includes('duplicate-record'));assert(codes.includes('period-gap'));assert.equal(result.status,'needs-input');});
test('zero remains explicit while missing remains blocked',()=>{const f=fixture();f.plan.items['scope1:stationary'].records[0].quantity='0';assert.equal(item(f).zeroQuantityCount,1);f.plan.items['scope1:stationary'].records[0].quantity=null;assert(item(f).findings.some(x=>x.code==='quantity-missing'));});
test('company-wide Scope 3 migrates legacy empty site mode while site-specific category does not',()=>{const f=fixture();f.input.sources.forEach(source=>source.answer='No');f.plan.screening['category-1']={answer:'Yes',reason:'Purchased goods',locationMode:'sites',locationIds:[]};f.plan.screening['category-8']={answer:'Yes',reason:'Leased site',locationMode:'sites',locationIds:[]};f.plan=Plan.reconcile(f.input,f.plan,catalog);for(const id of ['scope3:category-1','scope3:category-8']){const saved=f.plan.items[id];saved.records=[{id,id,recordType:'Ledger',quantity:'1',unit:'USD',quality:'actual',periodStart:'2025-01-01',periodEnd:'2025-12-31',reference:'Ledger'}];saved.needsReview=false;}f.methods.methods.push(...['category-1','category-8'].map(id=>({id,scope:'3',catalogId:id,status:'candidate',acceptedUnits:['USD'],requiredInputs:[]})));const assessment=evaluated(f),wide=assessment.items.find(x=>x.id==='scope3:category-1'),site=assessment.items.find(x=>x.id==='scope3:category-8');assert.equal(wide.locationMode,'company-wide');assert(!wide.findings.some(x=>x.code==='location-unresolved'));assert.equal(site.locationMode,'sites');assert(site.findings.some(x=>x.code==='location-unresolved'));});
test('justified No exclusions do not increase the activity action count',()=>{const f=fixture(),assessment=evaluated(f);assert(assessment.summary.excluded>0);assert.equal(assessment.summary.activityCount,1);});
test('evaluation is deterministic and does not mutate saved inputs',()=>{const f=fixture(),before=JSON.stringify(f);assert.deepEqual(evaluated(f),evaluated(f));assert.equal(JSON.stringify(f),before);});
test('delivered registry resolves every catalog mapping and remains unreleased',()=>{const registry=require('./data/readiness-methods.json'),f=fixture();f.methods=registry;const actual=item(f);assert(actual.methodId);const keys=[...catalog.families.flatMap(x=>x.subtypes.map(t=>t.id)),...catalog.scope2.map(x=>x.id),...catalog.scope3.map(x=>x.id)];for(const key of keys)assert(registry.methods.some(x=>x.catalogId===key),key);assert.equal(actual.readyForCalculation,false);});
test('missing subtype and unsupported activity remain visible input states',()=>{const f=fixture();f.plan.items['scope1:stationary'].subtypeId='';let result=item(f);assert.equal(result.status,'needs-input');assert(result.findings.some(x=>x.code==='subtype-missing'));f.plan.items['scope1:stationary'].subtypeId='absent';f.plan.items['scope1:stationary'].records=[];result=item(f);assert.equal(result.status,'unsupported');assert(evaluated(f).summary.needsInput>0);});
