'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const Core=require('./readiness-core.js'),Plan=require('./plan-core.js'),catalog=require('./data/collection-catalog.json');
function fixture(){const input={company:{legal:'Example',country:'United States'},period:{start:'2025-01-01',end:'2025-12-31'},boundary:{approach:'Operational control',operations:'All'},locations:[{id:'l1',name:'Main',included:'Include'}],sources:[{answer:'Yes',names:'Boiler',location:'l1'},...Array.from({length:4},()=>({answer:'No',notes:'Not operated'}))],changes:[],review:{complete:true,needed:true,role:'Owner'}};const plan=Plan.createPlan(input,catalog);const item=plan.items['scope1:stationary'];item.subtypeId=catalog.families[0].subtypes[0].id;item.locationIds=['l1'];item.records=[{id:'r1',recordType:'Fuel',quantity:'1',unit:'therm',quality:'actual',periodStart:'2025-01-01',periodEnd:'2025-12-31',reference:'Invoice 1'}];const methods={version:'test',methods:[{id:'test',scope:'1',catalogId:item.subtypeId,status:'candidate',acceptedUnits:['therm'],requiredFields:[]}]};const reconciled=Plan.reconcile(input,plan,catalog);reconciled.items['scope1:stationary'].needsReview=false;return {input,plan:reconciled,methods};}
function evaluated(f){return Core.evaluate(f.input,f.plan,catalog,f.methods);}
function item(f){return evaluated(f).items.find(i=>i.id==='scope1:stationary');}
test('complete records remain candidate only even forged release claims',()=>{const f=fixture();f.methods.methods[0].approvalStatus='approved';const result=item(f);assert.equal(result.status,'candidate-for-method-review');assert.equal(result.readyForCalculation,false);assert.equal(evaluated(f).readyForCalculation,false);});
test('zero is explicit while missing is blocked',()=>{const f=fixture();f.plan.items['scope1:stationary'].records[0].quantity='0';assert.equal(item(f).zeroQuantityCount,1);f.plan.items['scope1:stationary'].records[0].quantity=null;assert(item(f).findings.some(x=>x.code==='quantity-missing'));});
test('overlap duplicates and uncovered intervals are separately diagnosed',()=>{const f=fixture();const record=f.plan.items['scope1:stationary'].records[0];record.periodEnd='2025-03-31';f.plan.items['scope1:stationary'].records.push({...record,id:'r2'});const codes=item(f).findings.map(x=>x.code);for(const code of ['period-gap','period-overlap','duplicate-record'])assert(codes.includes(code));});
test('invalid unit, unknown quality, and unsupported methods are explicit',()=>{const f=fixture();Object.assign(f.plan.items['scope1:stationary'].records[0],{unit:'kg',quality:'unknown'});assert(item(f).findings.some(x=>x.code==='unit-incompatible'));assert(item(f).findings.some(x=>x.code==='quality-unknown'));f.methods.methods=[];assert.equal(item(f).status,'unsupported');});
test('required detail, estimation and evidence cannot be replaced by checked boxes',()=>{const f=fixture();f.methods.methods[0].requiredFields=[{id:'fuel',label:'fuel identity'}];const saved=f.plan.items['scope1:stationary'];saved.status='complete';saved.checks={all:true};Object.assign(saved.records[0],{quality:'estimated',reference:''});const codes=item(f).findings.map(x=>x.code);for(const code of ['detail-missing','estimate-basis-missing','evidence-missing'])assert(codes.includes(code));});
test('deterministic evaluation does not mutate input',()=>{const f=fixture(),before=JSON.stringify(f);assert.deepEqual(evaluated(f),evaluated(f));assert.equal(JSON.stringify(f),before);});

test('delivered registry resolves real subtype and all catalog mapping keys',()=>{const registry=require('./data/readiness-methods.json');const f=fixture();f.methods=registry;const actual=item(f);assert(actual.methodId,'real subtype mapping must resolve');const keys=[...catalog.families.flatMap(x=>x.subtypes.map(t=>t.id)),...catalog.scope2.map(x=>x.id),...catalog.scope3.map(x=>x.id)];for(const key of keys)assert(registry.methods.some(x=>x.catalogId===key),key);assert.equal(actual.readyForCalculation,false);});

test('missing subtype is an input gap and unsupported records still count missing inputs',()=>{const f=fixture();f.plan.items['scope1:stationary'].subtypeId='';const result=item(f);assert.equal(result.status,'needs-input');assert(result.findings.some(x=>x.code==='subtype-missing'));f.plan.items['scope1:stationary'].subtypeId='absent';f.plan.items['scope1:stationary'].records=[];assert.equal(item(f).status,'unsupported');assert(evaluated(f).summary.needsInput>0);});
