import {test,expect} from 'bun:test'
import {createPostgresConnection,HostedWorkspaceDatabase,provisionStagingRoster,createM71Seed,M71_ARTIFACT,M71_EVIDENCE_SHA256,M73_PROFILE,M73_PERIOD,M73_LIMITATIONS,m73SourceChoices,m73CanonicalJson,type WorkspaceConnection,type M73SaveInput,type M73Version} from '@neuvetra/database'
import {createM73Routes} from './m73-routes'
import {createM73Authority} from '../calculation/m73-authority'
import {decodeGasRegister,decodeGasVersion,decodeGasReport} from '../../../site-web/src/lib/m73-api'
const target=process.env.M73_TEST_DATABASE_URL
if(target){const u=new URL(target);if(u.hostname!=='127.0.0.1'||u.port!=='55463'||!/^\/m73_author_[a-z0-9_]+$/.test(u.pathname)||u.username!=='m63_test_admin'||u.password||u.search||u.hash)throw Error('M73 requires a new isolated local author fixture.')}
(target?test:test.skip)('M73 native Decimal, append-only lifecycle, reports and direct-runtime boundaries',async()=>{
 const company=crypto.randomUUID(),users={owner:crypto.randomUUID(),manager:crypto.randomUUID(),reviewer:crypto.randomUUID(),member:crypto.randomUUID(),outsider:crypto.randomUUID()},origin='http://127.0.0.1:37373'
 const operator=createPostgresConnection(target!,{tls:false,maxConnections:1}),url=new URL(target!);url.username='neuvetra_runtime'
 const runtime=createPostgresConnection(url.toString(),{tls:false,maxConnections:4}),database=new(HostedWorkspaceDatabase as unknown as new(c:WorkspaceConnection,r:string)=>HostedWorkspaceDatabase)(runtime,'abcdefghijklmnopqrst'),authority=createM73Authority()
 const route=createM73Routes({database,authority,origin,validateUser:async token=>users[token as keyof typeof users]?{id:users[token as keyof typeof users],email:null,phone:null,fullName:null}:null})
 const request=(suffix='',actor:string|null='owner',body?:unknown)=>route(new Request(origin+`/workspace/${company}/stationary-natural-gas`+suffix,{method:body===undefined?'GET':'POST',headers:{origin,...(actor?{authorization:'Bearer '+actor}:{}),...(body!==undefined?{'content-type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)}))
 const read=async(suffix='',actor='owner',body?:unknown)=>{const r=await request(suffix,actor,body);const text=await r.text();expect(r.status,text).toBe(body===undefined?200:201);return JSON.parse(text)}
 try{
  for(const id of Object.values(users))await operator.query('insert into auth.users(id) values($1)',[id])
  await provisionStagingRoster(operator,{expectedProjectRef:'abcdefghijklmnopqrst',workspaceId:company,ownerUserId:users.owner,members:[{userId:users.manager,role:'admin'},{userId:users.reviewer,role:'admin'},{userId:users.member,role:'member'}]})
  await provisionStagingRoster(operator,{expectedProjectRef:'abcdefghijklmnopqrst',workspaceId:crypto.randomUUID(),ownerUserId:users.outsider,members:[]})
  const snapshot=createM71Seed(),sourceId=crypto.randomUUID();snapshot.companyLabel='Synthetic Juniper — actual saved label';snapshot.sources.push({id:sourceId,entityId:snapshot.entities[0]!.id,facilityId:snapshot.facilities[0]!.id,name:'Synthetic dedicated gas boiler',domain:'stationary_combustion',...M73_PERIOD,evidenceRefs:[]});snapshot.coverageItems.push({id:crypto.randomUUID(),entityId:snapshot.entities[0]!.id,sourceId,domain:'stationary_combustion',...M73_PERIOD,disposition:'missing',activityDataState:'missing',evidenceState:'missing',methodReadiness:'candidate',reason:null,evidenceRefs:[],estimateBasis:null,quantity:null,unit:null});snapshot.boundaryDecisions[0]!.reason='Synthetic parent exercises operational control';snapshot.boundaryDecisions[0]!.evidenceRefs=[{artifactId:M71_ARTIFACT.id,expectedSha256:M71_EVIDENCE_SHA256,locator:M71_ARTIFACT.locator,purpose:'Synthetic control basis'}]
  const coverage=await database.saveCorporateInventory(users.owner,company,null,{snapshot,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()}),binding=m73SourceChoices(coverage)[0]!.binding
  const first:M73SaveInput={profile:M73_PROFILE,binding,period:M73_PERIOD,fuel:'Natural Gas',heatBasis:'HHV',unit:'MMBtu',quantityMmbtu:'1250.125',statement:{issuer:'Fictional energy team',reference:'GAS-2025-01',meterLabel:'DEDICATED-01',statedQuantityMmbtu:'1250.125',description:'Fictional annual source-consumed energy; no shared meter or stock adjustments.',consumptionBasis:'dedicated_meter_consumed_no_adjustments'},manualConfirmation:true,discrepancyReason:null,zeroReason:null,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()}
  expect((await request('',null)).status).toBe(401);expect((await request('','outsider')).status).toBe(404);expect((await request('','member',first)).status).toBe(403)
  await decodeGasRegister(await read(),company)
  let v=await decodeGasVersion(await read('','owner',first),company);expect(v.calculation!.total).toEqual({unrounded:'66399.7643125',display:'66399.7643',unit:'kg CO2e',rounding:'half_even_4dp'})
  const worksheet=v.worksheetId,versionsPath=`/${worksheet}/versions`,exportPath=`${versionsPath}/${v.id}/calculation-export`,originalExport=await(await request(exportPath)).text()
  expect(await read('','owner',first)).toEqual(v)
  const reportInput=(version:M73Version)=>({versionId:version.id,expectedVersionSha256:version.versionSha256,expectedDecisionId:version.review?.id??null,expectedDecisionSha256:version.review?.decisionSha256??null,idempotencyKey:crypto.randomUUID()})
  const report=await decodeGasReport(await read(`/${worksheet}/reports`,'owner',reportInput(v)),company,v)
  const download=await request(`/${worksheet}/reports/${report.id}/download`);expect(download.headers.get('content-security-policy')).toContain('sandbox allow-modals');expect(download.headers.get('x-content-type-options')).toBe('nosniff');expect(await download.text()).toBe(report.html)
  const review={versionId:v.id,expectedVersionSha256:v.versionSha256,decision:'accepted_bounded_internal',note:'Bounded independent internal synthetic check.',acknowledgedLimitations:[...M73_LIMITATIONS],idempotencyKey:crypto.randomUUID()}
  expect((await request(`/${worksheet}/reviews`,'owner',review)).status).toBe(403)
  const decision=await read(`/${worksheet}/reviews`,'reviewer',review);v={...v,review:decision}
  expect((await request(`/${worksheet}/reports`,'owner',{...reportInput(v),expectedDecisionId:null,expectedDecisionSha256:null})).status).toBe(409)
  await decodeGasReport(await read(`/${worksheet}/reports`,'owner',reportInput(v)),company,v)
  const correction=(prior:M73Version,quantity:string,reason:string):M73SaveInput=>({...first,quantityMmbtu:quantity,expectedVersionId:prior.id,expectedVersionSha256:prior.versionSha256,correctionReason:reason,discrepancyReason:'Manual entered correction; discrepancy remains open.',idempotencyKey:crypto.randomUUID()})
  const v2=await decodeGasVersion(await read(versionsPath,'manager',correction(v,'1500.125','Correct synthetic meter total')),company,v);expect(v2.review).toBeNull();expect(v2.calculation!.total.display).toBe('79678.3893');expect(v2.findings.some(f=>f.code==='activity_statement_discrepancy')).toBe(true)
  expect(await(await request(exportPath)).text()).toBe(originalExport)
  let current=v2
  for(const [q,display]of [['0.100','5.3114'],['0.300','15.9344'],['999999999999.999','53114499999999.9469']]){current=await decodeGasVersion(await read(versionsPath,'manager',correction(current,q,'Boundary vector '+q)),company,current);expect(current.calculation!.total.display).toBe(display)}
  const missing={...correction(current,'1.000','Mark activity missing'),quantityMmbtu:null,statement:null,manualConfirmation:false};current=await decodeGasVersion(await read(versionsPath,'manager',missing),company,current);expect(current.calculation).toBeNull()
  const zero={...correction(current,'0.000','Explicit supported zero'),statement:{...first.statement!,statedQuantityMmbtu:'0.000'},zeroReason:'Fictional shutdown; no gas consumed.'};current=await decodeGasVersion(await read(versionsPath,'manager',zero),company,current);expect(current.calculation!.total.display).toBe('0.0000')
  for(const change of [{unit:'therm'},{manualConfirmation:false},{statement:null},{quantityMmbtu:'1e3'},{quantityMmbtu:'1.0001'}])expect((await request(versionsPath,'manager',{...correction(current,'1.000','Rejected invalid input'),...change})).status).toBe(422)
  const raceInput=correction(current,'2.000','Concurrent identical retry'),race=await Promise.all([request(versionsPath,'manager',raceInput),request(versionsPath,'manager',raceInput)]);expect(race.map(r=>r.status)).toEqual([201,201]);const raced=await Promise.all(race.map(r=>r.json()));expect(raced[0]).toEqual(raced[1]);current=await decodeGasVersion(raced[0],company,current)
  const retainedRegister=await decodeGasRegister(await read(),company)
  await expect(runtime.query('update neuvetra.stationary_gas_heads set revision=revision where company_id=$1',[company])).rejects.toMatchObject({code:'42501'})
  const invalid=correction(current,'3.000','Forged direct calculation');await expect(runtime.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[users.manager]);await tx.query('select neuvetra.save_stationary_gas($1,$2,$3::text::jsonb,$4::text::jsonb)',[company,worksheet,JSON.stringify(invalid),JSON.stringify({...current.calculation,total:{unrounded:'0',display:'0.0000'}})])})).rejects.toMatchObject({code:'22023'})
  expect((await request(versionsPath,'manager',{...raceInput,quantityMmbtu:'4.000'})).status).toBe(409)
  const contenders=await Promise.all([request(versionsPath,'manager',correction(current,'4.000','First concurrent correction')),request(versionsPath,'manager',correction(current,'5.000','Second concurrent correction'))]);expect(contenders.map(r=>r.status).sort()).toEqual([201,409]);current=await decodeGasVersion(await contenders.find(r=>r.status===201)!.json(),company,current)
  // A new M71 head invalidates new writes against the old binding, but history stays readable.
  const coverage2=await database.saveCorporateInventory(users.owner,company,coverage.inventoryId,{snapshot:{...snapshot,companyLabel:'Synthetic renamed company'},expectedVersionId:coverage.id,expectedVersionSha256:coverage.versionSha256,correctionReason:'Rename only',idempotencyKey:crypto.randomUUID()})
  expect((await request(versionsPath,'manager',correction(current,'6.000','Stale coverage rejected'))).status).toBe(409)
  const relink={...correction(current,'6.000','Pin current corporate version'),binding:m73SourceChoices(coverage2)[0]!.binding};current=await decodeGasVersion(await read(versionsPath,'manager',relink),company,current);expect(current.worksheetId).toBe(worksheet)
  expect((await request(`/${worksheet}/reviews`,'owner',{...review,versionId:current.id,expectedVersionSha256:current.versionSha256,idempotencyKey:crypto.randomUUID()})).status).toBe(403)
  await expect(runtime.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[users.manager]);await tx.query('select neuvetra.save_stationary_gas($1,$2,$3::text::jsonb,null)',[company,worksheet,JSON.stringify({...relink,idempotencyKey:crypto.randomUUID(),statement:{...first.statement!,issuer:'\u00a0leading'}})])})).rejects.toMatchObject({code:'22023'})
  const snapshot3=structuredClone(coverage2.snapshot),source2=crypto.randomUUID();snapshot3.sources.push({...snapshot3.sources.find(x=>x.id===sourceId)!,id:source2,name:'Second dedicated gas source'});snapshot3.coverageItems.push({...snapshot3.coverageItems.find(x=>x.sourceId===sourceId)!,id:crypto.randomUUID(),sourceId:source2})
  const coverage3=await database.saveCorporateInventory(users.owner,company,coverage.inventoryId,{snapshot:snapshot3,expectedVersionId:coverage2.id,expectedVersionSha256:coverage2.versionSha256,correctionReason:'Add independent second source',idempotencyKey:crypto.randomUUID()})
  const second={...first,binding:m73SourceChoices(coverage3).find(x=>x.binding.sourceId===source2)!.binding,idempotencyKey:crypto.randomUUID()};expect((await request('','owner',second)).status).toBe(409)
  const independent={...second,statement:{...first.statement!,reference:'GAS-SECOND-2025',meterLabel:'DEDICATED-SECOND'},idempotencyKey:crypto.randomUUID()};await decodeGasVersion(await read('','owner',independent),company)
  expect((await decodeGasRegister(await read(),company)).worksheets.length).toBe(2)
  // Reserved history bytes include the maximum future review, so review cannot strand history.
  const used=(await operator.query<{used:string}>("select (coalesce((select sum(octet_length(convert_to(export_text,'utf8'))+4096) from neuvetra.stationary_gas_versions where company_id=$1),0)+coalesce((select sum(octet_length(convert_to(payload::text,'utf8'))) from neuvetra.stationary_gas_reports where company_id=$1),0))::text used",[company])).rows[0]!.used
  await operator.exec(`do $$ begin perform neuvetra.m73_capacity('${company}'::uuid,${3800000-Number(used)});begin perform neuvetra.m73_capacity('${company}'::uuid,${3800001-Number(used)});raise exception 'capacity failed to reject';exception when sqlstate '54001' then null;end;end $$;`);expect(Number(used)).toBeGreaterThan(4096*current.version)
  // Revocation applies even to an otherwise valid prior idempotency replay.
  await operator.query('delete from neuvetra.company_members where company_id=$1 and user_id=$2',[company,users.manager]);expect((await request(versionsPath,'manager',raceInput)).status).toBe(503)
  await operator.query("insert into neuvetra.company_members(company_id,user_id,role) values($1,$2,'admin')",[company,users.manager])
  // Reconnect/read through a fresh runtime connection, not a cached worksheet.
  const freshConnection=createPostgresConnection(url.toString(),{tls:false}),fresh=new(HostedWorkspaceDatabase as unknown as new(c:WorkspaceConnection,r:string)=>HostedWorkspaceDatabase)(freshConnection,'abcdefghijklmnopqrst');try{await decodeGasRegister(await fresh.findStationaryGas(users.owner,company,authority),company)}finally{await freshConnection.close()}
  expect(await(await request(`/${worksheet}/reports/${report.id}/download`)).text()).toBe(report.html)
  await Bun.write(`.tmp/m73-native-fixture-${new URL(target!).pathname.slice(1)}.json`,JSON.stringify({companyId:company,register:await decodeGasRegister(await read(),company),originalReport:report},null,2)+'\n')
  console.log(JSON.stringify({status:'m73_native_lifecycle_passed',companyId:company,worksheetId:worksheet,versions:current.version,priorExportPreserved:true}))
 }finally{await runtime.close();await operator.close()}
},120000)
