import {expect,test} from 'bun:test'
import {createPostgresConnection,HostedWorkspaceDatabase,provisionStagingRoster,createM71Seed,M71_ARTIFACT,M71_EVIDENCE_SHA256,M74_PROFILE,M74_PERIOD,M74_LIMITATIONS,m74SourceChoices,readMobileDiesel,m74Hash,m74CalculationHashPayload,m74ContentPayload,m74VersionHashPayload,m74Export,type WorkspaceConnection,type M74SaveInput,type M74Version} from '@neuvetra/database'
import {createM74Routes} from './m74-routes'
import {createM74Authority} from '../calculation/m74-authority'
import {decodeMobileRegister,decodeMobileReport,decodeMobileVersion} from '../../../site-web/src/lib/m74-api'

const target=process.env.M74_TEST_DATABASE_URL
if(target){const url=new URL(target);if(url.hostname!=='127.0.0.1'||url.port!=='55463'||!/^\/m74_author_[a-z0-9_]+$/.test(url.pathname)||url.username!=='m63_test_admin'||url.password||url.search||url.hash)throw Error('M74 requires a new isolated local author fixture.')}

(target?test:test.skip)('M74 native two-evidence Decimal lifecycle, identity reservations and report replay',async()=>{
 const company=crypto.randomUUID(),otherCompany=crypto.randomUUID(),users={owner:crypto.randomUUID(),manager:crypto.randomUUID(),reviewer:crypto.randomUUID(),member:crypto.randomUUID(),outsider:crypto.randomUUID()},origin='http://127.0.0.1:37474'
 const operator=createPostgresConnection(target!,{tls:false,maxConnections:1}),runtimeUrl=new URL(target!);runtimeUrl.username='neuvetra_runtime'
 const runtime=createPostgresConnection(runtimeUrl.toString(),{tls:false,maxConnections:4}),database=new(HostedWorkspaceDatabase as unknown as new(connection:WorkspaceConnection,ref:string)=>HostedWorkspaceDatabase)(runtime,'abcdefghijklmnopqrst'),authority=createM74Authority()
 const route=createM74Routes({database,authority,origin,validateUser:async token=>users[token as keyof typeof users]?{id:users[token as keyof typeof users],email:null,phone:null,fullName:null}:null})
 const request=(suffix='',actor:string|null='owner',body?:unknown)=>route(new Request(origin+`/workspace/${company}/mobile-diesel`+suffix,{method:body===undefined?'GET':'POST',headers:{origin,...(actor?{authorization:'Bearer '+actor}:{}),...(body!==undefined?{'content-type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)}))
 const read=async(suffix='',actor='owner',body?:unknown)=>{const response=await request(suffix,actor,body),text=await response.text();expect(response.status,text).toBe(body===undefined?200:201);return JSON.parse(text)}
 try{
  for(const id of Object.values(users))await operator.query('insert into auth.users(id) values($1)',[id])
  await provisionStagingRoster(operator,{expectedProjectRef:'abcdefghijklmnopqrst',workspaceId:company,ownerUserId:users.owner,members:[{userId:users.manager,role:'admin'},{userId:users.reviewer,role:'admin'},{userId:users.member,role:'member'}]})
  await provisionStagingRoster(operator,{expectedProjectRef:'abcdefghijklmnopqrst',workspaceId:otherCompany,ownerUserId:users.outsider,members:[]})
  const snapshot=createM71Seed(),sourceId=crypto.randomUUID();snapshot.companyLabel='Synthetic Redwood Distribution';snapshot.sources.push({id:sourceId,entityId:snapshot.entities[0]!.id,facilityId:snapshot.facilities[0]!.id,name:'Synthetic distribution vehicle TRUCK-001',domain:'mobile_combustion',...M74_PERIOD,evidenceRefs:[]});snapshot.coverageItems.push({id:crypto.randomUUID(),entityId:snapshot.entities[0]!.id,sourceId,domain:'mobile_combustion',...M74_PERIOD,disposition:'missing',activityDataState:'missing',evidenceState:'missing',methodReadiness:'candidate',reason:null,evidenceRefs:[],estimateBasis:null,quantity:null,unit:null});snapshot.boundaryDecisions[0]!.reason='Synthetic parent exercises full-year operational control';snapshot.boundaryDecisions[0]!.evidenceRefs=[{artifactId:M71_ARTIFACT.id,expectedSha256:M71_EVIDENCE_SHA256,locator:M71_ARTIFACT.locator,purpose:'Synthetic control basis'}]
  const coverage=await database.saveCorporateInventory(users.owner,company,null,{snapshot,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()}),binding=m74SourceChoices(coverage)[0]!.binding
  const first:M74SaveInput={profile:M74_PROFILE,binding,period:M74_PERIOD,vehicle:{assetId:'truck-001',vehicleClass:'Medium- and Heavy-Duty Vehicles',classificationBasis:'Synthetic registration identifies a 2015 medium/heavy-duty on-road vehicle.',modelYear:2015,fuel:'Fossil Diesel',controlBasis:'owned_operational_control_full_year'},quantityGallons:'1000.125',distanceMiles:'12000.500',fuelStatement:{issuer:'Fictional fleet fuel system',reference:'FUEL-TRUCK-001-2025',statedQuantityGallons:'1000.125',description:'Fictional annual fossil diesel consumed by the dedicated vehicle with no tank adjustment or auxiliary allocation.',consumptionBasis:'dedicated_vehicle_consumed_no_adjustments'},mileageStatement:{issuer:'Fictional telematics system',reference:'MILES-TRUCK-001-2025',statedDistanceMiles:'12000.500',description:'Fictional annual dedicated-vehicle distance including every trip location and interstate travel.',distanceBasis:'dedicated_vehicle_annual_distance'},fuelManualConfirmation:true,mileageManualConfirmation:true,fuelDiscrepancyReason:null,mileageDiscrepancyReason:null,zeroReason:null,expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()}
  expect((await request('',null)).status).toBe(401);expect((await request('','outsider')).status).toBe(404);expect((await request('','member',first)).status).toBe(403)
  await decodeMobileRegister(await read(),company)
  let version=await decodeMobileVersion(await read('','owner',first),company);expect(version.activity.vehicle.assetId).toBe('TRUCK-001');expect(version.calculation!.total).toEqual({unrounded:'10351.53209375',display:'10351.5321',unit:'kg CO2e',rounding:'half_even_4dp'});expect(version.calculation!.gasResults.co2.mass).toBe('10211.27625')
  const worksheet=version.worksheetId,versionsPath=`/${worksheet}/versions`,originalExport=await(await request(`${versionsPath}/${version.id}/calculation-export`)).text()
  expect(await read('','owner',first)).toEqual(version)
  const reportInput=(item:M74Version)=>({versionId:item.id,expectedVersionSha256:item.versionSha256,expectedDecisionId:item.review?.id??null,expectedDecisionSha256:item.review?.decisionSha256??null,idempotencyKey:crypto.randomUUID()})
  const unreviewed=await decodeMobileReport(await read(`/${worksheet}/reports`,'owner',reportInput(version)),company,version);expect(unreviewed.html).toContain('Vehicle mobile-combustion subtotal');expect(unreviewed.html).toContain('FUEL-TRUCK-001-2025');expect(unreviewed.html).toContain('MILES-TRUCK-001-2025')
  for(const statement of [version.fuelStatement!,version.mileageStatement!]){const response=await request(`/${worksheet}/statements/${statement.id}/download`);expect(response.headers.get('x-content-type-options')).toBe('nosniff');expect(await response.text()).toBe(statement.text)}
  const review={versionId:version.id,expectedVersionSha256:version.versionSha256,decision:'accepted_bounded_internal',note:'Bounded independent internal synthetic check.',acknowledgedLimitations:[...M74_LIMITATIONS],idempotencyKey:crypto.randomUUID()}
  expect((await request(`/${worksheet}/reviews`,'owner',review)).status).toBe(403);const decision=await read(`/${worksheet}/reviews`,'reviewer',review);version={...version,review:decision};await decodeMobileReport(await read(`/${worksheet}/reports`,'owner',reportInput(version)),company,version)
  const correction=(prior:M74Version,patch:Partial<M74SaveInput>,reason:string):M74SaveInput=>({...first,...patch,vehicle:{...first.vehicle,...patch.vehicle},expectedVersionId:prior.id,expectedVersionSha256:prior.versionSha256,correctionReason:reason,idempotencyKey:crypto.randomUUID()})
  const milesOnly=correction(version,{distanceMiles:'12500.500',mileageDiscrepancyReason:'Entered mileage was corrected; the retained statement difference remains visible.'},'Correct entered mileage only');let current=await decodeMobileVersion(await read(versionsPath,'manager',milesOnly),company,version);expect(current.calculation!.total.display).toBe('10357.3758');expect(current.calculation!.gasResults.co2).toEqual(version.calculation!.gasResults.co2);expect(current.review).toBeNull();expect(await(await request(`${versionsPath}/${version.id}/calculation-export`)).text()).toBe(originalExport)
  for(const [gallons,miles,display] of [['1.000','2.400','10.2380'],['1.000','0.800','10.2194'],['999999999999.999','999999999999.999','10221687499999.9898']]){const input=correction(current,{quantityGallons:gallons,distanceMiles:miles,fuelDiscrepancyReason:'Boundary-vector difference retained.',mileageDiscrepancyReason:'Boundary-vector difference retained.'},`Boundary vector ${gallons}/${miles}`);current=await decodeMobileVersion(await read(versionsPath,'manager',input),company,current);expect(current.calculation!.total.display).toBe(display)}
  const missing=correction(current,{distanceMiles:null,mileageStatement:null,mileageManualConfirmation:false,mileageDiscrepancyReason:null},'Retain incomplete missing mileage');current=await decodeMobileVersion(await read(versionsPath,'manager',missing),company,current);expect(current.calculation).toBeNull();expect(current.activityStatus.mileage).toBe('missing')
  const mixed=correction(current,{quantityGallons:'0.000',distanceMiles:'1.000',fuelStatement:{...first.fuelStatement!,statedQuantityGallons:'0.000'},mileageStatement:{...first.mileageStatement!,statedDistanceMiles:'1.000'},fuelDiscrepancyReason:null,mileageDiscrepancyReason:null},'Retain mixed-zero contradiction');current=await decodeMobileVersion(await read(versionsPath,'manager',mixed),company,current);expect(current.calculation).toBeNull();expect(current.findings.some(item=>item.code==='mixed_zero_contradiction')).toBe(true)
  const zero=correction(current,{quantityGallons:'0.000',distanceMiles:'0.000',fuelStatement:{...first.fuelStatement!,statedQuantityGallons:'0.000'},mileageStatement:{...first.mileageStatement!,statedDistanceMiles:'0.000'},zeroReason:'Fictional vehicle did not operate or consume fuel.',fuelDiscrepancyReason:null,mileageDiscrepancyReason:null},'Explicit supported zero');current=await decodeMobileVersion(await read(versionsPath,'manager',zero),company,current);expect(current.calculation!.total.display).toBe('0.0000')
  for(const change of [{vehicle:{...first.vehicle,modelYear:2023}},{vehicle:{...first.vehicle,fuel:'Renewable Diesel'}},{quantityGallons:'1e3'},{distanceMiles:'1.0001'},{quantityUnit:'litre'}])expect((await request(versionsPath,'manager',{...correction(current,{},'Reject unsupported input'),...change})).status).toBe(422)
  expect((await request(versionsPath,'manager',correction(current,{vehicle:{...first.vehicle,assetId:'TRUCK-002'}},'Attempt vehicle replacement'))).status).toBe(409)
  const replay=correction(current,{quantityGallons:'2.000',distanceMiles:'2.000',fuelDiscrepancyReason:'Retry fixture difference.',mileageDiscrepancyReason:'Retry fixture difference.',zeroReason:null},'Concurrent exact retry'),race=await Promise.all([request(versionsPath,'manager',replay),request(versionsPath,'manager',replay)]);expect(race.map(item=>item.status)).toEqual([201,201]);const raced=await Promise.all(race.map(item=>item.json()));expect(raced[0]).toEqual(raced[1]);current=await decodeMobileVersion(raced[0],company,current);expect((await request(versionsPath,'manager',{...replay,quantityGallons:'3.000'})).status).toBe(409)
  const forged=correction(current,{quantityGallons:'4.000',distanceMiles:'4.000',fuelDiscrepancyReason:'Forged fixture difference.',mileageDiscrepancyReason:'Forged fixture difference.'},'Forged direct result');await expect(runtime.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[users.manager]);await tx.query('select neuvetra.save_mobile_diesel($1,$2,$3::text::jsonb,$4::text::jsonb)',[company,worksheet,JSON.stringify(forged),JSON.stringify({...current.calculation,total:{unrounded:'0',display:'0.0000'}})])})).rejects.toMatchObject({code:'22023'})
  const coverageSnapshot=structuredClone(coverage.snapshot),secondSource=crypto.randomUUID(),thirdSource=crypto.randomUUID();for(const [id,name]of [[secondSource,'Aliased second source'],[thirdSource,'Concurrent third source']]as const){coverageSnapshot.sources.push({...coverageSnapshot.sources.find(item=>item.id===sourceId)!,id,name});coverageSnapshot.coverageItems.push({...coverageSnapshot.coverageItems.find(item=>item.sourceId===sourceId)!,id:crypto.randomUUID(),sourceId:id})}const coverage2=await database.saveCorporateInventory(users.owner,company,coverage.inventoryId,{snapshot:coverageSnapshot,expectedVersionId:coverage.id,expectedVersionSha256:coverage.versionSha256,correctionReason:'Add duplicate-identity challenge sources',idempotencyKey:crypto.randomUUID()}),choices=m74SourceChoices(coverage2),secondBinding=choices.find(item=>item.binding.sourceId===secondSource)!.binding,thirdBinding=choices.find(item=>item.binding.sourceId===thirdSource)!.binding
  expect((await request(versionsPath,'manager',correction(current,{binding:m74SourceChoices(coverage2).find(item=>item.binding.sourceId===sourceId)!.binding},'Relink current coverage'))).status).toBe(201)
  const raceBase={...first,vehicle:{...first.vehicle,assetId:'TRUCK-RACE'},fuelStatement:{...first.fuelStatement!,reference:'FUEL-RACE-2025'},mileageStatement:{...first.mileageStatement!,reference:'MILES-RACE-2025'}},raceInputs=[{...raceBase,binding:secondBinding,idempotencyKey:crypto.randomUUID()},{...raceBase,binding:thirdBinding,fuelStatement:{...raceBase.fuelStatement!,reference:'FUEL-RACE-B-2025'},mileageStatement:{...raceBase.mileageStatement!,reference:'MILES-RACE-B-2025'},idempotencyKey:crypto.randomUUID()}],duplicateRace=await Promise.all(raceInputs.map(input=>request('','owner',input)));expect(duplicateRace.map(item=>item.status).sort()).toEqual([201,409]);const failedIndex=duplicateRace.findIndex(item=>item.status===409),winnerIndex=1-failedIndex,winner=raceInputs[winnerIndex]!,failedBinding=raceInputs[failedIndex]!.binding
  const duplicateEvidence={...first,binding:failedBinding,vehicle:{...first.vehicle,assetId:'TRUCK-002'},fuelStatement:winner.fuelStatement,mileageStatement:{...first.mileageStatement!,reference:'MILES-TRUCK-002-2025'},idempotencyKey:crypto.randomUUID()};expect((await request('','owner',duplicateEvidence)).status).toBe(409)
  const independent={...duplicateEvidence,fuelStatement:{...first.fuelStatement!,reference:'FUEL-TRUCK-002-2025'},idempotencyKey:crypto.randomUUID()};await decodeMobileVersion(await read('','owner',independent),company);expect((await decodeMobileRegister(await read(),company)).worksheets.length).toBe(3)
  const beforeTamper=await decodeMobileRegister(await read(),company),victim=structuredClone(beforeTamper.worksheets.find(item=>item.sourceId===sourceId)!.versions.at(-1)!)
  victim.calculation!.method={...victim.calculation!.method,co2KgPerGallon:'10.210000000000001',factorSha256:'f'.repeat(64)};victim.calculation!.resultSha256=m74Hash(m74CalculationHashPayload(victim.calculation!));victim.contentSha256=m74Hash(m74ContentPayload(victim));victim.versionSha256=m74Hash(m74VersionHashPayload(victim))
  let coordinatedTamperRefused=false;try{await operator.transaction(async tx=>{await tx.exec("set local session_replication_role='replica'");await tx.query('update neuvetra.mobile_diesel_versions set payload=$2::text::jsonb,content_sha256=$3,version_sha256=$4,export_text=$5 where id=$1',[victim.id,JSON.stringify(victim),victim.contentSha256,victim.versionSha256,m74Export(victim)]);await tx.query("update neuvetra.mobile_diesel_audit set record_sha256=$2 where kind='save' and record_id=$1",[victim.id,victim.versionSha256]);await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[users.owner]);try{await readMobileDiesel(tx,company,authority)}catch{coordinatedTamperRefused=true}throw Error('rollback-coordinated-tamper')})}catch(error){expect((error as Error).message).toBe('rollback-coordinated-tamper')}expect(coordinatedTamperRefused).toBe(true)
  await operator.query('delete from neuvetra.company_members where company_id=$1 and user_id=$2',[company,users.manager]);expect((await request(versionsPath,'manager',replay)).status).toBe(503)
  const freshConnection=createPostgresConnection(runtimeUrl.toString(),{tls:false}),fresh=new(HostedWorkspaceDatabase as unknown as new(connection:WorkspaceConnection,ref:string)=>HostedWorkspaceDatabase)(freshConnection,'abcdefghijklmnopqrst');try{await decodeMobileRegister(await fresh.findMobileDiesel(users.owner,company,authority),company)}finally{await freshConnection.close()}
  const nativeRegister=await decodeMobileRegister(await read(),company),receipt={status:'m74_native_lifecycle_passed',companyId:company,worksheetId:worksheet,versions:nativeRegister.worksheets.reduce((sum,item)=>sum+item.versions.length,0),priorExportPreserved:true,pythonAndSqlIndependentReplay:true,duplicateVehicleRaceRefused:true,register:nativeRegister}
  await Bun.write(`.tmp/m74-native-fixture-${new URL(target!).pathname.slice(1)}.json`,JSON.stringify(receipt,null,2)+'\n');const {register:_,...summary}=receipt;console.log(JSON.stringify(summary))
 }finally{await runtime.close();await operator.close()}
},120000)
