import {expect,test} from 'bun:test'
import {createM78AuthorDatabase,openM78Fixture,m78FixtureProcessInput,rebindM78Fixture,m78ImmutableRowHashes,m78BaselineDigests} from '../../../../tools/staging/m78-backend-fixture'
import {createM78Routes} from './m78-routes'
import {M78_REVIEWED_POLICY} from '../../../../packages/neuvetra-database/src/m78-policy'
import {M78_LIMITATIONS,M78_MAX_RESPONSE_BYTES,M78_MAX_HISTORY_BYTES,M78_MAX_PROOF_BYTES,type M78VersionEnvelope,type M78Register,type M78ProcessActivity} from '../../../../packages/neuvetra-database/src/m78-contract'
import {m78Sum,m78Multiply,m78Display,buildM78Dependencies,m78ProcessProof,m78Contributors,deriveM78Reconciliation} from '../../../../packages/neuvetra-database/src/m78-reconciliation'
import {m78Hash,m78ContentHashPayload,m78VersionHashPayload,m78CheckResponseCapacity} from '../../../../packages/neuvetra-database/src/m78'
import {parseM78Json,m78CanonicalJson} from '../../../../packages/neuvetra-database/src/m78-validation'
import {decodeScope1Version,decodeScope1Register,decodeScope1Report} from '../../../site-web/src/lib/m78-api'
import {provisionStagingRoster,createM71Seed} from '../../../../packages/neuvetra-database/src/index'
test('M78 exact gross algebra and half-even display preserve tiny emissions',()=>{expect(m78Sum(['0.0000005','0.0000005'])).toBe('0.000001');expect(m78Multiply('0.000003','3350')).toBe('0.01005');expect(m78Display('0.01005')).toBe('0.0100');expect(m78Display('0.01015')).toBe('0.0102');expect(m78Multiply('2','1924')).toBe('3848');expect(()=>m78Sum(['-1'])).toThrow()})
test('Unknown discovery with no eligible contribution has no zero subtotal',()=>{const recon={dependencySha256:'1'.repeat(64),contentSha256:'2'.repeat(64),status:'blocked',rows:[],assets:[],findings:[]},discovery={version:null,review:null,reconciliation:recon},p={priorVersions:[],coverageVersion:{id:crypto.randomUUID(),versionSha256:'3'.repeat(64),review:null,findings:[],snapshot:{entities:[],facilities:[],relationships:[],boundaryDecisions:[],coverageItems:[],requirements:[],sources:[]}},boundCoverageVersions:[],sourceVersions:[],fleet:discovery,stationary:discovery,fugitive:discovery,process:null,policy:M78_REVIEWED_POLICY}as any,r=deriveM78Reconciliation(p,m78Hash);expect(r.status).toBe('blocked');expect(r.knownSourceSubtotal).toBeNull();expect(r.totals).toBeNull()})
test('Response budget matches strict parser maximum retains4MBproof and bounded30MBstorage',()=>{expect(M78_MAX_RESPONSE_BYTES).toBe(10000000);expect(M78_MAX_PROOF_BYTES).toBe(4000000);expect(M78_MAX_HISTORY_BYTES).toBe(30000000);const exact='π'.repeat((M78_MAX_RESPONSE_BYTES-2)/2);expect(()=>m78CheckResponseCapacity(exact)).not.toThrow();expect(parseM78Json(JSON.stringify(exact),M78_MAX_RESPONSE_BYTES)).toBe(exact);expect(()=>m78CheckResponseCapacity(exact+'x')).toThrow('response capacity');expect(()=>parseM78Json(JSON.stringify(exact+'x'),M78_MAX_RESPONSE_BYTES)).toThrow()})
test.skipIf(process.env.NEUVETRA_NATIVE_M78!=='1')('M78 fresh company persists blocked inventory without turning unknown into zero',async()=>{
 const name='m78_author_minimal_'+Date.now(),f=await openM78Fixture(await createM78AuthorDatabase(name)),companyId=crypto.randomUUID(),users={owner:crypto.randomUUID(),reviewer:crypto.randomUUID()};let posts=0;
 try{
  for(const id of Object.values(users))await f.operator.query('insert into auth.users(id)values($1)',[id]);
  await provisionStagingRoster(f.operator,{expectedProjectRef:f.projectRef,workspaceId:companyId,ownerUserId:users.owner,members:[{userId:users.reviewer,role:'admin'}]});
  await f.database.saveCorporateInventory(users.owner,companyId,null,{snapshot:createM71Seed(),expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()});
  const routes=createM78Routes({database:f.database,authorities:f.authorities,policy:M78_REVIEWED_POLICY,origin:'http://localhost:4198',validateUser:async token=>users[token as keyof typeof users]?{id:users[token as keyof typeof users]}as any:null});
  const call=(path:string,body?:unknown,role='owner')=>{if(body!==undefined)posts++;return routes(new Request('http://localhost:4199/workspace/'+companyId+'/'+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer '+role,origin:'http://localhost:4198','content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}))};
  const get=async()=>{const response=await call('scope1-inventory');expect(response.status).toBe(200);return decodeScope1Register(await response.json(),companyId)};
  const post=async(path:string,body:unknown,role='owner')=>{const response=await call(path,body,role);expect(response.status,await response.clone().text()).toBe(201);return response.json()};
  const reportInput=(e:M78VersionEnvelope)=>({versionId:e.version.id,expectedVersionSha256:e.version.versionSha256,expectedDecisionId:e.version.review?.id??null,expectedDecisionSha256:e.version.review?.decisionSha256??null,expectedReconciliationSha256:e.version.reconciliation?.contentSha256??null,idempotencyKey:crypto.randomUUID()});
  const changes=(e:M78VersionEnvelope)=>({versionId:e.version.id,expectedVersionSha256:e.version.versionSha256,expectedDependencySha256:e.version.dependencies.dependencySha256,decision:'changes_requested',note:'Separate review retains unknown gas and process applicability.',acknowledgedLimitations:[...M78_LIMITATIONS],idempotencyKey:crypto.randomUUID()});
  let r=await get();expect(r.proof.sourceVersions).toHaveLength(0);expect(r.reconciliation.knownSourceSubtotal).toBeNull();
  const first=await decodeScope1Version(await post('process-screen',m78FixtureProcessInput(r,false)),companyId),processPath='process-screen/'+first.version.streamId;
  const retained=await decodeScope1Report(await post(processPath+'/reports',reportInput(first)),companyId);await post(processPath+'/reviews',changes(first),'reviewer');
  r=await get();const second=await decodeScope1Version(await post(processPath+'/versions',{...first.version.activity,manualConfirmation:true,expectedVersionId:first.version.id,expectedVersionSha256:first.version.versionSha256,expectedDependencySha256:buildM78Dependencies(r.proof,'process_screen',m78Hash).dependencySha256,correctionReason:'Confirmation correction preserves every unresolved gas and category.',idempotencyKey:crypto.randomUUID()}),companyId,first.version);await post(processPath+'/reviews',changes(second),'reviewer');
  r=await get();const inventory=await decodeScope1Version(await post('scope1-inventory',{profile:'synthetic-scope1-inventory-v1',binding:second.version.activity.binding,note:'Blocked empty-source inventory retains unknown applicability.',expectedVersionId:null,expectedVersionSha256:null,expectedDependencySha256:buildM78Dependencies(r.proof,'inventory',m78Hash).dependencySha256,correctionReason:null,idempotencyKey:crypto.randomUUID()}),companyId);
  expect(inventory.version.reconciliation?.totals).toBeNull();expect(inventory.version.reconciliation?.knownSourceSubtotal).toBeNull();for(const finding of inventory.version.findings.filter(x=>['discovery_blocked','process_screen_blocked'].includes(x.code)))expect(finding.origin.family).toBe('m78');
  const inventoryPath='scope1-inventory/'+inventory.version.streamId,old=await decodeScope1Report(await post(inventoryPath+'/reports',reportInput(inventory)),companyId);await post(inventoryPath+'/reviews',changes(inventory),'reviewer');
  expect(await(await call(processPath+'/reports/'+retained.id)).json()).toEqual(retained);expect(await(await call(inventoryPath+'/reports/'+old.id)).json()).toEqual(old);expect(JSON.parse(old.snapshotJson).review).toBeNull();
  const final=await get();expect(final.versionProofs).toHaveLength(3);expect(final.reconciliation.status).toBe('blocked');
  await Bun.write('.superpowers/'+name+'-result.json',JSON.stringify({status:'author_native_m78_minimal_blocked_pass',database:name,companyId,users,migrationSha256:f.migrationSha256,applicationPostRequests:posts,actualRoutes:true,browserDecoders:true,independentReview:'pending',final},null,2));
 }catch(e){await Bun.write('.superpowers/'+name+'-failed.json',JSON.stringify({status:'author_native_m78_minimal_failed',database:name,migrationSha256:f.migrationSha256,message:(e as Error).message,applicationPostRequests:posts},null,2));throw e}finally{await f.runtime.close();await f.operator.close()}
},240000)
test.skipIf(process.env.NEUVETRA_NATIVE_M78!=='1')('M78 valid oversize successor refuses atomically and retained history remains readable',async()=>{
 const name='m78_author_capacity_'+Date.now(),f=await openM78Fixture(await createM78AuthorDatabase(name)),companyId=crypto.randomUUID(),users={owner:crypto.randomUUID(),reviewer:crypto.randomUUID()},errors:any[]=[];let posts=0;
 const routes=createM78Routes({database:new Proxy(f.database,{get(target,key){const value=(target as any)[key];return typeof value==='function'?async(...args:unknown[])=>{try{return await value.apply(target,args)}catch(e){errors.push({code:(e as any).code,capacityKind:(e as any).capacityKind,message:(e as Error).message});throw e}}:value}}),authorities:f.authorities,policy:M78_REVIEWED_POLICY,origin:'http://localhost:4198',validateUser:async()=>({id:users.owner}as any)}),call=(path:string,body?:unknown)=>{if(body!==undefined)posts++;return routes(new Request('http://localhost:4199/workspace/'+companyId+'/'+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer synthetic-capacity-clone',origin:'http://localhost:4198','content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}))};
 const get=async()=>{const response=await call('scope1-inventory');expect(response.status).toBe(200);return decodeScope1Register(await response.json(),companyId)};
 try{
  for(const id of Object.values(users))await f.operator.query('insert into auth.users(id)values($1)',[id]);
  await provisionStagingRoster(f.operator,{expectedProjectRef:f.projectRef,workspaceId:companyId,ownerUserId:users.owner,members:[{userId:users.reviewer,role:'admin'}]});await f.database.saveCorporateInventory(users.owner,companyId,null,{snapshot:createM71Seed(),expectedVersionId:null,expectedVersionSha256:null,correctionReason:null,idempotencyKey:crypto.randomUUID()});
  let r=await get(),draft=m78FixtureProcessInput(r,false);const location=r.coverageVersion.snapshot.facilities[0]!;draft.evidenceStatements.push(...Array.from({length:42},(_,i)=>({reference:'CAPACITY-INSPECTION-'+i.toString().padStart(2,'0'),issuer:'SYNTHETIC-CAPACITY-INSPECTOR',description:('Synthetic retained inspection note; gas and process applicability remain unknown. ').repeat(24).trim(),issuedOn:'2025-12-31',purpose:'process_inspection' as const,entityId:location.entityId,facilityId:location.id})));
  const firstResponse=await call('process-screen',draft);expect(firstResponse.status,await firstResponse.clone().text()).toBe(201);const first=await decodeScope1Version(await firstResponse.json(),companyId),path='process-screen/'+first.version.streamId,reportResponse=await call(path+'/reports',{versionId:first.version.id,expectedVersionSha256:first.version.versionSha256,expectedDecisionId:null,expectedDecisionSha256:null,expectedReconciliationSha256:null,idempotencyKey:crypto.randomUUID()});expect(reportResponse.status).toBe(201);const retained=await decodeScope1Report(await reportResponse.json(),companyId);r=await get();let refused=false;
  for(let i=0;i<14;i++){
   const prior=r.process.versions[r.process.versions.length-1]!,activity=prior.activity as M78ProcessActivity,before=await m78BaselineDigests(f.operator),response=await call(path+'/versions',{...activity,locations:activity.locations.map((l,j)=>j===0?{...l,businessActivities:'Valid synthetic capacity clarification '+i+' preserves unknown process and gas facts.'}:l),expectedVersionId:prior.id,expectedVersionSha256:prior.versionSha256,expectedDependencySha256:buildM78Dependencies(r.proof,'process_screen',m78Hash).dependencySha256,correctionReason:'Valid factual note correction exercises bounded retained response history.',idempotencyKey:crypto.randomUUID()}),body=await response.json();
   if(response.status===201){await decodeScope1Version(body,companyId,prior);r=await get();continue}
   expect(response.status).toBe(422);expect(body.code).toBe('history_limit');expect(errors[errors.length-1]).toMatchObject({code:'54000',capacityKind:'register_response'});expect(await m78BaselineDigests(f.operator)).toEqual(before);const read=await call('scope1-inventory');expect(read.status).toBe(200);expect(await read.json()).toEqual(r);const old=await call(path+'/reports/'+retained.id);expect(old.status).toBe(200);expect(await old.json()).toEqual(retained);refused=true;break;
  }expect(refused).toBe(true);await Bun.write('.superpowers/'+name+'-result.json',JSON.stringify({status:'author_native_m78_response_capacity_atomic_pass',name,companyId,migrationSha256:f.migrationSha256,applicationPostRequests:posts,validUnknownProcessSuccessors:true,validResponseCapacityRefusal:true,all121TableRowsUnchangedOnRefusal:true,oldRegisterAndReportReadable:true,sourceWrites:false,registerBytes:new TextEncoder().encode(m78CanonicalJson(r)).length,errors,independentReview:'pending'},null,2));
 }catch(e){await Bun.write('.superpowers/'+name+'-failed.json',JSON.stringify({status:'author_native_m78_response_capacity_failed',name,migrationSha256:f.migrationSha256,applicationPostRequests:posts,message:(e as Error).message,errors},null,2));throw e}finally{await f.runtime.close();await f.operator.close()}
},240000)
test.skipIf(process.env.NEUVETRA_NATIVE_M78!=='1')('M78 native authenticated process/inventory persistence and retained proof lifecycle',async()=>{
 const name='m78_author_native_'+Date.now(),f=await openM78Fixture(await createM78AuthorDatabase(name));let posts=0;const boundaryErrors:any[]=[];
 const tokens=Object.fromEntries(Object.entries(f.users).map(([role,id])=>['synthetic-m78-'+role,id])),routes=createM78Routes({database:new Proxy(f.database,{get(target,key){const value=(target as any)[key];return typeof value==='function'?async(...args:unknown[])=>{try{return await value.apply(target,args)}catch(e){const diagnostic={nativeBoundary:String(key),code:(e as any).code,message:(e as Error).message,where:(e as any).where,capacityKind:(e as any).capacityKind};boundaryErrors.push(diagnostic);console.error(JSON.stringify(diagnostic));throw e}}:value}}),authorities:f.authorities,policy:M78_REVIEWED_POLICY,origin:'http://localhost:4198',validateUser:async token=>tokens[token]?{id:tokens[token]}as any:null});
 const call=async(path:string,role='owner',body?:unknown)=>{if(body!==undefined)posts++;return routes(new Request('http://localhost:4199/workspace/'+f.companyId+'/'+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer synthetic-m78-'+role,origin:'http://localhost:4198','content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}))};
 const get=async()=>{const r=await call('scope1-inventory');expect(r.status).toBe(200);const v=await r.json()as M78Register;await decodeScope1Register(v,f.companyId);return v};
 const post=async(path:string,body:unknown,role='owner')=>{const r=await call(path,role,body),value=await r.json();if(r.status!==201)throw Error(JSON.stringify({path,status:r.status,value}));return value};
 const reportInput=(e:M78VersionEnvelope)=>({versionId:e.version.id,expectedVersionSha256:e.version.versionSha256,expectedDecisionId:e.version.review?.id??null,expectedDecisionSha256:e.version.review?.decisionSha256??null,expectedReconciliationSha256:e.version.reconciliation?.contentSha256??null,idempotencyKey:crypto.randomUUID()});
 try{
  const oldRows=await m78ImmutableRowHashes(f.operator);expect(f.functionMetadata.after).toHaveLength(6);
  expect(f.register.coverageVersion.snapshot.facilities).toHaveLength(3);expect(f.register.proof.sourceVersions).toHaveLength(10);expect(f.register.reconciliation.totals).toBeNull();expect((await call('scope1-inventory','outsider')).status).toBe(403);expect((await call('scope1-inventory','member',{})).status).toBe(403);
  let r=await get();const blockedInput=m78FixtureProcessInput(r,false),blocked=await post('process-screen',blockedInput)as M78VersionEnvelope;await decodeScope1Version(blocked,f.companyId);expect(blocked.version.findings.some(f=>f.classification==='functional_blocker')).toBe(true);expect(blocked.proof.process).toBeNull();const replay=await post('process-screen',blockedInput)as M78VersionEnvelope;expect(replay.version.id).toBe(blocked.version.id);const oldReport=await post('process-screen/'+blocked.version.streamId+'/reports',reportInput(blocked));await decodeScope1Report(oldReport,f.companyId);
  expect((await call('process-screen/'+blocked.version.streamId+'/reviews','owner',{versionId:blocked.version.id,expectedVersionSha256:blocked.version.versionSha256,expectedDependencySha256:blocked.version.dependencies.dependencySha256,decision:'changes_requested',note:'Self review must fail.',acknowledgedLimitations:[...M78_LIMITATIONS],idempotencyKey:crypto.randomUUID()})).status).toBe(403);
  r=await rebindM78Fixture(f);await decodeScope1Register(r,f.companyId);const correctedInput={...m78FixtureProcessInput(r,true),locations:blockedInput.locations,evidenceStatements:blockedInput.evidenceStatements,expectedVersionId:blocked.version.id,expectedVersionSha256:blocked.version.versionSha256,correctionReason:'Complete explicit fictional seven-gas discovery after all source and discovery rebindings.',idempotencyKey:crypto.randomUUID()};correctedInput.assessments=correctedInput.assessments.map(a=>({...a,locationRowIds:blockedInput.locations.map(l=>l.rowId).sort()}));correctedInput.gasCoverage=correctedInput.gasCoverage.map(g=>({...g,locationRowIds:blockedInput.locations.map(l=>l.rowId).sort()}));const process=await post('process-screen/'+blocked.version.streamId+'/versions',correctedInput)as M78VersionEnvelope;await decodeScope1Version(process,f.companyId,blocked.version);expect(process.version.findings.filter(f=>f.classification==='functional_blocker')).toEqual([]);
  await post('process-screen/'+process.version.streamId+'/reviews',{versionId:process.version.id,expectedVersionSha256:process.version.versionSha256,expectedDependencySha256:process.version.dependencies.dependencySha256,decision:'accepted_bounded_process_screen',note:'Separate complete fictional gas/category/site/offsite review.',acknowledgedLimitations:[...M78_LIMITATIONS],idempotencyKey:crypto.randomUUID()},'reviewer');
  r=await get();expect(r.reconciliation.status).toBe('reconciled_bounded_synthetic');expect(r.reconciliation.totals?.sourceRows).toHaveLength(10);const inventory=await post('scope1-inventory',{profile:'synthetic-scope1-inventory-v1',binding:process.version.activity.binding,note:'Gross synthetic compatible inventory, no offsets, no release eligibility.',expectedVersionId:null,expectedVersionSha256:null,expectedDependencySha256:buildM78Dependencies(r.proof,'inventory',m78Hash).dependencySha256,correctionReason:null,idempotencyKey:crypto.randomUUID()})as M78VersionEnvelope;await decodeScope1Version(inventory,f.companyId);const pending=await post('scope1-inventory/'+inventory.version.streamId+'/reports',reportInput(inventory));await decodeScope1Report(pending,f.companyId);
  await post('scope1-inventory/'+inventory.version.streamId+'/reviews',{versionId:inventory.version.id,expectedVersionSha256:inventory.version.versionSha256,expectedDependencySha256:inventory.version.dependencies.dependencySha256,decision:'accepted_bounded_inventory',note:'Separate exact gross source/gas/location/entity candidate reconciliation review.',acknowledgedLimitations:[...M78_LIMITATIONS],idempotencyKey:crypto.randomUUID()},'reviewer');const reviewed=await f.database.findScope1Version(f.users.owner,f.companyId,inventory.version.streamId,inventory.version.id,f.authorities,M78_REVIEWED_POLICY);const accepted=await post('scope1-inventory/'+inventory.version.streamId+'/reports',reportInput(reviewed!));await decodeScope1Report(accepted,f.companyId);expect(accepted.html).toContain('Seven-gas applicability and process discovery');expect(accepted.html).toContain('default higher heating value');expect(accepted.html).toContain('linked prior releases are included once');expect(accepted.html).toContain('SF6');expect(accepted.html).toContain('71000000-0000-4000-8000-000000000021');expect(accepted.html).not.toContain('href="/workspace');
  const old=await(await call('process-screen/'+blocked.version.streamId+'/reports/'+oldReport.id)).json();expect(old).toEqual(oldReport);const oldPending=await(await call('scope1-inventory/'+inventory.version.streamId+'/reports/'+pending.id)).json();expect(oldPending).toEqual(pending);expect(JSON.parse(oldPending.snapshotJson).review).toBeNull();let final=await get();expect(final.versionProofs).toHaveLength(3);expect(final.process.versions).toHaveLength(2);expect(final.inventory.versions).toHaveLength(1);expect(final.inventory.reports).toHaveLength(2);
  await expect(f.runtime.query('select neuvetra.m78_policy()')).rejects.toMatchObject({code:'42501'});await expect(f.runtime.query('update neuvetra.scope1_versions set payload=payload')).rejects.toMatchObject({code:'42501'});await expect(f.operator.query('update neuvetra.scope1_versions set payload=payload where id=$1',[process.version.id])).rejects.toMatchObject({code:'42501'});
  const p={...m78ProcessProof(final.proof),priorVersions:final.process.versions.map(v=>({...v,review:null}))},activity={...process.version.activity,manualConfirmation:false},request={...activity,expectedVersionId:process.version.id,expectedVersionSha256:process.version.versionSha256,expectedDependencySha256:buildM78Dependencies(p,'process_screen',m78Hash).dependencySha256,correctionReason:'Withdraw fictional manual evidence confirmation; incomplete draft must retain blockers.',idempotencyKey:crypto.randomUUID()},forged={...process.version,id:crypto.randomUUID(),version:3,previousVersionId:process.version.id,previousVersionSha256:process.version.versionSha256,createdAt:new Date().toISOString(),activity,dependencies:buildM78Dependencies(p,'process_screen',m78Hash),contributorIds:m78Contributors(p,process.version,f.users.owner,'process_screen'),findings:[],review:null,inputSha256:m78Hash(activity),contentSha256:'',versionSha256:''};forged.contentSha256=m78Hash(m78ContentHashPayload(forged));forged.versionSha256=m78Hash(m78VersionHashPayload(forged));await expect((f.database as any).asTrustedUser(f.users.owner,(tx:any)=>tx.query('select neuvetra.save_scope1_version($1,$2,$3,$4::text::jsonb,$5::text::jsonb,$6::text::jsonb)',[f.companyId,process.version.streamId,'process_screen',JSON.stringify(request),JSON.stringify(forged),JSON.stringify(p)]))).rejects.toMatchObject({code:'22023'});
  const beforeTamper=await f.database.findScope1Version(f.users.owner,f.companyId,process.version.streamId,process.version.id,f.authorities,M78_REVIEWED_POLICY);expect(beforeTamper!.version.id).toBe(process.version.id);expect((await call('scope1-inventory','owner',{...request,idempotencyKey:crypto.randomUUID()})).status).toBe(422);expect((await call('process-screen/'+process.version.streamId+'/versions','owner',{...correctedInput,expectedVersionId:blocked.version.id,idempotencyKey:crypto.randomUUID()})).status).toBe(409);
  const oldRowsAfter=await m78ImmutableRowHashes(f.operator);for(const [table,rows]of Object.entries(oldRows)){const remaining=[...oldRowsAfter[table]!];for(const sha of rows){expect(remaining).toContain(sha);remaining.splice(remaining.indexOf(sha),1)}}
  const processActivity=process.version.activity as M78ProcessActivity,clarified=await post('process-screen/'+process.version.streamId+'/versions',{...processActivity,declaration:{...processActivity.declaration!,discoveryBasis:processActivity.declaration!.discoveryBasis+' Fictional clarification preserves every controlled location and supported source.'},expectedVersionId:process.version.id,expectedVersionSha256:process.version.versionSha256,expectedDependencySha256:buildM78Dependencies(final.proof,'process_screen',m78Hash).dependencySha256,correctionReason:'Clarify retained fictional discovery basis without changing any source, gas or location fact.',idempotencyKey:crypto.randomUUID()})as M78VersionEnvelope;await decodeScope1Version(clarified,f.companyId,process.version);
  const processPending=await post('process-screen/'+process.version.streamId+'/reports',reportInput(clarified));await decodeScope1Report(processPending,f.companyId);
  await post('process-screen/'+process.version.streamId+'/reviews',{versionId:clarified.version.id,expectedVersionSha256:clarified.version.versionSha256,expectedDependencySha256:clarified.version.dependencies.dependencySha256,decision:'accepted_bounded_process_screen',note:'Separate review verifies unchanged complete source/gas/location facts and discovery clarification.',acknowledgedLimitations:[...M78_LIMITATIONS],idempotencyKey:crypto.randomUUID()},'reviewer');
  final=await get();const rebound=await post('scope1-inventory/'+inventory.version.streamId+'/versions',{...inventory.version.activity,expectedVersionId:inventory.version.id,expectedVersionSha256:inventory.version.versionSha256,expectedDependencySha256:buildM78Dependencies(final.proof,'inventory',m78Hash).dependencySha256,correctionReason:'Rebind gross inventory to the separately reviewed process clarification.',idempotencyKey:crypto.randomUUID()})as M78VersionEnvelope;await decodeScope1Version(rebound,f.companyId,inventory.version);expect(rebound.version.dependencies.processVersionPin?.id).toBe(clarified.version.id);expect(rebound.version.reconciliation?.totals).toEqual(inventory.version.reconciliation?.totals);
  await post('scope1-inventory/'+inventory.version.streamId+'/reviews',{versionId:rebound.version.id,expectedVersionSha256:rebound.version.versionSha256,expectedDependencySha256:rebound.version.dependencies.dependencySha256,decision:'accepted_bounded_inventory',note:'Separate gross inventory successor review retains all original totals and exact source proof.',acknowledgedLimitations:[...M78_LIMITATIONS],idempotencyKey:crypto.randomUUID()},'reviewer');
  const reboundReviewed=await f.database.findScope1Version(f.users.owner,f.companyId,inventory.version.streamId,rebound.version.id,f.authorities,M78_REVIEWED_POLICY),correctedReport=await post('scope1-inventory/'+inventory.version.streamId+'/reports',reportInput(reboundReviewed!));await decodeScope1Report(correctedReport,f.companyId);
  expect(await(await call('scope1-inventory/'+inventory.version.streamId+'/reports/'+pending.id)).json()).toEqual(pending);expect(await(await call('process-screen/'+process.version.streamId+'/reports/'+processPending.id)).json()).toEqual(processPending);final=await get();expect(final.process.versions).toHaveLength(3);expect(final.inventory.versions).toHaveLength(2);expect(new TextEncoder().encode(m78CanonicalJson(final)).length).toBeGreaterThan(6000000);expect(new TextEncoder().encode(m78CanonicalJson(final)).length).toBeLessThanOrEqual(M78_MAX_RESPONSE_BYTES);
  await Bun.write('.superpowers/'+name+'-result.json',JSON.stringify({status:'author_native_m78_lifecycle_pass',database:name,companyId:f.companyId,migrationSha256:f.migrationSha256,applicationPostRequests:posts,users:f.users,oldImmutableTables:Object.keys(oldRows),oldImmutableRows:Object.values(oldRows).reduce((n,r)=>n+r.length,0),functionMetadata:f.functionMetadata,realAuthenticatedRoutes:true,browserDecoders:true,syntheticAuth:true,normalProcessCorrectionInventorySuccessorReviewedReport:true,registerBytes:new TextEncoder().encode(m78CanonicalJson(final)).length,independentReview:'pending',final},null,2));
 }catch(e){await Bun.write('.superpowers/'+name+'-failed.json',JSON.stringify({status:'author_native_m78_failed',name,migrationSha256:f.migrationSha256,message:(e as Error).message,applicationPostRequests:posts,independentReview:'pending'},null,2));throw e}finally{await f.runtime.close();await f.operator.close()}
},240000)
