import {m71Uuid} from '../../../../packages/neuvetra-database/src/m71-validation'
import {M78ValidationError,parseM78Json,validateM78ProcessSave,validateM78InventorySave,validateM78Review,validateM78Report,m78CanonicalJson} from '../../../../packages/neuvetra-database/src/m78-validation'
import type {M78Authorities,M78Family,M78Policy,M78Register,M78VersionEnvelope,M78Report,M78ProcessSaveInput,M78InventorySaveInput,M78ReviewInput,M78Review,M78ReportInput} from '../../../../packages/neuvetra-database/src/m78-contract'
import {extractBearerToken,type AuthenticatedUser} from '../lib/auth'
export interface M78RouteDatabase {
 hasStagingAccess?:(userId:string)=>Promise<boolean>
 canManageWorkspace:(userId:string,companyId:string)=>Promise<boolean>
 findScope1:(userId:string,companyId:string,a:M78Authorities,policy:M78Policy|null)=>Promise<M78Register|null>
 findScope1Version:(userId:string,companyId:string,streamId:string,versionId:string,a:M78Authorities,policy:M78Policy|null)=>Promise<M78VersionEnvelope|null>
 findScope1Report:(userId:string,companyId:string,streamId:string,reportId:string,a:M78Authorities,policy:M78Policy|null)=>Promise<M78Report|null>
 saveProcessScreen:(userId:string,companyId:string,streamId:string|null,input:M78ProcessSaveInput,a:M78Authorities,policy:M78Policy|null)=>Promise<M78VersionEnvelope>
 saveScope1Inventory:(userId:string,companyId:string,streamId:string|null,input:M78InventorySaveInput,a:M78Authorities,policy:M78Policy|null)=>Promise<M78VersionEnvelope>
 reviewScope1Version:(userId:string,companyId:string,streamId:string,family:M78Family,input:M78ReviewInput,a:M78Authorities,policy:M78Policy|null)=>Promise<M78Review>
 createScope1Report:(userId:string,companyId:string,streamId:string,family:M78Family,input:M78ReportInput,a:M78Authorities,policy:M78Policy|null)=>Promise<M78Report>
}
export function createM78Routes(deps:{database:M78RouteDatabase;validateUser:(token:string)=>Promise<AuthenticatedUser|null>;origin:string;authorities:M78Authorities;policy?:M78Policy|null}){return async(request:Request):Promise<Response>=>{const respond=(status:number,body:unknown)=>Response.json(body,{status,headers:{'cache-control':'no-store'}}),match=/^\/workspace\/([^/]+)\/(process-screen|scope1-inventory)(?:\/([^/]+)\/(versions|reviews|reports|statements)(?:\/([^/]+)(?:\/(inventory-export|download|snapshot|proof))?)?)?$/.exec(new URL(request.url).pathname);if(!match||!m71Uuid(match[1])||match[3]&&!m71Uuid(match[3])||match[5]&&!m71Uuid(match[5]))return respond(404,{error:'Scope 1 record not found.'});const [,company,path,stream,action,id,operation]=match,family:M78Family=path==='process-screen'?'process_screen':'inventory',origin=request.headers.get('origin'),policy=deps.policy??null;if(request.method!=='GET'&&origin!==deps.origin||origin&&origin!==deps.origin)return respond(403,{error:'Forbidden.'});const token=extractBearerToken(request.headers);if(!token)return respond(401,{error:'Authentication required.'});const actor=await deps.validateUser(token);if(!actor)return respond(401,{error:'Authentication required.'});try{if(deps.database.hasStagingAccess&&!await deps.database.hasStagingAccess(actor.id))return respond(403,{error:'Forbidden.'});
 if(request.method!=='GET'&&request.method!=='POST')return respond(405,{error:'Method not allowed.'});if(request.method==='POST'&&!await deps.database.canManageWorkspace(actor.id,company!))return respond(403,{error:'Forbidden.'});const register=request.method==='GET'?await deps.database.findScope1(actor.id,company!,deps.authorities,policy):null;if(request.method==='GET'&&!register)return respond(404,{error:'Scope 1 record not found.'});const selected=register?(family==='process_screen'?register.process:register.inventory):null;if(request.method==='GET'&&stream&&selected?.streamId!==stream)return respond(404,{error:'Scope 1 record not found.'});const headers={'cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer'},download=(body:string,type:string,filename:string,extra:Record<string,string>={})=>new Response(body,{headers:{...headers,'content-type':type+'; charset=utf-8','content-disposition':`attachment; filename="${filename}"`,...extra}});
 if(request.method==='GET'){if(!action)return respond(200,register);if(action==='versions'&&stream&&id){const envelope=await deps.database.findScope1Version(actor.id,company!,stream,id,deps.authorities,policy);if(!envelope||envelope.version.family!==family)return respond(404,{error:'Scope 1 version not found.'});if(!operation)return respond(200,envelope);if(operation==='inventory-export')return download(m78CanonicalJson({...envelope.version,review:null}),'application/json','synthetic-scope1-version.json');if(operation==='proof')return respond(200,envelope.proof)}if(action==='statements'&&id&&operation==='download'){const s=selected!.versions.flatMap(v=>v.statements).find(s=>s.id===id);if(s)return download(s.text,'text/plain','synthetic-scope1-evidence.txt')}if(action==='reports'&&stream&&id){const report=await deps.database.findScope1Report(actor.id,company!,stream,id,deps.authorities,policy);if(!report||report.family!==family)return respond(404,{error:'Scope 1 report not found.'});if(!operation)return respond(200,report);if(operation==='snapshot')return download(report.snapshotJson,'application/json','synthetic-scope1-report-snapshot.json');if(operation==='proof')return respond(200,(parseM78Json(report.snapshotJson)as any).proof);if(operation==='download')return download(report.html,'text/html','synthetic-scope1-report.html',{'content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; sandbox allow-modals"})}return respond(404,{error:'Scope 1 record not found.'})}
 if(id||operation)return respond(405,{error:'Method not allowed.'});const body=parseM78Json(await request.text(),200000);if(action==='reviews'&&stream)return respond(201,await deps.database.reviewScope1Version(actor.id,company!,stream,family,validateM78Review(body),deps.authorities,policy));if(action==='reports'&&stream)return respond(201,await deps.database.createScope1Report(actor.id,company!,stream,family,validateM78Report(body),deps.authorities,policy));if(action&&action!=='versions')return respond(404,{error:'Scope 1 record not found.'});const input=family==='process_screen'?validateM78ProcessSave(body):validateM78InventorySave(body);if(Boolean(stream)!==Boolean(input.expectedVersionId))return respond(422,{error:'Exact correction binding required.'});return respond(201,family==='process_screen'?await deps.database.saveProcessScreen(actor.id,company!,stream??null,input as M78ProcessSaveInput,deps.authorities,policy):await deps.database.saveScope1Inventory(actor.id,company!,stream??null,input as M78InventorySaveInput,deps.authorities,policy));
 }catch(e){if(e instanceof M78ValidationError)return respond(422,{error:e.message});const code=(e as any)?.code;if(code==='M78_STREAM_NOT_FOUND')return respond(404,{error:'Scope 1 record not found.'});if(code==='42501')return respond(403,{error:'Forbidden.'});if(code==='23505')return respond(409,{error:'Scope 1 source, coverage, dependency or request changed. Refresh current records.'});if(['54000','54001'].includes(code))return respond(422,{error:'Scope 1 history capacity reached; retained records remain readable.',code:'history_limit'});if(['22023','22P02','22007','22008','22003'].includes(code))return respond(422,{error:'Invalid or unsupported Scope 1 input.'});return respond(503,{error:'Scope 1 records could not be verified.'})}}}
