import {describe,expect,test} from 'bun:test'
import {createM78Routes,type M78RouteDatabase} from './m78-routes'
import {createM78RoutesBaseline} from './m78-get-route-baseline-fixture'
import {m78CanonicalJson} from '../../../../packages/neuvetra-database/src/m78-validation'
import {m78FixtureAuthorities} from '../../../../tools/staging/m78-backend-fixture'
import {M78_REVIEWED_POLICY} from '../../../../packages/neuvetra-database/src/m78-policy'

const company='10000000-0000-4000-8000-000000000001',otherCompany='10000000-0000-4000-8000-000000000002',actor='10000000-0000-4000-8000-000000000003',origin='http://localhost:47821'
const ids={process:{stream:'20000000-0000-4000-8000-000000000001',version:'20000000-0000-4000-8000-000000000002',report:'20000000-0000-4000-8000-000000000003'},inventory:{stream:'30000000-0000-4000-8000-000000000001',version:'30000000-0000-4000-8000-000000000002',report:'30000000-0000-4000-8000-000000000003'}} as const
const statement={id:'40000000-0000-4000-8000-000000000001',text:'exact retained statement'}
const proof={proof:'exact'}
function records(family:'process_screen'|'inventory'){
 const key=family==='process_screen'?'process':'inventory',id=ids[key],version:any={id:id.version,companyId:company,streamId:id.stream,family,review:{id:'review'},statements:[statement],activity:{},versionSha256:'a'.repeat(64)},envelope:any={version,proof},snapshotJson=JSON.stringify({proof}),report:any={id:id.report,companyId:company,streamId:id.stream,family,versionId:id.version,snapshotJson,html:'<p>exact retained report</p>'};return {key,id,version,envelope,report}
}
function register(){const p=records('process_screen'),i=records('inventory');return {process:{streamId:p.id.stream,versions:[p.version],reports:[p.report]},inventory:{streamId:i.id.stream,versions:[i.version],reports:[i.report]}} as any}
function fixture(overrides:Partial<M78RouteDatabase>={}){const calls={root:0,version:0,report:0,manage:0,writes:0},all=register(),db:M78RouteDatabase={hasStagingAccess:async()=>true,canManageWorkspace:async()=>{calls.manage++;return true},findScope1:async()=>{calls.root++;return all},findScope1Version:async(_u,_c,stream,id)=>{calls.version++;for(const family of ['process_screen','inventory'] as const){const row=records(family);if(row.id.stream===stream&&row.id.version===id)return row.envelope}return null},findScope1Report:async(_u,_c,stream,id)=>{calls.report++;for(const family of ['process_screen','inventory'] as const){const row=records(family);if(row.id.stream===stream&&row.id.report===id)return row.report}return null},saveProcessScreen:async()=>{calls.writes++;return records('process_screen').envelope},saveScope1Inventory:async()=>{calls.writes++;return records('inventory').envelope},reviewScope1Version:async()=>{calls.writes++;return {} as any},createScope1Report:async()=>{calls.writes++;return records('inventory').report},...overrides};return {calls,db}}
function router(db:M78RouteDatabase,staging=true){return createM78Routes({database:{...db,hasStagingAccess:async()=>staging},origin,authorities:m78FixtureAuthorities(),policy:M78_REVIEWED_POLICY,validateUser:async token=>token==='valid'?{id:actor,email:null,phone:null,fullName:null}:null})}
const call=(route:ReturnType<typeof createM78Routes>,path:string,init:RequestInit={})=>route(new Request(`${origin}/workspace/${company}/${path}`,{...init,headers:{authorization:'Bearer valid',origin,...init.headers}}))
const responseShape=async(response:Response)=>{const pairs:[string,string][]=[];response.headers.forEach((value,key)=>pairs.push([key,value]));return {status:response.status,headers:Object.fromEntries(pairs.sort()),body:await response.text()}}

describe('M78 optimized specific GET dispatch',()=>{
 test('portable frozen baseline fixture proves exact successful response equivalence',async()=>{for(const family of ['process_screen','inventory'] as const){const row=records(family),prefix=row.key==='process'?'process-screen':'scope1-inventory',paths=[`${prefix}/${row.id.stream}/versions/${row.id.version}`,`${prefix}/${row.id.stream}/versions/${row.id.version}/inventory-export`,`${prefix}/${row.id.stream}/versions/${row.id.version}/proof`,`${prefix}/${row.id.stream}/reports/${row.id.report}`,`${prefix}/${row.id.stream}/reports/${row.id.report}/download`,`${prefix}/${row.id.stream}/reports/${row.id.report}/snapshot`,`${prefix}/${row.id.stream}/reports/${row.id.report}/proof`];for(const path of paths){const oldFixture=fixture(),newFixture=fixture(),oldRoute=createM78RoutesBaseline({database:oldFixture.db,origin,authorities:m78FixtureAuthorities(),policy:M78_REVIEWED_POLICY,validateUser:async()=>({id:actor,email:null,phone:null,fullName:null})}),newRoute=router(newFixture.db);expect(await responseShape(await call(newRoute,path))).toEqual(await responseShape(await call(oldRoute,path)));expect(newFixture.calls.root).toBe(0);expect(oldFixture.calls.root).toBe(1)}}})
 test('both families return exact version/report bytes and never load the root register',async()=>{
  for(const family of ['process_screen','inventory'] as const){const row=records(family),path=row.key==='process'?'process-screen':'scope1-inventory',f=fixture(),route=router(f.db)
   const version=await call(route,`${path}/${row.id.stream}/versions/${row.id.version}`);expect(version.status).toBe(200);expect(await version.json()).toEqual(row.envelope)
   const exported=await call(route,`${path}/${row.id.stream}/versions/${row.id.version}/inventory-export`);expect(exported.status).toBe(200);expect(await exported.text()).toBe(m78CanonicalJson({...row.version,review:null}));expect(exported.headers.get('content-disposition')).toBe('attachment; filename="synthetic-scope1-version.json"')
   const versionProof=await call(route,`${path}/${row.id.stream}/versions/${row.id.version}/proof`);expect(versionProof.status).toBe(200);expect(await versionProof.json()).toEqual(proof)
   const report=await call(route,`${path}/${row.id.stream}/reports/${row.id.report}`);expect(report.status).toBe(200);expect(await report.json()).toEqual(row.report)
   const html=await call(route,`${path}/${row.id.stream}/reports/${row.id.report}/download`);expect(html.status).toBe(200);expect(await html.text()).toBe(row.report.html);expect(html.headers.get('content-security-policy')).toContain("default-src 'none'")
   const snapshot=await call(route,`${path}/${row.id.stream}/reports/${row.id.report}/snapshot`);expect(snapshot.status).toBe(200);expect(await snapshot.text()).toBe(row.report.snapshotJson);expect(snapshot.headers.get('content-disposition')).toBe('attachment; filename="synthetic-scope1-report-snapshot.json"')
   const reportProof=await call(route,`${path}/${row.id.stream}/reports/${row.id.report}/proof`);expect(reportProof.status).toBe(200);expect(await reportProof.json()).toEqual(proof)
   expect(f.calls).toMatchObject({root:0,version:3,report:4,writes:0})
  }
 })
 test('root register and retained statement paths continue to use root state only',async()=>{const f=fixture(),route=router(f.db),root=await call(route,'scope1-inventory');expect(root.status).toBe(200);expect(await root.json()).toEqual(register());const download=await call(route,`process-screen/${ids.process.stream}/statements/${statement.id}/download`);expect(download.status).toBe(200);expect(await download.text()).toBe(statement.text);expect(f.calls).toMatchObject({root:2,version:0,report:0,writes:0})})
 test('null specific results use root only to preserve generic wrong-stream versus specific missing errors',async()=>{for(const kind of ['version','report'] as const){const suffix=kind==='version'?`versions/${ids.inventory.version}`:`reports/${ids.inventory.report}`,method=kind==='version'?'findScope1Version':'findScope1Report';for(const [rootValue,error] of [[null,'Scope 1 record not found.'],[register(),`Scope 1 ${kind} not found.`]] as const){const f=fixture({[method]:async()=>null,findScope1:async()=>{f.calls.root++;return rootValue}} as any),response=await call(router(f.db),`scope1-inventory/${ids.inventory.stream}/${suffix}`);expect(response.status).toBe(404);expect(await response.json()).toEqual({error});expect(f.calls.root).toBe(1)}}const f=fixture({findScope1Report:async()=>null}),response=await call(router(f.db),`scope1-inventory/${ids.process.stream}/reports/${ids.inventory.report}`);expect(response.status).toBe(404);expect(await response.json()).toEqual({error:'Scope 1 record not found.'});expect(f.calls.root).toBe(1)})
 test('mismatched requested id, company, stream or family from a specific getter is rechecked against root state',async()=>{for(const mutate of [(x:any)=>x.version.id=ids.process.version,(x:any)=>x.version.companyId=otherCompany,(x:any)=>x.version.streamId=ids.process.stream,(x:any)=>x.version.family='process_screen']){const value=structuredClone(records('inventory').envelope);mutate(value);const f=fixture({findScope1Version:async()=>{f.calls.version++;return value}}),r=await call(router(f.db),`scope1-inventory/${ids.inventory.stream}/versions/${ids.inventory.version}`);expect(r.status).toBe(404);expect(await r.json()).toEqual({error:'Scope 1 version not found.'});expect(f.calls.root).toBe(1)}for(const mutate of [(x:any)=>x.id=ids.process.report,(x:any)=>x.companyId=otherCompany,(x:any)=>x.streamId=ids.process.stream,(x:any)=>x.family='process_screen']){const value=structuredClone(records('inventory').report);mutate(value);const f=fixture({findScope1Report:async()=>{f.calls.report++;return value}}),r=await call(router(f.db),`scope1-inventory/${ids.inventory.stream}/reports/${ids.inventory.report}`);expect(r.status).toBe(404);expect(await r.json()).toEqual({error:'Scope 1 report not found.'});expect(f.calls.root).toBe(1)}})
 test('actual cross-family identities retain the generic wrong-stream error',async()=>{const f=fixture(),route=router(f.db);for(const [kind,id] of [['versions',ids.process.version],['reports',ids.process.report]] as const){const r=await call(route,`scope1-inventory/${ids.process.stream}/${kind}/${id}`);expect(r.status).toBe(404);expect(await r.json()).toEqual({error:'Scope 1 record not found.'})}expect(f.calls.root).toBe(2)})
 test('fallback root permission and corruption failures remain inside route error mapping',async()=>{for(const [error,status] of [[Object.assign(Error('denied'),{code:'42501'}),403],[Error('corrupt'),503]] as const){const f=fixture({findScope1Report:async()=>null,findScope1:async()=>{throw error}}),r=await call(router(f.db),`scope1-inventory/${ids.inventory.stream}/reports/${ids.inventory.report}`);expect(r.status).toBe(status)}})
 test('authentication, staging, permissions, corruption and unsupported requests retain refusal ordering',async()=>{const f=fixture(),route=router(f.db);expect((await route(new Request(`${origin}/workspace/${company}/scope1-inventory/${ids.inventory.stream}/reports/${ids.inventory.report}`))).status).toBe(401);expect((await call(router(f.db,false),`scope1-inventory/${ids.inventory.stream}/reports/${ids.inventory.report}`)).status).toBe(403);const denied=fixture({findScope1Report:async()=>{throw Object.assign(Error('denied'),{code:'42501'})}});expect((await call(router(denied.db),`scope1-inventory/${ids.inventory.stream}/reports/${ids.inventory.report}`)).status).toBe(403);const corrupt=fixture({findScope1Report:async()=>{throw Error('corrupt')}});expect((await call(router(corrupt.db),`scope1-inventory/${ids.inventory.stream}/reports/${ids.inventory.report}`)).status).toBe(503);expect((await call(route,'scope1-inventory',{method:'PUT'})).status).toBe(405);expect((await call(route,'scope1-inventory/not-a-uuid/reports/not-a-uuid')).status).toBe(404);expect(f.calls.writes).toBe(0)})
 test('POST manager gate and exact report writer behavior are unchanged',async()=>{const input={versionId:ids.inventory.version,expectedVersionSha256:'a'.repeat(64),expectedDecisionId:null,expectedDecisionSha256:null,expectedReconciliationSha256:null,idempotencyKey:'50000000-0000-4000-8000-000000000001'},denied=fixture({canManageWorkspace:async()=>false}),path=`scope1-inventory/${ids.inventory.stream}/reports`,blocked=await call(router(denied.db),path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});expect(blocked.status).toBe(403);expect(denied.calls.writes).toBe(0);const f=fixture(),saved=await call(router(f.db),path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});expect(saved.status).toBe(201);expect(await saved.json()).toEqual(records('inventory').report);expect(f.calls).toMatchObject({manage:1,writes:1,root:0,version:0,report:0})})
})
