import { describe, expect, test } from "bun:test"
import { M61_CHANGE_ROUTE_CODES, M61_LIMITATION_ACKNOWLEDGMENTS, draftReportDecisionSnapshotPayload, hashDraftReportDecisionSnapshot, validateDraftReportReviewInput } from "./m61"

describe("M61 bounded draft-report review contract",()=>{
  test("accepts only the exact fixed limitation acknowledgements",()=>{
    expect(()=>validateDraftReportReviewInput({decision:"accept_bounded_internal_draft",reasonCode:"exact_report_reviewed_for_bounded_internal_use",acknowledgedLimitations:[...M61_LIMITATION_ACKNOWLEDGMENTS],changeRouteCode:null,changeNote:null})).not.toThrow()
    for(const acknowledgedLimitations of [M61_LIMITATION_ACKNOWLEDGMENTS.slice(1),[...M61_LIMITATION_ACKNOWLEDGMENTS].reverse(),[...M61_LIMITATION_ACKNOWLEDGMENTS,"extra"]])expect(()=>validateDraftReportReviewInput({decision:"accept_bounded_internal_draft",reasonCode:"exact_report_reviewed_for_bounded_internal_use",acknowledgedLimitations:[...acknowledgedLimitations],changeRouteCode:null,changeNote:null})).toThrow("invalid")
  })

  test("requires exactly one bounded route and a safe trimmed 1-500 character note",()=>{
    for(const changeRouteCode of M61_CHANGE_ROUTE_CODES)expect(()=>validateDraftReportReviewInput({decision:"changes_requested",reasonCode:"report_revision_required",acknowledgedLimitations:[],changeRouteCode,changeNote:"Correct the identified report field."})).not.toThrow()
    for(const changeNote of [""," leading","trailing ","line\nbreak","tab\there",`${"x".repeat(501)}`])expect(()=>validateDraftReportReviewInput({decision:"changes_requested",reasonCode:"report_revision_required",acknowledgedLimitations:[],changeRouteCode:"report_presentation_revision_required",changeNote})).toThrow("invalid")
    expect(()=>validateDraftReportReviewInput({decision:"changes_requested",reasonCode:"report_revision_required",acknowledgedLimitations:[],changeRouteCode:null,changeNote:"Correct it."})).toThrow("invalid")
  })
  test("seals an explicitly ordered identity and lineage payload without a database timestamp",()=>{const input={companyId:"11111111-1111-4111-8111-111111111111",reportId:"22222222-2222-4222-8222-222222222222",profile:"neuvetra.synthetic.inventory-draft-report-review.v1" as const,decision:"accept_bounded_internal_draft" as const,outcome:"accepted_bounded_internal_draft" as const,reasonCode:"exact_report_reviewed_for_bounded_internal_use" as const,acknowledgedLimitations:[...M61_LIMITATION_ACKNOWLEDGMENTS],changeRouteCode:null,changeNote:null,reportSha256:"a".repeat(64),reportCreatedBy:"33333333-3333-4333-8333-333333333333",inventorySnapshotSha256:"b".repeat(64),sourceArchiveSha256:"c".repeat(64),sourceManifestSha256:"d".repeat(64),sourceLineageRootSha256:"e".repeat(64),releaseEligible:false as const,reviewerIdentity:"44444444-4444-4444-8444-444444444444"};const payload=draftReportDecisionSnapshotPayload(input);expect(payload.split("\n").map(line=>line.slice(0,line.indexOf("=")))).toEqual(["version","companyId","reportId","profile","decision","outcome","reasonCode","acknowledgedLimitations","changeRouteCode","changeNote","reportSha256","reportCreatedBy","inventorySnapshotSha256","sourceArchiveSha256","sourceManifestSha256","sourceLineageRootSha256","releaseEligible","reviewerIdentity"]);expect(payload).not.toContain("decidedAt");expect(hashDraftReportDecisionSnapshot(input)).toMatch(/^[0-9a-f]{64}$/);expect(hashDraftReportDecisionSnapshot({...input,reviewerIdentity:"55555555-5555-4555-8555-555555555555"})).not.toBe(hashDraftReportDecisionSnapshot(input))})
})
