/** Canonical LF template. Substitutions are escaped text, never HTML fragments. */
export const M65_TEMPLATE = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Synthetic electricity worksheet report — {{companyLabel}}</title>
<style>body{font:16px/1.55 system-ui,sans-serif;color:#182820;max-width:850px;margin:32px auto;padding:0 22px}h1{font-size:1.85rem;line-height:1.2}h2{font-size:1.2rem;margin-top:1.8rem}p,li,dd{overflow-wrap:anywhere}dl{display:grid;grid-template-columns:minmax(110px,1fr) minmax(0,3fr);gap:6px 18px}dt{font-weight:650}dd{margin:0;min-width:0}.notice{border:2px solid #927130;background:#fff8e8;padding:14px}.subtotal{font-size:2rem;font-weight:750;margin-bottom:0}.mono{font:12px/1.55 ui-monospace,monospace;overflow-wrap:anywhere;white-space:pre-wrap}.review-note{white-space:pre-wrap;border-left:3px solid #a1aea5;padding-left:12px}.print-status{display:none}.muted{color:#405248}a{color:#16553b}@media(max-width:500px){body{padding:0 14px}dl{display:block}dd{margin:2px 0 12px}}@page{size:auto;margin:24mm 15mm 22mm;@top-center{content:"Draft · Synthetic · Incomplete · Unreleased · No assurance";font:700 8pt/1.2 system-ui,sans-serif;color:#182820;vertical-align:middle}@bottom-center{content:"Draft · Synthetic · Incomplete · Unreleased · No assurance · Page " counter(page);font:700 8pt/1.2 system-ui,sans-serif;color:#182820;vertical-align:middle}}@media print{body{font-size:10pt;margin:0;max-width:none;padding:0}h1{font-size:21pt}h2{break-after:avoid}p,li,dd{orphans:3;widows:3}.notice{background:white}.subtotal{font-size:24pt}.mono{font-size:8pt}dl{display:block}dt{margin-top:7px}dd{margin-left:0}a{color:inherit;text-decoration:none}}</style></head><body>
<header class="print-status print-header">Draft · Synthetic · Incomplete · Unreleased · No assurance</header><footer class="print-status print-footer">Draft · Synthetic · Incomplete · Unreleased · No assurance · January 2023 CAMX worksheet only</footer>
<main><p>Neuvetra · Saved worksheet snapshot</p><h1>Synthetic electricity worksheet report</h1><div class="notice"><strong>Draft · Synthetic · Incomplete · Unreleased · No assurance</strong><br>Fictional manual data for private testing. No bill evidence, filing approval or professional assurance.</div>
<h2>January location-based subtotal</h2><p class="subtotal">{{display}} kg CO2e</p><p>Exact subtotal before display rounding: <strong>{{unrounded}} kg CO2e</strong></p><dl><dt>Fictional company</dt><dd>{{companyLabel}}</dd><dt>Fictional facility</dt><dd>{{facilityLabel}}</dd><dt>Period</dt><dd>January 1–31, 2023</dd><dt>Declared geography</dt><dd>United States · California · CAMX</dd><dt>Boundary</dt><dd>Operational control · Location-based Scope 2</dd><dt>Activity</dt><dd>Grid-delivered purchased electricity consumed by the reporting company</dd><dt>Manual quantity</dt><dd>{{quantityKwh}} kWh</dd><dt>Converted quantity</dt><dd>{{quantityMwh}} MWh · 1 MWh = 1,000 kWh</dd><dt>Evidence</dt><dd>Synthetic manual entry — no bill evidence</dd></dl>
<p>Display rounded once to four decimal places, half to even; no intermediate rounding. Decimal precision does not establish measurement certainty.</p>
<h2>Worksheet review captured for this report</h2><p><strong>{{reviewSummary}}</strong></p><p>This is a snapshot of a worksheet decision, not approval of this report presentation or assurance.</p><dl><dt>Reviewed source</dt><dd>Worksheet version {{sourceVersion}} · {{sourceVersionId}}</dd><dt>Result fingerprint</dt><dd class="mono">{{resultSha256}}</dd><dt>Manager reference</dt><dd class="mono">{{reviewerId}}</dd><dt>Decision time (UTC)</dt><dd>{{reviewedAt}}</dd><dt>Decision ID</dt><dd class="mono">{{reviewId}}</dd><dt>Decision fingerprint</dt><dd class="mono">{{reviewSha256}}</dd><dt>Acknowledgments</dt><dd>{{reviewAcknowledgments}}</dd></dl><p class="review-note">{{reviewNote}}</p><p class="muted">Review state was captured at {{createdAt}}. Later worksheet decisions and corrections do not change this report.</p>
<h2>Source and correction history</h2><dl><dt>Worksheet version</dt><dd>{{sourceVersion}} · {{sourceVersionId}}</dd><dt>Saved (UTC)</dt><dd>{{sourceCreatedAt}}</dd><dt>Source creator</dt><dd class="mono">{{sourceCreatedBy}}</dd><dt>Predecessor</dt><dd class="mono">{{previousVersionId}}</dd><dt>Correction reason</dt><dd>{{correctionReason}}</dd><dt>Tenant binding</dt><dd class="mono">{{companyId}}</dd><dt>Input fingerprint</dt><dd class="mono">{{inputSha256}}</dd><dt>Result fingerprint</dt><dd class="mono">{{resultSha256}}</dd></dl>
<h2>Pinned method and source</h2><p>An annual 2023 regional average factor is applied to January consumption. This is not a January-specific factor or a complete annual inventory.</p><dl><dt>Method</dt><dd>{{methodId}} · {{methodVersion}}</dd><dt>Candidate factor</dt><dd>{{factorId}} · {{factorVersion}}</dd><dt>Rate</dt><dd>{{factorValue}} kg CO2e/MWh</dd><dt>Workbook locator</dt><dd>EPA eGRID2023 metric workbook, revision 2 · SRL23!AI6 · annual total-output CO2e rate; A6=2023, B6=CAMX, C6=WECC California</dd><dt>Workbook fingerprint</dt><dd class="mono">{{sourceSha256}}</dd><dt>Candidate fingerprint</dt><dd class="mono">{{factorCandidateSha256}}</dd><dt>GWP policy</dt><dd>AR5 · 100 years · without climate-carbon feedbacks; CO2 1, CH4 28, N2O 265</dd><dt>GWP fingerprint</dt><dd class="mono">{{gwpPolicySha256}}</dd><dt>Reviewed engine fingerprint</dt><dd class="mono">{{reviewedEngineSha256}}</dd></dl><p><a href="https://www.epa.gov/system/files/documents/2025-06/egrid2023_data_metric_rev2.xlsx" rel="noreferrer">EPA source workbook</a> · <a href="https://www.epa.gov/system/files/documents/2025-01/egrid2023_technical_guide.pdf" rel="noreferrer">EPA technical guide, page 12, section 3.1.1.2 / Table 3-1</a></p><p>The existing reviewed candidate decimal normalization is retained. No factor or method is released by this report.</p>
<h2>Incomplete coverage and limitations</h2><ul><li>All input is fictional manual data without bill evidence.</li><li>The overall inventory is incomplete. February–December and other facilities/sources are not assessed; missing coverage is not zero consumption.</li><li>This worksheet covers January 2023 CAMX only.</li><li>Market-based Scope 2 is not included.</li><li>The factor and method are unreleased development candidates.</li><li>Scope 1 and Scope 3 are not assessed.</li><li>No assurance, verification, certification or filing approval is provided. Release eligibility remains false.</li></ul>
<h2>Report identity</h2><dl><dt>Report ID</dt><dd class="mono">{{reportId}}</dd><dt>Captured (UTC)</dt><dd>{{createdAt}}</dd><dt>Report creator</dt><dd class="mono">{{createdBy}}</dd><dt>Report profile</dt><dd>{{profile}}</dd><dt>Template version</dt><dd>{{templateVersion}}</dd><dt>Template fingerprint</dt><dd class="mono">{{templateSha256}}</dd><dt>Snapshot identity fingerprint</dt><dd class="mono">{{identitySha256}}</dd></dl><p class="muted">The snapshot identity fingerprint binds the company, worksheet input/result, captured review and template. The authenticated application receipt records the SHA-256 of all UTF-8 HTML bytes; this document does not embed its own byte hash. Browser print/PDF layout and bytes may vary and are not covered by the HTML hash. This report identifies its saved source version and does not claim that it remains the latest worksheet.</p>
</main></body></html>
`

export const M65_TEMPLATE_SHA256 = "cb279f0ec15cd492815dca2c4424e6d8852c0503f179fa0179482a0f087aa929" as const
