/** Synthetic coverage register only. No released method, calculation or legal determination. */
export const M71_PROFILE = "synthetic-corporate-coverage-v1" as const
export const M71_MAX_VERSIONS=40
export const M71_MAX_SNAPSHOT_BYTES=50000
export const M71_MAX_RESPONSE_BYTES=4000000
export const M71_LIMITATIONS = ["synthetic_only", "corporate_inventory_incomplete", "methods_not_released", "requirements_not_determined", "no_emissions_calculated", "no_external_assurance"] as const
export const M71_DOMAINS = ["stationary_combustion", "mobile_combustion", "process", "fugitive", "electricity", "steam", "heat", "cooling", "location_based", "market_based", ...Array.from({length:15},(_,i)=>`scope3_${i+1}`)] as const
export const M71_CATEGORIES = ["Purchased goods and services", "Capital goods", "Fuel- and energy-related activities", "Upstream transportation and distribution", "Waste generated in operations", "Business travel", "Employee commuting", "Upstream leased assets", "Downstream transportation and distribution", "Processing of sold products", "Use of sold products", "End-of-life treatment of sold products", "Downstream leased assets", "Franchises", "Investments"] as const
export type M71Disposition = "unassessed" | "missing" | "included_activity" | "included_estimate" | "excluded" | "not_applicable"
export interface M71Interval { start:string; endExclusive:string }
export interface M71EvidenceRef { artifactId:string; expectedSha256:string; locator:string; purpose:string }
export interface M71Entity extends M71Interval { id:string; legalName:string; countryCode:string; regionCode:string|null; evidenceRefs:M71EvidenceRef[] }
export interface M71Relationship extends M71Interval { id:string; parentEntityId:string; childEntityId:string; ownershipPercent:string|null; controlFacts:string|null; evidenceRefs:M71EvidenceRef[] }
export interface M71Facility extends M71Interval { id:string; entityId:string; name:string; countryCode:string; regionCode:string|null; evidenceRefs:M71EvidenceRef[] }
export interface M71Source extends M71Interval { id:string; entityId:string; facilityId:string|null; name:string; domain:string; evidenceRefs:M71EvidenceRef[] }
export interface M71BoundaryDecision extends M71Interval { id:string; entityId:string; disposition:M71Disposition; reason:string|null; evidenceRefs:M71EvidenceRef[] }
export interface M71Estimate { methodVersionId:string; assumptions:string; inputEvidenceRefs:M71EvidenceRef[]; uncertainty:string }
export interface M71CoverageItem extends M71Interval { id:string; domain:string; entityId:string|null; sourceId:string|null; disposition:M71Disposition; activityDataState:"not_assessed"|"missing"|"partial"|"entered"|"estimate_proposed"|"explicit_zero"; evidenceState:"not_assessed"|"missing"|"partial"|"linked"|"conflicting"; methodReadiness:"not_assessed"|"unsupported"|"candidate"; reason:string|null; evidenceRefs:M71EvidenceRef[]; estimateBasis:M71Estimate|null; quantity:string|null; unit:string|null }
export interface M71Requirement { id:string; character:"statute"|"regulation"|"standard"|"agency_guidance"|"proposal"|"enforcement_statement"|"court_order"; sourceLocator:string|null; sourceEdition:string|null; lastCheckedOn:string|null; applicability:"unknown"|"conflicting"; missingFacts:string[]; reason:string }
export interface M71Snapshot { profile:typeof M71_PROFILE; companyLabel:string; period:M71Interval; consolidationApproach:"operational_control"|"financial_control"|"equity_share"; policyVersion:string; entities:M71Entity[]; relationships:M71Relationship[]; facilities:M71Facility[]; sources:M71Source[]; boundaryDecisions:M71BoundaryDecision[]; coverageItems:M71CoverageItem[]; requirements:M71Requirement[] }
export interface M71SaveInput { snapshot:M71Snapshot; expectedVersionId:string|null; expectedVersionSha256:string|null; correctionReason:string|null; idempotencyKey:string }
export interface M71ReviewInput { versionId:string; expectedVersionSha256:string; decision:"accepted_bounded_internal"|"changes_requested"; note:string; acknowledgedLimitations:string[]; idempotencyKey:string }
export interface M71Review { id:string; versionId:string; versionSha256:string; decision:M71ReviewInput["decision"]; note:string; acknowledgedLimitations:string[]; reviewerId:string; reviewedAt:string; decisionSha256:string }
export interface M71Finding { code:string; recordId:string|null; message:string }
export interface M71Version { id:string; inventoryId:string; companyId:string; version:number; previousVersionId:string|null; previousVersionSha256:string|null; createdBy:string; createdAt:string; contributorIds:string[]; correctionReason:string|null; snapshot:M71Snapshot; contentSha256:string; versionSha256:string; findings:M71Finding[]; synthetic:true; corporateCompleteness:"incomplete"; releaseEligible:false; assurance:"none"; emissionsTotals:null; review:M71Review|null }
export interface M71Register { profile:typeof M71_PROFILE; companyId:string; inventoryId:string|null; headVersionId:string|null; versions:M71Version[]; limitations:string[] }
export const m71Id=(n:number)=>`71000000-0000-4000-8000-${String(n).padStart(12,"0")}`
export const M71_PERIOD:M71Interval={start:"2025-01-01",endExclusive:"2026-01-01"}
// The original text and locators are pinned by the server, not supplied by requests.
export const M71_ARTIFACT = {id:m71Id(900),text:"SYNTHETIC Juniper 2025 corporate register. Entities: California parent and California distribution subsidiary. Wholly owned; operational control. No activity measurements or legal conclusions. Screening assertions are fictional and require review.",locator:"synthetic-register:entities-and-screening",period:M71_PERIOD} as const
export function createM71Seed():M71Snapshot {
 const entities:M71Entity[]=[{id:m71Id(1),legalName:"Synthetic Juniper California parent",countryCode:"US",regionCode:"CA",...M71_PERIOD,evidenceRefs:[]},{id:m71Id(2),legalName:"Synthetic Juniper California distribution",countryCode:"US",regionCode:"CA",...M71_PERIOD,evidenceRefs:[]}]
 const facilities=entities.map((e,i)=>({id:m71Id(20+i),entityId:e.id,name:["Synthetic California office","Synthetic California distribution center"][i]!,countryCode:e.countryCode,regionCode:e.regionCode,...M71_PERIOD,evidenceRefs:[]}))
 const sources=facilities.map((f,i)=>({id:m71Id(30+i),entityId:f.entityId,facilityId:f.id,name:"Purchased electricity",domain:"electricity",...M71_PERIOD,evidenceRefs:[]}))
 return {profile:M71_PROFILE,companyLabel:"Synthetic Juniper group",period:{...M71_PERIOD},consolidationApproach:"operational_control",policyVersion:"synthetic-boundary-policy-v1",entities,facilities,sources,relationships:entities.slice(1).map((e,i)=>({id:m71Id(10+i),parentEntityId:entities[0]!.id,childEntityId:e.id,...M71_PERIOD,ownershipPercent:"100",controlFacts:null,evidenceRefs:[]})),boundaryDecisions:entities.map((e,i)=>({id:m71Id(40+i),entityId:e.id,...M71_PERIOD,disposition:i===0?"included_activity":"missing",reason:null,evidenceRefs:[]})),coverageItems:[...M71_DOMAINS.map((domain,i)=>({id:m71Id(100+i),domain,entityId:null,sourceId:null,...M71_PERIOD,disposition:"unassessed" as const,activityDataState:"not_assessed" as const,evidenceState:"missing" as const,methodReadiness:"unsupported" as const,reason:null,evidenceRefs:[],estimateBasis:null,quantity:null,unit:null})),...sources.map((s,i)=>({id:m71Id(200+i),domain:s.domain,entityId:s.entityId,sourceId:s.id,...M71_PERIOD,disposition:"missing" as const,activityDataState:"missing" as const,evidenceState:"missing" as const,methodReadiness:"unsupported" as const,reason:null,evidenceRefs:[],estimateBasis:null,quantity:null,unit:null}))],requirements:[{id:m71Id(300),character:"statute",sourceLocator:null,sourceEdition:null,lastCheckedOn:null,applicability:"unknown",missingFacts:["qualified_source_review","revenue_basis","jurisdiction_and_business_facts"],reason:"Synthetic planning placeholder. No SB 253 applicability determination."}]}
}
