import { M71_ARTIFACT, M71_DOMAINS, M71_LIMITATIONS, M71_PERIOD, M71_PROFILE, createM71Seed, type M71Snapshot, type M71SaveInput, type M71ReviewInput, type M71EvidenceRef, type M71Finding, type M71Interval, type M71Version, type M71Review } from "./m71-contract"
export const M71_EVIDENCE_SHA256="4fe7dc12d8f253f8d3cb1fd7fba2eade05f3d605ad7cb95376cca9d957afe5c7"
export class M71ValidationError extends Error {}
const fail=(message="Invalid synthetic corporate coverage request."):never=>{throw new M71ValidationError(message)}
export const m71Uuid=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(v)
export const m71HashString=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{64}$/.test(v)
export function m71Keys(v:unknown,keys:string[]):asserts v is Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v)||Object.keys(v).sort().join("|")!==[...keys].sort().join("|"))fail()}
export function m71CanonicalJson(v:unknown):string {if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(m71CanonicalJson).join(",")}]`;return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${m71CanonicalJson((v as Record<string,unknown>)[k])}`).join(",")}}`}
export function m71VersionHashPayload(v:Omit<M71Version,"review">|M71Version){return {profile:M71_PROFILE,id:v.id,inventoryId:v.inventoryId,companyId:v.companyId,version:v.version,previousVersionId:v.previousVersionId,previousVersionSha256:v.previousVersionSha256,createdBy:v.createdBy,createdAt:v.createdAt,contributorIds:v.contributorIds,correctionReason:v.correctionReason,contentSha256:v.contentSha256}}
export function m71ReviewHashPayload(companyId:string,r:M71Review){const {decisionSha256:_hash,...body}=r;return {profile:M71_PROFILE,companyId,...body}}
export function m71CompareText(a:string,b:string):number{const left=Array.from(a),right=Array.from(b);for(let i=0;i<Math.min(left.length,right.length);i++){const delta=left[i]!.codePointAt(0)!-right[i]!.codePointAt(0)!;if(delta)return delta}return left.length-right.length}
function label(v:unknown,max=500):string {if(typeof v!=="string"||/[\u0000-\u001f\u007f-\u009f\ud800-\udfff]/u.test(v))fail();const s=(v as string).trim().normalize("NFC");if(!s.length||Array.from(s).length>max)fail();return s}
function nullableLabel(v:unknown):string|null{return v===null?null:label(v)}
function enumeration(v:unknown,values:readonly string[]){if(typeof v!=="string"||!values.includes(v))fail();return v as string}
function date(v:unknown):string{if(typeof v!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)fail();return v as string}
function interval(v:M71Interval){date(v.start);date(v.endExclusive);if(v.start>=v.endExclusive||v.start<M71_PERIOD.start||v.endExclusive>M71_PERIOD.endExclusive)fail("Intervals must be valid inclusive-start/exclusive-end dates within 2025.")}
function decimal(v:unknown,max=18):string{if(typeof v!=="string"||!new RegExp(`^(0|[1-9][0-9]{0,${max-1}})(\\.[0-9]{1,6})?$`).test(v))fail();return (v as string).includes(".")?(v as string).replace(/0+$/,"").replace(/\.$/,""):v as string}
function refs(v:unknown):M71EvidenceRef[]{if(!Array.isArray(v)||v.length>8)fail();return (v as unknown[]).map(r=>{m71Keys(r,["artifactId","expectedSha256","locator","purpose"]);if(r.artifactId!==M71_ARTIFACT.id||r.expectedSha256!==M71_EVIDENCE_SHA256||r.locator!==M71_ARTIFACT.locator)fail("Only the pinned synthetic 2025 evidence and locator are supported.");return {...r,purpose:label(r.purpose)} as unknown as M71EvidenceRef}).sort((a,b)=>m71CompareText(a.purpose,b.purpose)).map((r,i,a)=>{if(i&&a[i-1]!.purpose===r.purpose)fail();return r})}
const dispositions=["unassessed","missing","included_activity","included_estimate","excluded","not_applicable"]
/** All user data is validated before writing and again on native database readback. */
export function validateM71Snapshot(value:unknown,previous?:M71Snapshot):M71Snapshot{
 m71Keys(value,["profile","companyLabel","period","consolidationApproach","policyVersion","entities","relationships","facilities","sources","boundaryDecisions","coverageItems","requirements"])
 const s=structuredClone(value) as unknown as M71Snapshot
 if(s.profile!==M71_PROFILE)fail();s.companyLabel=label(s.companyLabel,160);s.policyVersion=label(s.policyVersion,100)
 m71Keys(s.period,["start","endExclusive"]);if(m71CanonicalJson(s.period)!==m71CanonicalJson(M71_PERIOD))fail("Only calendar 2025 is supported.")
 enumeration(s.consolidationApproach,["operational_control","financial_control","equity_share"])
 const collections=["entities","relationships","facilities","sources","boundaryDecisions","coverageItems","requirements"] as const
 const globalIds=new Set<string>()
 for(const key of collections){const a=s[key];if(!Array.isArray(a)||a.length>150)fail();for(const row of a){if(!m71Uuid(row?.id)||globalIds.has(row.id))fail("Stable record IDs must be unique.");globalIds.add(row.id)}a.sort((a,b)=>a.id<b.id?-1:1)}
 const seed=createM71Seed();for(const key of ["entities","relationships","facilities","sources"] as const)for(const row of seed[key])if(!s[key].some(r=>r.id===row.id))fail("The expected synthetic corporate universe cannot be omitted.")
 if(previous)for(const key of collections)for(const row of previous[key]){const next=s[key].find(r=>r.id===row.id);if(!next)fail("Prior records must remain visible; use an explained disposition instead of deletion.");for(const field of ["entityId","sourceId","facilityId","parentEntityId","childEntityId","domain"]){if(field in row&&(row as unknown as Record<string,unknown>)[field]!==(next as unknown as Record<string,unknown>)[field])fail("Stable relationship/source identities cannot be repurposed; add a discovered record.")}}
 const entity=(id:string)=>s.entities.find(e=>e.id===id)??fail("Entity reference does not resolve in this snapshot.")
 const within=(a:M71Interval,b:M71Interval)=>{interval(a);if(a.start<b.start||a.endExclusive>b.endExclusive)fail("Reference intervals must fit their entity/facility interval.")}
 for(const e of s.entities){m71Keys(e,["id","legalName","countryCode","regionCode","start","endExclusive","evidenceRefs"]);e.legalName=label(e.legalName,160);if(typeof e.countryCode!=="string"||!/^[A-Z]{2}$/.test(e.countryCode)||!(e.regionCode===null||typeof e.regionCode==="string"&&/^[A-Z0-9-]{1,12}$/.test(e.regionCode)))fail();interval(e);e.evidenceRefs=refs(e.evidenceRefs)}
 for(const f of s.facilities){m71Keys(f,["id","entityId","name","countryCode","regionCode","start","endExclusive","evidenceRefs"]);f.name=label(f.name,160);if(typeof f.countryCode!=="string"||!/^[A-Z]{2}$/.test(f.countryCode)||!(f.regionCode===null||typeof f.regionCode==="string"&&/^[A-Z0-9-]{1,12}$/.test(f.regionCode)))fail();within(f,entity(f.entityId));f.evidenceRefs=refs(f.evidenceRefs)}
 for(const r of s.relationships){m71Keys(r,["id","parentEntityId","childEntityId","ownershipPercent","controlFacts","start","endExclusive","evidenceRefs"]);within(r,entity(r.parentEntityId));within(r,entity(r.childEntityId));if(r.parentEntityId===r.childEntityId)fail();r.ownershipPercent=r.ownershipPercent===null?null:decimal(r.ownershipPercent,3);if(r.ownershipPercent!==null&&Number(r.ownershipPercent)>100)fail();r.controlFacts=nullableLabel(r.controlFacts);r.evidenceRefs=refs(r.evidenceRefs)}
 for(const r of s.relationships){if(s.relationships.some(o=>o.id!==r.id&&o.childEntityId===r.childEntityId&&o.start<r.endExclusive&&r.start<o.endExclusive))fail("Contradictory overlapping ownership/control relationships.");const visit=(id:string,start:string,end:string,seen:Set<string>)=>{if(seen.has(id))fail("Effective-dated relationship cycle.");for(const edge of s.relationships.filter(e=>e.parentEntityId===id&&e.start<end&&start<e.endExclusive))visit(edge.childEntityId,edge.start>start?edge.start:start,edge.endExclusive<end?edge.endExclusive:end,new Set([...seen,id]))};visit(r.parentEntityId,r.start,r.endExclusive,new Set())}
 for(const source of s.sources){m71Keys(source,["id","entityId","facilityId","name","domain","start","endExclusive","evidenceRefs"]);source.name=label(source.name,160);enumeration(source.domain,M71_DOMAINS);within(source,entity(source.entityId));if(source.facilityId!==null){const f=s.facilities.find(f=>f.id===source.facilityId);if(!f||f.entityId!==source.entityId)fail("Facility must belong to the source entity.");within(source,f!)}source.evidenceRefs=refs(source.evidenceRefs)}
 for(const b of s.boundaryDecisions){m71Keys(b,["id","entityId","disposition","reason","start","endExclusive","evidenceRefs"]);within(b,entity(b.entityId));enumeration(b.disposition,dispositions);b.reason=nullableLabel(b.reason);b.evidenceRefs=refs(b.evidenceRefs);if(["excluded","not_applicable"].includes(b.disposition)&&(!b.reason||!b.evidenceRefs.length))fail("Exclusion/non-applicability needs a rationale and supporting references.")}
 for(const e of s.entities){const decisions=s.boundaryDecisions.filter(d=>d.entityId===e.id).sort((a,b)=>a.start<b.start?-1:1);let cursor=e.start;for(const d of decisions){if(d.start!==cursor)fail("Boundary decisions must cover each entity interval without gaps or overlap.");cursor=d.endExclusive}if(cursor!==e.endExclusive)fail("Every expected entity needs full interval boundary decisions.")}
 for(const c of s.coverageItems){m71Keys(c,["id","domain","entityId","sourceId","disposition","activityDataState","evidenceState","methodReadiness","reason","evidenceRefs","estimateBasis","quantity","unit","start","endExclusive"]);interval(c);enumeration(c.domain,M71_DOMAINS);enumeration(c.disposition,dispositions);enumeration(c.activityDataState,["not_assessed","missing","partial","entered","estimate_proposed","explicit_zero"]);enumeration(c.evidenceState,["not_assessed","missing","partial","linked","conflicting"]);enumeration(c.methodReadiness,["not_assessed","unsupported","candidate"]);c.reason=nullableLabel(c.reason);c.evidenceRefs=refs(c.evidenceRefs);if(c.evidenceState==="linked"&&!c.evidenceRefs.length)fail("Linked evidence must resolve to retained synthetic evidence.");if(c.entityId!==null)within(c,entity(c.entityId));if(c.sourceId!==null){const source=s.sources.find(s=>s.id===c.sourceId);if(!source||source.entityId!==c.entityId||source.domain!==c.domain)fail("Source screening must match its entity and domain.");within(c,source!)}else if(c.entityId!==null)fail("This foundation accepts group or source screenings.")
 if(["excluded","not_applicable"].includes(c.disposition)&&(!c.reason||!c.evidenceRefs.length))fail("Exclusion/non-applicability needs a rationale and supporting references.");c.quantity=c.quantity===null?null:decimal(c.quantity);c.unit=c.unit===null?null:label(c.unit,40);if((c.quantity===null)!==(c.unit===null))fail();if(c.quantity==="0"?c.activityDataState!=="explicit_zero":c.activityDataState==="explicit_zero")fail("Explicit zero is distinct from missing activity.");if(c.quantity!==null&&!["entered","partial","estimate_proposed","explicit_zero"].includes(c.activityDataState))fail();if(c.activityDataState==="explicit_zero"&&(!c.reason||!c.evidenceRefs.length))fail("An explicit zero needs a basis and supporting reference.")
 if(c.estimateBasis!==null){m71Keys(c.estimateBasis,["methodVersionId","assumptions","inputEvidenceRefs","uncertainty"]);c.estimateBasis.methodVersionId=label(c.estimateBasis.methodVersionId,100);c.estimateBasis.assumptions=label(c.estimateBasis.assumptions);c.estimateBasis.uncertainty=label(c.estimateBasis.uncertainty);c.estimateBasis.inputEvidenceRefs=refs(c.estimateBasis.inputEvidenceRefs);if(!c.estimateBasis.inputEvidenceRefs.length)fail()}if(c.disposition==="included_estimate"&&(c.estimateBasis===null||c.activityDataState!=="estimate_proposed"))fail("Estimate assertions need a method candidate, assumptions, provenance and uncertainty.")}
 for(const domain of M71_DOMAINS){const rows=s.coverageItems.filter(c=>c.entityId===null&&c.sourceId===null&&c.domain===domain);if(rows.length!==1||rows[0]!.start!==s.period.start||rows[0]!.endExclusive!==s.period.endExclusive)fail("Every Scope 1/2 domain and all 15 Scope 3 categories require exactly one full-year group screening.")}
 for(const source of s.sources){const rows=s.coverageItems.filter(c=>c.sourceId===source.id);if(rows.length!==1||rows[0]!.start!==source.start||rows[0]!.endExclusive!==source.endExclusive)fail("Every source must have one matching full-interval screening.")}
 if(!s.requirements.length)fail();for(const r of s.requirements){m71Keys(r,["id","character","sourceLocator","sourceEdition","lastCheckedOn","applicability","missingFacts","reason"]);enumeration(r.character,["statute","regulation","standard","agency_guidance","proposal","enforcement_statement","court_order"]);enumeration(r.applicability,["unknown","conflicting"]);r.sourceLocator=nullableLabel(r.sourceLocator);r.sourceEdition=nullableLabel(r.sourceEdition);if(r.lastCheckedOn!==null)date(r.lastCheckedOn);r.reason=label(r.reason);if(!Array.isArray(r.missingFacts)||!r.missingFacts.length||r.missingFacts.length>20)fail();r.missingFacts=r.missingFacts.map(x=>label(x,100)).sort(m71CompareText);if(new Set(r.missingFacts).size!==r.missingFacts.length)fail()}
 if(new TextEncoder().encode(m71CanonicalJson(s)).length>50000)fail("The synthetic coverage snapshot is limited to 50,000 UTF-8 bytes.")
 return s
}
export function validateM71Save(v:unknown):M71SaveInput{m71Keys(v,["snapshot","expectedVersionId","expectedVersionSha256","correctionReason","idempotencyKey"]);if(!m71Uuid(v.idempotencyKey))fail();if(v.expectedVersionId===null){if(v.expectedVersionSha256!==null||v.correctionReason!==null)fail()}else if(!m71Uuid(v.expectedVersionId)||!m71HashString(v.expectedVersionSha256)||v.correctionReason===null)fail();return {...v,snapshot:validateM71Snapshot(v.snapshot),correctionReason:nullableLabel(v.correctionReason)} as unknown as M71SaveInput}
export function validateM71Review(v:unknown):M71ReviewInput{m71Keys(v,["versionId","expectedVersionSha256","decision","note","acknowledgedLimitations","idempotencyKey"]);if(!m71Uuid(v.versionId)||!m71HashString(v.expectedVersionSha256)||!m71Uuid(v.idempotencyKey))fail();enumeration(v.decision,["accepted_bounded_internal","changes_requested"]);const note=label(v.note);if(m71CanonicalJson(v.acknowledgedLimitations)!==m71CanonicalJson(M71_LIMITATIONS))fail("Acknowledge the exact synthetic limitations.");return {...v,note} as unknown as M71ReviewInput}
export function deriveM71Findings(s:M71Snapshot):M71Finding[]{const out:M71Finding[]=[];const add=(code:string,recordId:string|null,message:string)=>out.push({code,recordId,message});add("requirements_not_determined",null,"Corporate applicability and reporting requirements remain undetermined.");add("methods_not_released",null,"No corporate calculation method is released; emissions remain unknown.");if(s.consolidationApproach!=="operational_control")add("unsupported_consolidation",null,"This consolidation approach requires a later reviewed method.");for(const e of [...s.entities,...s.facilities]){if(e.countryCode!=="US"||e.regionCode!=="CA")add("unsupported_geography",e.id,"Discovered operations remain registered; this milestone supports only California operations.");if(e.start!==s.period.start||e.endExclusive!==s.period.endExclusive)add("unsupported_temporal_allocation",e.id,"Partial-year control/operations need reviewed interval allocation.")}
 for(const r of s.relationships){if(r.start!==s.period.start||r.endExclusive!==s.period.endExclusive||r.ownershipPercent!=="100")add("unsupported_boundary_relationship",r.id,"Partial-year or non-wholly-owned relationships need reviewed allocation.");if(!r.controlFacts||!r.evidenceRefs.length)add("control_evidence_missing",r.id,"Control facts and supporting evidence are incomplete.")}
 for(const b of s.boundaryDecisions){if(["missing","unassessed"].includes(b.disposition))add("boundary_unreconciled",b.id,"Expected entity remains unreconciled.");if(["excluded","not_applicable"].includes(b.disposition))add(b.reason&&b.evidenceRefs.length?"boundary_assertion_unverified":"boundary_basis_missing",b.id,"Boundary exclusion/non-applicability remains visible and requires qualified review.")}
 for(const c of s.coverageItems){if(c.quantity===null)add("activity_unknown",c.id,"No activity quantity is recorded; unknown is not zero.");if(c.evidenceState!=="linked")add(c.evidenceState==="conflicting"?"evidence_conflicting":"evidence_incomplete",c.id,"Supporting evidence is missing, incomplete or conflicting.");if(c.evidenceRefs.length)add("synthetic_evidence_not_sufficient",c.id,"Pinned fictional evidence is not proof of activity or reporting sufficiency.");if(c.methodReadiness!=="candidate")add("method_unsupported",c.id,"This screening has no released calculation method.");if(["excluded","not_applicable"].includes(c.disposition))add(c.reason&&c.evidenceRefs.length?"screening_assertion_unverified":"screening_basis_missing",c.id,"The assertion remains an open coverage finding.");if(c.estimateBasis)add("estimate_unverified",c.id,"Proposed estimate needs a reviewed method and supporting activity.")}
 for(const r of s.requirements)add(r.applicability==="conflicting"?"requirement_conflicting":"requirement_unknown",r.id,"Missing facts/source review prevent a legal determination.");return out.sort((a,b)=>(a.recordId??"")<(b.recordId??"")?-1:(a.recordId??"")>(b.recordId??"")?1:a.code<b.code?-1:1)}
/** JSON.parse otherwise silently accepts duplicate keys. Scan the grammar first. */
export function parseM71Json(text:string,maxBytes=250000):unknown{if(!Number.isInteger(maxBytes)||maxBytes<1||maxBytes>4000000||new TextEncoder().encode(text).length>maxBytes)fail("Coverage request is too large.");let i=0;const ws=()=>{while(/\s/.test(text[i]??"")&&i<text.length)i++};const str=()=>{const start=i++;while(i<text.length){if(text[i]==="\\"){i+=2;continue}if(text[i++]==='"')return JSON.parse(text.slice(start,i)) as string}return fail()};const scan=()=>{ws();if(text[i]==="{"){i++;const keys=new Set<string>();ws();if(text[i]==="}"){i++;return}while(i<text.length){ws();if(text[i]!=='"')fail();const key=str();if(keys.has(key))fail("Duplicate JSON keys are not accepted.");keys.add(key);ws();if(text[i++]!==":")fail();scan();ws();const end=text[i++];if(end==="}")return;if(end!==",")fail()}}else if(text[i]==="["){i++;ws();if(text[i]==="]"){i++;return}while(i<text.length){scan();ws();const end=text[i++];if(end==="]")return;if(end!==",")fail()}}else if(text[i]==='"'){str()}else{const start=i;while(i<text.length&&!/[\s,}\]]/.test(text[i]!))i++;if(start===i)fail();JSON.parse(text.slice(start,i))}};try{scan();ws();if(i!==text.length)fail();return JSON.parse(text)}catch(e){if(e instanceof M71ValidationError)throw e;return fail()}}
