export const M73_REPORT_TEMPLATE=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Synthetic stationary natural-gas source report</title><style>body{font:16px/1.5 system-ui;margin:2rem auto;padding:0 1rem;max-width:900px;color:#172f2c;overflow-wrap:anywhere}h1,h2{line-height:1.2}dt{font-weight:700}dd{margin:0 0 .6rem}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.5 monospace;background:#f3f6f3;padding:1rem}li{margin:.3rem 0}table{border-collapse:collapse;width:100%}th,td{padding:.45rem;text-align:left;border-bottom:1px solid #ccd8d0}@media print{body{font-size:11pt;margin:0;max-width:none}h2{break-after:avoid}pre{font-size:9pt}.technical-appendix:not([open]){display:none}}</style></head><body><h1>Stationary natural-gas source report — synthetic internal draft</h1><p>Development candidate · Not released. Corporate inventory incomplete. No filing determination or external assurance.</p><h2>Source and activity</h2><dl>{{facts}}</dl><h2>Gas results and calculation trace</h2>{{calculation}}<h2>Supporting synthetic statement</h2><dl>{{statement}}</dl><h2>Corporate coverage remains incomplete</h2><p>Stationary combustion is partial. Mobile combustion, fugitive emissions including refrigerants, process emissions, other sources/facilities/periods, Scope 2 and all 15 Scope 3 categories remain unresolved or separately assessed. Combustion only; upstream fuel emissions excluded.</p><ul>{{findings}}</ul><details class="technical-appendix"><summary>Exact version and provenance record</summary><pre>{{snapshot}}</pre></details></body></html>`
import type {M73Version,M73Review} from './m73-contract'
import {m73CanonicalJson} from './m73-validation'
export const m73ReportSnapshot=(version:M73Version,review:M73Review|null)=>({profile:'m73-source-report-v1',version:{...version,review:null},review})
export function m73RenderReport(snapshot:ReturnType<typeof m73ReportSnapshot>):string{
 const v=snapshot.version,c=v.calculation,choice=v.coverageVersion.snapshot.sources.find(s=>s.id===v.activity.binding.sourceId),facility=v.coverageVersion.snapshot.facilities.find(f=>f.id===v.activity.binding.facilityId),entity=v.coverageVersion.snapshot.entities.find(e=>e.id===v.activity.binding.entityId),boundary=v.coverageVersion.snapshot.boundaryDecisions.find(b=>b.id===v.activity.binding.boundaryDecisionId)
 const esc=(value:unknown)=>String(value??'Missing').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')
 const pair=(label:string,value:unknown)=>'<dt>'+label+'</dt><dd>'+esc(value)+'</dd>'
 const fields:Record<string,string>={facts:pair('Company',v.coverageVersion.snapshot.companyLabel)+pair('Entity',entity?.legalName)+pair('Boundary basis',boundary?.reason)+pair('Facility',facility?.name)+pair('Source',choice?.name)+pair('Reporting period','2025-01-01 through 2026-01-01 (exclusive)')+pair('Coverage version',v.activity.binding.coverageVersionId)+pair('Source version',v.version)+pair('Entered natural gas (MMBtu HHV)',v.activity.quantityMmbtu)+pair('Statement amount (MMBtu HHV)',v.activity.statement?.statedQuantityMmbtu)+pair('Discrepancy explanation',v.activity.discrepancyReason??'Not applicable')+pair('No-consumption explanation',v.activity.zeroReason??'Not applicable')+pair('Exact source subtotal (kg CO2e)',c?.total.unrounded)+pair('Displayed source subtotal (kg CO2e)',c?.total.display)+pair('Review as captured',snapshot.review?.decision??'Unreviewed')+pair('Reviewer note',snapshot.review?.note??'Not yet reviewed')+pair('Review time',snapshot.review?.reviewedAt??'Not yet reviewed')+pair('Correction reason',v.correctionReason??'Not applicable'),calculation:c?'<table><thead><tr><th>Gas</th><th>Mass (kg)</th><th>kg CO2e</th></tr></thead><tbody>'+(['co2','ch4','n2o'] as const).map((key,index)=>'<tr><th>'+['CO2','CH4','N2O'][index]+'</th><td>'+esc(c.gasResults[key].mass)+'</td><td>'+esc(c.gasResults[key].co2e)+'</td></tr>').join('')+'</tbody></table><p>Only the displayed total is rounded to four decimal places, using half-even rounding. Gas values and the exact total retain full precision.</p>':'<p>Activity is missing; no emissions total was calculated.</p>',statement:v.statement?pair('Statement type','Synthetic — not a utility bill')+pair('Issuer',v.activity.statement?.issuer)+pair('Reference',v.activity.statement?.reference)+pair('Dedicated meter',v.activity.statement?.meterLabel)+pair('Annual period','2025-01-01 through 2026-01-01 (exclusive)')+pair('Stated energy (MMBtu HHV)',v.activity.statement?.statedQuantityMmbtu)+pair('Description',v.activity.statement?.description)+pair('Retained statement locator',v.statement.locator)+pair('Statement SHA-256',v.statement.sha256):pair('Evidence','No supporting statement entered'),findings:[...new Set([...v.findings,...v.coverageVersion.findings].map(f=>f.message))].map(message=>'<li>'+esc(message)+'</li>').join(''),snapshot:esc(m73CanonicalJson(snapshot))}
 return M73_REPORT_TEMPLATE.replace(/\{\{(facts|calculation|statement|findings|snapshot)\}\}/g,(_,key:string)=>fields[key]!)
}
