/** Pure shared contract: no database, process, filesystem, Bun or emissions arithmetic. */
import {m71CanonicalJson,m71Keys,m71Uuid,m71HashString,M71_EVIDENCE_SHA256} from './m71-validation'
import {M71_ARTIFACT,type M71Version} from './m71-contract'
import {M73_PROFILE,M73_PERIOD,M73_LIMITATIONS,type M73SaveInput,type M73ReviewInput,type M73ReportInput,type M73Activity,type M73Version,type M73Review,type M73Report,type M73Calculation,type M73Finding,type M73SourceChoice,type M73BindingInput} from './m73-contract'
export const m73CanonicalJson=m71CanonicalJson
export class M73ValidationError extends Error {}
export const m73Require=(v:unknown,message='Invalid synthetic natural-gas request.'):void=>{if(!v)throw new M73ValidationError(message)}
export const m73Keys=(v:unknown,keys:string[])=>{try{m71Keys(v,keys)}catch{throw new M73ValidationError('Unexpected or missing natural-gas fields.')}}
export function m73Text(v:unknown,max=500):string{m73Require(typeof v==='string'&&v.length>0);const s=(v as string).trim().normalize('NFC');m73Require(s.length>0&&Array.from(s).length<=max&&!/[\u0000-\u001f\u007f-\u009f\ud800-\udfff]/u.test(s));return s}
export const m73NullableText=(v:unknown,max=500)=>v===null?null:m73Text(v,max)
export function m73Quantity(v:unknown):string{m73Require(typeof v==='string'&&/^(?:0|[1-9][0-9]{0,11})(?:\.[0-9]{1,3})?$/.test(v));const [a,b='']=(v as string).split('.');return a+'.'+b.padEnd(3,'0')}
export function validateM73Save(value:unknown):M73SaveInput{
 m73Keys(value,['profile','binding','period','fuel','heatBasis','unit','quantityMmbtu','statement','manualConfirmation','discrepancyReason','zeroReason','expectedVersionId','expectedVersionSha256','correctionReason','idempotencyKey'])
 const v=structuredClone(value) as M73SaveInput
 m73Keys(v.binding,['coverageVersionId','coverageVersionSha256','entityId','facilityId','sourceId','boundaryDecisionId']);for(const [k,x]of Object.entries(v.binding))m73Require(k.endsWith('Sha256')?m71HashString(x):m71Uuid(x))
 m73Keys(v.period,['start','endExclusive']);m73Require(v.profile===M73_PROFILE&&m73CanonicalJson(v.period)===m73CanonicalJson(M73_PERIOD)&&v.fuel==='Natural Gas'&&v.heatBasis==='HHV'&&v.unit==='MMBtu'&&typeof v.manualConfirmation==='boolean'&&m71Uuid(v.idempotencyKey))
 v.quantityMmbtu=v.quantityMmbtu===null?null:m73Quantity(v.quantityMmbtu)
 if(v.statement!==null){m73Keys(v.statement,['issuer','reference','meterLabel','statedQuantityMmbtu','description','consumptionBasis']);m73Require(v.statement.consumptionBasis==='dedicated_meter_consumed_no_adjustments');v.statement={...v.statement,issuer:m73Text(v.statement.issuer,120),reference:m73Text(v.statement.reference,120),meterLabel:m73Text(v.statement.meterLabel,120),statedQuantityMmbtu:m73Quantity(v.statement.statedQuantityMmbtu),description:m73Text(v.statement.description,2000)}}
 v.discrepancyReason=m73NullableText(v.discrepancyReason);v.zeroReason=m73NullableText(v.zeroReason);v.correctionReason=m73NullableText(v.correctionReason)
 if(v.expectedVersionId===null)m73Require(v.expectedVersionSha256===null&&v.correctionReason===null);else m73Require(m71Uuid(v.expectedVersionId)&&m71HashString(v.expectedVersionSha256)&&v.correctionReason!==null)
 if(v.quantityMmbtu!==null){m73Require(v.statement!==null&&v.manualConfirmation,'A numeric calculation needs a retained statement and manual confirmation.');if(v.quantityMmbtu==='0.000')m73Require(v.statement!.statedQuantityMmbtu==='0.000'&&v.zeroReason!==null,'Zero needs a zero-supporting statement and no-consumption reason.');else if(v.quantityMmbtu!==v.statement!.statedQuantityMmbtu)m73Require(v.discrepancyReason!==null,'Explain the unresolved entered-versus-stated discrepancy.')}
 return v
}
export function validateM73Review(value:unknown):M73ReviewInput{m73Keys(value,['versionId','expectedVersionSha256','decision','note','acknowledgedLimitations','idempotencyKey']);const v=structuredClone(value) as M73ReviewInput;m73Require(m71Uuid(v.versionId)&&m71HashString(v.expectedVersionSha256)&&m71Uuid(v.idempotencyKey)&&['accepted_bounded_internal','changes_requested'].includes(v.decision)&&m73CanonicalJson(v.acknowledgedLimitations)===m73CanonicalJson(M73_LIMITATIONS));v.note=m73Text(v.note);return v}
export function validateM73Report(value:unknown):M73ReportInput{m73Keys(value,['versionId','expectedVersionSha256','expectedDecisionId','expectedDecisionSha256','idempotencyKey']);const v=value as M73ReportInput;m73Require(m71Uuid(v.versionId)&&m71HashString(v.expectedVersionSha256)&&m71Uuid(v.idempotencyKey)&&(v.expectedDecisionId===null?v.expectedDecisionSha256===null:m71Uuid(v.expectedDecisionId)&&m71HashString(v.expectedDecisionSha256)));return structuredClone(v)}
export function m73Activity(v:M73SaveInput):M73Activity{const {expectedVersionId:_,expectedVersionSha256:__,correctionReason:___,idempotencyKey:____,...activity}=v;return activity}
export function deriveM73Findings(a:M73Activity):M73Finding[]{const findings=[{code:'scope1_incomplete',message:'This source subtotal does not cover all stationary, mobile, fugitive or process emissions.'},{code:'method_not_released',message:'Factors and method are development candidates; no reporting or assurance determination.'}];if(a.quantityMmbtu===null)findings.push({code:'activity_missing',message:'Activity is missing; no emissions were calculated.'});if(a.statement===null)findings.push({code:'statement_missing',message:'No synthetic activity statement is retained.'});if(a.quantityMmbtu!==null&&a.statement&&a.quantityMmbtu!==a.statement.statedQuantityMmbtu)findings.push({code:'activity_statement_discrepancy',message:'Entered and stated quantities differ; the discrepancy remains unresolved.'});return findings}
export function m73SourceChoices(v:M71Version):M73SourceChoice[]{const s=v.snapshot,within=(x:{start:string;endExclusive:string})=>x.start===M73_PERIOD.start&&x.endExclusive===M73_PERIOD.endExclusive;return s.sources.filter(x=>x.domain==='stationary_combustion').map(source=>{const e=s.entities.find(x=>x.id===source.entityId),f=s.facilities.find(x=>x.id===source.facilityId),b=s.boundaryDecisions.find(x=>x.entityId===source.entityId&&within(x));const findings:M73Finding[]=[];const add=(message:string)=>findings.push({code:'source_ineligible',message});if(s.consolidationApproach!=='operational_control'||!within(s.period)||!e||!f||f.entityId!==e.id||e.countryCode!=='US'||e.regionCode!=='CA'||f.countryCode!=='US'||f.regionCode!=='CA'||!within(e)||!within(f)||!within(source))add('Selected source needs a full-year2025 California operational-control entity and facility.');const supportedRefs=(refs:{artifactId:string;expectedSha256:string;locator:string}[])=>refs.some(r=>r.artifactId===M71_ARTIFACT.id&&r.expectedSha256===M71_EVIDENCE_SHA256&&r.locator===M71_ARTIFACT.locator);if(!b||b.disposition!=='included_activity'||!b.reason?.trim()||!supportedRefs(b.evidenceRefs))add('Save the entity inclusion rationale and pinned fictional boundary reference first.');let id=e?.id;const seen=new Set<string>();while(id){if(seen.has(id)){add('Boundary relationship cycle.');break}seen.add(id);const rel=s.relationships.find(r=>r.childEntityId===id);if(!rel)break;if(!within(rel)||rel.ownershipPercent!=='100'||!rel.controlFacts?.trim()||!supportedRefs(rel.evidenceRefs))add('Every selected relationship requires full-year operational-control facts and fictional support.');id=rel.parentEntityId}return {binding:{coverageVersionId:v.id,coverageVersionSha256:v.versionSha256,entityId:source.entityId,facilityId:source.facilityId??'',sourceId:source.id,boundaryDecisionId:b?.id??''},companyLabel:s.companyLabel,entityLabel:e?.legalName??'',facilityLabel:f?.name??'',sourceLabel:source.name,eligible:findings.length===0,findings}})}
export function m73ResolveBinding(binding:M73BindingInput,coverage:M71Version){const choice=m73SourceChoices(coverage).find(s=>s.binding.sourceId===binding.sourceId);m73Require(choice?.eligible&&m73CanonicalJson(choice.binding)===m73CanonicalJson(binding),'The selected saved source or boundary is not eligible.');return choice!}
export function m73StatementText(a:M73Activity,v:M71Version):string{m73Require(a.statement!==null);const c=m73ResolveBinding(a.binding,v);return 'SYNTHETIC — NOT A UTILITY BILL\n'+m73CanonicalJson({profile:'m73-synthetic-gas-statement-v1',companyLabel:c.companyLabel,entityLabel:c.entityLabel,facilityLabel:c.facilityLabel,sourceLabel:c.sourceLabel,binding:a.binding,period:a.period,fuel:a.fuel,heatBasis:a.heatBasis,unit:a.unit,statement:a.statement})+'\n'}
export const m73InputHashPayload=(v:Pick<M73Version,'activity'>)=>v.activity
export const m73ContentPayload=(v:Pick<M73Version,'activity'|'coverageVersion'|'statement'|'calculation'|'findings'>)=>({activity:v.activity,coverageVersion:v.coverageVersion,statement:v.statement,calculation:v.calculation,findings:v.findings})
export const m73VersionHashPayload=(v:M73Version)=>({profile:M73_PROFILE,id:v.id,companyId:v.companyId,worksheetId:v.worksheetId,version:v.version,previousVersionId:v.previousVersionId,previousVersionSha256:v.previousVersionSha256,createdBy:v.createdBy,createdAt:v.createdAt,contributorIds:v.contributorIds,correctionReason:v.correctionReason,inputSha256:v.inputSha256,contentSha256:v.contentSha256})
export function m73ReviewHashPayload(companyId:string,r:M73Review){const {decisionSha256:_,...body}=r;return {profile:M73_PROFILE,companyId,...body}}
export function m73ReportHashPayload(r:M73Report){const {reportSha256:_,html:__,snapshotJson:___,...body}=r;return {profile:M73_PROFILE,...body}}
export function m73CalculationHashPayload(c:M73Calculation){const {resultSha256:_,...body}=c;return body}
export const m73Export=(v:M73Version)=>m73CanonicalJson({...v,review:null})
