import type {M71Version,M71Finding} from './m71-contract'
export const M73_PROFILE='synthetic-stationary-natural-gas-v1' as const
export const M73_PERIOD={start:'2025-01-01',endExclusive:'2026-01-01'} as const
export const M73_LIMITATIONS=['synthetic_only','scope1_incomplete','corporate_inventory_incomplete','factor_and_method_not_released','combustion_only_upstream_excluded','requirements_not_determined','no_external_assurance'] as const
export const M73_MAX_STREAMS=3, M73_MAX_VERSIONS=40, M73_MAX_HISTORY_BYTES=3800000, M73_MAX_RESPONSE_BYTES=4000000
export type M73Period=typeof M73_PERIOD
export interface M73BindingInput {coverageVersionId:string;coverageVersionSha256:string;entityId:string;facilityId:string;sourceId:string;boundaryDecisionId:string}
export interface M73StatementInput {issuer:string;reference:string;meterLabel:string;statedQuantityMmbtu:string;description:string;consumptionBasis:'dedicated_meter_consumed_no_adjustments'}
export interface M73SaveInput {profile:typeof M73_PROFILE;binding:M73BindingInput;period:M73Period;fuel:'Natural Gas';heatBasis:'HHV';unit:'MMBtu';quantityMmbtu:string|null;statement:M73StatementInput|null;manualConfirmation:boolean;discrepancyReason:string|null;zeroReason:string|null;expectedVersionId:string|null;expectedVersionSha256:string|null;correctionReason:string|null;idempotencyKey:string}
export interface M73ReviewInput {versionId:string;expectedVersionSha256:string;decision:'accepted_bounded_internal'|'changes_requested';note:string;acknowledgedLimitations:string[];idempotencyKey:string}
export interface M73ReportInput {versionId:string;expectedVersionSha256:string;expectedDecisionId:string|null;expectedDecisionSha256:string|null;idempotencyKey:string}
export type M73Activity=Omit<M73SaveInput,'expectedVersionId'|'expectedVersionSha256'|'correctionReason'|'idempotencyKey'>
export interface M73AuthorityInput {binding:M73BindingInput;period:M73Period;fuel:'Natural Gas';heatBasis:'HHV';unit:'MMBtu';quantityMmbtu:string;statementSha256:string}
export interface M73Method {id:string;version:string;engineSha256:string;dependencySha256:string;sourceSha256:string;factorSha256:string;gwpSha256:string;sourceTitle:string;sourceSheet:string;factorCells:string[];gwpCells:string[];noteCells:string[];co2KgPerMmbtu:string;ch4GramsPerMmbtu:string;n2oGramsPerMmbtu:string;ch4Gwp:string;n2oGwp:string;gwpAssessment:string;status:'development_candidate_not_released';releaseEligible:false;rights:'unresolved_for_factor_release'}
export const M73_METHOD:M73Method={id:'stationary-natural-gas-combustion',version:'m73-development-v1',engineSha256:'e1b91d4fa6afa1126eeb642769c458d0b0b747c12ad5ee172543afb9246eaa14',dependencySha256:'eebade88f291cec281f38efe09597a107ce24904f28782d51405e739c4d37603',sourceSha256:'43afb91d79b2ae765b3a447549d9e1021a144a407cec5eb804be9fcf69a668a7',factorSha256:'80da7b01f57c852a1bca9a6f80a23636baef02091cd26880a7395c8331f5a20f',gwpSha256:'d87fb6c54a170e1dff70327bf475774febb3681a754cb8abec9c4c31efa3b908',sourceTitle:'EPA GHG Emission Factors Hub 2025',sourceSheet:'Emission Factors Hub',factorCells:['C38','E38','F38','G38'],gwpCells:['E524','E525','E526'],noteCells:['C94','C95','C99','E523','C10','C556'],co2KgPerMmbtu:'53.06',ch4GramsPerMmbtu:'1.0',n2oGramsPerMmbtu:'0.10',ch4Gwp:'28',n2oGwp:'265',gwpAssessment:'IPCC AR5 100-year',status:'development_candidate_not_released',releaseEligible:false,rights:'unresolved_for_factor_release'}
export interface M73Gas {mass:string;massUnit:string;co2e:string;co2eUnit:'kg CO2e'}
export interface M73Calculation {profile:'m73-decimal-result-v1';input:M73AuthorityInput;inputSha256:string;method:M73Method;gasResults:{co2:M73Gas;ch4:M73Gas;n2o:M73Gas};total:{unrounded:string;display:string;unit:'kg CO2e';rounding:'half_even_4dp'};resultSha256:string}
export interface M73Authority {calculate(input:M73AuthorityInput):Promise<M73Calculation>;replayBatch(records:M73Calculation[]):Promise<void>}
export interface M73Statement {id:string;profile:'m73-synthetic-gas-statement-v1';input:M73StatementInput;locator:string;text:string;sha256:string;byteLength:number}
export interface M73Review {id:string;versionId:string;versionSha256:string;decision:M73ReviewInput['decision'];note:string;acknowledgedLimitations:string[];reviewerId:string;reviewedAt:string;decisionSha256:string}
export interface M73Finding {code:string;message:string}
export interface M73Version {id:string;companyId:string;worksheetId:string;version:number;previousVersionId:string|null;previousVersionSha256:string|null;createdBy:string;createdAt:string;contributorIds:string[];correctionReason:string|null;activity:M73Activity;coverageVersion:M71Version;statement:M73Statement|null;calculation:M73Calculation|null;findings:M73Finding[];inputSha256:string;contentSha256:string;versionSha256:string;synthetic:true;scope1Completeness:'incomplete';corporateCompleteness:'incomplete';releaseEligible:false;assurance:'none';review:M73Review|null}
export interface M73Report {id:string;companyId:string;worksheetId:string;versionId:string;versionSha256:string;decisionId:string|null;decisionSha256:string|null;createdBy:string;createdAt:string;rendererVersion:'m73-source-report-v1';html:string;htmlSha256:string;htmlByteLength:number;snapshotJson:string;snapshotSha256:string;reportSha256:string}
export interface M73Worksheet {profile:typeof M73_PROFILE;companyId:string;worksheetId:string;sourceId:string;headVersionId:string;versions:M73Version[];reports:M73Report[];findings:M73Finding[];limitations:string[];synthetic:true;scope1Completeness:'incomplete';corporateCompleteness:'incomplete';releaseEligible:false;assurance:'none'}
export interface M73SourceChoice {binding:M73BindingInput;companyLabel:string;entityLabel:string;facilityLabel:string;sourceLabel:string;eligible:boolean;findings:M73Finding[]}
export interface M73Register {profile:typeof M73_PROFILE;companyId:string;coverageHeadVersionId:string|null;worksheets:M73Worksheet[];sources:M73SourceChoice[];coverageFindings:M71Finding[];limitations:string[];synthetic:true;scope1Completeness:'incomplete';corporateCompleteness:'incomplete';releaseEligible:false;assurance:'none'}
