import type {WorkspaceSql} from './workspace'
import {readCorporateInventory,m71Export} from './m71'
import {M73_PROFILE,M73_LIMITATIONS,M73_METHOD,type M73Authority,type M73Register,type M73Version,type M73Review,type M73Report,type M73SaveInput,type M73ReviewInput,type M73ReportInput,type M73Calculation} from './m73-contract'
import {m73CanonicalJson,validateM73Save,validateM73Review,validateM73Report,m73Activity,m73ResolveBinding,m73SourceChoices,m73StatementText,m73InputHashPayload,m73ContentPayload,m73VersionHashPayload,m73ReviewHashPayload,m73ReportHashPayload,m73CalculationHashPayload,m73Export,deriveM73Findings,m73Keys} from './m73-validation'
import {m73RenderReport,m73ReportSnapshot} from './m73-report'
import {m71Uuid} from './m71-validation'
export * from './m73-contract'
export * from './m73-validation'
export * from './m73-report'
export const m73Hash=(v:unknown)=>new Bun.CryptoHasher('sha256').update(m73CanonicalJson(v)).digest('hex')
export const m73BytesHash=(s:string)=>new Bun.CryptoHasher('sha256').update(s).digest('hex')
const bytes=(s:string)=>new TextEncoder().encode(s).length
const same=(a:unknown,b:unknown)=>m73CanonicalJson(a)===m73CanonicalJson(b)
const flags={synthetic:true as const,scope1Completeness:'incomplete' as const,corporateCompleteness:'incomplete' as const,releaseEligible:false as const,assurance:'none' as const}
const fail=():never=>{throw Error('Stored natural-gas workpaper could not be verified.')}
const verify=(v:unknown)=>{if(!v)fail()}
const iso=(v:string)=>{const d=new Date(v);return Number.isFinite(d.getTime())?d.toISOString():fail()}
type RequestRow={company_id:string;idempotency_key:string;actor_id:string;kind:string;fingerprint:string;record_id:string}
type AuditRow={company_id:string;record_id:string;kind:string;record_sha256:string;actor_id:string;created_at:string}
export async function readStationaryGas(tx:WorkspaceSql,companyId:string,authority:M73Authority):Promise<M73Register|null>{
 if(!(await tx.query<{allowed:boolean}>('select neuvetra.m73_lock($1,false) allowed',[companyId])).rows[0]?.allowed)return null
 const coverage=await readCorporateInventory(tx,companyId);if(!coverage)return null
 const data=(await tx.query<{heads:any[];versions:any[];statements:any[];reviews:any[];reports:any[];requests:RequestRow[];audits:AuditRow[]}>(`select
 coalesce((select jsonb_agg(x order by id) from neuvetra.stationary_gas_heads x where company_id=$1),'[]') heads,
 coalesce((select jsonb_agg(to_jsonb(x)||jsonb_build_object('quantity_mmbtu',x.quantity_mmbtu::text) order by worksheet_id,version) from neuvetra.stationary_gas_versions x where company_id=$1),'[]') versions,
 coalesce((select jsonb_agg(x) from neuvetra.stationary_gas_statements x where company_id=$1),'[]') statements,
 coalesce((select jsonb_agg(x) from neuvetra.stationary_gas_reviews x where company_id=$1),'[]') reviews,
 coalesce((select jsonb_agg(x order by created_at,id) from neuvetra.stationary_gas_reports x where company_id=$1),'[]') reports,
 coalesce((select jsonb_agg(x) from neuvetra.stationary_gas_requests x where company_id=$1),'[]') requests,
 coalesce((select jsonb_agg(x) from neuvetra.stationary_gas_audit x where company_id=$1),'[]') audits`,[companyId])).rows[0]!
 verify(data.heads.length<=3&&data.versions.length<=40&&data.audits.length===data.versions.length+data.reviews.length+data.reports.length&&data.requests.length===data.audits.length)
 const audit=(kind:string,id:string,hash:string,actor:string,time:string,worksheetId:string|null,request:unknown)=>{const rows=data.audits.filter(a=>a.kind===kind&&a.record_id===id),req=data.requests.filter(r=>r.kind===kind&&r.record_id===id);verify(rows.length===1&&req.length===1);const a=rows[0]!,r=req[0]!;verify(a.company_id===companyId&&a.actor_id===actor&&a.record_sha256===hash&&iso(a.created_at)===time&&r.company_id===companyId&&r.actor_id===actor&&m71Uuid(r.idempotency_key)&&r.fingerprint===m73Hash({operation:kind,actor,companyId,worksheetId,request}))}
 const all:M73Version[]=[]
 const worksheets:M73Register['worksheets']=[]
 for(const head of data.heads){verify(head.company_id===companyId&&m71Uuid(head.id)&&m71Uuid(head.source_id));const versions:M73Version[]=[]
  for(const row of data.versions.filter(r=>r.worksheet_id===head.id)){
   const v=structuredClone(row.payload) as M73Version,prior=versions[versions.length-1]
   try{m73Keys(v,['id','companyId','worksheetId','version','previousVersionId','previousVersionSha256','createdBy','createdAt','contributorIds','correctionReason','activity','coverageVersion','statement','calculation','findings','inputSha256','contentSha256','versionSha256','synthetic','scope1Completeness','corporateCompleteness','releaseEligible','assurance','review'])}catch{return fail()}
   verify(v.id===row.id&&m71Uuid(v.id)&&v.companyId===companyId&&row.company_id===companyId&&v.worksheetId===head.id&&v.version===versions.length+1&&v.version===row.version&&v.previousVersionId===(prior?.id??null)&&v.previousVersionId===row.previous_version_id&&v.previousVersionSha256===(prior?.versionSha256??null)&&v.createdBy===row.created_by&&m71Uuid(v.createdBy)&&v.createdAt===iso(row.created_at)&&v.createdAt>=(prior?.createdAt??'')&&v.review===null)
   verify(Object.entries(flags).every(([k,x])=>(v as any)[k]===x)&&v.activity.binding.sourceId===head.source_id)
   let normalized:M73SaveInput;try{normalized=validateM73Save({...v.activity,expectedVersionId:v.previousVersionId,expectedVersionSha256:v.previousVersionSha256,correctionReason:v.correctionReason,idempotencyKey:v.id})}catch{return fail()}
   verify(same(m73Activity(normalized),v.activity));if(prior)verify(!same(prior.activity,v.activity)||prior.correctionReason!==v.correctionReason)
   const cv=coverage.versions.find(x=>x.id===v.activity.binding.coverageVersionId);verify(cv&&row.coverage_version_id===cv.id&&same({...cv!,review:null},v.coverageVersion));try{m73ResolveBinding(v.activity.binding,v.coverageVersion)}catch{return fail()}
   const contributors=[...new Set([...(prior?.contributorIds??[]),...v.coverageVersion.contributorIds,v.createdBy])].sort();verify(same(v.contributorIds,contributors)&&same(v.findings,deriveM73Findings(v.activity)))
   if(v.activity.statement===null)verify(v.statement===null&&row.statement_id===null);else{const s=v.statement;verify(s&&row.statement_id===s.id&&m71Uuid(s.id));const matches=data.statements.filter(x=>x.id===s!.id);verify(matches.length===1);const sr=matches[0];let expectedText:string;try{expectedText=m73StatementText(v.activity,v.coverageVersion)}catch{return fail()}
    verify(same(s,{id:s!.id,profile:'m73-synthetic-gas-statement-v1',input:v.activity.statement,locator:`m73-statement:${s!.id}:annual-activity`,text:expectedText,sha256:m73BytesHash(expectedText),byteLength:bytes(expectedText)})&&same(sr.payload,s)&&sr.company_id===companyId&&sr.statement_text===expectedText&&sr.statement_sha256===s!.sha256)
   }
   verify(row.quantity_mmbtu===v.activity.quantityMmbtu)
   if(v.activity.quantityMmbtu===null)verify(v.calculation===null);else{const c=v.calculation;verify(c&&same(c.method,M73_METHOD)&&same(c.input,{binding:v.activity.binding,period:v.activity.period,fuel:v.activity.fuel,heatBasis:v.activity.heatBasis,unit:v.activity.unit,quantityMmbtu:v.activity.quantityMmbtu,statementSha256:v.statement!.sha256})&&c.inputSha256===m73Hash(c.input)&&c.resultSha256===m73Hash(m73CalculationHashPayload(c)))}
   verify(v.inputSha256===row.input_sha256&&v.inputSha256===m73Hash(m73InputHashPayload(v))&&v.contentSha256===row.content_sha256&&v.contentSha256===m73Hash(m73ContentPayload(v))&&v.versionSha256===row.version_sha256&&v.versionSha256===m73Hash(m73VersionHashPayload(v))&&row.export_text===m73Export(v))
   audit('save',v.id,v.versionSha256,v.createdBy,v.createdAt,prior?head.id:null,{...v.activity,expectedVersionId:v.previousVersionId,expectedVersionSha256:v.previousVersionSha256,correctionReason:v.correctionReason})
   const reviews=data.reviews.filter(r=>r.version_id===v.id);verify(reviews.length<=1);if(reviews[0]){const rr=reviews[0],r=rr.payload as M73Review;try{m73Keys(r,['id','versionId','versionSha256','decision','note','acknowledgedLimitations','reviewerId','reviewedAt','decisionSha256']);validateM73Review({versionId:r.versionId,expectedVersionSha256:r.versionSha256,decision:r.decision,note:r.note,acknowledgedLimitations:r.acknowledgedLimitations,idempotencyKey:r.id})}catch{return fail()}
    verify(r.id===rr.id&&rr.company_id===companyId&&r.versionId===v.id&&r.versionSha256===v.versionSha256&&r.reviewerId===rr.reviewed_by&&m71Uuid(r.reviewerId)&&!v.contributorIds.includes(r.reviewerId)&&r.reviewedAt===iso(rr.reviewed_at)&&r.reviewedAt>=v.createdAt&&r.decisionSha256===rr.decision_sha256&&r.decisionSha256===m73Hash(m73ReviewHashPayload(companyId,r))&&(r.decision!=='accepted_bounded_internal'||v.calculation!==null));audit('review',r.id,r.decisionSha256,r.reviewerId,r.reviewedAt,head.id,{versionId:v.id,expectedVersionSha256:v.versionSha256,decision:r.decision,note:r.note,acknowledgedLimitations:r.acknowledgedLimitations});v.review=r
   }versions.push(v);all.push(v)
  }
  verify(versions.length>0&&head.version_id===versions[versions.length-1]!.id&&head.revision===versions.length)
  const last=versions[versions.length-1]!,meter=last.activity.statement?m73Hash([last.activity.statement.issuer.toLowerCase(),last.activity.statement.meterLabel.toLowerCase(),'2025']):null,reference=last.activity.statement?m73Hash([last.activity.statement.issuer.toLowerCase(),last.activity.statement.reference.toLowerCase(),'2025']):null;verify(head.meter_key===meter&&head.reference_key===reference)
  const reports:M73Report[]=[];for(const row of data.reports.filter(r=>r.worksheet_id===head.id)){const r=row.payload as M73Report;try{m73Keys(r,['id','companyId','worksheetId','versionId','versionSha256','decisionId','decisionSha256','createdBy','createdAt','rendererVersion','html','htmlSha256','htmlByteLength','snapshotJson','snapshotSha256','reportSha256'])}catch{return fail()}const v=versions.find(v=>v.id===r.versionId);verify(v&&r.id===row.id&&m71Uuid(r.id)&&r.companyId===companyId&&row.company_id===companyId&&r.worksheetId===head.id&&row.version_id===v.id&&r.versionSha256===v.versionSha256&&r.createdBy===row.created_by&&m71Uuid(r.createdBy)&&r.createdAt===iso(row.created_at)&&r.createdAt>=v.createdAt&&r.rendererVersion==='m73-source-report-v1');const decision=r.decisionId===null?null:v!.review;verify(r.decisionId===row.decision_id&&(r.decisionId===null?r.decisionSha256===null:decision&&decision.id===r.decisionId&&decision.decisionSha256===r.decisionSha256&&r.createdAt>=decision.reviewedAt));const snapshot=m73ReportSnapshot(v!,decision),text=m73CanonicalJson(snapshot),html=m73RenderReport(snapshot);verify(r.snapshotJson===text&&r.snapshotSha256===m73BytesHash(text)&&r.html===html&&r.htmlSha256===m73BytesHash(html)&&r.htmlByteLength===bytes(html)&&r.reportSha256===row.report_sha256&&r.reportSha256===m73Hash(m73ReportHashPayload(r)));audit('report',r.id,r.reportSha256,r.createdBy,r.createdAt,head.id,{versionId:r.versionId,expectedVersionSha256:r.versionSha256,expectedDecisionId:r.decisionId,expectedDecisionSha256:r.decisionSha256});reports.push(r)}
  worksheets.push({profile:M73_PROFILE,companyId,worksheetId:head.id,sourceId:head.source_id,headVersionId:head.version_id,versions,reports,findings:last.activity.binding.coverageVersionId!==coverage.headVersionId?[{code:'coverage_head_changed',message:'Corporate coverage changed; relink this source before a new review or report.'}]:[],limitations:[...M73_LIMITATIONS],...flags})
 }
 verify(all.length===data.versions.length&&data.statements.length===all.filter(v=>v.statement).length&&data.reviews.every(r=>all.some(v=>v.id===r.version_id))&&data.reports.every(r=>worksheets.some(w=>w.worksheetId===r.worksheet_id)))
 await authority.replayBatch(all.flatMap(v=>v.calculation?[v.calculation]:[]))
 const head=coverage.versions[coverage.versions.length-1],result:M73Register={profile:M73_PROFILE,companyId,coverageHeadVersionId:coverage.headVersionId,worksheets,sources:head?m73SourceChoices(head):[],coverageFindings:head?.findings??[],limitations:[...M73_LIMITATIONS],...flags};verify(bytes(m73CanonicalJson(result))<=4000000);return result
}
async function locked(tx:WorkspaceSql,companyId:string){if(!(await tx.query<{allowed:boolean}>('select neuvetra.m73_lock($1,true) allowed',[companyId])).rows[0]?.allowed)throw Object.assign(Error('Forbidden.'),{code:'42501'})}
export async function saveStationaryGas(tx:WorkspaceSql,actor:string,companyId:string,worksheetId:string|null,value:M73SaveInput,authority:M73Authority){const input=validateM73Save(value);await locked(tx,companyId);const before=await readStationaryGas(tx,companyId,authority);if(!before)return fail();const priorRequest=(await tx.query<RequestRow>('select * from neuvetra.stationary_gas_requests where company_id=$1 and idempotency_key=$2',[companyId,input.idempotencyKey])).rows[0];if(priorRequest){const {idempotencyKey:_,...request}=input;if(priorRequest.fingerprint!==m73Hash({operation:'save',actor,companyId,worksheetId,request})||priorRequest.kind!=='save')throw Object.assign(Error('Idempotency conflict.'),{code:'23505'});const v=before.worksheets.flatMap(w=>w.versions).find(v=>v.id===priorRequest.record_id);return v?{...v,review:null}:fail()}
 const coverage=await readCorporateInventory(tx,companyId),cv=coverage?.versions[coverage.versions.length-1];if(!cv||cv.id!==input.binding.coverageVersionId||cv.versionSha256!==input.binding.coverageVersionSha256)throw Object.assign(Error('Coverage changed.'),{code:'23505'});m73ResolveBinding(input.binding,cv)
 const activity=m73Activity(input);let calculation:M73Calculation|null=null;if(activity.quantityMmbtu!==null){const statementHash=m73BytesHash(m73StatementText(activity,cv));calculation=await authority.calculate({binding:activity.binding,period:activity.period,fuel:activity.fuel,heatBasis:activity.heatBasis,unit:activity.unit,quantityMmbtu:activity.quantityMmbtu,statementSha256:statementHash})}
 const id=(await tx.query<{id:string}>('select neuvetra.save_stationary_gas($1,$2,$3::text::jsonb,$4::text::jsonb) id',[companyId,worksheetId,JSON.stringify(input),JSON.stringify(calculation)])).rows[0]!.id;const after=await readStationaryGas(tx,companyId,authority);const v=after?.worksheets.flatMap(w=>w.versions).find(v=>v.id===id);return v?{...v,review:null}:fail()
}
export async function reviewStationaryGas(tx:WorkspaceSql,companyId:string,worksheetId:string,input:M73ReviewInput,authority:M73Authority){await locked(tx,companyId);await readStationaryGas(tx,companyId,authority);const id=(await tx.query<{id:string}>('select neuvetra.review_stationary_gas($1,$2,$3::text::jsonb) id',[companyId,worksheetId,JSON.stringify(validateM73Review(input))])).rows[0]!.id;const after=await readStationaryGas(tx,companyId,authority);return after?.worksheets.flatMap(w=>w.versions).map(v=>v.review).find(r=>r?.id===id)??fail()}
export async function createStationaryGasReport(tx:WorkspaceSql,companyId:string,worksheetId:string,input:M73ReportInput,authority:M73Authority){await locked(tx,companyId);await readStationaryGas(tx,companyId,authority);const id=(await tx.query<{id:string}>('select neuvetra.create_stationary_gas_report($1,$2,$3::text::jsonb) id',[companyId,worksheetId,JSON.stringify(validateM73Report(input))])).rows[0]!.id;const after=await readStationaryGas(tx,companyId,authority);return after?.worksheets.flatMap(w=>w.reports).find(r=>r.id===id)??fail()}
