import type {M74Review,M74Version} from './m74-contract'
import {m74CanonicalJson} from './m74-validation'

export const M74_REPORT_TEMPLATE=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Synthetic vehicle mobile-combustion source report</title><style>body{font:16px/1.5 system-ui;margin:2rem auto;padding:0 1rem;max-width:900px;color:#172f2c;overflow-wrap:anywhere}h1,h2{line-height:1.2}dt{font-weight:700}dd{margin:0 0 .6rem}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.5 monospace;background:#f3f6f3;padding:1rem}li{margin:.3rem 0}table{border-collapse:collapse;width:100%}th,td{padding:.45rem;text-align:left;border-bottom:1px solid #ccd8d0}@media print{body{font-size:11pt;margin:0;max-width:none}h2{break-after:avoid}pre{font-size:9pt}.technical-appendix:not([open]){display:none}}</style></head><body><h1>Vehicle mobile-combustion subtotal — synthetic internal draft</h1><p>Development candidate · Not released. Corporate inventory incomplete. No filing determination or external assurance.</p><h2>Source, vehicle and activity</h2><dl>{{facts}}</dl><h2>Gas results and calculation trace</h2>{{calculation}}<h2>Supporting synthetic fuel statement</h2><dl>{{fuelStatement}}</dl><h2>Supporting synthetic mileage statement</h2><dl>{{mileageStatement}}</dl><h2>Method and provenance</h2><dl>{{method}}</dl><h2>Corporate coverage remains incomplete</h2><p>This report covers one bounded vehicle source. Other stationary, mobile, fugitive, process, facility and period sources remain unresolved or separately assessed. Combustion only; upstream fuel emissions are excluded.</p><ul>{{findings}}</ul><details class="technical-appendix"><summary>Exact version and provenance record</summary><pre>{{snapshot}}</pre></details></body></html>`

export const m74ReportSnapshot=(version:M74Version,review:M74Review|null)=>({profile:'m74-mobile-source-report-v1' as const,version:{...version,review:null},review})
export function m74RenderReport(snapshot:ReturnType<typeof m74ReportSnapshot>):string{
 const version=snapshot.version,calculation=version.calculation,source=version.coverageVersion.snapshot.sources.find(item=>item.id===version.activity.binding.sourceId),facility=version.coverageVersion.snapshot.facilities.find(item=>item.id===version.activity.binding.facilityId),entity=version.coverageVersion.snapshot.entities.find(item=>item.id===version.activity.binding.entityId),boundary=version.coverageVersion.snapshot.boundaryDecisions.find(item=>item.id===version.activity.binding.boundaryDecisionId)
 const escape=(value:unknown)=>String(value??'Missing').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')
 const pair=(label:string,value:unknown)=>'<dt>'+label+'</dt><dd>'+escape(value)+'</dd>'
 const evidence=(kind:'fuel'|'mileage')=>{const statement=kind==='fuel'?version.fuelStatement:version.mileageStatement,input=kind==='fuel'?version.activity.fuelStatement:version.activity.mileageStatement;if(!statement||!input)return pair('Evidence','No supporting '+kind+' statement retained');return pair('Statement type','Synthetic human-entered '+kind+' statement')+pair('Issuer',input.issuer)+pair('Reference',input.reference)+pair('Annual period','2025-01-01 through 2026-01-01 (exclusive)')+pair(kind==='fuel'?'Stated consumed fuel (U.S. gallons)':'Stated distance (vehicle-miles)',kind==='fuel'?(input as NonNullable<typeof version.activity.fuelStatement>).statedQuantityGallons:(input as NonNullable<typeof version.activity.mileageStatement>).statedDistanceMiles)+pair('Description',input.description)+pair('Manual confirmation',kind==='fuel'?version.activity.fuelManualConfirmation:version.activity.mileageManualConfirmation)+pair('Retained statement locator',statement.locator)+pair('Statement SHA-256',statement.sha256)+pair('Statement byte length',statement.byteLength)}
 const method=calculation?.method
 const fields:Record<string,string>={
  facts:pair('Company',version.coverageVersion.snapshot.companyLabel)+pair('Entity',entity?.legalName)+pair('Boundary basis',boundary?.reason)+pair('Base facility',facility?.name)+pair('Source',source?.name)+pair('Reporting period','2025-01-01 through 2026-01-01 (exclusive)')+pair('All-trip location basis','All vehicle travel, including interstate trips')+pair('Coverage version',version.activity.binding.coverageVersionId)+pair('Source version',version.version)+pair('Vehicle asset ID',version.activity.vehicle.assetId)+pair('Vehicle class',version.activity.vehicle.vehicleClass)+pair('Classification basis',version.activity.vehicle.classificationBasis)+pair('Model year',version.activity.vehicle.modelYear)+pair('Fuel',version.activity.vehicle.fuel)+pair('Control basis',version.activity.vehicle.controlBasis)+pair('Entered consumed fuel (U.S. gallons)',version.activity.quantityGallons)+pair('Fuel statement amount (U.S. gallons)',version.activity.fuelStatement?.statedQuantityGallons)+pair('Fuel dimension status',version.activityStatus.fuel)+pair('Fuel discrepancy explanation',version.activity.fuelDiscrepancyReason??'Not applicable')+pair('Entered distance (vehicle-miles)',version.activity.distanceMiles)+pair('Mileage statement amount (vehicle-miles)',version.activity.mileageStatement?.statedDistanceMiles)+pair('Mileage dimension status',version.activityStatus.mileage)+pair('Mileage discrepancy explanation',version.activity.mileageDiscrepancyReason??'Not applicable')+pair('No-operation/no-consumption explanation',version.activity.zeroReason??'Not applicable')+pair('Exact vehicle mobile-combustion subtotal (kg CO2e)',calculation?.total.unrounded)+pair('Displayed vehicle mobile-combustion subtotal (kg CO2e)',calculation?.total.display)+pair('Review as captured',snapshot.review?.decision??'Unreviewed')+pair('Reviewer note',snapshot.review?.note??'Not yet reviewed')+pair('Review time',snapshot.review?.reviewedAt??'Not yet reviewed')+pair('Correction reason',version.correctionReason??'Not applicable'),
  calculation:calculation?'<table><thead><tr><th>Gas</th><th>Mass</th><th>kg CO2e</th></tr></thead><tbody>'+(['co2','ch4','n2o'] as const).map((key,index)=>'<tr><th>'+['CO2','CH4','N2O'][index]+'</th><td>'+escape(calculation.gasResults[key].mass)+' '+escape(calculation.gasResults[key].massUnit)+'</td><td>'+escape(calculation.gasResults[key].co2e)+'</td></tr>').join('')+'</tbody></table><p>CO2 uses consumed U.S. gallons. CH4 and N2O use vehicle-miles. Only the displayed total is rounded to four decimal places, using half-even rounding. Gas values and the exact total retain full precision.</p>':'<p>Required compatible activity and evidence are incomplete or contradictory; no emissions total was calculated.</p>',
  fuelStatement:evidence('fuel'),
  mileageStatement:evidence('mileage'),
  method:method?pair('Method ID and version',method.id+' / '+method.version)+pair('Source',method.sourceTitle)+pair('Source edition','January 15, 2025')+pair('Workbook SHA-256',method.sourceSha256)+pair('Factor locators',method.factorCells.join(', '))+pair('GWP locators',method.gwpCells.join(', '))+pair('Note locators',method.noteCells.join(', '))+pair('Factor normalization','Published displayed decimals corroborated by the EPA 2025 PDF; XLSX binary tails are not used')+pair('CO2 factor',method.co2KgPerGallon+' kg CO2 per U.S. gallon')+pair('CH4 factor',method.ch4GramsPerMile+' g CH4 per vehicle-mile')+pair('N2O factor',method.n2oGramsPerMile+' g N2O per vehicle-mile')+pair('GWP basis',method.gwpAssessment+'; CH4 '+method.ch4Gwp+', N2O '+method.n2oGwp)+pair('Rights status',method.rights)+pair('Method status',method.status):pair('Method','No calculation was admitted; method remains a development candidate'),
  findings:[...new Set([...version.findings,...version.coverageVersion.findings].map(item=>item.message))].map(message=>'<li>'+escape(message)+'</li>').join(''),
  snapshot:escape(m74CanonicalJson(snapshot)),
 }
 return M74_REPORT_TEMPLATE.replace(/\{\{(facts|calculation|fuelStatement|mileageStatement|method|findings|snapshot)\}\}/g,(_,key:string)=>fields[key]!)
}
