import type {M71Finding,M71Version} from './m71-contract'

export const M74_PROFILE='synthetic-mobile-diesel-v1' as const
export const M74_PERIOD={start:'2025-01-01',endExclusive:'2026-01-01'} as const
export const M74_LIMITATIONS=['synthetic_only','scope1_incomplete','corporate_inventory_incomplete','factor_and_method_not_released','vehicle_mobile_combustion_subtotal_only','upstream_fuel_emissions_excluded','requirements_not_determined','no_external_assurance'] as const
export const M74_MAX_STREAMS=3, M74_MAX_VERSIONS=40, M74_MAX_HISTORY_BYTES=3800000, M74_MAX_RESPONSE_BYTES=4000000

export type M74Period=typeof M74_PERIOD
export interface M74BindingInput {coverageVersionId:string;coverageVersionSha256:string;entityId:string;facilityId:string;sourceId:string;boundaryDecisionId:string}
export interface M74VehicleInput {assetId:string;vehicleClass:'Medium- and Heavy-Duty Vehicles';classificationBasis:string;modelYear:number;fuel:'Fossil Diesel';controlBasis:'owned_operational_control_full_year'}
export interface M74FuelStatementInput {issuer:string;reference:string;statedQuantityGallons:string;description:string;consumptionBasis:'dedicated_vehicle_consumed_no_adjustments'}
export interface M74MileageStatementInput {issuer:string;reference:string;statedDistanceMiles:string;description:string;distanceBasis:'dedicated_vehicle_annual_distance'}
export interface M74SaveInput {profile:typeof M74_PROFILE;binding:M74BindingInput;period:M74Period;vehicle:M74VehicleInput;quantityGallons:string|null;distanceMiles:string|null;fuelStatement:M74FuelStatementInput|null;mileageStatement:M74MileageStatementInput|null;fuelManualConfirmation:boolean;mileageManualConfirmation:boolean;fuelDiscrepancyReason:string|null;mileageDiscrepancyReason:string|null;zeroReason:string|null;expectedVersionId:string|null;expectedVersionSha256:string|null;correctionReason:string|null;idempotencyKey:string}
export interface M74ReviewInput {versionId:string;expectedVersionSha256:string;decision:'accepted_bounded_internal'|'changes_requested';note:string;acknowledgedLimitations:string[];idempotencyKey:string}
export interface M74ReportInput {versionId:string;expectedVersionSha256:string;expectedDecisionId:string|null;expectedDecisionSha256:string|null;idempotencyKey:string}
export type M74Activity=Omit<M74SaveInput,'expectedVersionId'|'expectedVersionSha256'|'correctionReason'|'idempotencyKey'>
export type M74DimensionStatus='missing'|'evidence_missing'|'unconfirmed'|'explicit_zero'|'entered'|'discrepancy'
export interface M74ActivityStatus {fuel:M74DimensionStatus;mileage:M74DimensionStatus}
export interface M74AuthorityInput {binding:M74BindingInput;period:M74Period;vehicle:M74VehicleInput;quantityGallons:string;quantityUnit:'US_gallon';distanceMiles:string;distanceUnit:'vehicle_mile';fuelStatementSha256:string;mileageStatementSha256:string}
export interface M74Method {id:'mobile-diesel-combustion';version:'m74-development-v1';engineSha256:string;sourceSha256:string;factorSha256:string;gwpSha256:string;sourceTitle:string;sourceSheet:string;factorCells:string[];gwpCells:string[];noteCells:string[];co2KgPerGallon:string;ch4GramsPerMile:string;n2oGramsPerMile:string;ch4Gwp:string;n2oGwp:string;gwpAssessment:string;status:'development_candidate_not_released';releaseEligible:false;rights:'unresolved_for_factor_release'}
export const M74_METHOD:M74Method={id:'mobile-diesel-combustion',version:'m74-development-v1',engineSha256:'1dc0bb7249d91e854004a8cadd34068be3fc03ecdd6e10b4cf297d375d7f52a6',sourceSha256:'43afb91d79b2ae765b3a447549d9e1021a144a407cec5eb804be9fcf69a668a7',factorSha256:'416931c40b347f1e22e9d4019ca1c28bd27ce40d7c16a3beeac3dadbbb783187',gwpSha256:'c151f9b90b23eba7ee9d36dd57a851ecf7a6f200c915579819b683d2b3b3c1c7',sourceTitle:'EPA GHG Emission Factors Hub 2025',sourceSheet:'Emission Factors Hub',factorCells:['C103:E103','C107:E107','C255:G256'],gwpCells:['E523:E526'],noteCells:['F3','F248:G248','C255:D256'],co2KgPerGallon:'10.21',ch4GramsPerMile:'0.0095',n2oGramsPerMile:'0.0431',ch4Gwp:'28',n2oGwp:'265',gwpAssessment:'IPCC AR5 100-year',status:'development_candidate_not_released',releaseEligible:false,rights:'unresolved_for_factor_release'}
export interface M74Gas {mass:string;massUnit:string;co2e:string;co2eUnit:'kg CO2e'}
export interface M74Calculation {profile:'m74-decimal-result-v1';input:M74AuthorityInput;inputSha256:string;method:M74Method;gasResults:{co2:M74Gas;ch4:M74Gas;n2o:M74Gas};total:{unrounded:string;display:string;unit:'kg CO2e';rounding:'half_even_4dp'};resultSha256:string}
export interface M74Authority {calculate(input:M74AuthorityInput):Promise<M74Calculation>;replayBatch(records:M74Calculation[]):Promise<void>}
export interface M74FuelStatement {id:string;profile:'m74-synthetic-fuel-statement-v1';input:M74FuelStatementInput;locator:string;text:string;sha256:string;byteLength:number}
export interface M74MileageStatement {id:string;profile:'m74-synthetic-mileage-statement-v1';input:M74MileageStatementInput;locator:string;text:string;sha256:string;byteLength:number}
export interface M74Review {id:string;versionId:string;versionSha256:string;decision:M74ReviewInput['decision'];note:string;acknowledgedLimitations:string[];reviewerId:string;reviewedAt:string;decisionSha256:string}
export interface M74Finding {code:string;message:string}
export interface M74Version {id:string;companyId:string;worksheetId:string;version:number;previousVersionId:string|null;previousVersionSha256:string|null;createdBy:string;createdAt:string;contributorIds:string[];correctionReason:string|null;activity:M74Activity;activityStatus:M74ActivityStatus;coverageVersion:M71Version;fuelStatement:M74FuelStatement|null;mileageStatement:M74MileageStatement|null;calculation:M74Calculation|null;findings:M74Finding[];inputSha256:string;contentSha256:string;versionSha256:string;synthetic:true;scope1Completeness:'incomplete';corporateCompleteness:'incomplete';releaseEligible:false;assurance:'none';review:M74Review|null}
export interface M74Report {id:string;companyId:string;worksheetId:string;versionId:string;versionSha256:string;decisionId:string|null;decisionSha256:string|null;createdBy:string;createdAt:string;rendererVersion:'m74-mobile-source-report-v1';html:string;htmlSha256:string;htmlByteLength:number;snapshotJson:string;snapshotSha256:string;reportSha256:string}
export interface M74Worksheet {profile:typeof M74_PROFILE;companyId:string;worksheetId:string;sourceId:string;vehicleAssetId:string;headVersionId:string;versions:M74Version[];reports:M74Report[];findings:M74Finding[];limitations:string[];synthetic:true;scope1Completeness:'incomplete';corporateCompleteness:'incomplete';releaseEligible:false;assurance:'none'}
export interface M74SourceChoice {binding:M74BindingInput;companyLabel:string;entityLabel:string;facilityLabel:string;sourceLabel:string;eligible:boolean;findings:M74Finding[]}
export interface M74Register {profile:typeof M74_PROFILE;companyId:string;coverageHeadVersionId:string|null;worksheets:M74Worksheet[];sources:M74SourceChoice[];coverageFindings:M71Finding[];limitations:string[];synthetic:true;scope1Completeness:'incomplete';corporateCompleteness:'incomplete';releaseEligible:false;assurance:'none'}
