import type {M71Version} from './m71-contract'
import type {M73BindingInput,M73Period,M73Gas} from './m73-contract'

export const M76_DIESEL_PROFILE='synthetic-stationary-diesel-v1' as const
export const M76_DIESEL_PERIOD={start:'2025-01-01',endExclusive:'2026-01-01'} as const
export const M76_DIESEL_FUEL='Fossil Distillate Fuel Oil No. 2' as const
export const M76_DIESEL_LIMITATIONS=['synthetic_only','scope1_incomplete','corporate_inventory_incomplete','factor_and_method_not_released','stationary_generator_subtotal_only','default_hhv_estimate','combustion_only_upstream_excluded','requirements_not_determined','no_external_assurance'] as const
export const M76_DIESEL_MAX_STREAMS=1,M76_DIESEL_MAX_VERSIONS=40,M76_DIESEL_MAX_REPORTS=40,M76_DIESEL_MAX_HISTORY_BYTES=3800000,M76_DIESEL_MAX_RESPONSE_BYTES=4000000
export type M76DieselBindingInput=M73BindingInput
export type M76DieselPeriod=M73Period
export interface M76DieselEquipmentInput {assetId:string;identifierBasis:string;equipmentType:'stationary_emergency_generator';engineType:'compression_ignition';stationaryInstallation:'fixed';controlBasis:'owned_operational_control_full_year';controlExplanation:string;fuel:typeof M76_DIESEL_FUEL;fossilFraction:'1.000';fuelGradeBasis:string}
export interface M76DieselStatementInput {issuer:string;reference:string;meterLabel:string;statedQuantityGallons:string;description:string;consumptionBasis:'dedicated_generator_consumed_no_adjustments';measurementBasis:'direct_device_fuel_meter';dedicatedToSingleDevice:true;includesTesting:true;stockDerivedConsumption:false;sharedFuelAllocation:false;consumptionBoundaryExplanation:string;supplierSpecificHhvAvailable:false;supplierSpecificCarbonAvailable:false;defaultFactorEligibilityExplanation:string}
export interface M76DieselSaveInput {profile:typeof M76_DIESEL_PROFILE;binding:M76DieselBindingInput;period:M76DieselPeriod;equipment:M76DieselEquipmentInput;unit:'US_gallon';quantityGallons:string|null;statement:M76DieselStatementInput|null;manualConfirmation:boolean;discrepancyReason:string|null;zeroReason:string|null;expectedVersionId:string|null;expectedVersionSha256:string|null;correctionReason:string|null;idempotencyKey:string}
export type M76DieselActivity=Omit<M76DieselSaveInput,'expectedVersionId'|'expectedVersionSha256'|'correctionReason'|'idempotencyKey'>
export type M76DieselActivityStatus='missing'|'evidence_missing'|'unconfirmed'|'explicit_zero'|'entered'|'discrepancy'|'unsupported_zero'
export interface M76DieselReviewInput {versionId:string;expectedVersionSha256:string;decision:'accepted_bounded_internal'|'changes_requested';note:string;acknowledgedLimitations:string[];idempotencyKey:string}
export interface M76DieselReportInput {versionId:string;expectedVersionSha256:string;expectedDecisionId:string|null;expectedDecisionSha256:string|null;idempotencyKey:string}
export interface M76DieselAuthorityInput {binding:M76DieselBindingInput;period:M76DieselPeriod;equipment:M76DieselEquipmentInput;unit:'US_gallon';quantityGallons:string;statementSha256:string}
export interface M76DieselMethod {id:'m76.stationary-distillate-no2.ca2025.ar5.default-hhv.v1';version:'m76-development-v1';engineSha256:string;sourceSha256:string;factorSha256:string;gwpSha256:string;sourceTitle:string;sourceSheet:string;factorCells:string[];gwpCells:string[];noteCells:string[];hhvMmbtuPerGallon:'0.138';co2KgPerMmbtu:'73.96';ch4GramsPerMmbtu:'3.0';n2oGramsPerMmbtu:'0.60';ch4Gwp:'28';n2oGwp:'265';gwpAssessment:string;status:'development_candidate_not_released';releaseEligible:false;rights:'unresolved_for_factor_release'}
export const M76_DIESEL_METHOD:M76DieselMethod={id:'m76.stationary-distillate-no2.ca2025.ar5.default-hhv.v1',version:'m76-development-v1',engineSha256:'60de93b901185527affd1eae73d400582cc9d041ecd13bb5668c9041374f6266',sourceSha256:'43afb91d79b2ae765b3a447549d9e1021a144a407cec5eb804be9fcf69a668a7',factorSha256:'7f2a655ff2fc3a214f8f076aeaf7acebc25a50f89801985f255157a3ab3a85d0',gwpSha256:'c151f9b90b23eba7ee9d36dd57a851ecf7a6f200c915579819b683d2b3b3c1c7',sourceTitle:'EPA GHG Emission Factors Hub 2025',sourceSheet:'Emission Factors Hub',factorCells:['C55','D55','E55','F55','G55'],gwpCells:['E524','E525','E526'],noteCells:['D14','D47:G47','C94','C95','C99','E523','C10','C556'],hhvMmbtuPerGallon:'0.138',co2KgPerMmbtu:'73.96',ch4GramsPerMmbtu:'3.0',n2oGramsPerMmbtu:'0.60',ch4Gwp:'28',n2oGwp:'265',gwpAssessment:'IPCC AR5 100-year',status:'development_candidate_not_released',releaseEligible:false,rights:'unresolved_for_factor_release'}
export interface M76DieselCalculation {profile:'m76-diesel-decimal-result-v1';input:M76DieselAuthorityInput;inputSha256:string;method:M76DieselMethod;derivedHhv:{quantityMmbtu:string;heatBasis:'HHV';basis:'default_hhv_estimate'};gasResults:{co2:M73Gas;ch4:M73Gas;n2o:M73Gas};total:{unrounded:string;display:string;unit:'kg CO2e';rounding:'half_even_4dp'};resultSha256:string}
export interface M76DieselAuthority {calculate(input:M76DieselAuthorityInput):Promise<M76DieselCalculation>;replayBatch(records:M76DieselCalculation[]):Promise<void>}
export interface M76DieselStatement {id:string;profile:'m76-synthetic-generator-statement-v1';input:M76DieselStatementInput;locator:string;text:string;sha256:string;byteLength:number}
export interface M76DieselReview {id:string;versionId:string;versionSha256:string;decision:M76DieselReviewInput['decision'];note:string;acknowledgedLimitations:string[];reviewerId:string;reviewedAt:string;decisionSha256:string}
export interface M76DieselFinding {code:string;message:string}
export interface M76DieselVersion {id:string;companyId:string;worksheetId:string;version:number;previousVersionId:string|null;previousVersionSha256:string|null;createdBy:string;createdAt:string;contributorIds:string[];correctionReason:string|null;activity:M76DieselActivity;activityStatus:M76DieselActivityStatus;coverageVersion:M71Version;statement:M76DieselStatement|null;calculation:M76DieselCalculation|null;findings:M76DieselFinding[];inputSha256:string;contentSha256:string;versionSha256:string;synthetic:true;scope1Completeness:'incomplete';corporateCompleteness:'incomplete';releaseEligible:false;assurance:'none';review:M76DieselReview|null}
export interface M76DieselReport {id:string;companyId:string;worksheetId:string;versionId:string;versionSha256:string;decisionId:string|null;decisionSha256:string|null;createdBy:string;createdAt:string;rendererVersion:'m76-generator-source-report-v1';html:string;htmlSha256:string;htmlByteLength:number;snapshotJson:string;snapshotSha256:string;reportSha256:string}
export interface M76DieselWorksheet {profile:typeof M76_DIESEL_PROFILE;companyId:string;worksheetId:string;sourceId:string;headVersionId:string;versions:M76DieselVersion[];reports:M76DieselReport[];findings:M76DieselFinding[];limitations:string[];synthetic:true;scope1Completeness:'incomplete';corporateCompleteness:'incomplete';releaseEligible:false;assurance:'none'}
export interface M76DieselSourceChoice {binding:M76DieselBindingInput;companyLabel:string;entityLabel:string;facilityLabel:string;sourceLabel:string;eligible:boolean;findings:M76DieselFinding[]}
export interface M76DieselRegister {profile:typeof M76_DIESEL_PROFILE;companyId:string;coverageHeadVersionId:string|null;worksheets:M76DieselWorksheet[];sources:M76DieselSourceChoice[];coverageFindings:{code:string;message:string}[];limitations:string[];synthetic:true;scope1Completeness:'incomplete';corporateCompleteness:'incomplete';releaseEligible:false;assurance:'none'}
