import {M76_LIMITATIONS,M76_RECONCILIATION_PROFILE,M76_MAX_ASSETS,M76_PERIOD,M76_PROFILE,type M76Activity,type M76Dependencies,type M76Finding,type M76Link,type M76Proof,type M76Reconciliation,type M76ReconciliationRow,type M76Report,type M76ReportInput,type M76Review,type M76ReviewInput,type M76RosterAsset,type M76SaveInput,type M76StatementInput,type M76Version,type M76WorkpaperPin} from './m76-contract'
import type {M71Version} from './m71-contract'
import type {M73Version} from './m73-contract'
import type {M76DieselVersion} from './m76-diesel-contract'
import {M76_DIESEL_FUEL} from './m76-diesel-contract'
import {m71CanonicalJson,m71HashString,m71Keys,m71Uuid} from './m71-validation'
import {m76EquipmentId} from './m76-diesel-validation'
import {m73SourceChoices} from './m73-validation'

export const m76CanonicalJson=m71CanonicalJson
export class M76ValidationError extends Error {}
const fail=(message='Invalid stationary-equipment request.'):never=>{throw new M76ValidationError(message)}
const require: (condition:unknown,message?:string)=>asserts condition=(condition,message)=>{if(!condition)fail(message)}
const keys=(value:unknown,names:string[])=>{try{m71Keys(value,names)}catch{fail('Unexpected or missing stationary-equipment fields.')}}
const text=(value:unknown,max=500):string=>{require(typeof value==='string');const out=(value as string).trim().normalize('NFC');require(out.length>0&&Array.from(out).length<=max&&!/[\u0000-\u001f\u007f-\u009f\ud800-\udfff]/u.test(out));return out}
const nullableText=(value:unknown,max=500)=>value===null?null:text(value,max)
const uuidOrNull=(value:unknown)=>{require(value===null||m71Uuid(value));return value as string|null}
const period=(value:unknown)=>{keys(value,['start','endExclusive']);const out=value as {start:unknown;endExclusive:unknown},valid=(v:unknown):v is string=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&(()=>{const [y,m,d]=v.split('-').map(Number),date=new Date(Date.UTC(y!,m!-1,d!));return date.getUTCFullYear()===y&&date.getUTCMonth()===m!-1&&date.getUTCDate()===d})();require(valid(out.start)&&valid(out.endExclusive)&&out.start<out.endExclusive);return {start:out.start,endExclusive:out.endExclusive}}
const normalizedId=(value:unknown)=>value===null?null:m76EquipmentId(value)

function asset(value:unknown):M76RosterAsset{
 keys(value,['rowId','equipmentId','aliases','identifierBasis','entityId','facilityId','period','equipmentType','fuel','controlBasis','classificationBasis','controlExplanation','meterRelationship']);const v=structuredClone(value) as M76RosterAsset
 require(m71Uuid(v.rowId));v.equipmentId=normalizedId(v.equipmentId);require(Array.isArray(v.aliases)&&v.aliases.length<=8);v.aliases=v.aliases.map(m76EquipmentId).sort();require(new Set(v.aliases).size===v.aliases.length&&!v.aliases.includes(v.equipmentId??''));v.entityId=uuidOrNull(v.entityId);v.facilityId=uuidOrNull(v.facilityId);v.period=v.period===null?null:period(v.period);require(['boiler','space_heater','stationary_emergency_generator','other','unknown'].includes(v.equipmentType));v.identifierBasis=nullableText(v.identifierBasis);v.fuel=nullableText(v.fuel,100);require(['owned_operational_control_full_year','other_control_arrangement','unknown'].includes(v.controlBasis));v.classificationBasis=nullableText(v.classificationBasis);v.controlExplanation=nullableText(v.controlExplanation)
 if(v.meterRelationship!==null){keys(v.meterRelationship,['issuer','meterLabel','measurementBasis','dedicatedToSingleDevice','explanation']);const r=v.meterRelationship;require(['dedicated_single_device_consumption','shared_meter','shared_tank_allocation','stock_derived','other','unknown'].includes(r.measurementBasis)&&[null,true,false].includes(r.dedicatedToSingleDevice));r.issuer=nullableText(r.issuer,120);r.meterLabel=nullableText(r.meterLabel,120);r.explanation=nullableText(r.explanation,2000)}return v
}
function statement(value:unknown):M76StatementInput{
 keys(value,['issuer','reference','description','discoveryBasis','coveredEntityIds','coveredFacilityIds','completeness','allControlledLocationsIncluded','assets']);const v=structuredClone(value) as M76StatementInput
 v.issuer=text(v.issuer,120);v.reference=text(v.reference,120);v.description=text(v.description,2000);v.discoveryBasis=text(v.discoveryBasis,2000);for(const field of ['coveredEntityIds','coveredFacilityIds'] as const){require(Array.isArray(v[field])&&v[field].every(m71Uuid));v[field]=[...new Set(v[field])].sort()}require(['declared_complete','partial','unknown'].includes(v.completeness)&&typeof v.allControlledLocationsIncluded==='boolean'&&Array.isArray(v.assets)&&v.assets.length<=M76_MAX_ASSETS);v.assets=v.assets.map(asset);require(new Set(v.assets.map(x=>x.rowId)).size===v.assets.length);return v
}
export function validateM76Save(value:unknown):M76SaveInput{
 keys(value,['profile','coverageVersionId','coverageVersionSha256','expectedDependencySha256','period','rosterStatement','manualConfirmation','links','expectedVersionId','expectedVersionSha256','correctionReason','idempotencyKey']);const v=structuredClone(value) as M76SaveInput
 require(v.profile===M76_PROFILE&&m71Uuid(v.coverageVersionId)&&m71HashString(v.coverageVersionSha256)&&m71HashString(v.expectedDependencySha256)&&m71Uuid(v.idempotencyKey)&&typeof v.manualConfirmation==='boolean');v.period=period(v.period);require(m76CanonicalJson(v.period)===m76CanonicalJson(M76_PERIOD));v.rosterStatement=v.rosterStatement===null?null:statement(v.rosterStatement);require(Array.isArray(v.links));v.links=v.links.map(raw=>{keys(raw,['rowId','sourceId']);const link=raw as M76Link;require(m71Uuid(link.rowId));return {rowId:link.rowId,sourceId:uuidOrNull(link.sourceId)}});require(new Set(v.links.map(x=>x.rowId)).size===v.links.length);if(v.rosterStatement)require(m76CanonicalJson(v.links.map(x=>x.rowId).sort())===m76CanonicalJson(v.rosterStatement.assets.map(x=>x.rowId).sort()));else require(v.links.length===0)
 if(v.expectedVersionId===null)require(v.expectedVersionSha256===null&&v.correctionReason===null);else{require(m71Uuid(v.expectedVersionId)&&m71HashString(v.expectedVersionSha256));v.correctionReason=text(v.correctionReason)}return v
}
export function validateM76Review(value:unknown):M76ReviewInput{keys(value,['versionId','expectedVersionSha256','expectedDependencySha256','decision','note','acknowledgedLimitations','idempotencyKey']);const v=structuredClone(value) as M76ReviewInput;require(m71Uuid(v.versionId)&&m71HashString(v.expectedVersionSha256)&&m71HashString(v.expectedDependencySha256)&&m71Uuid(v.idempotencyKey)&&['accepted_bounded_reconciliation','changes_requested'].includes(v.decision)&&m76CanonicalJson(v.acknowledgedLimitations)===m76CanonicalJson(M76_LIMITATIONS));v.note=text(v.note);return v}
export function validateM76Report(value:unknown):M76ReportInput{keys(value,['expectedReconciliationSha256','idempotencyKey']);const v=structuredClone(value) as M76ReportInput;require(m71HashString(v.expectedReconciliationSha256)&&m71Uuid(v.idempotencyKey));return v}
export function m76Activity(input:M76SaveInput):M76Activity{const {expectedDependencySha256:_,expectedVersionId:__,expectedVersionSha256:___,correctionReason:____,idempotencyKey:_____,...activity}=input;return activity}
export const m76DependencyPayload=(value:Pick<M76Dependencies,'coveragePin'|'coverageReviewPin'|'workpaperPins'>)=>({coveragePin:value.coveragePin,coverageReviewPin:value.coverageReviewPin,workpaperPins:value.workpaperPins})
export const m76InputPayload=(v:Pick<M76Version,'activity'>)=>v.activity
export const m76ContentPayload=(v:Pick<M76Version,'activity'|'dependencies'|'statement'|'findings'>)=>({activity:v.activity,dependencies:v.dependencies,statement:v.statement,findings:v.findings})
export const m76VersionHashPayload=(v:M76Version)=>({profile:M76_PROFILE,id:v.id,companyId:v.companyId,rosterId:v.rosterId,version:v.version,previousVersionId:v.previousVersionId,previousVersionSha256:v.previousVersionSha256,createdBy:v.createdBy,createdAt:v.createdAt,contributorIds:v.contributorIds,correctionReason:v.correctionReason,inputSha256:v.inputSha256,contentSha256:v.contentSha256})
export function m76ReviewHashPayload(companyId:string,v:M76Review){const {decisionSha256:_,...body}=v;return {profile:M76_PROFILE,companyId,...body}}
export function m76ReportHashPayload(v:M76Report){const {reportSha256:_,snapshotJson:__,html:___,...body}=v;return {profile:M76_PROFILE,...body}}
export const m76Export=(v:M76Version)=>m76CanonicalJson(v)
export function m76StatementText(activity:M76Activity,coverage:M71Version):string{require(activity.rosterStatement!==null);return 'SYNTHETIC — NOT AN ORIGINAL COMPANY EQUIPMENT REGISTER OR INDEPENDENT MEASUREMENT\n'+m76CanonicalJson({profile:'m76-synthetic-equipment-statement-v1',companyLabel:coverage.snapshot.companyLabel,coverageVersionId:coverage.id,coverageVersionSha256:coverage.versionSha256,period:activity.period,statement:activity.rosterStatement})+'\n'}

export function m76ValidateResolvedReferences(activity:M76Activity,coverage:M71Version):void{for(const row of activity.rosterStatement?.assets??[]){require(row.entityId===null||coverage.snapshot.entities.some(x=>x.id===row.entityId),'Declared entity does not resolve in this corporate version.');require(row.facilityId===null||coverage.snapshot.facilities.some(x=>x.id===row.facilityId),'Declared facility does not resolve in this corporate version.')}for(const link of activity.links)require(link.sourceId===null||coverage.snapshot.sources.some(x=>x.id===link.sourceId),'Mapped source does not resolve in this corporate version.');for(const id of activity.rosterStatement?.coveredEntityIds??[])require(coverage.snapshot.entities.some(x=>x.id===id),'Covered entity does not resolve.');for(const id of activity.rosterStatement?.coveredFacilityIds??[])require(coverage.snapshot.facilities.some(x=>x.id===id),'Covered facility does not resolve.')}
export function m76ValidateCorrection(prior:M76Version|null,activity:M76Activity):void{if(!prior)return;const previous=prior.activity.rosterStatement;if(previous){require(activity.rosterStatement!==null,'A retained declaration cannot be removed.');const current=new Map(activity.rosterStatement!.assets.map(x=>[x.rowId,x]));for(const row of previous.assets){const successor=current.get(row.rowId);require(successor,'Existing equipment rows cannot be removed.');require(row.equipmentId===null||successor!.equipmentId!==null,'Existing physical identity cannot be hidden.');const oldLink=prior.activity.links.find(x=>x.rowId===row.rowId)?.sourceId;require(!oldLink||activity.links.find(x=>x.rowId===row.rowId)?.sourceId,'Existing equipment cannot be unmapped to hide it.')}}}
const supportedGas=(a:M76RosterAsset)=>(a.equipmentType==='boiler'||a.equipmentType==='space_heater')&&a.fuel==='Natural Gas'
const supportedDiesel=(a:M76RosterAsset)=>a.equipmentType==='stationary_emergency_generator'&&a.fuel===M76_DIESEL_FUEL
export function deriveM76RosterFindings(activity:M76Activity,coverage:M71Version):M76Finding[]{
 const out:M76Finding[]=[],add=(code:string,rowKey:string|null,message:string)=>out.push({code,rowKey,message,blocking:true}),s=activity.rosterStatement
 if(!s){add('roster_statement_missing',null,'The independently declared stationary-equipment statement is missing.');return out}if(!activity.manualConfirmation)add('roster_unconfirmed',null,'Confirm the synthetic equipment declaration.');if(!s.assets.length)add('roster_empty',null,'An empty declaration cannot establish zero stationary equipment.');if(s.completeness!=='declared_complete')add('roster_not_declared_complete',null,'The equipment population is partial or unknown.');if(!s.allControlledLocationsIncluded)add('controlled_locations_incomplete',null,'The declaration must cover all controlled locations.');if(m76CanonicalJson(s.coveredEntityIds)!==m76CanonicalJson(coverage.snapshot.entities.map(x=>x.id).sort()))add('entity_population_incomplete',null,'Every corporate entity needs an equipment population declaration.');if(m76CanonicalJson(s.coveredFacilityIds)!==m76CanonicalJson(coverage.snapshot.facilities.map(x=>x.id).sort()))add('facility_population_incomplete',null,'Every corporate facility needs an equipment population declaration.')
 const links=new Map(activity.links.map(x=>[x.rowId,x.sourceId])),identities=new Map<string,string[]>(),sources=new Map<string,string[]>(),meters=new Map<string,string[]>();for(const a of s.assets){const key='roster:'+a.rowId;for(const id of [...(a.equipmentId?[a.equipmentId]:[]),...a.aliases])identities.set(id,[...(identities.get(id)??[]),a.rowId]);const source=links.get(a.rowId);if(source)sources.set(source,[...(sources.get(source)??[]),a.rowId]);const meter=a.meterRelationship;if(meter?.issuer&&meter.meterLabel){const id=m76CanonicalJson([meter.issuer.toLowerCase(),meter.meterLabel.toLowerCase(),a.period]);meters.set(id,[...(meters.get(id)??[]),a.rowId])}if(!a.equipmentId)add('equipment_identity_unknown',key,'Stable physical equipment identity is unknown.');if(!a.entityId||!a.facilityId||!a.period||a.equipmentType==='unknown'||!a.fuel||a.controlBasis==='unknown'||!a.identifierBasis||!a.classificationBasis||!a.controlExplanation)add('equipment_facts_unknown',key,'Required identity, facility, period, classification, fuel or control facts are unknown.');if(a.entityId&&!coverage.snapshot.entities.some(x=>x.id===a.entityId))add('unknown_entity',key,'The declared entity is absent from bound corporate coverage.');if(a.facilityId&&!coverage.snapshot.facilities.some(x=>x.id===a.facilityId&&x.entityId===a.entityId))add('facility_conflict',key,'The declared facility is absent or belongs to another entity.');if(source&&!coverage.snapshot.sources.some(x=>x.id===source&&x.domain==='stationary_combustion'))add('source_conflict',key,'The mapped source is absent or is not stationary combustion.');if(!source)add('source_missing',key,'No corporate stationary source is mapped to this equipment.');if(!meter?.issuer||!meter.meterLabel||!meter.explanation||meter.measurementBasis==='unknown'||meter.dedicatedToSingleDevice===null)add('meter_relationship_unknown',key,'Dedicated consumption evidence identity or relationship is unknown.');if(meter&&(meter.measurementBasis!=='dedicated_single_device_consumption'||meter.dedicatedToSingleDevice!==true)&&meter.measurementBasis!=='unknown')add('meter_relationship_unsupported',key,'Shared, allocated, stock-derived or other evidence relationships remain unsupported.');if(a.equipmentId&&a.equipmentType!=='unknown'&&a.fuel&&a.controlBasis!=='unknown'&&a.period&&(!(supportedGas(a)||supportedDiesel(a))||a.controlBasis!=='owned_operational_control_full_year'||m76CanonicalJson(a.period)!==m76CanonicalJson(M76_PERIOD)))add('equipment_profile_unsupported',key,'The declared equipment, fuel, period or control is outside the current stationary candidate profile.')}
 for(const [id,rows]of identities)if(rows.length>1)for(const row of rows)add('duplicate_equipment_identity','roster:'+row,`Physical identity ${id} appears in multiple equipment rows.`);for(const [id,rows]of sources)if(rows.length>1)for(const row of rows)add('duplicate_source_mapping','roster:'+row,`Stationary source ${id} maps to multiple equipment rows.`);for(const rows of meters.values())if(rows.length>1)for(const row of rows)add('duplicate_meter_relationship','roster:'+row,'The same dedicated meter-period is claimed for multiple equipment rows.');return out
}
export function buildM76Dependencies(coverage:M71Version|null,gas:M73Version[],diesel:M76DieselVersion[],hash:(value:unknown)=>string):M76Dependencies{const pins:M76WorkpaperPin[]=[...gas.map(v=>({family:'natural_gas' as const,worksheetId:v.worksheetId,sourceId:v.activity.binding.sourceId,equipmentId:null,version:{id:v.id,sha256:v.versionSha256},decision:v.review?{id:v.review.id,sha256:v.review.decisionSha256}:null})),...diesel.map(v=>({family:'stationary_diesel' as const,worksheetId:v.worksheetId,sourceId:v.activity.binding.sourceId,equipmentId:v.activity.equipment.assetId,version:{id:v.id,sha256:v.versionSha256},decision:v.review?{id:v.review.id,sha256:v.review.decisionSha256}:null}))].sort((a,b)=>a.family.localeCompare(b.family)||a.worksheetId.localeCompare(b.worksheetId));const value={coveragePin:coverage?{id:coverage.id,sha256:coverage.versionSha256}:null,coverageReviewPin:coverage?.review?{id:coverage.review.id,sha256:coverage.review.decisionSha256}:null,workpaperPins:pins};return {...value,dependencySha256:hash(m76DependencyPayload(value))}}
const rowStatus=(findings:M76Finding[]):M76ReconciliationRow['status']=>{const codes=new Set(findings.filter(x=>x.blocking).map(x=>x.code));if([...codes].some(x=>x.startsWith('duplicate_')))return 'duplicate';if([...codes].some(x=>x.includes('unsupported')||x==='workpaper_family_conflict'))return 'unsupported';if([...codes].some(x=>x.includes('unknown')||x.includes('unconfirmed')))return 'unknown';if(codes.has('orphan_source'))return 'orphan_source';if(codes.has('orphan_workpaper'))return 'orphan_workpaper';if(codes.has('source_missing'))return 'missing_source';if([...codes].some(x=>x.includes('stale')))return 'stale';if(codes.has('capacity_blocked'))return 'capacity_blocked';if(codes.has('workpaper_missing'))return 'missing_workpaper';if(codes.size)return 'workpaper_incomplete';return 'matched_reviewed'}
export function deriveM76Reconciliation(companyId:string,coverage:M71Version|null,gas:M73Version[],diesel:M76DieselVersion[],version:M76Version|null,reviews:M76Review[],hash:(value:unknown)=>string):M76Reconciliation{
 const dependencies=buildM76Dependencies(coverage,gas,diesel,hash),global:M76Finding[]=[],rows:M76ReconciliationRow[]=[],add=(list:M76Finding[],code:string,rowKey:string|null,message:string)=>list.push({code,rowKey,message,blocking:true}),activity=version?.activity,statement=activity?.rosterStatement,links=new Map(activity?.links.map(x=>[x.rowId,x.sourceId])??[]),mappedSources=new Set<string>(),usedWorksheets=new Set<string>(),works=[...gas.map(v=>({family:'natural_gas' as const,v})),...diesel.map(v=>({family:'stationary_diesel' as const,v}))]
 if(!coverage?.review||coverage.review.decision!=='accepted_bounded_internal')add(global,'coverage_review_required',null,'The exact current corporate coverage version needs bounded internal acceptance.');if(!version)add(global,'roster_missing',null,'No independent stationary-equipment declaration has been saved.');else{global.push(...version.findings);if(version.dependencies.dependencySha256!==dependencies.dependencySha256)add(global,'dependency_stale',null,'Corporate coverage or a stationary workpaper/review changed; save a current declaration successor.');if(activity!.coverageVersionId!==coverage?.id||activity!.coverageVersionSha256!==coverage?.versionSha256)add(global,'coverage_stale',null,'The declaration is not bound to current corporate coverage.')}
 const sources=coverage?.snapshot.sources.filter(x=>x.domain==='stationary_combustion')??[],choices=new Map(coverage?m73SourceChoices(coverage).map(x=>[x.binding.sourceId,x]):[])
 for(const a of statement?.assets??[]){const key='roster:'+a.rowId,findings=(version?.findings??[]).filter(x=>x.rowKey===key).map(x=>({...x})),sourceId=links.get(a.rowId)??null,source=sourceId?sources.find(x=>x.id===sourceId):undefined,heads=sourceId?works.filter(x=>x.v.activity.binding.sourceId===sourceId):[];if(sourceId)mappedSources.add(sourceId);for(const h of heads)usedWorksheets.add(h.v.worksheetId);if(sourceId&&!source)add(findings,'source_missing',key,'The mapped stationary source is absent from current corporate coverage.');if(source&&!choices.get(source.id)?.eligible)add(findings,'source_ineligible',key,'The corporate stationary source or boundary is not eligible for the candidate.');if(source){const screening=coverage?.snapshot.coverageItems.find(x=>x.sourceId===source.id&&x.domain==='stationary_combustion');if(!screening||screening.disposition!=='included_activity')add(findings,'source_screening_unresolved',key,'Current stationary-source screening must be included activity; missing, estimate, excluded or not-applicable assertions remain unresolved.')}
 if(!heads.length&&source){if(supportedGas(a)&&gas.length>=3||supportedDiesel(a)&&diesel.length>=1)add(findings,'capacity_blocked',key,'The relevant stationary workpaper capacity is full.');else add(findings,'workpaper_missing',key,'No current compatible stationary workpaper exists for this equipment.')}if(heads.length>1)add(findings,'duplicate_workpaper',key,'Multiple effective workpapers, including cross-family records, map to this stationary source.')
 for(const h of heads){const head=h.v,expectedFamily=supportedGas(a)?'natural_gas':supportedDiesel(a)?'stationary_diesel':null;if(h.family!==expectedFamily)add(findings,'workpaper_family_conflict',key,'Declared equipment/fuel and workpaper family differ.');if(a.entityId!==head.activity.binding.entityId||a.facilityId!==head.activity.binding.facilityId||a.controlBasis!=='owned_operational_control_full_year'||m76CanonicalJson(a.period)!==m76CanonicalJson(head.activity.period))add(findings,'workpaper_fact_conflict',key,'Equipment and workpaper entity, facility, control or period differ.');if(h.family==='stationary_diesel'){const equipment=(head as M76DieselVersion).activity.equipment;if(a.equipmentId!==equipment.assetId||a.identifierBasis!==equipment.identifierBasis||a.equipmentType!==equipment.equipmentType||a.fuel!==equipment.fuel||a.controlBasis!==equipment.controlBasis||a.controlExplanation!==equipment.controlExplanation)add(findings,'workpaper_equipment_conflict',key,'Generator equipment identity, fuel or control facts differ from the declaration.')}const meter=a.meterRelationship,st=head.activity.statement;if(!st||!meter?.issuer||!meter.meterLabel||st.issuer.toLowerCase()!==meter.issuer.toLowerCase()||st.meterLabel.toLowerCase()!==meter.meterLabel.toLowerCase())add(findings,'workpaper_meter_conflict',key,'Declared consumption evidence issuer/meter and retained workpaper evidence differ.');if(!head.calculation||head.findings.some(x=>!['scope1_incomplete','method_not_released'].includes(x.code)))add(findings,'workpaper_incomplete',key,'Current workpaper activity/evidence is missing, discrepant, unsupported or unconfirmed.');if(head.activity.binding.coverageVersionId!==coverage?.id||head.activity.binding.coverageVersionSha256!==coverage?.versionSha256)add(findings,'workpaper_stale',key,'The current workpaper is bound to older corporate coverage.');if(head.review?.decision!=='accepted_bounded_internal')add(findings,'workpaper_review_required',key,'The exact current stationary workpaper needs separate bounded internal acceptance.')}
 rows.push({rowKey:key,rosterRowId:a.rowId,sourceId,equipmentId:a.equipmentId,worksheetIds:heads.map(x=>x.v.worksheetId).sort(),entityLabel:a.entityId?coverage?.snapshot.entities.find(x=>x.id===a.entityId)?.legalName??null:null,facilityLabel:a.facilityId?coverage?.snapshot.facilities.find(x=>x.id===a.facilityId)?.name??null:null,sourceLabel:source?.name??null,status:rowStatus(findings),findings})}
 for(const s of sources.filter(x=>!mappedSources.has(x.id))){const key='source:'+s.id,findings:M76Finding[]=[];add(findings,'orphan_source',key,'Current corporate stationary source is absent from the equipment declaration.');const heads=works.filter(x=>x.v.activity.binding.sourceId===s.id);for(const h of heads)usedWorksheets.add(h.v.worksheetId);if(heads.length>1)add(findings,'duplicate_workpaper',key,'Multiple current workpaper families map to this stationary source.');rows.push({rowKey:key,rosterRowId:null,sourceId:s.id,equipmentId:null,worksheetIds:heads.map(x=>x.v.worksheetId).sort(),entityLabel:coverage?.snapshot.entities.find(x=>x.id===s.entityId)?.legalName??null,facilityLabel:coverage?.snapshot.facilities.find(x=>x.id===s.facilityId)?.name??null,sourceLabel:s.name,status:'orphan_source',findings})}
 for(const h of works.filter(x=>!usedWorksheets.has(x.v.worksheetId))){const w=h.v,key='workpaper:'+w.worksheetId,findings:M76Finding[]=[];add(findings,'orphan_workpaper',key,'Current stationary workpaper is absent from the equipment declaration/source mapping.');rows.push({rowKey:key,rosterRowId:null,sourceId:w.activity.binding.sourceId,equipmentId:h.family==='stationary_diesel'?(w as M76DieselVersion).activity.equipment.assetId:null,worksheetIds:[w.worksheetId],entityLabel:null,facilityLabel:null,sourceLabel:null,status:'orphan_workpaper',findings})}
 rows.sort((a,b)=>a.rowKey.localeCompare(b.rowKey));const allFindings=[...global,...rows.flatMap(x=>x.findings)],currentReview=version?reviews.find(x=>x.versionId===version.id&&x.versionSha256===version.versionSha256&&x.dependencies.dependencySha256===dependencies.dependencySha256):undefined;if(!currentReview||currentReview.decision!=='accepted_bounded_reconciliation')add(allFindings,'roster_review_required',null,'The exact current stationary reconciliation needs independent internal acceptance.');const status:M76Reconciliation['status']=allFindings.every(x=>!x.blocking||x.code==='roster_review_required')&&currentReview?.decision==='accepted_bounded_reconciliation'?'reconciled_bounded_synthetic':'blocked',known=(statement?.assets??[]).map(x=>x.equipmentId).filter((x):x is string=>!!x),base={profile:M76_RECONCILIATION_PROFILE,companyId,period:{...M76_PERIOD},rosterPin:version?{id:version.id,sha256:version.versionSha256}:null,rosterReviewPin:currentReview?{id:currentReview.id,sha256:currentReview.decisionSha256}:null,coveragePin:dependencies.coveragePin,coverageReviewPin:dependencies.coverageReviewPin,workpaperPins:dependencies.workpaperPins,rows,findings:allFindings,counts:{evidenceRows:statement?.assets.length??0,declaredUniqueKnownEquipment:new Set(known).size,currentStationarySources:sources.length,currentWorkpaperStreams:works.length,reconciledRows:rows.filter(x=>x.status==='matched_reviewed').length,blockingFindings:allFindings.filter(x=>x.blocking).length},status,dependencySha256:dependencies.dependencySha256,limitations:[...M76_LIMITATIONS],synthetic:true as const,scope1Completeness:'incomplete' as const,corporateCompleteness:'incomplete' as const,releaseEligible:false as const,assurance:'none' as const,emissionsTotals:null};return {...base,contentSha256:hash(base)}
}
export const deriveM76ReconciliationFromProof=(companyId:string,proof:M76Proof,version:M76Version|null,reviews:M76Review[],hash:(value:unknown)=>string)=>{if(version){const bound=proof.boundCoverageVersion;require(bound&&bound.id===version.activity.coverageVersionId&&bound.versionSha256===version.activity.coverageVersionSha256,'Declaration bound coverage proof does not resolve.');require(m76CanonicalJson(version.findings)===m76CanonicalJson(deriveM76RosterFindings(version.activity,bound!)),'Declaration findings do not match the bound corporate version.')}return deriveM76Reconciliation(companyId,proof.coverageVersion,proof.gasWorkpaperVersions,proof.dieselWorkpaperVersions,version,reviews,hash)}
