import type {M76Reconciliation,M76Review,M76Version} from './m76-contract'
import {m76CanonicalJson} from './m76-validation'

const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
export const M76_REPORT_TEMPLATE=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Synthetic stationary reconciliation</title><style>body{font:16px/1.5 system-ui;margin:2rem auto;padding:0 1rem;max-width:1000px;color:#172f2c;overflow-wrap:anywhere}h1,h2{line-height:1.2}table{border-collapse:collapse;width:100%}th,td{padding:.45rem;text-align:left;vertical-align:top;border-bottom:1px solid #ccd8d0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.5 monospace;background:#f3f6f3;padding:1rem}.blocked{color:#8a281f}@media print{body{font-size:10pt;margin:0;max-width:none}h2{break-after:avoid}tr{break-inside:avoid}}</style></head><body><h1>Stationary equipment reconciliation — synthetic internal draft</h1>{{summary}}<h2>Declared roster evidence</h2>{{evidence}}<h2>Full reconciliation union</h2>{{rows}}<h2>Open findings</h2>{{findings}}<h2>Limitations</h2>{{limitations}}<details><summary>Exact snapshot</summary><pre>{{snapshot}}</pre></details></body></html>`
export const m76ReportSnapshot=(version:M76Version,review:M76Review|null,reconciliation:M76Reconciliation)=>({profile:'m76-stationary-reconciliation-report-v1' as const,version,review,reconciliation})
export function m76RenderReport(snapshot:ReturnType<typeof m76ReportSnapshot>):string{
 const {version,review,reconciliation:r}=snapshot,statement=version.statement,blocked=r.status==='blocked'
 const summary=`<p class="${blocked?'blocked':''}"><strong>${esc(blocked?'Blocked — open findings remain':'Declared synthetic stationary devices reconciled to current internally reviewed workpapers')}</strong></p><p>Company ${esc(r.companyId)} · ${esc(r.period.start)} to ${esc(r.period.endExclusive)} · roster version ${version.version}. Equipment review: ${esc(review?.decision??'unreviewed')}.</p><p>No emissions aggregation. Candidate factors and methods are not released. Scope 1 and the corporate inventory remain incomplete. Requirements are not determined. No external assurance.</p>`
 const evidence=statement?`<dl><dt>Locator</dt><dd>${esc(statement.locator)}</dd><dt>SHA-256</dt><dd>${esc(statement.sha256)}</dd><dt>Issuer / reference</dt><dd>${esc(statement.input.issuer)} / ${esc(statement.input.reference)}</dd><dt>Declaration</dt><dd>${esc(statement.input.completeness)} · all controlled locations ${statement.input.allControlledLocationsIncluded?'included':'not confirmed'}</dd></dl>`:'<p class="blocked">Roster statement missing.</p>'
 const rows=`<table><thead><tr><th>Roster row</th><th>Asset</th><th>Source / workpaper</th><th>Status</th><th>Findings</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td>${esc(x.rosterRowId??'—')}</td><td>${esc(x.equipmentId??'unknown')}</td><td>${esc(x.sourceId??'—')}<br>${x.worksheetIds.map(esc).join('<br>')||'—'}</td><td>${esc(x.status)}</td><td>${x.findings.map(f=>esc(f.message)).join('<br>')||'—'}</td></tr>`).join('')}</tbody></table>`
 const findings=r.findings.length?`<ul>${r.findings.map(f=>`<li>${esc(f.code)}: ${esc(f.message)}</li>`).join('')}</ul>`:'<p>No reconciliation blockers.</p>',limitations=`<ul>${r.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`,exact=esc(m76CanonicalJson(snapshot))
 const slots:Record<string,string>={summary,evidence,rows,findings,limitations,snapshot:exact}
 return M76_REPORT_TEMPLATE.replace(/\{\{(summary|evidence|rows|findings|limitations|snapshot)\}\}/g,(_marker,name:string)=>slots[name]!)
}
