import type {M71Version} from './m71-contract'
import type {M73BindingInput} from './m73-contract'
export const M77_SOURCE_PROFILE='synthetic-fugitive-source-v1' as const
export const M77_POPULATION_PROFILE='synthetic-fugitive-population-v1' as const
export const M77_LIMITATIONS=['synthetic_only','declared_fugitive_reconciliation_only','scope1_incomplete','corporate_inventory_incomplete','factor_and_method_not_released','no_emissions_aggregation','requirements_not_determined','no_external_assurance'] as const
export const M77_MAX_ASSETS=25,M77_MAX_SOURCES=8,M77_MAX_VERSIONS=40,M77_MAX_REPORTS=80,M77_MAX_HISTORY_BYTES=8000000,M77_MAX_RESPONSE_BYTES=10000000
export type M77Family='source'|'population'
export type M77Equipment='fixed_hvac'|'fixed_refrigeration'|'fixed_fire_suppression'|'portable_fire_suppression'|'mobile_hvac'|'mobile_refrigeration'|'other'|'unknown'
export interface M77CalculatorInput {year:2025;asset_id:string;gas:string;equipment:string;unit:'kg';opening_date:'2025-01-01';closing_date:'2025-12-31';opening_capacity:string;closing_capacity:string;declarations:{full_year_operational_control:boolean;california_office_or_distribution:boolean;no_installation_retirement_or_retrofit:boolean;no_stocks_recovery_reuse_or_transfer:boolean;complete_all_provider_service_records:boolean;all_known_releases_recorded:boolean;opening_full_charge_verified:boolean;closing_full_charge_verified:boolean};evidence:{asset_identity:string;capacity:string;opening_full_charge:string;closing_full_charge:string;annual_contractor_record:string};refills:{id:string;date:string;kg:string;contractor:string;reference:string}[];releases:{id:string;date:string;kg:string;evidence:string;refill_id:string;preceded_refill_verified:boolean}[];zero_activity_evidence:string|null;uncertainty:string}
export interface M77Calculation {status:'candidate_method_estimate';method:string;gas:string;gwp:string;gwp_basis:string;factor_locator:string;factor_source_sha256:string;guidance_sha256:string;estimated_emitted_kg:string;kg_co2e_exact:string;kg_co2e_display:string;refill_count:number;known_release_count:number;evidence_verified:false;limitation:string}
export interface M77Authority {calculate(input:M77CalculatorInput):Promise<M77Calculation>;replayBatch(records:{input:M77CalculatorInput;calculation:M77Calculation}[]):Promise<void>}
export interface M77EvidenceInput {reference:string;issuer:string;description:string}
export interface M77EvidenceStatement extends M77EvidenceInput {id:string;locator:string;text:string;sha256:string;byteLength:number}
export interface M77SourceActivity {profile:typeof M77_SOURCE_PROFILE;binding:M73BindingInput;label:string;assetId:string;equipment:M77Equipment;gas:string|null;capacityKg:string|null;calculatorInput:M77CalculatorInput|null;evidenceStatements:M77EvidenceInput[]}
export interface M77PhysicalAsset {assetId:string;entityId:string;facilityId:string|null;equipment:M77Equipment;gas:string|null;capacityKg:string|null;controlBasis:'owned_operational_control_full_year'|'unknown'|'partial_year'|'other';explanation:string;sourceId:string|null}
export interface M77PopulationDeclaration {issuer:string;reference:string;description:string;discoveryBasis:string;completeness:'unknown'|'partial'|'declared_complete';coveredEntityIds:string[];coveredFacilityIds:string[];controlledFleetChecked:boolean;allControlledLocationsIncluded:boolean;assets:M77PhysicalAsset[]}
export interface M77PopulationActivity {profile:typeof M77_POPULATION_PROFILE;coverageVersionId:string;coverageVersionSha256:string;declaration:M77PopulationDeclaration|null}
export interface M77Predecessor {expectedVersionId:string|null;expectedVersionSha256:string|null;correctionReason:string|null;idempotencyKey:string}
export type M77SourceSaveInput=M77SourceActivity&M77Predecessor
export type M77PopulationSaveInput=M77PopulationActivity&M77Predecessor&{expectedDependencySha256:string}
export interface M77Pin {id:string;sha256:string}
export interface M77Dependencies {coveragePin:M77Pin|null;coverageReviewPin:M77Pin|null;workpaperPins:{worksheetId:string;sourceId:string;assetId:string;version:M77Pin;decision:M77Pin|null}[];dependencySha256:string}
export interface M77Finding {code:string;message:string;blocking:true;assetId:string|null;sourceId:string|null}
export interface M77ReviewInput {versionId:string;expectedVersionSha256:string;expectedDependencySha256:string|null;decision:'accepted_bounded_internal'|'accepted_bounded_reconciliation'|'changes_requested';note:string;acknowledgedLimitations:string[];idempotencyKey:string}
export interface M77Review {id:string;versionId:string;versionSha256:string;dependencies:M77Dependencies|null;decision:M77ReviewInput['decision'];note:string;acknowledgedLimitations:string[];reviewerId:string;reviewedAt:string;decisionSha256:string}
export interface M77VersionBase {id:string;companyId:string;streamId:string;family:M77Family;version:number;previousVersionId:string|null;previousVersionSha256:string|null;createdBy:string;createdAt:string;contributorIds:string[];correctionReason:string|null;coverageVersion:M71Version;statements:M77EvidenceStatement[];dependencies:M77Dependencies|null;findings:M77Finding[];inputSha256:string;contentSha256:string;versionSha256:string;synthetic:true;scope1Completeness:'incomplete';corporateCompleteness:'incomplete';releaseEligible:false;assurance:'none';emissionsTotals:null;review:M77Review|null}
export interface M77SourceVersion extends M77VersionBase {family:'source';activity:M77SourceActivity;calculation:M77Calculation|null}
export interface M77PopulationVersion extends M77VersionBase {family:'population';activity:M77PopulationActivity;calculation:null}
export type M77Version=M77SourceVersion|M77PopulationVersion
export interface M77ReportInput {versionId:string;expectedVersionSha256:string;expectedDecisionId:string|null;expectedDecisionSha256:string|null;expectedReconciliationSha256:string|null;idempotencyKey:string}
export interface M77Report {id:string;companyId:string;streamId:string;family:M77Family;versionId:string;versionSha256:string;createdBy:string;createdAt:string;rendererVersion:'m77-retained-report-v1';snapshotJson:string;snapshotSha256:string;html:string;htmlSha256:string;htmlByteLength:number;reportSha256:string}
export interface M77Reconciliation {companyId:string;dependencies:M77Dependencies;dependencySha256:string;populationVersionPin:M77Pin|null;reviewPin:M77Pin|null;status:'blocked'|'reconciled_bounded_synthetic';findings:M77Finding[];assets:M77PhysicalAsset[];sourceIds:string[];worksheetIds:string[];emissionsTotals:null;scope1Completeness:'incomplete';corporateCompleteness:'incomplete';releaseEligible:false;assurance:'none';limitations:string[];contentSha256:string}
export interface M77Worksheet {worksheetId:string;sourceId:string;assetId:string;headVersionId:string;versions:M77SourceVersion[];reports:M77Report[]}
export interface M77SourceChoice {binding:M73BindingInput;companyLabel:string;entityLabel:string;facilityLabel:string;sourceLabel:string;eligible:boolean;findings:M77Finding[]}
export interface M77Register {profile:'synthetic-fugitive-register-v1';companyId:string;coverageHeadVersionId:string|null;coverageVersion:M71Version|null;sources:M77SourceChoice[];worksheets:M77Worksheet[];population:{rosterId:string|null;headVersionId:string|null;versions:M77PopulationVersion[];reports:M77Report[]};reconciliation:M77Reconciliation;limitations:string[]}
export interface M77ReportSnapshot {profile:'m77-report-snapshot-v1';version:M77Version;review:M77Review|null;reconciliation:M77Reconciliation|null;proof:{coverageVersion:M71Version|null;workpaperVersions:M77SourceVersion[]}|null;limitations:string[]}

