import type {M77ReportSnapshot} from './m77-contract'
import {m77CanonicalJson} from './m77-validation'
const escape=(v:unknown)=>String(v??'Unknown').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')
const readable=(v:string)=>({fixed_hvac:'Fixed air conditioning',fixed_refrigeration:'Fixed refrigeration',fixed_fire_suppression:'Fixed fire suppression',portable_fire_suppression:'Portable fire suppression',mobile_hvac:'Vehicle air conditioning',mobile_refrigeration:'Refrigerated transport',owned_operational_control_full_year:'Owned and controlled throughout the year',partial_year:'Partial year — unsupported',other:'Other — unsupported',unknown:'Unknown',accepted_bounded_internal:'Accepted for this internal workpaper',accepted_bounded_reconciliation:'Accepted for this equipment reconciliation',changes_requested:'Changes requested',unreviewed:'Not reviewed'} as Record<string,string>)[v]??v
export function m77RenderReport(s:M77ReportSnapshot):string{
 const v=s.version,title=v.family==='source'?'Fugitive source workpaper':'Physical fugitive population reconciliation',status=v.family==='source'?(v.calculation?'Candidate method estimate':'Blocked — incomplete or unsupported method facts'):(s.reconciliation?.status==='reconciled_bounded_synthetic'?'Declared synthetic population reconciled':'Blocked — open reconciliation findings'),findings=s.reconciliation?.findings??v.findings;
 const number=v.family==='source'&&v.calculation?'<p>Gas '+escape(v.calculation.gas)+' · estimated emitted kg '+escape(v.calculation.estimated_emitted_kg)+' · kg CO2e '+escape(v.calculation.kg_co2e_display)+' (half-even, four decimals). Candidate AR5 GWP '+escape(v.calculation.gwp)+'. Known releases are already reconciled inside refill activity and are not added again.</p>':'';
 const statementLinks=v.statements.map(x=>'<li><a href="#evidence-'+escape(x.id)+'">'+escape(x.reference)+'</a> — '+escape(x.issuer)+' · '+escape(x.locator)+' · SHA-256 '+escape(x.sha256)+'</li>').join('');
 const evidenceSections=v.statements.map(x=>'<section id="evidence-'+escape(x.id)+'"><h3>'+escape(x.reference)+' · '+escape(x.issuer)+'</h3><p>'+escape(x.description)+'</p><details><summary>Exact retained statement</summary><pre>'+escape(x.text)+'</pre></details></section>').join('');
 const label=v.family==='source'?v.activity.label:'Independent physical discovery',company=(s.proof?.coverageVersion??v.coverageVersion).snapshot.companyLabel;
 const assetRows=(s.reconciliation?.assets??[]).map(a=>'<tr><td data-label="Asset">'+escape(a.assetId)+'</td><td data-label="Equipment">'+escape(readable(a.equipment))+'</td><td data-label="Gas">'+escape(a.gas)+'</td><td data-label="Charge kg">'+escape(a.capacityKg)+'</td><td data-label="Corporate source">'+escape((s.proof?.coverageVersion??v.coverageVersion).snapshot.sources.find(x=>x.id===a.sourceId)?.name??a.sourceId)+'</td><td data-label="Control">'+escape(readable(a.controlBasis))+'</td></tr>').join('');
 return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; base-uri \'none\'; form-action \'none\'"><title>'+title+'</title><style>body{font:16px/1.5 system-ui;margin:2rem auto;padding:0 1rem;max-width:1000px;color:#172f2c;overflow-wrap:anywhere}table{border-collapse:collapse;width:100%}th,td{padding:.4rem;text-align:left;border-bottom:1px solid #ccd8d0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.5 monospace;background:#f3f6f3;padding:1rem}@media(max-width:600px){thead{display:none}tr{display:block;margin:.8rem 0}td{display:block}td::before{content:attr(data-label);font-weight:600;margin-right:.5rem}}@media print{body{font-size:10pt;margin:0}tr{break-inside:avoid}}</style></head><body><h1>'+title+' — synthetic internal draft</h1><p>Company '+escape(company)+' · '+escape(label)+'</p><p>'+escape(status)+'</p><p>Calendar 2025 · version '+v.version+' · internal review: '+escape(readable(s.review?.decision??'unreviewed'))+'.</p><p>No complete Scope 1 or corporate inventory claim. Candidate methods and factors are not released. Requirements are not determined. No external assurance. No emissions aggregation.</p>'+number+'<h2>Retained evidence</h2><ul>'+statementLinks+'</ul>'+evidenceSections+'<h2>Physical devices</h2><table><thead><tr><th>Asset</th><th>Equipment</th><th>Gas</th><th>Charge kg</th><th>Corporate source</th><th>Control</th></tr></thead><tbody>'+assetRows+'</tbody></table><h2>Open findings</h2><ul>'+findings.map(f=>'<li>'+escape(f.message)+'</li>').join('')+'</ul><details><summary>Exact retained data and provenance</summary><pre>'+escape(m77CanonicalJson(s))+'</pre></details></body></html>'
}
