import {m71CanonicalJson,m71Keys,m71Uuid,m71HashString} from './m71-validation'
import {M78_CATEGORIES,M78_GAS_GROUPS,M78_PERIOD,M78_PROCESS_PROFILE,M78_INVENTORY_PROFILE,M78_LIMITATIONS,M78_MAX_ACTIVITY_BYTES,type M78ProcessActivity,type M78InventoryActivity,type M78ProcessSaveInput,type M78InventorySaveInput,type M78ReviewInput,type M78ReportInput,type M78Version,type M78Review,type M78Report,type M78EvidenceInput,type M78Finding,type M78Dependencies} from './m78-contract'
import {parseM77Json} from './m77-validation'
import type {M71Version} from './m71-contract'
export const m78CanonicalJson=m71CanonicalJson
export function m78Keys(v:unknown,keys:string[]):asserts v is Record<string,unknown>{try{m71Keys(v,keys)}catch{m78Fail('Exact Scope 1 field set required.')}}
export class M78ValidationError extends Error {}
export function m78Fail(message:string):never {throw new M78ValidationError(message)}
export const m78Text=(v:unknown,max=2000,min=1):string=>{if(typeof v!=='string'||v!==v.trim()||v!==v.normalize('NFC')||v.length<min||v.length>max||/[\x00-\x1f\x7f]/.test(v))m78Fail('Canonical descriptive text required.');return v}
const uuid=(v:unknown)=>{if(!m71Uuid(v))m78Fail('UUID required.');return v}
const hash=(v:unknown)=>{if(!m71HashString(v))m78Fail('SHA-256 required.');return v}
const ident=(v:unknown)=>{const s=m78Text(v,80);if(!/^[A-Z0-9][A-Z0-9._-]*$/.test(s))m78Fail('Canonical evidence/source identifier required.');return s}
function list(v:unknown,max:number):unknown[]{if(!Array.isArray(v)||v.length>max)m78Fail('Collection capacity exceeded.');return v}
function unique(v:string[]){if(new Set(v).size!==v.length)m78Fail('Duplicate identifiers are not supported.');return [...v].sort()}
function refs(v:unknown){return unique(list(v,100).map(ident))}
function binding(v:unknown){m78Keys(v,['coverageVersionId','coverageVersionSha256','processCoverageItemId','period']);uuid(v.coverageVersionId);hash(v.coverageVersionSha256);uuid(v.processCoverageItemId);if(m78CanonicalJson(v.period)!==m78CanonicalJson(M78_PERIOD))m78Fail('Only full calendar 2025 is admitted.');return v}
function date(v:unknown){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)m78Fail('Real evidence date required.');return v}
const predKeys=['expectedVersionId','expectedVersionSha256','expectedDependencySha256','correctionReason','idempotencyKey']
function predecessor(v:Record<string,unknown>){uuid(v.idempotencyKey);hash(v.expectedDependencySha256);if(v.expectedVersionId===null){if(v.expectedVersionSha256!==null||v.correctionReason!==null)m78Fail('First save cannot carry predecessor pins.')}else{uuid(v.expectedVersionId);hash(v.expectedVersionSha256);m78Text(v.correctionReason,500)}}
export function parseM78Json(s:string,max=6000000):unknown{try{return parseM77Json(s,max)}catch{m78Fail('Invalid or duplicate-key Scope 1 JSON.')}}
export function validateM78ProcessSave(value:unknown):M78ProcessSaveInput {
 m78Keys(value,['profile','binding','declaration','locations','assessments','gasCoverage','evidenceStatements','manualConfirmation',...predKeys]);predecessor(value);const v=structuredClone(value) as unknown as M78ProcessSaveInput;if(v.profile!==M78_PROCESS_PROFILE)m78Fail('Process-screen profile required.');binding(v.binding);if(typeof v.manualConfirmation!=='boolean')m78Fail('Explicit confirmation required.');
 if(v.declaration!==null){const d=v.declaration;m78Keys(d,['completeness','coveredEntityIds','coveredFacilityIds','allControlledOperationsIncluded','discoveryBasis']);if(!['unknown','partial','declared_complete'].includes(d.completeness)||typeof d.allControlledOperationsIncluded!=='boolean')m78Fail('Explicit discovery status required.');d.coveredEntityIds=unique(list(d.coveredEntityIds,150).map(uuid));d.coveredFacilityIds=unique(list(d.coveredFacilityIds,150).map(uuid));m78Text(d.discoveryBasis,2000,20)}
 for(const x of list(v.locations,25)){m78Keys(x,['rowId','entityId','facilityId','operationId','businessActivities','equipmentAndMaterials','controlExplanation','evidenceReferences']);uuid(x.rowId);uuid(x.entityId);if(x.facilityId!==null)uuid(x.facilityId);if(x.operationId!==null)ident(x.operationId);if((x.facilityId===null)===(x.operationId===null))m78Fail('Location requires a retained facility or explicit non-facility operation.');m78Text(x.businessActivities);m78Text(x.equipmentAndMaterials);m78Text(x.controlExplanation);x.evidenceReferences=refs(x.evidenceReferences)}unique(v.locations.map(x=>x.rowId));v.locations.sort((a,b)=>a.rowId.localeCompare(b.rowId));
 for(const x of list(v.assessments,100)){m78Keys(x,['rowId','category','discoveredSourceId','locationRowIds','disposition','reason','evidenceReferences']);uuid(x.rowId);if(!M78_CATEGORIES.includes(x.category as any)||!['unknown','indicated','not_applicable_proposed'].includes(x.disposition as string))m78Fail('Unsupported process assessment.');if(x.discoveredSourceId!==null)ident(x.discoveredSourceId);if(x.disposition==='indicated'&&x.discoveredSourceId===null)m78Fail('Indicated sources need stable identities.');if(x.disposition!=='indicated'&&x.discoveredSourceId!==null)m78Fail('Previously indicated sources remain indicated and unsupported.');x.locationRowIds=unique(list(x.locationRowIds,25).map(uuid));if(x.reason!==null)m78Text(x.reason);x.evidenceReferences=refs(x.evidenceReferences)}unique(v.assessments.map(x=>x.rowId));unique(v.assessments.filter(x=>x.discoveredSourceId!==null).map(x=>x.discoveredSourceId!));v.assessments.sort((a,b)=>a.rowId.localeCompare(b.rowId));
 for(const x of list(v.gasCoverage,7)){m78Keys(x,['gasGroup','state','sourceIds','discoveredSourceIds','locationRowIds','reason','evidenceReferences']);if(!M78_GAS_GROUPS.includes(x.gasGroup as any)||!['unknown','indicated','not_applicable_proposed','covered_by_sources'].includes(x.state as string))m78Fail('Seven-gas applicability state required.');x.sourceIds=unique(list(x.sourceIds,150).map(uuid));x.discoveredSourceIds=unique(list(x.discoveredSourceIds,100).map(ident));x.locationRowIds=unique(list(x.locationRowIds,25).map(uuid));x.evidenceReferences=refs(x.evidenceReferences);if(x.reason!==null)m78Text(x.reason);if(x.state==='covered_by_sources'&&!(x.sourceIds as string[]).length||x.state==='indicated'&&!(x.discoveredSourceIds as string[]).length||x.state!=='indicated'&&(x.discoveredSourceIds as string[]).length||x.state==='not_applicable_proposed'&&(x.sourceIds as string[]).length)m78Fail('Gas applicability conflicts with declared sources.')}unique(v.gasCoverage.map(x=>x.gasGroup));if(v.gasCoverage.length!==7)m78Fail('All seven gas groups require explicit assessment.');v.gasCoverage.sort((a,b)=>a.gasGroup<b.gasGroup?-1:1);
 for(const x of list(v.evidenceStatements,100)){m78Keys(x,['reference','issuer','description','issuedOn','purpose','entityId','facilityId']);ident(x.reference);m78Text(x.issuer,120);m78Text(x.description,2000,20);date(x.issuedOn);if(!['business_activity','process_inspection','offsite_discovery'].includes(x.purpose as string))m78Fail('Evidence purpose required.');uuid(x.entityId);if(x.facilityId!==null)uuid(x.facilityId)}unique(v.evidenceStatements.map(x=>x.reference));v.evidenceStatements.sort((a,b)=>a.reference.localeCompare(b.reference));
 if(new TextEncoder().encode(m78CanonicalJson(v)).length>M78_MAX_ACTIVITY_BYTES)m78Fail('Process activity exceeds capacity.');return v
}
export function validateM78InventorySave(value:unknown):M78InventorySaveInput{m78Keys(value,['profile','binding','note',...predKeys]);predecessor(value);if(value.profile!==M78_INVENTORY_PROFILE)m78Fail('Inventory profile required.');binding(value.binding);m78Text(value.note,2000);return structuredClone(value) as unknown as M78InventorySaveInput}
export function validateM78Review(value:unknown):M78ReviewInput{m78Keys(value,['versionId','expectedVersionSha256','expectedDependencySha256','decision','note','acknowledgedLimitations','idempotencyKey']);uuid(value.versionId);hash(value.expectedVersionSha256);hash(value.expectedDependencySha256);uuid(value.idempotencyKey);m78Text(value.note,2000);if(!['accepted_bounded_process_screen','accepted_bounded_inventory','changes_requested'].includes(value.decision as string)||m78CanonicalJson(value.acknowledgedLimitations)!==m78CanonicalJson(M78_LIMITATIONS))m78Fail('Exact bounded review and limitations required.');return structuredClone(value) as unknown as M78ReviewInput}
export function validateM78Report(value:unknown):M78ReportInput{m78Keys(value,['versionId','expectedVersionSha256','expectedDecisionId','expectedDecisionSha256','expectedReconciliationSha256','idempotencyKey']);uuid(value.versionId);hash(value.expectedVersionSha256);uuid(value.idempotencyKey);if(value.expectedDecisionId!==null){uuid(value.expectedDecisionId);hash(value.expectedDecisionSha256)}else if(value.expectedDecisionSha256!==null)m78Fail('Absent review requires absent hash.');if(value.expectedReconciliationSha256!==null)hash(value.expectedReconciliationSha256);return structuredClone(value) as unknown as M78ReportInput}
export function m78ProcessActivity(v:M78ProcessSaveInput):M78ProcessActivity{const {expectedVersionId:_,expectedVersionSha256:__,expectedDependencySha256:___,correctionReason:____,idempotencyKey:_____,...a}=v;return a}
export function m78InventoryActivity(v:M78InventorySaveInput):M78InventoryActivity{const {expectedVersionId:_,expectedVersionSha256:__,expectedDependencySha256:___,correctionReason:____,idempotencyKey:_____,...a}=v;return a}
export function m78ValidateProcessCorrection(prior:M78ProcessActivity|null,next:M78ProcessActivity){for(const a of prior?.assessments.filter(a=>a.discoveredSourceId!==null)??[]){const n=next.assessments.find(n=>n.discoveredSourceId===a.discoveredSourceId);if(!n||n.disposition!=='indicated'||n.category!==a.category)m78Fail('Previously discovered process sources cannot be removed, renamed or reassigned.')}for(const g of prior?.gasCoverage??[]){const nextGroup=next.gasCoverage.find(n=>n.gasGroup===g.gasGroup);if(g.discoveredSourceIds.some(id=>!nextGroup?.discoveredSourceIds.includes(id)))m78Fail('Previously indicated gas sources cannot be removed or reclassified.')}for(const l of prior?.locations??[]){const n=next.locations.find(n=>n.rowId===l.rowId);if(!n||n.entityId!==l.entityId||n.facilityId!==l.facilityId||n.operationId!==l.operationId)m78Fail('Previously discovered location/operation identities must remain retained.')}}
export function m78Finding(code:string,message:string,recordId:string|null=null,family='m78',classification:M78Finding['classification']='functional_blocker',resolution:M78Finding['resolution']=null):M78Finding{return {code,origin:{family,recordId,originalCode:code},classification,message,resolution}}
export function deriveM78ProcessFindings(a:M78ProcessActivity,c:M71Version):M78Finding[]{const out:M78Finding[]=[],add=(s:string,m:string,id:string|null=null)=>out.push(m78Finding(s,m,id,'process_screen')),d=a.declaration;if(!d||d.completeness!=='declared_complete'||!d.allControlledOperationsIncluded||!a.manualConfirmation)add('process_discovery_incomplete','Complete discovery and evidence confirmation are required.');if(d&&(m78CanonicalJson([...d.coveredEntityIds].sort())!==m78CanonicalJson(c.snapshot.entities.map(e=>e.id).sort())||m78CanonicalJson([...d.coveredFacilityIds].sort())!==m78CanonicalJson(c.snapshot.facilities.map(f=>f.id).sort())))add('process_scope_incomplete','Discovery must cover every retained entity and location.');for(const f of c.snapshot.facilities)if(!a.locations.some(l=>l.facilityId===f.id&&l.entityId===f.entityId))add('process_location_missing','Retained location has no process inspection.',f.id);
 const evidence=new Map(a.evidenceStatements.map(e=>[e.reference,e]));for(const e of a.evidenceStatements){if(!c.snapshot.entities.some(x=>x.id===e.entityId)||e.facilityId!==null&&!c.snapshot.facilities.some(f=>f.id===e.facilityId&&f.entityId===e.entityId))add('process_evidence_location_unknown','Statement location does not resolve.',e.reference)}for(const l of a.locations){if(!c.snapshot.entities.some(e=>e.id===l.entityId)||l.facilityId!==null&&!c.snapshot.facilities.some(f=>f.id===l.facilityId&&f.entityId===l.entityId))add('process_location_unknown','Inspection location does not resolve.',l.rowId);const entries=l.evidenceReferences.map(r=>evidence.get(r));if(!entries.length||entries.some(e=>!e||e.entityId!==l.entityId||e.facilityId!==l.facilityId)||!entries.some(e=>e?.purpose==='business_activity')||!entries.some(e=>e?.purpose===(l.facilityId===null?'offsite_discovery':'process_inspection')))add('process_location_evidence_missing','Inspection requires retained activity and location-matched discovery evidence.',l.rowId)}
 for(const e of c.snapshot.entities)if(!a.evidenceStatements.some(s=>s.entityId===e.id&&s.facilityId===null&&s.purpose==='offsite_discovery'))add('process_offsite_evidence_missing','Every entity needs explicit controlled non-facility discovery evidence.',e.id);
 for(const category of M78_CATEGORIES){const group=a.assessments.filter(x=>x.category===category&&x.discoveredSourceId===null);if(group.length!==1||m78CanonicalJson(group[0]?.locationRowIds)!==m78CanonicalJson(a.locations.map(x=>x.rowId).sort()))add('process_category_scope_incomplete','Every category requires one full-discovery assessment.',category)}for(const x of a.assessments){if(x.disposition!=='not_applicable_proposed')add(x.disposition==='indicated'?'process_method_unsupported':'process_applicability_unknown','Process applicability or indicated method remains unresolved.',x.discoveredSourceId??x.rowId);if(!x.reason||!x.evidenceReferences.length||x.evidenceReferences.some(r=>!evidence.has(r))||x.locationRowIds.some(r=>!a.locations.some(l=>l.rowId===r)))add('process_assessment_evidence_missing','Assessment rationale and references must resolve.',x.rowId);for(const id of x.locationRowIds){const l=a.locations.find(l=>l.rowId===id);if(l&&!x.evidenceReferences.some(r=>{const e=evidence.get(r);return e?.entityId===l.entityId&&e.facilityId===l.facilityId&&e.purpose===(l.facilityId===null?'offsite_discovery':'process_inspection')}))add('process_assessment_location_evidence_missing','Assessment lacks inspected-location support.',x.rowId)}}for(const g of a.gasCoverage){if(g.state==='unknown'||g.state==='indicated')add(g.state==='unknown'?'gas_applicability_unknown':'indicated_gas_source_unsupported','Gas applicability or indicated source is unresolved.',g.gasGroup);if(!g.reason||m78CanonicalJson(g.locationRowIds)!==m78CanonicalJson(a.locations.map(l=>l.rowId).sort())||g.evidenceReferences.some(r=>!evidence.has(r))||g.sourceIds.some(id=>!c.snapshot.sources.some(s=>s.id===id&&['stationary_combustion','mobile_combustion','fugitive','process'].includes(s.domain))))add('gas_scope_evidence_missing','Every gas group needs exact source and full-discovery evidence.',g.gasGroup);for(const e of c.snapshot.entities)if(!g.evidenceReferences.some(r=>{const s=evidence.get(r);return s?.entityId===e.id&&s.facilityId===null&&s.purpose==='offsite_discovery'}))add('gas_offsite_evidence_missing','Gas scope requires explicit non-facility discovery evidence for every entity.',g.gasGroup);for(const l of a.locations)if(!g.evidenceReferences.some(r=>{const e=evidence.get(r);return e?.entityId===l.entityId&&e.facilityId===l.facilityId&&e.purpose===(l.facilityId===null?'offsite_discovery':'process_inspection')}))add('gas_location_evidence_missing','Gas applicability lacks retained inspected-location support.',g.gasGroup)}for(const s of c.snapshot.sources.filter(s=>s.domain==='process'))add('corporate_process_source_unsupported','Corporate process source requires a supported method.',s.id);return out}
export const m78InputHashPayload=(v:M78Version)=>v.activity
export const m78ContentHashPayload=(v:M78Version)=>({activity:v.activity,dependencies:v.dependencies,statements:v.statements,findings:v.findings,reconciliation:v.reconciliation})
export const m78VersionHashPayload=(v:M78Version)=>{const {versionSha256:_,review:__,...body}=v;return body}
export const m78ReviewHashPayload=(companyId:string,r:M78Review)=>{const {decisionSha256:_,...body}=r;return {companyId,...body}}
export const m78ReportHashPayload=(r:M78Report)=>{const {html:_,snapshotJson:__,reportSha256:___,...body}=r;return body}
export const m78EvidenceText=(companyId:string,e:M78EvidenceInput)=>'SYNTHETIC — NOT ORIGINAL CUSTOMER EVIDENCE\n'+m78CanonicalJson({companyId,year:2025,...e})+'\n'
export function m78BindingValid(a:M78ProcessActivity|M78InventoryActivity,c:M71Version){const b=a.binding;return b.coverageVersionId===c.id&&b.coverageVersionSha256===c.versionSha256&&m78CanonicalJson(b.period)===m78CanonicalJson(c.snapshot.period)&&c.snapshot.coverageItems.some(x=>x.id===b.processCoverageItemId&&x.domain==='process'&&x.entityId===null&&x.sourceId===null)}
export function m78DependencyEquals(a:M78Dependencies,b:M78Dependencies){return m78CanonicalJson(a)===m78CanonicalJson(b)}
