import type {M71Version} from '../../../../packages/neuvetra-database/src/m71-contract'
import {test,expect} from 'bun:test'
import {decodeGasVersion,decodeGasReport,gasRegisterRequest} from './m73-api'
import {coverageSha256,syntheticCoverageReference} from './m71-api'
import {createM73Authority} from '../../../site-api/src/calculation/m73-authority'
import {M73_PROFILE,M73_PERIOD,type M73Version,type M73Report} from '../../../../packages/neuvetra-database/src/m73-contract'
import {m73CanonicalJson,m73ContentPayload,m73VersionHashPayload,m73StatementText,m73SourceChoices,m73CalculationHashPayload,m73ReportHashPayload} from '../../../../packages/neuvetra-database/src/m73-validation'
import {m73ReportSnapshot,m73RenderReport} from '../../../../packages/neuvetra-database/src/m73-report'
import {m71VersionHashPayload,deriveM71Findings,validateM71Snapshot} from '../../../../packages/neuvetra-database/src/m71-validation'
const hash=(v:unknown)=>coverageSha256(m73CanonicalJson(v))
const native=await Bun.file(new URL('../../../../evaluations/research-qa/m71-qa-native-fixture.json',import.meta.url)).json()
async function rehash(v:M73Version){v.inputSha256=await hash(v.activity);v.contentSha256=await hash(m73ContentPayload(v));v.versionSha256=await hash(m73VersionHashPayload(v));return v}
async function fixture(quantity='1250.125'){
 const coverage=structuredClone(native.register.versions[0]) as M71Version;coverage.review=null
 const f=coverage.snapshot.facilities[0],sourceId=crypto.randomUUID();const ref=await syntheticCoverageReference()
 const boundary=coverage.snapshot.boundaryDecisions.find(b=>b.entityId===f.entityId)!;boundary.disposition='included_activity';boundary.reason='Fictional parent operational-control basis';boundary.evidenceRefs=[ref]
 coverage.snapshot.sources.push({id:sourceId,entityId:f.entityId,facilityId:f.id,name:'Synthetic gas test source',domain:'stationary_combustion',...M73_PERIOD,evidenceRefs:[]})
 coverage.snapshot.coverageItems.push({id:crypto.randomUUID(),domain:'stationary_combustion',entityId:f.entityId,sourceId,...M73_PERIOD,disposition:'missing',activityDataState:'missing',evidenceState:'missing',methodReadiness:'candidate',reason:null,evidenceRefs:[],estimateBasis:null,quantity:null,unit:null})
 coverage.snapshot=validateM71Snapshot(coverage.snapshot);coverage.findings=deriveM71Findings(coverage.snapshot);coverage.contentSha256=await hash(coverage.snapshot);coverage.versionSha256=await hash(m71VersionHashPayload(coverage))
 const activity={profile:M73_PROFILE,binding:m73SourceChoices(coverage)[0]!.binding,period:M73_PERIOD,fuel:'Natural Gas' as const,heatBasis:'HHV' as const,unit:'MMBtu' as const,quantityMmbtu:quantity,statement:{issuer:'Synthetic supplier',reference:'Annual 2025',meterLabel:'Dedicated boiler',statedQuantityMmbtu:quantity,description:'Fictional dedicated-meter consumption without adjustments',consumptionBasis:'dedicated_meter_consumed_no_adjustments' as const},manualConfirmation:true,discrepancyReason:null,zeroReason:null}
 const sid=crypto.randomUUID(),text=m73StatementText(activity,coverage),statement={id:sid,profile:'m73-synthetic-gas-statement-v1' as const,input:activity.statement,locator:`m73-statement:${sid}:annual-activity`,text,sha256:await coverageSha256(text),byteLength:new TextEncoder().encode(text).length}
 const calculation=await createM73Authority().calculate({binding:activity.binding,period:M73_PERIOD,fuel:activity.fuel,heatBasis:activity.heatBasis,unit:activity.unit,quantityMmbtu:quantity,statementSha256:statement.sha256})
 const {deriveM73Findings}=await import('../../../../packages/neuvetra-database/src/m73-validation')
 return rehash({id:crypto.randomUUID(),companyId:native.company,worksheetId:crypto.randomUUID(),version:1,previousVersionId:null,previousVersionSha256:null,createdBy:coverage.createdBy,createdAt:'2026-09-15T16:00:00.000Z',contributorIds:coverage.contributorIds,correctionReason:null,activity,coverageVersion:coverage,statement,calculation,findings:deriveM73Findings(activity),inputSha256:'',contentSha256:'',versionSha256:'',synthetic:true,scope1Completeness:'incomplete',corporateCompleteness:'incomplete',releaseEligible:false,assurance:'none',review:null})
}
test('real Python result passes browser decoding with precise maximum and rounding ties',async()=>{for(const [quantity,exact,display]of [['1250.125','66399.7643125','66399.7643'],['0.100','5.31145','5.3114'],['0.300','15.93435','15.9344'],['999999999999.999','53114499999999.9468855','53114499999999.9469']]){const v=await fixture(quantity);await decodeGasVersion(v,v.companyId);expect(v.calculation!.total.unrounded).toBe(exact);expect(v.calculation!.total.display).toBe(display)}})
test('self-consistent altered method and statement bytes do not replace trusted bindings',async()=>{const original=await fixture();for(const mutate of [(v:M73Version)=>{v.calculation!.method.sourceSha256='a'.repeat(64)},(v:M73Version)=>{v.statement!.text+='UNTRUSTED'},(v:M73Version)=>{v.activity.binding.sourceId=crypto.randomUUID()},(v:M73Version)=>{v.scope1Completeness='complete' as unknown as 'incomplete'}]){const v=structuredClone(original);mutate(v);if(v.statement){v.statement.sha256=await coverageSha256(v.statement.text);v.statement.byteLength=new TextEncoder().encode(v.statement.text).length}if(v.calculation)v.calculation.resultSha256=await hash(m73CalculationHashPayload(v.calculation));await rehash(v);await expect(decodeGasVersion(v,v.companyId)).rejects.toThrow('could not be verified')}})
test('retained report must regenerate from the captured version even if all HTML hashes agree',async()=>{const v=await fixture(),snapshot=m73ReportSnapshot(v,null),html=m73RenderReport(snapshot),r:M73Report={id:crypto.randomUUID(),companyId:v.companyId,worksheetId:v.worksheetId,versionId:v.id,versionSha256:v.versionSha256,decisionId:null,decisionSha256:null,createdBy:v.createdBy,createdAt:v.createdAt,rendererVersion:'m73-source-report-v1',html,htmlSha256:await coverageSha256(html),htmlByteLength:new TextEncoder().encode(html).length,snapshotJson:m73CanonicalJson(snapshot),snapshotSha256:await hash(snapshot),reportSha256:''};r.reportSha256=await hash(m73ReportHashPayload(r));expect(await decodeGasReport(r,v.companyId,v)).toEqual(r);r.html=r.html.replace('Corporate inventory incomplete','Corporate inventory complete');r.htmlSha256=await coverageSha256(r.html);r.htmlByteLength=new TextEncoder().encode(r.html).length;r.reportSha256=await hash(m73ReportHashPayload(r));await expect(decodeGasReport(r,v.companyId,v)).rejects.toThrow('could not be verified')})
test('aborted response and private server text never reach the public source state',async()=>{const original=globalThis.fetch,controller=new AbortController(),actor={userId:native.actorIds.owner,accessToken:'synthetic-test',role:'owner' as const,signal:controller.signal};try{globalThis.fetch=(async()=>({status:200,ok:true,text:async()=>{controller.abort();return '{}'}} as Response)) as typeof fetch;await expect(gasRegisterRequest(actor,native.company)).rejects.toMatchObject({name:'AbortError'});globalThis.fetch=(async()=>Response.json({error:'PRIVATE UNTRUSTED DETAIL'},{status:503})) as typeof fetch;await expect(gasRegisterRequest({...actor,signal:undefined},native.company)).rejects.toThrow('Stationary source data is unavailable')}finally{globalThis.fetch=original}})
