import { m73RenderReport, m73ReportSnapshot } from '../../../../packages/neuvetra-database/src/m73-report'
import type { HostedWorkspaceActor } from './workspace-api'
import { coverageSha256, decodeCorporateVersion } from './m71-api'
import { m71Keys, m71Uuid, m71HashString, parseM71Json } from '../../../../packages/neuvetra-database/src/m71-validation'
import { M73_PROFILE,M73_METHOD,M73_LIMITATIONS,M73_MAX_RESPONSE_BYTES,M73_MAX_STREAMS,M73_MAX_VERSIONS,type M73Version,type M73Register,type M73Review,type M73Report,type M73SaveInput,type M73ReviewInput,type M73ReportInput } from '../../../../packages/neuvetra-database/src/m73-contract'
import { m73CanonicalJson,validateM73Save,m73Activity,m73InputHashPayload,m73ContentPayload,m73VersionHashPayload,m73ReviewHashPayload,m73ReportHashPayload,m73CalculationHashPayload,m73StatementText,m73ResolveBinding,deriveM73Findings,m73Export } from '../../../../packages/neuvetra-database/src/m73-validation'
const fail=():never=>{throw new Error('The saved stationary source could not be verified. Refresh before continuing.')}
const equal=(a:unknown,b:unknown)=>m73CanonicalJson(a)===m73CanonicalJson(b)
const hash=async(value:unknown)=>coverageSha256(m73CanonicalJson(value))
const instant=(v:unknown):v is string=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v
// eslint-disable-next-line no-control-regex
const bounded=(v:unknown,max=500):v is string=>typeof v==='string'&&v.length>0&&v===v.trim()&&v.normalize('NFC')===v&&Array.from(v).length<=max&&!/[\u0000-\u001f\u007f-\u009f\ud800-\udfff]/u.test(v)
const invariant=(v:{synthetic:unknown;scope1Completeness:unknown;corporateCompleteness:unknown;releaseEligible:unknown;assurance:unknown})=>v.synthetic===true&&v.scope1Completeness==='incomplete'&&v.corporateCompleteness==='incomplete'&&v.releaseEligible===false&&v.assurance==='none'
export async function decodeGasReview(value:unknown,companyId:string,version?:M73Version):Promise<M73Review>{try{m71Keys(value,['id','versionId','versionSha256','decision','note','acknowledgedLimitations','reviewerId','reviewedAt','decisionSha256']);const r=value as unknown as M73Review;if(!m71Uuid(r.id)||!m71Uuid(r.versionId)||!m71Uuid(r.reviewerId)||!m71HashString(r.versionSha256)||!m71HashString(r.decisionSha256)||!instant(r.reviewedAt)||!bounded(r.note)||!['accepted_bounded_internal','changes_requested'].includes(r.decision)||!equal(r.acknowledgedLimitations,M73_LIMITATIONS))return fail();if(version&&(r.versionId!==version.id||r.versionSha256!==version.versionSha256||version.contributorIds.includes(r.reviewerId)||r.reviewedAt<version.createdAt||r.decision==='accepted_bounded_internal'&&version.calculation===null))return fail();if(await hash(m73ReviewHashPayload(companyId,r))!==r.decisionSha256)return fail();return r}catch{return fail()}}
export async function decodeGasVersion(value:unknown,companyId:string,previous?:M73Version):Promise<M73Version>{try{
 m71Keys(value,['id','companyId','worksheetId','version','previousVersionId','previousVersionSha256','createdBy','createdAt','contributorIds','correctionReason','activity','coverageVersion','statement','calculation','findings','inputSha256','contentSha256','versionSha256','synthetic','scope1Completeness','corporateCompleteness','releaseEligible','assurance','review'])
 const v=value as unknown as M73Version
 if(!m71Uuid(companyId)||v.companyId!==companyId||![v.id,v.worksheetId,v.createdBy].every(m71Uuid)||!instant(v.createdAt)||!invariant(v)||!Number.isInteger(v.version)||v.version<1||v.version>M73_MAX_VERSIONS||![v.inputSha256,v.contentSha256,v.versionSha256].every(m71HashString))return fail()
 if(!Array.isArray(v.contributorIds)||!v.contributorIds.every(m71Uuid)||!equal(v.contributorIds,[...new Set(v.contributorIds)].sort())||!v.contributorIds.includes(v.createdBy))return fail()
 if(v.version===1){if(v.previousVersionId!==null||v.previousVersionSha256!==null||v.correctionReason!==null)return fail()}else if(!m71Uuid(v.previousVersionId)||!m71HashString(v.previousVersionSha256)||!bounded(v.correctionReason))return fail()
 if(previous&&(v.worksheetId!==previous.worksheetId||v.version!==previous.version+1||v.previousVersionId!==previous.id||v.previousVersionSha256!==previous.versionSha256||v.createdAt<previous.createdAt||v.activity.binding.sourceId!==previous.activity.binding.sourceId))return fail()
 const normalized=validateM73Save({...v.activity,expectedVersionId:v.previousVersionId,expectedVersionSha256:v.previousVersionSha256,correctionReason:v.correctionReason,idempotencyKey:v.id});if(!equal(m73Activity(normalized),v.activity)||!equal(deriveM73Findings(v.activity),v.findings))return fail()
 await decodeCorporateVersion(v.coverageVersion,companyId);if(v.coverageVersion.review!==null)return fail();m73ResolveBinding(v.activity.binding,v.coverageVersion)
 const contributors=[...new Set([...(previous?.contributorIds??[]),...v.coverageVersion.contributorIds,v.createdBy])].sort();if(previous||v.version===1){if(!equal(contributors,v.contributorIds))return fail()}else if(!contributors.every(id=>v.contributorIds.includes(id)))return fail()
 if(v.statement===null){if(v.activity.statement!==null)return fail()}else{m71Keys(v.statement,['id','profile','input','locator','text','sha256','byteLength']);const s=v.statement;if(!m71Uuid(s.id)||s.profile!=='m73-synthetic-gas-statement-v1'||s.locator!==`m73-statement:${s.id}:annual-activity`||!equal(s.input,v.activity.statement)||s.text!==m73StatementText(v.activity,v.coverageVersion)||s.byteLength!==new TextEncoder().encode(s.text).length||await coverageSha256(s.text)!==s.sha256)return fail()}
 if(v.activity.quantityMmbtu===null){if(v.calculation!==null)return fail()}else{
  const c=v.calculation;if(!c||!v.statement)return fail();m71Keys(c,['profile','input','inputSha256','method','gasResults','total','resultSha256']);m71Keys(c.input,['binding','period','fuel','heatBasis','unit','quantityMmbtu','statementSha256']);if(c.profile!=='m73-decimal-result-v1'||!equal(c.input,{binding:v.activity.binding,period:v.activity.period,fuel:v.activity.fuel,heatBasis:v.activity.heatBasis,unit:v.activity.unit,quantityMmbtu:v.activity.quantityMmbtu,statementSha256:v.statement.sha256})||await hash(c.input)!==c.inputSha256||await hash(m73CalculationHashPayload(c))!==c.resultSha256)return fail()
  m71Keys(c.total,['unrounded','display','unit','rounding']);if(c.total.unit!=='kg CO2e'||c.total.rounding!=='half_even_4dp'||!/^\d+(?:\.\d+)?$/.test(c.total.unrounded)||!/^\d+\.\d{4}$/.test(c.total.display))return fail()
  m71Keys(c.gasResults,['co2','ch4','n2o']);for(const [name,gas] of Object.entries(c.gasResults)){m71Keys(gas,['mass','massUnit','co2e','co2eUnit']);if(gas.massUnit!=='kg '+name.toUpperCase()||gas.co2eUnit!=='kg CO2e'||!/^\d+(?:\.\d+)?$/.test(gas.mass)||!/^\d+(?:\.\d+)?$/.test(gas.co2e))return fail()}
  if(!equal(c.method,M73_METHOD)||c.method.status!=='development_candidate_not_released'||c.method.releaseEligible!==false||c.method.rights!=='unresolved_for_factor_release')return fail()
 }
 if(await hash(m73InputHashPayload(v))!==v.inputSha256||await hash(m73ContentPayload(v))!==v.contentSha256||await hash(m73VersionHashPayload(v))!==v.versionSha256)return fail();if(v.review!==null)await decodeGasReview(v.review,companyId,v);return v
 }catch{return fail()}}
export async function decodeGasReport(value:unknown,companyId:string,version?:M73Version):Promise<M73Report>{try{m71Keys(value,['id','companyId','worksheetId','versionId','versionSha256','decisionId','decisionSha256','createdBy','createdAt','rendererVersion','html','htmlSha256','htmlByteLength','snapshotJson','snapshotSha256','reportSha256']);const r=value as unknown as M73Report;if(r.companyId!==companyId||![r.id,r.worksheetId,r.versionId,r.createdBy].every(m71Uuid)||!instant(r.createdAt)||r.rendererVersion!=='m73-source-report-v1'||!m71HashString(r.versionSha256)||!(r.decisionId===null?r.decisionSha256===null:m71Uuid(r.decisionId)&&m71HashString(r.decisionSha256))||typeof r.html!=='string'||r.htmlByteLength!==new TextEncoder().encode(r.html).length||r.htmlByteLength>131072||await coverageSha256(r.html)!==r.htmlSha256||typeof r.snapshotJson!=='string'||await coverageSha256(r.snapshotJson)!==r.snapshotSha256||await hash(m73ReportHashPayload(r))!==r.reportSha256)return fail();if(version&&(r.versionId!==version.id||r.versionSha256!==version.versionSha256||r.worksheetId!==version.worksheetId||r.createdAt<version.createdAt||r.decisionId!==null&&(r.decisionId!==version.review?.id||r.decisionSha256!==version.review.decisionSha256)))return fail();const snapshot=parseM71Json(r.snapshotJson,M73_MAX_RESPONSE_BYTES) as ReturnType<typeof m73ReportSnapshot>;m71Keys(snapshot,['profile','version','review']);const captured=await decodeGasVersion(snapshot.version,companyId);if(snapshot.profile!=='m73-source-report-v1'||captured.review!==null||captured.id!==r.versionId||captured.versionSha256!==r.versionSha256||captured.worksheetId!==r.worksheetId)return fail();if(snapshot.review!==null)await decodeGasReview(snapshot.review,companyId,captured);if((snapshot.review?.id??null)!==r.decisionId||(snapshot.review?.decisionSha256??null)!==r.decisionSha256||m73CanonicalJson(snapshot)!==r.snapshotJson||m73RenderReport(snapshot)!==r.html)return fail();return r}catch{return fail()}}
export async function decodeGasRegister(value:unknown,companyId:string):Promise<M73Register>{try{m71Keys(value,['profile','companyId','coverageHeadVersionId','worksheets','sources','coverageFindings','limitations','synthetic','scope1Completeness','corporateCompleteness','releaseEligible','assurance']);const r=value as unknown as M73Register;if(r.profile!==M73_PROFILE||r.companyId!==companyId||!m71Uuid(companyId)||!invariant(r)||!equal(r.limitations,M73_LIMITATIONS)||!(r.coverageHeadVersionId===null||m71Uuid(r.coverageHeadVersionId))||!Array.isArray(r.worksheets)||r.worksheets.length>M73_MAX_STREAMS||!Array.isArray(r.sources)||!Array.isArray(r.coverageFindings))return fail();const ids=new Set<string>(),sourceIds=new Set<string>();let count=0;for(const w of r.worksheets){m71Keys(w,['profile','companyId','worksheetId','sourceId','headVersionId','versions','reports','findings','limitations','synthetic','scope1Completeness','corporateCompleteness','releaseEligible','assurance']);if(w.profile!==M73_PROFILE||w.companyId!==companyId||!invariant(w)||!equal(w.limitations,M73_LIMITATIONS)||![w.worksheetId,w.sourceId,w.headVersionId].every(m71Uuid)||ids.has(w.worksheetId)||sourceIds.has(w.sourceId)||!Array.isArray(w.versions)||!w.versions.length||!Array.isArray(w.reports)||!Array.isArray(w.findings))return fail();ids.add(w.worksheetId);sourceIds.add(w.sourceId);let prev:M73Version|undefined;for(const raw of w.versions){const v=await decodeGasVersion(raw,companyId,prev);if(v.version!==(prev?.version??0)+1||v.worksheetId!==w.worksheetId||v.activity.binding.sourceId!==w.sourceId)return fail();prev=v;count++}if(w.headVersionId!==prev?.id||w.reports.length>w.versions.length*2)return fail();for(const report of w.reports){const v=w.versions.find(v=>v.id===report.versionId);if(!v)return fail();await decodeGasReport(report,companyId,v)}}if(count>M73_MAX_VERSIONS)return fail();for(const s of r.sources){m71Keys(s,['binding','companyLabel','entityLabel','facilityLabel','sourceLabel','eligible','findings']);m71Keys(s.binding,['coverageVersionId','coverageVersionSha256','entityId','facilityId','sourceId','boundaryDecisionId']);if(typeof s.eligible!=='boolean'||!Array.isArray(s.findings)||!['companyLabel','entityLabel','facilityLabel','sourceLabel'].every(k=>typeof s[k as keyof typeof s]==='string')||!m71Uuid(s.binding.sourceId)||s.binding.coverageVersionId!==r.coverageHeadVersionId||!m71HashString(s.binding.coverageVersionSha256))return fail()}return r}catch{return fail()}}
async function request(actor:HostedWorkspaceActor,companyId:string,suffix:string,payload?:unknown){actor.signal?.throwIfAborted();if(!m71Uuid(companyId)||!actor.accessToken||/[\r\n]/.test(actor.accessToken))return fail();const response=await fetch(`/workspace-api/workspace/${companyId}/stationary-natural-gas${suffix}`,{method:payload===undefined?'GET':'POST',headers:{authorization:`Bearer ${actor.accessToken}`,...(payload===undefined?{}:{'content-type':'application/json'})},body:payload===undefined?undefined:JSON.stringify(payload),signal:actor.signal,cache:'no-store'});actor.signal?.throwIfAborted();if(response.status===401||response.status===403){actor.onUnauthorized?.();throw new Error('Your access changed. Sign in again to continue.')}if(!response.ok)throw new Error(response.status===409?'The source, boundary or review changed, or this statement is already assigned. Refresh and check the source before retrying.':response.status===422?'Check the source boundary, decimal quantity, statement, confirmation and required explanations. Nothing was saved.':'Stationary source data is unavailable. Retry the same action or refresh.');const text=await response.text();actor.signal?.throwIfAborted();if(new TextEncoder().encode(text).length>M73_MAX_RESPONSE_BYTES)return fail();return text}
export async function gasRegisterRequest(a:HostedWorkspaceActor,c:string){return decodeGasRegister(parseM71Json(await request(a,c,''),M73_MAX_RESPONSE_BYTES),c)}
export async function gasSaveRequest(a:HostedWorkspaceActor,c:string,w:string|null,input:M73SaveInput){if(w!==null&&!m71Uuid(w))return fail();return decodeGasVersion(parseM71Json(await request(a,c,w?`/${w}/versions`:'',input),M73_MAX_RESPONSE_BYTES),c)}
export async function gasReviewRequest(a:HostedWorkspaceActor,c:string,w:string,input:M73ReviewInput){if(!m71Uuid(w))return fail();return decodeGasReview(parseM71Json(await request(a,c,`/${w}/reviews`,input),M73_MAX_RESPONSE_BYTES),c)}
export async function gasReportRequest(a:HostedWorkspaceActor,c:string,w:string,input:M73ReportInput){if(!m71Uuid(w))return fail();return decodeGasReport(parseM71Json(await request(a,c,`/${w}/reports`,input),M73_MAX_RESPONSE_BYTES),c)}
export async function gasStatementDownload(a:HostedWorkspaceActor,c:string,w:string,v:M73Version){if(v.companyId!==c||v.worksheetId!==w||!v.statement||!m71Uuid(w))return fail();const text=await request(a,c,`/${w}/statements/${v.statement.id}/download`);if(text!==v.statement.text||await coverageSha256(text)!==v.statement.sha256)return fail();return text}
export async function gasExportRequest(a:HostedWorkspaceActor,c:string,v:M73Version){if(v.companyId!==c||!m71Uuid(v.worksheetId)||!m71Uuid(v.id))return fail();const text=await request(a,c,`/${v.worksheetId}/versions/${v.id}/calculation-export`);await decodeGasVersion(parseM71Json(text,M73_MAX_RESPONSE_BYTES),c);if(text!==m73Export(v))return fail();return text}
export async function gasReportDownload(a:HostedWorkspaceActor,c:string,w:string,r:M73Report){if(r.companyId!==c||r.worksheetId!==w||!m71Uuid(w)||!m71Uuid(r.id))return fail();const text=await request(a,c,`/${w}/reports/${r.id}/download`);if(text!==r.html||await coverageSha256(text)!==r.htmlSha256)return fail();return text}
