import { m76DieselRenderReport, m76DieselReportSnapshot } from '../../../../packages/neuvetra-database/src/m76-diesel-report'
import type { HostedWorkspaceActor } from './workspace-api'
import { coverageSha256, decodeCorporateVersion } from './m71-api'
import { m71Keys, m71Uuid, m71HashString, parseM71Json } from '../../../../packages/neuvetra-database/src/m71-validation'
import { M76_DIESEL_PROFILE,M76_DIESEL_METHOD,M76_DIESEL_LIMITATIONS,M76_DIESEL_MAX_RESPONSE_BYTES,M76_DIESEL_MAX_STREAMS,M76_DIESEL_MAX_VERSIONS,M76_DIESEL_MAX_REPORTS,type M76DieselVersion,type M76DieselRegister,type M76DieselReview,type M76DieselReport,type M76DieselSaveInput,type M76DieselReviewInput,type M76DieselReportInput } from '../../../../packages/neuvetra-database/src/m76-diesel-contract'
import { m76DieselCanonicalJson,validateM76DieselSave,m76DieselActivity,m76DieselInputHashPayload,m76DieselContentPayload,m76DieselVersionHashPayload,m76DieselReviewHashPayload,m76DieselReportHashPayload,m76DieselCalculationHashPayload,m76DieselStatementText,m76DieselResolveBinding,deriveM76DieselFindings,m76DieselExport,m76DieselCanCalculate,deriveM76DieselActivityStatus } from '../../../../packages/neuvetra-database/src/m76-diesel-validation'
const fail=():never=>{throw new Error('The saved stationary source could not be verified. Refresh before continuing.')}
const equal=(a:unknown,b:unknown)=>m76DieselCanonicalJson(a)===m76DieselCanonicalJson(b)
const hash=async(value:unknown)=>coverageSha256(m76DieselCanonicalJson(value))
const instant=(v:unknown):v is string=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v
// eslint-disable-next-line no-control-regex
const bounded=(v:unknown,max=500):v is string=>typeof v==='string'&&v.length>0&&v===v.trim()&&v.normalize('NFC')===v&&Array.from(v).length<=max&&!/[\u0000-\u001f\u007f-\u009f\ud800-\udfff]/u.test(v)
const invariant=(v:{synthetic:unknown;scope1Completeness:unknown;corporateCompleteness:unknown;releaseEligible:unknown;assurance:unknown})=>v.synthetic===true&&v.scope1Completeness==='incomplete'&&v.corporateCompleteness==='incomplete'&&v.releaseEligible===false&&v.assurance==='none'
export async function decodeGeneratorReview(value:unknown,companyId:string,version?:M76DieselVersion):Promise<M76DieselReview>{try{m71Keys(value,['id','versionId','versionSha256','decision','note','acknowledgedLimitations','reviewerId','reviewedAt','decisionSha256']);const r=value as unknown as M76DieselReview;if(!m71Uuid(r.id)||!m71Uuid(r.versionId)||!m71Uuid(r.reviewerId)||!m71HashString(r.versionSha256)||!m71HashString(r.decisionSha256)||!instant(r.reviewedAt)||!bounded(r.note)||!['accepted_bounded_internal','changes_requested'].includes(r.decision)||!equal(r.acknowledgedLimitations,M76_DIESEL_LIMITATIONS))return fail();if(version&&(r.versionId!==version.id||r.versionSha256!==version.versionSha256||version.contributorIds.includes(r.reviewerId)||r.reviewedAt<version.createdAt||r.decision==='accepted_bounded_internal'&&(version.calculation===null||version.findings.some(f=>!['scope1_incomplete','method_not_released'].includes(f.code)))))return fail();if(await hash(m76DieselReviewHashPayload(companyId,r))!==r.decisionSha256)return fail();return r}catch{return fail()}}
export async function decodeGeneratorVersion(value:unknown,companyId:string,previous?:M76DieselVersion):Promise<M76DieselVersion>{try{
 m71Keys(value,['id','companyId','worksheetId','version','previousVersionId','previousVersionSha256','createdBy','createdAt','contributorIds','correctionReason','activity','activityStatus','coverageVersion','statement','calculation','findings','inputSha256','contentSha256','versionSha256','synthetic','scope1Completeness','corporateCompleteness','releaseEligible','assurance','review'])
 const v=value as unknown as M76DieselVersion
 if(!m71Uuid(companyId)||v.companyId!==companyId||![v.id,v.worksheetId,v.createdBy].every(m71Uuid)||!instant(v.createdAt)||!invariant(v)||!Number.isInteger(v.version)||v.version<1||v.version>M76_DIESEL_MAX_VERSIONS||![v.inputSha256,v.contentSha256,v.versionSha256].every(m71HashString))return fail()
 if(!Array.isArray(v.contributorIds)||!v.contributorIds.every(m71Uuid)||!equal(v.contributorIds,[...new Set(v.contributorIds)].sort())||!v.contributorIds.includes(v.createdBy))return fail()
 if(v.version===1){if(v.previousVersionId!==null||v.previousVersionSha256!==null||v.correctionReason!==null)return fail()}else if(!m71Uuid(v.previousVersionId)||!m71HashString(v.previousVersionSha256)||!bounded(v.correctionReason))return fail()
 if(previous&&(v.worksheetId!==previous.worksheetId||v.version!==previous.version+1||v.previousVersionId!==previous.id||v.previousVersionSha256!==previous.versionSha256||v.createdAt<previous.createdAt))return fail()
 const normalized=validateM76DieselSave({...v.activity,expectedVersionId:v.previousVersionId,expectedVersionSha256:v.previousVersionSha256,correctionReason:v.correctionReason,idempotencyKey:v.id});if(!equal(m76DieselActivity(normalized),v.activity)||!equal(deriveM76DieselFindings(v.activity),v.findings)||v.activityStatus!==deriveM76DieselActivityStatus(v.activity))return fail()
 await decodeCorporateVersion(v.coverageVersion,companyId);if(v.coverageVersion.review!==null)return fail();m76DieselResolveBinding(v.activity.binding,v.coverageVersion)
 const contributors=[...new Set([...(previous?.contributorIds??[]),...v.coverageVersion.contributorIds,v.createdBy])].sort();if(previous||v.version===1){if(!equal(contributors,v.contributorIds))return fail()}else if(!contributors.every(id=>v.contributorIds.includes(id)))return fail()
 if(v.statement===null){if(v.activity.statement!==null)return fail()}else{m71Keys(v.statement,['id','profile','input','locator','text','sha256','byteLength']);const s=v.statement;if(!m71Uuid(s.id)||s.profile!=='m76-synthetic-generator-statement-v1'||s.locator!==`m76-diesel-statement:${s.id}:annual-activity`||!equal(s.input,v.activity.statement)||s.text!==m76DieselStatementText(v.activity,v.coverageVersion)||s.byteLength!==new TextEncoder().encode(s.text).length||await coverageSha256(s.text)!==s.sha256)return fail()}
 if(!m76DieselCanCalculate(v.activity)){if(v.calculation!==null)return fail()}else{
  const c=v.calculation;if(!c||!v.statement)return fail();m71Keys(c,['profile','input','inputSha256','method','derivedHhv','gasResults','total','resultSha256']);m71Keys(c.input,['binding','period','equipment','unit','quantityGallons','statementSha256']);if(c.profile!=='m76-diesel-decimal-result-v1'||!equal(c.input,{binding:v.activity.binding,period:v.activity.period,equipment:v.activity.equipment,unit:v.activity.unit,quantityGallons:v.activity.quantityGallons,statementSha256:v.statement.sha256})||await hash(c.input)!==c.inputSha256||await hash(m76DieselCalculationHashPayload(c))!==c.resultSha256)return fail()
  m71Keys(c.derivedHhv,['quantityMmbtu','heatBasis','basis']);if(c.derivedHhv.heatBasis!=='HHV'||c.derivedHhv.basis!=='default_hhv_estimate'||!/^\d+(?:\.\d+)?$/.test(c.derivedHhv.quantityMmbtu))return fail()
  m71Keys(c.total,['unrounded','display','unit','rounding']);if(c.total.unit!=='kg CO2e'||c.total.rounding!=='half_even_4dp'||!/^\d+(?:\.\d+)?$/.test(c.total.unrounded)||!/^\d+\.\d{4}$/.test(c.total.display))return fail()
  m71Keys(c.gasResults,['co2','ch4','n2o']);for(const [name,gas] of Object.entries(c.gasResults)){m71Keys(gas,['mass','massUnit','co2e','co2eUnit']);if(gas.massUnit!=='kg '+name.toUpperCase()||gas.co2eUnit!=='kg CO2e'||!/^\d+(?:\.\d+)?$/.test(gas.mass)||!/^\d+(?:\.\d+)?$/.test(gas.co2e))return fail()}
  if(!equal(c.method,M76_DIESEL_METHOD)||c.method.status!=='development_candidate_not_released'||c.method.releaseEligible!==false||c.method.rights!=='unresolved_for_factor_release')return fail()
 }
 if(await hash(m76DieselInputHashPayload(v))!==v.inputSha256||await hash(m76DieselContentPayload(v))!==v.contentSha256||await hash(m76DieselVersionHashPayload(v))!==v.versionSha256)return fail();if(v.review!==null)await decodeGeneratorReview(v.review,companyId,v);return v
 }catch{return fail()}}
export async function decodeGeneratorReport(value:unknown,companyId:string,version?:M76DieselVersion):Promise<M76DieselReport>{try{if(!version)return fail();m71Keys(value,['id','companyId','worksheetId','versionId','versionSha256','decisionId','decisionSha256','createdBy','createdAt','rendererVersion','html','htmlSha256','htmlByteLength','snapshotJson','snapshotSha256','reportSha256']);const r=value as unknown as M76DieselReport;if(r.companyId!==companyId||![r.id,r.worksheetId,r.versionId,r.createdBy].every(m71Uuid)||!instant(r.createdAt)||r.rendererVersion!=='m76-generator-source-report-v1'||!m71HashString(r.versionSha256)||!(r.decisionId===null?r.decisionSha256===null:m71Uuid(r.decisionId)&&m71HashString(r.decisionSha256))||typeof r.html!=='string'||r.htmlByteLength!==new TextEncoder().encode(r.html).length||r.htmlByteLength>131072||await coverageSha256(r.html)!==r.htmlSha256||typeof r.snapshotJson!=='string'||await coverageSha256(r.snapshotJson)!==r.snapshotSha256||await hash(m76DieselReportHashPayload(r))!==r.reportSha256)return fail();if(version&&(r.versionId!==version.id||r.versionSha256!==version.versionSha256||r.worksheetId!==version.worksheetId||r.createdAt<version.createdAt||r.decisionId!==null&&(r.decisionId!==version.review?.id||r.decisionSha256!==version.review.decisionSha256)))return fail();const snapshot=parseM71Json(r.snapshotJson,M76_DIESEL_MAX_RESPONSE_BYTES) as ReturnType<typeof m76DieselReportSnapshot>;m71Keys(snapshot,['profile','version','review']);const captured=await decodeGeneratorVersion(snapshot.version,companyId);if(!equal({...captured,review:null},{...version,review:null})||snapshot.profile!=='m76-generator-source-report-v1'||captured.review!==null||captured.id!==r.versionId||captured.versionSha256!==r.versionSha256||captured.worksheetId!==r.worksheetId)return fail();if(snapshot.review!==null)await decodeGeneratorReview(snapshot.review,companyId,captured);if((snapshot.review?.id??null)!==r.decisionId||(snapshot.review?.decisionSha256??null)!==r.decisionSha256||m76DieselCanonicalJson(snapshot)!==r.snapshotJson||m76DieselRenderReport(snapshot)!==r.html)return fail();return r}catch{return fail()}}
export async function decodeGeneratorRegister(value:unknown,companyId:string):Promise<M76DieselRegister>{try{m71Keys(value,['profile','companyId','coverageHeadVersionId','worksheets','sources','coverageFindings','limitations','synthetic','scope1Completeness','corporateCompleteness','releaseEligible','assurance']);const r=value as unknown as M76DieselRegister;if(r.profile!==M76_DIESEL_PROFILE||r.companyId!==companyId||!m71Uuid(companyId)||!invariant(r)||!equal(r.limitations,M76_DIESEL_LIMITATIONS)||!(r.coverageHeadVersionId===null||m71Uuid(r.coverageHeadVersionId))||!Array.isArray(r.worksheets)||r.worksheets.length>M76_DIESEL_MAX_STREAMS||!Array.isArray(r.sources)||!Array.isArray(r.coverageFindings))return fail();const ids=new Set<string>(),sourceIds=new Set<string>();let count=0;for(const w of r.worksheets){m71Keys(w,['profile','companyId','worksheetId','sourceId','headVersionId','versions','reports','findings','limitations','synthetic','scope1Completeness','corporateCompleteness','releaseEligible','assurance']);if(w.profile!==M76_DIESEL_PROFILE||w.companyId!==companyId||!invariant(w)||!equal(w.limitations,M76_DIESEL_LIMITATIONS)||![w.worksheetId,w.sourceId,w.headVersionId].every(m71Uuid)||ids.has(w.worksheetId)||sourceIds.has(w.sourceId)||!Array.isArray(w.versions)||!w.versions.length||!Array.isArray(w.reports)||!Array.isArray(w.findings))return fail();ids.add(w.worksheetId);sourceIds.add(w.sourceId);let prev:M76DieselVersion|undefined;for(const raw of w.versions){const v=await decodeGeneratorVersion(raw,companyId,prev);if(v.version!==(prev?.version??0)+1||v.worksheetId!==w.worksheetId)return fail();prev=v;count++}if(w.headVersionId!==prev?.id||prev?.activity.binding.sourceId!==w.sourceId||w.reports.length>M76_DIESEL_MAX_REPORTS)return fail();const reportIds=new Set<string>(),reportStates=new Set<string>();for(const report of w.reports){const state=report.versionId+'|'+(report.decisionId??'none');if(reportIds.has(report.id)||reportStates.has(state))return fail();reportIds.add(report.id);reportStates.add(state);const v=w.versions.find(v=>v.id===report.versionId);if(!v)return fail();await decodeGeneratorReport(report,companyId,v)}}if(count>M76_DIESEL_MAX_VERSIONS)return fail();for(const s of r.sources){m71Keys(s,['binding','companyLabel','entityLabel','facilityLabel','sourceLabel','eligible','findings']);m71Keys(s.binding,['coverageVersionId','coverageVersionSha256','entityId','facilityId','sourceId','boundaryDecisionId']);if(typeof s.eligible!=='boolean'||!Array.isArray(s.findings)||!['companyLabel','entityLabel','facilityLabel','sourceLabel'].every(k=>typeof s[k as keyof typeof s]==='string')||!m71Uuid(s.binding.sourceId)||s.binding.coverageVersionId!==r.coverageHeadVersionId||!m71HashString(s.binding.coverageVersionSha256))return fail()}return r}catch{return fail()}}
async function request(actor:HostedWorkspaceActor,companyId:string,suffix:string,payload?:unknown){actor.signal?.throwIfAborted();if(!m71Uuid(companyId)||!actor.accessToken||/[\r\n]/.test(actor.accessToken))return fail();const response=await fetch(`/workspace-api/workspace/${companyId}/stationary-diesel${suffix}`,{method:payload===undefined?'GET':'POST',headers:{authorization:`Bearer ${actor.accessToken}`,...(payload===undefined?{}:{'content-type':'application/json'})},body:payload===undefined?undefined:JSON.stringify(payload),signal:actor.signal,cache:'no-store'});actor.signal?.throwIfAborted();if(response.status===401||response.status===403){actor.onUnauthorized?.();throw new Error('Your access changed. Sign in again to continue.')}if(!response.ok)throw new Error(response.status===409?'The source, boundary or review changed, or this statement is already assigned. Refresh and check the source before retrying.':response.status===422?'Check the source boundary, decimal quantity, statement, confirmation and required explanations. Nothing was saved.':'Stationary source data is unavailable. Retry the same action or refresh.');const text=await response.text();actor.signal?.throwIfAborted();if(new TextEncoder().encode(text).length>M76_DIESEL_MAX_RESPONSE_BYTES)return fail();return text}
export async function generatorRegisterRequest(a:HostedWorkspaceActor,c:string){return decodeGeneratorRegister(parseM71Json(await request(a,c,''),M76_DIESEL_MAX_RESPONSE_BYTES),c)}
export async function generatorSaveRequest(a:HostedWorkspaceActor,c:string,w:string|null,input:M76DieselSaveInput){if(w!==null&&!m71Uuid(w))return fail();return decodeGeneratorVersion(parseM71Json(await request(a,c,w?`/${w}/versions`:'',input),M76_DIESEL_MAX_RESPONSE_BYTES),c)}
export async function generatorReviewRequest(a:HostedWorkspaceActor,c:string,w:string,input:M76DieselReviewInput){if(!m71Uuid(w))return fail();return decodeGeneratorReview(parseM71Json(await request(a,c,`/${w}/reviews`,input),M76_DIESEL_MAX_RESPONSE_BYTES),c)}
export async function generatorReportRequest(a:HostedWorkspaceActor,c:string,w:string,input:M76DieselReportInput){if(!m71Uuid(w))return fail();const raw=parseM71Json(await request(a,c,`/${w}/reports`,input),M76_DIESEL_MAX_RESPONSE_BYTES);const version=await decodeGeneratorVersion(parseM71Json(await request(a,c,`/${w}/versions/${input.versionId}`),M76_DIESEL_MAX_RESPONSE_BYTES),c);return decodeGeneratorReport(raw,c,version)}
export async function generatorStatementDownload(a:HostedWorkspaceActor,c:string,w:string,v:M76DieselVersion){if(v.companyId!==c||v.worksheetId!==w||!v.statement||!m71Uuid(w))return fail();const text=await request(a,c,`/${w}/statements/${v.statement.id}/download`);if(text!==v.statement.text||await coverageSha256(text)!==v.statement.sha256)return fail();return text}
export async function generatorExportRequest(a:HostedWorkspaceActor,c:string,v:M76DieselVersion){if(v.companyId!==c||!m71Uuid(v.worksheetId)||!m71Uuid(v.id))return fail();const text=await request(a,c,`/${v.worksheetId}/versions/${v.id}/calculation-export`);await decodeGeneratorVersion(parseM71Json(text,M76_DIESEL_MAX_RESPONSE_BYTES),c);if(text!==m76DieselExport(v))return fail();return text}
export async function generatorReportDownload(a:HostedWorkspaceActor,c:string,w:string,r:M76DieselReport){if(r.companyId!==c||r.worksheetId!==w||!m71Uuid(w)||!m71Uuid(r.id))return fail();const version=await decodeGeneratorVersion(parseM71Json(await request(a,c,`/${w}/versions/${r.versionId}`),M76_DIESEL_MAX_RESPONSE_BYTES),c);await decodeGeneratorReport(r,c,version);const text=await request(a,c,`/${w}/reports/${r.id}/download`);if(text!==r.html||await coverageSha256(text)!==r.htmlSha256)return fail();return text}
