import type {HostedWorkspaceActor} from './workspace-api'
import {coverageSha256,decodeCorporateVersion} from './m71-api'
import {m71Uuid} from '../../../../packages/neuvetra-database/src/m71-validation'
import {M77_LIMITATIONS,M77_MAX_RESPONSE_BYTES,M77_MAX_SOURCES,M77_MAX_VERSIONS,M77_MAX_REPORTS,type M77Register,type M77Version,type M77Review,type M77Report,type M77ReportSnapshot,type M77Family,type M77ReviewInput,type M77ReportInput} from '../../../../packages/neuvetra-database/src/m77-contract'
import {m77ValidatePopulationCorrection,parseM77Json,m77Keys,m77CanonicalJson,validateM77SourceSave,validateM77PopulationSave,validateM77Review,m77ContentPayload,m77VersionHashPayload,m77ExpectedCalculation,m77SourceChoices,m77SourceFindings,m77EvidenceText,deriveM77Reconciliation} from '../../../../packages/neuvetra-database/src/m77-validation'
import {m77RenderReport} from '../../../../packages/neuvetra-database/src/m77-report'

const fail=():never=>{throw new Error('Fugitive-source records could not be verified. Refresh before continuing.')}
const check=(v:unknown)=>{if(!v)fail()}
const equal=(a:unknown,b:unknown)=>m77CanonicalJson(a)===m77CanonicalJson(b)
const hash=(v:unknown)=>coverageSha256(m77CanonicalJson(v))
const instant=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v
const uuid=(v:string)=>{check(m71Uuid(v));return v}
async function derive<T>(fn:(h:(v:unknown)=>string)=>T):Promise<T>{const cache=new Map<string,string>();class Missing{constructor(readonly text:string){}}for(let i=0;i<20;i++){try{return fn(v=>{const s=m77CanonicalJson(v),h=cache.get(s);if(!h)throw new Missing(s);return h})}catch(e){if(!(e instanceof Missing))throw e;cache.set(e.text,await coverageSha256(e.text))}}return fail()}
const versionKeys=['id','companyId','streamId','family','version','previousVersionId','previousVersionSha256','createdBy','createdAt','contributorIds','correctionReason','coverageVersion','statements','dependencies','findings','inputSha256','contentSha256','versionSha256','synthetic','scope1Completeness','corporateCompleteness','releaseEligible','assurance','emissionsTotals','review','activity','calculation']
async function decodeReview(raw:unknown,v:M77Version):Promise<M77Review|null>{if(raw===null)return null;m77Keys(raw,['id','versionId','versionSha256','dependencies','decision','note','acknowledgedLimitations','reviewerId','reviewedAt','decisionSha256']);const r=raw as unknown as M77Review;check(m71Uuid(r.id)&&m71Uuid(r.reviewerId)&&instant(r.reviewedAt)&&r.reviewedAt>=v.createdAt&&r.versionId===v.id&&r.versionSha256===v.versionSha256&&!v.contributorIds.includes(r.reviewerId));validateM77Review({versionId:r.versionId,expectedVersionSha256:r.versionSha256,expectedDependencySha256:r.dependencies?.dependencySha256??null,decision:r.decision,note:r.note,acknowledgedLimitations:r.acknowledgedLimitations,idempotencyKey:r.id});check(v.family==='source'?r.dependencies===null&&r.decision!=='accepted_bounded_reconciliation':r.dependencies!==null&&equal(r.dependencies,v.dependencies)&&r.decision!=='accepted_bounded_internal');const {decisionSha256,...body}=r;check(await hash({companyId:v.companyId,...body})===decisionSha256);if(r.decision==='accepted_bounded_internal')check(v.calculation&&v.findings.length===0);return r}
export async function decodeFugitiveVersion(raw:unknown,companyId:string,previous?:M77Version):Promise<M77Version>{try{
  m77Keys(raw,versionKeys);const v=raw as unknown as M77Version;check(v.companyId===uuid(companyId)&&[v.id,v.streamId,v.createdBy].every(m71Uuid)&&instant(v.createdAt)&&['source','population'].includes(v.family)&&Number.isInteger(v.version)&&v.version>0&&v.version<=M77_MAX_VERSIONS);check(v.synthetic===true&&v.scope1Completeness==='incomplete'&&v.corporateCompleteness==='incomplete'&&v.releaseEligible===false&&v.assurance==='none'&&v.emissionsTotals===null);check(Array.isArray(v.contributorIds)&&v.contributorIds.every(m71Uuid)&&equal(v.contributorIds,[...new Set(v.contributorIds)].sort())&&v.contributorIds.includes(v.createdBy));if(v.version===1)check(v.previousVersionId===null&&v.previousVersionSha256===null&&v.correctionReason===null);else check(m71Uuid(v.previousVersionId)&&typeof v.correctionReason==='string'&&v.correctionReason.length>0);if(previous)check(v.streamId===previous.streamId&&v.family===previous.family&&v.version===previous.version+1&&v.previousVersionId===previous.id&&v.previousVersionSha256===previous.versionSha256&&v.createdAt>=previous.createdAt&&previous.contributorIds.every(id=>v.contributorIds.includes(id)));
  await decodeCorporateVersion(v.coverageVersion,companyId);const pins={expectedVersionId:v.previousVersionId,expectedVersionSha256:v.previousVersionSha256,correctionReason:v.correctionReason,idempotencyKey:v.id};
  if(v.family==='source'){validateM77SourceSave({...v.activity,...pins});check(v.dependencies===null&&v.activity.binding.coverageVersionId===v.coverageVersion.id&&v.activity.binding.coverageVersionSha256===v.coverageVersion.versionSha256);check(m77SourceChoices(v.coverageVersion).some(s=>(!v.activity.calculatorInput||s.eligible)&&equal(s.binding,v.activity.binding)));check(equal(v.findings,m77SourceFindings(v.activity)));check(equal(v.calculation,v.activity.calculatorInput?m77ExpectedCalculation(v.activity.calculatorInput):null))}
  else {if(previous?.family==='population')m77ValidatePopulationCorrection(previous,v.activity);check(v.dependencies&&v.calculation===null&&equal(v.findings,[]));validateM77PopulationSave({...v.activity,...pins,expectedDependencySha256:v.dependencies!.dependencySha256});check(v.activity.coverageVersionId===v.coverageVersion.id&&v.activity.coverageVersionSha256===v.coverageVersion.versionSha256);m77Keys(v.dependencies!,['coveragePin','coverageReviewPin','workpaperPins','dependencySha256']);const {dependencySha256,...dep}=v.dependencies!;check(equal(dep.coveragePin,{id:v.coverageVersion.id,sha256:v.coverageVersion.versionSha256})&&await hash(dep)===dependencySha256)}
  const expectedStatements=v.family==='source'?v.activity.evidenceStatements:v.activity.declaration?[{reference:v.activity.declaration.reference,issuer:v.activity.declaration.issuer,description:`${v.activity.declaration.description} Discovery basis: ${v.activity.declaration.discoveryBasis}`}]:[];check(Array.isArray(v.statements)&&v.statements.length===expectedStatements.length);
  for(let i=0;i<v.statements.length;i++){const s=v.statements[i];m77Keys(s,['id','locator','text','sha256','byteLength','reference','issuer','description']);check(m71Uuid(s.id)&&equal({reference:s.reference,issuer:s.issuer,description:s.description},expectedStatements[i])&&s.locator===`m77-evidence:${s.id}:${s.reference}`&&s.text===m77EvidenceText(companyId,v.family==='source'?v.activity.assetId:null,expectedStatements[i])&&s.byteLength===new TextEncoder().encode(s.text).length&&s.sha256===await coverageSha256(s.text))}
  check(Array.isArray(v.findings));for(const f of v.findings){m77Keys(f,['code','message','blocking','assetId','sourceId']);check(f.blocking===true&&typeof f.message==='string'&&typeof f.code==='string')}
  check(await hash(v.activity)===v.inputSha256&&await hash(m77ContentPayload(v))===v.contentSha256&&await hash(m77VersionHashPayload(v))===v.versionSha256);await decodeReview(v.review,v);return v
}catch{return fail()}}
export async function decodeFugitiveReport(raw:unknown,companyId:string):Promise<M77Report>{try{
  m77Keys(raw,['id','companyId','streamId','family','versionId','versionSha256','createdBy','createdAt','rendererVersion','snapshotJson','snapshotSha256','html','htmlSha256','htmlByteLength','reportSha256']);const r=raw as unknown as M77Report;check(r.companyId===companyId&&[r.id,r.streamId,r.versionId,r.createdBy].every(m71Uuid)&&instant(r.createdAt)&&r.rendererVersion==='m77-retained-report-v1');const s=parseM77Json(r.snapshotJson,M77_MAX_RESPONSE_BYTES) as unknown as M77ReportSnapshot;m77Keys(s,['profile','version','review','reconciliation','proof','limitations']);check(s.profile==='m77-report-snapshot-v1'&&equal(s.limitations,M77_LIMITATIONS)&&s.version.review===null&&s.version.id===r.versionId&&s.version.versionSha256===r.versionSha256&&s.version.streamId===r.streamId&&s.version.family===r.family&&s.version.createdAt<=r.createdAt&&(!s.review||s.review.reviewedAt<=r.createdAt));await decodeFugitiveVersion(s.version,companyId);await decodeReview(s.review,s.version);
  if(s.version.family==='source')check(s.proof===null&&s.reconciliation===null);else {check(s.proof&&s.reconciliation);await decodeCorporateVersion(s.proof!.coverageVersion,companyId);for(const v of s.proof!.workpaperVersions)await decodeFugitiveVersion(v,companyId);const expected=await derive(h=>deriveM77Reconciliation(companyId,s.proof!.coverageVersion,s.proof!.workpaperVersions,s.version.family==='population'?s.version:null,s.review?[s.review]:[],h));check(equal(expected,s.reconciliation))}
  check(r.snapshotJson===m77CanonicalJson(s)&&await coverageSha256(r.snapshotJson)===r.snapshotSha256&&r.html===m77RenderReport(s)&&await coverageSha256(r.html)===r.htmlSha256&&new TextEncoder().encode(r.html).length===r.htmlByteLength);const body:Record<string,unknown>={...r};delete body.snapshotJson;delete body.html;delete body.reportSha256;check(await hash(body)===r.reportSha256);return r
}catch{return fail()}}
export async function decodeFugitiveRegister(raw:unknown,companyId:string):Promise<M77Register>{try{
  m77Keys(raw,['profile','companyId','coverageHeadVersionId','coverageVersion','sources','worksheets','population','reconciliation','limitations']);const r=raw as unknown as M77Register;check(r.profile==='synthetic-fugitive-register-v1'&&r.companyId===uuid(companyId)&&equal(r.limitations,M77_LIMITATIONS));if(r.coverageVersion)await decodeCorporateVersion(r.coverageVersion,companyId);check(r.coverageHeadVersionId===(r.coverageVersion?.id??null)&&equal(r.sources,m77SourceChoices(r.coverageVersion)));check(Array.isArray(r.worksheets)&&r.worksheets.length<=M77_MAX_SOURCES);m77Keys(r.population,['rosterId','headVersionId','versions','reports']);const allVersions:M77Version[]=[];let reportCount=0;
  for(const w of r.worksheets){m77Keys(w,['worksheetId','sourceId','assetId','headVersionId','versions','reports']);check(m71Uuid(w.worksheetId)&&m71Uuid(w.sourceId)&&Array.isArray(w.versions)&&w.versions.length>0);let previous:M77Version|undefined;for(const v of w.versions){await decodeFugitiveVersion(v,companyId,previous);check(v.family==='source'&&v.streamId===w.worksheetId&&v.activity.assetId===w.assetId);previous=v;allVersions.push(v)}check(w.headVersionId===previous?.id&&previous?.family==='source'&&previous.activity.binding.sourceId===w.sourceId);for(const report of w.reports){await decodeFugitiveReport(report,companyId);check(report.streamId===w.worksheetId&&w.versions.some(v=>v.id===report.versionId&&v.versionSha256===report.versionSha256));reportCount++}}
  let previous:M77Version|undefined;for(const v of r.population.versions){await decodeFugitiveVersion(v,companyId,previous);check(v.family==='population'&&v.streamId===r.population.rosterId);previous=v;allVersions.push(v)}check(r.population.headVersionId===(previous?.id??null)&&(previous?m71Uuid(r.population.rosterId):r.population.rosterId===null));for(const report of r.population.reports){await decodeFugitiveReport(report,companyId);check(report.streamId===r.population.rosterId&&r.population.versions.some(v=>v.id===report.versionId&&v.versionSha256===report.versionSha256));reportCount++}
  check(allVersions.length<=M77_MAX_VERSIONS&&reportCount<=M77_MAX_REPORTS&&new Set(allVersions.map(v=>v.id)).size===allVersions.length&&new Set(r.worksheets.map(w=>w.sourceId)).size===r.worksheets.length&&new Set(r.worksheets.map(w=>w.assetId)).size===r.worksheets.length);
  for(const v of allVersions){
   const prior=v.previousVersionId?allVersions.find(p=>p.id===v.previousVersionId):null
   const contributors=[...(prior?.contributorIds??[]),...v.coverageVersion.contributorIds,v.createdBy]
   if(v.family==='population'){
    const pins=v.dependencies!.workpaperPins;check(Array.isArray(pins)&&new Set(pins.map(p=>p.worksheetId)).size===pins.length);const capturedHeads=r.worksheets.map(w=>w.versions.filter(x=>x.createdAt<=v.createdAt).sort((a,b)=>b.version-a.version)[0]).filter(Boolean);check(pins.length===capturedHeads.length&&capturedHeads.every(x=>pins.some(p=>p.worksheetId===x.streamId&&p.version.id===x.id&&p.version.sha256===x.versionSha256)))
    for(const pin of pins){m77Keys(pin,['worksheetId','sourceId','assetId','version','decision']);const source=allVersions.find(x=>x.id===pin.version.id);check(source?.family==='source'&&source.versionSha256===pin.version.sha256&&source.streamId===pin.worksheetId&&source.activity.assetId===pin.assetId&&source.activity.binding.sourceId===pin.sourceId&&source.createdAt<=v.createdAt);contributors.push(...source!.contributorIds);if(pin.decision)check(source!.review?.id===pin.decision.id&&source!.review.decisionSha256===pin.decision.sha256&&source!.review.reviewedAt<=v.createdAt)}
   }
   check(equal(v.contributorIds,[...new Set(contributors)].sort()))
  }
  for(const report of [...r.worksheets.flatMap(w=>w.reports),...r.population.reports]){const snapshot=parseM77Json(report.snapshotJson,M77_MAX_RESPONSE_BYTES) as unknown as M77ReportSnapshot;const exact=allVersions.find(v=>v.id===snapshot.version.id);check(exact&&equal({...exact,review:null},snapshot.version));verifyCapturedReview(snapshot.review,exact!,report.createdAt,snapshot.reconciliation?.dependencySha256??null);for(const proof of snapshot.proof?.workpaperVersions??[]){const authoritative=allVersions.find(v=>v.id===proof.id);check(authoritative&&equal({...authoritative,review:null},{...proof,review:null}));verifyCapturedReview(proof.review,authoritative!,report.createdAt,null)}}
  const heads=r.worksheets.map(w=>w.versions[w.versions.length-1]),pop=r.population.versions[r.population.versions.length-1]??null;const expected=await derive(h=>deriveM77Reconciliation(companyId,r.coverageVersion,heads,pop,pop?.review?[pop.review]:[],h));check(equal(expected,r.reconciliation));return r
}catch{return fail()}}
const path=(family:M77Family)=>family==='source'?'fugitive-sources':'fugitive-population'
async function request(actor:HostedWorkspaceActor,companyId:string,family:M77Family,suffix:string,payload?:unknown){uuid(companyId);actor.signal?.throwIfAborted();check(actor.accessToken&&!/[\r\n]/.test(actor.accessToken));const response=await fetch(`/workspace-api/workspace/${companyId}/${path(family)}${suffix}`,{method:payload===undefined?'GET':'POST',headers:{authorization:`Bearer ${actor.accessToken}`,...(payload===undefined?{}:{'content-type':'application/json'})},body:payload===undefined?undefined:JSON.stringify(payload),signal:actor.signal,cache:'no-store'});actor.signal?.throwIfAborted();if(response.status===401||response.status===403){actor.onUnauthorized?.();throw new Error('Your access changed. Sign in again to continue.')}if(!response.ok)throw new Error(response.status===409?'The source, equipment or evidence changed. Refresh before continuing.':response.status===422?'Check the equipment, complete evidence references, supported gas, quantities and required review explanations. Nothing was accepted.':'Fugitive-source records are unavailable. Refresh before continuing.');const text=await response.text();actor.signal?.throwIfAborted();check(new TextEncoder().encode(text).length<=M77_MAX_RESPONSE_BYTES);return text}
export async function fugitiveRegisterRequest(a:HostedWorkspaceActor,c:string){return decodeFugitiveRegister(parseM77Json(await request(a,c,'source',''),M77_MAX_RESPONSE_BYTES),c)}
export async function fugitiveSaveRequest(a:HostedWorkspaceActor,c:string,f:M77Family,s:string|null,input:unknown){return decodeFugitiveVersion(parseM77Json(await request(a,c,f,s?`/${uuid(s)}/versions`:'',input),M77_MAX_RESPONSE_BYTES),c)}
export async function fugitiveReviewRequest(a:HostedWorkspaceActor,c:string,f:M77Family,s:string,input:M77ReviewInput){const raw=parseM77Json(await request(a,c,f,`/${uuid(s)}/reviews`,input),M77_MAX_RESPONSE_BYTES);const v=await decodeFugitiveVersion(parseM77Json(await request(a,c,f,`/${uuid(s)}/versions/${uuid(input.versionId)}`),M77_MAX_RESPONSE_BYTES),c);const review=await decodeReview(raw,v);check(review&&review.versionId===input.versionId&&review.versionSha256===input.expectedVersionSha256&&review.decision===input.decision&&review.note===input.note&&review.dependencies?.dependencySha256===(input.expectedDependencySha256??undefined)&&equal(v.review,review));return review!}
export async function fugitiveReportRequest(a:HostedWorkspaceActor,c:string,f:M77Family,s:string,input:M77ReportInput){const report=await decodeFugitiveReport(parseM77Json(await request(a,c,f,`/${uuid(s)}/reports`,input),M77_MAX_RESPONSE_BYTES),c);await verifyRetainedReport(a,c,report);return report}
export async function fugitiveReportDownload(a:HostedWorkspaceActor,c:string,r:M77Report){await verifyRetainedReport(a,c,r);const html=await request(a,c,r.family,`/${uuid(r.streamId)}/reports/${uuid(r.id)}/download`);check(html===r.html&&await coverageSha256(html)===r.htmlSha256);return html}
export async function fugitiveSnapshotDownload(a:HostedWorkspaceActor,c:string,r:M77Report){await verifyRetainedReport(a,c,r);const text=await request(a,c,r.family,`/${uuid(r.streamId)}/reports/${uuid(r.id)}/snapshot`);check(text===r.snapshotJson&&await coverageSha256(text)===r.snapshotSha256);return text}
export async function fugitiveStatementDownload(a:HostedWorkspaceActor,c:string,v:M77Version,id:string){await decodeFugitiveVersion(v,c);const exact=await decodeFugitiveVersion(parseM77Json(await request(a,c,v.family,`/${uuid(v.streamId)}/versions/${uuid(v.id)}`),M77_MAX_RESPONSE_BYTES),c);check(equal({...exact,review:null},{...v,review:null}));const statement=v.statements.find(s=>s.id===id);check(statement);const text=await request(a,c,v.family,`/${uuid(v.streamId)}/statements/${uuid(id)}/download`);check(text===statement!.text&&await coverageSha256(text)===statement!.sha256);return text}

// A self-consistent downloaded object is not proof of an authorized retained record.
async function verifyRetainedReport(a:HostedWorkspaceActor,c:string,r:M77Report){
 await decodeFugitiveReport(r,c)
 const authorized=await decodeFugitiveReport(parseM77Json(await request(a,c,r.family,`/${uuid(r.streamId)}/reports/${uuid(r.id)}`),M77_MAX_RESPONSE_BYTES),c)
 check(equal(r,authorized))
 const snapshot=parseM77Json(r.snapshotJson,M77_MAX_RESPONSE_BYTES) as unknown as M77ReportSnapshot
 const captured=[snapshot.version,...(snapshot.proof?.workpaperVersions??[])]
 for(const v of captured){const exact=await decodeFugitiveVersion(parseM77Json(await request(a,c,v.family,`/${uuid(v.streamId)}/versions/${uuid(v.id)}`),M77_MAX_RESPONSE_BYTES),c);check(equal({...exact,review:null},{...v,review:null}));if(v.id===snapshot.version.id)verifyCapturedReview(snapshot.review,exact,r.createdAt,snapshot.reconciliation?.dependencySha256??null);else verifyCapturedReview(v.review,exact,r.createdAt,null)}
 a.signal?.throwIfAborted()
}

function verifyCapturedReview(captured:M77Review|null,exact:M77Version,createdAt:string,dependencySha:string|null){
 const applicable=exact.family==='source'||exact.review?.dependencies?.dependencySha256===dependencySha
 if(captured)check(applicable&&equal(captured,exact.review)&&captured.reviewedAt<=createdAt)
 else if(applicable&&exact.review)check(exact.review.reviewedAt>=createdAt)
 // Equal-millisecond absence is resolved by the native audit sequence and authorized report GET.
}
